README.md

link was broken due to incorrect casing.
- [x ] I have read the **README** document
- [ x] I have read the **CONTRIBUTING** document
- [ x] My code follows the code style of this project

broken link... looks like it is case sensitive

---

.travis.yml
README.md

Adding Travis-CI builds
#115 
Watching the travis build output to see that it successfully builds and runs the tests

Travis-CI builds

---

CONTRIBUTING.md
README.md

1. Replace the "Getting Started" instructions in `README.md` with a link to `CONTRIBUTING.md`.
2. Add a link to the `good first issue` label from `CONTRIBUTING.md`.
1. `README.md` currently instructs users to install from the marketplace, but the toolkit has not yet been published to the marketplace. For now, users must build and run from source.
2. `CONTRIBUTING.md` currently points users to the `help wanted` label, which is empty. We should point users to *both* 'newcomer' labels: `good first issue` and `help wanted`.

Update instructions for newcomers.

---

CONTRIBUTING.md
README.md
package-lock.json
package.json

1. Add an `npm run package` script that builds a `.vsix` from source.
2. Add instructions to `README.md` explaining how to install this `.vsix`.
Currently, if a user wants to try out the toolkit, they must launch a debugging session from vscode. This might be fine for developers, but is not a good experience for people who just want to try out the toolkit.
#118 
1. Followed the new instructions in the readme to build and install the toolkit. Launch VS Code and sanity-check the toolkit's behavior.
2. Ran `npm run test` to run all existing tests.

Add package script, and add instructions to README.md explaining how to use it to locally install the toolkit.

---

.github/PULL_REQUEST_TEMPLATE.md

Add an "infrastructure" change type to the pull request template.
Recently I've seen (and created) several PRs for infrastructure work. We've been marking them "technical debt", but that isn't really accurate because there isn't any debt to fix, we're just adding additional engineering.

Add 'Infrastructure' change type to PR template.

---

package.json

The [GitHub licensing docs](https://help.github.com/articles/licensing-a-repository/) specify the identifier for the Apache 2.0 license as `apache-2.0`. However, the [official SPDX docs](https://spdx.org/licenses/) specifies the identifier as `Apache-2.0`. With the incorrect casing, `vscode` warns about a bad SPDX identifier every time I run `npm install`.

Fix casing of SPDX license identifier in package.json

---

package-lock.json
package.json
package.nls.json
src/extension.ts
src/lambda/local/debugConfigurationProvider.ts
src/lambda/local/detectLocalLambdas.ts
src/shared/cloudformation/cloudformation.ts
src/shared/codelens/typescriptCodeLensProvider.ts
src/shared/sam/packagers/samPackager.ts
src/shared/templates/sam/samTemplateGenerator.ts
src/shared/typescriptLambdaHandlerSearch.ts
src/test/shared/sam/samPackager.test.ts
src/test/templates/sam/samTemplateGenerator.test.ts
tsconfig.json
types/jszip.d.ts

Seeding the CodeLens feature branch
This is the initial support for #135 and #136

Initial CodeLens Provider

---

README.md

The instructions under 'Method Two: Create a profile using the AWS Tools for PowerShell ' won't work due to the fact that the credentials are encrypted and VSCode can't get to them. This change is just to update the documentation to ~remove Method Two and move Method Three into its place~ provide additional detail for Windows users to write to the shared credentials file.
- [ * ] Documentation (change which modifies or adds documentation, but does not change functionality)
* ~Removed 'Method Two: Create a profile using the AWS Tools for PowerShell' and its bullets~
* Revised `Method Two` to explicitly write to the credentials file on Windows
* ~Renamed 'Method Three: Manually create a profile' to 'Method Two: Manually create a profile'~
VSCode can't access PowerShell credential profiles …

Update README.md to remove PowerShell method

---

src/lambda/explorer/cloudFormationNodes.ts
src/lambda/explorer/defaultRegionNode.ts
src/lambda/explorer/standaloneNodes.ts
src/test/lambda/explorer/cloudFormationNodes.test.ts
src/test/lambda/explorer/standaloneNodes.test.ts

Preparation for upcoming explorer unit tests
Allow tree nodes to be mocked by extracting their interfaces.

Separate tree node interfaces and implementations

---

src/extension.ts
src/lambda/commands/deleteCloudFormation.ts
src/lambda/commands/deleteLambda.ts
src/lambda/explorer/cloudFormationNodes.ts
src/lambda/lambdaTreeDataProvider.ts
src/shared/treeview/awsTreeNodeBase.ts
src/test/lambda/commands/deleteLambda.test.ts
src/test/lambda/explorer/mockCloudFormationNodes.ts
src/test/lambda/explorer/mockStandaloneNodes.ts

Add unit tests for the 'delete' command introduced in #192 and #193.
Add unit tests for the 'delete lambda function' command.
Having tests is good. Not having tests is bad.
#192 
#193

Add unit tests for deleteLambda command.

---

package-lock.json
package.json
src/shared/utilities/childProcess.ts
src/test/utilities/childProcess.test.ts

A recent change caused the `sam build` call from code lenses to fail on windows, when sam.cmd is located in a folder containing a space (eg: `c:\Program Files\...`). This change addresses the issue, and adds a few more checks using spaces in paths (specifically folders) to the tests.

Fix error trying to run SAM CLI on Windows when it is located in a folder containing a space

---

CONTRIBUTING.md
README.md

The toolkit cannot be built using old (pre-6) versions of NPM. This change updates the documentation to reflect this requirement.

Add minimum NPM version to README and CONTRIBUTING.

---

package.json

- [] New feature (non-breaking change which adds functionality)
Added target to enable devlopers to use `npm run install-plugin`
Easier to use an npm target than remember the associated commends.
n/a
Manually tested and used for local devlopment.

Added build target to install aws-toolkit-vscode

---

src/shared/sam/cli/samCliVersion.ts
src/test/shared/sam/cli/samCliVersion.test.ts

* Updated to support SAM CLI up to 0.16
* Extracted cut/paste code to shared function
* Changed `SamCliVersionValidation` to string enum for improved output clarity (e.g. "Expected: Valid, Actual: VersionTooHigh" is more understandable than "Expected: 0, Actual: 3")
Extension did not work with current SAM CLI
Updated test inputs.

Updated max CLI v to 0.16 & made tests DRY

---

package.nls.json
src/lambda/commands/deploySamApplication.ts
src/lambda/lambdaTreeDataProvider.ts

When using command palate to deploy it disappears immediately with no feedback. For large deployments the delay can be many minutes leaving the user wondering if the extension even tried to deploy the SAM app. Now it provides output indicating packaging is occurring, deployment is occurring, then success or failure.

Deployment UX improvements

---

src/lambda/models/samLambdaRuntime.ts
src/lambda/utilities/getMainSourceFile.ts
src/test/lambda/utilities/getMainSourceFile.test.ts

Follow-up to #311 that adds support for Python.
See #311.
See #311
#287
#311
* Added new unit tests
* Ran all new and existing tests
* Manually tested with and without a workspace open in VS Code.

Open the main source code file after new Python SAM app creation

---

src/lambda/commands/createNewSamApp.ts

Fix bug where an error during SAM init doesn't relay the error message

---

build-scripts/clean.js
package.json

npm scripts to clean and recompile
* clean - removes the `out` folder
* recompile - `clean` + `compile`
A clean step is often useful when switching branches, or other situations where src/test files are added and removed. Stale test files can raise errors when run, or cause the experimental instance of VS Code to not close properly at the end of the test run.
I manually delete this folder too often to not have this scripted.

Adding npm scripts for clean and recompile

---

CHANGELOG.md
build-scripts/clean.js

Fixing issue #345.
Syntax error prevented building the package. Made change so that catch is syntactically correct.
I added parentheses and e variable to the catch in the exists function so that it does not produce a syntax error.
#345
- Ran tests ```270 passing (5s)```
- Ran ```npm run package```

Fixed clean.js syntax error.

---

src/lambda/explorer/functionNode.ts
src/lambda/explorer/standaloneNodes.ts
src/test/lambda/commands/deleteLambda.test.ts
src/test/lambda/explorer/mockStandaloneNodes.ts
src/test/lambda/explorer/standaloneNodes.test.ts
src/test/shared/clients/mockClients.ts

Sort the Lambda Function nodes in AWS Explorer, paralleling the CloudFormation stack node sorting.

Sort Lambda Function nodes in AWS Explorer

---

package.nls.json
src/lambda/commands/deploySamApplication.ts
src/shared/sam/cli/samCliBuild.ts

* Added a status bar entry that persists for the duration of a SAM App deploy operation:
* Deploying Sam apps now calls `sam build` prior to package and deploy, so that dependencies are pulled in.
#274 

Deploying Sam App calls sam build, updates statusbar

---

README.md

Add node version to note on build tool requirements in README.md. Also pointed reference to NPM link in note to point to npm.org.
Users building this plugin should have clarification on which version of **Node** to use so they do not encounter errors related to unimplemented or changed language features that are being used to develop the project. Currently it this limitation is specified in the CONTRIBUTING.md but not in the README.md.
Issue #351
Issue #345  
No code changed.
N/A

Added node version to toolkit note.

---

src/shared/utilities/vsCodeUtils.ts
src/test/shared/utilities/vsCodeUtils.test.ts

Enable access to underlying outputChannel and logger from `ChannelLogger`
Enable showing/hiding of output channel
Existing tests pass.

Added channel and logger props to ChannelLogger

---

src/shared/filesystem.ts
src/test/shared/filesystem.test.ts

Added delete support to our `fs` wrapper by exporting a promisified `rename` and `unlink`
Needed to be able to delete a file for an upcoming PR
Added test

Added promisified rename & unlink

---

CHANGELOG.md
package.json

Changes to prepare our extension for display in Marketplace
* Changelog file is rendered as a "tab" in marketplace, so I've cleared it. https://github.com/aws/aws-toolkit-vscode/issues/381 was created to create the changelog management pipeline
* Added a Bugs url to github issues list
* Set gallery Banner to Amazon coloring
* Added categories and keywords
* marked as Preview (until we GA)
* Disabled the Marketplace Q&A, instead providing a link to github issues list
Reference Docs:
* https://code.visualstudio.com/api/working-with-extensions/publishing-extension#marketplace-integration
* https://code.visualstudio.com/api/references/extension-manifest#fields
* https://code.visualstudio.com/api/references/extension-manifest#marketplace-presentation-tips
By submitting this pull request, I …

Changes to prepare our extension for display in Marketplace

---

resources/marketplace/extension-page.md

Added a README-style page for this extension.
Added a README-style page for both the extension's home in the Visual Studio Code Marketplace as well as after users load the extension into VS Code.
Helps customers use this extension without necessarily going to the full documentation elsewhere online.
None.
Viewed the HTML version of the Markdown on GitHub, and tested all of the links.
None.

Added Marketplace extension page.

---

package.nls.json
src/lambda/config/templates.ts
src/lambda/local/configureLocalLambda.ts
src/shared/codelens/codeLensUtils.ts
src/shared/codelens/localLambdaRunner.ts
src/shared/utilities/pathUtils.ts
src/shared/utilities/textDocumentUtilities.ts
src/test/lambda/config/templates.test.ts
src/test/shared/utilities/pathUtils.test.ts

* handlers.json contained lambda handler specific configurations, indexed by "handler name" (eg: app.lambdahandler)
* templates.json contains template related configurations that span the workspace
It made more sense to fold both configurations together, and use a single configuration file. This change no longer uses handlers.json, instead configuration is now in templates.json in this manner:
Example:
```json
{
"templates": {
"processors/app.json": {
"handlers": {
"app.lambda_handler": {
"event": {},
"environmentVariables": {
"MAX_TIMEOUT_MS": 30000
}
}
},
"parameterOverrides": {
"DB_TABLE_NAME": "records"
}
}
}
}
```
#369 
* Ran Tests
* Added Tests
* Used Run/Debug/Configure CodeLenses on a js file, with different combinations of templates.json file contents …

Breaking Change: handler configs moving from handlers.json to templates.json

---

buildspec/release.yml

From https://code.visualstudio.com/api/working-with-extensions/publishing-extension#marketplace-integration: 
> A README.md file at the root of your extension will be used to populate the extension's Marketplace page's contents.
When the release script runs, it will now copy `resources/marketplace/extension-page.md` over top of README.md prior to creating the vsix file, so that we have the right page in the extension.
#277 
* Ran a non-production build against this branch
* Loaded the generated vsix into my VS Code instance
* Looked at the "Installed Extension" listing:

The release script substitutes README.md with the extension page when producing the VSIX file

---

src/schemas/templates.json

As a follow up to #387 this change adds schema definitions for the handlers portion of the `templates.json` json schema.

Added Json Schema definitions and descriptions for lambda handlers

---

src/shared/codelens/pythonCodeLensProvider.ts

Showing feedback at the start of Python run/debug sessions, so the user knows some processing is happening (sam build) before their session starts up.

Added channel logger to the start of local Python run/debug sessions

---

src/shared/codelens/localLambdaRunner.ts

Wait for debug port to open before proceeding to connect to it with a debugger.
Another commit removed this, re-adding it in this PR.

Wait for debug port before attaching debugger (Python)

---

src/extension.ts
src/shared/codelens/codeLensUtils.ts
src/shared/codelens/localLambdaRunner.ts
src/shared/codelens/pythonCodeLensProvider.ts
src/shared/codelens/typescriptCodeLensProvider.ts

Adding metrics to capture the debugger attach success/failure results.

Metrics for debugger attach results

---

src/shared/telemetry/telemetryUtils.ts

`getTime` returns millis since epoch. 
`getMilliseconds` returns the milliseconds component of Date, not elapsed/total milliseconds.

Fix duration calculation

---

src/shared/codelens/pythonCodeLensProvider.ts

Improve the perf (by only inspecting the first character instead of the entire path) and readbility (by simplifying the implementation) of drive letter coercion to upper case on Windows.

Minor: Improve readbility/perf of drive letter case coercion

---

README.md

SAM CLI requires a default region to work. This documents that.
Workaround for https://github.com/aws/aws-toolkit-vscode/issues/416
https://github.com/aws/aws-toolkit-vscode/issues/416
N/A

Correcting readme instructions--adding mention that a default region is necessary

---

package-lock.json
package.json
src/extension.ts

Setting to version 0.1.0

---

src/test/shared/sam/cli/samCliBuild.test.ts

Test did not have same validation logic as other tests.
Test did not correctly validate that the arg and arg value were correlated.

Updated test to use same validation logic as other tests

---

.vscode/extensions.json

Currently, we recommend a single (deprecated) extension. This change replaces it with the non-deprecated successor, and adds several other recommendations.
When a contributor opens our repository in VS Code, it prompts them to install recommended extensions listed in `.vscode/extensions.json`.

Update list of recommended extensions.

---

src/shared/codelens/pythonCodeLensProvider.ts

Added missing line flushes to the python debug wrapper

Tidy up debug wrapper output

---

package.nls.json
src/shared/codelens/typescriptCodeLensProvider.ts

Users see an error message when clicking the Debug codeLens if their lambda handler is determined to be Node 4.3 or Node 6.10
The Debug CodeLens would have been disabled ideally, but this would require loading data from the template file, further delaying the CodeLenses from appearing.

Disabling debug support for node4, 6.10

---

CHANGELOG.md
extension-readme.md
package-lock.json
package.json

Preparing the Release branch:
* Updated changelog
* Updated version
* Added info to the extension page about requiring a Python extension

Prep for 0.2.0

---

designs/modify-resources-attached-to-code-pipeline.md

This is the design for how the Toolkit can work with resources that are associated with pipelines. The initial draft has been based on internal discussions, and the Jetbrains Toolkit implementation.
Design: #487 and #500
Design for: #486 and #501 

Design for operations against resources attached to code pipelines

---

CHANGELOG.md
package-lock.json
package.json
src/shared/sam/cli/samCliVersionValidator.ts

* Bump maximum supported SAM CLI version.
* Bump toolkit version to 0.1.2.
* Port fix for `npm audit` issues from mainline.
Our current supported version range for SAM CLI is `[0.11.0, 0.16.0)`. The next release of SAM CLI will be version `0.16.0`, and there will be no backwards compatibility breaks prior to `0.23.0`.

Prepare for release 0.1.2.

---

package.json

Commit f9816c156 introduced an issue that removed all of the Context menu items from the AWS Explorer. This is a fix.

Fixes issue introduced in f9816c156 that caused the AWS Explorer context menu to disappear

---

.vscode/tasks.json
package.json

Allows us to run a lint-fix pass on demand from within VS Code.

Added vs code task to run lint fixer

---

CHANGELOG.md
package.nls.json
src/extension.ts
src/lambda/commands/createNewSamApp.ts
src/lambda/lambdaTreeDataProvider.ts
src/lambda/wizards/samInitWizard.ts
src/shared/sam/cli/defaultValidatingSamCliProcessInvoker.ts
src/shared/sam/cli/samCliContext.ts
src/shared/sam/cli/samCliInit.ts
src/shared/sam/cli/samCliValidationUtils.ts
src/shared/telemetry/telemetryEvent.ts
src/shared/telemetry/telemetryUtils.ts
src/test/lambda/lambdaTreeDataProvider.test.ts
src/test/shared/sam/cli/samCliBuild.test.ts
src/test/shared/sam/cli/samCliInfo.test.ts
src/test/shared/sam/cli/samCliInit.test.ts
src/test/shared/sam/cli/testSamCliProcessInvoker.ts
src/test/shared/telemetry/telemetryUtils.test.ts

When entering the "Create new SAM Application" workflow, the toolkit now checks for a valid SAM CLI version before prompting the user for inputs. If a valid install is not found, the user sees a notification message.
#526 
* Tried to create a new SAM Application in the following situations:
* Adjusted code to think SAM CLI was not installed
* Adjusted code to think minimum version was higher than my installed version
* Adjusted code to think maximum version was lower than my installed version

SAM CLI Validation at the start of Create New SAM App flow

---

CHANGELOG.md
package.nls.json
src/lambda/commands/deploySamApplication.ts
src/lambda/lambdaTreeDataProvider.ts

* Workflow improvement
When entering the "Deploy SAM Application" workflow, the toolkit now checks for a valid SAM CLI version before prompting the user for inputs. If a valid install is not found, the user sees a notification message.
#527 
* ran existing tests
* Adjusted code to think maximum version was lower than my installed version and tried to deploy

SAM CLI Validation at the start of Deploy SAM App flow

---

src/lambda/commands/deploySamApplication.ts
src/shared/sam/cli/samCliDeploy.ts
src/test/shared/sam/cli/samCliDeploy.test.ts
src/test/shared/sam/cli/samCliLocalInvoke.test.ts
src/test/shared/sam/cli/samCliTestUtils.ts

Improving the code that calls `sam deploy`. This change will be used in a follow up PR to further improve the sam deploy workflow code.

Code Improvement: sam deploy calls

---

src/lambda/commands/deploySamApplication.ts
src/shared/sam/cli/samCliPackage.ts
src/test/shared/sam/cli/samCliPackage.test.ts

Improving the code that calls `sam package`. This change will be used in a follow up PR to further improve the sam deploy workflow code.

Code Improvement: sam package calls

---

src/lambda/commands/deploySamApplication.ts
src/lambda/lambdaTreeDataProvider.ts
src/lambda/wizards/samDeployWizard.ts
src/lambda/wizards/samInitWizard.ts
src/shared/constants.ts
src/shared/ui/buttons.ts
src/test/lambda/commands/deploySamApplication.test.ts
src/test/lambda/wizards/samInitWizard.test.ts

Added help buttons to the Deploy SAM Application workflow
Users can quickly find help while in the middle of a workflow.
https://github.com/aws/aws-toolkit-vscode/issues/529
Local testing and fixed existing tests.

Adding help buttons to deploy workflow

---

CHANGELOG.md
package-lock.json
package.json

* Replace "NEXT" with actual version for next release.
* Fix bullet-point formatting to satisfy linter.
* The placeholder NEXT is no longer needed.
#588
No testing was performed, as only the CHANGELOG was modified.

Update changelog for 0.2.0.

---

CHANGELOG.md

* Add CHANGELOG entry for python support.
* Update Node 10.x changelog entry for consistency with .NET Core and Python.

Add python support to CHANGELOG, update node 10.x support CHANGELOG entry for consistency.

---

src/test/shared/codelens/csharpCodeLensProvider.test.ts
src/test/shared/filesystemUtilities.test.ts

Some of the tests leave temp folders on the system running the tests. This change fixes a few of those tests.

Clean up temp folders from test runs

---

package.nls.json
src/lambda/wizards/samInitWizard.ts

The title currently says "Choose", but this is not a selection-based UI. "Enter" is more appropriate.

Updated the input title from 'Choose' to 'Enter' to more clearly articulate the user operation

---

.changes/next-release/Feature-e740ee91-43ce-4501-a417-e89ab2c72b96.json
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
build-scripts/createRelease.ts
build-scripts/newChange.ts
package-lock.json
package.json

Port over programmatic changelog changes from jetbrains. 
Additionally, edit contributing to have steps on how to use the script.
This should not be merged yet, but all the changes are in it.

Port over programmatic changelog script

---

package-lock.json
package.json

Updating package references (and removing unused vscode-nls-dev reference) to address dependency vulnerability warnings.

Update package references

---

package-lock.json
package.json

Update package reference to remove audit warning

---

.changes/next-release/Feature-aa6cc4c2-cf32-447f-8233-41e54f5bec3b.json
src/shared/sam/cli/samCliValidator.ts

Increase SAM CLI maximum version to 0.30 exclusive

---

CHANGELOG.md

Delete the header from the changelog

Delete the header from the changelog

---

buildspec/bumpVersion.yml

Release process will now automate the changelog file updates.

Create changelog when bumping version

---

src/test/shared/utilities/promiseutilities.test.ts

Removed sleep from promiseutilities test, reduced time to run from ~500ms to ~100ms

Removed sleep from promiseutilities test

---

src/shared/sam/activation.ts
src/shared/sam/cli/samCliContext.ts
src/shared/sam/cli/samCliInvoker.ts

Removing some code that needlessly passed a logger through a bunch of calls.
* Ran SAM related commands and checked that logs emit as they have been

Removing unnecessary code that passes a logger object around

---

.changes/next-release/Feature-9aab7d6c-d0f3-420c-8f03-a543a276773a.json
package-lock.json
src/integrationTest/sam.test.ts
src/lambda/commands/createNewSamApp.ts
src/lambda/models/samLambdaRuntime.ts
src/shared/sam/cli/samCliInit.ts
src/test/shared/sam/cli/samCliInit.test.ts

Added --app-template and --dependency-manager args
Fields are required by SAM CLI 0.30.0+
Existing tests pass

Adding fields to sam init for SAM CLI 0.30.0

---

src/test/shared/sam/cli/samCliInit.test.ts

Added tests for https://github.com/aws/aws-toolkit-vscode/pull/786
Tests are good!
Tests pass

Added missing tests

---

.changes/next-release/Feature-c12d80eb-42e3-47c9-956c-a34fe04a7cff.json
src/shared/sam/cli/samCliValidator.ts

Increase SAM CLI maximum version to 0.40 exclusive

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

- Auto label issues cut from issue templates
- It also auto-formatted with prettier

Auto label issues cut from issue templates

---

buildspec/cloneRepo.yml
buildspec/pushToGithub.yml

Updating builspec to match internal pipeline changes

Updating buildspec

---

src/shared/codelens/localLambdaRunner.ts

Removing one of the duplicate functions in the local lambda code.

Removed duplicate getConfig call

---

buildspec/bumpVersion.yml

Add needed git add to the build pipeline

---

extension-readme.md

Adding "AWS" to the name of the CDK Explorer.
The CDK team asked us to do this for naming consistency.
Verified the content in my fork.

Adjusted the name of the AWS CDK Explorer.

---

buildspec/linuxTests.yml
buildspec/windowsTests.yml

Add codebuild ci scripts to repo

---

.vscode/launch.json
package.json

- Improve the dev experience by adding an extension launch that does not Webpack
- Revert change to the target "extension test" that was made in the Webpack PR

Improve the dev experience by adding an extension launch that does not webpack

---

src/lambda/commands/deploySamApplication.ts
src/shared/sam/activation.ts
src/test/lambda/commands/deploySamApplication.test.ts

Removing unused ExtensionContext from a call chain

---

.changes/next-release/Feature-701535de-b343-4cd4-a627-2d55ddbdd7d9.json

This changelog entry was originally for PR #913.  This PR is only to add the entry into the changelog.

Added entry to change log for PR #913

---

src/credentials/providers/sharedCredentialsProvider.ts
src/eventSchemas/commands/downloadSchemaItemCode.ts
src/shared/filesystemUtilities.ts

This change removes some unnecessary code, as identified by https://lgtm.com/projects/g/aws/aws-toolkit-vscode/alerts/?mode=list

Fix some code quality issues identified by LGTM tool

---

.changes/next-release/Bug Fix-84fc46da-7a4a-48fd-b75e-2462bb6ed446.json

message was missing from my last PR

Add changelog message for 1.6.1

---

.changes/1.6.1.json
.changes/next-release/Bug Fix-84fc46da-7a4a-48fd-b75e-2462bb6ed446.json
CHANGELOG.md
package-lock.json
package.json

Update version to 1.6.1

---

.github/ISSUE_TEMPLATE/guidance_request.md
README.md

Ask for upvotes in README.md :)

doc: feedback

---

.gitignore
.vscode/launch.json
buildspec/buildRelease.yml
buildspec/linuxIntegrationTests.yml
buildspec/linuxTests.yml
buildspec/windowsTests.yml
package-lock.json
package.json
src/test/testRunner.ts
third-party/test/index.ts

Enabling CodeBuild [Test Reports](https://aws.amazon.com/blogs/devops/test-reports-with-aws-codebuild/)
It's annoying having to scroll through 1000s of lines of logs to figure out which tests fail. This also gives us the ability to track tests over time.

Enabling test reporting for all tests

---

.travis.yml
buildspec/linuxTests.yml
buildspec/windowsTests.yml

CI: skip codecov if $CODE_COV_TOKEN is not defined

---

src/awsexplorer/activation.ts
src/cdk/activation.ts
src/eventSchemas/activation.ts
src/extension.ts
src/shared/codelens/codeLensUtils.ts
src/shared/codelens/csharpCodeLensProvider.ts
src/shared/codelens/pythonCodeLensProvider.ts
src/shared/codelens/typescriptCodeLensProvider.ts
src/shared/logger/activation.ts
src/shared/sam/activation.ts

dispose the result of registerCommand()

---

docs/debugging-python-lambda-functions.md

Corrected the path to the activate bash script

---

.vscode/launch.json
third-party/test/index.ts

Restricts the tests to the current opened file
https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables
Easier to run individual tests
Tests were tested

Add config for debugging individual test files

---

.changes/next-release/Feature-fef00a92-bd2d-4d34-887e-b6f32d0cf883.json

Put most/all of the initial Step Function functionality into one changelog entry.

Update initial changelog for Step Functions

---

package-lock.json
package.json

Simple version update
We need the newest version of amazon-states-language-service
Tested it manually

Updates version of asl service to 1.0.0

---

src/stepFunctions/commands/downloadStateMachineDefinition.ts

This change fixes an issue where Windows systems are unable to download state machines.

Fix issue when downloading state machines

---

package-lock.json
package.json

Updates version of amazon-states-language-service. The new version is a minor update fixing small typos in validation helper strings.
Manual

Updates version of asl service to 1.0.1

---

package.nls.json

String update
UX designer requested a string update

Updates the string for previewing sate machines

---

media/css/executeStateMachine.css
src/stepFunctions/commands/executeStateMachine.ts

- Lowering the opacity of the placeholder text to ensure it is clear that it is placeholder text, and not actual input.
- If no input is provided, considering it as undefined instead of an empty string for the state machine execution.
- Makes content on the view clearer.
- Execution input handling matches the Step Functions console. 
- Ran tests in the toolkit, tested manually.

Modifications to Step Functions Execution view

---

src/integrationTest/sam.test.ts
src/lambda/local/debugConfiguration.ts
src/shared/sam/debugger/samDebugSession.ts
src/shared/utilities/pathUtils.ts
src/shared/utilities/workspaceUtils.ts
src/test/fakeExtensionContext.ts
src/test/lambda/local/debugConfiguration.test.ts
third-party/test/index.ts

- fix some failing tests
- fix a deprecation warning for `mocha`
- commit the result of:
```
$ node_modules/run-node/run-node node_modules/prettier/bin-prettier.js --write './src/**'
```
- ~~dep: upgrade husky to 2.7.0~~

lint, fix tests, fix deprecation

---

package-lock.json
package.json

Manually invoke lambdas + load explorer

Update our dependencies

---

package-lock.json
package.json
src/feedback/commands/submitFeedbackListener.ts

Follow up to: https://github.com/aws/aws-toolkit-vscode/pull/962#discussion_r391351602

Add result metric when submitting feedback

---

media/css/executeStateMachine.css

…lder
Placeholder text seemed like a autofill for state machines definition. 
Decreased the opacity of the placeholder.

Decrease the capacity for light theme execution placeholder

---

src/awsexplorer/defaultRegion.ts

This change addresses an issue where the prompt text may be truncated. Moving the text to the title wraps the text.
#247 

Moved the "show hidden default region?" text into title

---

src/shared/codelens/samTemplateCodeLensProvider.ts
src/shared/utilities/pathUtils.ts
src/shared/utilities/workspaceUtils.ts
src/test/shared/codelens/samTemplateCodeLensProvider.test.ts
src/test/shared/utilities/pathUtils.test.ts

samTemplateCodeLensProvider: normalize to full path

---

buildspec/packageTestVsix.yml

- Still need to do the infrastructure side changes but this build worked on my account

Add CI job that will package a VSIX

---

.changes/next-release/Bug Fix-fba170ec-42cc-4f47-8890-30557d088eba.json

Added changelog for #1029

---

package-lock.json
package.json
src/shared/telemetry/defaultTelemetryService.ts

- Bump telemetry version
- Handle another invalid case in the telemetry cache - metadata value cannot be null or empty

Bump telemetry version

---

buildspec/packageTestVsix.yml

Futureproofing the package test. Future changes may affect how the `extension-readme.md` file is produced.

Ensure extension-readme.md is present at package for packaging test

---

third-party/test/index.ts

test: fix "Extension Tests (current file)" task on Windows

---

.changes/next-release/Bug Fix-d4a96aa8-11a0-44ff-8439-2fc0bfffddb5.json
package-lock.json
package.json

I've updated the version of amazon-states-language-service containing bug fixes for the language server functionality. 
#1030 
https://github.com/aws/amazon-states-language-service/issues/17
Manual testing. I checked all the starter templates and one complex state machine. 

Updates version of asl service

---

src/lambda/local/debugConfiguration.ts
src/shared/sam/debugger/awsSamDebugger.ts
src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
src/test/testUtil.ts
src/testFixtures/workspaceFolder/python3.7-plain-sam-app/events/event.json
src/testFixtures/workspaceFolder/python3.7-plain-sam-app/hello_world/app.py
src/testFixtures/workspaceFolder/python3.7-plain-sam-app/hello_world/requirements.txt
src/testFixtures/workspaceFolder/python3.7-plain-sam-app/template.yaml
src/testFixtures/workspaceFolder/python3.7-plain-sam-app/tests/unit/test_handler.py

- add direct coverage of `debugConfiguration.getCodeRoot()`, `debugConfiguration.getHandlerName()`
- test python 3.7
- test invalid template.yaml

SAM debug: more test coverage + edge cases

---

src/lambda/local/debugConfiguration.ts
src/shared/sam/debugger/awsSamDebugger.ts

introduce getRuntimeFamily()

---

src/shared/sam/debugger/samDebugSession.ts

SAM debugconfig: end the session

---

package-lock.json
package.nls.json
src/shared/codelens/localLambdaRunner.ts
src/shared/codelens/pythonCodeLensProvider.ts
src/shared/sam/cli/samCliLocalInvoke.ts
src/shared/sam/debugger/samDebugSession.ts
src/shared/utilities/timeoutUtils.ts
src/test/shared/utilities/timeoutUtils.test.ts

Merge 'master' into feature/debugconfig

Merge 'master' into feature/debugconfig

---

package.nls.json
src/lambda/commands/createNewSamApp.ts
src/lambda/models/samTemplates.ts
src/lambda/wizards/samInitWizard.ts
src/test/lambda/models/samTemplates.test.ts

- Adding the template option for Step Functions quick start template in SAM.
- Expected SAM CLI version is `0.52.0` , so adding a check to ensure that the Step Functions quick start template is not provided as an option for SAM CLI versions lower than that. 
- Modified existing unit test and added a new one.

SAM Step Functions quick start template

---

package-lock.json
package.json
src/s3/commands/createFolder.ts

Add telemetry for S3 CreateFolder

Add telemetry for S3 CreateFolder

---

.gitignore
CONTRIBUTING.md
build-scripts/packageAlpha.ts
media/js/submitFeedbackVue.js
package-lock.json
package.json
package.nls.json
src/extension.ts
src/feedback/templates/feedbackTemplates.ts
src/shared/extensionUtilities.ts
src/shared/extensions.ts
src/shared/utilities/disposableFiles.ts
src/test/fakeExtensionContext.ts
src/test/shared/codelens/localLambdaRunner.test.ts
src/test/shared/utilities/disposableFiles.test.ts

Merge main to feature/debugconfig

---

src/feedback/templates/feedbackTemplates.ts

Fixing feedback comment length text

---

.changes/next-release/Bug Fix-5fefb880-c18d-4d2d-8024-2a635e295d22.json
.changes/next-release/Bug Fix-7011a4f4-309d-42c7-95c6-fd8a9f5df136.json
.changes/next-release/Bug Fix-a128fcc4-26d3-4a49-b680-05489c6b0d24.json
.changes/next-release/Feature-14640c03-b9f6-46b2-8109-3c6bafac99ad.json
package-lock.json
package.json

Updates the version of amazon-states-language-service.
Various small bug fixes and additional validation of JSON Paths within paramaters.
#1165 #1117 #1116
Manual testing, Unit tests within amazon-states-language-service

Updates version of asl service to 1.1.2

---

package.json

Activate extension shortly after VSCode startup
This will allow for faster loading and immediate availability
of language contributions like code lenses and snippets
without affecting VSCode startup time
https://code.visualstudio.com/api/references/activation-events#onStartupFinished

Activate extension shortly after VSCode startup

---

package.nls.json
src/shared/codelens/csharpCodeLensProvider.ts

SAM lambda debug: adjust "dotnetcore3.1" message

---

.changes/next-release/Bug Fix-6d192fb6-debd-4186-b947-8b7901432923.json
package-lock.json
package.json

Update version of asl service. 
https://github.com/aws/aws-toolkit-vscode/issues/1196

Updates version of asl service to  1.1.6

---

designs/modify-resources-attached-to-code-pipeline.md
designs/s3/design-vscode-s3.md
docs/connecting-to-aws.md

Updating documents:
/aws-toolkit-vscode/designs/modify-resources-attached-to-code-pipeline.md
/aws-toolkit-vscode/designs/s3/design-vscode-s3.md
/aws-toolkit-vscode/docs/connecting-to-aws.md

Updating some documents

---

.changes/next-release/Feature-61ff1bf0-e985-4314-968e-8d3fc6be2e95.json

changelog: Launch-config-driven SAM local Lambda debugging

---

src/shared/sam/cli/samCliConfiguration.ts
src/shared/sam/cli/samCliLocator.ts

SAM CLI detection: avoid potential set-event-set-event-… loop

---

.changes/next-release/Feature-9e61513c-3822-4a8a-9ff1-dd4eb31f1227.json
package-lock.json
package.json

Step Functions is launching new features for Amazon States Language, and we are updating the [amazon-states-language-service](https://github.com/aws/amazon-states-language-service) version in the toolkit to enable the new features.
We are releasing the new Amazon States Language features on 8/13, we would like to have the linter in the toolkit for Step Functions to have the new features available.
No related issues.
Ran tests locally on MAC

Upgrade amazon-states-language-service dependency to version 1.4.0

---

.eslintrc.js
src/test/shared/clients/fakeFileStreams.ts

Ban null again

---

CONTRIBUTING.md
docs/TESTPLAN.md

- start documenting test architecture / future plans
- inspired by https://github.com/aws/aws-toolkit-azure-devops/blob/master/docs/TESTPLAN.md

doc: TESTPLAN.md

---

build-scripts/generateServiceClient.ts

Recent JS SDK changed their TS generation logic, which breaks CI builds

Pin SDK client generation to version in package-lock.json

---

buildspec/linuxIntegrationTests.yml

Log into DockerHub for Integration tests so we don't get throttled

---

package-lock.json
package.json
src/apigateway/commands/copyUrl.ts
src/apigateway/commands/invokeRemoteRestApi.ts
src/shared/telemetry/service-2.json

Add telemetry for implemented API Gateway features

---

CONTRIBUTING.md

doc: How to run a single test

---

.vscode/launch.json
package.nls.json
src/integrationTest/shared/codelens/samTemplateCodeLensProvider.test.ts
src/shared/cloudformation/templateSymbolResolver.ts
src/shared/codelens/codeLensUtils.ts
src/shared/codelens/samTemplateCodeLensProvider.ts
src/shared/debug/launchConfiguration.ts
src/shared/sam/debugger/awsSamDebugConfiguration.ts
src/shared/utilities/timeoutUtils.ts
src/shared/utilities/workspaceUtils.ts
src/test/shared/cloudformation/templateSymbolResolver.test.ts
src/test/shared/cloudformation/yaml/template_api_endpoint_configuration.yaml
src/test/shared/cloudformation/yaml/template_api_request_model.yaml
src/test/shared/codelens/samTemplateCodeLensProvider.test.ts
src/test/shared/debug/launchConfiguration.test.ts
src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
src/test/testUtil.ts
src/testFixtures/workspaceFolder/.vscode/launch.json
src/testFixtures/workspaceFolder/python3.7-plain-sam-app/hello_world/app.py
src/testFixtures/workspaceFolder/python3.7-plain-sam-app/template.yaml
test-scripts/integrationTest.ts
test-scripts/test.ts

APIGW: show CodeLens on "Events..Type=Api" in template.yaml

---

.changes/next-release/Feature-1d2c5bab-06bd-4c5e-a795-f18c7fb34912.json
.changes/next-release/Feature-5756814e-3364-40ce-9565-f0d4bba0a325.json
extension-readme.md

…elog entry
Added changelog to summarize new Systems Manager features
Removed old changelog
Small updates to readme

SSM: update changelog entry, readme

---

.changes/next-release/Feature-50a7f7d2-da1c-4eca-b814-7933fee56cbd.json
src/lambda/commands/invokeLambda.ts
src/lambda/templates/lambdaTemplates.ts

fixes issue #663
The change is required, as one could have lambdas with the same name in different AWS regions.
#663 
- [x ] I have read the **README** document
- [ x] I have read the **CONTRIBUTING** document
- [x ] My code follows the code style of this project
- [ x] I have added tests to cover my changes
- [ x] All new and existing tests passed
- [x ] A short description of the change has been added to the changelog using the script `npm run newChange`

UI: "Invoke on AWS": Add Region and ARN

---

.changes/next-release/Bug Fix-d8aabc08-e3f9-44f6-b338-fd390f9101d3.json

ref https://github.com/aws/aws-toolkit-vscode/pull/1242

changelog: mention SAM debugging fix for WSL

---

.changes/next-release/Feature-0cd9b664-2fb0-47d7-a688-f7d457ed0de8.json
package.nls.json
src/shared/sam/debugger/awsSamDebugger.ts

SAM debug: enable debugging for dotnet 3.1 Lambdas

---

src/shared/telemetry/telemetryEvent.ts

Fix reporting metrics as passive/active

---

src/apigateway/activation.ts
src/awsexplorer/regionNode.ts
src/integrationTest/shared/codelens/samTemplateCodeLensProvider.test.ts
src/shared/cloudformation/templateSymbolResolver.ts
src/shared/featureToggle.ts

Re-enable APIGW features on `feature/apigateway` .
This reverts commit 6b4f1f081be3d39029c9c02aba2b6138ea8e3c71.

Revert "APIGW: disable all APIGW features"

---

.changes/next-release/Feature-58dd3336-fb6b-4876-90d5-baf1bf9fad52.json
package.json
src/lambda/explorer/cloudFormationNodes.ts
src/lambda/wizards/samDeployWizard.ts

More UX feedback: icon and positioning for deploy action unclear; moving to context menus. Wording and positioning TBD.
Lambda Node:
CloudFormation Node:
Region Node

Deploy SAM Application moved to context menus

---

src/stepFunctions/commands/visualizeStateMachine/aslVisualization.ts

Added Content-Security-Policy content values.
Added default-src, script-src and style-src values of the meta tag that contains the Content-Security-Policy.
This is a bug fix that prevents an error when attempting to render the webview.

Added default-src rules for SF webview

---

src/shared/extensions.ts
test-scripts/integrationTest.ts

Fix integration tests failing due to missing Jupyter plugin

---

src/test/cdk/detectCdkProjects.test.ts
src/test/cdk/utilities/treeTestUtils.ts

test/cdk: remove redundant util function

---

.changes/next-release/Feature-5da32220-237a-4ec7-9b84-b6952f2e5bae.json
.changes/next-release/Feature-c56b7fa8-7102-4006-afd1-5458cb70c0ef.json
package.json
src/lambda/activation.ts
src/shared/featureToggle.ts

This reverts commit 65b62f04192555a4370be2a54d9534f783df9a50.
Security review passed; ungating feature.

Revert "Gating Lambda features (#1287)"

---

.changes/next-release/Bug Fix-7a3b381b-15e3-4a93-a4e2-e27870f14261.json
src/apigateway/commands/invokeRemoteRestApi.ts
src/lambda/commands/invokeLambda.ts
src/stepFunctions/commands/executeStateMachine.ts

- In views it makes sense to do
#1389 
#1257

Retain webview state when changing tabs

---

buildspec/linuxIntegrationTests.yml

Undo temporary changes from  https://github.com/aws/aws-toolkit-vscode/pull/1418

build: undo temporary changes for Lambda Image feature

---

src/shared/sam/cli/samCliLocalInvoke.ts
src/shared/sam/localLambdaRunner.ts

- "sam local start-api" outputs similar "Starting debugger" messages as  "sam local invoke", so we can reuse the `SamCliLocalInvokeInvocation`  logic related to that.
- Fix the `runDebugger` promise so that it returns the  `childProcess.start()` promise rather than an async promise. Else
`.then(() => { timeExpired = false }` does not work (awaiting the  `runDebugger` promise would not await the inner promise).

APIGW: use "cue" system for APIGW too

---

buildspec/linuxIntegrationTests.yml
src/integrationTest/sam.test.ts
src/testFixtures/workspaceFolder/csharp2.1-image-sam-app/src/HelloWorld/Dockerfile
src/testFixtures/workspaceFolder/js-image-sam-app/hello-world/Dockerfile
src/testFixtures/workspaceFolder/python3.7-image-sam-app/hello_world/Dockerfile

test/integ/SAM debug: also test Image Lambdas

---

src/shared/sam/cli/samCliLocalInvoke.ts
src/shared/telemetry/activation.ts

- disable telemetry
- fix presentation of "Command stopped" message

c9 telemetry

---

src/integrationTest/stepFunctions/visualizeStateMachine.test.ts

Fixes https://github.com/aws/aws-toolkit-vscode/issues/1441

Removing integration test criteria due to Insiders divergence

---

src/testFixtures/workspaceFolder/js-image-sam-app/hello-world/app.js
src/testFixtures/workspaceFolder/js-image-sam-app/hello-world/package.json

ref https://github.com/aws/aws-sam-cli-app-templates/pull/80

test: update test fixture package.json

---

src/test/shared/codelens/codeLensUtils.test.ts

This tests the logic of the picklist for the Add Debug Config codelens.

Added test for picklist associated with the Add Debug Config codelens

---

.github/workflows/node.js.yml

CI: Windows github action

---

package.json
package.nls.json
src/cdk/activation.ts

…Create New Issue
Added the 'Submit Quick Feedback' option to the CDK explorer menu.  Replaced the 'Provide Feedback' option with the 'Create a New Issue on GitHub' option.
The 'Provide Feedback' menu option in the CDK menu brought the user to open a new issue on GitHub, which is the same action as 'Create a New Issue on GitHub' found in the AWS explorer menu.  Adding the Quick Feedback feature gives the user the option to either leave a short opinion or report an issue/suggest a feature.  

Add Submit Quick Feedback command to CDK menu

---

package.nls.json
src/lambda/commands/deploySamApplication.ts

Toolkit provides a message if a build fails during deployment and the package operation is attempted
Provides a bit more transparency to users not looking at the output channel

Toolkit provides feedback when packaging without a successful build

---

.github/workflows/node.js.yml

CI: Add test matrix to GitHub actions workflows

---

src/shared/telemetry/activation.ts

Reverts commit 9aec3319cf37862e004de868301d7c0630bd5cfa.

cloud9: re-enable telemetry

---

buildspec/linuxIntegrationTests.yml

https://github.com/yarnpkg/yarn/issues/7866
https://github.com/aws/aws-toolkit-jetbrains/pull/2414

CI: workaround invalid yarn key

---

src/integrationTest/sam.test.ts

Not needed since https://github.com/aws/aws-sam-cli-app-templates/pull/82
This reverts commit 8902746177ad5eb19e05bd003ae92b3846ce8529.

Revert "CI: fix python2.7 setup #1478"

---

README.quickstart.cloud9.md
README.quickstart.vscode.md

Quickstart upkeep: list the correct runtimes.

doc: Extension readmes list current runtimes

---

src/integrationTest/sam.test.ts

test/integ: nodejs14.x

---

src/extension.ts
src/lambda/activation.ts
src/lambda/vue/samInvoke.ts
src/lambda/vue/samInvokeVue.ts
src/shared/debug/launchConfiguration.ts

Bryceito experiment/vue apis

---

src/lambda/vue/samInvoke.ts
src/webviews/main.ts

more incremental changes, syncing at end of day

Bryceito experiment/more apis

---

media/css/samInvokeForm.css
src/lambda/vue/DONOTUSE.vue
src/lambda/vue/samInvoke.ts
src/lambda/vue/samInvokeVue.ts
src/webviews/main.ts

Vue webview updates

---

.changes/next-release/Bug Fix-e1e87ed3-4067-47a9-a98b-bd27ded82d4f.json

Changelog for #1520

---

CONTRIBUTING.md

doc: CONTRIBUTING.md

---

README.md
src/integrationTest/sam.test.ts

Test CI
related upstream fixes for python2.7 issue:
- https://github.com/aws/aws-sam-cli-app-templates/pull/91
- https://github.com/aws/aws-sam-cli/pull/2695

test PR for integ failures, python2.7 issue

---

.changes/next-release/Feature-53534920-234b-4f17-829b-ccec7ab8feaf.json
package.nls.json

Renaming "Create New SAM Application" -> "Create Lambda SAM Application"
Multiple instances of feedback stating that it was too difficult to figure out how to get started with Lambda. Feedback amplified with the introduction of Cloud9 users (legacy Cloud9 used "Create Lambda" as their entrypoint for a SAM-based Lambda starter template)

SAM: rename "Create New SAM App" command

---

README.quickstart.cloud9.md
README.quickstart.vscode.md

Also update command name #1549

doc: mention ECR in marketplace page

---

src/shared/sam/cli/samCliLocalInvoke.ts
src/shared/telemetry/activation.ts
src/test/shared/sam/debugger/samDebugConfigProvider.test.ts

- Merge `feature/cloud9` to main branch.
- After this the `cloud9` branch can be deleted.

Merge feature/cloud9

---

src/shared/telemetry/defaultTelemetryService.ts

log telemetry at "debug" level

---

package-lock.json

build: update dependencies

---

.github/PULL_REQUEST_TEMPLATE.md

Reduce friction of contributing, by removing boilerplate that is rarely
useful to maintainers.

PULL_REQUEST_TEMPLATE.md: reduce boilerplate

---

.changes/next-release/Feature-445e6d5d-712a-4f0d-ba2e-5678c0df8e7e.json
README.quickstart.vscode.md

Final changes for Java update: Quickstart and changelog entry.

Changelog and quickstart updates for Java

---

package-lock.json
package.json

For "nodejs14.x" runtime name.
https://github.com/aws/aws-toolkit-common/pull/109

build: update telemetry package

---

.eslintignore
src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
src/testFixtures/workspaceFolder/ts-plain-sam-app/package.json
src/testFixtures/workspaceFolder/ts-plain-sam-app/src/app.ts
src/testFixtures/workspaceFolder/ts-plain-sam-app/template.yaml
src/testFixtures/workspaceFolder/ts-plain-sam-app/tsconfig.json
webpack.config.js

Need testing for TypeScript support changes.
Add more tests surrounding the changes added for TypeScript support.

SAM: TypeScript - Testing for Typescript support

---

src/integrationTest/sam.test.ts

test/integ: SAM "F5 debugging" with target=api

---

.changes/next-release/Feature-be42345d-b617-42bd-9bf0-d41113a6d72d.json
README.quickstart.vscode.md

Update the docs and add new change. ~~I put 'Go (1.14, 1.15, 1.16)' instead of 'Go (1.x)' since 'Go1.x' is pretty misleading.~~

docs: update quickstart and add new change

---

.github/dependabot.yml

CI: dependabot.yml

---

src/lambda/vue/samInvoke.ts

Invoker UI in Cloud9 couldn't invoke SAM functions
Cloud9 cannot resolve the `aws-sam` launch config directly via VS Code API. Resolve and invoke manually.
* This won't work with the `${workspaceFolder}` variable but Cloud9 doesn't have support and we don't add it automatically (like we do with VS Code).

Invoker UI skips full debug resolution in Cloud9

---

src/shared/utilities/messages.ts

Cloud9 does not fully support progress notifications
Change the progress location to the window status bar for Cloud9

UX: no progress notification on Cloud9

---

src/webviews/main.ts

Cloud9 opens webview panes into the bottom pane and cannot persist state
* Open webview to panel 2. Panel 2 appears to always be on the top row.
* Persist context for webview instead of relying on state functions. Does not work if dragging to a new pane.

Cloud9 webview contingencies

---

src/lambda/local/debugConfiguration.ts
src/shared/codelens/goCodeLensProvider.ts
src/shared/sam/debugger/goSamDebug.ts
src/test/shared/sam/debugger/samDebugConfigProvider.test.ts

Removed some unused code and added a block comment describing how Go debugging works in the context of SAM CLI

SAM: Go clean-up + comments

---

README.quickstart.vscode.md

Keep documentation up to date with new feature.
Add TypeScript to list of supported languages in the README quickstart page.

Doc: README: Update supported local debugging runtimes

---

package-lock.json
package.json

Dependabot is not smart enough to know that this fixes the security issue.

build(deps): bump vsce from 1.88.0 to 1.93.0

---

docs/CODE_GUIDELINES.md
src/lambda/local/debugConfiguration.ts
src/shared/sam/debugger/pythonSamDebug.ts

doc: various guidelines

---

.husky/pre-commit
package.json

This _actually_ fixes Husky.
Apparently you can't use `package.json` at all anymore for hooks.

Husky real fix

---

.vscode/settings.json

code: use relative import paths by default

---

.eslintignore
README.quickstart.vscode.md
package.nls.json
src/lambda/commands/createNewSamApp.ts
src/lambda/models/samTemplates.ts
src/shared/codelens/codeLensUtils.ts
src/shared/codelens/typescriptCodeLensProvider.ts
src/shared/filesystemUtilities.ts
src/shared/sam/activation.ts
src/shared/sam/debugger/typescriptSamDebug.ts
src/test/lambda/commands/createNewSamApp.test.ts
src/test/lambda/models/samTemplates.test.ts
src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
src/testFixtures/workspaceFolder/ts-plain-sam-app/package.json
src/testFixtures/workspaceFolder/ts-plain-sam-app/src/app.ts
src/testFixtures/workspaceFolder/ts-plain-sam-app/template.yaml
src/testFixtures/workspaceFolder/ts-plain-sam-app/tsconfig.json
webpack.config.js

Cannot locally run or debug SAM Lambda projects written in TypeScript.
Related:
- https://github.com/aws/aws-toolkit-vscode/issues/1453
- https://github.com/aws/aws-toolkit-vscode/issues/1487
Add support for TypeScript to the Toolkit.

Merge feature/typescript

---

src/test/globalSetup.test.ts
src/test/lambda/models/samTemplates.test.ts
src/test/shared/sam/cli/samCliInit.test.ts

Module exports were being assigned on file load causing race conditions. Assign them on test start instead.

test: fix lazy loaded strings

---

.changes/next-release/Feature-94f07709-1755-4a0c-bfaa-0775976d18ac.json

App Runner: add changelog entry

---

resources/markdown/samReadme.md

Toolkit readme issues
* Missing curly brace
* Potentially not openable in Cloud9
* Add curly brace
* ??? (TODO)

Toolkit Readme fix

---

src/shared/cloudformation/activation.ts

Problem
-------
Writing settings to workspace scope is noisy.
We missed this in ed8f69c4f5509a4ce53822cb676a16020ba76d58 #1896.
Solution
--------
- Write settings to global scope (user home directory).
- Do not writing settings if they already exist.
- Check the result of getConfiguration(), do not assume that it is valid.
ref #1933

SAM/CFN JSON schema: write settings to global (not workspace) scope

---

src/test/apprunner/explorer/apprunnerNode.test.ts

tests: fix flaky App Runner polling test

---

src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
src/testFixtures/workspaceFolder/csharp2.1-image-sam-app/template.yaml
src/testFixtures/workspaceFolder/csharp2.1-plain-sam-app/template.yaml
src/testFixtures/workspaceFolder/go1-image-sam-app/template.yaml
src/testFixtures/workspaceFolder/go1-plain-sam-app/template.yaml
src/testFixtures/workspaceFolder/java11-image-gradle-sam-app/template.yaml
src/testFixtures/workspaceFolder/java11-plain-gradle-sam-app/template.yaml
src/testFixtures/workspaceFolder/java11-plain-maven-sam-app/template.yaml
src/testFixtures/workspaceFolder/js-image-sam-app/template.yaml
src/testFixtures/workspaceFolder/js-manifest-in-root/template.yaml
src/testFixtures/workspaceFolder/python3.7-image-sam-app/template.yaml

The test fixture templates have extraneous and unused propterties.
Remove Outputs and Environment Vars from template files found within `src/testFixtures`

tests: Remove noise from test fixtures

---

buildspec/linuxIntegrationTests.yml

Cleanup files after running tests.

integ: fix ENOSPC

---

build-scripts/generateConfigurationAttributes.ts

It was hard to work with launch config properties while developing the toolkit because the docstrings would be string IDs from `package.nls.json`
Replace string definitions with the actual text.
Before:
After:
TODO: Also write to stderr if a property definition isn't present? Missing string IDs would bubble up to users writing their own launch configs.

Adds proper docstrings to type definition for launch config

---

.changes/next-release/Bug Fix-8ac16f1a-0f39-420d-9662-3966067112b2.json

PR #1990 should have an included a changelog entry for the bug fix.
Add the changelog entry to describe the fix.

changelog: Add changelog entry

---

.changes/next-release/Feature-dc4c945a-d726-44b1-b95d-3dc636333fed.json
media/css/base-cloud9.css
media/css/base.css
package-lock.json
resources/dark/done.svg
resources/dark/expand-less.svg
resources/light/done.svg
resources/light/expand-less.svg
src/lambda/vue/samInvoke.css
src/lambda/vue/samInvokeBackend.ts
src/lambda/vue/samInvokeComponent.vue
src/lambda/vue/samInvokeFrontend.ts
src/webviews/components/settingsPanel.vue
src/webviews/main.ts
third-party/README.md
third-party/resources/from-google-fonts/material-design-icons/LICENSE.txt
third-party/resources/from-google-fonts/material-design-icons/README.md
third-party/resources/from-google-fonts/material-design-icons/expand-less.svg

And for Cloud9 (temporary style sheet):
Not currently able to get any exact matches with the current theme since none of the variables are exposed. Instead I'm applying tints and shades to the background color, which is basically a darker version of the current theme. Because of color composition I'm pretty restricted in how much tinting/shading I can do before the saturation diverges significantly. Since there's only 5 themes this isn't too bad, and it looks 'close enough' on each one. 
The `Additional Fields` (previously a button called 'More Fields') and `Payload` have been moved to collapseable panels. They start pre-collapsed.
Boolean fields are now checkboxes
* Fixed issue where empty payload field would cause an error
Need to check compatibility with different browsers for C9. The …

UI: Lambda invoke style updates

---

README.quickstart.cloud9.md
README.quickstart.vscode.md

docs: mention AppRunner in quickstart

---

src/shared/extensions/yaml.ts

YAML Schemas: better URI logic

---

src/shared/extensions/yaml.ts

URI is returned given our own scheme, we can't use 'file' on it since it won't have the file scheme.

YAML Schemas: use parse not file

---

src/shared/constants.ts

update AWS docs URLs

---

package-lock.json
package.json
src/credentials/sso/ssoAccessTokenProvider.ts
src/integrationTest/cloudformation/templateRegistry.test.ts
src/integrationTest/integrationTestsUtilities.ts
src/integrationTest/sam.test.ts
src/shared/utilities/promiseUtilities.ts
src/shared/utilities/symbolUtilities.ts
src/shared/utilities/timeoutUtils.ts
src/test/shared/utilities/timeoutUtils.test.ts
test-scripts/test.ts

Makes the code a bit easier to read (esp. for someone new to JS) and removes a dependency, albeit a tiny one.

misc: consolidate `sleep` Promises

---

src/lambda/models/samLambdaRuntime.ts
src/lambda/vue/samInvokeBackend.ts
src/lambda/vue/samInvokeFrontend.ts

Small issues I noticed.
Right now this webview is managing state in a difficult-to-follow way (so it's very bug-prone) while also not capturing all possible state.
This will need to be revisited at some point. 
We also have two API payload fields???

SAM run/debug: launch config webview fixes

---

src/shared/sam/localLambdaRunner.ts

SAM run/debug: fix wrong field name

---

src/lambda/vue/samInvokeFrontend.ts

#1995 introduced regression in an attempt to fix a race condition where the backend would send initialization data prior to the event hook being set-up. We can fix it by ignoring the init state if we are storing a saved-state.

SAM run/debug: fix webview state regression

---

src/shared/sam/debugger/awsSamDebugger.ts
src/shared/sam/localLambdaRunner.ts

followup to f5af6fec287a84a421af43bbe8e5933b6024df17 ,  fb5d91597ef9

SAM run/debug: calculate architecture earlier in intake phase

---

CONTRIBUTING.md
docs/CODE_GUIDELINES.md

Missing some important resources in CONTRIBUTING.md
Update CONTRIBUTING.md

docs(CONTRIBUTING.md)

---

package-lock.json

build(deps): bump nth-check

---

src/shared/telemetry/defaultTelemetryClient.ts

CI and test builds send metrics, which is unnecessary and noisy.
Skip telemetry publish in non-production builds.

telemetry: skip in non-production build

---

src/dynamicResources/model/supported_resources.json

Updated resource model including 17 new supported resources.

cloudControl: update resource model

---

src/shared/sam/localLambdaRunner.ts

SAM run/debug: do not stringify the error from got

---

.vscode/launch.json
buildspec/linuxIntegrationTests.yml
src/apprunner/wizards/apprunnerCreateServiceWizard.ts
src/integrationTest/integrationTestsUtilities.ts
src/integrationTest/shared/extensions/git.test.ts
src/shared/extensions/git.ts
src/shared/systemUtilities.ts
src/shared/utilities/collectionUtils.ts
src/test/shared/systemUtilities.test.ts
test-scripts/integrationTest.ts
test-scripts/launchTestUtilities.ts
types/git.d.ts

feat(system, git): more tools, more Git features

---

src/shared/cloudformation/activation.ts
src/shared/sam/activation.ts

Race-condition on start. Would likely predominantly affect slower systems since it's dependent on the file system.

SAM: re-order registry activation

---

src/apprunner/wizards/apprunnerCreateServiceWizard.ts
src/apprunner/wizards/codeRepositoryWizard.ts
src/apprunner/wizards/deploymentButton.ts
src/apprunner/wizards/imageRepositoryWizard.ts
src/shared/constants.ts
src/test/apprunner/wizards/codeRepositoryWizard.test.ts

Help icon "?" on AppRunner `Create Service` wizard, does not go to relevant help.
Set the URL.

fix(apprunner): set docs URL for "Create Service"

---

package-lock.json
package.json
src/test/apprunner/explorer/apprunnerNode.test.ts
src/test/cloudWatchLogs/commands/addLogEvents.test.ts
src/test/credentials/awsCredentialsStatusBarItem.test.ts
src/test/credentials/provider/sharedCredentialsProvider.test.ts
src/test/credentials/provider/ssoAccessTokenProvider.test.ts
src/test/globalSetup.test.ts
src/test/shared/telemetry/defaultTelemetryService.test.ts
src/test/shared/ui/picker.test.ts
src/test/shared/utilities/timeoutUtils.test.ts
src/test/testUtil.ts

Removes the patching code since it's now apart of the actual package.

tests: update `fake-timers` to use new flag

---

src/lambda/commands/createNewSamApp.ts
src/shared/activationReloadState.ts
src/test/shared/activationReloadState.test.ts

telemetry: record arch in "Create SAM App" resume

---

src/dynamicResources/model/supported_resources.json

Updating manifest with newly supported types

---

src/test/shared/utilities/timeoutUtils.test.ts

The upstream fix is pretty easy, though still might take some time.

tests: add skips for flaky `Timeout` tests until fix can be sent upstream

---

.changes/next-release/Bug Fix-8d5524b7-de69-4dee-b8f9-a6490237c739.json
src/shared/extensionUtilities.ts

commands: fix 'About Toolkit' missing newline

---

package.nls.json
src/s3/commands/presignedURL.ts
src/s3/commands/uploadFile.ts
src/ssmDocument/commands/deleteDocument.ts
src/ssmDocument/commands/openDocumentItem.ts
src/ssmDocument/commands/updateDocumentVersion.ts
src/ssmDocument/wizards/publishDocumentWizard.ts
src/test/s3/commands/uploadFile.test.ts

- Presigned URL dialog wording can be improved.
- Various messages are verbose.
- Update presigned URL dialog.
- Remove "Please" in several messages, tighten up their wording, put variable part at end of message.

feat(UX): cleanup messages

---

package-lock.json

Steps performed:
$ rm -rf node_modules
$ npm audit fix

build: update dependencies, esp. "follow-redirects"

---

.changes/next-release/Bug Fix-43b50976-bc5a-4eb9-a6c1-32a2997d88f6.json
package.json
src/stepFunctions/activation.ts
src/stepFunctions/commands/visualizeStateMachine/abstractAslVisualizationManager.ts
src/stepFunctions/commands/visualizeStateMachine/aslVisualizationManager.ts

Step Functions: fix issue with opening graph render from editor

---

build-scripts/generateNonCodeFiles.ts
package-lock.json
package.json

https://github.com/aws/aws-toolkit-vscode/pull/2436

Update marked dependency

---

src/shared/sam/debugger/pythonSamDebug.ts

Ran against `public.ecr.aws/lambda/python:3.6.2022.01.29.04`:

SAM/debug: change Python 3.6 bootstrap file location

---

.changes/next-release/Bug Fix-7118f9a6-0252-4f60-b61d-95251221c864.json

This adds a changelog entry that should have been included for the bug fix in #2441 

Add changelog entry for bug fix in PR2441

---

buildspec/linuxIntegrationTests.yml
src/integrationTest/sam.test.ts
src/integrationTest/shared/codelens/samTemplateCodeLensProvider.test.ts

tests/integ: fix outdated tests

---

package-lock.json

Steps performed:
$ rm -rf node_modules
$ npm audit fix

build: update dependencies, esp. "markdown-it", "nanoid"

---

src/ecs/commands/runCommandInContainer.ts

The task role permission check is conducted first, even if
there are no running tasks.
Run the task role permissions check after the wizard flow.
If no tasks are running, the user will see that message in the picker
and it will exit, avoiding the permissions check.

ECS Exec: check permissions only for running tasks

---

resources/walkthrough/setup-connect.md
resources/walkthrough/setup-region.md

fix(welcome): broken images in walkthrough

---

package-lock.json
package.json
src/dynamicResources/awsResourceManager.ts
src/integrationTest/sam.test.ts
src/integrationTest/shared/codelens/samTemplateCodeLensProvider.test.ts
src/shared/logger/activation.ts
src/shared/logger/winstonToolkitLogger.ts
src/shared/sam/debugger/goSamDebug.ts
src/shared/schemas.ts
src/shared/telemetry/defaultTelemetryService.ts
src/shared/utilities/cliUtils.ts
src/stepFunctions/activation.ts
src/test/awsExplorer/awsExplorer.test.ts
src/test/dynamicResources/awsResourceManager.test.ts
src/test/fake/fakeEnvironmentVariableCollection.ts
src/test/fakeExtensionContext.ts
src/test/globalSetup.test.ts
src/test/shared/codelens/localLambdaRunner.test.ts
src/test/shared/credentials/credentialsProfileMru.test.ts
src/test/shared/defaultAwsContext.test.ts
src/test/shared/extensionUtilities.test.ts
src/test/shared/schemas.test.ts
src/test/shared/telemetry/activation.test.ts
src/test/shared/telemetry/defaultTelemetryService.test.ts
src/test/shared/ui/pickerPrompter.test.ts
src/test/shared/utilities/cliUtils.test.ts
src/test/shared/vscode/window.ts
src/test/ssmDocument/commands/createDocumentFromTemplate.test.ts
src/test/stepFunctions/commands/visualizeStateMachine.test.ts
src/test/stepFunctions/commands/visualizeStateMachineCDK.test.ts

deps: bump minimum vscode to 1.50.1

---

buildspec/linuxIntegrationTests.yml

fix(ci): failing java install

---

docs/cfn-schema-support.md

Currently there is no documentation on how to fix JSON schema issues that occur in this project
This PR adds in additional documentation for aws-toolkit-vscode developers to diagnose incoming JSON schema issues

doc(schema): Add schema-support.md for diagnosing issues with JSON schemas

---

.changes/next-release/Bug Fix-2d0cddd1-d531-4b01-9f38-8883bccb7127.json

We should have a changelog item for all the SAM template.yaml improvements for every version
Adds in a changelog for all the SAM template.yaml improvements made in this version

fix(schema): Add SAM template.yaml improved syntax support to changelog

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/guidance_request.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.quickstart.cloud9.md
README.quickstart.vscode.md
resources/walkthrough/setup-toolchain.md

- update CONTRIBUTING.md
- simplify PR and issue templates
fix #615
ref #2600

docs: cleanup, mention AWS Code Catalog, goformation

---

src/shared/utilities/asyncCollection.ts
src/test/shared/utilities/asyncCollection.test.ts

The types for this util could have better inference.
Make them better and rename a few things

fix(util): update `AsyncCollection` with better types

---

src/shared/clients/s3Client.ts

#2683 failed lookupRegion does not log a failure reason.
Add some visibility.
ref #2683
ref 9d3413701b8a #1806

fix(s3): log failed lookupRegion

---

src/apigateway/commands/copyUrl.ts
src/apprunner/activation.ts
src/awsexplorer/commands/copyArn.ts
src/awsexplorer/commands/copyName.ts
src/dynamicResources/commands/copyIdentifier.ts
src/ecr/commands/copyRepositoryUri.ts
src/ecr/commands/copyTagUri.ts
src/iot/commands/copyEndpoint.ts
src/s3/commands/copyPath.ts
src/s3/commands/presignedURL.ts
src/shared/constants.ts
src/shared/utilities/messages.ts
src/shared/vscode/env.ts
src/test/s3/commands/presignedURL.test.ts

Copy paste, indeed.
copy paste
refactor

refactor(copyurl): remove redundant code

---

src/codewhisperer/commands/basicCommands.ts
src/codewhisperer/commands/invokeRecommendation.ts
src/codewhisperer/service/completionProvider.ts
src/codewhisperer/service/keyStrokeHandler.ts
src/codewhisperer/service/recommendationHandler.ts
src/test/codewhisperer/service/completionProvider.test.ts

CodeWhisperer: Fix bugs for C9 IDE

---

.changes/next-release/Bug Fix-bf3ec7d7-77c8-4efb-88de-14c0697cd8e1.json

fix(codewhisperer): Add change log for PR #2733

---

src/codewhisperer/models/constants.ts
src/codewhisperer/vue/root.vue

This PR is to update the user facing terms of service and prompt message in reference tracker.

fix(codewhisperer): Update messages in ToS and Reference tracker

---

package-lock.json
package.json
src/codewhisperer/commands/startSecurityScan.ts
src/codewhisperer/models/model.ts
src/codewhisperer/util/dependencyGraph/dependencyGraph.ts
src/codewhisperer/util/dependencyGraph/javaDependencyGraph.ts
src/codewhisperer/util/dependencyGraph/pythonDependencyGraph.ts

Add additional fields to security scan telemetry because the telemetry schema has been updated 
similar to https://github.com/aws/aws-toolkit-vscode-staging/pull/545, but need to roll this out first to unblock #2792 

feat(codewhisperer): update security scan telemetry

---

src/codewhisperer/client/service-2.json

Need to update code whisperer api model to include the latest api changes
Update `service-2.json`

feat(codewhisperer): update api model

---

src/test/cdk/detectCdkProjects.test.ts

on Windows CI, sometimes the detectCdkProjects() tests fail:
1) detectCdkProjects
detects deep projects:
AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected
+ undefined
- 'c:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\aws-toolkit-vscode\\vsctkL53wNx\\directory1\\directory2\\cdk.json'
at Context.<anonymous> (d:\a\aws-toolkit-vscode\aws-toolkit-vscode\src\test\cdk\detectCdkProjects.test.ts:77:16)
Check that the test file was written before trying to detect it.

fix(tests): detectCdkProjects sometimes fails

---

package.nls.json

Currently says `Search by log group` but we want something that mirrors the `Search by Date` on changing time range. Also a more specific message would be helpful. 
change the message to `Search by Pattern`. 

cwl: fix hover text to be more specific

---

src/codewhisperer/commands/basicCommands.ts
src/codewhisperer/commands/startSecurityScan.ts
src/codewhisperer/models/constants.ts

Some messages have awkward or verbose wording.
Adjust the messages.

fix(ui): adjust messages

---

src/ecr/commands/createRepository.ts
src/ecr/commands/deleteRepository.ts
src/iot/commands/deleteCert.ts
src/iot/commands/deletePolicy.ts
src/iot/commands/deletePolicyVersion.ts
src/iot/commands/deleteThing.ts
src/iot/commands/detachCert.ts
src/iot/commands/detachPolicy.ts
src/iot/commands/updateCert.ts
src/lambda/commands/deploySamApplication.ts
src/lambda/commands/uploadLambda.ts
src/s3/commands/createFolder.ts
src/s3/commands/deleteBucket.ts
src/s3/commands/deleteFile.ts
src/s3/commands/downloadFileAs.ts
src/ssmDocument/commands/deleteDocument.ts
src/ssmDocument/commands/publishDocument.ts
src/ssmDocument/commands/updateDocumentVersion.ts
src/stepFunctions/commands/publishStateMachine.ts
src/stepFunctions/vue/executeStateMachine/executeStateMachine.ts
src/test/ecr/commands/createRepository.test.ts
src/test/ecr/commands/deleteRepository.test.ts
src/test/iot/commands/deleteCert.test.ts
src/test/iot/commands/deletePolicy.test.ts
src/test/iot/commands/deleteThing.test.ts
src/test/iot/commands/detachCert.test.ts
src/test/iot/commands/detachPolicy.test.ts
src/test/iot/commands/updateCert.test.ts
src/test/s3/commands/createFolder.test.ts
src/test/s3/commands/downloadFileAs.test.ts

fix(ui): avoid noise words in messages

---

package-lock.json
package.json
src/codewhisperer/tracker/codewhispererCodeCoverageTracker.ts
src/test/codewhisperer/tracker/codewhispererCodeCoverageTracker.test.ts

corresponding JB PR: https://github.com/aws/aws-toolkit-jetbrains/pull/3303

bump telemetry version from 1.0.70 to 1.0.72

---

src/dynamicResources/model/supported_resources.json

Update CloudControl resource manifest

---

src/codewhisperer/service/inlineCompletionService.ts
src/codewhisperer/service/recommendationHandler.ts

Pagination logic in CodeWhisperer is unnecessarily complex. See https://github.com/aws/aws-toolkit-vscode/pull/2888#discussion_r973236349
Simplify pagination logic.

refactor(codewhisperer): Simplify pagination 

---

src/credentials/sso/ssoAccessTokenProvider.ts
src/test/credentials/sso/ssoAccessTokenProvider.test.ts

Eager cache eviction drops refresh tokens on potentially recoverable faults
Don't eagerly evict tokens

fix(sso): preserve refresh tokens on service-faults

---

package.json

- max of 5 keywords
- allowed categories ~~are listed at https://code.visualstudio.com/api/references/extension-manifest~~
- the bottom of https://marketplace.visualstudio.com/vscode has a more updated list:

feat: update vscode marketplace tags

---

.changes/next-release/Bug Fix-291dc161-1ef0-4a28-9256-df2d9a5b5542.json
package.json
src/codewhisperer/activation.ts

https://github.com/aws/aws-toolkit-vscode/issues/2939
Only enable keybinding when CodeWhisperer is enabled.

fix(codewhisperer): Update keybinding for suggestion navigation

---

.github/CODEOWNERS

Add CodeWhisperer team as a codeowner to it's directory

---

src/shared/schemas.ts

- Currently, if an error occurs at all during the schema downloading process, all schemas will fail to resolve. E.g. If the cfn schema isn't cached and fails to be downloaded, then an error will be thrown and the sam schema won't attempt to be downloaded
- Treat each schema independently, if one schema errors when downloading then log it but continue processing the other schemas as well. This will allow schemas that are cached or downloaded to still be used in the editor, regardless of whether or not an error occured downloading another schema.

fix(schemas): Increase schema downloading resiliency

---

package-lock.json

build(deps): bump @xmldom/xmldom

---

package.json
src/credentials/auth.ts
src/credentials/sso/clients.ts

No UI to signout
Add a button on the node. This is a placeholder to make development easier and is not the final UI.

feat(auth): add minimal signout button

---

src/test/shared/vscode/testUtils.ts

VSC Insiders now minimizes private field names
Replace the event if the emitter is not found

fix(tests): patch `exposeEmitters`

---

.changes/next-release/Bug Fix-323bebec-e52d-4977-b4b7-31fcbcf37bbf.json
.changes/next-release/Feature-b58057ed-a465-4379-9407-a544d0e4e1a3.json

add change log for CodeWhisperer bug fixes

feat(codewhisperer): add change log for CodeWhisperer bug fixes

---

.changes/next-release/Feature-778c35c9-3c44-40e0-a6b1-4e656c74eadf.json
src/codewhisperer/commands/invokeRecommendation.ts
src/codewhisperer/models/constants.ts
src/codewhisperer/service/inlineCompletionService.ts
src/codewhisperer/service/keyStrokeHandler.ts
src/test/codewhisperer/commands/invokeRecommendation.test.ts
src/test/codewhisperer/service/keyStrokeHandler.test.ts

current auto-trigger heuristics is not very responsive
replacing the character number based triggering rule with an idle time based triggering rule to make the triggering more aggressive

feat(codewhisperer): auto trigger improvements

---

.changes/next-release/Bug Fix-27ad0ba0-7e9d-41c7-ab49-85a3af733e6f.json
.changes/next-release/Bug Fix-ec78c026-4ac2-4f47-9f84-54a984a43b07.json

SAM template.yaml file issues #2924 and #2867 were reported for this repo, but corrections were made in the awslabs/goformation repo.
Add changelogs to show bug fixes.

add changelogs for sam schema support changes

---

src/cloudWatchLogs/document/logDataDocumentProvider.ts

In cloudwatch logs when we search logs and ctrl + click we previously were only able to do this on the timestamp.
Remove the limitation that only allows you to click on the timestamp and instead be able to click anywhere on the line.
Additionally, the whole line gets highlighted upon hover.

feat(cwl): Allow cwl ctrl + click on whole line in an event stream

---

.github/workflows/node.js.yml
buildspec/linuxIntegrationTests.yml
buildspec/linuxTests.yml
buildspec/packageTestVsix.yml
buildspec/windowsTests.yml
package-lock.json
package.json

Reliability improvements such as:
https://github.com/microsoft/vscode-test/commit/d9f5723fbd2c0fba59c072495e9e31fa0039acbf
- requires nodejs 16. 
- need to update codebuild image to `aws/codebuild/standard:6.0` https://github.com/aws/aws-codebuild-docker-images/issues/490#issuecomment-1234439138

deps: update vscode-test

---

buildspec/linuxIntegrationTests.yml
buildspec/linuxTests.yml

codebuild image 6.0 has missing stuff 
figure out what stuff is needed

CI: dependencies

---

buildspec/windowsTests.yml
codecov.yml

Add CodeWhisperer Codecov github check

Add CodeWhisperer Codecov github check

---

src/shared/constants.ts
src/shared/sam/sync.ts

fix(sam): link to "sam sync" documentation

---

src/cloudWatchLogs/registry/logDataRegistry.ts
src/shared/utilities/messages.ts

fix(cwl): less verbose message

---

.github/workflows/node.js.yml
buildspec/windowsTests.yml

fix(tests): coverage information found on head

---

.changes/next-release/Feature-c1e800e4-94d4-433d-a545-d6a32b64c7a3.json
src/shared/awsConsole.ts
src/shared/constants.ts
src/shared/logger/winstonToolkitLogger.ts
src/shared/sam/sync.ts
src/shared/ui/buttons.ts
src/shared/ui/pickerPrompter.ts
src/test/shared/sam/sync.test.ts
src/test/shared/ui/pickerPrompter.test.ts

When trying the "Sync SAM" command, the "No items found" message is confusing.
- Show a more informative message.
- Visit the help page if user hits Enter.
related: #2996

feat(sam): "Sync SAM" shows more info if no template.yaml found

---

src/credentials/sso/model.ts
src/shared/constants.ts
src/shared/sam/cli/samCliDetection.ts
src/shared/sam/cli/samCliValidationNotification.ts
src/shared/sam/sync.ts
src/shared/ui/buttons.ts
src/shared/utilities/vsCodeUtils.ts

Extract openUrl() and use it from common places.

telemetry: "aws_openUrl" for URL click

---

package.json

Updates the VSCode Extension description to mention more info about the supported services.

chore: Update extension description

---

package-lock.json
package.json
src/credentials/sso/clients.ts
src/credentials/sso/ssoAccessTokenProvider.ts
src/shared/telemetry/vscodeTelemetry.json

It's hard to diagnose issues relating to refreshing credentials
Add more logic to improve observability

fix(auth): add extra logging to the OIDC client

---

src/shared/localizedText.ts
src/shared/sam/sync.ts

fix(sam): update version notification wording

---

resources/codecatalyst_connect
resources/codecatalyst_connect.ps1
src/codecatalyst/model.ts
src/codecatalyst/reconnect.ts
src/codecatalyst/tools.ts
src/shared/clients/codecatalystClient.ts
src/shared/extensionUtilities.ts
src/test/codecatalyst/uriHandlers.test.ts

"Dev Environment" is the preferred name.

fix(codecatalyst): "dev environment" wording

---

src/codecatalyst/model.ts

Problem:
openDevEnv() calls getDevEnvironment() even though prepareDevEnvConnection() already has that info.
Solution:
Use the object from prepareDevEnvConnection() and drop the extra call to getDevEnvironment().

perf(codecatalyst): avoid extra service call during connect

---

src/codewhisperer/util/editorContext.ts
src/codewhisperer/util/runtimeLanguageContext.ts
src/test/codewhisperer/util/editorContext.test.ts

Make CW generates code based on the language of each notebook cell

---

src/credentials/vue/ServiceItem.vue
src/credentials/vue/root.vue

- Creates all the buttons on the left side of the page
- Creates a class that manages the state of the buttons
This includes:
- The item that is currently selected by the user
- The status of the item (locked, unlocked)
- Which section the item should be in the view (locked/unlocked section)

auth: Webview Create Clickable Items + State Management

---

src/credentials/auth.ts

fix(codecatalyst): never drop tokens in a dev environment

---

src/codecatalyst/tools.ts
src/shared/errors.ts
src/shared/systemUtilities.ts
src/test/codecatalyst/tools.test.ts

fix(codecatalyst): regression with ssh config

---

scripts/test/launchTestUtilities.ts
src/codecatalyst/tools.ts
src/integrationTest/globalSetup.test.ts
src/shared/extensions.ts
src/test/globalSetup.test.ts
src/test/setupUtil.ts
src/testE2E/codecatalyst/client.test.ts

tests(codecatalyst): improve reporting when tests fail

---

src/shared/telemetry/telemetryLogger.ts

feat(telemetry): log metric names at "verbose" log-level

---

src/cloudWatchLogs/changeLogSearch.ts
src/cloudWatchLogs/cloudWatchLogsUtils.ts
src/cloudWatchLogs/commands/searchLogGroup.ts
src/cloudWatchLogs/commands/viewLogStream.ts
src/shared/telemetry/vscodeTelemetry.json

cwl: record "Search Log Group" telemetry as a flow/span

---

package-lock.json
package.json

deps: update @aws-toolkits/telemetry

---

src/shared/telemetry/vscodeTelemetry.json

cwl: use metric definition from aws-toolkit-common

---

resources/endpoints.json

Problem:
endpoints.json included in the VSIX is old.
Solution:
Update endpoints.json

package: update endpoints.json

---

src/codewhisperer/service/classifierTrigger.ts
src/codewhisperer/service/keyStrokeHandler.ts
src/codewhisperer/util/telemetryHelper.ts

expand classifier trigger A/B to include 4 more languages

feat(codewhisperer): classifier trigger for more languages

---

src/codewhisperer/activation.ts

fix(codewhisperer): classifier threshold

---

.changes/next-release/Bug Fix-185bc9a6-c99a-4c9a-b230-2dd7c90e6162.json
package.json
src/codewhisperer/activation.ts
src/codewhisperer/util/authUtil.ts

fix https://github.com/aws/aws-toolkit-vscode/issues/3490 

fix codewhisperer command not found error when codewhisperer is disabled

---

tsconfig.json

build: forceConsistentCasingInFileNames

---

.changes/next-release/Bug Fix-26d07028-115f-42eb-9723-fd531d320235.json
src/shared/constants.ts
src/shared/sam/activation.ts
src/shared/sam/cli/samCliDetection.ts
src/shared/sam/cli/samCliLocator.ts
src/shared/sam/cli/samCliValidationNotification.ts
src/shared/sam/cli/samCliValidator.ts
src/shared/utilities/messages.ts
src/shared/utilities/vsCodeUtils.ts
src/test/shared/sam/cli/samCliValidationNotification.test.ts

SAM CLI 1.85-1.86 has issues on Windows.
Detect the problem on Windows and show a warning.

fix(sam): SAM CLI 1.85-1.86 fails on Windows

---

buildspec/linuxIntegrationTests.yml
buildspec/linuxTests.yml

ref f53186e443093db89dbf3d4d813915813e3404b6

ci: run-as unprivileged user

---

src/apprunner/wizards/codeRepositoryWizard.ts
src/apprunner/wizards/deploymentButton.ts
src/auth/credentials/utils.ts
src/auth/utils.ts
src/cdk/explorer/rootNode.ts
src/codecatalyst/explorer.ts
src/codewhisperer/activation.ts
src/codewhisperer/commands/basicCommands.ts
src/codewhisperer/commands/startSecurityScan.ts
src/dynamicResources/activation.ts
src/ecs/activation.ts
src/eventSchemas/wizards/schemaCodeDownloadWizard.ts
src/extension.ts
src/lambda/commands/createNewSamApp.ts
src/lambda/models/samLambdaRuntime.ts
src/lambda/wizards/samDeployWizard.ts
src/s3/fileViewerManager.ts
src/shared/awsContextCommands.ts
src/shared/debug/launchConfiguration.ts
src/shared/sam/debugger/awsSamDebugger.ts
src/shared/utilities/cliUtils.ts
src/shared/wizards/multiStepWizard.ts

Capture metrics for generic URLs.

telemetry: aws_openUrl

---

src/auth/ui/vue/serviceItem.vue

fix: auth webview import

---

src/shared/sam/cli/samCliLocator.ts
src/shared/sam/cli/samCliSettings.ts

minor cleanup to remove unnecessary indirection

refactor: remove indirection

---

src/codewhisperer/client/codewhisperer.ts

Make userAgent in the created CW clients

---

src/cloudWatchLogs/activation.ts
src/cloudWatchLogs/commands/searchLogGroup.ts
src/cloudWatchLogs/commands/viewLogStream.ts

cwl: telemetry

---

package.json
src/auth/activation.ts
src/auth/secondaryAuth.ts
src/auth/ui/vue/authForms/manageBuilderId.vue
src/auth/ui/vue/authForms/manageCredentials.vue
src/auth/ui/vue/authForms/manageIdentityCenter.vue
src/auth/ui/vue/authForms/shared.vue
src/auth/ui/vue/authForms/types.ts
src/auth/ui/vue/root.vue
src/auth/ui/vue/serviceItem.vue
src/auth/ui/vue/serviceItemContent/awsExplorerContent.vue
src/auth/ui/vue/serviceItemContent/codeCatalystContent.vue
src/auth/ui/vue/show.ts
src/extension.ts
src/shared/utilities/vsCodeUtils.ts
src/test/shared/utilities/vscodeUtils.test.ts

Various fixes from the bug bash.
See each commit for info on the specific fix
- Changed the mechanism for detecting if user is a first time user or not. See commit `refactor: is first extension use logic`

authWebview: Bug Bash fixes

---

src/auth/sso/model.ts
src/auth/ui/vue/authForms/manageBuilderId.vue
src/auth/ui/vue/authForms/manageCredentials.vue
src/auth/ui/vue/authForms/manageIdentityCenter.vue
src/auth/ui/vue/authForms/sharedAuthForms.css
src/auth/ui/vue/authForms/types.ts
src/auth/ui/vue/root.vue
src/auth/ui/vue/serviceItem.vue
src/auth/ui/vue/serviceItemContent/awsExplorerContent.vue
src/auth/ui/vue/serviceItemContent/baseServiceItemContent.css
src/auth/ui/vue/serviceItemContent/codeCatalystContent.vue
src/auth/ui/vue/serviceItemContent/codeWhispererContent.vue
src/auth/ui/vue/shared.css
src/auth/ui/vue/show.ts
src/test/credentials/sso/ssoAccessTokenProvider.test.ts

Small fixes from the fit and finish
See each commit for info on each

authWebview: Various small fixes

---

src/codewhisperer/models/constants.ts

Increase supplemental context fetch size from 60 -> 3000

feat(codewhisperer): update code chunks size fetched

---

src/auth/ui/vue/root.vue
src/auth/ui/vue/serviceItem.vue

- Updated the text for CloudCatalyst in the webview.
- Needed to readjust the width since the new text is longer.

authWebview: mior fix CC webview text + adjust webview width

---

.changes/next-release/Bug Fix-16b028ca-252d-4bbe-9702-a3566377aa9b.json
src/codewhisperer/util/supplementalContext/crossFileContextUtil.ts
src/codewhisperer/util/supplementalContext/utgUtils.ts

fix(codewhisperer): filter out blank code chunk

---

src/codewhisperer/util/supplementalContext/crossFileContextUtil.ts
src/test/codewhisperer/util/crossFileContextUtil.test.ts
src/test/testUtil.ts

feat(codewhisperer) factor in filedistance when fetching crossfile context

---

.vscode/launch.json
.vscode/tasks.json
CONTRIBUTING.md

- document web-mode development steps
- rearrange launch configs to be more discoverable.

docs: web-mode development steps

---

CONTRIBUTING.md

docs: using new vscode APIs

---

.changes/next-release/Feature-7fd62dd9-139d-489b-ab89-0bd6a4490423.json
src/codewhisperer/util/supplementalContext/utgUtils.ts
src/test/codewhisperer/util/utgUtils.test.ts

java 50% 50%
python 50% 50%
java 100%
python 50% 50%

codewhisperer: dial up java utg support

---

src/auth/ui/vue/root.vue

The "switch connections" call to action can be confusing, so relax it to something more passive.

auth: relax "Switch connections" message

---

.changes/next-release/Feature-64bea307-ef6a-4167-896a-08445ffc0013.json
src/codewhisperer/util/supplementalContext/crossFileContextUtil.ts
src/test/codewhisperer/util/crossFileContextUtil.test.ts

codewhisperer: enable complete .py .js .jsx .ts .tsx crossfile support

---

src/auth/ui/vue/show.ts

remove log message

---

README.md
docs/faq-credentials.md

This will be our new FAQ page for common issues that we can easily update.

doc: create faq page

---

.changes/next-release/Bug Fix-d47847cc-bbb7-4c26-a102-82943152654a.json
src/codewhisperer/util/supplementalContext/codeParsingUtil.ts
src/test/codewhisperer/util/codeParsingUtil.test.ts

- TestMyClass.java
- MyClassTest.java
- TestMyClass.java
- MyClassTest.java
- MyClassTests.java

codewhisperer: patch java test file regex pattern MyClassTests.java

---

.changes/next-release/Bug Fix-3d1f0437-68e9-47ce-b3e6-72f859c6d72f.json
src/codewhisperer/util/supplementalContext/codeParsingUtil.ts

codewhisperer: isTestFile should use normalize filePath

---

src/codewhisperer/util/editorContext.ts
src/codewhisperer/util/supplementalContext/crossFileContextUtil.ts
src/codewhisperer/util/supplementalContext/utgUtils.ts

codewhisperer: add  logs to supplemental context feature

---

src/codewhisperer/service/recommendationHandler.ts

Log messages are missing useful info about the exception:
2023-08-24 17:32:05 [ERROR]: CodeWhisperer Invocation Exception :
2023-08-24 17:32:07 [ERROR]: CodeWhisperer Invocation Exception :
2023-08-24 17:32:09 [ERROR]: CodeWhisperer Invocation Exception :
2023-08-24 17:32:09 [ERROR]: CodeWhisperer Invocation Exception :
Fix the logger call.
**Note:** We are looking at ways to improve the logger to avoid this kind of mistake.

fix(codewhisperer): incomplete log message

---

src/shared/fs/templateRegistry.ts

feat(sam): link to search.exclude setting from message

---

.editorconfig
CONTRIBUTING.md

No onboarding docs for defining telemetry.
Write some docs.

docs: telemetry

---

src/shared/logger/logger.ts

Various bugs in ConsoleLogger, see commits.

fix: ConsoleLogger bugs

---

.changes/next-release/Feature-b29743c8-4740-4e98-a965-204fe972a058.json
src/ecs/util.ts
src/shared/constants.ts

feat(ecs): show more context for missing permissions

---

src/codewhisperer/models/constants.ts
src/codewhisperer/util/supplementalContext/crossFileContextUtil.ts

codewhisperer: revert crossfile 1000 code chunks experiment vs. 60

---

src/codewhisperer/service/recommendationHandler.ts

codewhisperer: fix error type get swllowed

---

.changes/next-release/Feature-0cd31fc0-2e29-4295-83a3-f4cb7eeaa325.json
src/codewhisperer/service/classifierTrigger.ts
src/codewhisperer/service/inlineCompletionService.ts
src/codewhisperer/service/keyStrokeHandler.ts
src/codewhisperer/util/userGroupUtil.ts
src/test/codewhisperer/service/keyStrokeHandler.test.ts

release classifier trigger to 100% for all language, and remove Crossfile experiment

codewhisperer: classifier trigger for 15 langs

---

src/codewhisperer/commands/invokeRecommendation.ts
src/codewhisperer/service/keyStrokeHandler.ts

fix no recommendation in C9 path after the first invocation

codewhisperer: fix for cloud9 path

---

src/codewhisperer/service/recommendationHandler.ts
src/shared/utilities/textUtilities.ts
src/test/shared/utilities/textUtilities.test.ts

codewhisperer "recommendations" logging uses multiple logger calls and the formatting is hard to read.
- Use a single log statement.
- Indent the message parts so that related parts are visually grouped.
2023-09-30 08:57:15 [DEBUG]: Request ID: ecc997a9-518a-47ae-a28b-ebbcd0aba39a,
timestamp(epoch): 1696089435380,
timezone: America/Los_Angeles,
datetime: 30/09/2023, 08:57:15,
vscode version: '1.82.2',
extension version: '1.92.0',
filename: 'samCliInvokerUtils.test.ts',
left context of line:  '...   SAM_CLI_TELEMETRY',
line number: 89,
character location: 34,
latency: 678.2888330221176 ms.
2023-09-30 08:57:15 [VERBOSE]: Recommendations:
2023-09-30 08:57:15 [VERBOSE]: [0]
telemetryEnabled ? '1' : 'x',
AWS_REGION: 'us-east-1',
...(telemetryEnabled ? {} : { SAM_CLI_TELEMETRY: 'x' })
} …

refactor(codewhisperer): recommendations logging

---

.changes/next-release/Feature-93736bc9-dfa0-4698-924d-0f1d8a119c85.json

changelog item

---

src/codewhisperer/activation.ts

This issue was introduced in 1.90.0.  
No change log is needed because there is no customer facing impact of this fix. The 1.90.0 was not deployed to C9 instances.

fix(codewhisperer): fix auto trigger in AWS c9

---

src/codewhisperer/service/keyStrokeHandler.ts
src/codewhisperer/util/userGroupUtil.ts
src/test/codewhisperer/service/keyStrokeHandler.test.ts

rollout token infilling suppression to 100% users

codewhisperer: reduce token infilling suggestions

---

.changes/next-release/Feature-f245a4be-1541-4c3e-8680-2c0a7b10e3fc.json

add changelog for #3944

---

src/codewhisperer/service/securityIssueCodeActionProvider.ts
src/test/codewhisperer/service/securityIssueCodeActionProvider.test.ts

Need a way to open the webview without the mouse
Added additional code action that triggers the webview

feat(codewhisperer): code action to open webview

---

src/codewhisperer/client/codewhisperer.ts
src/codewhisperer/client/user-service-2.json
src/codewhisperer/service/recommendationHandler.ts
src/codewhisperer/util/commonUtil.ts
src/codewhisperer/util/editorContext.ts
src/test/codewhisperer/util/editorContext.test.ts

CodeWhisperer: Add OptOut field to GenerateCompletions API

---

.changes/next-release/Feature-2ea7bfa5-c933-4e58-9381-54c692bfd38a.json

I forgot to add the changelog item, yet again :)

CW status bar changelog item

---

src/codewhisperer/models/model.ts
src/codewhisperer/util/codeWhispererSession.ts
src/codewhisperer/util/editorContext.ts
src/codewhisperer/util/supplementalContext/crossFileContextUtil.ts
src/codewhisperer/util/supplementalContext/supplementalContextUtil.ts
src/codewhisperer/util/supplementalContext/utgUtils.ts
src/codewhisperer/util/telemetryHelper.ts

To avoid circular dependency. Move data class into model file

(refactor codewhisperer): refactor 1, move supplemental context pojos to model file

---

src/codewhisperer/commands/basicCommands.ts
src/test/codewhisperer/explorer/codewhispererChildrenNodes.test.ts

fix casing of command id

---

src/shared/clients/codecatalystClient.ts

fix(codecatalyst): using wrong endpoint

---

package-lock.json
package.json

If the incoming stream is broken especially on code blocks, because of the typewriter animation a javascript error occurs on panel
added a safety check layer on mynah-ui

fix(amazonq): update mynah-ui version to 3.2.9

---

src/amazonqGumby/activation.ts
src/amazonqGumby/entrypoint.ts
src/codewhisperer/commands/startTransformByQ.ts
src/codewhisperer/models/constants.ts
src/codewhisperer/service/transformByQHandler.ts

1. QuickPick which pops up to get user input on what project to transform (rarely) freezes / becomes unresponsive.
2. Missing notification to user when job is partially successful
3. /transform causes the QuickPick for user input to open then close immediately as a result of the fix to problem 1
4. We run a `mvn` command which does not create a directory when there are no dependencies to copy over, leading to a directory not found error
1. Remove the shouldResume: true (make it false)
2. Add notification in this case
3. Sleep for 1s to give chat time to respond with message, then show input dialog pop-up
4. Include check to ensure directory exists before trying to read from it
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

fix(transform): various bug fixes

---

src/codewhispererChat/controllers/chat/telemetryHelper.ts

- mark panel events are passive
- remove result from all events

fix(cwc): mark panel events as passive and remove result

---

package.json

fix: disable CodeCatalyst view in cloud9-classic

---

package.json
src/amazonqGumby/entrypoint.ts
src/codewhisperer/commands/startTransformByQ.ts
src/codewhisperer/models/constants.ts
src/codewhisperer/service/transformByQHandler.ts
src/codewhisperer/service/transformationResultsViewProvider.ts
src/test/amazonqGumby/entrypoint.test.ts
src/test/codewhisperer/commands/transformByQ.test.ts
src/testInteg/amazonqGumby/transformByQ.test.ts
src/testInteg/util/amazonQUtil.ts

We had some duplicate code and other minor cleanups to handle. We wanted more test coverage.
Remove duplicate code and do minor cleanups. Add test cases.

fix/test: improve error handling and add more tests

---

src/amazonqFeatureDev/client/featureDev.ts
src/amazonqFeatureDev/controllers/chat/controller.ts
src/amazonqFeatureDev/session/session.ts
src/shared/telemetry/exemptMetrics.ts
src/test/amazonqFeatureDev/controllers/chat/controller.test.ts
src/test/amazonqFeatureDev/session/session.test.ts
src/test/amazonqFeatureDev/session/sessionState.test.ts
src/test/amazonqFeatureDev/utils.ts

- We have no test coverage for ensuring telemetry events are being sent when an event happens
- Add tests

featureDev: Add tests for ensuring telemetry events are being sent

---

src/codewhisperer/service/recommendationHandler.ts

Missing `result` field on `codewhisperer_perceivedLatency` metric. This was not noticed because of the missing `await` (this will be caught in the future after #1638 is merged).
rejected promise not handled within 1 second: Error: Metric `codewhisperer_perceivedLatency` was emitted without the `result` property. This property is always required. Consider using `.run()` instead of `.emit()`, which will set these properties automatically. See https://github.com/aws/aws-toolkit-vscode/blob/master/docs/telemetry.md#guidelines
stack trace: Error: Metric `codewhisperer_perceivedLatency` was emitted without the `result` property. This property is always required. Consider using `.run()` instead of `.emit()`, which will set these properties automatically. See …

fix(telemetry): metric emitted without "result"

---

src/test/eventSchemas/commands/downloadSchemaItemCode.test.ts

see commits
continues https://github.com/aws/aws-toolkit-vscode/pull/3814

fix(tests): "rejected promise not handled"

---

src/codewhisperer/util/userGroupUtil.ts
src/codewhispererChat/commands/registerCommands.ts
src/codewhispererChat/controllers/chat/controller.ts
src/codewhispererChat/view/messages/messageListener.ts
src/common/browserUtils.ts
src/dev/activation.ts
src/dev/beta.ts
src/dev/codecatalyst.ts
src/dynamicResources/activation.ts
src/dynamicResources/awsResourceManager.ts
src/dynamicResources/commands/copyIdentifier.ts
src/dynamicResources/commands/deleteResource.ts
src/dynamicResources/commands/openResource.ts
src/dynamicResources/commands/saveResource.ts
src/ec2/commands.ts
src/ec2/explorer/ec2ParentNode.ts
src/ecr/commands/createRepository.ts
src/ecr/commands/deleteRepository.ts
src/ecr/commands/deleteTag.ts
src/ecs/activation.ts
src/ecs/commands.ts
src/eventSchemas/commands/downloadSchemaItemCode.ts
src/eventSchemas/commands/viewSchemaItem.ts
src/eventSchemas/vue/searchSchemas.ts
src/eventSchemas/wizards/schemaCodeDownloadWizard.ts
src/extension.ts

Continued from:
- #1638
- #4202
- #4218

lint: require "await" or .catch() on async calls

---

buildspec/linuxTests.yml
buildspec/shared/common.sh
buildspec/shared/linux-pre_build.sh

fix(ci): test failure does not fail CI

---

src/test/dynamicResources/awsResourceManager.test.ts

Even after 6d66720b8782944376a99b35ab3c72f97d409415, tests still sometimes fail because the global schemaService is not properly restored:
createNewSamApp
addInitialLaunchConfiguration
produces and returns initial launch configurations:
TypeError: Cannot read properties of undefined (reading 'registerMapping')
at CloudFormationTemplateRegistry.process (src/shared/fs/templateRegistry.ts:38:35)
at async CloudFormationTemplateRegistry.addItem (src/shared/fs/watchedFiles.ts:214:26)
at async Context.<anonymous> (src/test/lambda/commands/createNewSamApp.test.ts:118:13)
...
rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'isMapped')
stack trace: TypeError: Cannot read properties of undefined (reading 'isMapped')
at …

fix(tests): "TypeError: … undefined (reading 'isMapped')"

---

src/codewhisperer/service/recommendationHandler.ts

refactor(codewhisperer): simplify isValidResponse()

---

package-lock.json
src/browser/package.json
webpack.browser.config.js

polyfills crypto module when in the browser with a browser compatible version

build: polyfill crypto module when in the browser

---

src/test/codewhisperer/commands/onAcceptance.test.ts
src/test/codewhisperer/commands/onInlineAcceptance.test.ts

fix codewhisperer:  clean codewhisperer states afterEach

---

src/test/codewhisperer/commands/onAcceptance.test.ts
src/test/codewhisperer/commands/onInlineAcceptance.test.ts

fix(tests): unreliable codewhisperer tests

---

src/shared/telemetry/telemetryService.ts
src/shared/telemetry/util.ts

refactor: simplify validateMetricEvent()

---

src/shared/systemUtilities.ts

Reverts to only using `fs` methods instead of `fs-extra` since `fs` will not break if imported in to the browser.
`fs` code still cannot run in the browser, but it will not break if something imports it.

browser: remove fs-extra uses from systemUtilities.ts

---

.gitignore

remove committed zip file

---

packages/toolkit/src/extension.ts
packages/toolkit/src/extensionShared.ts
packages/toolkit/src/extensionWeb.ts
packages/webpack.browser.config.js

With this PR you can now:
- Start up the Chromium test window with the toolkit installed
- Connect to auth + use CodeWhisperer code suggestions
Note errors may still pop up, but these are being worked on.

web: Active CodeWhisperer in Web Mode

---

CONTRIBUTING.md
docs/browser.md

doc: add prerequisite for browser mode

---

packages/toolkit/src/shared/cloudformation/cloudformation.ts

fix https://github.com/aws/aws-toolkit-vscode/issues/4462
rejected promise not handled within 1 second: Error: undefined template for uri: file:///codebuild/output/src1385150502/src/github.com/aws/aws-toolkit-vscode/packages/toolkit/dist/src/testFixtures/workspaceFolder/.vscode/settings.json

fix: "rejected promise ... reading AWSTemplateFormatVersion"

---

packages/toolkit/src/shared/sam/cli/samCliDetection.ts

telemetry: invalid Metric: "sam_detect" emitted with result=Failed but without the reason property.

fix(telemetry): "sam_detect" emitted without "reason"

---

packages/toolkit/src/extension.ts
packages/toolkit/src/extensionShared.ts
packages/toolkit/src/extensionWeb.ts
packages/toolkit/src/shared/resourcefetcher/fileResourceFetcher.ts
packages/toolkit/src/testWeb/extension.test.ts
packages/webpack.web.config.js

This PR:
- removes some uses of `fs-extra`
- Gets the region provider working in web. This enables the user to sign in w/ IdC and be able to select a region listed in  our `endpoints.json` file.
- Fixes an issue w/ webpack + web extension in chrome + breakpoints.
See each commit for specifics.

web: various fixes/improvements

---

.changes/next-release/Bug Fix-caa49c08-b446-4349-8228-31b5f00af5e5.json
package-lock.json
packages/core/package.json

New version of mynah ui is released: https://github.com/aws/mynah-ui/releases/tag/v4.3.0
Update to it

deps: update mynah-ui to 4.3.0

---

packages/core/src/shared/telemetry/util.ts

https://github.com/aws/aws-toolkit-vscode/pull/4494 broke linting
Fix the linting by running `npm run lintfix`

lint: fix linting error in telemetry utils

---

packages/toolkit/scripts/build/copyFiles.ts

build: document --vueHr

---

packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
packages/core/src/amazonqFeatureDev/userFacingText.ts
packages/core/src/testE2E/amazonq/featureDev.test.ts
packages/core/src/testE2E/amazonq/framework/framework.ts
packages/core/src/testE2E/amazonq/framework/messenger.ts
packages/core/src/testE2E/amazonq/framework/text.ts

- We don't have any e2e tests to make sure codegen is working
- Add tests for all codegen states
- Add tests for all possible ending states including iterations
List of test cases:
```
Amazon Q Feature Dev
quick action availability
- Shows /dev when feature dev is enabled
- Does NOT show /dev when feature dev is NOT enabled
/dev {msg} entry
- Should receive chat response
Moves directly from approach to codegen
Clicks accept code
- clicks new task
- click close session
Iterates on codegen
Clicks accept code
- clicks new task
- click close session
Iterates on approach
- Should iterate successfully
Moves to codegen after iteration
Clicks accept code
- clicks new task
- click close session
Iterates on codegen
Clicks accept code
- clicks new task
- click close session
/dev entry
- Clicks …
```

tests: Add feature dev codegen e2e tests

---

package-lock.json
packages/core/package.json
packages/core/src/amazonq/webview/ui/apps/featureDevChatConnector.ts
packages/core/src/amazonq/webview/ui/commands.ts
packages/core/src/amazonq/webview/ui/connector.ts
packages/core/src/amazonq/webview/ui/diffTree/actions.ts
packages/core/src/amazonq/webview/ui/diffTree/types.ts
packages/core/src/amazonq/webview/ui/main.ts
packages/core/src/amazonqFeatureDev/app.ts
packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
packages/core/src/amazonqFeatureDev/controllers/chat/messenger/messenger.ts
packages/core/src/amazonqFeatureDev/session/session.ts
packages/core/src/amazonqFeatureDev/session/sessionState.ts
packages/core/src/amazonqFeatureDev/types.ts
packages/core/src/amazonqFeatureDev/views/actions/uiMessageListener.ts
packages/core/src/amazonqFeatureDev/views/connector/connector.ts
packages/core/src/test/amazonqFeatureDev/utils.ts

- We don't have a way for users to individually select which files should be accepted after code generation
- Allow users to reject files from being accepted after code generation

feat: Introduce file by file acceptance

---

packages/core/src/amazonqFeatureDev/util/files.ts
packages/core/src/test/amazonqFeatureDev/util/files.test.ts

Currently the unit tests are failing on windows See Issue #4525 
Small test bug fixes

fix(amazonqFeatureDev): fix tests on windows

---

packages/core/src/auth/auth.ts
packages/core/src/auth/secondaryAuth.ts
packages/core/src/auth/sso/ssoAccessTokenProvider.ts
packages/core/src/codewhisperer/service/featureConfigProvider.ts
packages/core/src/codewhisperer/util/authUtil.ts
packages/core/src/shared/utilities/cacheUtils.ts

The current auth code path does not have sufficient logging, which makes it hard to debug auth related issues.
Add log.info in aws toolkit auth code path. 

fix(cwspr): add more log info for auth code path

---

packages/core/src/auth/secondaryAuth.ts
packages/core/src/auth/sso/ssoAccessTokenProvider.ts

chore: lint

---

packages/core/src/shared/utilities/cacheUtils.ts

With some good debugging from Lei, it was discovered that we were getting errors during auth but that they were being lost.
The errors we now see indicate that during a read of the SSO cache, the JSON is malformed.
A guess is that multiple writes to a file can happen at the same time.
To mitigate this, when writing cache we will make it more atomic by writing all the content to a temp file, then renaming the temp file to the actual target.
Now, if there is a race condition each write will either fully make it in or be overwritten by the following write. We should now avoid the malformed JSON.
- If we do multiple token refreshes in rapid succession, both refreshed access tokens will be valid by the looks of it. I guess there isn't a max of 1 active token. So if we have a race condition for …

fix: malformed SSO cache

---

packages/core/src/auth/sso/ssoAccessTokenProvider.ts

Outdated comment for class SsoAccessTokenProvider

docs: outdated comment

---

packages/amazonq/package.json
packages/core/package.json
packages/core/src/shared/logger/activation.ts
packages/core/src/test/techdebt.test.ts

test(q): set default log level to debug for beta testing

---

.gitignore
packages/amazonq/README.md
packages/amazonq/package.json
packages/amazonq/scripts/build/copyFiles.ts

ci(amazonq): update for beta publishing

---

package-lock.json
packages/amazonq/package.json

ci(amazonq): fix qna, clean script in package.json

---

packages/core/src/test/amazonqFeatureDev/controllers/chat/controller.test.ts
packages/core/src/test/amazonqFeatureDev/session/session.test.ts
packages/core/src/test/amazonqFeatureDev/utils.ts

Follow up for the this PR:
https://github.com/aws/aws-toolkit-vscode/pull/4556
why?
This test makes sure only non rejected files are being inserted when customer accepting changes.

feat(Amazon Q FeatureDev): add test for insertChanges

---

scripts/package.ts

- Should fix for users running windows machines

fix(packaging): use execFileSync

---

buildspec/release/00clonerepo.yml
buildspec/release/40pushtogithub.yml

fix(release): add branch env var, protect against release loops

---

buildspec/release/20buildrelease.yml
buildspec/release/50githubrelease.yml
buildspec/release/60publish.yml

fix(release): dynamic release buildspecs

---

packages/core/src/codewhisperer/service/transformByQ/transformApiHandler.ts
packages/core/src/test/codewhisperer/commands/transformByQ.test.ts

fix(gumby): update command, unskip test

---

package-lock.json
packages/core/package.json

- we are seeing multiple "Generating your answer..." cards in featureDev
- update mynah ui to 4.5.5
The bug hasn't been released to customers yet, that why theres no changelog entry

deps: Update Mynah UI to 4.5.5 

---

packages/amazonq/src/extensionShared.ts

followup to https://github.com/aws/aws-toolkit-vscode/pull/4711 

fix(amazonq): improve autoinstall message

---

packages/amazonq/src/extensionShared.ts
packages/core/src/extensionShared.ts
packages/core/src/shared/telemetry/activation.ts
packages/core/src/shared/telemetry/service-2.json
packages/core/src/shared/telemetry/telemetryClient.ts

Related: https://github.com/aws/aws-toolkit-common/pull/723

feat(telemetry): add dynamic product names for multiple extensions

---

packages/amazonq/.vscode/tasks.json
packages/toolkit/package.json

merge `master` into `feature/standalone`

---

.changes/next-release/Feature-29598070-7516-4255-8981-a3db0c4cb8de.json
.changes/next-release/Feature-c45c0979-bb7a-43dd-b1e2-d046667ebbb1.json
package-lock.json
packages/core/package.json
packages/core/src/codewhisperer/activation.ts
packages/core/src/codewhisperer/commands/startSecurityScan.ts
packages/core/src/codewhisperer/models/constants.ts
packages/core/src/codewhisperer/models/model.ts
packages/core/src/codewhisperer/ui/codeWhispererNodes.ts

Fix remaining bugs in `feature/cw-proactive-scan` branch
- Add changelogs
- Update telemetry package and pass scope field to `codewhisperer_securityScan`
- Don't run file scans if auth is not connected
- Don't run file scans if monthly quota is exceeded

codewhisperer: fix bugs for proactive scans

---

package.json

fix(scripts): clean up root npm scripts

---

packages/core/src/codewhisperer/util/codewhispererSettings.ts

fix(lint): ignore codewhisperer setting name too long

---

packages/core/src/auth/ui/vue/authForms/types.ts
packages/core/src/codewhisperer/activation.ts
packages/core/src/codewhisperer/client/codewhisperer.ts
packages/core/src/codewhisperer/commands/invokeRecommendation.ts
packages/core/src/codewhisperer/models/constants.ts
packages/core/src/codewhisperer/service/diagnosticsProvider.ts
packages/core/src/codewhisperer/service/featureConfigProvider.ts
packages/core/src/codewhisperer/service/recommendationHandler.ts
packages/core/src/codewhisperer/ui/codeWhispererNodes.ts
packages/core/src/codewhisperer/util/authUtil.ts
packages/core/src/codewhisperer/util/showSsoPrompt.ts
packages/core/src/codewhisperer/vue/backend.ts
packages/core/src/feedback/vue/submitFeedback.ts
packages/core/src/shared/utilities/download.ts

feat(amazonq): string updates

---

packages/core/src/auth/sso/server.ts
packages/core/src/auth/sso/ssoAccessTokenProvider.ts
packages/core/src/auth/sso/vue/index.html
packages/core/src/test/credentials/sso/server.test.ts

- We don't need to re-show scopes since they were on the last auth page
- Use a more generic message instead

fix: update successful authentication message

---

.changes/next-release/Bug Fix-4480804e-ed2b-4d53-98f6-c22ae10fdbf0.json
packages/core/src/amazonq/webview/ui/followUps/generator.ts
packages/core/src/amazonq/webview/ui/quickActions/generator.ts
packages/core/src/amazonq/webview/ui/tabs/generator.ts

Needed to make visual text&copy changes to Feature Development capability. 
Making visual, copy/text changes by
- Removing `Application Development` menu group
- Updating command description for `/dev` command
- Updating welcome message for `/dev` command
- Updating followup message of `/dev` command

fix(q): Make copy/text changes to Feature Development capability

---

packages/core/src/login/webview/vue/login.vue

fix typo in func name of login webview

fix(amazonq): fix typo in func name of login webview

---

packages/core/src/codecatalyst/auth.ts

Onboarding problems, fixed by this I hope

cherry-pick: cc connection state fix

---

packages/core/src/shared/extensionUtilities.ts
packages/core/src/test/shared/extensionUtilities.test.ts

feat(amazonq): product name

---

packages/core/src/codewhisperer/commands/basicCommands.ts
packages/core/src/codewhisperer/models/constants.ts
packages/core/src/codewhisperer/service/securityIssueProvider.ts
packages/core/src/test/codewhisperer/commands/basicCommands.test.ts
packages/core/src/test/codewhisperer/service/securityIssueProvider.test.ts

Bug fixes for security scan issues
- Don't show notification when applying fix
- Fix bug where hover sometimes incorrectly gets removed when document changes

fix(amazonq): bug fixes

---

packages/core/src/codewhisperer/activation.ts
packages/core/src/shared/telemetry/activation.ts
packages/core/src/shared/telemetry/util.ts

fix(amazonq): settings

---

packages/core/src/shared/telemetry/activation.ts

fix(telemetry): notice mentions extension name

---

packages/core/src/shared/telemetry/activation.ts
packages/core/src/shared/telemetry/util.ts
packages/core/src/shared/vscode/commands2.ts

refactor: use isAmazonQ()

---

packages/core/src/codewhisperer/activation.ts

fix settings open in code reference log

fix(amazonq): fix settings open in code reference log

---

packages/amazonq/README.md

fix(readme): amazonq readme spacing

---

buildspec/release/20buildrelease.yml

fix(release): old buildrelease.yml artifact

---

packages/amazonq/package.json

Update Walkthrough description

fix(amazonq): update walkthrough description

---

.github/PULL_REQUEST_TEMPLATE.md

Update PR template to include guidance for UI/UX related PRs

docs: guidance for UX related PRs

---

packages/toolkit/scripts/build/handlePackageJson.ts

Fixes: #4658
See code for explanation in the docstring

fix: null extension during Debug mode

---

package-lock.json
package.json

dependency: update @vscode/test-web

---

packages/core/src/codewhisperer/ui/codeWhispererNodes.ts
packages/core/src/codewhisperer/vue/backend.ts
packages/core/src/feedback/vue/submitFeedback.ts
packages/core/src/feedback/vue/submitFeedback.vue
packages/core/src/test/feedback/commands/submitFeedbackListener.test.ts

fix(feedback): rename last CodeWhisperer strings to Amazon Q

---

packages/amazonq/.changes/next-release/Bug Fix-1a10b655-4aec-44ad-9c9c-1423375a10bf.json

feat(auth): add changelog for `5a59571ca82a4ce6a8b1d04145d5affc8d9591e1`

---

packages/core/src/auth/connection.ts

ux(auth): change IdC roles message to warn instead of error

---

packages/core/src/login/webview/vue/login.vue

fix icon for `IAM_CREDENTIAL` in Login page.

fix(amazonq): fix icon for IAM_CREDENTIAL

---

packages/core/src/dev/activation.ts

It is common for want to view/modify the Auth Profile store. The Profile Store is our source of truth for auth connections that the extension is aware of and using.
We sometimes want to read and modify this source of truth for debugging purposes.
The issue is that this option is hard to find since you need to dig through multiple menus. Also once you get to it, the content you see will become stale if it ever changes and there is no way to refresh it to get the latest changes due to a bug.
- Add a new item to our Developer Menu to open the auth profile store editor.
- Fix issue where the text document editor was not refreshing with the latest changes.
- The root of the issue was that we never signaled that the file content changed.
- So we need to call `refresh()` to force the file to …

dev: Edit Auth connections + fix stale auths

---

packages/core/src/codewhisperer/models/constants.ts

Increase polling frequency of scans
Increase polling frequency to maximize the speed of scan completion.

amazonq: increase polling frequency of scans

---

packages/core/src/shared/utilities/messages.ts
packages/core/src/test/codewhisperer/util/authUtil.test.ts

auth: add telemetry to reauth notification

---

packages/core/src/accessanalyzer/vue/constants.ts
packages/core/src/accessanalyzer/vue/iamPolicyChecks.ts
packages/core/src/accessanalyzer/vue/iamPolicyChecks.vue
packages/core/src/shared/telemetry/vscodeTelemetry.json

Telemetry implementation, updating response colors to be shown in the Webview, and return intended line numbers in problems panel.
Corresponding PR for new metrics in `aws-toolkit-common`: https://github.com/aws/aws-toolkit-common/pull/735

feat(IamPolicyChecks): implement Telemetry, update error colors, fix problems line number

---

package-lock.json
packages/core/package.json
packages/core/src/accessanalyzer/vue/constants.ts
packages/core/src/accessanalyzer/vue/iamPolicyChecks.ts
packages/core/src/accessanalyzer/vue/iamPolicyChecks.vue
packages/core/src/shared/telemetry/vscodeTelemetry.json
packages/toolkit/.changes/next-release/Feature-2eeb5c36-d40f-4fe5-bd00-49e0fde883cc.json

Remove from Experiments and prepare for next release.
Updated responses and error messaging
Cleaned up some bugs discovered from a bug bash

feat(IamPolicyChecks): remove from Experiments and enable by default, update error messages, fix bugs

---

buildspec/release/60publish.yml

ref https://github.com/aws/aws-toolkit-vscode/issues/4943

ci: publish to OpenVSX

---

packages/amazonq/package.json
packages/toolkit/package.json

build: update marketplace categories

---

README.md

Very much open to wording/content changes.

chore: update root README.md for 2 extensions

---

packages/amazonq/src/extensionShared.ts

fix: registerCommands not imported in amazon q

---

packages/core/src/amazonq/webview/ui/followUps/constants.ts

File just contains header
Delete file

cleanup: remove empty file

---

packages/amazonq/README.md
packages/core/src/login/webview/vue/login.vue

update copy for builder id accounts

fix(amazonq): update copy for builder id

---

README.md
docs/arch_develop.md
packages/amazonq/.changes/next-release/Bug Fix-17572ed1-4601-4554-9144-9eb5143bf0ff.json
packages/amazonq/README.md
packages/amazonq/package.json
packages/amazonq/src/extension.ts
packages/amazonq/src/extensionCommon.ts
packages/amazonq/src/extensionWeb.ts
packages/core/package.json
packages/core/src/amazonq/onboardingPage/walkthrough.ts
packages/core/src/codewhisperer/service/classifierTrigger.ts
packages/core/src/codewhisperer/ui/codeWhispererNodes.ts
packages/core/src/codewhisperer/util/authUtil.ts
packages/core/src/extension.ts
packages/core/src/extensionCommon.ts
packages/core/src/extensionWeb.ts
packages/core/src/extensionWebShared.ts
packages/core/src/login/webview/vue/login.vue
packages/core/src/shared/extensionGlobals.ts
packages/core/src/shared/utilities/functionUtils.ts
packages/core/src/shared/utilities/timeoutUtils.ts
packages/core/src/test/codewhisperer/commands/transformByQ.test.ts
packages/toolkit/.changes/next-release/Bug Fix-7a3ed468-dad2-4867-933b-1cfc101e99b9.json
packages/toolkit/README.md
scripts/package.ts

Merge master into feature/separate-sessions

---

packages/amazonq/.changes/next-release/Bug Fix-d273820d-6692-4de2-af43-55913213d948.json
packages/core/src/amazonqGumby/chat/controller/controller.ts
packages/core/src/amazonqGumby/chat/controller/messenger/messenger.ts
packages/core/src/codewhisperer/models/constants.ts
packages/core/src/codewhisperer/service/transformByQ/transformApiHandler.ts
packages/core/src/codewhisperer/service/transformByQ/transformationResultsViewProvider.ts

We want to give users more helpful error message for proxy-related errors they may experience.
Show users pre-approved text when these proxy-related errors happen.

fix(amazonq): handle proxy-related error cases

---

packages/core/src/codewhisperer/client/user-service-2.json
src.gen/@amzn/codewhisperer-streaming/README.md
src.gen/@amzn/codewhisperer-streaming/package.json
src.gen/@amzn/codewhisperer-streaming/src/commands/ExportResultArchiveCommand.ts
src.gen/@amzn/codewhisperer-streaming/src/commands/GenerateAssistantResponseCommand.ts
src.gen/@amzn/codewhisperer-streaming/src/commands/GenerateTaskAssistPlanCommand.ts
src.gen/@amzn/codewhisperer-streaming/src/models/models_0.ts
src.gen/@amzn/codewhisperer-streaming/src/protocols/Aws_restJson1.ts

The streaming client needs to be updated to access recent API changes.
I followed the instructions [here](https://github.com/aws/aws-toolkit-vscode/blob/master/docs/build.md) to regenerate the client source files. I ran a quick test of basic chat features (Q, Featuredev, Gumby) to ensure stability.
~~Note: the client is 2 months out of date at this point, so quite a few changes have been generated.~~

chore: upgrade codewhisperer-streaming client

---

packages/amazonq/src/extension.ts
packages/core/src/dev/activation.ts
packages/core/src/dev/index.ts

**Split session commit**
Dev menu will now access individual extensions auth.

refactor(dev): update dev menu for separate auth sessions

---

packages/core/src/codecatalyst/activation.ts
packages/core/src/codecatalyst/auth.ts
packages/core/src/codecatalyst/commands.ts
packages/core/src/codecatalyst/devEnv.ts
packages/core/src/codecatalyst/explorer.ts

- Remove some unused auth code
- Add CodeCatalyst reauth function that verifies we are only using codecatalyst scopes.

[split sessions] refactor(codecatalyst): cleanup auth code, add scope check

---

packages/core/src/shared/logger/activation.ts

fix(logging): "View Logs" fails

---

docs/web.md

Doc to explain how to test your local development build in vscode.dev

doc: vscode.dev testing local build

---

packages/core/src/auth/sso/ssoAccessTokenProvider.ts

telemetry: missing reasonDesc for aws_refreshCredentials

---

packages/amazonq/.changes/next-release/Bug Fix-7a8b455f-a505-46b6-b5ae-783dcd6e55f4.json
packages/core/src/amazonq/webview/ui/tabs/generator.ts

- Current: Welcome to feature development. ... 
- Update: Hi, I'm the Amazon Q Developer Agent for software development. ...

fix(featureDev): update welcome message

---

packages/core/src/auth/auth.ts
packages/core/src/codewhisperer/activation.ts

Fixes:
- Adds 'source' to telemetry for logout prompt
- If in dev env, fall back to MDE credentials if logged out (due to sharing connection with Q)
- Bug where signing in to Amazon Q in dev env will add coca scopes (and otherwise share the underlying MDE credentials)
- Amazon Q was also importing the MDE creds under the hood, so it was being detected as an existant connection. This means any login method will use that instead of creating a new connection.

fix(codecatalyst): split session auth issues

---

packages/amazonq/.changes/next-release/Bug Fix-9130bd3b-edc4-4749-8c96-bd9a4fb9f03c.json
packages/core/src/amazonq/activation.ts
packages/core/src/login/webview/vue/login.vue
packages/core/src/login/webview/vue/reauthenticate.vue
packages/core/src/login/webview/vue/root.vue

- Update Styling for Login Page and Reauth page
- Show notification once if a user is not logged in when Amazon Q extension activates.

fix(amazonq): update login screen and auth notification

---

package-lock.json
packages/amazonq/.changes/next-release/Bug Fix-0f3dfb01-3e8b-4265-b577-95c697cd0882.json
packages/amazonq/.changes/next-release/Bug Fix-93ec3407-f6ca-45d8-a382-3da94d1da4bc.json
packages/amazonq/.changes/next-release/Bug Fix-c59b24c3-cffc-4944-9dc3-41370db42611.json
packages/amazonq/.changes/next-release/Bug Fix-cb5ae152-1668-4bb0-a9e3-a071c5e2bc51.json
packages/amazonq/.changes/next-release/Bug Fix-d8d55934-89f2-4061-b093-271f53fbb44e.json
packages/core/package.json

- There was some mynah update which caused the in progress message to be hidden leading to bad experience for customers as they would not be aware that their calls are in progress.
- Mynah changes were fixed with this PR: https://github.com/aws/mynah-ui/pull/67
- Bumped mynah-version to use latest fix

fix(featureDev): progress UX during backend calls

---

CONTRIBUTING.md
packages/core/src/shared/filesystemUtilities.ts
packages/core/src/test/testRunner.ts
packages/core/src/test/testUtil.ts
packages/core/src/testInteg/globalSetup.test.ts
packages/core/src/testInteg/stepFunctions/init.test.ts

docs: various

---

package-lock.json
package.json
packages/core/package.json

close https://github.com/aws/aws-toolkit-vscode/pull/5139

deps: update marked, telemetry

---

package-lock.json
packages/amazonq/.changes/next-release/Bug Fix-3cf4b30c-f9c0-46e4-b84c-25393280406b.json
packages/amazonq/.changes/next-release/Bug Fix-4b7b00c1-acf9-404e-aeb7-454ea27b4756.json
packages/amazonq/.changes/next-release/Bug Fix-7cf51833-202a-4ac9-ba80-31508173cdeb.json
packages/amazonq/.changes/next-release/Bug Fix-ba598435-f135-461d-a9e7-30e237f39197.json
packages/amazonq/.changes/next-release/Bug Fix-ed04e79f-8e4a-4e82-b009-b53a9ce282ef.json
packages/amazonq/.changes/next-release/Bug Fix-f15a1b78-94fc-4dba-9ef7-33a234ee42cb.json
packages/core/package.json

- Button texts are getting cropped too short
- Button texts are too big
- Buttons don't show borders inside chat messages
- Prompt input becomes invisible if user types html special characters
- Prompt input and selected command are not horizontally aligned
- Prompt input doesn't show some lines if user pastes multiline content
- All the above issues addressed through mynah-ui updates.
[MynahUI 4.15.1 release notes](https://github.com/aws/mynah-ui/releases/tag/v4.15.1)
[MynahUI 4.15.0 release notes](https://github.com/aws/mynah-ui/releases/tag/v4.15.0)
[MynahUI 4.14.1 release notes](https://github.com/aws/mynah-ui/releases/tag/v4.14.1)

fix: Prompt input and button styles and bugs

---

packages/core/src/codewhispererChat/controllers/chat/controller.ts

fix(amazonq): typo

---

packages/core/src/login/webview/vue/login.vue
packages/core/src/login/webview/vue/reauthenticate.vue
packages/core/src/login/webview/vue/selectableItem.vue

Font color for high contrast themes to fix #5294 

fix: font color for high contrast themes

---

.github/workflows/node.js.yml

[2024-07-12T13:58:12.874Z] ['info'] -> No token specified or token is empty
...
[2024-07-12T13:58:13.715Z] ['verbose'] Passed token was 0 characters long
[2024-07-12T13:58:13.952Z] ['verbose'] The error stack is: Error:
Error uploading to https://codecov.io: Error: There was an error
fetching the storage URL during POST: 429 - {'detail':
ErrorDetail(string='Rate limit reached. Please upload with the
Codecov repository upload token to resolve issue. Expected time to
availability: 1752s.', code='throttled')}
- Update codecov GHA runner.
- Set "token" field of the codecov GHA runner.
- https://github.com/codecov/codecov-action/issues/1292
- https://github.com/codecov/codecov-action/issues/598
By submitting this pull request, I confirm that my contribution is made under the terms of the …

fix(ci): codecov throttled on GHA

---

packages/amazonq/package.json

fix: remove duplicate command entry

---

.gitignore
package-lock.json
package.json
packages/core/src/amazonqGumby/chat/controller/controller.ts
packages/core/src/login/webview/vue/backend.ts
packages/core/src/shared/telemetry/vscodeTelemetry.json

depends on https://github.com/aws/aws-toolkit-common/pull/785

telemetry: upstream metrics to aws-toolkit-common

---

packages/core/package.json
packages/core/package.nls.json
packages/core/src/awsexplorer/regionNode.ts
packages/core/src/dynamoDb/activation.ts
packages/core/src/dynamoDb/commands/searchDynamoDbTables.ts
packages/core/src/dynamoDb/commands/sortDynamoDbTables.ts
packages/core/src/dynamoDb/commands/viewDynamoDbTable.ts
packages/core/src/dynamoDb/explorer/dynamoDbInstanceNode.ts
packages/core/src/dynamoDb/explorer/dynamoDbTableNode.ts
packages/core/src/extension.ts
packages/core/src/shared/clients/dynamoDbClient.ts

- Users should be able to see the DynamoDB in the Explorer tab, it should list all the tables available. 
- Should be able to refresh, and search the tables. 
- When clicked on a table, it should open the contents of the tables in a file.
Implemented the code for the above problem statement. 

DynamoDB Initial Changes

---

packages/core/src/login/webview/vue/base.css

Scale login / re-authenticate screen based on width.

fix: scale content based on width

---

packages/core/src/codewhisperer/models/constants.ts
packages/core/src/codewhisperer/service/securityIssueHoverProvider.ts
packages/core/src/codewhisperer/service/securityScanHandler.ts

- We have nested loops which may cost some performance issues in the plugin.
- Reduce the time complexity in the code which will improve performance of the plugin.

[Amazon Q Security Scans] Refactoring code to improve the performance

---

docs/TESTPLAN.md
packages/core/src/amazonq/commons/diff.ts
packages/core/src/amazonq/index.ts
packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
packages/core/src/amazonqFeatureDev/types.ts
packages/core/src/test/amazonq/common/diff.test.ts
packages/core/src/test/amazonqFeatureDev/controllers/chat/controller.test.ts

- A lot of the diffing functionality is hidden in feature dev
- Pull it out into amazon q commons

Refactor diff functionality to make it more usable

---

package-lock.json
package.json
packages/core/package.json
packages/core/src/dynamoDb/activation.ts
packages/core/src/dynamoDb/explorer/dynamoDbTableNode.ts
packages/core/src/dynamoDb/utils/dynamodb.ts
packages/core/src/dynamoDb/utils/dynamodbUtils.ts
packages/core/src/dynamoDb/vue/index.ts
packages/core/src/dynamoDb/vue/tableView.css
packages/core/src/dynamoDb/vue/tableView.ts
packages/core/src/dynamoDb/vue/tableView.vue
packages/core/src/extension.ts

UI Changes for DynamoDB

---

packages/core/src/dynamoDb/utils/dynamodb.ts
packages/core/src/dynamoDb/vue/tableView.css
packages/core/src/dynamoDb/vue/tableView.ts
packages/core/src/dynamoDb/vue/tableView.vue
packages/core/src/test/dynamoDb/commands/deleteDynamoDbTable.test.ts
packages/core/src/test/dynamoDb/commands/searchDynamoDbTables.test.ts
packages/core/src/test/dynamoDb/utils/dynamodb.test.ts
packages/core/src/test/dynamoDb/vue/tableView.test.ts
packages/core/src/test/shared/clients/dynamoDbClient.test.ts

Unit test cases for DynamoDB Module

Unit test cases for DynamoDB Module

---

packages/core/src/amazonq/commons/model.ts
packages/core/src/amazonqFeatureDev/models.ts
packages/core/src/amazonqFeatureDev/views/connector/connector.ts
packages/core/src/amazonqGumby/app.ts
packages/core/src/amazonqGumby/chat/controller/messenger/messenger.ts
packages/core/src/amazonqGumby/chat/views/connector/connector.ts

Transform is using imports from feature dev
- Clean up dependencies
- Rename a couple variables 

refactor: cleanup feature dev imports in transform

---

packages/core/src/auth/sso/constants.ts
packages/core/src/auth/sso/validation.ts
packages/core/src/login/webview/vue/login.vue

Follow up to https://github.com/aws/aws-toolkit-vscode/pull/5418

chore(auth): consolidate start url validation

---

package-lock.json
package.json
packages/core/package.json
packages/core/package.nls.json
packages/core/src/dynamoDb/activation.ts
packages/core/src/dynamoDb/explorer/dynamoDbInstanceNode.ts
packages/core/src/dynamoDb/utils/dynamodb.ts
packages/core/src/dynamoDb/utils/editItem.ts
packages/core/src/dynamoDb/vue/contextMenu.vue
packages/core/src/dynamoDb/vue/tableView.css
packages/core/src/dynamoDb/vue/tableView.ts
packages/core/src/dynamoDb/vue/tableView.vue
packages/core/src/shared/clients/dynamoDbClient.ts
packages/core/src/test/dynamoDb/utils/dynamodb.test.ts

- Currently there is no pagination for the items in query panel
- Added pagination for the items in query panel

DynamoDB: Pagination in Query Panel

---

package-lock.json
packages/amazonq/test/unit/codewhisperer/tracker/codewhispererTracker.test.ts
packages/core/package.json
packages/core/src/codewhisperer/service/transformByQ/humanInTheLoopManager.ts
packages/core/src/codewhisperer/service/transformByQ/transformApiHandler.ts
packages/core/src/codewhisperer/tracker/codewhispererTracker.ts

Bump telemetry version to the latest
https://github.com/aws/aws-toolkit-common/pull/807
https://github.com/aws/aws-toolkit-jetbrains/pull/4770

(telemetry): bump toolkit telemetry generator version

---

packages/core/src/shared/telemetry/vscodeTelemetry.json

fix(telemetry): make auth_modifyConnection passive

---

packages/core/src/test/amazonq/common/contentController.test.ts

CI test in linux is failing.
Fix integ test case of content controller.

fix(amazonq): Fix integ test case of content controller

---

packages/toolkit/.changes/next-release/Bug Fix-5cccc581-cb46-4d26-a59e-1efdf73c147f.json

We need this so it is not empty

changelog item for toolkit

---

.github/workflows/lintcommit.js
CONTRIBUTING.md

- Rename "topic" to "type".
- Add "deps" type.
- Require a scope for "feat" and "fix".

ci: conventional commits

---

package-lock.json
package.json
packages/core/src/shared/performance/performance.ts
packages/core/src/shared/telemetry/spans.ts
packages/core/src/shared/telemetry/vscodeTelemetry.json
packages/core/src/shared/utilities/workspaceUtils.ts
packages/core/src/test/shared/telemetry/spans.test.ts

Cleanup how trackPerformance is used
https://github.com/aws/aws-toolkit-common/pull/823

refactor: Move trackPerformance to a property on telemetry

---

.github/workflows/node.js.yml
.github/workflows/notify.js

Tests aren't being written
Consider adding an action that checks for the presence of test files in a PR

config(toolkits): check for presence of test files in PRs

---

.github/workflows/notify.js

ci: update base head to include owner

---

.github/workflows/notify.js
.github/workflows/utils.js

we can't run the change/test action from a fork :(
Just log the information instead
---

ci(workflows): log on changelog/tests needed

---

.github/workflows/lintcommit.js
.github/workflows/node.js.yml
.github/workflows/notification.yml
.github/workflows/notify.js
.github/workflows/utils.js

sorry for the spam 😅. pull_request_target apparently gives us more permissions
Example run: https://github.com/jpinkney-aws/aws-toolkit-vscode/pull/269
---

fix(workflows): test ci with pull_request_target

---

package-lock.json
package.json
packages/core/src/codewhisperer/commands/startTransformByQ.ts
packages/core/src/codewhisperer/service/transformByQ/transformApiHandler.ts
packages/core/src/codewhisperer/service/transformByQ/transformProjectValidationHandler.ts
packages/core/src/shared/utilities/download.ts

Need to update telemetry to reflect that we are no longer emitting a metric for API errors or latency, and to reflect the latest common telemetry updates.
Update telemetry as described.
---

telemetry(amazonq): telemetry updates

---

packages/amazonq/.changes/next-release/Feature-fb724754-850b-41b3-b3dd-2484b40720ff.json
packages/core/src/amazonq/webview/ui/apps/featureDevChatConnector.ts
packages/core/src/amazonqFeatureDev/app.ts
packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
packages/core/src/amazonqFeatureDev/views/actions/uiMessageListener.ts
packages/core/src/test/amazonqFeatureDev/controllers/chat/controller.test.ts
packages/core/src/test/amazonqFeatureDev/utils.ts

- feature dev is missing feedback telemetry. 
- Add feedback telemetry
---

telemetry(featuredev): add feedback telemetry

---

packages/amazonq/.changes/next-release/Bug Fix-e18d0bfd-d423-4c64-9454-b221eff45b7f.json
packages/core/src/shared/featureConfig.ts
packages/core/src/test/fake/mockFeatureConfigData.ts
packages/core/src/test/shared/featureConfig.test.ts

Add Additional Utility Methods to FeatureConfigProvider.

fix(fetureconfigprovider): add additional utility methods

---

packages/amazonq/.vscode/launch.json
packages/core/.vscode/launch.json
packages/toolkit/.vscode/launch.json

update presentation with groupings
---

config(launchjson): update presentation with groupings

---

packages/core/src/shared/extensionGlobals.ts

docs: explain outputChannel vs logOutputChannel

---

packages/core/src/amazonqGumby/chat/controller/controller.ts
packages/core/src/codewhisperer/commands/startTransformByQ.ts
packages/core/src/codewhisperer/service/transformByQ/transformApiHandler.ts
packages/core/src/codewhisperer/service/transformByQ/transformMavenHandler.ts
packages/core/src/codewhisperer/service/transformByQ/transformProjectValidationHandler.ts
packages/core/src/codewhisperer/service/transformByQ/transformationResultsViewProvider.ts
packages/core/src/test/techdebt.test.ts

Clean up deprecated code transform metrics.
---

telemetry: remove deprecated transform metrics

---

packages/amazonq/CHANGELOG.md

Update Changelog for Amazon Q extesnion.
---

fix(changelog): update changelog.md

---

packages/amazonq/test/e2e/amazonq/featureDev.test.ts
packages/amazonq/test/e2e/amazonq/framework/jsdomInjector.ts

E2E test is not up to date post approach removal
- Removed tests related to approach
- Refactored the E2E test script
---

test(feature dev): E2E test script post approach removal

---

packages/amazonq/.changes/next-release/Bug Fix-aa650a37-9441-4702-8c3e-7962ad57b00d.json
packages/core/resources/css/securityIssue.css
packages/core/src/codewhisperer/views/securityIssue/vue/root.vue

fix(amazonq): fix styles for security webview

---

.github/workflows/notification.yml

ci: skip notify job in staging repo

---

docs/telemetry.md
packages/core/src/shared/telemetry/spans.ts

No documentation about traceIds
Add documentation about traceIds
---

docs(telemetry): Add documentation about traceId

---

docs/arch_features.md

docs(ec2): add ec2 connect details to `arch_features.md`

---

packages/core/src/shared/handleUninstall.ts

verify path for .obsolete file

fix(amazonq): verify path for .obsolete file

---

packages/amazonq/.changes/next-release/Feature-4aa1d456-99b9-4b0d-a4cf-8452d00327da.json
packages/core/src/amazonqGumby/chat/controller/controller.ts

This reverts commit 0c4289b1a0b5d294cc352f7d2e7e586937ac0318.
Re-adding commit after backend fix 
---

feat(amazonq): skip showing users unit test form (#5679)

---

packages/core/resources/css/amazonq-chat.css
packages/core/src/amazonq/webview/generators/webViewContent.ts

Add animation for View Diff and Apply Diff buttons. 
Prerequisite - https://github.com/aws/mynah-ui/pull/140
Demo - 
https://github.com/user-attachments/assets/05092447-be86-4dc8-89b5-ecb7c4bfee0f

fix(amazonq): display animation for Apply Diff and View Diff buttons

---

packages/amazonq/.changes/next-release/Bug Fix-4519935f-b219-4535-8608-da1940a5b2a6.json

Since the amazonq one is empty
---

fix(release): changelog item

---

packages/core/src/test/shared/crashMonitoring.test.ts

increment the time that we wait for the interval to finish since it runs slower in ci
---

fix(test): flaky test

---

packages/core/src/codewhispererChat/controllers/chat/telemetryHelper.ts
packages/core/src/shared/telemetry/vscodeTelemetry.json

Bad grammar
Better grammar
---

fix(telemetry): fix grammer in time to first usable chunk metric

---

packages/core/src/codewhisperer/util/telemetryHelper.ts

JB's PR: https://github.com/aws/aws-toolkit-jetbrains/pull/5008
---

telemetry: add acceptedCharCount to UserTriggerDecision STE

---

packages/amazonq/package.json
packages/toolkit/package.json

Re-syncs icons after discrepancy in https://github.com/aws/aws-toolkit-vscode/pull/5835
---

ci: run generateIcons for extensions

---

.github/workflows/notify.js

bot is commenting on Merge prs: https://github.com/aws/aws-toolkit-vscode/pull/5882#issuecomment-2444027415
skip Merge prs.
---

ci: skip "test files required" for Merge prs

---

packages/core/src/amazonq/webview/ui/messages/constants.ts

There's nothing in this file
Remove it
---

style(amazonq): remove file with no contents in it

---

packages/core/src/shared/env/resolveEnv.ts

recent change to getResolvedShellEnv cause test to stall
Change return back to resolve in promise
---

fix(appbuilder): change getResolvedShellEnv to resolve

---

packages/core/src/login/webview/vue/types.ts
packages/core/src/notifications/panelNode.ts
packages/core/src/notifications/rules.ts
packages/core/src/notifications/types.ts
packages/core/src/test/notifications/rules.test.ts

- Add types to some RuleContext fields
- Add some informative log statements for debugging
- Add a test for getRuleContext()
- Add case-insenstive rule checks
- Fix getRuleContext to properly capture authTypes
- Remove a few unneeded lines of code
- Add red icon for emergency notifications
---

feat(notifications): add misc rule, log, type, and test changes

---

packages/amazonq/test/unit/amazonqFeatureDev/util/files.test.ts

Follow up PR from #5853 
Added more unit test coverage
---

test: update /dev prepareRepoData unit test to include devfile filtering

---

packages/core/src/dev/beta.ts

fix(beta): product name for Q beta

---

packages/core/src/shared/sam/build.ts
packages/core/src/shared/sam/deploy.ts
packages/core/src/shared/sam/processTerminal.ts
packages/core/src/shared/sam/sync.ts
packages/core/src/shared/sam/utils.ts
packages/core/src/test/shared/sam/utils.test.ts

With only Unknown errors, It's hard to differentiate errors or make possible improvements
- Parse SAM CLI output
- Add telemetry code based on the output error
---

telemetry(lambda): Send meaningful telemetry error codes for SAM CLI invocation failures

---

package-lock.json

Update dependencies to avoid any vulnerabilities 
---

deps(core): Update dependencies

---

packages/core/src/amazonq/lsp/lspController.ts

- bump amazonQ helper version to the latest
---

deps(amazonq): bump amazonQ helper version

---

packages/amazonq/.changes/next-release/Bug Fix-170bbb4e-ab52-4290-b803-1836b75ed415.json
packages/core/src/amazonqFeatureDev/client/featureDev.ts

RTS changed feature dev governance interface on dealing with quota
Added handling for this case on feature dev 
---

fix(amazonq): add handling for new limit mechanism

---

.github/workflows/copyPasteDetection.yml

Disable the task for now. 
---

build(jscpd): disable jscpd CI Task

---

packages/core/src/testInteg/perf/zipcode.test.ts

fix https://github.com/aws/aws-toolkit-vscode/issues/6117
---

test(flaky): unreliable test: zipCode performance tests

---

packages/amazonq/.changes/next-release/Bug Fix-75ff3f7a-3cfb-491c-9557-ce8c04f54ccc.json
packages/core/src/codewhisperer/commands/startCodeFixGeneration.ts

We are sending incorrect code issue description to the service.
Improved Code Fix generation for code review issues by sending issue recommendation text as description to the service.
---

fix(amazonq): Improved Code Fix generation for code review issues

---

packages/toolkit/.changes/next-release/Feature-eb088612-3f07-4410-86f2-6e91131d3ffe.json

Getting prepared to release LiveTail to AWSToolkit master branch. 
Create Changelog entry for LiveTail feature.
---

docs(cwl): Add liveTail changelog entry

---

packages/amazonq/.changes/next-release/Bug Fix-c685f18f-0c30-49a0-b4d8-e4eab0cf3bc6.json
packages/core/src/amazonq/lsp/lspController.ts

There are some code not used at all. 
Remove unused code
---

refactor(amazonq): Remove unused code

---

packages/toolkit/package.json

config(packagejson): update fonts

---

packages/amazonq/.changes/next-release/Feature-d0329e3d-65bd-4987-b87c-ee11b86de399.json

corresponding JB change https://github.com/aws/aws-toolkit-jetbrains/pull/5256 (vscode logics has been implemented)
---

feat(inline completion): enhance inline completion context fetching

---

packages/core/src/shared/resourcefetcher/httpResourceFetcher.ts

We currently only retry normal get requests in the httpResourceFetcher
Retry etag get requests as well
---

refactor(core): Allow retries while fetching etags

---

packages/core/src/shared/resourcefetcher/httpResourceFetcher.ts

Recently a [PR](https://github.com/aws/aws-toolkit-vscode/pull/6387/files#diff-c0100187095b7c009b33063c21a517248290b37d02ef10e9370d28cd3ed5d1ea) on master combined `waitUntil` with `withRetries`. Once master merged into feature branch, it caused this case to start erroring. 
Leading to the following:
```
npm error src/shared/resourcefetcher/httpResourceFetcher.ts(164,16): error TS2304: Cannot find name 'withRetries'.
```
- migrate to `waitUntil` in the same fashion as the PR. 
---
- License: I confirm that my contribution is made under the …

refactor(fetcher): migrate withRetries to waitUntil

---

packages/core/package.nls.json
packages/core/src/awsexplorer/regionNode.ts
packages/core/src/shared/settings-toolkit.gen.ts
packages/toolkit/.changes/next-release/Feature-a7fb8317-77bc-4459-a278-2bc98fd0a5cf.json
packages/toolkit/package.json

feat(ec2): graduate EC2 out of Experiments

---

docs/lsp-debugging.md
packages/amazonq/.vscode/launch.json
packages/amazonq/src/lsp/client.ts
packages/core/src/shared/lsp/utils/platform.ts

It's painful to setup debugging with flare
Add instructions to make it easy
---

docs(amazonq): Add instructions for debugging flare lsps

---

docs/web.md
package-lock.json
package.json

- Update web mode dependencies so we can run in debug mode
- Update docs w/ info on how to fix these dependencies as they go stale often. Otherwise we may not be able to run in debug mode.
---

build(web): update web mode deps

---

src.gen/@amzn/codewhisperer-streaming/README.md
src.gen/@amzn/codewhisperer-streaming/package-lock.json
src.gen/@amzn/codewhisperer-streaming/src/commands/GenerateAssistantResponseCommand.ts
src.gen/@amzn/codewhisperer-streaming/src/commands/GenerateTaskAssistPlanCommand.ts
src.gen/@amzn/codewhisperer-streaming/src/commands/SendMessageCommand.ts
src.gen/@amzn/codewhisperer-streaming/src/models/models_0.ts
src.gen/@amzn/codewhisperer-streaming/src/protocols/Aws_restJson1.ts

This is to simply update the src.gen dependencies of Amazon Q using new API models.
---

deps(cw): update SDK clients with codegen at 0.25.x

---

buildspec/release/notify.txt

refactor: notify.txt typos

---

src.gen/@amzn/codewhisperer-streaming/src/models/models_0.ts

Some code was accidentally checked in to src.gen
Remove these unnecessary code
---

refactor(amazonq): remove unnecessary code

---

package-lock.json
packages/core/package.json
packages/core/src/amazonq/webview/ui/main.ts

deps(amazonq): update mynahUI to beta 11

---

package-lock.json
packages/core/package.json

deps(amazonq): upgrade to mynahui beta 12

---

packages/amazonq/src/app/inline/completion.ts
packages/core/src/amazonq/lsp/config.ts

fix(cw): add missing languages; update ws lsp version

---

CONTRIBUTING.md

docs: CONTRIBUTING.md

---

packages/core/resources/css/amazonq-webview.css

style(chat): increase line height for h1

---

packages/core/resources/css/amazonq-webview.css

style(chat): make chat more compact

---

packages/core/src/login/webview/vue/regionProfileSelector.vue

fix(amazonq): update loading profile test displayed

---

packages/core/src/codewhispererChat/controllers/chat/controller.ts
packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts

- fix(chat): Improve diffView UX, changes include:
- Remove the icon in diff view
- Clean up temp files when accept or reject
- Do not open the files as they generate
---

fix(chat): Improve diffView UX

---

packages/amazonq/.changes/next-release/Bug Fix-f098149d-ad2c-485c-b652-c5bef1ecb379.json
packages/core/src/codewhisperer/client/codewhisperer.ts
packages/core/src/codewhisperer/service/securityScanHandler.ts

fix(amazonq): /review returns 0 findings

---

packages/core/src/amazonq/webview/ui/apps/cwChatConnector.ts
packages/core/src/amazonq/webview/ui/connector.ts
packages/core/src/amazonq/webview/ui/main.ts
packages/core/src/codewhispererChat/clients/chat/v0/chat.ts
packages/core/src/codewhispererChat/controllers/chat/controller.ts
packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
packages/core/src/codewhispererChat/tools/chatStream.ts
packages/core/src/codewhispererChat/tools/fsRead.ts
packages/core/src/codewhispererChat/tools/listDirectory.ts
packages/core/src/codewhispererChat/view/connector/connector.ts

- Reverting PR: #6975  as this is causing regression in some cases.
---

fix(chat): Reverting PR:6975

---

packages/core/src/shared/vscode/commands2.ts

fix(amazonq): "Sign in" does not focus Q panel

---

packages/core/src/codewhispererChat/controllers/chat/controller.ts

- Build is broken
- Fix failure caused by merge conflicts
---

fix(chat): Fix failure caused by merge conflicts

---

package-lock.json
packages/core/package.json
packages/core/src/amazonq/webview/ui/tabs/generator.ts
packages/core/src/codewhispererChat/controllers/chat/controller.ts

Pair Programmer mode button change in Mynah UI beta update caused the notification message in chat error.
- Corrected the prompt values for new button in controller to send the right message.
---

fix(chat): fix for pair programmer mode message in chat

---

package-lock.json
packages/core/package.json
packages/core/src/amazonq/webview/ui/tabs/generator.ts
packages/core/src/codewhispererChat/controllers/chat/controller.ts

fix the import parameter in controller and the programmer mode UI

---

package-lock.json
packages/core/package.json
packages/core/resources/css/amazonq-webview.css

The padding was too tight which not meet the requirement 
##
Notification
This pr update the beta version mynahUi
---

fix(chat): fix the tight paddding

---

packages/core/src/amazonq/webview/ui/tabs/generator.ts

fix(chat): Some string change for agentic chat

---

packages/amazonq/src/lsp/chat/webviewProvider.ts

fix(amazonq): chat disclaimer acknowledgement not recognized

---

packages/amazonq/src/lsp/chat/messages.ts

If you currently ask Q any questions about cursor position or highlighted text, it lacks the context necessary to answer. This is because in the payload sent to the LSP we send the cursor position as the wrong type:
https://github.com/aws/aws-toolkit-vscode/blob/2e8d4c7eb0f0bcbc416d8f6e06ff7e00d57dc6b2/packages/amazonq/src/lsp/chat/messages.ts#L159
whereas [Flare](https://github.com/aws/language-server-runtimes/blob/d9960b5dd6df52c52309f0a7edae64a824da9003/types/chat.ts#L82) is expecting: `cursorState`.
- Convert the vscode selection to a Flare cursorState. 
- Add stronger typing by casting the params to `ChatParams` type before modifying to avoid these types of bugs. 
- This fixes flare being unable to identify cursor position, and mostly fixes highlighted text. However, I was still able …

fix(amazonq): send proper cursor position to lsp

---

packages/amazonq/src/lsp/chat/messages.ts

During the agentic loop, if there are multiple iterations and then it eventually fails, the partial results would not be posted and the user would not be able to continue chat (it wouldn't allow them to type)
Port in the VSC client related change from: https://github.com/aws/language-servers/pull/1012
Now if there are errors during the agentic loop, we will display all the partial responses we have gathered and then break out of the generating state, allowing the user to continue.
Between the previous and new changes I ran the same test suite
- Ask agentic chat to make 101 files (since [a recent change](https://github.com/aws/language-servers/pull/1022) increased the loop limit to 100) in a test folder, adding in some random text
- Ask agentic chat to "read every single file, not skipping …

feat(amazonq): Port in chat message error handling

---

packages/amazonq/src/lsp/auth.ts

Some users were having invalid bearer token exceptions when making chat requests through agentic chat. This highlights an issue in how we sync the token. 
Originally, we thought this was because of a race condition. We check the token every 10 seconds for changes, and if its expired, refresh it and send it to the language server. However, that still leaves a 10 second gap where the language server could use an expired token before we update it. 
However, we add a buffer of one minute to our `isExpired` check here: 
https://github.com/aws/aws-toolkit-vscode/blob/db673c9b74b36591bb5642b3da7d4bc7ae2afaf4/packages/core/src/auth/sso/model.ts#L160
Therefore, this causes the token to expire a minute early, meaning there is a full minute, where our checks should detect the expired token and …

fix(amazonq): retry LSP token refresh on recoverable errors only. 

---

packages/amazonq/.changes/next-release/Feature-24aa4962-f8c1-4371-9725-216477e036dd.json
packages/amazonq/.changes/next-release/Feature-ef539952-41de-40d0-870e-94aee31f36d3.json

Add changelog for Pair Programmer release
---

feat(agentic chat): Add changelog

---

packages/amazonq/src/lsp/config.ts

Use flare preprod manifest for testing
---

feat(amazonq): Use flare preprod manifest

---

packages/amazonq/src/app/inline/completion.ts
packages/amazonq/src/app/inline/recommendationService.ts

config(amazonq): revert spamming log

---

packages/core/src/codewhisperer/ui/statusBarMenu.ts

fix(amazonq): fix git merge caused compile failure

---

package-lock.json
packages/amazonq/.changes/1.72.0.json
packages/amazonq/.changes/next-release/Feature-57661731-6180-4157-a04b-d3a8b50aa1a8.json
packages/amazonq/.changes/next-release/Feature-d6714581-799f-49dc-bb63-f08d461e9bde.json
packages/amazonq/CHANGELOG.md
packages/amazonq/package.json
packages/amazonq/src/lsp/client.ts

deps(amazonq): merge master to feature/flare-mega

---

packages/amazonq/.changes/next-release/Feature-35bcb9ac-0cc5-456f-8159-765a6deb3b47.json

Add change log to the feature branch
---

feat(q): add change log

---

packages/amazonq/.changes/next-release/Bug Fix-541466ab-cebc-4f12-bbc6-6cdedad9eafe.json

- Adding change log for #7520 
---

fix(amazonq): adding new changelog for #7520

---

packages/amazonq/src/app/inline/activation.ts

config(amazonq): disable nep development utility UI NextEditPredictionPanel

---

packages/amazonq/src/lsp/client.ts

Will revisit this feature later once we have other pieces working first
---

config(amazonq): temporarily disable cursorUpdateManager.ts

---

packages/amazonq/src/app/inline/completion.ts

refactor(amazonq): update inline tutorial todo comments

---

packages/amazonq/src/app/inline/cursorUpdateManager.ts
packages/amazonq/test/unit/app/inline/cursorUpdateManager.test.ts

The CursorUpdateManager starts its periodic timer regardless of the autotrigger setting, causing unnecessary background processing when autotrigger is disabled.
Modified CursorUpdateManager to respect the autotrigger setting by:
• Only starting the timer when autotrigger is enabled
• Dynamically starting/stopping the timer based on autotrigger state changes
• Added proper cleanup of state listeners
Note: This functionality was temporarily disabled in [PR #7576](https://github.com/aws/aws-toolkit-vscode/pull/7576/files) but this fix ensures correct behavior when it's re-enabled.
• Treat all work as PUBLIC. Private feature/x branches will not be squash-merged at release time.
• Your code changes must meet the guidelines in [CONTRIBUTING.md](https://github.com/aws/aws-toolkit-vscode/blob/mast …

fix(amazonq): update cursor tracking based on autotrigger setting

---

packages/amazonq/src/app/inline/EditRendering/displayImage.ts

config(amazonq): detailed debug logs for NEP

---

packages/amazonq/src/lsp/config.ts

To setup: https://github.com/aws/aws-toolkit-vscode/releases/tag/pre-prerelease-flare
This points `aws-toolkit-vscode` master branch to `langauage servers` main branch to test the latest changes in both repositories
---

feat(amazonq): setup to test flare main changes

---

packages/core/src/codewhisperer/client/codewhisperer.ts
packages/core/src/codewhisperer/client/user-service-2.json
packages/core/src/codewhisperer/util/telemetryHelper.ts

telemetry: should send suggestionType/pluginVersion via sendTelemetryEvent api
