- .travis.yml
- README.md
When TravisCI build script is successful, the code coverage reports are uploaded to CodeCov.
Added a badge to README.md to show coverage of the develop branch.
#86
#114
* Created PR, watched TravisCI build logs to see that coverage reports are processed by CodeCov
* Looked for this branch in CodeCov underneath https://codecov.io/gh/aws/aws-toolkit-vscode
> Hooking up code coverage reports to CodeCov

- src/extension.ts
- src/shared/credentials/defaultCredentialsFileReaderWriter.ts
- src/shared/defaultAwsContextCommands.ts
- src/test/defaultCredentialsFileReaderWriter.test.ts
If you've previously connected to AWS with a credentials profile and closed VS Code, the next time you open VS Code it uses the same profile. On startup, if the user does not have a config file, a "file does not exist" error shows up. This change prevents the code from trying to load profiles from the (non-existent) config file.
* Connect to AWS with a profile, then close VS Code
* delete (or rename) .aws/config file
* Reopen VS Code, select AWS Explorer
* Extension will attempt to re-connect to AWS with the same profile
* expect no error message
> Fix case where Extension startup tries to load a profile and the config file does not exist

- package-lock.json
- package.json
- src/shared/lambdaHandlerSearch.ts
- src/shared/typescriptLambdaHandlerSearch.ts
- src/test/samples/javascript/sampleClasses.js
- src/test/samples/javascript/sampleFunctions.js
- src/test/samples/typescript/sampleClasses.ts
- src/test/samples/typescript/sampleFunctions.ts
- src/test/samples/typescript/sampleInterfaces.ts
- src/test/typescriptLambdaHandlerSearch.test.ts
This code provides a way of locating Typescript functions that can be used as Lambda Function Handlers. This uses the Typescript engine instead of Symbol Information that can be surfaced by VS Code, since VS Code doesn't seem to provide parameter information for functions and methods.
#140  - while this is not surfaced presently, it will be used in #135 and #136 when CodeLens looks to determine which functions can be invoked/debugged.
> Utility class to detect Typescript functions that can possibly be used as Lambda Function Handlers.

- package.json
- package.nls.json
- src/lambda/lambdaTreeDataProvider.ts
Allow user to manually refresh the entire contents of the explorer.
Note: This change uses an existing icon as a placeholder for the 'refresh' icon.
The user's AWS resources may be changed outside of the toolkit. In this case, we don't have a mechanism to detect the change and automatically refresh. As a workaround, this change allows the user to manually refresh the explorer.
> Add refresh button to explorer.

- package-lock.json
- package.json
- package.nls.json
- src/lambda/lambdaTreeDataProvider.ts
- src/lambda/local/configureLocalLambda.ts
- src/shared/codelens/typescriptCodeLensProvider.ts
- src/shared/filesystem.ts
Currently, when a lambda handler is invoked through a code lens, the event payload is always `{}`. This change adds a new code lens labeled `configure`, that allows the user to specify a custom event payload for the handler.
Currently, when a lambda handler is invoked through a code lens, the event payload is always `{}`. This change adds a new code lens labeled `configure`, that allows the user to specify a custom event payload for the handler.
This code lens opens a new configuration file (`.aws/handlers.json`) and selects the configuration for the handler in question.
In the real world, lambda handlers are triggered by events. To be able to usefully debug handlers, the customer must be able to provide realistic event payloads.
#149
Tests are not included in this PR. Immediately after …
> Add code lens for configuring lambda handlers for local invoke.

- package-lock.json
- package.json
- src/lambda/local/configureLocalLambda.ts
When symbols are not available for `.aws/handlers.json`, retry with a delay. This handles the case in which the document symbol provider has not yet finished loading during the first attempt.
If the user invokes the 'Configure' code lens, and no JSON documents have previously been opened since VS Code was started, there is a brief window where symbols are not available for that document.
If symbols are unavailable, we consider the document to be invalid (the parser we use, `jsonc-parser`, is highly fault tolerant, so the lack of any symbols indicates a hopelessly malformed document) and create its contents from scratch. But if the symbols are missing due to the document symbol provider still loading, we will unnecessarily clobber the file.
By submitting this pull request, I confirm that …
> Bugfix: Avoid clobbering `handlers.json` before JSON document symbol provider is ready.

- .gitignore
- src/shared/credentials/userCredentialsUtils.ts
- src/test/shared/credentials/userCredentialsUtils.test.ts
Ensured user can read/write newly created credentials file
Ensured user can read/write newly created credentials file
https://github.com/aws/aws-toolkit-vscode/issues/153
Created test for file permissions after creation
> Set permissions for new creds file

- package-lock.json
- package.json
- src/shared/cloudformation/cloudformation.ts
- src/shared/utilities/asyncIteratorShim.ts
1. The latest VS Code update breaks our `asyncIterator` shim because `Symbol.asyncIterator` is now readonly. This change fixes the shim to correctly handle this case.
2. The latest update `@types/js-yaml` changes the signature of `yaml.safeLoad`, causing a linter error. We did not catch this earlier because npm 6+ defaults to the earliest matching version, which contains the old signature.
* Ran all existing tests
* Manually tested basic E2E scenarios.
> Fix `asyncIteratorShim` to work with latest VS Code update, and fix typedef version mismatch for `js-yaml`.

- package-lock.json
`npm audit` detected a prototype pollution issue in one of our dependencies. See https://github.com/aws/aws-toolkit-vscode/network/alert/package-lock.json/node.extend/open for details. This change uses `npm audit fix` to fix the issue.
https://github.com/aws/aws-toolkit-vscode/network/alert/package-lock.json/node.extend/open
> Fix security vulnerability detected by `npm audit`.

- package.json
Commands that are hooked up to the UI end up showing in the Command Palette by default. This isn't ideal, because these command usually is contextually relevant to Ui gestures, like the node that a context menu was associated with. The result was that the command palette contained extension commands that generally did nothing, raised errors (expecting parametered input), or messaged that the command was not found (due to the extension not being loaded). It turns out we did not understand how to hide these commands from the command palette, but this is possible. Result is cleaner experience in the command palette.
Commands hidden:
* Explorer Context Menu Items for CloudFormation, Lambda, Error nodes
* Refresh Explorer
#242 #244  #245 #246 
By submitting this pull request, I confirm that my …
> Hide commands from the Command Palette that are intended to be invoked with UI

- package.json
- package.nls.json
- src/extension.ts
- src/lambda/commands/deleteLambda.ts
- src/lambda/lambdaTreeDataProvider.ts
- src/test/lambda/commands/deleteLambda.test.ts
- src/test/mockOutputChannel.ts
Added confirmation when deleting Lambda
* Added confirmation when deleting Lambda
* Removed use of globals from deleteLambda
In response to issue.
https://github.com/aws/aws-toolkit-vscode/issues/219
Updated test to:
* Check that delete is called when confirmed
* Check that delete is not called when cancelled
* Refresh is called on both confirm and cancel
> Lambda delete confirm 219

- src/lambda/local/detectLocalLambdas.ts
- src/shared/cloudformation/cloudformation.ts
- src/shared/codelens/typescriptCodeLensProvider.ts
- src/shared/templates/sam/samTemplateGenerator.ts
- src/test/templates/sam/samTemplateGenerator.test.ts
1. Fix error on local invoke when there is no existing template by configuring our YAML dumper to ignore undefined values (instead of throwing).
2. Remove unused code from `SamTemplateGenerator`, and increase its type-safety.
3. Update `invoke locally` to search the same folders as `deploy`.
Previously it only searched the root of each workspace folder. Now
it also searchs their *direct* children.
1. Previously, if the user invoked a CodeLens without an existing template, the toolkit would throw when trying to save the generated template.
2. Templates inside a child folder of each workspace folder were detected by `Deploy to AWS`, but not by `Invoke Locally`.
* Manual testing:
1. Run the toolkit without opening a folder in VS Code.
2. Run the 'Create New Sam Application' command with …
> Fix SAM template detection during local invoke.

- package.nls.json
- src/lambda/commands/deleteCloudFormation.ts
- src/lambda/explorer/cloudFormationNodes.ts
You cannot delete CloudFormation stacks from the Explorer, because the label says `stackname stackStatus`, and the label is passed into SDK calls to delete cf stacks. Fixed this, so the actual stack name is passed in. 
While there, I added an error message when the command has no cloudFormation information to work with, to improve the feedback loop (otherwise there is no indication that processing has stopped).
Deleted a CF Stack using the Explorer.
> Fix delete CloudFormation to use stack name instead of label

- package.nls.json
- src/extension.ts
- src/lambda/commands/createNewSamApp.ts
- src/lambda/lambdaTreeDataProvider.ts
- src/lambda/local/detectLocalLambdas.ts
- src/lambda/local/detectLocalTemplates.ts
- src/lambda/models/samLambdaRuntime.ts
- src/lambda/utilities/getMainSourceFile.ts
- src/lambda/wizards/samDeployWizard.ts
- src/shared/cloudformation/cloudformation.ts
- src/shared/sam/cli/samCliInvoker.ts
- src/shared/treeview/awsTreeProvider.ts
- src/shared/utilities/childProcess.ts
- src/shared/utilities/collectionUtils.ts
- src/test/lambda/lambdaTreeDataProvider.test.ts
- src/test/lambda/local/detectLocalTemplates.test.ts
- src/test/lambda/utilities/getMainSourceFile.test.ts
- src/test/shared/cloudformation/cloudformation.test.ts
- src/test/utilities/childProcess.test.ts
- src/test/utilities/collectionUtils.test.ts
After a new SAM application is created, open its default code file (`app.js`, `Program.cs`, `app.py`, etc.).
* This change supports the NodeJS family of runtimes.
* A follow-up change will add support for the .NET family of runtimes.
Currently, when the user creates a new SAM application using our toolkit, it is unclear when the operation has completed. If the user has the 'file explorer' viewlet open, they will see a new folder appear in the viewlet, but that's it.
This change opens the default code file for a SAM app once creation completes. This serves the dual purpose of providing feedback to the user, and saving them time searching for the file.
Additional context: VS Code has the following unfortunate behavior when updating workspace folders:
> ```
> If the first workspace folder is …
```
> Open the main source code file on project creation

- src/shared/defaultAwsContextCommands.ts
When selecting regions to show/hide from the AWS Explorer, the filter would only apply against the region's friendly name. It now applies to the region code as well.
#239 
> Region selector now filters by friendly name and by region code

- src/lambda/models/samLambdaRuntime.ts
Update list of supported runtimes to include `python3.7`, `ruby2.5`, and `dotnetcore2.1`.
SAM CLI has added support for three additional runtimes since our last refresh. We don't currently auto-detect available runtimes (we should probably at least add a test that does this), so a manual update is required.
Follow-up to #326.
> Update list of supported runtimes.

- package.json
- package.nls.json
- src/extension.ts
- src/shared/constants.ts
Added a menu to the AWS panel with the following commands:
```
Connect to AWS
-----
Show region in the Explorer
Hide region in the Explorer
-----
View Documentation (redirects to AWS VS Code page)
View Source on Github
```
Making feature discoverability easier. This will allow users to access some functionality without knowledge of the command palette
https://github.com/aws/aws-toolkit-vscode/issues/313
Tests pass, menu and menu functionalities work correctly on manual test
> Adding general explorer features to menu in AWS pane

- src/lambda/lambdaTreeDataProvider.ts
- src/shared/codelens/typescriptCodeLensProvider.ts
- src/shared/telemetry/telemetryEvent.ts
- src/shared/telemetry/telemetryUtils.ts
Changes the return type of `registerCommand`'s callback from
```typescript
{
result?: T,
datum?: Datum
} | void
```
to
```typescript
T & { datum?: Datum } | void
```
And returns the result of the the callback to the vscode command system.
Currently, `registerCommand`:
1. Swallows the return value of the command callback.
2. Forces commands that return values to include a telemetry datum (rather than using the default datum).
This change addresses those two issues, allowing callbacks with no custom telemetry data to return `T` instead of `{ result: T; datum: Datum }`.
> Allow command callbacks to return values

- src/shared/codelens/localLambdaRunner.ts
After clicking a Run/Debug CodeLens, the output channel is supposed to be shown, so the user can see that the toolkit is building and preparing to invoke the lambda locally. This PR fixes a regression to that behavior.
* Ran toolkit, used run/debug Node and run Python CodeLenses
* Ran tests
> Fix regression where running locally does not bring up the output channel while preparing to invoke

- src/shared/codelens/localLambdaRunner.ts
- src/shared/sam/cli/samCliLocalInvoke.ts
- src/test/shared/sam/cli/samCliLocalInvoke.test.ts
This is one of the initial changes for #349 and #350 - setting up `sam local invoke` calls to support the following args:
* use-container
* docker-network
* skip-pull-image
Previous PR #355 did the same for `sam build` calls.
For now, these args are not hooked into the Toolkit. A follow-up change will integrate them, pending design for #323 (which will influence where these are configured)
#349 and #350 
> Support for use-container, docker-network, skip-pull-image in calls to sam local invoke

- src/shared/telemetry/telemetryUtils.ts
Telemetry registerCommand broke commands registered with multiple parameters.
Bugfix
https://github.com/aws/aws-toolkit-vscode/issues/366
Tests pass, manual checking works
> Allowing unbounded amount of callbackArgs for registered commands

- src/test/lambda/config/samParameterCompletionItemProvider.test.ts
Consolidate test symbol creation into a helper function, which shortens and simplifies test code.
These tests contain a lot of identical boilerplate. This makes it hard to pick out the relevant bits while reading/debugging tests.
#331
> Simplify tests for SamParameterCompletionItemProvider.

- src/shared/sam/cli/samCliLocalInvoke.ts
- src/test/shared/sam/cli/samCliLocalInvoke.test.ts
use-container is not supported by calls to `sam local invoke`. This change removes support for this option from the sam local invoke wrapping code.
* Unit Tests
* locally ran/debugged a node function
> Removed useContainer from sam local invoke calls, it isn't supported there

- src/shared/codelens/pythonCodeLensProvider.ts
Add 'file' scheme to python code lens document selector. This limits the selector to documents that exist on disk.
We don't currently support templateless lambdas, so all lambdas must exist on disk to work with our code lenses.
> Add scheme to python code lens document selector.

- src/shared/credentials/userCredentialsUtils.ts
- src/shared/defaultAwsContextCommands.ts
We now create the `~/.aws` dir if it doesn't exist
Users who didn't have this directory were getting blocked from adding credentials via our wizard
N/A
Manual testing (ran wizard with no `~/.aws` directory and with an empty `~/.aws` directory, the two cases that pop the credential addition wizard.
> Creates the .aws dir if it doesn't already exist

- src/shared/codelens/localLambdaRunner.ts
`vscode.debug.startDebugging` is expected to return true/false. Try again if it returns undefined.
> Attempt to reattach debugger when startDebugging returns undefined

- src/shared/codelens/localLambdaRunner.ts
Removed `onWillAttachDebugger` now that attach debugger `onWillRetry` is in place
> Removing onWillAttachDebugger - it is no longer used

- src/lambda/wizards/samDeployWizard.ts
- src/shared/utilities/projectDefaults.ts
- src/test/shared/utilities/projectDefaults.test.ts
After a user deploys a SAM template, the wizard should remember the selections they specified and use them as defaults. The deployment workflow doesn't change. User can accept the defaults or specify different value at each step in the deployment process. Defaults are stored in hidden directory in their SAM project folder named `.aws-toolkit-vscode` similar to and in the same directory as SAM's own `.aws-sam`. 
```
const filePath = path.resolve(samProjectDir, '.aws-toolkit-vscode/user-prefs.json')
```
Improve user-friendliness.
https://github.com/aws/aws-toolkit-vscode/issues/310
Created new unit tests for `ProjectDefaultsManager`
> Remember selections for sam deploy wizzard

- CHANGELOG.md
- package.json
- src/lambda/lambdaTreeDataProvider.ts
Fixes a case where the AWS Explorer Context menu is leaking into other places in VS Code.
AWS Explorer Context Menu: 
One of the GitLens Extension Panels (as an example)
Before:
After:
* Verified the menu items no longer appear on other extension panels
* Verified the affected menu items still function
* Verified the commands backing the affected menu items still function from the Command Palette
> Prevent AWS Explorer context menu items from getting added to other extension/view menus

- src/lambda/models/samLambdaRuntime.ts
- src/shared/codelens/localLambdaRunner.ts
Removed runtimes that are unsupported by the current version of the AWS Toolkit for VS Code
Having additional runtimes in our Create Sam Application wizard gives the impression that we have full-stack support. Removing these removes the confusion; will add these back in as we add support.
https://github.com/aws/aws-toolkit-vscode/issues/322
Tests pass successfully. List only presents currently-supported options (see screenshot)
> Removing unused runtimes

- src/shared/telemetry/telemetryEvent.ts
- src/shared/telemetry/telemetryUtils.ts
- src/test/shared/telemetry/telemetryUtils.test.ts
Two changes to the telemetry system:
* Added constants for standard metadata field names and values
* `result` and `duration` will now retain existing metadata values if they exist
> Metrics overrides for result and duration

- src/lambda/local/debugConfiguration.ts
- src/shared/clients/dockerClient.ts
- src/shared/codelens/codeLensUtils.ts
- src/shared/codelens/csharpCodeLensProvider.ts
- src/shared/codelens/localLambdaRunner.ts
- src/shared/codelens/pythonCodeLensProvider.ts
- src/test/lambda/local/debugConfiguration.test.ts
- src/test/shared/clients/dockerClient.test.ts
See title.
Debugging lambda functions locally is part of the core feature set of the toolkit. We do not consider a runtime to be supported if it cannot be debugged locally.
#514 
Manually tested locally on Windows only.
Ran all new and existing tests.
> Implement "Debug Locally" code lens for .NET Core.

- package.nls.json
- src/shared/credentials/userCredentialsUtils.ts
- src/shared/defaultAwsContext.ts
- src/test/shared/credentials/userCredentialsUtils.test.ts
- src/test/shared/defaultAwsContext.test.ts
- src/test/utilities/testSettingsConfiguration.ts
addUserDataToContext throws an error if a profile's credentials are nonexistent.
This was causing issues on extension load if a nonexistent profile was selected since the extension load was not handling the error.
Fix for #557 
Added new tests, everything passes. 
Testing with fixes from #577 works as expected (loads if profile exists, resets to default state if profile doesn't)
> addUserDataToContext throws an error if a profile's credentials are nonexistent

- src/shared/filesystem.ts
- src/shared/filesystemUtilities.ts
- src/shared/logger.ts
- src/test/shared/filesystem.test.ts
- src/test/shared/filesystemUtilities.test.ts
When the logger starts up, the logging folder is created prior to initialization. This eliminates a situation (#566) where the logging platform threw an error on initialization, which crashes extension activation.
To support this, I found out that electron apps throw an error if `mkdir` tries to recursively create more than one folder, so I added a drop-in clause that explicitly creates each folder one parent at a time.
#566 
* Regular startup
* started extension in remote WSL session
* ran tests
> Ensure log folder exists prior to initialization

- src/shared/codelens/csharpCodeLensProvider.ts
For .NET Core functions, we were looking at the wrong key in `templates.json`, which caused `event` and `environmentVariables` to be empty. This change uses the right key instead.
> Fix issue that caused templates.json to be ignored when invoking .NET Core functions.

- src/shared/cloudformation/cloudformation.ts
- src/shared/codelens/codeLensUtils.ts
* Do not render codelenses for 'raw' lambdas (which will throw if invoked).
* Fix Python Code Lens Provider to support SAM templates that are in an ancestor directory of the source file.
We removed support for 'raw' lambdas several months ago, but never disabled the rendering of code lenses for this scenario. We will eventually re-enable support for 'raw' lambdas, but for now the code lenses should not be rendered.
* Ran all new and existing tests.
* Manually tried the following:
1. Create a new Python SAM app, verify that code lenses appear.
2. Close and re-open VS Code, verify that code lenses appear.
3. Add a 'raw' handler to the source file, verify that code lenses appear for the original handler, but not the raw handler.
By submitting this pull request, I confirm that my contribution …
> Disable code lenses for 'raw' (template-less) lambdas

- package-lock.json
- src/extension.ts
- src/shared/codelens/pythonCodeLensProvider.ts
If JEDI is enabled and the python document symbol provider returns an empty result, retry until symbols are found or polling times out.
A recent regression in the Python extension for VS Code breaks rendering of code lenses in some cases when JEDI is enabled. If a code lens provider is called twice, and returns `[]` the first time, and a non-empty result the second time, the second result is ignored.
This causes issues because when we first query VS Code for document symbols, they have not yet been loaded, so VS Code returns an empty result. To work around this, when JEDI is enabled, poll the symbol provider until it returns symbols instead of immediately returning if no symbols are found. Include a timeout, in case there truly are no symbols in the document.
This workaround should be …
> Fix rendering of Python code lenses when JEDI is enabled.

- CHANGELOG.md
- src/shared/credentials/userCredentialsUtils.ts
- src/test/shared/credentials/userCredentialsUtils.test.ts
Fix MFA login by passing the session token to our `sts.getCallerIdentity` calls. Other calls should be unaffected.
Broke MFA users
https://github.com/aws/aws-toolkit-vscode/issues/620
Tested logging in as an MFA user. Soon: test other AWS calls (list and deploy operations)
> Fix session token login issues

- CHANGELOG.md
- src/shared/cloudformation/cloudformation.ts
- src/shared/codelens/localLambdaRunner.ts
- src/shared/templates/sam/samTemplateGenerator.ts
- src/test/templates/sam/samTemplateGenerator.test.ts
Local Run and Debug of SAM Applications now uses the MemorySize value if one is set in the SAM Template Resource.
#509 
* ran tests
* Windows: local run/debug of node8, dotnet21, python3.6 with custom `MemorySize` values in the template.yaml file
* Mac: local run/debug of node8, dotnet21, python3.6 with custom `MemorySize` values in the template.yaml file
> Use MemorySize from Sam Template

- src/shared/codelens/csharpCodeLensProvider.ts
Adding a normaized telemetry name for csharp invokes
This will help us track down data on csharp usage better by bringing the metric in line with the other codelens providers.
N/A
Existing tests pass
> Using normalized telemetry name for csharp local invoke

- src/extension.ts
- src/shared/logger.ts
Ensure that all commands record a telemetry event when invoked.
Some of our commands were not registered using our `registerCommand` util, and therefore lacked associated telemetry.
#625 
#634 
* Ran all existing tests.
* Put a breakpoint in TelemetryService.record, and ensured the updated commands record events.
> Ensure that all commands record telemetry.

- src/lambda/lambdaTreeDataProvider.ts
- src/shared/codelens/codeLensUtils.ts
- src/shared/codelens/csharpCodeLensProvider.ts
- src/shared/codelens/pythonCodeLensProvider.ts
- src/shared/codelens/typescriptCodeLensProvider.ts
We are using outdated telemetry names for "invoke locally" and "create new SAM app". This is because the telemetry name passed to `registerCommand` is only used if no datum is provided. If a datum is provided, its name takes precedence.
Our telemetry for this event does not match the other toolkits, nor our own conventions.
#632
* Ran all existing tests.
* Put a breakpoint in `TelemetryService.record`, created a new SAM app. Verified that the correct telemetry name is used.
* Invoked the code lens on the new app. Verified that the correct telemetry name is used.
> Fix telemetry names for lambda_localinvoke and project_new.

- CHANGELOG.md
- package.json
Adding SAM Application commands to the AWS Explorer menu
Users unfamiliar with the Command Palette may not be able to find SAM application-related commands (which make up the majority of the AWS Toolkit's current functionality). This places these items in a location that is more conventional to non-VS Code power users.
Menu items appear and function correctly--created and deployed a SAM app through these menus.
> Adding SAM App commands to the AWS Explorer menu

- src/lambda/wizards/samInitWizard.ts
Pressing Cancel on the "Open Folder" dialog would return the user back to the runtime selection step. To reduce confusion in the workflow, pressing cancel now returns the user to the folder selection step.
* Enter Create SAM App workflow. Progress to the folder selection stage.
* ensure back button returns to the runtime step
* ensure pressing ESC returns to the runtime step
* ensure selecting a folder advances to the app name step
* bringing up the open folder dialog, ensure pressing cancel returns to the folder selection step
* bringing up the open folder dialog, ensure selecting a folder advances to the app name step
> Create Sam App Wizard - Canceling open folder dialog takes user back to folder picker

- package.nls.json
- src/shared/codelens/typescriptCodeLensProvider.ts
If you run a Javascript function, but have your template's runtime set a non-javascript runtime (eg: `python3.7`), the message says the runtime is unsupported, which is misleading. The message has been changed to indicate it is not a valid _javascript_ runtime in order to reduce confusion.
Starting with a new node 8 sam application:
* press run/debug codelenses, see the function run/debug
* change template.yaml resource runtime to `python3.7`, try to run/debug, see new error message, and logged text
* change template.yaml resource runtime to `nodejs8.10x`, try to run/debug, see new error message, and logged text
> Local Invoke (JS) - unsupported runtime is logged, and error message was made more clear

- CHANGELOG.md
- src/shared/regions/defaultRegionProvider.ts
- src/test/shared/regions/defaultRegionProvider.test.ts
Until the Toolkit can support accounts in other partitions, it is confusing to surface regions for those partitions in the UI. All regions from other partitions have been removed.
The only logic change is to check for `partiton === 'aws'`, however I moved some existing code into functions and put tests around them, primarily to validate this change.
#660 
* existing and new tests pass
* Ran the "Show Regions" command, the govcloud and china partition regions aren't listed
* Ran the "Deploy SAM Application" command, the govcloud and china partition regions aren't listed
> Remove regions that aren't in the standard AWS partition (until they can be supported)

- .changes/next-release/Bug Fix-56d4c3e7-0079-4eba-a5b3-b43f278b1032.json
- src/extension.ts
- src/lambda/commands/createNewSamApp.ts
- src/shared/activationLaunchPath.ts
- src/shared/utilities/workspaceUtils.ts
- src/test/shared/activationLaunchPath.test.ts
After creating a SAM App, a file from the application is supposed to auto-load into the editor.
If an app was created, but you selected a different folder instead of choosing one of the existing workspace folders, a file would not be loaded into the editor.
The root cause was attempting to set up a workspace filesystemwatcher on the new folder, but the documentation states that you can only do this against workspace folders. The code was sitting in a promise waiting for an event that would never happen.
I took the opportunity to add a few abstractions in related code.
#678 
* Start with no workspace open, create a SAM App
* Start with a workspace open, create a SAM App to the workspace folder
* Start with a workspace open, create a SAM App to a different folder not contained in the …
> Fix case where app file would not load into editor after SAM App creation

- src/test/shared/codelens/localLambdaRunner.test.ts
This week the commit triggered builds have started sporadically failing. This set of tests was missing some logger initialization. Fixed.
> Fix sporadic test failures by adding missing test logger setup

- .travis.yml
Updating the Travis build scripts:
* switching from trusty (Ubuntu 14.04) to bionic (18.04)
* using the Travis supported headless testing (xvfb) approach
See: https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
> Updated travis build script to use bionic and their supported headless browser testing

- src/awsexplorer/awsExplorer.ts
- src/awsexplorer/defaultRegionNode.ts
- src/lambda/explorer/lambdaNodes.ts
- src/test/awsExplorer/defaultRegionNode.test.ts
- src/test/lambda/explorer/cloudFormationNodes.test.ts
- src/test/lambda/explorer/lambdaNodes.test.ts
- src/test/lambda/explorer/mockLambdaNodes.ts
Renamed `standaloneNodes` to `lambdaNodes`. `standalone` was shorthand for `standalone Lambda functions`, which is less descriptive than directly relating it to Lambdas.
Moved `defaultRegionNode` out of the `lambda` directory structure. This represents the root AWS Explorer node; moving this to a more generic location means it will make more sense when we start building additional non-Lambda-related explorers.
Makes our codebase less confusing
N/A
Existing tests and a manual check work.
> Renaming and reorganizing Lambda nodes

- src/shared/clients/defaultEcsClient.ts
- src/shared/clients/ecsClient.ts
- src/test/shared/clients/defaultEcsClient.test.ts
- src/test/shared/clients/mockClients.ts
listTaskDefinitions returns individual instances of task definitions. listTaskDefinitionFamilies returns top-level names.
We want to display task definition families, not individual instances
https://github.com/aws/aws-toolkit-vscode/issues/714
Reconfigured and ran tests
> listTaskDefinitions -> listTaskDefinitionFamilies

- src/shared/loggerUtils.ts
- src/test/shared/sam/cli/testSamCliProcessInvoker.ts
The goal is to cut down on the sporadic test failures. I suspect the cause is some tests are checking log files for contents before the logger has finished writing those contents.
> Added retry logic to assertLogContainsBadExitInformation in case logger is still writing/flushing

- buildspec/bumpVersion.yml
Without `npm install` the changelog script cannot run (it uses ts-node)
> Added missing npm install before call to create changelog

- src/test/shared/telemetry/defaultTelemetryService.test.ts
Remove sleep from DefaultTelemetryService tests. Test runs go from over 600ms to ~200ms
> Remove sleep from DefaultTelemetryService tests

- src/awsexplorer/awsExplorer.ts
- src/awsexplorer/defaultRegionNode.ts
- src/extension.ts
- src/lambda/commands/createNewSamApp.ts
- src/lambda/commands/deploySamApplication.ts
- src/lambda/explorer/cloudFormationNodes.ts
- src/lambda/explorer/functionNode.ts
- src/lambda/explorer/lambdaNodes.ts
- src/lambda/wizards/samDeployWizard.ts
- src/lambda/wizards/samInitWizard.ts
- src/shared/extensionGlobals.ts
- src/shared/sam/activation.ts
- src/shared/ui/buttons.ts
- src/test/awsExplorer/awsExplorer.test.ts
- src/test/awsExplorer/defaultRegionNode.test.ts
- src/test/lambda/explorer/cloudFormationNodes.test.ts
- src/test/lambda/explorer/lambdaNodes.test.ts
- src/test/lambda/explorer/mockLambdaNodes.ts
- src/test/shared/ui/buttons.test.ts
- src/test/shared/utilities/iconPathUtils.ts
SAM and Explorer nodes passed a function down many layers to ultimately compute icon paths, which are fixed for the lifetime of the extension. The icon paths have been made central, and the function pass-down has been removed to help tidy up the code.
* Tests were updated
* Ran the Toolkit to verify the Explorer icons still show
* Ran the Toolkit to verify the SAM Workflows still show the help icon
> Icon path retrieval has been centralized

- .changes/next-release/Feature-32b6099e-a88c-4dc7-b67b-e8baf66f915d.json
- package-lock.json
- package.json
- src/shared/sam/cli/samCliLocalInvoke.ts
- src/shared/utilities/textUtilities.ts
- src/test/shared/utilities/textUtilities.test.ts
The output of local invoke calls includes ansi codes to color the text. This text renders in the Debug Console, but not the Output tab. This change removes ansi codes from the SAM local invoke output that is sent to the Output tab.
* Ran a local run and a local debug of a lambda handler, verified that the Output tab received cleaner text, and the debug console was still colored.
> Remove Ansi codes from SAM CLI local invoke output when writing to OutputChannel

- src/shared/logger.ts
- src/shared/loggerUtils.ts
- src/test/mockOutputChannel.ts
- src/test/shared/logger.test.ts
I went to write some tests that verified log contents, and it turns out that tests currently have to poll for a log file to materialize, then poll for the log file to get updated, then scrape the contents of the log files. This isn't ideal. It turns out the toolkit's logging could benefit from some encapsulations.
I've tried to make this change disrupt as few files as possible, with plans to make subsequent, incremental changes that will bring logging into a more ideal state.
What's in this change:
* The Toolkit now uses Winston logger to output to the "Toolkit Log" OutputChannel
* The Winston logger, and corresponding concerns from the `Logger` interface, have been encapsulated (in `WinstonToolkitLogger`)
* Ideally these two things would have been separate changes, but they were too …
> Encapsulating Winston Logger

- .changes/next-release/Bug Fix-ef3fc182-9d97-47af-9633-72d09d8622b9.json
- src/integrationTest/sam.test.ts
- src/lambda/commands/createNewSamApp.ts
- src/shared/sam/cli/samCliContext.ts
- src/shared/sam/cli/samCliInit.ts
- src/shared/sam/cli/samCliValidator.ts
- src/test/shared/sam/cli/samCliInit.test.ts
Errors out as expected with:
```
2019-10-14 16:56:09 [ERROR]: Unexpected exitcode (1), expecting (0)
2019-10-14 16:56:09 [ERROR]: Error: undefined
2019-10-14 16:56:09 [ERROR]: stderr: Error: 
ERROR: Missing required parameters, with --no-interactive set.
Must provide one of the following required parameter combinations:
--name and --runtime and --dependency-manager and --app-template
--location
```
> Add --no-interactive to init

- src/awsexplorer/regionNode.ts
- src/lambda/explorer/cloudFormationNodes.ts
- src/test/lambda/explorer/cloudFormationNodes.test.ts
The interface definitions representing CloudFormation related items in the Explorer only have one implementation. They have been removed to help make the code more understandable by removing unnecessary abstractions.
To keep each PR manageable, a separate change is planned with similar changes for the Lambda related Nodes.
* test suite
* ran extension, exercised the CloudFormation related nodes in the Explorer
> Remove interfaces related to CloudFormation Explorer Nodes

- src/awsexplorer/regionNode.ts
- src/lambda/explorer/lambdaNodes.ts
- src/test/lambda/explorer/lambdaNodes.test.ts
The interface definitions representing Lambda related items in the Explorer only have one implementation. They have been removed to help make the code more understandable by removing unnecessary abstractions.
To improve clarity in naming, `LambdaFunctionGroupNode` has also been renamed to `LambdaNode`
* Test suite
* ran extension and exercised the Lambda nodes in the Explorer (Expand, Collapse, Refresh, Context menus)
> Remove interfaces related to Lambda Explorer Nodes

- src/awsexplorer/awsExplorer.ts
- src/lambda/commands/invokeLambda.ts
- src/lambda/explorer/cloudFormationNodes.ts
- src/lambda/explorer/lambdaFunctionNode.ts
- src/lambda/explorer/lambdaNodes.ts
- src/test/lambda/explorer/cloudFormationNodes.test.ts
- src/test/lambda/explorer/lambdaFunctionNode.test.ts
- src/test/lambda/explorer/lambdaNodes.test.ts
Changes to improve code clarity:
* `CloudFormationFunctionNode` and `LambdaFunctionNode` were identical, and there is no need to have two different classes. They have been removed, and the parent class `FunctionNodeBase` has been made non-abstract.
* `FunctionNodeBase` has been renamed to `LambdaFunctionNode`, making it more consistent with other Lambda related nodes
Not in scope for this change:
* Now that the Lambda node classes are cleaner (due to this change and #800), it is easier to reason about their behavior. There is opportunity to clean up and simplify the test cases.
* Test suite
* Launched the toolkit and exercised the AWS Explorer
* checked that Lambda nodes can be deleted, but CloudFormation Lambda nodes cannot
* checked that all Lambda nodes can invoke, and display …
> Converge CloudFormationFunctionNode and LambdaFunctionNode

- .changes/next-release/Bug Fix-57668a32-9c81-4fce-9356-42780cc147c7.json
- package.nls.json
- src/lambda/explorer/cloudFormationNodes.ts
- src/test/lambda/explorer/cloudFormationNodes.test.ts
CloudFormation nodes don't show the user anything when CloudFormation Stacks are not found. They now have a child node indicating that stacks could not be found:
> AWS Explorer indicates when CloudFormation Stacks cannot be found

- .changes/next-release/Bug Fix-7bac53bb-d8cb-42a8-9d31-b268eacc32dc.json
- package.nls.json
- src/lambda/explorer/cloudFormationNodes.ts
- src/shared/treeview/treeNodeUtilities.ts
- src/test/lambda/explorer/cloudFormationNodes.test.ts
CloudFormation Stack child nodes were not explicitly sorted. This change sorts the child nodes and standardizes the child node creation with how Lambda (#814) and CloudFormation (#815) handle their child nodes.
> Sort CloudFormation Stack Resource nodes

- src/cdk/explorer/detectCdkProjects.ts
Addresses a bug where the `path` was being used instead of `fsPath` when determining the location of the CDK construct tree. 
bug was reported by @awschristou 
Using the path works for 
* tested on a Windows machine.
* tests do access the filesystem but we might need to be more rigorous with testing the Windows experience in general
> fix: use the fsPath instead of path to ensure that the tree path is valid for Windows

- src/cdk/activation.ts
- src/cdk/explorer/nodes/appNode.ts
- src/shared/telemetry/telemetryTypes.ts
Adding 2 events that we want to add Telemetry for
* Expansions of `CDK App` Nodes
* Disabling the CDK Explorer
* CDK App node expansion- helps us determine if CDK applications are being opened and that there is interaction with the explorer
* Disabling the CDK Explorer - helps us refine defaults to deliver a great experience
--
* Tested in the explorer locally
* Re-ran the extension tests
> cdk explorer telemetry

- src/test/cdk/detectCdkProjects.test.ts
- src/test/cdk/explorer/appNode.test.ts
Some tests were failing on windows because of the usage of `path` instead of `fsPath`
Extension tests were working fine on OS X, but not on Windows
--
Ran all the extension tests on a Windows desktop
> fix windows tests

- buildspec/bumpVersion.yml
Tagging occurs after release notes are processed now.
> Bump version script no longer tags on version increment.

- buildspec/linuxTests.yml
- buildspec/windowsTests.yml
- Lint was removed from `test` to speed up development time, but it was forgotten to be added to the new build scripts
> Re-add lint to buildscripts

- src/shared/logger/winstonToolkitLogger.ts
- src/test/shared/logger/winstonToolkitLogger.test.ts
Added the ability to change the winston logger's log level.
Motivation: for future use with the integration tests, so that we can see the logged output.
Not in scope: wiring this support into the toolkit, so that configuration changes trigger an update to the logger's log level.
> Added ability to change winston logger's log level

- src/lambda/local/detectLocalLambdas.ts
- src/test/lambda/local/detectLocalLambdas.test.ts
Removing unnecessary code.
The test was unreliable. The function swapped in 'vscode.workspace.workspaceFolders' for the parameter if undefined is passed in, and only the test passed in undefined. So, the test was working under flawed assumptions, for a case that is never used in the codebase.
> Made detectLocalLambdas parameter non-nullable.

- src/shared/codelens/csharpCodeLensProvider.ts
- src/shared/codelens/localLambdaRunner.ts
- src/shared/codelens/pythonCodeLensProvider.ts
Currently, all runtimes wait for an open port before attaching a debugger to a local debug session of a SAM Application. I've wrapped that in a "before attach" style handler in preparation for some upcoming changes, where languages may perform customized checks before proceeding to attach a debugger.
> Creating a before-attach-debugger hook for an upcoming change

- src/awsexplorer/activation.ts
- src/awsexplorer/awsExplorer.ts
- src/shared/telemetry/telemetryTypes.ts
Added a telemetry call to record the number of active regions.  This is called on activation of the AwsExplorer(on startup), showRegion, and hideRegion.  The value that is tracked is the quantity of regions that are currently active for the user.
The purpose of this change is to collect data to help determine the need of having the multiple region feature.
N/A
Launched extension in the VS Code debugger with no errors.  Verified that telemetry was received and accurate.
> Added telemetry to track quantity of active regions

- src/integrationTest/codelens.js.test.ts
- src/integrationTest/integrationTestsUtilities.ts
- src/integrationTest/sam.test.ts
- src/integrationTest/vscode.test.ts
- src/shared/extensions.ts
Moving known Extension IDs to a central set of constants. Related to some upcoming integration test changes.
> Centralize Extension IDs

- buildspec/linuxIntegrationTests.yml
- test-scripts/integrationTest.ts
- test-scripts/launchTestUtilities.ts
An upcoming change aims to resume testing python SAM Applications in the integration tests. The Python extension is necessary for those tests. This change adds the support code to install the extension for the tests.
> Install the Python Extension as part of the Integration Test setup

- src/shared/sam/cli/samCliLocator.ts
- src/shared/utilities/childProcess.ts
Add more logging calls to better diagnose
* Paths checked for SAM CLI
* SAM CLI Location found/used by toolkit
* command line calls made to programs like sam cli
This should help chase down situations like #658 / #701 
> Add logging calls to SAM CLI detection and child process calls

- src/test/shared/defaultAwsContext.test.ts
There were some tests that had some incorrect logic. Their validation code was not running, because it is not exercised in the system under test. This change fixes that.
> Fix test logic for DefaultAwsContext region changes

- .changes/next-release/Feature-155caa37-d5ab-444a-96f5-7dc85373258f.json
- src/shared/sam/cli/samCliValidator.ts
Bumping the max SAM CLI version to 0.50 (exclusive)
> Increase SAM CLI maximum version to 0.50 exclusive

- package.json
Two Schema Search related commands are associated with AWS Explorer node context menus, and operate against explorer nodes. They weren't intended to appear in the Command Palette. This change hides them from the Command Palette.
Fixes #881
* Open the command palette and type "schema". Observe that the commands no longer appear in the list
* Exercised the search commands from the explorer context menus to ensure they still work as expected
> Remove two Schema related search commands from the Command Palette.

- src/lambda/commands/deploySamApplication.ts
- src/lambda/wizards/samDeployWizard.ts
- src/shared/sam/activation.ts
- src/test/lambda/commands/deploySamApplication.test.ts
- src/test/lambda/wizards/samDeployWizard.test.ts
This change removes some RegionProvider usages that are unnecessary, and are getting in the way of upcoming work involving RegionProvider.
The core of this change moves RegionProvider into DefaultSamDeployWizardContext where it is used, instead of through deploySamApplication, which doesn't directly use it.
In toolkit:
* Go backwards and forwards through the Deploy Wizard, verify the pickers work as expected
* deploy a SAM application from the toolkit and verifying that SAM app deployed to my account
> Remove some unnecessary RegionProvider usages

- package.nls.json
- src/shared/defaultAwsContextCommands.ts
Added titles to the pickers to show and hide regions, to better clarify the the prompt.
Was (is it hide or show???): 
Now (Hide):
Now (Show): 
> Added titles to show/hide region picker

- package.json
Json validation on templates.json (local debug configurations) stopped working when the validation file was moved, but the manifest was not updated. This change restores the validation behavior (intellisense and tooltips).
> Fix for missing json validation on local debug configurations

- src/extension.ts
- src/lambda/commands/createNewSamApp.ts
- src/lambda/commands/deploySamApplication.ts
- src/lambda/config/configureParameterOverrides.ts
- src/shared/codelens/localLambdaRunner.ts
- src/shared/extensionUtilities.ts
- src/shared/sam/cli/samCliDeploy.ts
- src/shared/sam/cli/samCliInvokerUtils.ts
- src/shared/sam/cli/samCliLocalInvoke.ts
- src/shared/sam/cli/samCliPackage.ts
- src/shared/utilities/vsCodeUtils.ts
- src/test/lambda/commands/deploySamApplication.test.ts
- src/test/shared/fakeChannelLogger.ts
- src/test/shared/utilities/vsCodeUtils.test.ts
This change cleans up some old logger usage:
* removed all instances where a logger is passed around. Loggers should be obtained with `getLogger`
* ChannelLogger no longer exposes a logger. Calling code can get a logger as needed with `getLogger`
* ChannelLogger tests were rearranged so that each scenario is tested in isolation
* removed console log spam produced by ChannelLogger tests
> Clean up logger usage

- src/shared/regions/defaultRegionProvider.ts
- src/shared/regions/endpoints.ts
- src/test/shared/regions/defaultRegionProvider.test.ts
- src/test/shared/regions/endpoints.test.ts
`Region` had a `description` field, paralleling the endpoints json structure. It isn't as intuitive to develop against, so this change renames it to `name`.
> Rename Region description field to name

- src/shared/telemetry/defaultTelemetryService.ts
If the file doesn't exist it produces a log message like this, which is just noise:
```
2020-02-20 18:13:52 [ERROR]: Error: ENOENT: no such file or directory, open '/Users/jmkeyes/Library/Application Support/Code/User/globalStorage/amazonwebservices.aws-toolkit-vscode/telemetryCache'
at Object.openSync (fs.js:447:3)
at Object.func (electron/js2c/asar.js:138:31)
at Object.func [as openSync] (electron/js2c/asar.js:138:31)
at Object.readFileSync (fs.js:349:35)
at Object.<anonymous> (electron/js2c/asar.js:580:40)
at Object.readFileSync (electron/js2c/asar.js:580:40)
at Function.readEventsFromCache (/Volumes/workplace/aws-toolkit-vscode/dist/src/shared/telemetry/defaultTelemetryService.js:226:41)
at DefaultTelemetryService.<anonymous> …
```
> telemetry: avoid noisy error in logs

- codecov.yml
- Disable the bot comment on PRs.
- Adjust the acceptable threshhold.
- Don't fail PRs if coverage falls by a small amount.
- Overrides the [default yaml](https://docs.codecov.io/docs/codecov-yaml#section-default-yaml)
- waiting on @aws org owner to approve install request of the codecov GitHub app for this repo and aws-toolkit-vscode repo.
- codecov still posts a comment sometimes, even though we specify `comment: false`. That's just a codecov bug.
> CI: code-coverage configuration

- CONTRIBUTING.md
- package-lock.json
- src/test/globalSetup.test.ts
- src/test/lambda/commands/deleteLambda.test.ts
- src/test/shared/systemUtilities.test.ts
- src/test/testLogger.ts
- Logs were not getting written to a file during tests which made it harder to debug, write logs to a file now
- example output:
```
...
=== Starting test "getChannelLogger log level error logs with 2 template params: error, error processTemplate handles this scenario" ===
1st Error 'Error zero'; 2nd error: 'Error one'
Error: Error zero
Error: Error one
=== Ending test "getChannelLogger log level error logs with 2 template params: error, error processTemplate handles this scenario" ===
...
```
> Write test logger output to a file

- .changes/next-release/Bug Fix-10d87a21-1e86-4b17-b0cc-dc6ced1ac5f1.json
- src/shared/sam/cli/samCliDeploy.ts
Toolkit now supports `CAPABILITY_NAMED_IAM`: https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html
Fix https://github.com/aws/aws-toolkit-vscode/issues/943
https://github.com/aws/aws-toolkit-vscode/issues/943
Added the following to a CloudFormation template:
```
Resources:
NamedIam:
Type: AWS::IAM::Role
Properties:
RoleName: 'thisisarole'
AssumeRolePolicyDocument:
Version: 2012-10-17
Statement:
Effect: Deny
Principal:
Service:
ec2.amazonaws.com
Action:
'sts:AssumeRole'
```
Deployed unsuccessfully with the existing toolkit and deployed successfully with my changes. (the error is triggered by the addition of `RoleName: 'thisisarole'`).
> Adding support for CAPABILITY_NAMED_IAM

- .changes/next-release/Bug Fix-f9ca4514-70f4-4ac0-8ed7-06bc56ddfc5b.json
- src/shared/codelens/typescriptCodeLensProvider.ts
- src/shared/typescriptLambdaHandlerSearch.ts
- src/test/typescriptLambdaHandlerSearch.test.ts
Fix for an issue where adding or removing a bunch of newlines before a function declaration in .js files causes CodeLens to position on the wrong lines until the file is saved.
> Fix lagging js CodeLens positions when adding/removing lines above a CodeLens

- .github/ISSUE_TEMPLATE/bug_report.md
Added a comment to the bug report template in the 'Desktop' section to let users know about the new 'About AWS Toolkit' command/option.
The new feature makes it easier for the user to gather and copy the desktop information.  The intent is to lower the 'cost' of filling out the bug report.  This comment brings awareness to the new option.
The 'About AWS Toolkit' command was implemented in PR #932 
> Added guidance to bug report about the new About AWS Toolkit command

- CONTRIBUTING.md
Updating contributing doc
Update doc while it's fresh in our minds
https://github.com/microsoft/vscode/issues/90484
Ran the extension multiple times in debug mode/ran tests on my local machine and could not get tests into a broken state.
> Updating Contributing doc with updated info

- package.nls.json
- src/awsexplorer/activation.ts
- src/awsexplorer/awsExplorer.ts
- src/credentials/activation.ts
- src/credentials/loginManager.ts
- src/credentials/providers/credentialsProviderManager.ts
- src/credentials/providers/sharedCredentialsProviderFactory.ts
- src/shared/defaultAwsContextCommands.ts
- src/test/awsExplorer/awsExplorer.test.ts
- src/test/credentials/provider/credentialsProviderManager.test.ts
1. Auto-connect: If there is exactly one profile, connect to it automatically.
2. Show "Connecting..." message in the AwsExplorer root-node during early init.
- On init, the AwsExplorer root-node doesn't know yet if we will auto-connect. After attempting auto-connect (`loginWithMostRecentCredentials()`) we can then update the text to "Connect to AWS..." call-to-action.
3. TODO: avoid auto-connect for MFA/SSO.
- Problem: doesn't look like `getMfaTokenFromUser()` is ever called, and I don't see any conditions that would lead to that.
- Manual testing with different forms of `~/.aws/*` 
- Integration tests exercise the `loginWithMostRecentCredentials()` codepath. 
- TODO: however, we should add explicit testing for all the login scenarios
By submitting this pull request, I confirm that my …
> activation: auto-connect

- src/credentials/activation.ts
- src/credentials/providers/credentialsProvider.ts
- src/credentials/providers/credentialsProviderId.ts
- src/credentials/providers/credentialsProviderManager.ts
- src/credentials/providers/sharedCredentialsProvider.ts
- src/shared/defaultAwsContextCommands.ts
- src/test/credentials/provider/credentialsProviderManager.test.ts
- src/test/credentials/provider/sharedCredentialsProvider.test.ts
- src/test/shared/credentials/loginManager.test.ts
test case:
1. add to `~/.aws/credentials`:
```
mfa_serial=arn:aws:iam::1234567:mfa/cc2-toolkit-role-assumer
```
2. ensure that `…/Code/User/settings.json` has not stored `aws.profile`   from a previous login
3. invoke the Toolkit
4. Toolkit should _not_ auto-connect, because of the presence of `mfa_serial`
todo:
- check for SSO
> activation: do not auto-connect MFA credentials

- build-scripts/generateConfigurationAttributes.ts
- package.json
- src/shared/sam/debugger/awsSamDebugConfiguration.ts
- src/shared/sam/debugger/awsSamDebugger.ts
This requires the value of invokeTarget to be one of the subtypes
The type generator generates a type union for this with two different interfaces
VSCode is smart enough to filter available properties to the type being specified
This generates the two subtypes with proper constraints and gives the user better autocomplete.
```ts
/* tslint:disable */
/*!
* Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
* SPDX-License-Identifier: Apache-2.0
*/
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/
import * as vscode from "vscode";
export interface AwsSamDebuggerConfiguration extends vscode.DebugConfiguration { …
```
> Use oneOf for the different aws-sam invokeTarget types

- .vscode/launch.json
- third-party/test/index.ts
VSCode seems to refuse to unset an env var used in the test
Explicitly always passing it and checking for the string 'null'
Switching between "single test" and "all test" launches creates problems with environment variables that hang around and it's unclear how to unset them.
> Workaround weird env behavior during testing

- src/lambda/wizards/samInitWizard.ts
- src/test/lambda/wizards/samInitWizard.test.ts
- Problem: "Create new SAM app" command asks for "app name" in the final step of the wizard, but it just cycles
- ... because `CreateNewSamAppWizard.name` never gets set
- ... because promptUserForName() returns value instead of a Promise.
- Solution: return Promise from promptUserForName().
- Also (unrelated enhancement): pre-populate the "app name" step with  the workspace/folder name.
Test case:
1. invoke the  `Create new SAM Application` command on a new, empty
folder/workspace.
2. fill out the fields until the final step, which asks for an app name.
3. the wizard loops back to the "location" step instead of completing
the action.
> command/createNewSamApp: fix "Name" input step

- src/integrationTest/stepFunctions/visualizeStateMachine.test.ts
- src/stepFunctions/utils.ts
This change improves visualizeStateMachine test stability
* the test wasn't set up to run on its own, added a missing call to activate the extension, because it calls a command registered by the extension
* the first test that runs the visualizer command has been given a larger timeout, to give test machines (and other systems that don't have the visualizer cached) a chance to download the visualizer. This reveals a code smell -- perhaps the cache component can be isolated a little better than it is currently (@alanbo )
> visualizeStateMachine stability improvements

- third-party/test/index.ts
(node:719) DeprecationWarning: useColors is DEPRECATED and will be removed from a future version of Mocha. Instead, use the "color" option
> test: fix deprecated API usage

- third-party/test/index.ts
`globalSetup` is required for various tests. Include it when running
a single test file (i.e. `$TEST_FILE` is defined via the "Extension
Tests (current file)" task in `launch.json`).
Note: to confirm that the before() and beforeEach() in globalSetup are
executed before any tests, create a test sibling to globalSetup.test.ts,
and observe that the globalSetup before/beforeEach are executed before
executing the "AAA" test:
src/test/aaaa.test.ts:
import { getLogger } from '../shared/logger'
beforeEach(async function() {
console.log('aaaaa BEFOREEACH')
})
describe('AAA', async () => {
it('AAA test', async () => {
getLogger()
})
})
> test: run globalSetup when running single test

- package.nls.json
- src/shared/cloudformation/templateSymbolResolver.ts
- src/shared/codelens/samTemplateCodeLensProvider.ts
- src/shared/debug/launchConfiguration.ts
- src/shared/sam/activation.ts
- src/shared/sam/debugger/awsSamDebugConfiguration.ts
- src/shared/sam/debugger/awsSamDebugConfigurationProvider.ts
- src/shared/sam/debugger/awsSamDebugConfigurationValidator.ts
- src/shared/sam/debugger/commands/addSamDebugConfiguration.ts
- src/test/shared/cloudformation/cloudformation.test.ts
- src/test/shared/cloudformation/cloudformationTestUtils.ts
- src/test/shared/cloudformation/templateSymbolResolver.test.ts
- src/test/shared/codelens/samTemplateCodeLensProvider.test.ts
- src/test/shared/debug/launchConfiguration.test.ts
- src/test/shared/sam/debugger/awsSamDebugConfigurationProvider.test.ts
- src/test/shared/sam/debugger/awsSamDebugConfigurationValidator.test.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
Register CodeLensProvider for SAM templates
- Files must match the pattern *template.{yml/yaml/json}
- For yaml, the yaml extension from RedHat must be installed
Show CodeLenses above Functions
- Text is 'Add Debug Config'
- Doesn't show if a config already exists in launch.json
Register `aws.addSamDebugConfiguration` command
- Appends config to top of launch.json and opens in
Note: Telemetry and AWS::Lambda::Function are TODO
This makes it easier to configure local debugging for SAM functions
[Design doc](https://github.com/aws/aws-toolkit-vscode/blob/master/designs/sam-debugging/local-sam-debugging.md)
Unit tests for all changes.
> Show CodeLenses for SAM functions in CloudFormation templates

- package.nls.json
- src/credentials/awsCredentialsStatusBarItem.ts
Change the statusbar text from `AWS Credentials: ...` to `AWS: ...`.
Our statusbar widget occupies more space than most statusbar widgets, unnecessarily.
- "AWS" is enough to recognize the Toolkit statusbar widget.
- "AWS: Credentials" is hyper-specific, we should use this widget to   reveal more than just credentials (e.g. context-specific messages for  the current document).
- Users will appreciate allowing room for other statusbar widgets.
- Mentioning "Credentials" is redundant anyway, because usually  a "profile:" prefix is shown.
> UI: minimize statusbar verbiage

- package.json
Fixes https://github.com/aws/aws-toolkit-vscode/issues/1027 .
VS Code apparently doesn't like `$ref` tags in the package.json file. Our use-case was narrow enough that we don't need to have `$ref` tags for now although I will reach out considering that it may be useful in the future.
Built and tested a webpacked version: loading the extension did not cause errors in the `launch.json` or `settings.json` files.
> Fix JSON validation issue

- .changes/next-release/Feature-bf18bc73-f20c-490e-8d2d-28669f945360.json
- src/shared/sam/cli/samCliValidator.ts
Bump maximum (exclusive) supported SAM CLI version from 0.50.0 to 0.60.0
SAM is currently on version 0.47.0 and will likely go into the fifties soon
> Increase max SAM version from 0.50.0 to 0.60.0

- src/shared/filesystemUtilities.ts
- src/shared/sam/debugger/awsSamDebugger.ts
- src/test/shared/filesystemUtilities.test.ts
If directory has trailing slashes, they do not change the logical question of whether some other path is a descendant of the directory.
> isInDirectory(): handle trailing slashes

- .changes/next-release/Breaking Change-d7152d4c-71b8-445e-8900-a1349bf01a72.json
- package.json
Toolkit version 1.8.0 introduced a unseen VS Code engine version requirement: the LSP client requires VS Code 1.42.0 or greater. Adding this dependency to our `package.json` so that way the extension can't be installed on lower versions of VS Code.
Brought to our attention in https://github.com/aws/aws-toolkit-vscode/issues/1041 .
> Bumping VS Code minimum version: 1.31.1 => 1.42.0

- src/shared/telemetry/awsTelemetryOptOut.ts
- src/test/shared/telemetry/awsTelemetryOptOut.test.ts
The telemetry opt-in setting is an enum, but our code was reading/writing it as a nullable boolean. At some point, VS Code started to treat this as unexpected data, changing the setting to the default, which is "defer to the IDE".
This change stops the bleeding by adding correct reading/writing of the field going forward. Improving quality of code in adjacent areas is out of scope.
Test plan:
* manually set the setting to "Enabled", activated extension, saw that metrics are opted in
* manually set the setting to "Disabled", activated extension, saw that metrics are opted out
* manually set the setting to use the IDEs setting, activated extension, saw that metrics follow suit
* manually set the setting to garbage, activated extension, saw that metrics follow the default (use the IDE)
By …
> Fix issue where Telemetry preference is incorrectly changing

- src/test/lambda/wizards/samInitWizard.test.ts
When you run some tests using mocha's `.only` clause, there are some other tests that are additionally run. This change fixes that bug.
> Fix gratuitous tests running when using .only

- .changes/next-release/Feature-f8fd7312-74ee-44de-af95-d8a21bee8f48.json
- package-lock.json
- src/stepFunctions/commands/visualizeStateMachine.ts
- src/stepFunctions/utils.ts
- src/test/stepFunctions/utils.test.ts
I'm filtering the diagnostics removing ones that contain reference to arn regex. This is a temporary solution. Ideally, in the future, amazon-states-language-service will output error codes that we will be able to use for filtering.
Customers expect to be able to visualize state machines when ARN's are invalid in asl file. ARN's are often not known at the development time so the developers use placeholders. 
#1017 
#1016 
I've tested the change manually.
> Allows for state machine visualisation on invalid ARN

- src/integrationTest/codelens.js.test.ts
- src/integrationTest/sam.test.ts
- src/shared/codelens/codeLensUtils.ts
- src/shared/codelens/csharpCodeLensProvider.ts
- src/shared/codelens/pythonCodeLensProvider.ts
- src/shared/codelens/samTemplateCodeLensProvider.ts
- src/shared/codelens/typescriptCodeLensProvider.ts
- src/shared/lambdaHandlerSearch.ts
- src/shared/sam/activation.ts
- src/shared/sam/debugger/awsSamDebugConfiguration.ts
- src/shared/sam/debugger/commands/addSamDebugConfiguration.ts
- src/shared/typescriptLambdaHandlerSearch.ts
- src/test/shared/codelens/samTemplateCodeLensProvider.test.ts
- src/test/typescriptLambdaHandlerSearch.test.ts
Removed the `Run Local` and `Debug Local` codelenses from potential SAM function handlers (see #1049) In their place, we now draw "Add Debug Configuration" codelenses which, when clicked, creates a launch config that looks like:
```
{
"type": "aws-sam",
"request": "direct-invoke",
"name": 'handler.name' // TODO: Something friendlier?,
"invokeTarget": {
"target": "code",
"projectRoot": "/absolute/path/to/handler" // TODO: Relative to workspace?,
"lambdaHandler": "handler.name" // same as 'name' field, although this will stay this way.
}
}
```
Also standardized some codepaths (JS and C# codelens drawing is a bit more uniform)
Next steps (out of scope for this PR):
* Implement `code`-type `aws-sam` launch config functionality
* Code cleanup (pruned pathways, commented-out code, etc., all …
> `Run Local` and `Debug Local` Codelenses in .js, .py, and .cs files => `Add Debug Configuration` Codelenses

- src/shared/codelens/pythonCodeLensProvider.ts
- src/test/shared/codelens/pythonCodeLensProvider.test.ts
Incorrect slice on the handler name. Found via manual testing. Confirmed working via manual testing.
> Correcting Python handler parsing

- src/lambda/local/debugConfiguration.ts
- src/lambda/models/samLambdaRuntime.ts
- src/shared/codelens/codeLensUtils.ts
- src/shared/sam/debugger/awsSamDebugConfiguration.ts
- src/shared/sam/debugger/awsSamDebugger.ts
- src/shared/sam/debugger/commands/addSamDebugConfiguration.ts
Missed in https://github.com/aws/aws-toolkit-vscode/pull/1054/ ; adds a runtime field to the code handlers.
Picks the first runtime in the runtime set for each language and added a note specifying that the runtimes are now ordered and should have the newest runtime first.
Runtime is necessary to correctly interpret the code handlers.
Shows up correctly for files of the three language types we target.
> Adding runtime field to code debug types

- src/shared/sam/debugger/commands/addSamDebugConfiguration.ts
`aws-sam` launch configs have relative paths instead of absolute ones
Relative paths are smaller, make more contextual sense, and make it easier for users to share workspace configs.
Manual testing for both template and code type codelenses.
> Launch configs created by the toolkit use relative paths instead of absolute

- src/shared/sam/debugger/awsSamDebugger.ts
- src/shared/sam/debugger/samDebugSession.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
...by moving the EXECUTE phase into the DebugAdapter.
- CONFIG phase: `resolveDebugConfiguration()`
- EXECUTE phase: `samDebugSession.attachRequest()`
> SAM debugconfig: eliminate magic "__noInvoke" field

- .vscode/settings.json
- CONTRIBUTING.md
vscode crawls the files in `testFixtures`, reports errors, tries to suggest plugins, etc.:
Why doesn't the "exclude" in `tsconfig.json` suffice?
> project: tell vscode to ignore testFixtures

- src/shared/telemetry/activation.ts
Mitigate https://github.com/aws/aws-toolkit-vscode/issues/1071
- Exceptions like this are found in CodeBuild jobs `vscodeLinuxTests`
and `vscodeWindowsTests` (and Travis) since 0e199e8727a6:
```
rejected promise not handled within 1 second: TypeError: Cannot set property 'telemetryEnabled' of undefined
stack trace: TypeError: Cannot set property 'telemetryEnabled' of undefined
at applyTelemetryEnabledState (/Users/travis/build/aws/aws-toolkit-vscode/dist/src/shared/telemetry/activation.js:9:5779)
at Object.<anonymous> (/Users/travis/build/aws/aws-toolkit-vscode/dist/src/shared/telemetry/activation.js:9:4573)
at /Users/travis/build/aws/aws-toolkit-vscode/dist/src/shared/telemetry/activation.js:9:1746
at new Promise (<anonymous>)
at __awaiter …
```
> telemetry: handle stale onDidChangeConfiguration handler

- src/lambda/local/debugConfiguration.ts
- src/shared/cloudformation/templateRegistry.ts
- src/shared/codelens/csharpCodeLensProvider.ts
- src/shared/sam/debugger/awsSamDebugConfiguration.ts
- src/shared/sam/debugger/awsSamDebugger.ts
- src/shared/sam/debugger/commands/addSamDebugConfiguration.ts
- src/test/shared/cloudformation/templateRegistry.test.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
Test case:
1. delete `launch.json` file
2. open `template.yaml`
3. select the Debug/Run sidebar in VSCode
4. click the "creat a launch.json file" link
5. select "AWS SAM: Debug Lambda ..."
the generated JSON should look like this:
invokeTarget": {
"samTemplatePath": "template.yaml",
...,
}
previously it looked like like this:
invokeTarget": {
"samTemplatePath": "/full/path/to/template.yaml",
...,
}
> SAM debugconfig: generate workspace-relative paths

- src/lambda/local/debugConfiguration.ts
- src/shared/codelens/csharpCodeLensProvider.ts
- src/shared/codelens/localLambdaRunner.ts
- src/shared/codelens/pythonCodeLensProvider.ts
- src/shared/codelens/typescriptCodeLensProvider.ts
- src/shared/sam/debugger/awsSamDebugger.ts
- src/shared/sam/debugger/samDebugSession.ts
- src/test/lambda/local/debugConfiguration.test.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
- Handle the `noDebug` case. This is when the user invokes the debugconfig via the `Run: Start Without Debugging` vscode command.
> SAM debugconfig: fix "Run Without Debugging"

- src/shared/codelens/csharpCodeLensProvider.ts
- src/shared/codelens/pythonCodeLensProvider.ts
- src/shared/codelens/typescriptCodeLensProvider.ts
- src/shared/sam/debugger/awsSamDebugger.ts
- src/shared/sam/debugger/samDebugSession.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
Followup to ae0d28179b8d. The changes in that commit are "good enough" for python/nodejs, but the csharp codepath still attaches and starts debugging.
The full, proper fix is to set `request='launch'` instead of `request='attach'`.
> SAM debugconfig: fix "Run: Start Without Debugging"

- package.nls.json
- src/shared/codelens/csharpCodeLensProvider.ts
- src/shared/codelens/localLambdaRunner.ts
- src/shared/codelens/pythonCodeLensProvider.ts
- src/shared/codelens/typescriptCodeLensProvider.ts
- src/shared/sam/debugger/samDebugSession.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
- The `invokeXXLambda` family of functions is mostly redundant.  Move the  common logic in to `invokeLambdaFunction()`.
- Eliminate `OnLocalInvokeCommandContext`.
- This also adds telemetry for the python/nodejs cases.
- 3f1b35b Avoid potential race between invoke, exit 
- Wait before emitting TerminatedEvent.
> SAM debugconfig: DRY

- src/extension.ts
- src/shared/codelens/codeLensUtils.ts
- src/shared/extensions.ts
- src/shared/sam/activation.ts
- src/test/fakeExtensionContext.ts
- src/test/lambda/local/debugConfiguration.test.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
VSCode 1.45 (but not 1.44 or earlier) seems to have a problem with this:
const extContext: ExtContext = {
...context,
It throws an exception. ~~Use inheritance instead of destructuring/composition to workaround it.~~ edit: use a nested property instead.
Exception details:
2020-05-06 14:02:36 [ERROR]: Error Activating AWS Toolkit Error: [amazonwebservices.aws-toolkit-vscode]:
Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api amazonwebservices.aws-toolkit-vscode
at a (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:591:810)
at Object.t.checkProposedApiEnabled (/Applications/Visual Studio Code - …
> ExtContext: fix vscode 1.45 activation failure

- src/shared/sam/debugger/awsSamDebugConfiguration.ts
- src/shared/sam/debugger/awsSamDebugger.ts
- src/shared/sam/debugger/commands/addSamDebugConfiguration.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
Resource/lambda names may be generic. This is an attempt to help the user by adding a suffix to the generated config names.
> SAM debugconfig: append runtime to generated config name

- package-lock.json
- package.nls.json
- src/shared/codelens/localLambdaRunner.ts
- src/shared/codelens/pythonCodeLensProvider.ts
- src/shared/sam/cli/samCliLocalInvoke.ts
- src/shared/utilities/timeoutUtils.ts
- src/test/shared/utilities/timeoutUtils.test.ts
Problem: the default timeout of 30 seconds makes pulling images time out consistently on slow connections. So, reset the timer every time we get text from SAM which gives us an indication it's still trying to do something. We will still timeout if SAM hangs, but this way we can pull large images without customer confusion.
> Make SAM timeout dynamic so images can be pulled on slow connections

- .vscode/launch.json
- src/shared/telemetry/activation.ts
- src/test/stepFunctions/commands/visualizeStateMachine.test.ts
Fix / suppress tests
* Tests were failing in travis due to a race condition where web view was used after disposed. Those tests are commented out while a fix is being worked on in #1071
* VSCode `null` environment variable behavior changed. Previously `null` would result in the string 'null'. A behavior change made it so `null` variables were ignored (value unchanged). Making this explicit to approximate an "unset" operation.
* Telemetry test rapidly switch `ext.telemetry` from set to unset. A decoupled event emitter fires at some point during the test while it is unset. Adding an explicit ignore for this usecase.
> Workaround test issues

- src/shared/codelens/codeLensUtils.ts
- src/shared/debug/launchConfiguration.ts
- src/shared/sam/debugger/awsSamDebugConfiguration.ts
- src/test/shared/debug/launchConfiguration.test.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
Test case:
1. with empty launch.json...
2. visit code file and click "add debug config"
- the `projectRoot` is relative to workspace
3. visit template.yaml and click "add debug config"
4. BUG: the `projectRoot` added in (2) is now absolute
5. you can swap steps (2) and (4), same result
This happens because somehow `DefaultDebugConfigSource.getDebugConfigurations()`
returns the existing configs with *absolute* paths:
class DefaultDebugConfigSource implements DebugConfigurationSource {
...
public getDebugConfigurations(): vscode.DebugConfiguration[] {
return this.launch.get<vscode.DebugConfiguration[]>('configurations') ?? []
}
...
}
> SAM debugconfig: ensure relative paths

- src/shared/codelens/pythonCodeLensProvider.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
- SAM debugconfig: fix for deep project trees
- add `target=template` tests for dotnet
- cleanup tests: use actual `template.yaml` in `testFixtures/` instead of  creating a fake.
> SAM debugconfig: fix for deep project trees

- codecov.yml
PR's should only fail if coverage on the diff falls below threshold.
> Make codecov informational by default

- .changes/next-release/Feature-5efec0b4-52f8-465a-8cb2-6b9f7df38751.json
- package-lock.json
- package.json
- src/integrationTest/stepFunctions/visualizeStateMachine.test.ts
- src/stepFunctions/commands/visualizeStateMachine/aslVisualization.ts
- src/stepFunctions/utils.ts
- src/test/stepFunctions/commands/visualizeStateMachine.test.ts
- src/test/stepFunctions/utils.test.ts
Basic visualization capability for state machines defined in yaml.  
We want to give users basic capability to visualize valid state machines in yaml. This won't be an official release and we will not provide errors or linting when the state machine definition is incorrect. 
> Adds visualisation of yaml state machine definitions

- package.nls.json
- src/eventSchemas/commands/downloadSchemaItemCode.ts
- src/test/eventSchemas/commands/downloadSchemaItemCode.test.ts
We recently introduced a feature to let users pick whether or not they would like to override conflicting files during schemas download code bindings. Upon collision, there would a modal displayed with No, Cancel and Yes buttons. Currently both No and Cancel button acts in a a same way and proceeds download by not overriding files.  This commit aims at to fix the Cancel button behavior by cancelling the download code bindings operation.
https://github.com/aws/aws-toolkit-vscode/pull/1089
Added new unit tests.
Locally did end to end testing in my laptop.
> Cancel download code bindings operation when user picks Cancel in the collision prompt

- src/lambda/models/samLambdaRuntime.ts
- src/lambda/wizards/samInitWizard.ts
- src/shared/sam/debugger/awsSamDebugConfiguration.ts
- src/shared/sam/debugger/commands/addSamDebugConfiguration.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
Codelenses in source now prompt the user on which runtime to use for the created debug config instead of assuming the newest.
CONSIDERATION: now that we're creating a quick pick, should we also use a quick pick instead of the modal that pops up when using a template codelens with a legacy configuration?
Results of a bug bash
Tested manually with all three runtime families.
> Code-type codelenses now prompt for a runtime

- package-lock.json
- package.json
- src/cdk/explorer/awsCdkExplorer.ts
- src/cdk/explorer/detectCdkProjects.ts
- src/eventSchemas/wizards/schemaCodeDownloadWizard.ts
- src/lambda/wizards/samInitWizard.ts
- src/shared/wizards/multiStepWizard.ts
This matches our minimum supported vscode version
Our types should match our min supported vscode version. I noticed the discrepancy when I was trying to use the codicons but the constructor was only declared public in `1.42.0`.
Tests pass
> Upgrade @types/vscode to 1.42.0

- package.json
- package.nls.json
- src/lambda/config/templates.ts
- src/lambda/local/debugConfiguration.ts
- src/lambda/local/detectLocalLambdas.ts
- src/shared/sam/debugger/awsSamDebugConfiguration.ts
- src/shared/sam/debugger/awsSamDebugConfigurationValidator.ts
- src/shared/sam/debugger/awsSamDebugger.ts
- src/shared/sam/debugger/csharpSamDebug.ts
- src/shared/sam/debugger/pythonSamDebug.ts
- src/shared/sam/debugger/samDebugSession.ts
- src/shared/sam/debugger/typescriptSamDebug.ts
- src/shared/sam/localLambdaRunner.ts
- src/shared/utilities/workspaceUtils.ts
- src/test/lambda/local/debugConfiguration.test.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
- src/test/testUtil.ts
- src/testFixtures/workspaceFolder/js-manifest-in-root/template.yaml
- SAM debugconfig: always include "event", "environmentVariables"
- When generating new debugconfigs, always include the "event" (aka payload) and "environmentVariables" fields. This improves discoverability and makes it clear that `{}` is sent as the payload.
- SAM debugconfig: pass env vars, memoryMb, timeout
- ~~Merge template.yaml env with env (if any) defined in the config (launch.json).~~ **Update:** Create `input-template.yaml` and `env-vars.json` [according to legacy/SAM rules](https://github.com/aws/aws-toolkit-vscode/pull/1100#discussion_r432213707).
- SAM debugconfig: support `event.path`
> SAM debugconfig: pass env vars and other fields

- src/shared/codelens/codeLensUtils.ts
- src/shared/codelens/samTemplateCodeLensProvider.ts
- src/shared/debug/launchConfiguration.ts
- src/test/shared/codelens/samTemplateCodeLensProvider.test.ts
- src/test/shared/debug/launchConfiguration.test.ts
"Add Debug Configuration" codelenses in source files used to draw at all times if they met the criteria for codelenses. This change mimics the template.yaml approach which hides the codelenses if a configuration already exists for the file in question.
Gave users mixed feedback since templates and source files worked differently.
> Configuration codelenses in source files don't draw if a config exists

- src/test/fakeExtensionContext.ts
- src/test/shared/codelens/localLambdaRunner.test.ts
Use FakeExtensionContext.getNew() instead, which forces re-initialization of ExtensionDisposableFiles and avoids an exception if it was already initialized.
ref: https://github.com/aws/aws-toolkit-vscode/pull/1097/files#r435476880
Other tests may call ExtensionDisposableFiles.initialize(), which causes an error (all tests run in the same process):
Error: ExtensionDisposableFiles already initialized
at Function.<anonymous> (dist/src/shared/utilities/disposableFiles.js:9:4556)
at /codebuild/output/src753373494/src/github.com/aws/aws-toolkit-vscode/dist/src/shared/utilities/disposableFiles.js:9:1746
at new Promise (<anonymous>)
at __awaiter (dist/src/shared/utilities/disposableFiles.js:9:662)
at Function.initialize …
> localLambdaRunner.test.ts: avoid ExtensionDisposableFiles.initialize()

- designs/sam-debugging/local-sam-debugging.md
- package.json
- src/shared/sam/cli/samCliBuild.ts
- src/shared/sam/cli/samCliLocalInvoke.ts
- src/shared/sam/debugger/csharpSamDebug.ts
- src/shared/sam/debugger/samDebugSession.ts
- src/shared/sam/localLambdaRunner.ts
- src/test/shared/codelens/localLambdaRunner.test.ts
- localLambdaRunner.ts: eliminate executeSamBuild()
- "execute sam build" is already abstracted via `SamCliBuildInvocationArguments`, so `executeSamBuild()` is unnecessary.
- localLambdaRunner.ts: support sam.buildArguments, sam.localArguments
- change type of `sam.buildArguments` to "array"
- change type of `sam.localArguments` to "array"
- append the args to the end of the SAM invocations
> SAM debugconfig: support sam.buildArguments, sam.localArguments

- package-lock.json
- package.json
- src/extension.ts
Emit a metric indicating how long the toolkit takes to activate. This helps us find out the current performance, and long term try to drive it down below 250ms (per guidance from the VS Code team)
Here is a sample of the metrics that are emitted:
> Add Toolkit Initialization metric

- src/shared/sam/debugger/csharpSamDebug.ts
- src/test/lambda/local/debugConfiguration.test.ts
- src/test/shared/sam/cli/samCliBuild.test.ts
- src/test/shared/sam/cli/samCliLocalInvoke.test.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
- fix placement of `.vsdbg` (dotnet debugger)
- add some explicit test coverage of `sam.localArguments` `sam.buildArguments` (see d0963c9)
> SAM debugconfig: fix placement of .vsdbg

- src/shared/sam/debugger/typescriptSamDebug.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
Before: debugging stops at line 1 of the runtime bootstrap file; user must explicitly "Continue" to proceed with debugging.
After: debugging does not stop until a user breakpoint is hit.
> SAM debugconfig: default to stopOnEntry=false

- package.nls.json
- src/shared/sam/cli/samCliLocalInvoke.ts
- src/shared/sam/localLambdaRunner.ts
- src/shared/utilities/childProcess.ts
Problem: ENOENT error during the "sam invoke" step when attempting to
debug, which causes SAM debug to fail:
> ```
> Building SAM Application...
> Build complete.
> Starting the SAM Application locally (see Terminal for output)
> Running command: sam local invoke awsToolkitSamLocalResource --template /tmp/aws-toolkit-vscode/vsctk7JaaJI/output/template.yaml --event /tmp/aws-toolkit-vscode/vsctk7JaaJI/event.json --env-vars /tmp/aws-toolkit-vscode/vsctk7JaaJI/env-vars.json -d 5883
> Error running local SAM Application: spawn sam ENOENT
> Waiting for SAM Application to start before attaching debugger...
> Local invoke of SAM Application has ended.
> ```
Solution: When setting env vars one must also copy the current environment, else it is discarded.
- ref …
> samCliLocalInvoke.ts: fix environment spec

- .gitignore
- CONTRIBUTING.md
- build-scripts/packageAlpha.ts
- package.json
- package.nls.json
- src/extension.ts
- src/shared/extensionUtilities.ts
- src/shared/extensions.ts
- `npm run packageAlpha` creates an artifact that can be delivered to  users for testing alpha builds. It creates artifact: `aws-toolkit-vscode-1.99.0-SNAPSHOT.vsix`
- Show a warning message on startup if the extension version is   alpha.
> build: introduce "packageAlpha" task

- src/shared/vscode/window.ts
- src/test/lambda/commands/deleteLambda.test.ts
- src/test/mockOutputChannel.ts
- src/test/shared/vscode/fakeWindow.ts
Add fakes for tracking and "clicking" buttons shown in messages
This lets us verify that the correct buttons are shown and the correct action is taken on click.
e.g.
```typescript
// Simulate Cancel being clicked
const window = new FakeWindow({ message: { warningSelection: 'Cancel' } })
await deleteFileCommand(window)
// Verify delete wasn't performed
verify(s3.deleteObject(anything())).never()
```
* Update S3 UI with new commands other improvements #1153
* Implement more APIs for S3 client wrapper #1155
* Add S3 delete commands and tweak others #1156 
> Add fakes for tracking and "clicking" buttons shown in messages

- src/shared/utilities/disposableFiles.ts
- src/test/fakeExtensionContext.ts
- src/test/shared/utilities/disposableFiles.test.ts
Some tests implicitly depend on the global `ExtensionDisposableFiles.INSTANCE`, other tests clear it, but it is not correctly re-initialized.
Use `clearInstance()`, and rearrange its logic to avoid a race condition. Hoist `TestExtensionDisposableFiles` into `FakeExtensionContext` so it can use `clearInstance()`.
Previous attempt to fix this in https://github.com/aws/aws-toolkit-vscode/pull/1133 was incomplete, and only "worked" by accident. Problem resurfaces in `feature/debugconfig` because it has more tests that depend on `ExtensionDisposableFiles.INSTANCE`.
Rearrange `clearInstance()` so that
ExtensionDisposableFiles.INSTANCE = undefined
is the first step. Because `del.sync()` does file IO, node may switch to another context while it waits on the file IO.
Fixes this error (among …
> disposableFiles: fix edge cases again

- src/shared/sam/localLambdaRunner.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
- Problem: Since 7b5aae7cf1133539e6a1d1070f9385a0608b13af , `target=template`  uses the original resource name instead of the dummy name  `awsToolkitSamLocalResource`.  But we forgot to update the name in  `env-vars.json`, so envvars specified in `launch.json` were not  applied.
- Solution: use the correct name in `env-vars.json`.
> SAM debugconfig: fix env-vars.json

- src/shared/utilities/promiseUtilities.ts
- src/shared/vscode/commands.ts
- src/shared/vscode/env.ts
- src/shared/vscode/window.ts
- src/shared/vscode/workspace.ts
- src/test/shared/vscode/fakeCommands.ts
- src/test/shared/vscode/fakeEnv.ts
- src/test/shared/vscode/fakeWindow.ts
- src/test/shared/vscode/fakeWorkspace.ts
- src/test/utilities/mockito.ts
This is a cherry-pick of #1074 and #1152 (already reviewed, no changes).
See #1074 and #1152
> Create reusable fakes/stubs for VSCode UI components (#1074) (#1152)

- src/shared/constants.ts
> Use CloudFront for endpoints.json instead of S3

- .changes/next-release/Feature-6930a1df-1673-4ffb-8a98-38720d102fe9.json
- src/lambda/local/debugConfiguration.ts
- src/shared/sam/cli/samCliValidator.ts
- For each of SAM CLI 0.45.0, SAM CLI 1.0.0
- For each of nodejs12.x, python3.7, dotnet2.1
- Set the `aws.samcli.location` to point to new/old sam binary.
- Verify that `Run Locally` works
- Verify that `Debug Locally` works.
With sam 0.45.0, the Toolkit pulls these Docker images:
Fetching lambci/lambda:dotnetcore2.1 Docker container image
Fetching lambci/lambda:nodejs12.x Docker container image
Fetching lambci/lambda:python3.7 Docker container image
With sam 1.0.0, the Toolkit pulls these Docker images:
Fetching amazon/aws-sam-cli-emulation-image-dotnetcore2.1:latest Docker container image
Fetching amazon/aws-sam-cli-emulation-image-nodejs10.x:latest Docker container image
Fetching amazon/aws-sam-cli-emulation-image-nodejs12.x:latest Docker container image
Fetching …
> SAM: support SAM CLI version 1.x

- buildspec/linuxIntegrationTests.yml
- buildspec/windowsTests.yml
Currently having issues with running our CI Integration tests and Windows unit tests against VS Code 1.47.0 in AWS CodeBuild.
* The Integration tests might be an issue with our code waiting for a port to open on the new debugger. Will require more research.
* Windows unit tests are running into an error with `getmac.exe`. This error is not encountered when using 1.46.0 and our code does not utilize `getmac.exe`. Cut an issue to VS Code (https://github.com/microsoft/vscode/issues/102428) to determine whether or not this is a regression.
Can confirm that the tests run successfully against 1.47.0 on my local Windows 10 machine; so far, this appears to be an issue with the CI hosts only.
We want some degree of integration and Windows test coverage on new PRs in our repo.
Pushing as a draft to …
> Temporarily reducing VS Code version to 1.46.0 due to issues with 1.47.0

- test-scripts/launchTestUtilities.ts
> Add an option to run tests against the minimum supported VS Code version

- package.nls.json
- src/shared/sam/activation.ts
- src/shared/sam/cli/samCliConfiguration.ts
- src/shared/sam/cli/samCliDetection.ts
- src/shared/sam/cli/samCliLocalInvoke.ts
- src/shared/sam/cli/samCliLocator.ts
- src/test/shared/sam/cli/samCliConfiguration.test.ts
The `aws.samcli.location` vscode setting has been exposed since 60a2eab4d1ad but it was not used in `SamCliLocalInvokeInvocation`.
- use the value in `SamCliLocalInvokeInvocation`
- handle `onDidChangeConfiguration` when the setting is changed at runtime
- TODO: use `SamCliProcessInvoker` instead? (why doesn't `samCliConfiguration.ts` use it already, as the other `samCliX` modules do?)
> SAM: respect the 'aws.samcli.location' user setting

- .changes/next-release/Breaking Change-f8934213-b3a8-4b65-bcc3-0d97b5097169.json
- .changes/next-release/Feature-3427d93a-a8da-41e2-9d90-fae3ed0b3526.json
- package.nls.json
- src/lambda/models/samLambdaRuntime.ts
- src/shared/codelens/csharpCodeLensProvider.ts
- src/shared/sam/cli/samCliContext.ts
- src/shared/sam/cli/samCliValidator.ts
- src/test/lambda/commands/deploySamApplication.test.ts
- src/test/shared/sam/cli/defaultValidatingSamCliProcessInvoker.test.ts
- src/test/shared/sam/cli/samCliContext.test.ts
- src/test/shared/sam/cli/samCliInit.test.ts
Assorted SAM CLI fixes:
* Minimum version bump: 0.38.0 -> 0.47.0 (for dotnetcore3.1 compatibility)
* Only "Run Locally" is available for dotnetcore3.1 functions. "Debug Locally" will automatically convert to a "Run Locally" on execution.
* We manually select the correct Docker image for the SAM CLI version when installing VSDBG.
The dotnetcore3.1 runtime has been available in SAM for a while (but without debugging capabilities). This is a past-due update as we move to newer SAM CLI versions.
SAM CLI 1.0.0 and up use an Amazon-owned Docker image from Dockerhub, `amazon/aws-sam-cli-emulation-image-<runtime>` instead of the community-owned version, `lambci/lambda:<runtime>`. Prior to debugging a .NET Lambda function, we need to pull down the container that the SAM CLI will use and …
> SAM CLI upgrade and associated fixes

- buildspec/linuxIntegrationTests.yml
- package.json
Reintroducing of #1188 with fix for integ tests mentioned in #1192 
Disable coverage during integration tests
Nothing is currently done with the coverage reports (if they even work)
and this breaks a bunch integration tests in weird circumstances (#1192)
e.g. it causes global context to be unavailable to tests for some reason if activation comes from the plugin itself rather than from the test
#1188
#1192 
> Activate extension shortly after VSCode startup

- src/credentials/activation.ts
- src/credentials/loginManager.ts
- src/shared/defaultAwsContextCommands.ts
- src/shared/sam/activation.ts
- src/shared/sam/cli/samCliDetection.ts
- src/test/shared/credentials/loginManager.test.ts
The aws_setCredentials, SAM_detect events should not be recorded unless the user actually initiated them.
- when user invokes `AWS: Detect SAM CLI`, telemetry is recorded (`recordSamDetect` is called)
- `recordSamDetect` is not called on startup 
- when user invokes `AWS: Sign out` followed by `AWS: Connect to AWS`, telemetry is recorded (`recordAwsSetCredentials` is called)
- `recordAwsSetCredentials` is not called on startup
> telemetry: do not record passive aws_setCredentials, SAM_detect

- src/test/cloudWatchLogs/commands/viewLogStream.test.ts
Due to a stunning lack of caffeine, I didn't realize that `new Date().getSeconds()` returned the current amount of seconds in the current timestamp after the minutes have been calculated, rather than seconds from epoch; this meant that there was a 1/60 chance that there would be 0 seconds, which JS interprets as falsy. Changed to a proper date calculation (`new Date().getTime()`)
Broken test
Test passes.
> Fixing a flaky test

- .changes/next-release/Feature-1d2c5bab-06bd-4c5e-a795-f18c7fb34912.json
- src/ssmDocument/activation.ts
- src/ssmDocument/commands/createDocumentFromTemplate.ts
- src/ssmDocument/util/util.ts
- src/test/ssmDocument/commands/createDocumentFromTemplate.test.ts
This PR adds creating a SSM Document locally command. This PR follows PR https://github.com/aws/aws-toolkit-vscode/pull/1186
This command can help users create a SSM Document from templates base on the document type and document format, so that they don't have to start editing a SSM Document from scratch.
I included tests in `src/tests/ssmDocument/createDocumentFromTemplates.test.ts`. 
> Added createLocalDocument command to SSM Document support

- src/stepFunctions/activation.ts
- src/stepFunctions/commands/visualizeStateMachine/aslVisualizationManager.ts
- src/test/stepFunctions/commands/visualizeStateMachine.test.ts
Deflaking a test
There's no guarantee that extension tests don't open text editors (some actively open webviews, for instance). This is a relatively simple defensive change to ensure that we pass in an expected value.
Alternately, we can look to stub out `vscode.window.activeTextEditor`.
https://github.com/aws/aws-toolkit-vscode/issues/1201
Tests pass, SFN viewer works.
> Fixing flaky test

- package.nls.json
- src/shared/sam/debugger/awsSamDebugger.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
We currently haven't implemented enough magic (or UI, alternatively) to guess/decide a launchable config if the user doesn't actually have a launch.json.  So for now, just show an error with guidance.
1. Delete all `launch.json` files in the workspace
2. Visit `template.yaml`
3. Hit F5. VSCode presents a menu of possible debuggers, which includes `AWS SAM: Debug Lambda Function Locally`
4. Select `AWS SAM: Debug Lambda Function Locally`
5. Because there is no `launch.json`, the Lambda runtime, handler name, etc., must be guessed, or we must prompt the user each time. But we currently haven't implemented that. 
- With this commit, we show an error.
- Before this commit, we auto-generated configs from the workspace and chose the first one.
- **Future:** we could show a menu and let the user …
> SAM debug: show error on missing launch.json

- buildspec/linuxIntegrationTests.yml
- buildspec/linuxTests.yml
- buildspec/packageTestVsix.yml
- buildspec/windowsTests.yml
- test-scripts/launchTestUtilities.ts
- do not pin to VSCode `1.46.0`. It doesn't seem to help, since Windows CI still fails.
- Reverts cda7451080b2
- print exact version (and git hash) of the vscode test instance. Example:
```
$ ./node_modules/.bin/ts-node ./test-scripts/launchTestUtilities.ts
Seting up VS Code test instance, version: stable
Found .vscode-test/vscode-1.47.3. Skipping download.
VS Code test instance location: /Volumes/workplace/aws-toolkit-vscode/.vscode-test/vscode-1.47.3/Visual Studio Code.app/Contents/MacOS/Electron
Invoking vscode CLI command:
/Volumes/workplace/aws-toolkit-vscode/.vscode-test/vscode-1.47.3/Visual Studio Code.app/Contents/Resources/app/bin/code --version
1.47.3
91899dcef7b8110878ea59626991a18c8a6a1b3e
x64
```
By submitting this pull request, I confirm that my contribution is made under …
> CI: do not pin to VSCode 1.46.0

- .changes/next-release/Feature-1d2c5bab-06bd-4c5e-a795-f18c7fb34912.json
- src/awsexplorer/regionNode.ts
- src/shared/clients/defaultSsmDocumentClient.ts
- src/shared/clients/defaultToolkitClientBuilder.ts
- src/shared/clients/ssmDocumentClient.ts
- src/shared/clients/toolkitClientBuilder.ts
- src/ssmDocument/explorer/documentItemNode.ts
- src/ssmDocument/explorer/documentTypeNode.ts
- src/ssmDocument/explorer/registryItemNode.ts
- src/ssmDocument/explorer/ssmDocumentNode.ts
- src/test/shared/clients/mockClients.ts
- src/test/ssmDocument/explorer/documentItemNode.test.ts
- src/test/ssmDocument/explorer/documentTypeNode.test.ts
- src/test/ssmDocument/explorer/registryItemNode.test.ts
- src/test/ssmDocument/explorer/ssmDocumentNode.test.ts
Added SSM Document Explorer nodes and ssmDocument clients that calls AWS SSM API's to retrieve document info.
The explorer nodes have 4 levels. 
1. SSM Document
2. Registry by document owner 
3. Registry by document type
4. document item
This allows users to view SSM Documents in VS Code. The open document command will come later.
There are tests for each level of the explorer nodes. The tests are created based on the eventSchemas explorer test cases. 
> added explorer nodes and ssmDocument clients

- test-scripts/launchTestUtilities.ts
This allows the release pipeline to proceed, until we debug the CI issue with the "stable" and "insiders" vscode versions on Windows CI.
> CI: temporarily force "minimum" VSCode on Windows

- src/test/ssmDocument/commands/createDocumentFromTemplate.test.ts
In a test, a stub function (openAndSaveDocument) causing an undefined object to get passed to a showTextDocument call within createSsmDocumentFromTemplate. Fixing this to remove errors that are generated during test runs.
> Fix test error trying to access uri of undefined document

- src/shared/sam/cli/samCliLocator.ts
One of SAM CLI's recommended install methods is to use linuxbrew. If linuxbrew is not in $PATH for some reason, Toolkit can work around that by searching the default linuxbrew location.
> SAM: search for SAM CLI in ~/.linuxbrew

- package.json
- src/shared/sam/cli/samCliConfiguration.ts
- src/shared/settingsConfiguration.ts
- src/test/utilities/testSettingsConfiguration.ts
Using `Global` scope for the `aws.samcli.location` config entry is untenable because:
- Multiple running VSCode instances may change it, and then all  instances respond to the `onDidChangeConfiguration` event, which may  cause hysterisis (on/off loop).
- _Remote_ VSCode instances share `Global` config with local running  VSCode instances.  Thus machine-dependent settings must not be  `Global`, because the config value on a remote VSCode may conflict  with local instance(s).
`Workspace` is a reasonable scope for `aws.samcli.location` because it is usually auto-detected (setting it manually is usually only  for debugging/experimentation)
- From the vscode settings UI one can see that there is a concept of machine-specific configuration: `~/.vscode-server/data/Machine/settings.json` . But …
> SAM: change config to "machine" scope; handle failed config write

- src/shared/telemetry/defaultTelemetryService.ts
_timer may be undefined if shutdown() was called, despite clearTimeout(), because the `async` closure scheduled by the previous timer tick may be pending.
TypeError: Cannot read property 'refresh' of undefined
at DefaultTelemetryService.<anonymous> (/Volumes/workplace/aws-toolkit-vscode/src/shared/telemetry/defaultTelemetryService.ts:150:30)
at fulfilled (/Volumes/workplace/aws-toolkit-vscode/dist/src/shared/telemetry/defaultTelemetryService.js:9:58)
{stack: 'TypeError: Cannot read property 'refresh' of …ed/telemetry/defaultTelemetryService.js:9:58)', message: 'Cannot read property 'refresh' of undefined'}
> TelemetryService: avoid race after shutdown()

- buildspec/linuxIntegrationTests.yml
- buildspec/linuxTests.yml
- buildspec/packageTestVsix.yml
- buildspec/windowsTests.yml
- test-scripts/launchTestUtilities.ts
- test-scripts/test.ts
- use `env` directive instead of shell-specific commands to set env vars
- ~~also report `--status` after installing the vscode test-instance~~
- `[main 2020-07-30T18:56:35.684Z] Warning: The --status argument can only be used if Code is already running. Please run it again after Code has started.`
- (temporary commit): invoke tests with `--verbose --log debug`
- Revert "CI: temporarily force "minimum" VSCode on Windows #1224" 
> CI: restore Windows CI;  use "--verbose --log debug"

- .changes/next-release/Feature-97c6535a-a446-4f56-beaa-da5ee8d4a5f9.json
- src/awsexplorer/regionNode.ts
- src/shared/featureToggle.ts
Ungates Cloudwatch Logs functionality by removing the requirement to have a feature flag set.
Makes feature generally available
Contingent on https://github.com/aws/aws-toolkit-vscode/pull/1200
Confirmed that the feature appears without a feature flag present
> Ungate CloudWatch Logs functionality

- src/stepFunctions/utils.ts
- src/test/stepFunctions/utils.test.ts
`updateCache()` uses `Promise.all()` to call multiple tasks in parallel which eventually call `writeToLocalStorage()`, targeting the same directory.
fixes https://github.com/aws/aws-toolkit-vscode/issues/1230
> stepFunctions visualization: do not fail if directory exists

- src/test/stepFunctions/commands/visualizeStateMachine.test.ts
VSCode "insiders" build has improved Uri validation, thus these tests were failing:
1) StepFunctions VisualizeStateMachine
Test AslVisualization on setup all properties are correct:
Error: [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character
at c:\codebuild\tmp\output\src868706983\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:154:26
at new u (c:\codebuild\tmp\output\src868706983\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:154:340)
at new h (c:\codebuild\tmp\output\src868706983\src\github.com\aws\aws-toolkit …
> test: set fake Uri to something actually valid

- buildspec/linuxIntegrationTests.yml
This change avoids 100s of non-error messages in the CI build log. Errors/warnings are still shown, and CodeBuild shows "Running command ..." headers, so we still have visibility should anything fail or hang.
Now the log for the INSTALL and PRE_BUILD steps looks like:
```
[Container] 2020/08/27 20:50:48 Entering phase INSTALL
[Container] 2020/08/27 20:50:48 Running command >/dev/null apt-get -qq update
[Container] 2020/08/27 20:50:56 Running command wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | apt-key add -
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
[Container] 2020/08/27 20:50:57 Running command >/dev/null wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
[Container] …
```
> CI: reduce noise from apt/pip/docker

- .changes/next-release/Bug Fix-96a0f7d4-b5b1-495b-b8b1-6efd814e0fe3.json
- package-lock.json
- package.json
Upgrade version of amazon-states-language-service from `1.4.0` -> `1.4.1`.
Consumes bug fix for state validation where a state referenced in a Choice state was marked as unreachable when defined before the Choice state (https://github.com/aws/amazon-states-language-service/pull/54).
Fixes false validation errors for state reachability.
Fixes https://github.com/aws/aws-toolkit-vscode/issues/1117
Manually tested extension using the definition referenced in https://github.com/aws/aws-toolkit-vscode/issues/1117#issuecomment-685996951
N/A
> Use version 1.4.1 of amazon-states-language-service

- .changes/next-release/Feature-5da32220-237a-4ec7-9b84-b6952f2e5bae.json
- .changes/next-release/Feature-c56b7fa8-7102-4006-afd1-5458cb70c0ef.json
- package.json
- src/lambda/activation.ts
- src/shared/featureToggle.ts
A bit too eager on adding the Lambda upload/import functionalities to the `master` branch. This gates these features so they're hidden from the general public. Enterprising users can try these features by adding the following lines to VS Code's `settings.json` file and restarting the IDE:
```
{
...
"aws.experimentalFeatureFlags": [
"LambdaImport",
"LambdaUpload"
],
}
```
> Gating Lambda features

- src/shared/sam/localLambdaRunner.ts
The `skipNewImageCheck` parameter for SAM debug configs now functions
Resolving an oversight. Debated internally on whether or not we should change this to `skipPullImage` to be in line with the SAM CLI's `--skip-pull-image` verbiage but pulled back for two reasons:
* `skipNewImageCheck` is more descriptive
* We have a similar issue with `--use-container` and `containerBuild`. Moving one but not the other would be confusing to users, and moving both would require users to potentially migrate.
Manual testing
> Wiring up skipNewImageCheck

- package.nls.json
- src/extension.ts
- src/shared/cloudformation/activation.ts
On the theme of working towards figuring out what is wrong and fixing #1286 , fix the toolkit activating when using a readonly (444) or folder we have no permissions to (000) as a workspace. 
This seems like a reasonable proxy for read and write issues to a workspace.
> Show a message and not fail to activate if we can't start the template registry

- .travis.yml
Example https://travis-ci.org/github/aws/aws-toolkit-vscode/jobs/729674803 :
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
...
ERROR in extension.js from Terser
...
npm ERR! aws-toolkit-vscode@1.14.0-SNAPSHOT vscode:prepublish: `npm run clean && npm run lint && webpack --mode production && npm run buildScripts`
npm ERR! Exit status 2
> CI/travis: avoid webpack OOM

- src/integrationTest/sam.test.ts
- src/shared/utilities/timeoutUtils.ts
- src/test/testRunner.ts
- test-scripts/launchTestUtilities.ts
The test only waits for 1 debug session, but the top-level, user-initiated, `aws-sam` session internally starts a platform-specific session. The "stop debugging" action only stops the foreground session.
Other changes:
- `waitUntil` was cherry-picked from `feature/apigateway`
- change `invokeVSCodeCli()` to let the caller decide if/when to print output
- ~~Restore coverage for integ tests by avoiding `decache()`~~
- Edit: after removing `decache()`, coverage reports aren't generated. So the need for `decache()` is not Windows-only after all?
```
==> Searching for coverage reports in:
+ .coverage
--> No coverage report found.
```
Test failure before this PR:
```
4 failing
1) SAM Integration Tests
SAM Application Runtime: python2.7
Starting with a newly created python2.7 SAM Application... …
```
> test/integ: wait for previous sessions

- src/integrationTest/sam.test.ts
This is a temporary change to unblock CI.
https://github.com/aws/aws-toolkit-vscode/pull/1315 was an attempt to fix this but it appears these sessions are not merely slow, but actually aren't killed by the "stop debugging" action (or there is a race in the tests somewhere).
> test/integ: allow previous sessions

- package.json
This change brings these two context menus in alignment with the rest of the AWS Explorer.
> Add missing separator to group delete actions away from less destructive operations

- buildspec/windowsTests.yml
This workaround was only to avoid spurious/noise errors in the CI log:
Unable to retrieve mac address (Error: Command failed: getmac.exe
'getmac.exe' is not recognized as an internal or external command,
VSCode 1.50 removes its dependency on getmac.exe so we can remove the workaround.
ref: c0bdf1f5c122
ref: https://github.com/microsoft/vscode/issues/102428
- Compare `Windows Unit Tests [insiders]` log to `Windows Unit Tests [stable]`. The Insiders log does _not_ have the getmac.exe message.
> CI: getmac.exe workaround is no longer needed

- src/shared/clients/defaultToolkitClientBuilder.ts
- The order was swapped in c5abd330735f.
- The bug was not noticed because 65da599ddfab was merged meanwhile, and the swapped order was not noticed when fixing the merge-conflict.
- The tests passed because they create `DefaultS3Client` directly (with the correct arg-order) instead of using `ToolkitClientBuilder`.
- AWS Explorer: expand the S3 and observe that buckets are listed. Expand an S3 bucket and observe that its contents are listed.
> S3: fix argument order when creating DefaultS3Client

- buildspec/linuxIntegrationTests.yml
problem: CI environment fails to install "dotnet-sdk-2.1"
[Container] 2020/10/13 17:44:33 Running command >/dev/null apt-get -qq install -y dotnet-sdk-2.1
E: Unable to correct problems, you have held broken packages.
solution: install dotnet via AWS codebuild "runtime-versions" directive instead of apt-get. 
fixes https://github.com/aws/aws-toolkit-vscode/issues/1349
> CI/integ: fix failing dotnetcore2.1 package install

- src/integrationTest/sam.test.ts
- src/shared/sam/debugger/csharpSamDebug.ts
- src/shared/sam/debugger/pythonSamDebug.ts
- src/shared/sam/debugger/typescriptSamDebug.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
The "SamLocalDebug" name is left-over from the old logic, before the Toolkit supported VSCode launch-configs.
This change has these effects:
- The user-given name will appear in logs/output/messaging.
- Integration tests can assert the name, which serves as an extra guard  to check "overlapping" `DebugSession` events.
> SAM debug: preserve user-given config name

- package.json
The `additionalProperties` specification is too restrictive: instead it should be omitted entirely.
ref https://github.com/aws/aws-toolkit-vscode/issues/1344
Test cases:
1. Editing the following launch.json in VSCode does _not_ show   warnings/errors (i.e. it is "valid"):
```
{
"configurations": [
{
"type": "aws-sam",
"request": "direct-invoke",
"name": "sam-samples:HelloWorldFunction",
"invokeTarget": {
"target": "template",
"templatePath": "sam-samples/template.yaml",
"logicalId": "HelloWorldFunction"
},
"lambda": {
"payload": {
"json": {
"foo": {
"a": 1,
"b": {
"bb": []
}
},
"bar": 42
}
},
"environmentVariables": {}
}
}
]
}
```
2. Changing the "json" item to `"json": 42` is correctly flagged as an error.
By submitting this pull request, I confirm that my contribution is made under the …
> SAM debugconfig: `payload.json` field should allow any object

- .gitignore
- README.quickstart.vscode.md
- build-scripts/generateNonCodeFiles.ts
- buildspec/packageTestVsix.yml
- install vsix from [CI](https://d1ihu6zq92vp9p.cloudfront.net/f3519e77-e378-495c-ab06-ba90e73187e9/report.html)
- `AWS: View Quick Start` command shows the quick start page
- unzip the vsix, confirm that `README.md` was replaced with the content from `README.quickstart.vscode.md` , and the relative URLs were converted to absolute URLs.
> build: rename quickstart files

- .changes/next-release/Feature-58dd3336-fb6b-4876-90d5-baf1bf9fad52.json
- .changes/next-release/Feature-7d6f8be9-8646-4c81-9e1f-287e683c06d4.json
- package.json
- src/lambda/explorer/lambdaNodes.ts
- src/lambda/wizards/samDeployWizard.ts
- src/shared/sam/activation.ts
Adding a right-click option for `Create new SAM Application` to the top-level Lambda nodes and an action icon for `Deploy SAM Application` to the top-level region nodes.
* Also: Deploying via region node icon now skips the region selection step and uses the region node's region.
Considerations:
* Should we change the names of these to emphasize that this is acting on local, non-Lambda resources? E.g. `Create new local SAM Application`?
* Is this the right iconography?
* Thinking we can add icons for individual Lambda upload/import commands later, shouldn't be conflicting with these because those will be tied to the individual Lambdas rather than the root note.
UX studies have identified that this is a good way to surface this functionality to users even though the actions aren't …
> Adding icons for SAM actions

- src/shared/cloudformation/cloudformation.ts
- src/shared/sam/localLambdaRunner.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
- Make CloudFormation registry more lenient, explicitly say that there are other resource types (string), and that other properties can exist
- Pass all resources into invoke instead of only the function we are running
https://github.com/aws/aws-toolkit-vscode/issues/1352
> Fix bug where SAM Invoke would only use one resource from the template

- .changes/next-release/Bug Fix-c1c64d50-c466-48fd-90bc-d5d7e9324f9c.json
- src/shared/clients/defaultS3Client.ts
- src/test/shared/clients/defaultS3Client.test.ts
Fix creating S3 buckets in us-east-1 by plucking logic from the Java SDK
#1367
> Fix creating buckets in us-east-1

- .gitignore
- CONTRIBUTING.md
- build-scripts/packageAlpha.ts
- package.json
- src/shared/extensions.ts
- Rename `packageAlpha.ts` to `packageDebug.ts`
- Do not minify the webpack result; useful for debugging and inspection.
> build: packageDebug.ts: do not minify the "debug" VSIX

- .gitignore
- build-scripts/packageDebug.ts
- If `fs.copyFileSync('foo.bk', 'foo')` succeeds then it is very   unlikely that we need the 'foo.bk' file.
- Rename `packageAlpha.ts` to `packageDebug.ts` (forgotten in 979a92f8da57).
> build: packageDebug.ts: cleanup *.bk files

- .changes/next-release/Feature-a468d30b-6593-44ea-9ab3-2d4bb93ec1e8.json
- package.json
- package.nls.json
- src/cloudWatchLogs/activation.ts
- src/cloudWatchLogs/commands/addLogEvents.ts
- src/cloudWatchLogs/commands/viewLogStream.ts
- src/cloudWatchLogs/registry/logStreamRegistry.ts
- src/extension.ts
- src/test/cloudWatchLogs/commands/addLogEvents.test.ts
- src/test/cloudWatchLogs/document/logStreamDocumentProvider.test.ts
- src/test/cloudWatchLogs/registry/logStreamRegistry.test.ts
Lets user set a limit for log entries returned per query
Performance issues
> Adding user-configurable limit to CloudWatch Logs calls

- src/shared/sam/cli/samCliLocalInvoke.ts
- src/shared/utilities/childProcess.ts
- src/test/shared/utilities/childProcess.test.ts
- Rename killed() to stopped(): checking `child_process.killed` is   misleading, we want to know if the process was stopped, not   merely that a signal was sent.
- Rename kill() to stop(): we want to stop the process, not just send a signal which may be ignored.
- Introduce `onExit` hook.
- Introduce `collect` option which controls whether `start()` collects stdout/stderr (this allows `stopped()` to check `this.processResult` to decide if the process stopped).
- Move stdout/stderr collection to `start()`, so `run()` is now just a thin wrapper.
> childProcess.ts: fix and rename kill()/killed()

- src/cloudWatchLogs/commands/viewLogStream.ts
- src/eventSchemas/wizards/schemaCodeDownloadWizard.ts
- src/lambda/wizards/samDeployWizard.ts
- src/lambda/wizards/samInitWizard.ts
- src/shared/wizards/multiStepWizard.ts
- src/ssmDocument/wizards/publishDocumentWizard.ts
- src/stepFunctions/wizards/publishStateMachineWizard.ts
- src/test/shared/wizards/multiStepWizard.test.ts
The current wizard system expects each step to specify both the next step, as well as the behavior of the "back" button arrow. This is okay for simple flows, but starts to become difficult to follow once you start throwing in conditional behavior and need to figure out which step to actually return.
This attempts to improve readability by moving from explicitly specifying the desired "previous" state to an intent, and moving the onus for handling this onto the homegrown wizard framework instead. This ~unfortunately~ also prevents wizards from intentionally/accidentally jumping around with regards to step ordering
> Minor refactor of MultiStepWizard to clarify state transitions

- src/eventSchemas/commands/downloadSchemaItemCode.ts
- src/lambda/activation.ts
- src/lambda/commands/deploySamApplication.ts
- src/lambda/commands/importLambda.ts
- src/lambda/commands/uploadLambda.ts
- src/shared/filesystemUtilities.ts
- src/shared/sam/debugger/awsSamDebugger.ts
- src/shared/sam/localLambdaRunner.ts
- src/test/eventSchemas/commands/downloadSchemaItemCode.test.ts
- src/test/lambda/local/util.ts
- src/test/shared/codelens/localLambdaRunner.test.ts
- Delete temporary files when we are done using them instead of at deactivation time. Deactivation does not seem to be reliable in some environments and can cause buildup on long running sessions.
- We still will try to delete at deactivation time as before as well if something is missed
> Handle temporary files better

- src/lambda/commands/importLambda.ts
Lambda Import workflow now adds workspace folders later in the workflow. This does not affect functionality.
Found a weird bug with adding workspace folders to VS Code: if a user has an instance of VS Code open that is open to a folder, but the folder is not part of a workspace, and the user attempts to add a workspace folder via extension command, it appears that the extension host restarts, failing the command mid-flight. This does not happen if nothing is open in VS Code (instead, the whole IDE restarts) or if a workspace is in place (works as intended). This helps to mitigate this issue: the user may see an issue with a launch config being added, but should have their Lambda downloaded and unzipped correctly.
As a side note, a deeper dive here did find some issues with the Lambda …
> Moving workspace folder addition in import Lambda flow

- src/cloudWatchLogs/commands/viewLogStream.ts
- src/eventSchemas/wizards/schemaCodeDownloadWizard.ts
- src/lambda/commands/importLambda.ts
- src/lambda/commands/uploadLambda.ts
- src/shared/codelens/codeLensUtils.ts
- src/shared/sam/debugger/commands/addSamDebugConfiguration.ts
- src/stepFunctions/wizards/publishStateMachineWizard.ts
More step numbers, added to the following workflows:
View Log Stream
Import Lambda
Upload Lambda
Create Launch Config
Also added back buttons to the Upload Lambda flow. Should we migrate this to a wizard as well?
TODO:
* Revert changes to 1-step workflows (including view log stream/import lambda)? Are they necessary?
* OR add steps to all 1-step workflows? Change spurred by current issues with adding to the S3 workflows, since those use `showInputBox` rather than `createInputBox`; `showInputBox` has an easier (and much more mockable) workflow but does not allow step numbers.
Whatever we do, we should try and make it uniform.
UX review
> Added more step numbers

- src/shared/cloudformation/templateRegistry.ts
- src/test/shared/cloudformation/templateRegistry.test.ts
fix "TypeError: Reduce of empty array with no initial value"
> templateRegistry.ts: fix getResourcesForHandler() on empty input

- .changes/next-release/Bug Fix-1b137e40-7d80-480d-95a4-318dfbc9d2f3.json
- src/integrationTest/cloudformation/templateRegistryManager.test.ts
- src/shared/cloudformation/activation.ts
- src/shared/cloudformation/templateRegistry.ts
- src/shared/cloudformation/templateRegistryManager.ts
- src/test/shared/cloudformation/templateRegistry.test.ts
- Add banned file patterns, we will log and not add it to the registry
- Code cleanup `addTemplatesToRegistry` was redundant, the base function already had an unused quiet option. Use it in the one place `addTemplatesToRegistry` was used
#1380
> Fix showing templates from .aws-sam in sam deploy 

- src/integrationTest/globalSetup.test.ts
- src/shared/logger/logger.ts
- src/shared/logger/winstonToolkitLogger.ts
- src/test/shared/logger/winstonToolkitLogger.test.ts
- src/test/testLogger.ts
- `logger: introduce logLevelEnabled()`
- Sometimes it is useful to enable certain behaviors based on the current log-level.
- Examples:
- When invoking `sam` CLI, if the current log-level is 'debug' then it
could make sense to use `sam --debug …`
- Other third-party components like debuggers have verbosity levels that
are useful to include in the Toolkit's own logs. (Else the debugger
logs get lost or must be configured some other way.)
- `logger: introduce setLogLevel()`
- Avoids circular import detected by webpack:
```
ERROR in Circular dependency detected:
src/shared/logger/logger.ts -> src/shared/logger/winstonToolkitLogger.ts -> src/shared/logger/logger.ts
ERROR in Circular dependency detected:
src/shared/logger/winstonToolkitLogger.ts -> src/shared/logger/logger.ts -> …
```
> logger: introduce logLevelEnabled(), setLogLevel()

- src/shared/sam/cli/samCliBuild.ts
- src/shared/sam/cli/samCliInvoker.ts
- src/shared/sam/cli/samCliInvokerUtils.ts
- src/shared/sam/cli/samCliLocalInvoke.ts
- src/shared/utilities/childProcess.ts
- src/shared/utilities/vsCodeUtils.ts
- src/test/shared/fakeChannelLogger.ts
AWS Toolkit:
```
Preparing to debug 'app.lambda_handler' locally...
Building SAM Application...
Running command: (not started) [/usr/local/bin/sam build --build-dir /tmp/aws-toolkit-vscode/vsctkSnup4p/output --template /Users/richali/tmp/saminit/py/app___vsctk___template.yaml --use-container]
Starting Build inside a container
Building codeuri: hello_world/ runtime: python3.8 metadata: {} functions: ['HelloWorldFunction']
Fetching amazon/aws-sam-cli-build-image-python3.8 Docker container image......
Mounting /Users/richali/tmp/saminit/py/hello_world as /tmp/samcli/source:ro,delegated inside runtime container
Build Succeeded
Built Artifacts  : private/tmp/aws-toolkit-vscode/vsctkSnup4p/output
Built Template   : private/tmp/aws-toolkit-vscode/vsctkSnup4p/output/template.yaml
Commands you can …
```
> Emit 'sam build' output to the user output channel

- src/shared/sam/cli/samCliBuild.ts
- src/shared/sam/cli/samCliDeploy.ts
- src/shared/sam/cli/samCliLocalInvoke.ts
- src/shared/sam/cli/samCliStartApi.ts
- src/test/shared/sam/cli/samCliBuild.test.ts
- src/test/shared/sam/cli/samCliLocalInvoke.test.ts
- src/test/shared/sam/cli/samCliStartApi.test.ts
Show SAM CLI `--debug` messages if current Toolkit log-level is "debug".
> SAM CLI: specify --debug if log-level is "debug"

- src/lambda/wizards/samDeployWizard.ts
Ensures that the region node is a region node by checking for a `regionCode` property. This prevents the deploy workflow from skipping the region selection, which would mean that a user can't select an S3 bucket.
> Ensure a region node is indeed a region node

- package.json
VS Code uses Start Casing when parsing configuration keys for their Settings UI. This converts "Cloud Watch Logs" to "Cloudwatch Logs".
> Cloud Watch Logs -> Cloudwatch Logs in settings UI

- CONTRIBUTING.md
Mentioning that commits now require the [AWS `git secrets`](https://github.com/awslabs/git-secrets) hook, which is called on commit. This helps ensure that any contributors to the repo will not accidentally post their AWS credentials by exiting out of the commit if anything resembling credentials is included.
> Contributing guide mentions git secrets requirement

- codecov.yml
- They are too noisy, makes PR review difficult.
- We don't get credit for coverage from our integ tests, because of  a tooling bug, which makes it very difficult to reach 100% coverage.
https://docs.codecov.io/docs/github-checks-beta#disabling-github-checks-patch-annotations-via-yaml
> CI: disable codecov annotations

- package.nls.json
- src/stepFunctions/commands/createStateMachineFromTemplate.ts
- src/stepFunctions/wizards/createStateMachineWizard.ts
- src/test/stepFunctions/wizards/createStateMachineWizard.test.ts
I added multiple step wizard to allow customer choose format (YAML/JSON) when they use "AWS: Create New State Machine" command.
We want to unable users to use templates of Step Functions state machines in YAML
Tested it manually.
> StepFunctions: Add YAML option to ASL template creation

- package.json
- package.nls.json
- src/shared/sam/localLambdaRunner.ts
- src/test/shared/codelens/localLambdaRunner.test.ts
This setting is stored as 30 for all users, which is way too high. Retrying more than a few times is very bad user experience. Until recently, the retry logic didn't work, so users have never actually encountered a need for this setting. Expecting them to
configure it will just be confusing, and there is little reason for it to be configurable anyway.
> SAM debug: remove "max retries" user setting

- resources/debugger/py_debug_wrapper.py
- src/shared/sam/debugger/pythonSamDebug.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
Depends on https://github.com/aws/aws-toolkit-vscode/pull/1361 and resolves https://github.com/aws/aws-toolkit-vscode/issues/1272
ptvsd is considered deprecated and debugpy is the replacement
> SAM debug: use debugpy instead of ptvsd

- src/lambda/commands/createNewSamApp.ts
- src/shared/sam/debugger/commands/addSamDebugConfiguration.ts
- src/shared/watchedFiles.ts
- src/test/shared/cloudformation/templateRegistry.test.ts
- Allow get to take a `vscode.Uri` which helps prevent issues that only manifest themselves on Windows
- Fix the names to no longer have template
> WatchedFiles improvements

- src/shared/sam/localLambdaRunner.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
Problem: the validation tries to load JSON from a relative path, but the process CWD is "/", so the file is not found.
Solution: pass the absolute path.
--
regression by 5f05a50d8a291
ref #1439
> SAM debug: fix payload JSON validation

- .changes/next-release/Feature-85fc3d12-13de-40ca-aa7d-0f008bc84e0e.json
- package-lock.json
- package.json
Bumps up the version of the amazon-states-language-service. The new one contains various bug fixes for YAML support in ASL.
I flipped the order of file extension in package.json to `asl.yaml` having priority over `asl.yml` - templates, by default will have preferable `asl.yaml` extension. 
YAML Support in VS Code for Amazon States Language
Tested manually by creating various state machines from templates and from scratch. 
> Updates version of amazon-states-language-service

- test-scripts/test.ts
This was a temporary change, not needed since CI has been relatively stable.
reverts c2165cf48e62
> test: remove verbose VSCode logging

- src/lambda/commands/deploySamApplication.ts
- src/shared/sam/cli/samCliDeploy.ts
https://github.com/aws/aws-toolkit-jetbrains/pull/2295
* 1.14.0 made the sam deploy option `--image-repository` required for image based lambdas
* Tested on 1.13.1 and 1.15.0
> Fix deployment for image based lambdas in sam cli 1.14+

- package.json
Without changing the text or order, renamed some of the group names in package.json for organization and logical flow.
An example in the CDK menu had a group with entries of 2 and 3, but not 1.  
> Reorganize group names for context menus

- buildspec/linuxIntegrationTests.yml
- buildspec/linuxTests.yml
- buildspec/packageTestVsix.yml
- buildspec/windowsTests.yml
* ~~Doing some additional testing, want to ensure that the buildscripts don't attempt to use CodeArtifact if env vars aren't present (I have confirmed that a CodePipeline tracking the child branch does use CodeArtifact correctly).~~ Confirmed
* ~~Our main CI and Github Actions/Travis accounts are currently not wired up for CodeArtifact and should skip the CodeArtifact `pre-build` step. Tests run against this PR should confirm this.~~ Confirmed
* ~~We may need to roll back Windows CodeArtifact usage. This is because we can't update our Windows builds to the newer CodeBuild image (required by CodeBuild): https://github.com/microsoft/vscode/issues/77499~~ Rolled back
This change implements [CodeArtifact](https://aws.amazon.com/codeartifact/) as a cache for NPM for CI jobs run by AWS …
> Use CodeArtifact for AWS CodeBuild CI jobs

- src/test/lambda/wizards/samDeployWizard.test.ts
Tests were failing with:
```
1) "after each" hook for "displays region nodes with user-friendly region names":
TypeError: Cannot read property 'restore' of undefined
at Context.<anonymous> (src/test/lambda/wizards/samDeployWizard.test.ts:655:17)
```
For some reason, the `beforeEach` and `afterEach` blocks for `DefaultSamDeployWizardContext` were firing before and after every test in the codebase. Unsure why this fixes it, but it does (validated through breakpoints in code)
Additionally, this makes the heading for `DefaultSamDeployWizardContext` show up in the test output as it should (it didn't before)
Tests work as they should
https://github.com/aws/aws-toolkit-vscode/issues/1458
Local tests, breakpoints on `DefaultSamDeployWizardContext`'s `beforeEach` and `afterEach` hooks no longer …
> Fixing BeforeEach and AfterEach for DefaultSamDeployWizardContext firing before each test

- buildspec/linuxIntegrationTests.yml
- buildspec/linuxTests.yml
- buildspec/packageTestVsix.yml
- buildspec/windowsTests.yml
Decided to rename `ACCOUNT_ID` in our buildspecs.
> ACCOUNT_ID => TOOLKITS_ACCOUNT_ID

- .changes/next-release/Feature-8729574b-6dd2-4ab4-88bb-a5f13b710e0b.json
- src/apigateway/explorer/apiGatewayNodes.ts
- src/apigateway/explorer/apiNodes.ts
- src/test/apigateway/explorer/apiGatewayNodes.test.ts
Names for API Gateway nodes are not guaranteed unique. This change adds the ID to the node labels in parenthesis, similar to how it's shown in the console's breadcrumbs
If multiple APIs had the same name, all APIs for the region would not be viewable
https://github.com/aws/aws-toolkit-vscode/issues/1468
Tests pass
> API Gateway nodes include their IDs

- .changes/next-release/Feature-298a87ca-c8dc-4522-a990-529eb66b7f55.json
- src/lambda/wizards/samInitWizard.ts
- src/shared/filesystemUtilities.ts
- src/test/lambda/wizards/samInitWizard.test.ts
- src/test/shared/filesystemUtilities.test.ts
Problem:
Before this commit the "AWS: Create new SAM application" command
defaults the application folder name based on the parent folder:
https://github.com/aws/aws-toolkit-vscode/blob/44dad848fbed20e3b081dfa4cad6f41e00e05a0c/src/lambda/wizards/samInitWizard.ts#L445
In cloud9 this always is `environment`, which is not helpful.
Solution:
Default to a name like "lambda-python3.8", and append a number if such
a name already exists in the workspace.
> "Create SAM app": default to a more intuitive name

- buildspec/linuxIntegrationTests.yml
- src/integrationTest/sam.test.ts
- Pip2 and Python27 are no longer available (end-of-life) in the  standard repo in the CodeBuild 5.0 image, so add workarounds to  install them.
- Python 2.7 is in the `Universe` repository.
- Pip2 is not, install it with their install script.
ref https://github.com/aws/aws-toolkit-jetbrains/pull/2366
- TODO: revert this PR after https://github.com/aws/aws-sam-cli-app-templates/pull/82 is merged.
- `sam` [clones HEAD of the "aws-sam-cli-app-templates" repo](https://github.com/aws/aws-sam-cli/blob/23d244927c245eae874efbc21957bdfc143a8e61/samcli/commands/init/init_templates.py#L27)
> CI: fix python2.7 setup

- .changes/next-release/Bug Fix-55703bad-99e5-4cd8-ba13-8f913f7c044d.json
- src/eventSchemas/commands/downloadSchemaItemCode.ts
- src/test/eventSchemas/commands/downloadSchemaItemCode.test.ts
…eviously kicked of using the error name
Just found a bug that download code bindings for custom schemas (all schemas other than `aws.schemas` registry) fails with an error.  The way that code generation logic works, we try to download code bindings ( this automatically works for aws.schemas as they are pre-generated), if it fails with NotFound exception then we generate the code bindings. Previously we would use stack parameter from the Error interface to determine the error type, which seems to be not returned anymore. Instead there is a new parameter `name` which contains the error type. 
I did an end-to end testing by selecting a custom schema in my account, download its code bindings for 3 different languages and verified that all are successful.   
By submitting this pull request, I …
> Schemas: fix code generation on download failure

- src/shared/cloudformation/templateRegistry.ts
- src/shared/codelens/codeLensUtils.ts
- src/shared/sam/debugger/awsSamDebugConfiguration.ts
- src/shared/sam/debugger/commands/addSamDebugConfiguration.ts
- src/test/shared/cloudformation/templateRegistry.test.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
Codelenses in source files can generate template run configs for image-based Lambdas.
* If the template resource is an image, looks through the linked Dockerfile for a match on the handler.
* The handler is relative to the Dockerfile location, unless it's C# (in which case it's absolute).
* Looks for a direct match in quotes. (targeting things like `CMD ["app.handler"]`. 
Gives a bit better support to active development of image-based Lambdas.
Local tests and added tests pass.
* Generated handlers match those from initial SAM app creation (aside from the name).
* Actually works a bit better than the in-template API codelenses; those don't pick up paths.
> Source-based codelenses can generate template run configs for image-based Lambdas.

- .changes/next-release/Feature-2c4a26e6-46c9-4d6a-b94d-9b7b591d0fb7.json
- .changes/next-release/Feature-cbc68594-0491-470d-91b8-83ff87a3170c.json
- src/lambda/models/samLambdaRuntime.ts
- src/shared/sam/debugger/awsSamDebugConfigurationValidator.ts
- Support SAM CLI 1.16, which includes dotnet5.0 template support
- Not gated on SAM CLI version.
- Gating is planned for a future release, but the current behavior is reasonable: if `sam` is an older version which doesn't support the dotnet5.0 template, Toolkit focuses the VSCode Output window and shows this error message:
`Error: Invalid value for '-i' / '--base-image': invalid choice: amazon/dotnet5.0-base. (choose from amazon/nodejs12.x-base, amazon/nodejs10.x-base, amazon/python3.8-base, ...)`
- dotnet5: 
- tested with https://github.com/aws/aws-sam-cli/commit/8b7d51ac890d44e447850f8565ce43eb66065a56
- sam init works
- sam run/debug works
> runtimes: dotnet 5.0

- src/shared/telemetry/activation.ts
> cloud9: don't show telemetry popup

- .changes/next-release/Feature-0c29042c-cae4-4e59-82ca-6d2c091f5c1f.json
- src/lambda/local/debugConfiguration.ts
- src/shared/cloudformation/cloudformation.ts
- src/shared/cloudformation/templateRegistry.ts
- src/shared/sam/debugger/awsSamDebugConfigurationValidator.ts
- src/shared/sam/debugger/awsSamDebugger.ts
- src/shared/sam/debugger/commands/addSamDebugConfiguration.ts
- src/test/shared/cloudformation/cloudformation.test.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
- src/test/templates/sam/samTemplateGenerator.test.ts
Fields in the `Globals` field of a SAM template are now checked when handling SAM template operations.
* Any fields set directly in a Function resource will take priority over a Globals value.
* These fields can include Refs.
* Technically handles all [currently-accepted Globals fields](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html#sam-specification-template-anatomy-globals-supported-resources-and-properties), although we may not be handling these directly in the toolkit (they should be passed to execution, however)
SAM accepts values in `Globals` which we didn't account for.
https://github.com/aws/aws-toolkit-vscode/issues/1211
https://github.com/aws/aws-toolkit-vscode/issues/1395
Testing a SAM template with …
> Check SAM template global values if defaults are missing

- .changes/next-release/Feature-e62211a9-d387-469e-bd1b-645294b45a1e.json
- src/lambda/models/samLambdaRuntime.ts
- Support for SAM CLI 1.17: SAM create/run nodejs14.x
- nodejs12.x remains the default for now (`DEFAULT_RUNTIMES`), until we    implement fine-grained sam version handling.
> runtimes: add nodejs14.x

- src/lambda/commands/createNewSamApp.ts
- src/shared/activationReloadState.ts
- src/test/shared/activationReloadState.test.ts
Changes to `sam init` telemetry
* Removing potential PII source (`name` metadata)
* Telemetry event is emitted on `sam init` resumption
OpEx
> sam init telemetry improvements

- .changes/next-release/Breaking Change-711c2a47-7b8f-4554-b409-6d2fe567e0d8.json
- src/lambda/models/samLambdaRuntime.ts
- src/test/lambda/models/samLambdaRuntime.test.ts
- src/test/lambda/wizards/samInitWizard.test.ts
- src/test/shared/sam/cli/samCliInit.test.ts
nodejs8 is EOL and not supported by Lambda since 1 year.
> runtimes: remove nodejs8

- package.nls.json
- src/shared/sam/debugger/awsSamDebugger.ts
Rewording an extremely vague error message when a runtime is not inferrable by the SAM runner. This is increasingly necessary with image-type Lambdas, as the toolkit cannot infer the runtime from a Dockerfile.
> Better error message for missing runtimes

- src/shared/utilities/workspaceUtils.ts
Fixing an issue where we're using a `vscode.Uri.parse`, which caused file schemes to be off and create issues with relative pathing (for launch config creation)
https://github.com/aws/aws-toolkit-vscode/issues/1511
Local tests
> Fixing file scheme when parsing parent files

- src/shared/extensionUtilities.ts
Force any `isCloud9()` statements to `true` by adding the following setting to any VS Code settings:
```
{
...
"aws.forceCloud9": true,
...
}
```
Potentially override the `getIdeType()` call as well? 
Lets us test expected Cloud9 functionalities quickly in VS Code
See screenshot
(note fewer menu options)
> Force Cloud9 behavior with "aws-debug.forceCloud9" setting

- src/shared/sam/localLambdaRunner.ts
The `qs` property must be an object, not a string.
From https://github.com/request/request#requestoptions-callback :
> qs - object containing querystring values to be appended to the uri
Test coverage is in progress at https://github.com/aws/aws-toolkit-vscode/pull/1430
> APIGW: fix querystring

- src/shared/clients/defaultStsClient.ts
Problem:
Toolkit fails with "Error: Could not determine Account Id for credentials".
Solution:
Set the `stsRegionalEndpoints` flag on the client config:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#stsRegionalEndpoints-property
fixes https://github.com/aws/aws-toolkit-vscode/issues/1183
> auth: Set the `stsRegionalEndpoints` flag on the client config

- src/shared/utilities/childProcess.ts
Added error handlers to the ChildProcess start method to fix ENOTCONN errors on macOS (#1525)
Errors were propagating through the error and output streams of the child process and were not being handled correctly.
> Added error handlers for ChildProcess to fix ENOTCONN bug

- src/shared/utilities/timeoutUtils.ts
- src/test/shared/utilities/childProcess.test.ts
- src/test/shared/utilities/timeoutUtils.test.ts
A few changes have been done:
- Improved waitUntil in timeoutUtilities.ts by explicitly checking for undefined values and enforcing the timeout constraint, as mentioned in the comments of #1315
- Explicitly checking for undefined return values in waitUntil broke some test cases for childProcess.ts that relied on false return values, this was fixed by returning undefined in the test function for false values
- Test cases were added for waitUntil, again as mentioned in #1315
Previous comments mentioned an optional "attempts" parameter for waitUntil to prevent a function from being called for longer than the timeout period. Instead of this, waitUntil now records how long the function takes to execute. Now waitUntil will always terminate within the timeout period. …
> waitUntil(): ensure timeout, check undefined explicitly

- src/integrationTest/sam.test.ts
- src/lambda/commands/importLambda.ts
- src/shared/utilities/childProcess.ts
- src/test/shared/utilities/timeoutUtils.test.ts
Tests were sometimes failing erroneously due to the timeout time being too low.
A use of waitUntil was also changed to not use false return values.
> waitUntil(): fix false positives

- package-lock.json
- With this change, npm updated `lockfileVersion` from 1 to 2. That adds 12k lines, because it keeps the old structure for backwards compatibility.
- update "elliptic" to 6.5.4
Steps performed:
$ rm -rf node_modules
$ npm audit fix
> build: update dependencies

- src/shared/sam/cli/samCliLocator.ts
These messages are redundant and very noisy (1k+ in CI logs, also for user sessions), only log them once per session.
> SAM config: avoid noisy log messages

- media/css/samInvokeForm.css
- src/lambda/vue/samInvokeVue.ts
This fixes a bug that occurred when attempting to load a config when data had already been entered or a different config was already loaded.  The `clearForm` method will run immediately before loading a config into the form.
> Lambda UX: bug fix - clear form prior to loading new config

- src/credentials/sso/diskCache.ts
- src/shared/utilities/textUtilities.ts
- Move the hash logic out of textUtilities: it is only for use by SSO.
- Explain the reasoning for SHA1
- Suppress the LGTM warning to avoid false positive.
> SSO: clarify SHA1 usage, suppress warning

- package.nls.json
- src/credentials/activation.ts
- src/credentials/credentialsStore.ts
- src/credentials/credentialsUtilities.ts
- src/credentials/providers/sharedCredentialsProvider.ts
- src/credentials/providers/ssoCredentialProvider.ts
- src/credentials/sso/diskCache.ts
- src/credentials/sso/ssoAccessToken.ts
- src/credentials/sso/ssoAccessTokenProvider.ts
- src/credentials/sso/ssoCache.ts
- src/credentials/sso/ssoClientRegistration.ts
- src/credentials/sso/ssoSupport.ts
- src/test/credentials/diskCache.test.ts
- src/test/credentials/provider/ssoAccessTokenProvider.test.ts
- src/test/credentials/provider/ssoCredentialProvider.test.ts
- src/test/shared/credentials/credentialsStore.test.ts
- Merge SSO authentication feature into main.
- Toolkit SSO credentials flow:
1. Check local cache.
2. Perform SDK API call and get a device code.
3. Use the device code to make SDK API call to get an access token (`ssoClient.createToken()`).
> Merge feature/sso

- src/integrationTest/sam.test.ts
- src/integrationTest/shared/codelens/samTemplateCodeLensProvider.test.ts
> CI: temporarily skip integ tests on vscode 1.42

- src/lambda/commands/createNewSamApp.ts
Users were being told the SAM CLI was not found even though they were not trying to use serverless applications (see #1580). This was because the SAM version was being checked before `pathToLaunch` was checked. Bug originated from this PR: #1554
> SAM: fixed bug created by adding version telemetry

- src/test/shared/logger/winstonToolkitLogger.test.ts
Test may fail if the file contents aren't flushed before the check.
Observed in https://github.com/aws/aws-toolkit-vscode/pull/1557/checks?check_run_id=2135797945
1 failing
1) WinstonToolkitLogger
logs to a file
logs error:
AssertionError [ERR_ASSERTION]: Expected log message was missing
-false
+true
at Suite.<anonymous> (d:\a\aws-toolkit-vscode\aws-toolkit-vscode\src\test\shared\logger\winstonToolkitLogger.test.ts:151:24)
at fulfilled (d:\a\aws-toolkit-vscode\aws-toolkit-vscode\dist\src\test\shared\logger\winstonToolkitLogger.test.js:9:58)
> test/logger: avoid false positive because of slow filesystem

- src/integrationTest/sam.test.ts
blocked by https://github.com/aws/aws-sam-cli-app-templates/issues/95
> test/integ: skip python3.8 test broken by upstream

- src/lambda/commands/createNewSamApp.ts
Checks if previous SAM initialization state exists outside of the try/catch block. The `finally` block was always being executed previously, regardless of whether or not we were resuming SAM app creation.
> startup: skip telemetry if we aren't resuming

- src/extension.ts
- src/lambda/commands/createNewSamApp.ts
- src/shared/activationReloadState.ts
- src/shared/extensionGlobals.ts
- src/shared/sam/activation.ts
- src/shared/telemetry/telemetryService.ts
- src/test/fake/fakeTelemetryService.ts
- src/test/globalSetup.test.ts
- src/test/shared/activationReloadState.test.ts
- src/test/shared/telemetry/defaultTelemetryService.test.ts
Assert that non-passive metrics are never emitted at startup (except when "resuming", i.e. `resumeCreateNewSamApp()`).
After reverting e9f6543ae4cc, integration tests fail correctly:
1) "before all" hook in "{root}":
Error: non-passive metric emitted at startup
at Object.<anonymous> (/Volumes/workplace/aws-toolkit-vscode/src/extension.ts:247:23)
> telemetry: never emit non-passive metrics at startup

- src/shared/awsClientBuilder.ts
- src/shared/telemetry/defaultTelemetryClient.ts
JB reference: https://github.com/aws/aws-toolkit-jetbrains/pull/2507
sidenote on change: I would have preferred it to be like JB where we added it explicitly in the constructor of each client (but we have an additional layer that makes it easier), so fall back to "add another argument"
> telemetry: do not add user agent to requests

- .changes/next-release/Feature-b6e48e85-7d01-40fd-82b2-be99cf3a6244.json
- package.nls.json
- src/stepFunctions/activation.ts
- src/stepFunctions/asl/aslServer.ts
- src/stepFunctions/asl/client.ts
- src/stepFunctions/commands/createStateMachineFromTemplate.ts
- src/stepFunctions/commands/publishStateMachine.ts
- src/stepFunctions/commands/visualizeStateMachine/aslVisualization.ts
- src/stepFunctions/constants/aslFormats.ts
- src/stepFunctions/wizards/createStateMachineWizard.ts
- src/test/stepFunctions/commands/visualizeStateMachine.test.ts
Adds ability to publish YAML state machine for Step Functions. 
When user tries to publish state machine in yaml or asl-yaml format, it will be converted to json and published to Step Functions API. SFN API does not support publish of YAML state machines directly so it needs to be converted to JSON first. 
We want to give users ability to publish their state machines in YAML.
#1526 
> SFN: adds publish for YAML state machine

- src/credentials/loginManager.ts
- src/credentials/providers/credentialsProvider.ts
- src/credentials/providers/credentialsProviderId.ts
- src/credentials/providers/sharedCredentialsProvider.ts
- src/test/shared/credentials/loginManager.test.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
Before this, we did not record CredentialType.
The old/existing `SharedCredentialsProvider.getCredentialsType()`
function does nothing very useful, we should migrate away from it.
> telemetry: record CredentialType on login

- src/test/credentials/provider/ssoAccessTokenProvider.test.ts
Unreliable SSO tests (#1583) caused by unfulfilled promises.
Use `clock.runAllAsync` to make sure the tests do not get stuck waiting for a promise to be fulfilled.
Arrow functions were replaced to stay aligned with #1561 (unrelated to the fix).
> test: fix unreliable SSO tests

- src/shared/defaultAwsContextCommands.ts
The command 'AWS.command.credential.profile.create' was failing despite valid inputs, caused by old code not being updated to use new structures.
Create a new `CredentialsProviderId` using the `SharedCredentialsProvider` type and pass that to the login manager. Consider this fix temporary until a more defined way of assigning credential provider types is established.
Bonus: the credentials file is opened after creating a new profile (it was not doing this behavior previously)
> credentials: fix "Create Credentials Profile" command

- src/shared/logger/index.ts
- src/shared/logger/logger.ts
- src/shared/sam/cli/samCliInfo.ts
- src/shared/sam/cli/samCliInvoker.ts
- src/shared/sam/cli/samCliInvokerUtils.ts
- src/shared/sam/cli/samCliLocalInvoke.ts
- src/shared/sam/debugger/csharpSamDebug.ts
- src/shared/utilities/childProcess.ts
- src/test/shared/utilities/childProcess.test.ts
"sam --info" is noisy and not useful in the logs.
before:
2021-03-31 16:37:03 [VERBOSE]: SAM debug: config: "3/31 API n12-image:HelloWorldFunction (nodejs12.x)"
2021-03-31 16:37:03 [VERBOSE]: Searching for SAM CLI in: /usr/local/bin/sam
2021-03-31 16:37:03 [INFO]: Running command: (not started) [/usr/local/bin/sam --info]
2021-03-31 16:37:03 [INFO]: SAM CLI not configured, using SAM found at: '/usr/local/bin/sam'
2021-03-31 16:37:03 [VERBOSE]: running: (not started) [/usr/local/bin/sam --info]
2021-03-31 16:37:04 [VERBOSE]: stdout: {
"version": "1.20.0"
}
after:
2021-03-31 16:49:21 [VERBOSE]: SAM debug: config: "3/31 API n12-image:HelloWorldFunction (nodejs12.x)"
2021-03-31 16:49:21 [VERBOSE]: Searching for SAM CLI in: /usr/local/bin/sam
2021-03-31 16:49:22 [INFO]: SAM CLI location: …
> childprocess: do not log "sam --info" command

- package-lock.json
- package.json
Old SDK version had a bug with the credentials system (#641, #1541, #1603)
Update the SDK 
> build: Update AWS SDK

- src/extension.ts
- src/shared/extensionUtilities.ts
- src/shared/telemetry/defaultTelemetryService.ts
- src/shared/telemetry/telemetryService.ts
- src/test/shared/telemetry/defaultTelemetryService.test.ts
When asserting passive metrics at startup, we must skip cached telemetry
from the previous session: it can contain arbitrary metrics, we cannot
reason about whether they should be passive or active.
ref #1592
> telemetry: do not assert *cached* metrics at startup

- src/shared/sam/cli/samCliStartApi.ts
- src/shared/sam/localLambdaRunner.ts
Debugger was not attaching when using image lambdas in `start-api` mode. See #1443
This was because container environment variables were not being given to SAM CLI. SAM should be setting defaults if we fail to give it environment variables, but for some reason it isn't. It's difficult to say what the exact cause is due to so many parameters being exchanged. One possibility is that something we're setting is preventing the defaults from being used.
Add a `containerEnvFile` field to `buildSamCliStartApiArguments`.
**Future work:**
There seems to be a ton of duplicate code for invoking local lambdas, which is probably why this bug happened (invoke local had the correct field, API did not). Some refactors surrounding the SAM CLI code should be considered, especially for the argument …
> fix: Pass container environment variables when invoking SAM API

- src/shared/sam/localLambdaRunner.ts
- src/test/shared/codelens/localLambdaRunner.test.ts
Retrying more than once is a bad experience: VSCode will show the
debugger UI again and again, and user must hit the "Stop" button every
time we retry.
TODO: can we listen to the "Stop" button and cancel retries then?
> SAM debug: retry only once

- src/shared/sam/localLambdaRunner.ts
`onWillAttachDebugger` was creating a race condition between debugger attachment and checking for ports. 
Use 'await' to make it a blocking call. If this causes tests to fail then we should just rip out the `waitForPort` code (it was never doing anything useful before).
> SAM: Make 'onWillAttachDebugger' do something useful

- src/integrationTest/sam.test.ts
- src/integrationTest/shared/codelens/samTemplateCodeLensProvider.test.ts
Extra code was being used to handle runtimes differently. 
Moved the `startDebugger` code and rewrote some of it to manage race conditions better.
~~**Removed the skips for 1.42 to test to see if it works now**~~
Python still fails, seems to have something to do with the DAP for that version.
**Also need to make sure this doesn't negatively affect Java tests too much**
> test/integ: Remove runtime workaround

- src/shared/sam/debugger/javaSamDebug.ts
The Java debugger didn't attach ~50% of the time on first try. For the most part, it seemed that it attached 100% on the second attempt. This means that we likely need a delay before the debugger starts fully.
This introduces a 250 ms wait before attaching. This is a lot more consistent on my machine; will see if it's better for others.
> Delay makes debugger attach more consistently

- src/lambda/commands/createNewSamApp.ts
- src/shared/activationReloadState.ts
- src/shared/cloudformation/templateRegistry.ts
- src/test/lambda/commands/createNewSamApp.test.ts
- src/test/shared/activationReloadState.test.ts
Duplication of https://github.com/aws/aws-toolkit-vscode/pull/1645 , but for master with Java references removed. Will keep the other PR around for the Java codelens one-liner, but this change is deemed impactful enough to merge directly into master.
Launch configs weren't created on sam init
Swapping to opening the readme file caused some issues with creating the initial launch config, so we now explicitly look at the template and readme files on creation.
> Fixing template config creation on sam init

- src/shared/cloudformation/templateRegistry.ts
Java codelenses couldn't infer templates to make template config
Granted Java codelenses the same logic used by C#.
> Java codelenses can infer templates

- src/shared/logger/activation.ts
- src/shared/logger/logger.ts
- src/shared/logger/winstonToolkitLogger.ts
- src/test/shared/logger/winstonToolkitLogger.test.ts
- src/test/testLogger.ts
The function `getLogById` would fail to find the recorded log on Windows machines. This was because the file scheme was hardcoded as 'file://', but on Windows local files use the scheme 'file:///'.
Require log tracking functions to use `vscode.Uri` instead of a raw string. This way we do not have to worry about parsing for different operating systems.
> logger: Fix 'getLogById'

- src/integrationTest/sam.test.ts
Integration tests sometimes fail due to active debug sessions. This can happen if a session starts after another one ends, but before the next test begins. The 'getAddDebugConfigCodeLens' also would run indefinitely if it timed-out.
* Repeatedly force old debug sessios to close before beginning a new session (***).
* Update 'getAddDebugConfigCodeLens' to use 'waitUntil'
* Add constants for readability
*****This is just so integration tests don't erroneously fail as much. The root cause lies somewhere with the NodeJS tests, since those are the only ones causing this issue. Ideally there should never be a debug session from a previous state.**
> integ/tests: Minor improvements for 'sam.test.ts'

- package.nls.json
- src/lambda/commands/createNewSamApp.ts
- src/shared/constants.ts
Users who have created a SAM application might not know what to do after they've created it.
Offer a user a direct link to the relevant docs on create.
Links to the following pages: [VS Code](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/serverless-apps.html#serverless-apps-debug) , [Cloud9](https://docs.aws.amazon.com/cloud9/latest/user-guide/serverless-apps-toolkit.html#sam-run-debug)
> Users can get help after creating a new SAM app

- src/integrationTest/sam.test.ts
Previous attempt to fix active debug sessions not disappearing failed. This causes tests to fail even though an active debug session does not really affect the debugging of a new session. 
* Suppress assertions when the previous debug session was Node (this appears to be the only one that causes this issue)
* The code that forced sessions to quit was removed since it didn't work. 
* Frozen debug sessions will now appear in the session log as a warning. This is to remind us that a problem exists without having to retry integration tests. 
* The time to wait for sessions to disappear was also reduced slightly.
> tests/integ: Suppress asserts for previous Node debug sessions

- src/lambda/commands/deploySamApplication.ts
Deploying a SAM application wouldn't show any of the resources in the AWS explorer on a successfuly deployment
Refresh the entire explorer on deploy. Opting for this over a single service because CFN/SAM can deploy more than just Lambda.
> AWS Explorer refreshes after SAM application is deployed

- .changes/next-release/Bug Fix-adb07031-c137-4311-b1b2-57023233c633.json
- src/shared/sam/debugger/pythonSamDebug.ts
- src/shared/sam/localLambdaRunner.ts
'debugpy' does not emit a message when it starts, so our cue message only detects when the debug wrapper is executed. Since we do not retry debugger attachment anymore, the process will fail if 'debugpy' has not completely finished initializing. 
* Bump the sleep time from 1 second to 3 seconds
* Use `waitForPort` before we sleep. The port being used does not mean that 'debugpy' is ready for connections, but it does mean it has started the server (so slightly better than the cue message).
> SAM: Add retries back in for Python only

- .changes/next-release/Feature-4362f78f-c52d-4fab-b215-f744c7b090e0.json
- .changes/next-release/Feature-d0efaf09-2f4a-4a35-b742-1e13719dcd5b.json
- src/cdk/explorer/detectCdkProjects.ts
CDK Explorer does not detect CDK projects that are children-of-children
of the main root folder.
Search one level deeper.
> CDK: search 2 levels of descendants

- .changes/next-release/Removal-e6787559-2fbe-4733-bcfa-f019b6ac99dd.json
- package.json
- package.nls.json
- src/awsexplorer/activation.ts
- src/cdk/activation.ts
- CDK: the "Enable CDK" setting is redundant, VSCode already has implicit support for showing/hiding panels
- CDK panel is shown on Cloud9
- remove "Enable CDK" setting
- hide CDK on Cloud9
Closes https://github.com/aws/aws-toolkit-vscode/issues/1669
> settings/CDK: remove "Enable CDK" setting

- src/shared/cloudformation/cloudformation.ts
- src/shared/sam/localLambdaRunner.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
Cannot run/debug if project dir has non-alphanumeric chars (such as hyphens).
- For Java compat, ba1cbffc57a3b changed makeResourceName() (which   generates a temporary/intermediate template.yaml) such that it chooses  a resource name based on the project directory name.
- To avoid having multiple codepaths, we chose to use this logic for    all runtime types.
- But filesystem (directory) name may have characters that are not    allowed in a SAM/CFN template.yaml resource id (logical id).
- Scrub the name when generating a resource id.
- Expand the path to ensure relative paths like "." have a usable name.
ref https://github.com/aws/aws-toolkit-vscode/issues/1684
ref https://github.com/aws/aws-toolkit-vscode/issues/1685
By submitting this pull request, I confirm that my contribution is …
> SAM run/debug: cannot run/debug if project dir has non-alphanumeric chars

- .changes/next-release/Feature-c408b805-298c-4ac9-9884-96dc6594282b.json
- src/shared/logger/activation.ts
Logs were being store in hard-coded locations that differed by OS. Addresses #1692
Use VS Code's 'globalStoragePath'
> Logging: change location of logs to use 'globalStoragePath'

- .changes/next-release/Feature-0eb750ad-9159-4b82-9f58-f68b3510ff79.json
- src/shared/sam/debugger/csharpSamDebug.ts
- src/shared/sam/debugger/goSamDebug.ts
- src/shared/sam/debugger/javaSamDebug.ts
- src/shared/sam/debugger/pythonSamDebug.ts
- src/shared/sam/debugger/typescriptSamDebug.ts
- src/shared/sam/localLambdaRunner.ts
Our lambda runner would keep trying to execute despite key components failing, frustrating users and outputting useless information.
* Break up lambda runner into key components (Builder and Invoker functions)
* Return a boolean for the success or failure of each function
* Immediately return as soon as a component fails
> SAM: Stop lambda runner on a fatal error

- .changes/next-release/Feature-5137cbc0-26f1-4f13-9a14-e39394545448.json
- package.json
- src/cdk/activation.ts
- src/cdk/explorer/awsCdkExplorer.ts
- src/test/cdk/explorer/awsCdkExplorer.test.ts
1. If CDK view is hidden, it's wasteful to search for CDK projects.
1. Any view can be shown/hidden. But the Toolkit "standard" menu items (such as help docs, feedback, etc.) are defined in the AWS view. 
1. Skip search if CDK view is not visible; refresh() when set to visible.
1. If the AWS view is hidden, show the "standard" menu items in non-AWS view menus.
- ref e132be025e90 #1632
> CDK: show main-menu items if AWS panel is hidden; search for projects only if CDK is enabled

- buildspec/linuxIntegrationTests.yml
dirmngr sometimes fails with a "IPC error", which causes CI to fail.
Remove it since it was a temporary fix for https://github.com/yarnpkg/yarn/issues/7866
ref a52644096ba9e3a4815ef98debed04053893f23f
ref c8fb4347b7bd7a8b38bda821a1463115607f4db1
> CI: remove dirmngr + apt-key step

- src/cdk/explorer/detectCdkProjects.ts
`detectCdkProjectsInFolder()` produces log spam for every folder which does *not* have a cdk.json:
2021-05-03 03:57:44 [DEBUG]: Error detecting CDK apps in /Volumes/workplace/sam-samples: [Error: ENOENT: no such file or directory, access '/Volumes/workplace/sam-samples/cdk.json'] {
errno: -2,
code: 'ENOENT',
syscall: 'access',
path: '/Volumes/workplace/sam-samples/cdk.json'
}
This is not useful, we only might be interested in "permissions issue" cases.
Skip ENOENT cases.
> CDK: reduce log noise

- .github/dependabot.yml
Dependabot sends PRs to staging repo.
Specify "master" branch explicitly.
From https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#target-branch : 
> When you use this option, the settings for this package manager will no longer affect any pull requests raised for security updates.
Hmm..
> CI/dependabot: avoid PRs in "staging"

- src/awsexplorer/activation.ts
- src/extension.ts
Toolkit eagerly tries to login on startup, regardless of whether it is being used.
Do not attempt auto-login until AWS Explorer is made visible.
ref #1433
> startup: auto-connect when AWS Explorer is shown

- package.nls.json
- src/lambda/commands/uploadLambda.ts
Lambda upload message was confusing
Removed confusing bits and made it more in-line with the console notifications.
> Better direct Lambda upload messaging

- src/credentials/activation.ts
- src/credentials/providers/credentialsProviderId.ts
- src/credentials/providers/credentialsProviderManager.ts
- src/shared/logger/winstonToolkitLogger.ts
Related: 09f505fff6e8 #1641
Similar to 09f505fff6e8, we can't assume that `getCredentialProviderNames()` returns anything valid... because `loadSharedCredentialsProfiles()` is lying to us...?
- Check for undefined
- Log a warning message
- Skip popup message on Cloud9
> autoconnect: fix potential use of undefined

- designs/credentials/class-diagram.svg
- designs/credentials/credentials-management.md
- package-lock.json
- package.json
- src/credentials/loginManager.ts
- src/credentials/providers/credentialsProviderFactory.ts
- src/credentials/providers/sharedCredentialsProvider.ts
- src/credentials/providers/sharedCredentialsProviderFactory.ts
- src/test/credentials/provider/credentialsProviderFactory.test.ts
- src/test/credentials/provider/credentialsProviderManager.test.ts
- src/test/credentials/provider/sharedCredentialsProvider.test.ts
- src/test/credentials/provider/sharedCredentialsProviderFactory.test.ts
- src/test/shared/credentials/loginManager.test.ts
#1691 changed user-visible credentialId string, which also decides how `aws.credentials` is resolved from a launch config.
revert #1691 5785aa819304142fecd82e0a7795d5aa7c900be7
> Revert "telemetry: Login sets "passive" instead of skipping telemetry"

- package.json
- src/shared/sam/activation.ts
aws.sam.enableCodeLenses was defined with default "true" (string)
instead of true (boolean), so readSetting() returned nonsense which
caused the initial invocation of the "Toggle" command to do nothing.
- Fix the aws.sam.enableCodeLenses defined in package.json
- Simplify the code a bit.
> SAM hints: fix "aws.sam.enableCodeLenses" default

- src/shared/sam/debugger/goSamDebug.ts
On some macOS machines, `go get -d 'github.com/go-delve/delve/cmd/dlv'`
does not install to the expected `globalStoragePath` directory.
- Set `GO111MODULE=off` before the `go get -d …` invocation.
- Use execFileSync() instead of execSync() to avoid shell-specific quoting issues.
> SAM/go: fix delve install

- src/shared/sam/debugger/awsSamDebugConfiguration.ts
Code launch configs were using the manifest's parent's parent directory. 
Go one level lower.
> SAM: use manifest's parent directory name for code launch configs

- cloud9-toolkit-install.sh
Problem:
If "~/environment/.c9/extensions" does not exist, the `mv` step fails.
Solution:
Ensure the directory exists.
ref a60fd39a28dbfa91e8f063019fcc657e4f619d66 #1673
> cloud9-toolkit-install.sh: ensure directories

- src/lambda/models/samLambdaRuntime.ts
- src/lambda/wizards/samInitWizard.ts
- src/shared/sam/debugger/awsSamDebugConfigurationValidator.ts
- src/test/lambda/models/samLambdaRuntime.test.ts
- Cloud9 shows dotnet5.0 in runtime quickpick menu, but it's not supported there.
- Runtimes in each IDE are not clear, which leads to mistakes.
- Exclude dotnet5.0 in Cloud9.
- Add tests to make the resolved runtimes super clear.
> SAM runtimes: exclude dotnet5.0 on cloud9

- src/lambda/vue/samInvoke.ts
- src/lambda/vue/samInvokeVue.ts
- src/webviews/main.ts
* Webview in Cloud9 was not populating with data
* aws-sam configs require a runtime when invoking an image runtime
* Runtimes were static
* Added a 500ms delay for Cloud9 on messaging in initial webview state
* Runtime now immediately available to set for all launch config types in webview
* Dynamically message runtimes to webview on load
> Invoker webview fixes

- package.json
- src/shared/codelens/codeLensUtils.ts
- src/shared/sam/activation.ts
- src/test/shared/codelens/codeLensUtils.test.ts
"Add SAM Debug Configuration" command was inconsistent to inexperienced users
Get rid of the conditional and let errors handle themselves.
> Always show 'Add SAM Debug Configuration' command

- .changes/next-release/Bug Fix-e4696f16-db39-4fa3-b140-324eeb8995d9.json
- package.json
- src/lambda/commands/deploySamApplication.ts
- src/lambda/wizards/samDeployWizard.ts
- src/test/lambda/commands/deploySamApplication.test.ts
We specified the `manuallySelectedBuckets` as an object but we were storing it as a string. 
* Write the setting as an object. A new interface `SavedBuckets` was added to clarify the structure of saved buckets.
* Check for previously saved stringified buckets and parse them. Failed parses will reset the setting.
* Add two new tests to check the above.
> SAM/Deploy: fix recently used bucket setting

- src/integrationTest/codelens.js.test.ts
- src/integrationTest/integrationTestsUtilities.ts
- src/integrationTest/sam.test.ts
- src/shared/sam/localLambdaRunner.ts
- test-scripts/test.ts
A test or two will fail randomly during integration tests (though every other test passes)
The command `sam local start-api` appears to sometimes build the image twice for the 'image' + 'start-api' combo, causing the test to fail due to timeout.
* Add a start-up delay before running tests (20 seconds for now)
* Force 'skip-pull-image' when invoking an API lambda.
* Small refactor to `codelens.js.test.ts` (why is this named like that) replacing `expectCodeLenses` with `getAddConfigCodeLens`
> integ/tests: Reduce transient failures

- src/shared/awsClientBuilder.ts
- src/shared/clients/defaultApiGatewayClient.ts
- src/shared/clients/defaultCloudFormationClient.ts
- src/shared/clients/defaultCloudWatchLogsClient.ts
- src/shared/clients/defaultEcrClient.ts
- src/shared/clients/defaultEcsClient.ts
- src/shared/clients/defaultIamClient.ts
- src/shared/clients/defaultLambdaClient.ts
- src/shared/clients/defaultS3Client.ts
- src/shared/clients/defaultSchemaClient.ts
- src/shared/clients/defaultSsmDocumentClient.ts
- src/shared/clients/defaultStepFunctionsClient.ts
- src/shared/clients/defaultStsClient.ts
- src/shared/telemetry/defaultTelemetryClient.ts
- src/test/shared/defaultAwsClientBuilder.test.ts
`createAndConfigureServiceClient()` is awkward to use and hard to understand because of indirection.
- introduce `createAwsService()`
- document it
- remove `createAndConfigureServiceClient()`
> refactor: improve ergonomics of AWSClientBuilder

- build-scripts/package.ts
- package-lock.json
- package.json
- src/shared/sam/cli/samCliLocalInvoke.ts
- src/shared/utilities/childProcess.ts
- src/ssmDocument/commands/publishDocument.ts
- src/test/globalSetup.test.ts
- test-scripts/launchTestUtilities.ts
Reverts ce3089742f9695d2ebd55df85e7ec59ddfb126fa #1758
https://github.com/aws/aws-toolkit-vscode/pull/1758#issuecomment-842555310
> This update should not be done since the node version is based off the one used by the minimum version 1.42 which is node 12:
> Revert "build(deps-dev): bump @types/node from 10.17.35 to 15.0.3"

- package.json
- src/shared/sam/localLambdaRunner.ts
- src/shared/utilities/timeoutUtils.ts
Some builds take a long time.  For example, the TypeScript sample template has multiple resources that each require an install and compile step.  The timer created from `createInvokeTimer` expires before reaching the invoke step.
~~Create a reset for timers.~~
Refresh the timer.
> SAM debug: refresh timeout after "sam build" step

- src/shared/sam/debugger/typescriptSamDebug.ts
If the TypeScript compiler is not installed and a local invoke is called where the target is the source code, the app will not fail until the invoke step and the error is not clear.
Check for TypeScript compiler before attempting to compile and show a clear error if it is not present.
> SAM debug: target=code: require TypeScript on host system

- src/shared/sam/cli/samCliLocalInvoke.ts
- src/shared/sam/localLambdaRunner.ts
Local invoke will build and attempt to invoke before failing due to Docker either not installed or running.
Verify if Docker is installed and running before the build step to quickly inform the user that Docker is either not installed or not running.
> SAM debug: fail early if Docker is not working

- src/lambda/commands/createNewSamApp.ts
- src/test/lambda/commands/createNewSamApp.test.ts
When the template extension is `.yml` instead of `.yaml`, as is the case for the TypeScript SAM template, the toolkit will give a warning that the template file was not found.
The toolkit now looks for `template.yml` when `template.yaml` is not found.
> New SAM app: Recognize .yml extension for template

- .changes/next-release/Bug Fix-48dd227c-8804-4f2a-8f5c-54a99d1966e7.json
- package.json
- package.nls.json
- src/integrationTest/integrationTestsUtilities.ts
- src/shared/sam/localLambdaRunner.ts
The name is referencing only debug attachment, but the timer is being used for the entire workflow.
> Settings: update lambda timeout setting name

- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
- src/testFixtures/workspaceFolder/ts-plain-sam-app/src/app.ts
Update to `js-yaml` dependency #1703 caused some tests to fail:
1. The expected output for a test incorrectly wraps a field with quotes.
2. Parameter for sample TS app needs to be typed correctly.
1. Correct the format of the output by removing the quotes.
2. Add type for the parameter.
> Tests: fix tests after dependency update

- .changes/next-release/Feature-539b9557-6b71-4741-a943-5e8739d24a88.json
- package.json
- src/lambda/wizards/samDeployWizard.ts
- src/shared/sam/activation.ts
- src/shared/watchedFiles.ts
- src/test/lambda/wizards/samDeployWizard.test.ts
To deploy using AWS Toolkit, the order of operations is:
1. start Deploy action
2. select the relevant template.yaml
But sometimes it's easier to reach SAM template.yaml file from the VSCode File Explorer, so the order is swapped:
1. select template.yaml
2. start Deploy action
https://github.com/aws/aws-toolkit-vscode/issues/263
Show the Deploy action on template.yaml files.
> SAM/deploy: user can start Deploy from template.yaml

- src/lambda/config/parameterUtils.ts
- src/lambda/config/samParameterCompletionItemProvider.ts
- src/lambda/wizards/samDeployWizard.ts
- src/test/cdk/detectCdkProjects.test.ts
- src/test/cdk/explorer/appNode.test.ts
- src/test/cdk/explorer/constructNode.test.ts
- src/test/cdk/iconPathUtils.ts
- src/test/cdk/tree/treeInspector.test.ts
- src/test/cdk/treeTestUtils.ts
- src/test/lambda/utilities/parameterUtils.test.ts
- src/test/lambda/wizards/samDeployWizard.test.ts
Problem
-------
In terms of project layout, it is unnecessary to have a utilities/ subdirectory (or "module family") in various sub-topics.
Utils should live in one of:
1. the top-level (root) util/ directory, or...
2. a named module ("foo.ts", no need for "util/foo.ts"), or...
3. "util.ts" in the family subdir (not "util/\*.ts")
Solution
--------
- Move lambda/utilities/parameterUtils.ts -> lambda/config/parameterUtils.ts
- Move src/test/cdk/utilities/\*.ts -> src/test/cdk/\*.ts
Benefits:
* "Economy of patterns" (eliminate frivolous choice) makes it clear to new developers which patterns to follow. This increases consistency, which increases discoverability.
* Avoids unnecessary nesting and entropy.
By submitting this pull request, I confirm that my contribution is made under the terms …
> refactor: eliminate utilities/ subdirectories

- package-lock.json
- package.json
- src/lambda/vue/samInvokeVue.ts
- src/webviews/main.ts
VS Code now has an official type for the [webview-owned `vscode` object](https://code.visualstudio.com/updates/v1_57#_vscodewebviewdts).
> Use vscode-webview types

- package.json
Problem
-------
Not obvious how vscode classifies Toolkit.
Solution
--------
Declare the extensionKind explicitly.
This also serves as a form of documentation.
> package: declare explicit extensionKind

- src/integrationTest/globalSetup.test.ts
- src/integrationTest/integrationTestsUtilities.ts
- src/integrationTest/sam.test.ts
- src/integrationTest/shared/codelens/samTemplateCodeLensProvider.test.ts
- src/shared/codelens/codeLensUtils.ts
- src/shared/codelens/goCodeLensProvider.ts
- src/shared/sam/activation.ts
- src/shared/sam/debugger/javaSamDebug.ts
- src/shared/sam/debugger/pythonSamDebug.ts
- src/shared/utilities/vsCodeUtils.ts
- src/test/shared/utilities/vscodeUtils.test.ts
Various parts of the codebase need to check if an extension is available and/or activate it, but the logic is duplicated.
Deduplicate.
> refactor: DRY extension-check/activate code

- .changes/next-release/Bug Fix-00926769-d0c3-4810-8f46-46973a0d5e49.json
- src/shared/clients/defaultS3Client.ts
- src/shared/clients/s3Client.ts
- src/test/shared/clients/defaultS3Client.test.ts
Problem
-------
headBucket calls are redirected to bucket local region endpoints. Cross WAN calls are expensive and not always possible.
Solution
--------
Use the getBucketLocation API to discover bucket regions staying within the client's configured region.
> S3: use getBucketLocation to lookup bucket regions

- test-scripts/integrationTest.ts
VS code 1.57 introduced a 'trust' feature that is applied to the current workspace, restricting extension access based on trust level. The insiders build allows individual extensions to have a trust level, by default they are untrusted. Untrusted extensions cannot be activated, thus failing the test. We are not particularly concerned with this functionality in regards to other extensions, so we will just disable it entirely when testing.
We should look into this more for our own extension as far as UX is concerned (what should our extension be capable of given a minimum trust level?)
Refer to this issue: https://github.com/microsoft/vscode/issues/120251
Considerations for the toolkit (to be added to `package.json`):
```javascript
capabilities:
untrustedWorkspaces:
{ supported: true } |
{ …
```
> integ/test: --disable-workspace-trust

- .changes/next-release/Bug Fix-4dea5c66-129e-462f-9bfe-4c04e074b9fd.json
- src/shared/constants.ts
- src/test/cloudWatchLogs/registry/logStreamRegistry.test.ts
Timestamp was 12 hour notation instead of 24.
Fixes #1820
> CloudWatch Logs: fix timestamp

- src/awsexplorer/activation.ts
- src/lambda/commands/deploySamApplication.ts
The toolkit currently does not discriminate between user-initiated and code-initiated refreshes.
If we want to record refreshes made by our own code then we should use a separate metric.
> telemetry: do not record explorer refresh from 'refreshAwsExplorerNode'

- package.json
- src/awsexplorer/regionNode.ts
- src/extension.ts
Notes:
* Basic workflow (right-click log group -> view log stream -> load newer and older codelenses) is successful
* Save Current Log and Copy Log Stream Name do not show up in the explorer or in the editor's top bar.
* The above functions DO show up when you right-click an editor tab. However, this is currently causing an issue: once these options become visible in a right-click menu, they appear in the right-click menu for all other editor nodes, and persist with behavior permanently: the option in all right click menus will copy the text from the first Cloudwatch Logs editor opened, and won't be removed or overwritten by closing the tab or opening a new log stream.
* The editor is not readonly and can be written in.
* The CWL implementation will overwrite all text on loading new …
> cloud9: enable CloudWatch Logs component

- src/integrationTest/shared/codelens/samTemplateCodeLensProvider.test.ts
- src/shared/codelens/codeLensUtils.ts
- src/shared/codelens/samTemplateCodeLensProvider.ts
Unclear that codelenses represent AWS functionality
Add "AWS: " (or "Amazon: " in China-vended assets) to codelenses in source files. Does not apply to CFN or SAM templates since there should be clear context that this is tied to AWS (can revisit this decision later)
> Add 'AWS: ' to codelenses in source files

- .husky/pre-commit
- src/shared/telemetry/defaultTelemetryClient.ts
- src/test/shared/defaultAwsClientBuilder.test.ts
- 9edae9a accidentally removed an argument in the createAwsService() call, but it was not caught because of `@ts-ignore`.
- Also: 
- code style: point to locally-installed pretty-quick. Don't require that `pretty-quick` is globally installed.
- Use a cast instead of `@ts-ignore`.
> telemetry: do not include user agent

- src/shared/cloudformation/cloudformation.ts
Webpack was resolving the schema module differently than TSC. So building with webpack resulted in a different import. Apparently js-yaml also lies about the types it accepts, so just using both exports works correctly.
ES6 modules are fun.
> CFN: fix bad default export

- .changes/next-release/Bug Fix-8d683e5f-f86c-4145-a6a8-03c5d357b00f.json
- src/lambda/commands/downloadLambda.ts
This was probably caused by moving to node 12. Something to do with permissions I would imagine.
Resolves #1857
If someone can manually test this fix too that'd be great since I don't know exactly what the expected behavior is other than that no warning or error message appears (and a file is opened).
> SAM: fix download lambda

- src/awsexplorer/defaultRegion.ts
- src/extension.ts
- src/s3/activation.ts
- src/shared/awsContext.ts
- src/shared/defaultAwsContext.ts
- src/shared/regions/regionUtilities.ts
- src/stepFunctions/commands/publishStateMachine.ts
- src/test/shared/regions/regionUtilities.test.ts
- src/test/utilities/fakeAwsContext.ts
DEFAULT_REGION was used on activate.ts
Elevated the usage to getCredentialDefaultregion()
> clients: drop DEFAULT_REGION, use getCredentialDefaultregion()

- .vscode/extensions.json
These extensions are not particularly related to this project, developers should install whatever they prefer for typescript/npm work.
Also markdownlint makes recommendations that are not necessarily aligned with our build tooling. Furthermore it is redundant, because our build lints itself, and prettier autoformats at commit-time.
> project: drop some recommended extensions

- .markdownlint.json
- .prettierignore
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- docs/CODE_GUIDELINES.md
Added linter exceptions that conflict with prettier
Also just fixed some of the minor linter stuff since it made it the file easier to read:
* Spaces around code blocks
* Add `ts` to language-specific blocks
I don't think GitHub markdown is smart enough to highlight TS types but it at least shows JS syntax correctly.
> docs: allow prettier on docs

- .changes/next-release/Bug Fix-e72a3c2c-d389-4664-8058-388265d03812.json
- src/cloudWatchLogs/explorer/cloudWatchLogsNode.ts
If a user has no logs the placeholder currently looks like an error. Make the placeholder clarify that no logs exist (which is not an error).
> CloudWatch Logs: normal placeholder

- src/shared/wizards/stateController.ts
- src/test/lambda/wizards/stateController.test.ts
* Wizard controller + `Prompter` abstraction will be second
* This is the biggest one since it includes a testing framework
* Concrete implementations of the `Prompter` abstraction will be the final PR
State machine controller that will be used in later PRs for the new wizard framework. Will eventually replace `multiStepWizard.ts` and related tests. The interface is different enough that it cannot replace it directly.
New capabilities:
* States are remembered and handled exclusively by the controller. This prevents mutation of state outside transitions.
* Multiple steps can be added to the machine at runtime as a group, allowing for dynamic branching.
* Decouples transitions from the state management logic. 
* Exposes the current step and total number of steps that the controller …
> UI: state machine controller (wizard framework 1/3)

- .changes/next-release/Feature-159d0360-1d9d-439a-aaf4-624434216694.json
- src/credentials/providers/ecsCredentialsProvider.ts
- src/extension.ts
- src/shared/environmentVariables.ts
- src/test/credentials/provider/ecsCredentialsProvider.test.ts
ECS container credentials can currently only be used by defining a credentials profile that specifies EcsContainer as a credential_source (added in #1833). This requires additional setup by the user.
This change adds a credentials provider for ECS containers that auto detects running in a container. This enables a zero touch credentials setup process.
ECS exposes environment variables to running tasks (`AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` or `AWS_CONTAINER_CREDENTIALS_FULL_URI`) with the location of credentials metadata. This check is performed by the [JavaScript SDK's ECS credentials](https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/remote_credentials.js#L99-L101) and is required to retrieve credentials.
Tested through VSCode remote attached to a locally running ECS …
> feat: add ECS credentials provider

- src/shared/ui/prompter.ts
- src/shared/utilities/tsUtils.ts
- src/shared/wizards/wizard.ts
- src/shared/wizards/wizardForm.ts
- src/test/shared/ui/prompter.test.ts
- src/test/shared/wizards/wizard.test.ts
- src/test/shared/wizards/wizardForm.test.ts
- src/test/shared/wizards/wizardTestUtils.ts
Two key objects are implemented in this PR: `Wizard` and `WizardForm`. Together these two things can be thought of as the 'Wizard Controller'. Concrete UI elements are also abstracted away as a `Prompter` object to be used by the wizard. This is by far the largest PR for the wizard framework, mostly due to the increased number of tests and focus on type-safety. The implementation itself is relatively small, but the large amount of flexibility offered by the framework made specialized testing code worth the effort.
At the highest level, QuickPicks and QuickInputs are just a way to collect data from the user. For QuickInputs the result is just a string, while QuickPicks can have arbitrary shape. To accommodate this, the `Prompter` abstraction uses generic types and makes no assumptions …
> UI: wizard controller and testing framework (wizard framework 2/3)

- .changes/next-release/Bug Fix-a2794092-7e1f-4b32-94f3-94f78512f1b7.json
- package-lock.json
- src/lambda/vue/samInvokeVue.ts
The 'Show All Fields' button was being treated as a form submission button, causing VS code to blank out the webview when clicking it. This bug did not affect Cloud 9.
> SAM Invoke Webview: fix 'Show All Fields'

- docs/TESTPLAN.md
- src/test/lambda/wizards/samDeployWizard.test.ts
`await` statements directly in `describe` blocks for Mocha tests cause the `describe` block to be evaluated for every test, including running `before` and `beforeEach` statements before all other tests. Even affects tests running with a `.only`! Also causes issues with some tests not running.
Removed an `await` statement from the SAM Deploy Wizard's tests and tested by adding a `.only` to a random test, and reveled in the fact that only that one test was run (and not the tests for the SAM Deploy Wizard). Added documentation for future reference.
> tests: removed await statement from describe block

- buildspec/linuxIntegrationTests.yml
CodeBuild images use `goenv` to install Go. This means they come with Go even if you do not specify a runtime. It also means you cannot upgrade the version the standard way, and instead must use `goenv` directly.
> tests/integ: fix Go install

- src/shared/cloudformation/templateRegistry.ts
- src/test/globalSetup.test.ts
- src/test/lambda/local/debugConfiguration.test.ts
- src/test/shared/cloudformation/templateRegistry.test.ts
- test-scripts/test.ts
Linus Stable/Insiders Unit Tests are failing with errors similar to:
```
Uncaught TypeError: this.onSuccess is not a function
at Timeout._onTimeout (/root/.vscode/extensions/redhat.vscode-yaml-0.21.1/node_modules/vscode-languageclient/lib/common/utils/async.js:36:22)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)
```
Location is arbitrary and sporadic.
Remove all dependence on the YAML extension existing for unit test codepaths:
* Remove YAML test extension installation
* Note: this still made the test fail even if the extension wasn't explicitly activated!
* Remove YAML test extension activation
* All YAML extensions setting updates no longer directly use the VS Code WorkspaceConfiguration object and can be spoofed. …
> Test fix: YAML extension onSuccess errors

- CONTRIBUTING.md
- docs/TESTPLAN.md
- TESTPLAN is an architecture/strategy document, guidelines are not
found there.
- Removed note about .only, because it is obvious, and mentioning it in
docs doesn't help to avoid such mistakes.
> doc: move "await in describe()" note

- test-scripts/test.ts
Other extensions running can cause problems with our unit tests, causing them to fail for non-obvious reasons. This PR disables all other extensions but our own for unit testing. Any test written that relies on other extensions should be treated as an integration test, not a unit test.
Add '--disable-extensions' to the test entry point. Calling 'activate' on extensions will not have any effect when using this argument, so we do not need to make any code changes.
> tests: disable extensions for unit tests

- src/shared/extensions.ts
- src/shared/extensions/git.ts
- types/git.d.ts
Wraps some of the Git API functionality in a new class. A wrapper is used since it appears some of the API calls are lacking in their capability, thus we sometimes want to use `git` directly. I'm open to ideas though in terms of how this wrapper should act in various circumstances. I was using it in a pretty narrow way so it may be that this solution is not ideal.
I'm currently thinking of making extension wrappers always 'silently' (but with logs) fail when the extension does not exist or is not enabled. The idea being that we do not want to be strictly dependent on other extensions; they should _enhance_ our own functionality. Of course, a caller can always check for enablement of the wrapper since there are definitely circumstances where behavior should be determined based off what …
> extensions: start Git extension API wrapper

- src/shared/cloudformation/activation.ts
- src/shared/cloudformation/cloudformation.ts
- src/shared/cloudformation/templateRegistry.ts
- src/test/shared/cloudformation/cloudformation.test.ts
Improvements from an internal bug bash:
* Don't block our extension load on the YAML extension's load
* Always create a new WorkspaceConfiguration object. Appears that the WorkspaceConfiguration will only pull the values from when it was created, in this case, it was bulldozing YAML schema definitions if you added them while the toolkit was activated and you saved a template file
* Only attempt to write to settings if the YAML extension is available.
* Add `file:/` to the YAML files. Existing impl worked on Windows, and Windows breaks if `file://` is used. Checking to see if this fixes Mac and Windows impls.
Additionally, now checks ALL `.yaml` and `.yml` files in a workspace. Unsure if this will significantly affect startup, but shouldn't explicitly block extension activation (aside from …
> SAM/CFN: JSON schema improvements

- package-lock.json
- package.json
- src/shared/clients/apprunnerClient.ts
- src/shared/clients/toolkitClientBuilder.ts
- src/test/shared/clients/mockClients.ts
Adds the client. Nothing fancy.
Side note: can we get rid of `MockToolkitClientBuilder`?? We have a big discrepancy in how our tests mock SDK clients. Some tests use these hand-made mocks, others use `mockito`. I'm in favor of just using `mockito`.
> Apprunner: add client

- .changes/next-release/Feature-d65c175d-c61e-4a9f-b428-e72f093dfcc6.json
- resources/markdown/samReadme.md
- src/lambda/commands/createNewSamApp.ts
- src/test/lambda/commands/createNewSamApp.test.ts
User does not have good in-your-face instructions on what to do with a SAM application in the toolkit after creating one.
Pop up a toolkit-specific readme.
* Does not include images to preserve relevance outside the toolkit/the user's computer
* Links to users' README.md and template.yaml files and external docs
* Does not link to any files outside the SAM-created folder as there is no guarantee the pathing will be correct.
> SAM/Lambda: show Toolkit-owned README file for new apps

- src/eventSchemas/wizards/schemaCodeDownloadWizard.ts
- src/lambda/wizards/samDeployWizard.ts
- src/lambda/wizards/samInitWizard.ts
- src/shared/ui/buttons.ts
- src/stepFunctions/wizards/publishStateMachineWizard.ts
- src/test/shared/ui/pickerPrompter.test.ts
* Add button toolkit documentation link as default to help button (I forgot to add this)
* Remove redundant tooltips from old buttons
* Skip `FilterBoxQuickPickPrompter` tests on 1.42
* Tests fail about 1 in every ~10 runs in CI
* Appears to be a race condition with the event callbacks
* Since we're moving off of 1.42 sooner rather than later, it's worth skipping these
> UI: button + text fixes

- src/awsexplorer/regionNode.ts
Refreshing the AWS Explorer will not properly refresh nodes that implement the LoadMoreNode interface. (Currently this affects ECS)
Executing the general refresh will search for nodes with a clearChildren method and execute. Calling a refresh directly on a node will not execute the clearChildren method.
> RegionNode: clear children on refresh

- src/apprunner/wizards/apprunnerCreateServiceWizard.ts
- src/apprunner/wizards/codeRepositoryWizard.ts
- src/apprunner/wizards/imageRepositoryWizard.ts
- src/shared/clients/iamClient.ts
- src/shared/constants.ts
- src/shared/ui/buttons.ts
- src/shared/ui/common/exitPrompter.ts
- src/shared/ui/common/rolePrompter.ts
- src/shared/ui/common/variablesPrompter.ts
- src/shared/ui/inputPrompter.ts
- src/shared/ui/pickerPrompter.ts
- src/shared/ui/prompter.ts
- src/shared/ui/wizardPrompter.ts
- src/shared/utilities/vsCodeUtils.ts
- src/shared/wizards/wizard.ts
- src/shared/wizards/wizardForm.ts
- src/test/apprunner/wizards/codeRepositoryWizard.test.ts
- src/test/apprunner/wizards/createServiceWizard.test.ts
- src/test/apprunner/wizards/imageRepositoryWizard.test.ts
- src/test/shared/clients/mockClients.ts
- src/test/shared/ui/inputPrompter.test.ts
- src/test/shared/ui/pickerPrompter.test.ts
- src/test/shared/ui/prompter.test.ts
- src/test/shared/ui/prompters/rolePrompter.test.ts
- src/test/shared/wizards/wizard.test.ts
- src/test/shared/wizards/wizardForm.test.ts
- src/test/shared/wizards/wizardTestUtils.ts
There's some extensions to the wizard framework here, mainly just adding a way to have an 'exit' prompt and functionality to estimate the # of steps that would be needed if the user goes down a certain path.
The majority of this PR is just creating a variety of different prompts and then routing them to the correct location. Due to limited time some things aren't _quite_ how I would like them. For example, many of the very simple prompts are not directly tested (like enter a port, name, etc.). 
> App Runner: wizard implementations

- package-lock.json
- package.json
- src/credentials/providers/credentials.ts
ECS IMDS credentials source is recorded as "ec2".
Update logic to use new "ecs" credentials source defined in
https://github.com/aws/aws-toolkit-common/pull/183
> telemetry: record ECS credentials source as "ecs"

- .changes/next-release/Bug Fix-716213c0-0281-477f-b556-92631bce89a5.json
- src/shared/cloudformation/cloudformation.ts
The YAML extension expects a URI path for schemas. It appears to also handle encoding correctly. Tested locally, need to verify that this works on other OS.
ref #1932
> SAM/CFN JSON schema: use URIs instead of plain strings

- .changes/next-release/Bug Fix-92436df0-2443-4376-bfbf-3ae02abbd504.json
- src/shared/cloudformation/cloudformation.ts
Whenever the schemas need to be downloaded (i.e. first-time load or an update) they are currently being written to disk with a writestream. Normally not a big deal, however, the YAML extension may try to load the partial schema, requiring a reload to fix things.
Write to disk after retrieving the full contents in memory (only for schemas, write streams are normally a good thing)
> SAM/CFN JSON schema: write downloaded schema from memory

- src/stepFunctions/commands/publishStateMachine.ts
- src/stepFunctions/explorer/stepFunctionsNodes.ts
#993 After creation of new state machine user needs to refresh the explorer manually to see it. 
I store references to State Machine nodes in a regionalized map so that I can refresh them from outside of the tree structure through `refreshStepFucntionsTree` function.
After creating state machine I call `refreshStepFunctionsTree` function to refresh the state machines for given region in the AWS Explorer. 
> Refreshes Step Functions tree after creation

- src/awsexplorer/activation.ts
- src/credentials/loginManager.ts
The `recordVscodeActiveRegions` telemetry was sending before the explorer was created during startup.  This caused the value for the metric to read 0, which was incorrect.
Moved the telemetry call to a different step in the login process and now uses the number of regions that were stored in the globalState which does not need the explorer.
> telemetry: Send the correct value for active regions

- src/credentials/providers/sharedCredentialsProvider.ts
Migrating to SDK v3 introduced a regression where credentials were not updated as the credentials file changed. This was because the new 'patching' logic assumed the profile data within the provider was accurate (it was not).
We should look towards some simple integration tests for credentials. This would also allow 'safer' updates to the system in the future.
Let the SDK parse the file when `source_profile` is not being used, exerting the original behavior.
Note that the original behavior is likely an 'accident' and highly unintuitive. The provider class contains information about the shared-ini files that is no longer in-sync with what the SDK will read. But since it does have the desired effect I suppose it falls into 'it's not a bug, it's a feature'
By submitting this pull request, I …
> credentials: use SDK to parse credentials if not using 'source_profile'

- package-lock.json
- package.json
- src/credentials/loginManager.ts
- src/test/shared/credentials/loginManager.test.ts
'set credentials' isn't a very useful metric and also does not belong in the login manager file. The `login` method is doing a bunch of validating and throws when it fails. So having the metric refer to 'validation' makes more sense.
> telemetry: use 'validate credentials' instead of 'set' to capture more information

- .changes/next-release/Bug Fix-2d168a17-4543-410f-95d4-7f8d6f935342.json
- src/shared/sam/cli/samCliLocalInvoke.ts
- src/shared/sam/cli/samCliStartApi.ts
- src/shared/sam/debugger/awsSamDebugConfiguration.ts
- src/shared/sam/debugger/awsSamDebugger.ts
- src/shared/sam/localLambdaRunner.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
Toolkit would send the environment variables option and override any settings defined in a SAM config file.
Do not send the option if no variables are defined. 
**Caveat:** users cannot use relative paths in their SAM config file. They will need to in-line the environment variables OR use an absolute path
> SAM: skip '--env-vars' option when no environment variables are present

- src/lambda/vue/samInvokeVue.ts
Bug reported via Quick Feedback
> Query String textbox turned empty when I click Save Debug Config or Invoke Debug Config
Bind the field to the data
> SAM invoke webview: sync query string fields

- build-scripts/generateServiceClient.ts
When running `npm install`, the `generateServiceClient.ts` script always re-clones the entire AWS JS SDK to a new temporary directory.
- Use a stable temp dir and use `git fetch` + `git checkout` if the repo was already cloned to it.
- Saves 10 seconds in the common case. 
- See commit message for details.
> build/generateServiceClient: avoid re-cloning the SDK

- .changes/next-release/Bug Fix-fad1ddc6-c92c-45a5-aecb-9091a9d67f52.json
- src/shared/wizards/stateController.ts
- src/test/lambda/wizards/stateController.test.ts
When closing out of a dialog (e.g to select a file), the prompt is 'retried' by the wizard controller. There is a logic bug in the state machine where it instead uses the _last_ state rather than maintaining the current state. This is probably an artifact from previous iterations. The bug was never caught since `WIZARD_RETRY` is only used a single time in the wizard flow under specific circumstances. 
Fix bug and add test to prevent regressions.
> UI: fix edge case when retrying a prompt

- .changes/next-release/Feature-21fa11e4-498b-4279-b201-209aad3594d1.json
- src/credentials/providers/sharedCredentialsProvider.ts
- src/credentials/providers/ssoCredentialProvider.ts
- src/credentials/sso/ssoAccessTokenProvider.ts
SSO profiles do not reconnect automatically on start up, even
if the token is still valid.
If the most recent credentials were a SSO profile, check if
the token is still valid. Continue login if it is, but do not attempt to
refresh if the token is no longer valid.
> credentials: Reconnect to SSO profile

- .git-blame-ignore-revs
- CONTRIBUTING.md
`git blame` can be polluted by style-only commits e.g. e003b28a7cef217b809d7dc2e54f38f15d1b3920
- Add a `.git-blame-ignore-revs`.
- This is the current quasi-conventional name AFAICT.
- Currently not possible for git to automatically find this file. Each developer needs to do this one-time step:
- `git config blame.ignoreRevsFile .git-blame-ignore-revs`
> docs: .git-blame-ignore-revs

- src/lambda/commands/createNewSamApp.ts
Cloud9 opens the toolkit readme as a text file instead of a Markdown preview
Open it as a markdown preview
> "Create Lambda SAM App": enable markdown view in Cloud9

- .changes/next-release/Bug Fix-de3aab83-3133-475f-b60c-27dba54b6248.json
- src/credentials/credentialsUtilities.ts
- src/integrationTest/integrationTestsUtilities.ts
- src/integrationTest/sam.test.ts
- src/shared/sam/cli/samCliBuild.ts
- src/shared/sam/localLambdaRunner.ts
- src/shared/utilities/timeoutUtils.ts
Timeout was never wired through
Add it
`Timeout` should be an argument of the `ChildProcess` class as a whole, but that requires a good chunk of refactoring.
> SAM: wire timeout into build step

- src/test/shared/logger/winstonToolkitLogger.test.ts
Problem
-------
Sometimes `winstonToolkitLogger.test.ts` fails like this:
"after all" hook for "throws when logging to a disposed object":
Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\RUNNER~1\AppData\Local\Temp\aws-toolkit-vscode\vsctkXgBlt7'
Solution
--------
Make the delete a best-effort attempt. On CI it doesn't matter if the
temp dir remains. On a local Windows desktop, the temp dir should be
cleaned up by the OS (sooner or later).
> test: do not fail if temp dir cleanup fails

- package.json
- package.nls.json
- src/apprunner/wizards/deploymentButton.ts
- src/shared/sam/activation.ts
- src/shared/settingsConfiguration.ts
- src/test/shared/settingsConfiguration.test.ts
- src/test/templates/sam/samTemplateGenerator.test.ts
followup to #1937
- Validate the promptName by inspecting package.json.
- Rename subitems to "apprunnerNotifyPricing", "yamlExtPrompt". Don't
need "suppress" in the names, it is redundant and looks strange in the
UI.
> settings: validate suppressPrompts calls, rename

- src/credentials/awsCredentialsStatusBarItem.ts
- src/extension.ts
- src/shared/awsContext.ts
- src/shared/defaultAwsContext.ts
- src/shared/extensionUtilities.ts
- src/shared/logger/logger.ts
- src/shared/settingsConfiguration.ts
- src/shared/vscode/env.ts
- src/test/utilities/fakeAwsContext.ts
- src/test/utilities/testSettingsConfiguration.ts
- Add some structure to support temporary settings whose values should not be  committed.
- Start reworking the SettingsConfiguration class.
- Change the AWS statusbar when a developer setting is active:
- <img width="309" alt="Screen Shot 2021-09-15 at 6 20 26 PM" src="https://user-images.githubusercontent.com/55561878/133534234-170fdafc-a221-4147-b0c8-4b2a77f8265f.png">
> settings: support developer-only settings

- src/shared/clients/ec2MetadataClient.ts
- src/test/credentials/provider/ec2CredentialsProvider.test.ts
- src/test/shared/extensionUtilities.test.ts
Problem:
Control continues even after reject()/resolve().
https://stackoverflow.com/a/32536083/152142
So Ec2MetadataClient.invoke() tried to parse nonsense even after `err`
was received.
Solution:
- add `return` to Ec2MetadataClient.invoke()
- defensive: also try/catch JSON.parse()
> ec2MetadataClient: handle broken endpoint, bad response

- .changes/next-release/Bug Fix-1939a4d6-c76f-48c6-84f1-d4955dd4490a.json
- .changes/next-release/Bug Fix-f2997a0c-7d2a-4074-9ad7-e377cc1dcdb9.json
- .changes/next-release/Feature-d7430e98-ef86-49bb-a792-69a0abadacf5.json
- src/shared/sam/debugger/typescriptSamDebug.ts
- src/shared/sam/localLambdaRunner.ts
- src/shared/systemUtilities.ts
- src/test/shared/systemUtilities.test.ts
- src/test/testUtil.ts
1. Toolkit checks for "tsc" for plain javascript Lambdas.
2. Toolkit only checks global $PATH for "tsc". #1487
3. If the source project dir containing the Lambda being run/debugged   has a hyphen (or other special chars), our `compileTypeScript()`   codepath will fail because `sam build` uses a "scrubbed" name in the temporary build output dir.
1. Skip "tsc" check if tsconfig.json or `*.ts` is not found in the top-level of the app dir.
2. Also look for "tsc" in the workspace node_modules/ dir.
3. Change the logic in `compileTypeScript()` to look for "output/*/tsconfig.json"   instead of using `config.invokeTarget.projectRoot`.
- Alternatives considered:
1. add a property to samCliBuild.ts.
- problem: needs to inspect the CodeUri or use a similar findFiles() approach.
2. in …
> SAM/typescript: skip "tsc" for plain JS; fix if source dir has special chars

- src/integrationTest/sam.test.ts
Problem:
If startDebugging() fails, the failure manifests as NRE:
SAM Application Runtime: nodejs12.x/typescript (ZIP)
Starting with a newly created nodejs12.x/typescript (ZIP) SAM Application...
target=api: invokes and attaches on debug request (F5):
TypeError: Cannot read property 'name' of undefined
at /codebuild/output/src408332906/src/github.com/aws/aws-toolkit-vscode/src/integrationTest/sam.test.ts:325:66
Solution:
Detect failed startDebugging(). Don't deref undefined global.
> test(integ): detect failed startDebugging()

- src/shared/sam/localLambdaRunner.ts
We were forcing skip pulls for all cases to fix issues with CI, but this meant we didn't respect the user's config. This change now respects the config, and is optimized for skipping the image check if this is a container build or an image, as we would've already build the image. This should keep the performance benefits for the Image/container build cases without causing weird caching issues.
> SAM run/debug: `skipPullImage` optimize/fix

- src/apigateway/explorer/apiGatewayNodes.ts
- src/apprunner/explorer/apprunnerNode.ts
- src/awsexplorer/awsExplorer.ts
- src/awsexplorer/childNodeCache.ts
- src/awsexplorer/childNodeLoader.ts
- src/cloudWatchLogs/explorer/cloudWatchLogsNode.ts
- src/ecr/explorer/ecrNode.ts
- src/ecr/explorer/ecrRepositoryNode.ts
- src/eventSchemas/explorer/registryItemNode.ts
- src/eventSchemas/explorer/schemasNode.ts
- src/lambda/explorer/cloudFormationNodes.ts
- src/lambda/explorer/lambdaNodes.ts
- src/s3/explorer/s3BucketNode.ts
- src/s3/explorer/s3FolderNode.ts
- src/shared/treeview/treeNodeUtilities.ts
- src/ssmDocument/explorer/documentTypeNode.ts
- src/ssmDocument/explorer/registryItemNode.ts
- src/ssmDocument/explorer/ssmDocumentNode.ts
- src/stepFunctions/explorer/stepFunctionsNodes.ts
They did not use generics despite being pretty generic constructs. This meant callers had to use hard casts (or explicit annotations) to get their code to appear well-typed. Now the types are correctly inferred.
> types: fix `makeChildrenNodes` and `childNodeLoader` types

- src/lambda/vue/samInvokeBackend.ts
- src/lambda/vue/samInvokeFrontend.ts
Webview now correctly saves state for everything. Fixes 'Load config' not working after context change as well.
There also appears to be (undocumented) debugging logic littered in the code and Vue template in a rather unconventional way.
This should be removed at a later date since it could be confusing to other devs.
> SAM run/debug: webview state fixes

- src/shared/sam/debugger/awsSamDebugger.ts
We do this for the "temp dir" case so also do it for the explicit `buildDir` case.
fix #2120
ref #2061
> SAM run/debug: auto-create buildDir

- .changes/next-release/Feature-d7eee614-868c-4ab6-8cf0-536a49da047b.json
- package.json
- src/stepFunctions/explorer/stepFunctionsNodes.ts
#2073 - Added an option to create state machine from template.
I keep the name consistent with the name of the command in the palette. 
> Step Functions: adds ability to create from explorer

- .changes/next-release/Bug Fix-e3752045-17ab-4620-ae97-438c00d24bae.json
- src/dynamicResources/activation.ts
- src/dynamicResources/awsResourceManager.ts
We close the active editor at the conclusion of several actions including resource save, create, and close of the editor mode. This is desired behavior. However we also unnecessarily close the editor when a document close event occurs. In Cloud9 this results in unnecessary flickering as the closed document is briefly visible before being re-closed.
Add a flag to indicate the editor is already closed and only perform cleanup actions.
> cloudControl: avoid redundant editor closing

- src/shared/sam/localLambdaRunner.ts
After aws/aws-toolkit-vscode#2263,
- even valid paths are rejected too quickly (no pause between retries).
- 403 is being handled by `got` in unexpected ways, e.g. it doesn't respect the retry limit?
> Revert "SAM run/debug: do not stringify the error from got"

- src/shared/sam/localLambdaRunner.ts
Changed the logic to explicitly check for `attemptCount` and 403 error code
Supposedly `got` is only supposed to retry on the codes I've specified, but that doesn't appear to be the case.  `limit` was also being ignored, causing some confusion on what needed to be checked on retry. 
> SAM run/debug: target=api, proper fix for 'got' issue

- .vscode/launch.json
- .vscode/tasks.json
- docs/ARCHITECTURE.md
- media/css/base.css
- package-lock.json
- package.json
- src/lambda/vue/entry.ts
- src/lambda/vue/samInvokeBackend.ts
- src/lambda/vue/samInvokeFrontend.ts
- src/webviews/client.ts
- src/webviews/components/settingsPanel.vue
- src/webviews/main.ts
- src/webviews/mixins/saveData.ts
- src/webviews/server.ts
- src/webviews/util.ts
- webpack.config.js
Adds framework code to develop robust (and type-safe!) webviews. Also adds support for `WebviewView`, though they are not currently used.
Main goals:
* Establish style conventions through common code
* Increase modularity by abstracting away the `window`/`message` event-based communication protocol
* Increase developer productivity with faster iteration loops (hot-module reloads) and 'failing quickly' (types are easier to add/maintain)
* Ensure consistency of state retention through mixins (see `src/webviews/saveData.ts`)
* Open an avenue for common testing constructs via uniform entry points.
See `docs/ARCHITECTURE.md` for an overview plus some small examples of usage.
> Webviews: add framework code

- src/webviews/main.ts
- src/webviews/server.ts
`WebviewView` is handled slightly differently in that the underlying panel is not completely disposed off when collapsing the pane.
Dispose of the listeners when the webview is reloaded or when the view is disposed.
> Webviews: clean-up listeners for the WebviewView case

- docs/CODE_GUIDELINES.md
- src/shared/resourcefetcher/compositeResourceFetcher.ts
- src/shared/resourcefetcher/fileResourceFetcher.ts
- src/shared/resourcefetcher/httpResourceFetcher.ts
- src/shared/schemas.ts
- src/webviews/server.ts
Fetchers log the error as an error and then return undefined. If something can be handled by just returning undefined then it definitely wasn't an error we really cared about. Also, we should refrain from just dumping the whole stack trace every time an error occurs. It better be an error that truly was unhandled to dump the stack. Especially since the names are mangled in the bundled extension, so it's pretty much useless in production too.
> Logs: remove/change some noisy logging code

- src/ecs/commands/runCommandInContainer.ts
- src/shared/utilities/cliUtils.ts
- src/test/ecs/commands/runCommandInContainer.test.ts
The SSM Plugin is required for ECS Exec.
Implement auto installation utility before it is used.
> ECS: add auto install of SSM plugin

- src/shared/resourcefetcher/httpResourceFetcher.ts
- src/shared/sam/cli/samCliInvoker.ts
- src/shared/sam/cli/samCliInvokerUtils.ts
- src/shared/sam/cli/samCliLocalInvoke.ts
- src/shared/sam/debugger/csharpSamDebug.ts
- src/shared/sam/debugger/goSamDebug.ts
- src/shared/sam/debugger/typescriptSamDebug.ts
- src/shared/sam/localLambdaRunner.ts
- src/shared/systemUtilities.ts
- src/shared/utilities/childProcess.ts
- src/shared/utilities/timeoutUtils.ts
- src/test/lambda/local/debugConfiguration.test.ts
- src/test/shared/utilities/childProcess.test.ts
The current `ChildProcess` is pretty rigid and doesn't offer a lot of customization despite being used in many modules. It also requires both the command and its arguments up-front rather than waiting until it is ran. This doesn't help much for composition, though it does make the object well-behaved when looking at it in isolation.
Re-arrange the constructor arguments for ergonomics. Also make `args` not a rest parameter. Usually if you have optional parameters you don't want a rest parameter as well. Removed the old `run` since all it did was just wrap `start` in a Promise. `run` can now merge in with the base options, allowing for some amount of information hiding that previously was not possible.
Also the process is now killed by default on an error in one of:
1. the process stream
2. …
> utils: refactor `ChildProcess` to support more things

- src/iot/commands/editPolicyVersion.ts
- src/test/iot/commands/editPolicyVersion.test.ts
Existing implementation threw `methodNotSupported` exceptions upon performing an edit on a newly created `TextDocument`.
Create the `TextDocument` with the desired content directly.
> IoT: fix policy editing bug with C9

- package.json
- src/iot/commands/createCert.ts
- src/iot/commands/createPolicy.ts
- src/iot/commands/createThing.ts
- src/test/iot/commands/createCert.test.ts
- src/test/iot/commands/createPolicy.test.ts
- src/test/iot/commands/createThing.test.ts
* The Policies folder node does not have an `+` to create a policy as the Things and Certificates folders do.
* The user is unnecessarily prompted for confirmation when creating a certificate, and then again when selecting a download location.
* There is no input validation for Thing or Policy names.
> Fix major issues from bug bash

- package.nls.json
- src/awsexplorer/activation.ts
- src/credentials/activation.ts
- src/credentials/loginManager.ts
- src/shared/awsContext.ts
1. For new users (or systems, e.g. a new Cloud9 env) autoconnect is
skipped if there are multiple profiles.
2. If autoconnect is skipped, AWS Explorer shows "Connecting..." even
though it is not doing anything.
1. On new systems with multiple profiles, try the "default" profile.
2. Set the Explorer text to "Connect to AWS..." if autoconnect fails.
- Tested with
1. zero profiles,
2. exactly one but no "default",
3. exactly one "default",
4. multiple including "default",
5. multiple but no "default".
- TODO: will add tests for the autoconnect codepaths after migrating to SDK v3.
> fix(login): stuck at "Connecting..."

- .changes/next-release/Bug Fix-d9deac78-e348-4692-b769-23a939fd68b1.json
- src/cdk/explorer/detectCdkProjects.ts
- src/test/cdk/detectCdkProjects.test.ts
Use `vscode.workspace.findFiles` instead of iterating over files.
`detectCdkProjects` went from taking >2000ms to ~50ms on my machine with the Toolkit repository as a fixture.
Oh also the tests for `detectCdkProjects` are an example of _good_ tests (thanks @awschristou !). I was able to change the implementation details without needing to update the tests.
Fixes: #2312
> CDK: make CDK project detection over 20x faster

- README.quickstart.cloud9.md
- README.quickstart.vscode.md
- IoT Explorer does not have an entry in the quickstart guide.
- Add quickstart entry for IoT Explorer
> Add IoT Explorer to quickstart

- .changes/next-release/Bug Fix-24b2dcff-9177-4c02-8d75-803abbe08262.json
- .changes/next-release/Bug Fix-7427c4fd-dc23-4334-8da1-a18a69290772.json
- src/credentials/activation.ts
- src/credentials/loginManager.ts
- src/shared/utilities/timeoutUtils.ts
Followup to #2315
Useful for Cloud9 and other ECS-like envs. Example:
2021-11-18 17:51:08 [INFO]: autoconnect: trying "profile:default"
2021-11-18 17:51:09 [WARN]: autoconnect: failed to connect: 'profile:default'
2021-11-18 17:51:09 [INFO]: autoconnect: trying "profile:sso-test"
2021-11-18 17:51:09 [INFO]: autoconnect: trying "profile:foo-dev"
2021-11-18 17:51:10 [INFO]: autoconnect: connected: 'profile:foo-dev'
> feat(autoconnect): try up to 3 non-default profiles

- .changes/next-release/Bug Fix-9305895c-8be2-411d-a84b-086b78787f69.json
- src/s3/activation.ts
- src/s3/commands/uploadFileToParent.ts
Fixes issue where 'Upload to Parent...'  does not work.
Using `executeCommand` on commands we register is fragile and should be avoided in general. We lose out on type safety for little benefit. If we _must_ use the commands API then creating interfaces with stricter types is preferred. 
> S3: fix `uploadFileToParent`

- .changes/next-release/Bug Fix-5b2f31be-37c7-4566-a0e4-3fdbb47fab79.json
- src/shared/schemas.ts
We were not catching errors that can occur from updating the settings configuration.
TODO:
Update `SettingsConfiguration` to not be scoped down to only our own settings. We should be using these classes with error handling built-in by default whenever we want side-effects (like messing with settings)
> Schemas: catch errors for invalid settings configurations

- .changes/next-release/Feature-b93e984e-1c2d-4b78-aafe-2e3264c95f45.json
- package.json
- src/iot/commands/attachPolicy.ts
- src/iot/commands/createPolicy.ts
- src/iot/commands/createPolicyVersion.ts
- src/iot/commands/detachPolicy.ts
- src/iot/commands/setDefaultPolicy.ts
- src/iot/explorer/iotCertFolderNode.ts
- src/iot/explorer/iotCertificateNode.ts
- src/iot/explorer/iotPolicyFolderNode.ts
- src/iot/explorer/iotPolicyNode.ts
- src/iot/explorer/iotPolicyVersionNode.ts
- src/test/iot/commands/attachPolicy.test.ts
- src/test/iot/commands/createPolicy.test.ts
- src/test/iot/commands/createPolicyVersion.test.ts
- src/test/iot/commands/detachPolicy.test.ts
- src/test/iot/commands/setDefaultPolicy.test.ts
- src/test/iot/explorer/iotCertFolderNode.test.ts
- src/test/iot/explorer/iotCertificateNode.test.ts
- src/test/iot/explorer/iotPolicyFolderNode.test.ts
- src/test/iot/explorer/iotPolicyNode.test.ts
This addresses some concerns and suggestions from the bug bash prior to the release of the IoT explorer:
* Policies attached to certs are not visible in the **Things** subtree, making it hard to see the policies applied to a Thing.
* In the **Certificates** subtree, the user is unable to see to what Things a certificate is attached until the user tries to delete the cert. Same for policies in the **Policies** subtree.
* The policy document would be easier to view if it appeared when clicking the node, instead of having to right click and select it from the context menu.
Additionally, the following changes and cleanups were made:
* Sort the policy version nodes to allow using the available `.refresh()` on the parent node instead of having to define a new refresh command that clears its …
> Add IoT improvements

- CONTRIBUTING.md
- build-scripts/package.ts
- src/shared/constants.ts
- src/shared/telemetry/defaultTelemetryClient.ts
- src/shared/vscode/env.ts
ref #2361
Some test builds are shared with beta testers where telemetry is wanted.
Introduce `constants.forceTelemetry`.
> telemetry: prerelease build can optionally send metrics

- src/shared/clients/ecsClient.ts
#2362 
While listing service arns from a cluster can result in up to
100 service arns, only 10 can be described per SDK call.
Set the max requests per list and describe call to 10. Each
page of results will now show up to 10 Clusters/Services.
> ECS: bug: only 10 services can described per call

- src/apprunner/wizards/codeRepositoryWizard.ts
- src/integrationTest/shared/extensions/git.test.ts
- src/shared/extensions/git.ts
We don't want to activate another extension until we need to use it, but we also want to ensure that a method works without having to make a separate call.
Check activation promise for every call. Decorators would help reduce boilerplate here if we reuse this pattern elsewhere.
Also just renamed things for consistency.
> extensions: lazily activate git

- src/shared/clients/lambdaClient.ts
Lambda now uses Lambda States to determine whether or not create/update calls are successful. Most of our operations are run through SAM/CFN but we do need to respect the state for direct code updates.
> Lambda updates wait for Lambda State updates

- src/shared/extensionGlobals.ts
- src/shared/logger/index.ts
- src/shared/logger/loggableType.ts
- src/shared/settingsConfiguration.ts
- src/shared/telemetry/defaultTelemetryClient.ts
- src/shared/telemetry/defaultTelemetryPublisher.ts
- src/shared/telemetry/defaultTelemetryService.ts
- src/shared/telemetry/telemetryLogger.ts
- src/shared/telemetry/telemetryService.ts
- src/test/globalSetup.test.ts
- src/test/shared/credentials/loginManager.test.ts
- src/test/shared/settingsConfiguration.test.ts
- src/test/shared/telemetry/defaultTelemetryPublisher.test.ts
- src/test/shared/telemetry/defaultTelemetryService.test.ts
- src/test/testUtil.ts
Developers cannot easily test telemetry metrics emitted during test execution.
Add 'logger' to keep track of recorded metrics. Lots of rough edges still since our telemetry system maps all metadata to strings...
Though I guess it makes sense to leave it as-is because the logger is storing what will actually be sent to out vs. what the module code sent in. Could also add some temporary logic to intercept metrics prior to being mapped, or perhaps just move the mapping logic.
This PR is just the first half for better telemetry inspection. The next half is hooking up the code to Winston.
In release the logger will just use the current behavior, but in dev it'll output more info.
> Telemetry: add way to test what metrics would be emitted

- src/shared/logger/activation.ts
The deleted log file detection logic seems to be inconsistent, sometimes firing even when the log file was definitely not removed. This is likely due to the `rename` event being fired from more than just file moved/deleted (may be OS specific?).
Just check if the file exists after the event is fired.
> logging: make log file moved notification more consistent

- .changes/next-release/Bug Fix-d771a209-92f1-43fd-b9b7-3585a3112c7b.json
- src/credentials/sharedCredentials.ts
- src/shared/credentials/credentialsFile.ts
- src/test/shared/credentials/userCredentialsUtils.test.ts
Credential field names (e.g. `aws_access_key_id`) should be case-insensitive, but right now we read them as-is.
See #2394
Normalize them when parsing the files.
Also removed dead code in a second commit and started using VS Code's URI + `fs` API. We should prefer URIs and the `fs` API whenever possible as they cover many edge cases we may not otherwise consider (though that doesn't matter much here).
> credentials: normalize field names

- src/test/shared/utilities/childProcess.test.ts
One of the `ChildProcess` test cases sometimes doesn't free the script before exiting (only on Windows?)
Use force stop plus `tryRemoveFolder`
> tests: fix unreliable ChildProcess 'can report errors'

- src/shared/utilities/asyncCollection.ts
- src/shared/utilities/collectionUtils.ts
- src/shared/utilities/tsUtils.ts
- src/test/shared/utilities/asyncCollection.test.ts
- src/test/shared/utilities/collectionUtils.test.ts
To make it easier to handle pagination, I've added a new utility interface called AsyncCollection. This basically allows you to treat async generators/iterables as if they were a static collection. This is great since we can manipulate them in a declarative way; no more while loops to iterate over the elements and check for done. It also helps to abstract away async generators, which most callers don't really care about. You can still iterate over the collection as if it were an AsyncIterable, but again the common-case is we just want all the results. This is provided by a promise method which outputs all results in an array.
Benefits:
* Much better ergonomics and type safety for mapping paginated API calls
* Flexible. The collection does not hide the fact that things come in pages, so it …
> util: AsyncCollection

- src/shared/extensionGlobals.ts
- src/test/globalSetup.test.ts
Extension activation fights with test initialization
Don't fight extension activation. We should start thinking on how to orientate code around this idea.
Addresses #2398
> tests: increase stability

- src/ecs/commands/updateEnableExecuteCommandFlag.ts
* There is no visual indication that the command to enable or disable an ECS service was run.
* The current implementation for refresh after an enable command could potentially not work in Cloud 9.
* Add a notification when a service is enabled or disabled.
* Set the parent cluster node to refresh after a enable or disable command.
> ECS exec: enable/disable notification

- src/awsexplorer/activation.ts
- src/shared/credentials/credentialsFile.ts
- src/shared/systemUtilities.ts
The `workspace.fs` API does not work on C9 (this broke credential parsing)
Use `fs` for C9, otherwise use the API
URIs are better for describing locations of objects compared to plain strings. VS Code's URI class handles things like normalization and validation for us. It also allows us to use `workspace.fs` so we can correctly handle virtual file systems. 
There will be some hiccups with moving towards URIs (like this PR) but it's worth it in the long run.
> utils: check for C9 before using VSC FS API

- src/test/s3/util/fileViewerManager.test.ts
The tests are unreliable on min version
Skip them
I've noticed that in general, tests that utilize more of the real VS Code API are unreliable on our min version. Is this something we should be concerned about? I don't want to skip these tests, but to support them means adding more logic to reduce flakiness. I suppose we could also use Mocha's `retry` only for min ver?
We should discuss this more in our testing strategy for C9.
> tests: skip S3 editor tests on minimum

- src/ecs/wizards/executeCommand.ts
It's not clear to users that valid tasks are starting but aren't ready yet.
Show it within the UI:
Doesn't handle niche edge-cases (like tasks with agents that are stopping)
These are just shown as invalid and sorted to the bottom for all cases.
> ECS: show valid tasks that are starting

- docs/ARCHITECTURE.md
Abstractions are hard to use without documentation and/or examples. Many of the interfaces are documented, though these comments do not capture the 'big idea'.
Add more docs. We need more examples within the codebase as well since the docs will never capture all the possible uses. 
Docs added:
* Prompter
* Wizard
Do we need/want a section explicitly for `AsyncCollection`? Could take whatever documentation there is for our clients and combine that into its own thing: `Working with the AWS SDK`
> docs: add more 'high-level' documentation for UI abstractions

- src/integrationTest/sam.test.ts
- src/integrationTest/stepFunctions/visualizeStateMachine.test.ts
- src/shared/utilities/vsCodeUtils.ts
- src/shared/vscode/env.ts
- src/test/s3/util/fileViewerManager.test.ts
- src/test/testUtil.ts
S3 editor tests still not reliable
Attempt 2 at improving stability by waiting for specific contents rather than _any_ active text editor. 
The pattern of waiting for certain things to happen will become increasing common as we use more of the real VS Code API. This is just because we're dealing with of a lot of asynchronous things that otherwise have no explicit sequence of events. Luckily I think it's mostly a 'one-and-done' type of deal; once we figure out the nuances with each API, the test code can be re-used elsewhere.
I'll be making some dummy commits against this PR over the day to see if this change truly made things more stable.
Once VS Code has a better API for managing tabs, this code can be made so much more reliable. It's just right now there's very little way to inspect …
> tests: wait for active S3 editor to have matching contents

- src/shared/codelens/codeLensUtils.ts
We're throwing an uncaught error if trying to provide codelenses to files outside the workspace folder.
Error log and return a blank array instead of throwing
> Codelens providers do not throw errors if source file is not in workspace folder

- src/ecs/activation.ts
- src/ecs/commands/runCommandInContainer.ts
If a command on a node is executed before the node has
completely loaded, it will error.
Verify the node exists and is typed before attempting to
execute the command.
> ECS: bug fix, verify node before run command

- .changes/next-release/Feature-8fa21b2e-2510-4d9e-b5ab-8a6b331c7b4b.json
- package.nls.json
- src/ecs/explorer/ecsContainerNode.ts
- src/ecs/explorer/ecsServiceNode.ts
- src/shared/clients/ecsClient.ts
- src/test/shared/clients/mockClients.ts
Containers may have no running tasks but still allow for a user
to start the 'Run Command' wizard.
Show in the explorer when a container has no running tasks.
> ECS: show when container node has no running tasks

- buildspec/linuxIntegrationTests.yml
- src/integrationTest/sam.test.ts
fix #2486
python3.6/3.7 aren't in `/usr` :
```
[Container] 2022/02/24 23:32:04 Running command find /usr -name 'python*' | grep 'python3..$'
/usr/include/x86_64-linux-gnu/python3.8
/usr/include/python3.8
/usr/bin/python3.8
/usr/lib/python3.8
/usr/lib/python3.9
/usr/local/lib/python3.8
/usr/local/aws-cli/v2/2.2.44/dist/include/python3.8
/usr/local/aws-cli/v2/2.2.44/dist/lib/python3.8
/usr/share/doc/python3.8
/usr/share/lintian/overrides/python3.8
/usr/share/binfmts/python3.8
```
Just for reference, `sam` in $PATH looks fine.
```
[Container] 2022/02/25 00:05:39 Running command pip3 show aws-sam-cli
Name: aws-sam-cli
Version: 1.40.0
Location: /root/.pyenv/versions/3.9.5/lib/python3.9/site-packages
...
[Container] 2022/02/25 00:05:50 Running command /root/.pyenv/shims/sam --version
SAM CLI, …
```
> fix(ci): install python3.6, python3.7

- src/webviews/main.ts
Cloud9 doesn't re-apply webview panel options when the HTML changes.
Add redundancy by setting some invariants when we create the view.
> webviews: fix loading on Cloud9

- .changes/next-release/Feature-71234bfa-7e72-404f-801b-f5f831741eb7.json
- README.quickstart.vscode.md
- src/lambda/models/samLambdaRuntime.ts
- src/test/lambda/models/samLambdaRuntime.test.ts
SAM CLI  1.40 supports dotnet6 (.NET 6), but Toolkit does not.
Enable dotnet6 in Toolkit.
- manual testing:
- created dotnet6 "image" app using "Create new SAM Lambda app" command
- codelens appears on function in src/HelloWorld/Function.cs
- initiated debugging, sam pulled docker image `mcr.microsoft.com/dotnet/sdk:6.0`
- lambda ran in docker container, debugger hit breakpoint
- created dotnet6 "zip" (managed) app using "Create new SAM Lambda app" command
- codelens appears on function in src/HelloWorld/Function.cs
- initiated debugging, sam pulled docker image `public.ecr.aws/sam/emulation-dotnet6:rapid-1.40.0-x86_64`
- lambda ran in docker container
- debugger hit breakpoint, can step through code, inspect variables.
By submitting this pull request, I confirm that my contribution is …
> feat(lambda,sam): add support for dotnet6 (.NET 6)

- src/shared/sam/debugger/pythonSamDebug.ts
Lambda will publish a new image that has an alias from
/var/runtime/awslambda/bootstrap.py => /var/runtime/bootstrap.py
The Toolkit must choose one or the other. Many customers have images
with the old path. So to minimize error, we continue using the old path
(which will work with the Lambda image having the alias).
> fix(sam/debug): revert Python 3.6 bootstrap location

- .changes/next-release/Feature-a4cd1f7e-d66e-4b21-9a59-a948615b600a.json
- package.json
- src/dynamicResources/explorer/nodes/resourcesNode.ts
- src/lambda/commands/createNewSamApp.ts
In Cloud9, user cannot choose which Resources to show/hide.
> feat(resources): enable multiselect in Cloud9

- .changes/next-release/Feature-489f795c-9a8f-4055-92d6-51c561ae58a9.json
- src/eventSchemas/models/schemaCodeLangs.ts
- src/test/eventSchemas/model/schemaCodeLangs.test.ts
- src/test/lambda/models/samTemplates.test.ts
EventBridge Schemas now supports Golang as a language to generate code bindings with. VSCode Toolkit currently supports Java, Python, and Typescript for Schemas code generating and generating SAM EventBridge applications.
Added Golang (go1.x) to the list of supported languages for schemas code generation and EventBridge templates for SAM. 
Pull Requests Open: 
For EventBridge SAM templates: https://github.com/aws/aws-sam-cli-app-templates/pull/183
For SAM CLI: https://github.com/aws/aws-sam-cli/pull/3657
> feat(schemas,sam): Add Golang to EventBridge Schemas

- src/shared/awsClientBuilder.ts
- src/test/shared/defaultAwsClientBuilder.test.ts
We can't easily add request listeners to service clients in a cross-cutting fashion
Add option for request listeners. Kept light for simplicity, though it would be wise to build simple interfaces against `Request` as to not couple too much with v2 of the SDK.
Example:
```ts
const service = await builder.createAwsService(FooService, {
requestListeners: [
request => request.on('error', e => console.log(e)),
],
})
```
Note that when request events are fired is highly dependent on the SDK. Any implementations should keep this in mind. For example, 'error' may fire more than once for a single request.
> util/services: support service request listeners

- src/shared/resourcefetcher/httpResourceFetcher.ts
Default `got` does not work on Cloud9, even after upgrading
Always use the 'patched' version. Previously, there was a hard-coded version to toggle usage of the 'patched' version. The assumption was that the issue was specific to the VS Code version (not Cloud9), but clearly that's not the case.
> HttpResourceFetcher: always use patched `got` for Cloud9

- .changes/next-release/Bug Fix-983cd27f-6bfe-449d-9fbe-a78776800a8b.json
- src/shared/sam/localLambdaRunner.ts
Hard-coded retry limit means the debugger can fail to attach if SAM CLI takes too long to start.
See: https://github.com/aws/aws-toolkit-vscode/issues/2446#issuecomment-1023484906
Retry indefinitely until the user cancels. The amount of additional logic was kept very minimal, so the UX as far as error reporting goes is still not great.
Tested manually. A good way to simulate slower machines is to add a sleep in `DefaultSamLocalInvokeCommand` right before the process is ran.
> SAM run/debug: remove strict retry limit for "local API" debugger attachment

- package.nls.json
- src/shared/extensionUtilities.ts
In ephemeral environments such as Cloud9, the welcome message is
redundant.
Don't show the message on Cloud9.
> fix(cloud9): don't show welcome message

- src/dynamicResources/commands/openResource.ts
- src/dynamicResources/explorer/nodes/resourceTypeNode.ts
- src/iot/explorer/iotPolicyFolderNode.ts
- src/lambda/commands/downloadLambda.ts
- src/shared/ui/common/variablesPrompter.ts
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated.
We replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> refactor: replace deprecated String.prototype.substr()

- .changes/next-release/Bug Fix-d243fc5e-2336-4c1a-91da-385d56ba923d.json
- src/apigateway/vue/invokeApi.vue
Resource names in the 'Invoke on AWS' webview would always show as 'resource.path'
Put the reference in the template string.
> fix(api-gateway): correct issue with resource names in webview

- src/integrationTest/sam.test.ts
- src/integrationTest/shared/codelens/samTemplateCodeLensProvider.test.ts
- src/shared/telemetry/defaultTelemetryClient.ts
- checking isReleaseVersion() is no longer needed because we just `!isAutomation()`. ref #2528
- **Solution:** remove the check
- Language-specific, third-party extensions may not support older versions of vscode, then the integ tests start failing.
- https://github.com/golang/vscode-go/blob/089cf1321315bd169468611957269564831f4970/package.json#L92
- https://github.com/redhat-developer/vscode-yaml/blob/c09167284842953506b462efd2ed6396bd18216b/package.json#L27
- **Solution:** Skip integ tests if the vscode version does not meet the version required by the third-party extension.
should probably store the version in this structure: https://github.com/aws/aws-toolkit-vscode/blob/a33b236db904132785f0e01acc48a155af0b0402/src/shared/extensions.ts#L14-L24
By submitting this pull request, I …
> fix(telemetry): remove redundant check

- .changes/next-release/Feature-e0e893f6-8b9e-4753-93e3-96998ec5bf23.json
- package.json
- package.nls.json
- src/extension.ts
Feedback suggests that customers have trouble finding Toolkit commands, or aren't accustomed to using the VSCode command palette.
Add a command that lists all Toolkit commands, and put it at the top of the main AWS Explorer menu.
> feat(explorer): "Show AWS Commands"

- src/shared/codelens/codeLensUtils.ts
- src/shared/codelens/csharpCodeLensProvider.ts
- src/shared/codelens/goCodeLensProvider.ts
- src/shared/codelens/javaCodeLensProvider.ts
- src/shared/codelens/pythonCodeLensProvider.ts
- src/shared/codelens/typescriptCodeLensProvider.ts
- src/shared/lambdaHandlerSearch.ts
#2564
Codelenses (for in code potential lambda handlers) only appear for files with an associated manifest
file. Lambdas that are downloaded will not have template.yaml file or a
manifest file and therefore no codelens appears, but can still be invoked locally.
The manifest file was mainly used to find the project root. In
the absence of such file, use the source file as the project root.
> Codelens: show without manifest file

- .changes/next-release/Bug Fix-dde17524-db50-4ba9-864a-c33514f35c82.json
- package.json
- src/s3/fileViewerManager.ts
- src/test/s3/util/fileViewerManager.test.ts
- src/test/testUtil.ts
Users would see an error such as `aws.s3.editFile:[UriError]: Scheme contains illegal characters.` when opening a file with a reserved URI character (e.g. `:`)
See #2581
Do not use `path`. Just assign the path directly to the URI. This removed the `[S3]` prefix which is unfortunate but it was getting encoded weirdly.
> fix(s3): handle file paths with reserved characters

- src/lambda/commands/uploadLambda.ts
- src/shared/ui/common/openDialog.ts
Legacy code is hard to change/improve because it's tightly coupled to UI.
Split up control flow from UI, then tighten the interfaces to make it obvious what the code truly depends on.
> refactor(lambda): use wizard code for `uploadLambdaCommand`

- .changes/next-release/Feature-8a4d8884-b775-4e24-9077-58cc5b1cb841.json
- src/credentials/credentialsStore.ts
- src/credentials/credentialsUtilities.ts
- src/credentials/loginManager.ts
- src/shared/sam/debugger/awsSamDebugger.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
todo
- #1715 
When running/debugging a local Lambda, Toolkit does not use the current active credentials. This is inconsistent with other actions (e.g `aws.deploySamApplication`) and other Toolkits such as aws-toolkit-jetbrains.
Also the `aws.credentials` launch-config field is not well-known.
If the `aws.credentials` launch-config field is not set, pass the current Toolkit credentials to `sam local invoke` as environment variables.
Motivation for the `aws.credentials` launch-config field:
https://github.com/aws/aws-toolkit-vscode/pull/933#discussion_r377387302
1. set "aws.credentials" in launch-config overrides current active  credentials
2. without "aws.credentials", current Toolkit credentials are used in  the `sam local invoke` call.
Sample Lambda function code (correctly lists the …
> feat(sam debug): pass active credentials to the Docker container

- .changes/next-release/Feature-f746c8b0-a0e4-47e3-9583-0e746d6ac490.json
- src/eventSchemas/explorer/schemaItemNode.ts
Currently, clicking on a schema item node doesn't do anything. This is a bit confusing since we define onclick actions for things like s3 file nodes.
Open up the schema when clicking on a schema item node.
Related issue: https://github.com/aws/aws-toolkit-vscode/issues/2608
> feat(eventSchemas): Open schemas directly when clicking on schema item nodes

- src/shared/sam/cli/samCliInfo.ts
- src/shared/utilities/childProcess.ts
The logger is assigned on instantiation rather than when calling `run`. So having `logging` in the run params doesn't work.
Remove `logging` from the interface when running the process.
> fix(ChildProcess): clean-up the 'options' interface

- src/ecs/commands/runCommandInContainer.ts
- src/shared/constants.ts
Problem: 
Solution:If a user is missing the necessary ecs permission to execute
commands, a generic failed message will show when they attempt to run a
command in a container.
If a user is missing the necessary ecs permission to execute
commands, a generic failed message will show when they attempt to run a
command in a container.
If a user is missing the necessary ecs permission to execute
commands, a generic failed message will show when they attempt to run a
command in a container.
> ECS: handle missing ecs exec permissions

- src/awsexplorer/activation.ts
- src/credentials/activation.ts
- src/credentials/loginManager.ts
- src/lambda/commands/deploySamApplication.ts
- src/shared/sam/activation.ts
- src/shared/sam/debugger/awsSamDebugger.ts
- src/shared/vscode/commands2.ts
- src/test/lambda/commands/deploySamApplication.test.ts
- This builds on:
-  https://github.com/aws/aws-toolkit-vscode/pull/1708
- #2573 
- ~~Long-term it probably makes sense to wrap all Toolkit commands in a common class to handle auto-login.~~
- Done:  #2584
7400c5f55070 #1708 changed Toolkit to attempt auto-connect only when AWS
Explorer is made visible. But the "AWS: Deploy SAM Application" command
requires credentials. SAM local Run/Debug also wants credentials since
2b347ebdf0b7.
Try auto-connect in the central Commands hook.
> feat(sam): try auto-connect on "Deploy", "SAM Local Run/Debug"

- src/test/apprunner/wizards/codeRepositoryWizard.test.ts
Need to get rid of `CachedPrompter` sooner rather than later. It's not very good.
> fix(tests): make `ConnectionPrompter` tests not flaky

- buildspec/linuxIntegrationTests.yml
- src/integrationTest/cloudformation/templateRegistry.test.ts
- src/integrationTest/sam.test.ts
- src/shared/sam/activation.ts
- src/shared/watchedFiles.ts
CI tests are failing ~~since 5e40506dd627.~~ That correlates with...
1. SAM integ test failures started after release of SAM CLI 1.48: https://github.com/aws/aws-sam-cli/releases/tag/v1.48.0
2. `CloudFormationTemplateRegistry` test started failing after vscode 1.67 was released on 5/5
> fix(ci): skip watchedFiles test, build in-container

- src/shared/settings.ts
Migration was a bit noisy if the user had no settings to migrate
Skip migration if the setting isn't present
> fix(logging): reduce settings migration noise in edge case

- package.json
- src/dev/activation.ts
- src/extension.ts
- src/shared/vscode/secrets.ts
- src/test/fakeExtensionContext.ts
We don't leverage the VS Code API to boost our own productivity
Add a new module for "developer tools". This is basically an extension of `DevSettings`.
Currently just has a single command to edit an arbitrary key in `globalState` or `secrets`.
You need to have a 'dev setting' enabled to see it. Can be anything.
Here's an example of me editing the AWS explorer 'regions' state (the Toolkit would reflect these changes on reload)
> feat(dev): add internal tools module 

- .changes/next-release/Bug Fix-283da1b8-06b7-4fcf-ae7e-4285b3328da3.json
- resources/markdown/samReadme.md
Markdown Issues with emitted file, `README.TOOLKIT.md`.
- Remove superfluous line breaks
- Fix incorrect escaping of MD bold
- Add newChange file
- Remove unnecessary `<br/>`
- Unescaped escaped usage of bold `**`
- Rebuilt, ran tests, ran extension
> fix(sam init): markdown cleanup

- .changes/next-release/Feature-38b84656-bfe1-44f6-af07-a4010ece1029.json
- package.json
- src/credentials/loginManager.ts
- src/lambda/commands/uploadLambda.ts
1. Improper use of vscode-nls causes a runtime error.
1. Grouped expressions are not supported in vscode's package.json `with` clauses.
1. Fix the vscode-nls import.
1. Enable "Upload to Lambda" on all folders.
> fix: incorrect use of 'vscode-nls', always enable "Upload Lambda" context-menu item

- src/shared/resourcefetcher/compositeResourceFetcher.ts
- src/shared/resourcefetcher/fileResourceFetcher.ts
- src/shared/resourcefetcher/httpResourceFetcher.ts
- src/shared/schemas.ts
fileResourceFetcher and httpResourceFetcher already catch exceptions and
log a failure message, and are so documented. So `get().catch(…)` in
`schemas.ts` is redundant.
- remove `catch(…)` in `schemas.ts`
- cleanup log messages in fetcher impls.
> refactor(fetcher): drop redundant catch/log

- codecov.yml
The codecov "patch" check fails too often, is far too noisy, is not
actionable. Codecov is too unreliable.
At this point, codecov is merely a way to see coverage stats over time,
and to be able to glance at PRs to see if they measurably affected code
coverage (assuming codecov actually works on the PR).
> fix(ci): disable codecov "patch" check

- .changes/next-release/Feature-585b135b-349f-4db0-bf8a-9a483bd9b20e.json
- src/feedback/commands/submitFeedback.ts
- src/feedback/vue/submitFeedback.vue
The "Send" button is disabled until feedback is entered, and it's not
obvious what is expected.
Always enable the "Send" button, but show informative message if
a "sentiment" (smile/frown) was not chosen.
fix #2640
> feat(feedback): always enable "Send" button

- package.json
- src/awsexplorer/localExplorer.ts
- src/stepFunctions/activation.ts
- src/stepFunctions/commands/visualizeStateMachine/aslVisualizationCDKManager.ts
Apparently they have integ tests? 
And I guess the only case where the command wouldn't have an argument would be for keybindings.
But the keybindings in `package.json` was broken. Hmm.
Fix the keybindings in `package.json`
Update the command to infer the editor (this is not correct in all cases but good enough to maintain C9 compat)
Add fix for odd C9 <---> URI behavior
> fix(stepFunctions): add correct keybinding clause for `aws.previewStateMachine`

- src/shared/settings.ts
- src/test/shared/settingsConfiguration.test.ts
`affectsConfiguration` quite literally just checks if the _exact_ configuration key was modified. This is problematic for nested settings which the user can update as-if they were individual things.
For example, if the user updated `aws.experiments.jsonResourceModification`, VS Code will just say `aws.experiments` changed. But a big part of our `Settings` abstraction is that we don't need to worry about what exactly VSC says is a setting or isn't. I'll see about opening a ticket for VSC to discuss the whole configuration stuff more because tying these config keys + schemas directly to the UI is problematic.
Add a bit of logic for change detection plus a test. 
> fix(settings): add logic to detect changes in deeply-nested settings

- src/shared/extensionUtilities.ts
- src/shared/vscode/env.ts
- src/test/techdebt.test.ts
some code is using workarounds for older nodejs versions.
- add a test that fails when the minimum nodejs version is 16+
- show nodejs version in the `About Toolkit` command
> test: check tech debt for old nodejs versions

- .changes/next-release/Bug Fix-13d65c25-8be7-458a-8c16-081996e70da9.json
- package-lock.json
- package.json
Customers are not able to provide non-object values for the `Parameters` property in their Step Functions state machines. This behaviour is not consistent with the linting done in the AWS Console, which permits the value to be any type. 
The schema for the `Parameters` property was updated to accept any type in https://github.com/aws/amazon-states-language-service/pull/83. Bumping the package version to `^1.7.2` to pull in this change. 
Confirmed that non-object values are permitted for the `Parameters` property when bumping the version to `^1.7.2`. 
> Bump amazon-states-language-service dependency to ^1.7.2

- src/shared/extensions/git.ts
before:
```
error: unknown option `test'
```
after:
```
fatal: strange pathname '--test' blocked
```
Users can provide flags to be passed to `ls-remote`
POSIX guidelines state that any arguments after `--` should be treated as operands instead of flags
> fix(git): prevent users from passing additional flags to ls-remote

- src/awsexplorer/localExplorer.ts
- src/cdk/explorer/detectCdkProjects.ts
- src/cdk/explorer/nodes/appNode.ts
- src/test/cdk/detectCdkProjects.test.ts
- src/test/cdk/explorer/appNode.test.ts
* C9 creates a new workspace folder when creating a new CDK app for some reason
* C9 doesn't listen for `onDidChangeTreeData` correctly (can't refresh a child node)
Make the item IDs extremely precise and add a `isCloud9` check when refreshing.
> fix(cdk): address more C9 edge-cases

- .changes/next-release/Bug Fix-4ce9962e-2b34-4e0b-9201-d23e0c5e7901.json
- src/shared/cloudformation/cloudformation.ts
- src/shared/cloudformation/templateRegistry.ts
- src/test/shared/cloudformation/cloudformation.test.ts
Currently yaml schema association to cfn/sam yaml files sometimes fails because `cloudformation.load` does additional validation on the yaml document (basically checks if some fields exist on the resources). In some cases, this can cause the `cloudformation.load` to fail, resulting in the schema not getting applied to the cfn/sam yaml files when it should be.
Add the option to specify whether or not the yaml document should be validated when being loaded. This will allow us to disable upfront validation done while loading the file so that the schema is properly associated and then subsequently validated by vscode-yaml.
Ideally I would have like to have an integration test for this but vscode-yaml doesn't provide any way for us to get the current schema associated for the file 😢  
By …
> fix(schema support): fix yaml schemas occasionally not getting associated with cfn/sam yaml files

- src/shared/utilities/childProcess.ts
- src/test/shared/utilities/childProcess.test.ts
- src/test/testUtil.ts
Tests on macOS/Insiders are failing due to changes in node 16 
Add shebang line to shell scripts
> fix(tests): use shebang line for test scripts 

- package-lock.json
- package.json
- src/dynamicResources/awsResourceManager.ts
- src/extension.ts
- src/shared/awsFiletypes.ts
- src/shared/extensions/yaml.ts
- src/shared/schemas.ts
- src/shared/settings.ts
- src/shared/telemetry/activation.ts
- src/shared/telemetry/telemetryLogger.ts
- src/shared/telemetry/telemetryService.ts
- src/test/dynamicResources/awsResourceManager.test.ts
- src/test/globalSetup.test.ts
- src/test/shared/awsFiletypes.test.ts
- src/test/shared/settingsConfiguration.test.ts
- src/test/shared/telemetry/activation.test.ts
- src/test/shared/telemetry/telemetryService.test.ts
- src/test/utilities/collectionUtils.ts
No telemetry for AWS filetypes.
Solution:
- Set an `onDidOpenTextDocument` handler
- Checks if the opened file is an "AWS filetype" by asking these services:
- `schemaService`
- `templateRegistry`
- `awsFiletypes`
- TODO: only if edited? (`onDidChangeTextDocument`)
- TODO:is it worth adding "Resources" filetypes?
- Emit the `file_editAwsFile` metric.
- Currently "passive". May change later.
- Add TelemetryLogger.clear() so that tests can clear the global logger
state before querying.
- TODO: can we eliminate TelemetryLogger (just use the
TelemetryService directly)?
- ~~tests~~
- ~~passive or active?~~
> telemetry: AWS filetypes

- package-lock.json
- package.json
- src/test/shared/vscode/testUtils.ts
Typescript 4.7 has some great new features:
* Generic function instantiation
* Explicit variance notation
* Extends/infer short-hand (finally...)
* Better CFA, esp. for indexed fields
* ES module support
> build(deps): bump typescript to 4.7.2

- src/integrationTest/schema/schema.test.ts
- src/shared/extensions/git.ts
- src/test/shared/schema/testUtils.ts
Signed-off-by: Joshua Pinkney <jpink@amazon.com>
Currently we have no way of testing whether or not any schema changes in the [goformation](https://github.com/awslabs/goformation) project causes regressions in this project. 
This PR introduces a pretty easy way to verify that certain definitions are available in the JSON schema provided by the goformation project. It only deals with verifying definitions, properties and references. We could add support for verifying types but every time the schema changes we would have to manually update our tests with new types, etc so it might be a bit of a pain over time.
I've also added regression tests for all the JSON schema issues I closed last week.
Related issue: https://github.com/aws/aws-toolkit-vscode/issues/2597 …
> feat(tests): SAM JSON-schema regression tests

- package-lock.json
- package.json
macos CI fails with:
Setting up VS Code test instance, version: insiders
Downloading VS Code insiders from https://update.code.visualstudio.com/latest/darwin/insider
Error: read ECONNRESET
at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {
errno: -54,
code: 'ECONNRESET',
syscall: 'read'
}
Update vscode-test which includes a fix:
https://github.com/microsoft/vscode-test/pull/152
https://github.com/microsoft/vscode/issues/151588
> fix(ci): failing macos build

- docs/ARCHITECTURE.md
There's some documentation for `Commands` in the source code but not many examples. 
Add documentation plus simple examples. There's obviously a lot more that could be mentioned but it's probably better if those details are closer to the code.
I'll have to add some more UI examples later on though as the best patterns become more clear.
> docs(commands): add high-level documentation plus examples

- .changes/next-release/Bug Fix-c23296a6-e165-4532-aad9-3ef885d69277.json
- .changes/next-release/Feature-87ca1b13-8fee-442d-bf0d-651e70451eba.json
- media/css/base-cloud9.css
- media/css/base.css
- src/apigateway/vue/invokeApi.vue
- src/eventSchemas/vue/searchSchemas.vue
- src/feedback/vue/submitFeedback.vue
- src/lambda/vue/configEditor/samInvoke.css
- src/lambda/vue/configEditor/samInvokeComponent.vue
- src/lambda/vue/remoteInvoke/remoteInvoke.vue
- src/stepFunctions/vue/executeStateMachine/executeStateMachine.vue
- src/webviews/main.ts
- Forms don't share base.css by default.
- Buttons are hidden at the bottom of many forms in random locations.
- Include base.css by default in all forms.
- Move buttons to a "sticky" floating div at the top of all forms.
- Also put the title in there.
> feat(ui): sticky buttons everywhere

- .changes/next-release/Bug Fix-67cd5ec0-60ff-4f6d-8055-681a084aeaec.json
- src/lambda/activation.ts
The command doesn't auto-connect despite having entry-points outside of the AWS explorer
Make it login prior to execution
> fix(lambda): auto-connect when running `Upload Lambda`

- package-lock.json
- package.json
- src/lambda/commands/createNewSamApp.ts
- src/shared/sam/localLambdaRunner.ts
- src/shared/telemetry/vscodeTelemetry.json
todo
- ~~bump dependency after https://github.com/aws/aws-toolkit-common/pull/324 is merged~~
local telemetry defs should be in aws-toolkit-common
move them. https://github.com/aws/aws-toolkit-common/pull/324
> fix(telemetry): lift local defs into aws-toolkit-common

- media/css/base-cloud9.css
After 0f86958823b5 #2691, buttons in cloud9 webviews are gray. And the
headers are not sticky.
Copy some of the base.css stuff to base-cloud9.css.
Remove some of the forced background-color items.
> fix(css) webview style regression in cloud9

- .changes/next-release/Bug Fix-fd07b2a1-5c62-4402-9229-64149dfc5f12.json
- src/shared/awsClientBuilder.ts
JS SDK v2 has built-in logic to 'refresh' credentials on certain API errors, but the way it works is that it directly mutates the credentials provider. 
Align with the implementation. This should _finally_ resolve this fairly long-standing bug.
Related:
* #2664
* #2465
* #1226
> fix(auth): refresh credentials on certain API errors

- src/awsexplorer/defaultRegion.ts
On Cloud9, changing credentials is uncommon, while _new_ environments
_are_ common. Showing a prompt to ask about adding a region to AWS
Explorer is noisy.
On Cloud9, add the credentials-default region to AWS Explorer without
prompting.
> feat(cloud9): always add default region

- package-lock.json
- package.json
vscode-test now retries failed vscode download, which should reduce
spurious CI failures. https://github.com/microsoft/vscode-test/pull/154
> build(deps): update vscode-test

- src/test/globalSetup.test.ts
We're still using `FakeExtensionContext` for some reason but not resetting the stateful bits.
This doesn't cover everything but it's most of what tests use.
> tests: reset `globalState` after each test

- src/test/codewhisperer/util/showAccessTokenPrompt.test.ts
There are no unit tests for `showAccessTokenPrompt`
` showAccessTokenPrompt` is implemented as a combination of a quick pick and input box. It's meant to be temporary.
Add basic test cases
> [CodeWhisperer]: Add accountless unit test case

- src/codewhisperer/activation.ts
https://github.com/aws/aws-toolkit-vscode/issues/2732
> fix(codewhisperer): Only enable intelliSense config in AWS C9

- src/apigateway/activation.ts
- src/apprunner/activation.ts
- src/awsexplorer/activation.ts
- src/cloudWatchLogs/activation.ts
- src/codewhisperer/activation.ts
- src/dynamicResources/activation.ts
- src/ecr/activation.ts
- src/ecs/activation.ts
- src/eventSchemas/activation.ts
- src/extension.ts
- src/iot/activation.ts
- src/lambda/activation.ts
- src/lambda/vue/configEditor/samInvokeBackend.ts
- src/s3/activation.ts
- src/shared/cloudformation/activation.ts
- src/shared/sam/activation.ts
- src/ssmDocument/activation.ts
- src/stepFunctions/activation.ts
- This is a step towards getting better telemetry about command usage, in particular "aws.toggleSamCodeLenses".
- Sets `autoconnect` on these commands:
- 'aws.codeWhisperer'
- 'aws.s3.uploadFile'
> refactor(commands): migrate to commands2

- .changes/next-release/Bug Fix-b99c68f5-b3fe-417d-ac9a-cd5b63697396.json
- src/codewhisperer/activation.ts
( won't be merged until after release)
For troubleshooting issues potentially related to codewhisperer, it is
useful for users to be able to fully disable codewhisperer to rule it
out as a possible cause. But codewhisperer activate() is called even
when it is disabled in settings, and this creates various handlers for
numerous vscode events, which could be a potential source of performance
issues or other bugs.
Skip codewhisperer activation entirely if it is disabled in
settings.
> fix(codewhisperer): skip activation when disabled

- resources/css/base-cloud9.css
Accidentally added the override back in while merging the icons PR
Remove the artifact
> fix(css): remove Cloud9 override for header

- src/shared/ui/common/region.ts
- src/shared/wizards/wizard.ts
- src/ssmDocument/commands/publishDocument.ts
- src/ssmDocument/wizards/publishDocumentWizard.ts
- src/test/shared/wizards/wizardTestUtils.ts
- src/test/ssmDocument/commands/publishDocument.test.ts
- src/test/ssmDocument/wizards/publishDocumentWizard.test.ts
The old wizard code makes it hard to do other refactors, especially for things used by the wizard like `AwsContext`.
Simplify the existing code and add test coverage.
> refactor(ssm): clean-up create/update wizard

- src/test/codewhisperer/service/keyStrokeHandler.test.ts
- src/test/codewhisperer/service/recommendationHandler.test.ts
There are unusual API calls in CodeWhisperer unit tests. These API calls should be stubbed. 
Errors like 
```
rejected promise not handled within 1 second: AccessDeniedException: User: arn:aws:sts::412837722354:assumed-role/AWSVectorConsolasCognito-AWSVectorConsolasCognito-1D8LCKDHOCXA1/CognitoIdentityCredentials is not authorized to perform: codewhisperer:GenerateRecommendations because no identity-based policy allows the codewhisperer:GenerateRecommendations action
stack trace: AccessDeniedException: User: arn:aws:sts::412837722354:assumed-role/AWSVectorConsolasCognito-AWSVectorConsolasCognito-1D8LCKDHOCXA1/CognitoIdentityCredentials is not authorized to perform: codewhisperer:GenerateRecommendations because no identity-based policy allows the codewhisperer:GenerateRecommendations …
```
> fix(codewhisperer): Correctly stub API call in CodeWhisperer unit tests

- src/shared/sam/cli/samCliBuild.ts
All of our SAM CLI invocations are ran without an explicit working directory. I believe node defaults to the current working directory of the process in this case i.e. the extension host. 
Explicitly set a working directory for `sam build` as the template's directory. This is the behavior one would expect when running `sam build` in a fresh project. 
Other `sam` commands are still affected although they are harder to change without breaking things due to the temporary directory :/ 
The way the Toolkit + SAM CLI interact is incredibly brittle and this 'solution' is mediocre at best.
> fix(sam): set working directory for `sam build`

- src/codewhisperer/activation.ts
- src/codewhisperer/commands/basicCommands.ts
- src/codewhisperer/util/invalidateToken.ts
When updating global state in CodeWhisperer, sometimes the update was not awaited and it might cause race conditions.
await was added to each globalState.update call under CodeWhisperer.
> fix(codewhisperer): Add await in each globalState.update

- src/codewhisperer/commands/invokeRecommendation.ts
- src/codewhisperer/service/inlineCompletion.ts
- src/codewhisperer/service/keyStrokeHandler.ts
- src/codewhisperer/service/recommendationHandler.ts
When a suggestion is rejected and cleared from plugin in either intelliSense or VSC inline, sometimes a userDecision event is not fired in plugin telemetry.
1. Always fire userDecision events before clearing the suggestions.
2. Do not send serviceInvocation events if genReco/listReco API is not called.
> fix(codewhisperer): Add missing userDecision events

- src/shared/telemetry/service-2.json
Service model is too strict
Relax `ClientId`. This doesn't do much besides let's us see how many times `getClientId` fails. And if any of our tests are sending telemetry somehow.
> telemetry: update service model

- package.json
"Show AWS Commands" should not appear in Cloud9, it's a vscode-ism.
Add condition in package.json
> fix(cloud9): omit "Show AWS Commands" in cloud9

- src/codewhisperer/commands/basicCommands.ts
If customer opens a non-text document, for example images, and hit security scan, they will see `Please open a file you want to scan to proceed`, which can be confusing.
To update the error message to handle this case.
> fix(codewhisperer): update security scan error message

- src/cloudWatchLogs/commands/addLogEvents.ts
- src/cloudWatchLogs/commands/searchLogGroup.ts
- src/cloudWatchLogs/commands/viewLogStream.ts
- src/cloudWatchLogs/registry/logStreamRegistry.ts
If a search of log groups is taking too long or was accidental, the user has no way to cancel it. 
Add a timeout that can be cancelled via user input. 
Note: This change involves using deprecated code from `waitTimeout` in `src/shared/utilities/timeoutUtils.ts`. 
Note: The `Timeout` object is currently set to auto cancel the search after 5 seconds. 
> cwl: Cancel log group search 

- package-lock.json
- src/credentials/wizards/createProfile.ts
- src/credentials/wizards/templates.ts
- src/shared/awsContextCommands.ts
- src/shared/credentials/userCredentialsUtils.ts
- src/test/credentials/wizards/createProfile.test.ts
Old flow is clunky. If the user provides bad credentials they need to start all over. 
Use updated flow that goes back a step on failure.
This flow was pulled from a separate branch with more in-depth UX improvements which is why the implementation is split into a 'template' rather than a single wizard.
The validation step can be made nicer but that's for another time.
> ux(auth): improve 'Create Credentials Profile' flow

- .changes/next-release/Feature-2d7e75e6-fd08-41fd-91d0-5e1a8c26759d.json
- src/shared/awsFiletypes.ts
Files ~/.aws/credentials and ~/.aws/config are highlighted incorrectly if vscode auto-detect is disabled or fails depending on the contents, then sets the language to "plaintext" or "markdown".
Set the language as "ini".
> feat(filetypes): syntax highlighting for ~/.aws/ files

- .changes/next-release/Bug Fix-80a89464-b246-4ed8-bc7c-c58bdad7b508.json
- .changes/next-release/Feature-aa840ab7-982f-4c52-a2c5-c6d1513129af.json
- .changes/next-release/Feature-eae23041-03ad-4df1-92ab-908412b5f584.json
- package.json
- package.nls.json
- src/credentials/loginManager.ts
- src/credentials/providers/credentialsProviderManager.ts
- src/extension.ts
- src/shared/awsContextCommands.ts
- src/shared/credentials/credentialSelectionDataProvider.ts
- src/shared/credentials/defaultCredentialSelectionDataProvider.ts
- src/shared/utilities/collectionUtils.ts
- src/test/shared/credentials/defaultCredentialSelectionDataProvider.test.ts
- src/test/techdebt.test.ts
- Problem 1:
- Docs still mention the "Connect to AWS" command, though it was renamed.
- Even if we update the docs, there is evidence that customers still expect a "Connect" command; "Choose AWS Profile" is not intuitive for the first connection.
- **Solution:**
- Restore "Connect to AWS" command.
- Problem 2:
- Trying non-default profiles is useful when env vars or IMDS are present. But in other cases, arbitrarily trying 3 profiles can be annoying.
- **Solution:**
- Try only 1 other profile instead of 3.
- ref https://github.com/aws/aws-toolkit-vscode/pull/2316 https://github.com/aws/aws-toolkit-vscode/commit/1f5b341301864fd273cec8ff6de6c168961e6d3c
- Problem 3:
- "AWS" statusbar item and other entrypoints defer to the profile picker, and there's no obvious way to edit the profiles.
- …
> feat(connect): "Edit Credentials" in profile quickpick; restore "Connect to AWS"; autoconnect max 1

- package.json
There are three cloudWatchLogs commands available when viewing a log group search or log stream. `aws.cwl.changeFilterPattern` and `aws.cwl.changeTimeFilter` don't offer anything `aws.cwl.searchLogGroup` doesn't. 
We eliminate `aws.cwl.changeFilterPattern` and `aws.cwl.changeTimeFilter` from command Palette. 
> CWL: don't show commands on commandPalette

- src/credentials/wizards/createProfile.ts
- src/shared/utilities/messages.ts
If "Create Credentials" command fails, the message doesn't include a help button.
Add help button.
> fix(credentials): show help button on "Create Credentials" failure

- .changes/next-release/Bug Fix-1859b589-4651-4fa5-9545-317fceaff3f1.json
- src/shared/sam/debugger/goSamDebug.ts
See #2797
This affects MacOS running Node 16+, presumably due to a change in libuv.
Same root cause as https://github.com/aws/aws-toolkit-vscode/pull/2666
Add shebang line. I don't think we have any other places with shell scripts we create but could be wrong.
> fix(SAM/Go): update Delve install script

- src/test/testUtil.ts
Flaky CI failure (on "minimum" job):
1 failing
1) "before each" hook for "returns placeholder node if no resource types are enabled":
Error: Editor "Untitled-1" was still open after executing "closeAllEditors"
at Object.<anonymous> (src/test/testUtil.ts:278:15)
Retry the "closeAllEditors" command.
> fix(tests): closeAllEditors() sometimes fails

- .changes/next-release/Bug Fix-a8470482-60c4-4711-b967-e5b8c446a027.json
- package.json
- src/codewhisperer/activation.ts
When pressing up or down when suggestion is active, the cursor won't go up or down.
Let cursor go up or down after user pressing pressing up or down( meanwhile the suggestion is rejected).
> fix(codewhisperer):  Fix up & down not moving cursor when suggestion active

- src/integrationTest/stepFunctions/visualizeStateMachine.test.ts
- src/stepFunctions/activation.ts
- src/stepFunctions/commands/downloadStateMachineDefinition.ts
- src/test/testUtil.ts
These tests execute extension commands, and one test specifically checks for an error. Commands now show an error message instead of bubbling it up so this test ended up stalling on the error message.
Fix the test so it checks for an error message.
Need to figure out why Mocha timeouts don't work so these stalled tests are easier to find.
> fix(tests): update `visualizeStateMachine` 

- package-lock.json
- package.json
- src/codewhisperer/service/completionProvider.ts
- src/codewhisperer/service/inlineCompletion.ts
- src/codewhisperer/service/recommendationHandler.ts
- src/codewhisperer/util/telemetryHelper.ts
- src/test/codewhisperer/commands/onAcceptance.test.ts
- src/test/codewhisperer/service/recommendationHandler.test.ts
- src/test/codewhisperer/util/telemetryHelper.test.ts
1. Recommendations of empty string or empty list are not reported in userDecision telemetry.
2. The type prefix matching for determining Discard event should only be performed when client gets the suggestion from server. 
1. Report useDecision events for empty recommendations.
2. Do telemetry type prefix matching when suggestion first reaches client.
3. If a suggestion is marked as Discard but later it was showed to user, it won't be reported as Discard in userDecision telemetry.
Note:
This fix is not user facing so no changelog item is added.
This PR has been tested with below test cases:
1. With recommendation = [] at line 259 of recommendationHandler.ts that simulate a Empty List recommendations. userDecision event with Empty was sent.
2. With r.content = '' at line 266 of that …
> fix(codewhisperer): Add userDecision telemetry for empty recommendation

- src/awsexplorer/localExplorer.ts
- src/cdk/explorer/nodes/appNode.ts
- src/cdk/explorer/nodes/constructNode.ts
- src/cdk/explorer/nodes/propertyNode.ts
- src/cdk/explorer/rootNode.ts
- src/codewhisperer/explorer/codewhispererNode.ts
- src/shared/treeview/resource.ts
- src/shared/treeview/resourceTreeDataProvider.ts
- src/shared/treeview/utils.ts
- src/shared/vscode/commands2.ts
- src/test/cdk/explorer/appNode.test.ts
- src/test/cdk/explorer/constructNode.test.ts
- src/test/cdk/explorer/propertyNode.test.ts
- src/test/shared/treeview/resourceTreeDataProvider.test.ts
- src/test/shared/vscode/commands.test.ts
While prototyping features, I kept running into the situation where I wanted to update how a node was rendered independently of the node's children. The current implementation does not easily support this use-case, forcing us to propagate events up to a parent node to get the desired behavior.
Fully generalize the `TreeNode` interface. It was already very close to the general solution, it just needed a few tweaks to get it there. Of course, implementing this correctly with a tree data provider required more substantial changes which tests were added for.
I wouldn't recommend that _all_ tree node implementations use this pattern because it can quickly spiral out of control from a maintainability point of view. Still, I'd rather have the proper solution readily available than a bunch of …
> feat(ui): decouple tree nodes from the UI representation

- package.json
Escape Hatches were invisible and some other functionality was not emitting proper telemetry. 
The source was that the `package.json` file was outdated. 
> fix(cwl): update resourceScheme in package.json

- src/cloudWatchLogs/registry/logStreamRegistry.ts
`viewLogStream` could also take a long time to load and we already have to the code to improve this. 
Implement the same logic as we have in `searchLogGroup`. 
TODO: Generalize this logic as a function `getResponseOrCancel`. Note: I tried to do this and it ended up much nastier than keeping them separate so didn't include in this PR. 
> cwl: cancel view log stream + loading message. 

- src/cloudWatchLogs/activation.ts
- src/cloudWatchLogs/registry/logStreamRegistry.ts
- src/test/cloudWatchLogs/changeLogSearch.test.ts
- src/test/cloudWatchLogs/registry/logStreamRegistry.test.ts
`onDidCloseTextDocument` was being called anytime registry was initiated and was not being made a disposable.
Move the event handlers out of the registry class and into subscriptions so that they are disposable and avoid any potential memory issues. 
> cwl: onDidCloseTextDocument() should be called exactly once for the lifetime of the Toolkit

- src/cloudWatchLogs/timeFilterSubmenu.ts
- src/test/cloudWatchLogs/commands/searchLogGroup.test.ts
The custom time range box did not have the same buttons/functionality as all other Wizard prompts. Additionally, there was an error when the custom time range box was cancelled and then reopened. 
We can add the common buttons to custom time range box and not reuse a previous prompter to avoid the error. 
> cwl: Update custom date range prompter

- src/shared/credentials/defaultCredentialSelectionDataProvider.ts
Error on vscode 1.63 or older:
2022-08-10 18:29:21 [ERROR]: aws.login: Error: Extension 'amazonwebservices.aws-toolkit-vscode' CANNOT use API proposal: quickPickSeparators.
Its package.json#enabledApiProposals-property declares: [] but NOT quickPickSeparators.
The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api amazonwebservices.aws-toolkit-vscode
Check vscode version instead of relying on feature-detection.
ref #2820
> fix(): "API proposal" error for older vscode

- src/awsexplorer/activation.ts
- src/awsexplorer/localExplorer.ts
- src/shared/treeview/resourceTreeDataProvider.ts
- src/shared/utilities/functionUtils.ts
- src/test/shared/treeview/resourceTreeDataProvider.test.ts
- src/test/shared/utilities/functionUtils.test.ts
View is re-rendered when a node becomes "invisible".
This is a consequence of visibility being functionally different from a node's children changing.
Externally refresh a specific node's child **without** changing the children array itself. 
This can also be implemented by increasing the scope of `onDidChangeChildren` and exposing it on the "root" node although I'll save that for another time.
> performance: optimize `Developer Tools` view

- src/codewhisperer/activation.ts
- src/codewhisperer/commands/onAcceptance.ts
- src/codewhisperer/util/closingBracketUtil.ts
- src/test/codewhisperer/commands/onAcceptance.test.ts
- src/test/codewhisperer/util/closingBracketUtil.test.ts
When customer invoke CodeWhisperer, they might already have matching brackets in the right context but our current implementation is not taking it into account.
When customer accept a recommendation, we match the brackets that are in the accepted recommendation with user's right context, and remove the extra brackets if there is any:
in VSC:
https://user-images.githubusercontent.com/60411978/184037665-0c68da1a-d13c-4947-adb5-929435664a8e.mov
in C9:
https://user-images.githubusercontent.com/60411978/184037688-1615cad5-06f9-45ee-8dfc-4207d7634423.mov
with whitespace:
https://user-images.githubusercontent.com/60411978/184675900-ea83c202-53a5-4660-9831-2a57a234b52d.mov
> feat(codewhisperer): handle extra brackets onAcceptance of recommendation

- docs/CODE_GUIDELINES.md
- src/test/shared/vscode/testUtils.ts
Not obvious how to test commands without splitting up the logic. 
This is only applicable when the command itself requires fakes.
Add util function to create testable versions of commands. It's not perfect because VS Code commands are meant to be global and unique whereas testing often requires test versions of things. The implementation is also fragile but acceptable for simple tests.
> testing: add `testCommand` util

- src/codewhisperer/service/referenceLogViewProvider.ts
request from product to make the license name bold and italic in reference log so it stands out more
> feat(codewhisperer): make the license name bold in reference log

- package-lock.json
- package.json
- src/codewhisperer/tracker/codewhispererCodeCoverageTracker.ts
- src/test/codewhisperer/tracker/codewhispererCodeCoverageTracker.test.ts
The startTime field in CodeWhisperer percentageCode metric is unused but it caused issue on the backend.
Remove this startTime field.
> fix(codewhisperer): Remove startTime in CodeWhisperer percentageCode metric

- src/codewhisperer/service/inlineCompletion.ts
- src/codewhisperer/service/recommendationHandler.ts
By the time when plugin gets first paginated suggestion(s), 
1. If the cursor is behind invocation position, it is Discarded.
2. If the typeahead does not match, it is Discarded.
3. If the editor is changed or the invocation editor lost focus, it is Discarded.
Mark suggestions as Discard in the above 3 cases. 
https://user-images.githubusercontent.com/97199248/186044661-5dd36cf3-3ac7-452a-92d8-07eb50cd643e.mov
https://user-images.githubusercontent.com/97199248/186044683-6f3a1aeb-1ffc-46ac-a4e7-f757cc1cc5bc.mov
https://user-images.githubusercontent.com/97199248/186044693-f2454786-c7c8-4e4c-9003-00916f5189bb.mov
> fix(codewhisperer): Mark suggestions as Discard in some cases

- package-lock.json
- package.json
- src/codewhisperer/commands/startSecurityScan.ts
- src/codewhisperer/models/constants.ts
- src/codewhisperer/models/model.ts
- src/codewhisperer/util/commonUtil.ts
- src/shared/filesystemUtilities.ts
- Update security scan telemetry to track overall project size
- Add util method to get working directory size;
- Update security scan command to emit project size field telemetry;
- Verification is as follow images
Size from Finder view:
Telemetry log indicates successfully emit essential field:
> feat(codewhisperer): Update security scan telemetry to track overall project size

- src/codewhisperer/activation.ts
- src/codewhisperer/commands/onAcceptance.ts
- src/codewhisperer/service/keyStrokeHandler.ts
- src/codewhisperer/tracker/codewhispererCodeCoverageTracker.ts
- src/test/codewhisperer/tracker/codewhispererCodeCoverageTracker.test.ts
Current code percentage written metric in CodeCoverageTracker does not count tokens removed by user, which makes this metric inaccurate.
Similar to what was implemented in AWS Toolkit for JetBrains by @Will-ShaoHua , we make best effort to:
1. Estimate total user token by counting user inputs and deletions
2. Estimate total accepted tokens from CodeWhisperer suggestion by counting unmodified suggestions
Total user token is updated when there is a TextDocumentChange Event,
1. If  the event is not from human input (i.e. from plugins, formatters), this event is ignored.
2. If the event is when user copy large chunk of code, this event is ignored.
We only count the user manual keyboard input, intelliSense code acceptance and small chunk code copy as inserted total user token. For deletion …
> fix(codewhisperer): update code coverage tracker to keep tracker of removed characters

- .changes/next-release/Feature-a61e0660-9f68-4e50-a0b1-b8a742075017.json
- src/shared/constants.ts
- src/shared/extensions/yaml.ts
- src/shared/schemas.ts
- Currently SAM/CFN schema paths take up a lot of space on the status bar
- Specify a title for the SAM/CFN schemas so VSCode-YAML will display that on the status bar instead of the full file path
Related issue: https://github.com/aws/aws-toolkit-vscode/issues/2704
The only annoying thing is when you have a title for the schema it automatically adds that everytime you hover something as shown in the after screenshot
**Before:**
**After:** 
> feat(Schema): Decrease the amount of space SAM/CFN schemas take on the status bar

- src/shared/errors.ts
- src/shared/sam/cli/samCliLocalInvoke.ts
- src/shared/sam/debugger/awsSamDebugger.ts
- src/shared/sam/debugger/goSamDebug.ts
- src/shared/sam/localLambdaRunner.ts
- src/shared/telemetry/spans.ts
- src/test/lambda/local/debugConfiguration.test.ts
- src/test/shared/codelens/localLambdaRunner.test.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
Our SAM run/debug implementation has several problems with error handling:
* Inconsistent error message UX (some are placed in the logs, some are shown directly to the user)
* Telemetry only covers a portion of the relevant code paths and does not emit reasons for failure
* Some errors are swallowed while others are bubbled up to the VSC API
* Bubble up all errors but use a single error handler to prevent the VSC error modal from showing
* Added a button to open the launch config to preserve current UX 
* Use telemetry spans to cover almost the entire code path
* Remove `sam_attachDebugger` metric as it is redundant. Failures to attach counts as a failure for the whole execution.
* Add some basic error codes to better determine why a run/debug execution failed …
> feat(sam): improve run/debug error handling and telemetry

- .changes/next-release/Bug Fix-6b246663-e029-4e55-9ecb-c392c38c8aa2.json
- src/shared/sam/cli/samCliInvokerUtils.ts
- src/shared/sam/debugger/pythonSamDebug.ts
Debugging Python image lambdas does not work on C9
Use the same pattern that we use for debugpy
> fix(sam): use different debugger args for Python image lambdas on C9 

- src/awsexplorer/defaultRegion.ts
- src/ecs/commands/updateEnableExecuteCommandFlag.ts
- src/s3/fileViewerManager.ts
- src/shared/sam/activation.ts
- The `promptInstallYamlPlugin` buttons are verbose, and get truncated on a laptop-sized screen.
- In other "Install X" dialogs we use "Install" as the action button. "Open Marketplace Page" might be confused with a website link.
> feat(sam): simplify "install yaml" verbiage

- package-lock.json
- package.json
> chore: bump telemetry version to be 1.69

- src/test/codewhisperer/service/recommendationHandler.test.ts
https://github.com/aws/aws-toolkit-vscode/issues/2857
The root cause is likely from concurrent test cases which reads & writes a single shared global variable. 
Replace global variable shared between multiple test cases with local variable for each test case.
> fix(codewhisperer): Fix unreliable test in CodeWhisperer

- src/integrationTest/sam.test.ts
I was wrong, [this change](https://github.com/aws/aws-toolkit-vscode/pull/2870/files#diff-4dd1d1082508662f8f220333fa91583d5fc4abdfcacc30547c2309cdf9435a65L59-R59) actually did cause the test failures
Remove the regexp. The test loses some specificity but I think it's acceptable for better UX.
> tests: fix failing SAM CLI integration tests

- .changes/next-release/Feature-9b4c339a-7cdf-4340-b911-f33bde49b461.json
- src/credentials/credentialsUtilities.ts
- src/credentials/loginManager.ts
- src/credentials/wizards/createProfile.ts
- src/shared/credentials/defaultCredentialSelectionDataProvider.ts
- src/shared/utilities/messages.ts
When onboarding "from zero" (no ~/.aws, need credentials) or when running the "Create Credentials Profile" command, if the provided credentials are invalid, or if the user needs to edit ~/.aws/credentials to provide non-static credentials, there is no obvious way to open the ~/.aws/credentials file for new users.
Show "Edit Credentials" in the error message if "Create Credentials Profile" fails.
> feat(credentials): show "Edit Credentials" in error message

- package-lock.json
- package.json
- src/codewhisperer/service/inlineCompletion.ts
We need more visibility into user's perceived latency
To emit telemetry on the new perceivedLatency event: the definition of this event is added in this [PR](https://github.com/aws/aws-toolkit-common/pull/366)
corresponding JB PR is [here](https://github.com/aws/aws-toolkit-jetbrains/pull/3298)
> [codewhisperer]: emit perceived latency telemetry

- .changes/next-release/Bug Fix-6071a140-0b81-468b-bb9b-f481c9147a7f.json
- .changes/next-release/Bug Fix-77142a2a-46de-420b-b17e-ffcdabf6d93c.json
- src/codewhisperer/service/keyStrokeHandler.ts
When cwspr working with https://marketplace.visualstudio.com/items?itemName=dsznajder.es7-react-js-snippets plugin, which call generate code templates, the code template from react plugin will trigger cwspr auto completion, which is supposed to be block by this logic https://github.com/aws/aws-toolkit-vscode/blob/master/src/codewhisperer/service/keyStrokeHandler.ts#L154.
The multiline code snippet generated from the plugin above is not captured by API `isSingle`, so the PR is a short term fix for this and will try other more solid solution.
> fix(CodeWhisperer): interference with react plugin

- src/shared/icons.ts
- src/test/shared/icons.test.ts
No easy way to figure out where an icon came from (this is a good thing in most cases)
Add a best-effort escape hatch. Icons can come from many places so `source` may not always exist.
> icons: add source field

- .changes/next-release/Bug Fix-301c5e9e-3c91-4044-90c1-f419336d2b96.json
- src/codewhisperer/util/closingBracketUtil.ts
- src/test/codewhisperer/util/closingBracketUtil.test.ts
the level of bracket needs to be greater than or equal to 0. When auto-triggering at a position before the opening `(`, it should be matched up with the closing `)` from right context.
before:
after:
https://user-images.githubusercontent.com/60411978/190811164-f66720c4-0ca2-460a-b612-c075d03ebb9f.mov
> fix(codewhisperer): bug in handling closing brackets

- .changes/next-release/Feature-a884bba4-5d48-4a0b-9b80-9549697f4f79.json
- src/shared/sam/activation.ts
Right now, we are only prompting users to install the YAML plugin when AWSTemplateFormatVersion is in a document when it's opened/focused or the file is template.yaml/template.yml but it doesn't take into account when users type into the document
If the YAML plugin is not installed then listen to onDidChangeEvents until AWSTemplateFormatVersion becomes available. This feature is currently configured to have a higher debounce rate since the prompt doesn't need to show particularly fast. Also not every yaml file they open will be an aws related file.
Tested against 40k line yaml files
Related issue: https://github.com/aws/aws-toolkit-vscode/issues/2677
> feat(YAML): Prompt users to install YAML plugin when AWSTemplateFormatVersion becomes available in their YAML document

- .changes/next-release/Bug Fix-bfe16ba3-99a9-4953-80fe-792a666829b8.json
- src/credentials/providers/ec2CredentialsProvider.ts
- src/credentials/providers/ecsCredentialsProvider.ts
Credentials from ECS and EC2 are held past expiration
Remove the memoization
> fix(auth): ec2/ecs credentials caching

- src/codewhisperer/activation.ts
- src/codewhisperer/util/hoverConfigUtil.ts
- src/test/codewhisperer/util/hoverConfigUtil.test.ts
CodeWhisperer won't restore user settings if they reload/exit at certain times
Use `globalState` + restore the setting on extension activation
> fix(codewhisperer): impove 'hover' override robustness for inline suggestions

- src/codewhisperer/activation.ts
- src/codewhisperer/commands/onAcceptance.ts
- src/codewhisperer/commands/onInlineAcceptance.ts
- src/codewhisperer/service/referenceHoverProvider.ts
- src/codewhisperer/service/referenceLogViewProvider.ts
The on acceptance command is chunky and prone to error. [https://github.com/aws/aws-toolkit-vscode/pull/2888#discussion_r973187466](https://github.com/aws/aws-toolkit-vscode/pull/2888)
On acceptance is separated from activation.ts. 
> refactor(codewhisperer): onAccept command

- src/codewhisperer/activation.ts
- src/codewhisperer/service/inlineCompletionService.ts
Fix a critical bug that were introduced in https://github.com/aws/aws-toolkit-vscode/commit/f82944e81c155ef938ab2e264b6747b47d54fa34
When changing the hover config in inlineCompletionService, a document text close event will be sent and received by the listener in activation.ts, which removed the recommendations.
This bug will make new inline completion not showing the recommendation if there is only one recommendation in paginated response. 
No changelog item is needed for this fix.
Let the doc close listener only remove recommendation when the closed file is the invocation file.
> fix(codewhisperer): Sometimes not show recommendation bug in new inline code path

- .changes/next-release/Feature-66c53a81-650f-442b-ad0c-4ea71a3f1f3c.json
- package.json
- src/dev/activation.ts
Toolkit developers, and customers who are troubleshooting, need a way to see the various global state that Toolkit depends on.
Introduce `Show Global State` item in the "AWS (Developer)" menu. Currently only shows env vars, but can be expanded later.
> feat(dev): "Show Global State"

- package.json
- package.nls.json
- src/awsexplorer/commands/copyArn.ts
- src/awsexplorer/commands/copyName.ts
- src/awsexplorer/regionNode.ts
- src/ecs/commands.ts
- src/ecs/model.ts
- src/ecs/wizards/executeCommand.ts
- src/shared/clients/ecsClient.ts
- src/shared/treeview/resource.ts
- src/shared/treeview/utils.ts
- src/test/awsExplorer/commands/copyArn.test.ts
- src/test/awsExplorer/commands/copyName.test.ts
* The "Copy ARN" command doesn't work with `TreeShim`
* `RegionNode` caches all service nodes
* Can't list services for non-default ECS cluster (#2915)
* Fix the copy name/ARN commands
* Added tests for this
* Change `RegionNode` to lazily instantiate service nodes
* Add cluster ARN to `listServices` call
Also added more documentation for `ResourceTreeNode`
> fix(ecs): update `Copy ARN` command and region node

- src/codewhisperer/service/recommendationHandler.ts
- src/test/codewhisperer/service/recommendationHandler.test.ts
userDecision events with Empty recommendation state in CodeWhisperer is sent more than expected. This event should only be sent when all paginated responses are Empty list of recommendation
Only send one empty user decision per pagination session
No changelog item is needed for this PR.
> fix(codewhisperer): only send one empty user decision per pagination session

- src/codewhisperer/commands/onInlineAcceptance.ts
- src/test/codewhisperer/service/completionProvider.test.ts
When accept a reco, userDecision telemetry was sent twice. In release 1.51.0, telemetry acceptance userDecision events will be sent twice. 
Remove recommendations before they are sent twice.
> fix(codewhisperer): Fix duplicate userDecision telemetry accept

- package.json
- src/ecs/commands.ts
See #2928
The VSC API does not work on C9,  the handler for `createTerminal` is not implemented.
> fix(ecs): gate "Open Terminal..." feature on Cloud9

- .changes/next-release/Feature-a4f4b3f0-0449-4e29-a8d1-f7d2c452ebc1.json
- src/dynamicResources/awsResourceManager.ts
- src/shared/cloudformation/activation.ts
- src/shared/cloudformation/cloudformation.ts
- src/shared/cloudformation/templateRegistry.ts
- src/shared/sam/codelensRootRegistry.ts
- src/shared/schemas.ts
- src/shared/utilities/vsCodeUtils.ts
- src/shared/watchedFiles.ts
- src/test/dynamicResources/awsResourceManager.test.ts
- src/test/shared/schemas.test.ts
- Currently, untitled yaml files for cloudformation/sam do not get a schema associated until the file is saved
- Watch untitled yaml files for cloudformation/sam contents and apply the schema accordingly
- Allow the file watcher to be able to work with untitled yaml files
To test you can just create a new untitled file and make sure the language is yaml. Then add `AWSTemplateFormatVersion` and it should automatically start detecting the schema
> feat(YAML): Watch untitled yaml files for cloudformation/sam contents

- src/shared/telemetry/telemetryClient.ts
- src/shared/telemetry/telemetryLogger.ts
- src/shared/telemetry/telemetryService.ts
- src/test/codewhisperer/tracker/codewhispererCodeCoverageTracker.test.ts
- src/test/shared/telemetry/spans.test.ts
- src/test/testUtil.ts
This is unblocked since we have `guessDefaultRegion()` now.
related: a50b83a833dacf95d29216c7e446c67556cf7925
> feat(telemetry): add awsRegion in commonMetadata

- src/shared/cloudformation/templateRegistry.ts
- src/shared/watchedFiles.ts
- src/test/shared/cloudformation/templateRegistry.test.ts
No need for remove() to accept a string anymore.
> refactor: no string arg in watchedFiles.remove()

- src/test/codewhisperer/commands/basicCommands.test.ts
- src/test/codewhisperer/testUtil.ts
- src/test/codewhisperer/util/telemetryHelper.test.ts
In some situation telemetry test case in CodeWhisperer may fail. The assertTelemetry compares a deep equal of the first telemetry record it gets from the queries. 
Clean the telemetry records before each telemetry test case.
> fix(codewhisperer): clear telemetry logger to avoid flaky test case

- .changes/next-release/Bug Fix-24b2f685-2010-4504-ace1-6bad1ca4b660.json
- src/codewhisperer/service/keyStrokeHandler.ts
- src/test/codewhisperer/service/keyStrokeHandler.test.ts
1. The 15 character keystroke auto-trigger was accidentally removed in https://github.com/aws/aws-toolkit-vscode/pull/2899. 
2. Enter auto trigger by \r\n was removed in https://github.com/aws/aws-toolkit-vscode/pull/2899. 
3. Reverted the 2 second auto trigger limitation for Special characters | Enter |intelliSense auto triggers which was removed in https://github.com/aws/aws-toolkit-vscode/pull/2899. 
Trigger auto trigger when there are more than 15 keystroke inputs.
> fix(codewhisperer): fix auto-trigger regressions

- src/codewhisperer/service/inlineCompletionService.ts
- src/codewhisperer/service/keyStrokeHandler.ts
2 additional regression cases found for auto-trigger after #2899 refactoring:
- it's not triggering when user press multiple Enter key
- In Cloud9, every document change is triggering recommendation as IntelliSenseAcceptance because the length of changedText for Cloud9 content change event is greater than 1
> fix(codewhisperer): additional cases for auto-trigger

- src/shared/buildspec/registry.ts
- src/shared/cloudformation/templateRegistry.ts
- src/shared/schemas.ts
- src/test/shared/schemas.test.ts
- Currently buildspec and cloudformation are watching all yaml files and trying to race to see evaluate whether the current yaml file is buildspec or cloudformation. This means that sometimes schemas won't be set for valid buildspec or cloudformation files. This is due to an issue in the watchedfile registry, where having multiple template registries watch one file type wasn't really considered.
- Introduce the concept of "owned" files in the template registries, where only owners of a file can update the schema for a file unless the type of the schema changes. E.g. cloudformation <-> buildspec. Since each registry is considered seperate and the implementation for the buildspec/cloudformation registries in other parts of the code require only their file types to be available, this choice …
> fix(schemas): Allow template registries to "own" a file path to fix race conditions in JSON Schema assignment

- CONTRIBUTING.md
- src/credentials/sso/clients.ts
- src/shared/awsClientBuilder.ts
- src/shared/settings.ts
- src/shared/utilities/typeConstructors.ts
- src/test/shared/defaultAwsClientBuilder.test.ts
No easy way for us to change service endpoints
Add `aws.dev.endpoints` setting. This could be exposed to extension users in a later release.
> feat(dev): add endpoints override

- src/awsexplorer/activation.ts
- src/credentials/auth.ts
- src/credentials/sdkV2Compat.ts
- src/shared/settings.ts
- src/shared/utilities/tsUtils.ts
- src/test/credentials/auth.test.ts
- src/test/fakeExtensionContext.ts
- src/test/shared/vscode/message.ts
- src/test/shared/vscode/window.ts
- src/test/testUtil.ts
No easy way to manipulate SSO configurations separate from traditional AWS credentials
* Add a shared auth service
* Gate any UI behind a feature flag
* Add the setting `"aws.dev.showAuthNode": true` to see the UI
> feat(auth): add initial unified auth implementation

- .changes/next-release/Bug Fix-e4cfd29a-bc4e-4aab-809d-08b44991d139.json
- buildspec/packageTestVsix.yml
- scripts/build/createRelease.ts
changelog is not generated for prerelease builds.
generate the changelog in CI "package test" job.
> build: also generate CHANGELOG.md in prereleases

- src/shared/awsClientBuilder.ts
- src/test/shared/defaultAwsClientBuilder.test.ts
Endpoint override doesn't play nicely with hard-coded variant
Don't clobber it
> fix(dev): preserve hard-coded endpoint override if it exists

- src/ecs/model.ts
- src/test/ecs/model.test.ts
- src/test/shared/treeview/testUtil.ts
- src/test/utilities/collectionUtils.ts
* Current explorer tree tests are verbose and redundant
* No tests for ECS explorer tree
* Add some utils
* Add simple tests
The tedious part for writing these tests is collecting example data. A follow-up PR will address that.
> tests(explorer): add utils and examples using ECS

- .changes/next-release/Bug Fix-f3f310a4-ee52-4c4a-8c91-3ca9b4b670c6.json
- src/shared/awsContextCommands.ts
- src/shared/credentials/userCredentialsUtils.ts
- src/test/shared/credentials/userCredentialsUtils.test.ts
- If ~/.aws/config exists but doesn't have a usable credentials profile, the Connect to AWS and Choose AWS Profile actions open ~/.aws/config immediately instead of starting the Create Credentials Profile wizard.
- When using "Connect" and "Choose profile", open the create credentials wizard or the profile selector when credentials aren't actually present in the ~/.aws/config and ~/.aws/credentials files
> fix(credentials): "Connect" and "Choose Profile" open create credentials wizard/profile selector when credentials aren't present in aws configs

- src/credentials/auth.ts
- src/credentials/sso/clients.ts
- src/test/credentials/auth.test.ts
- src/test/utilities/stubber.ts
The Auth service doesn't remember the active connection across sessions
Persist the connection id and restore it later.
Originally I was going to implement something similar to `canAutoConnect` but just persisting the current connection is simpler and more user-friendly for the case of expired connections
> feat(auth): persist active connection and add more docs

- src/shared/credentials/userCredentialsUtils.ts
- src/test/shared/credentials/userCredentialsUtils.test.ts
- Currently the way we find existing credential filenames is by seeing if a few keys are in the credentials document. This isn't really robust and breaks down for different profile types.
- Re-use the sharedCredentialsProvider to provide validation when trying to find existing credential filenames. This will ensure that if we find a credentials file, it has at least one valid profile name
> fix(credentials): Make finding existing credential filenames more robust

- .eslintignore
- .eslintrc.js
- src/codewhisperer/activation.ts
- src/codewhisperer/commands/invokeRecommendation.ts
- src/codewhisperer/commands/startSecurityScan.ts
- src/codewhisperer/service/diagnosticsProvider.ts
- src/codewhisperer/service/inlineCompletion.ts
- src/codewhisperer/service/inlineCompletionService.ts
- src/codewhisperer/service/keyStrokeHandler.ts
- src/codewhisperer/service/recommendationHandler.ts
- src/codewhisperer/service/referenceLogViewProvider.ts
- src/codewhisperer/service/securityScanHandler.ts
- src/codewhisperer/tracker/codewhispererCodeCoverageTracker.ts
- src/codewhisperer/tracker/codewhispererTracker.ts
- src/codewhisperer/util/dependencyGraph/dependencyGraph.ts
- src/codewhisperer/util/dependencyGraph/javaDependencyGraph.ts
- src/codewhisperer/util/dependencyGraph/pythonDependencyGraph.ts
- src/codewhisperer/views/securityPanelViewProvider.ts
- src/eventSchemas/commands/downloadSchemaItemCode.ts
- src/shared/filesystemUtilities.ts
- src/test/codewhisperer/tracker/codewhispererCodeCoverageTracker.test.ts
Control flow statements are inconsistently formatted, e.g. there is some code like this:
if (this._timer !== undefined) return
Configure eslint to enforce braces:
if (this._timer !== undefined) {
return
}
> build: eslint "curly" rule

- src/shared/resourcefetcher/httpResourceFetcher.ts
- src/shared/schemas.ts
- src/test/shared/resourceFetcher/httpResourceFetcher.test.ts
- Currently you need to configure the buildspec schema location through a setting
- Use the hosted files cloudfront distribution for getting the buildspec schema
> Use hosted files for buildspec schema

- src/credentials/auth.ts
- src/credentials/awsCredentialsStatusBarItem.ts
* Statusbar should be in an error state for expired credentials 
* Signout out of IAM connection puts users in a fully logged-out state
* Update statusbar color depending on connection state
* Use different color in dev mode 
* Fallback to an SSO connection when signing out of an IAM connection
> fix(auth): update status bar color; use SSO connection as a fallback

- src/credentials/auth.ts
Connections are created _before_ the user finishes the auth flow. This can be confusing because the connections aren't marked as 'pending'. 
Don't persist the connection until we get a token.
> fix(auth): ensure token exists before persisting connection

- src/credentials/auth.ts
- src/credentials/loginManager.ts
- src/credentials/sso/ssoAccessTokenProvider.ts
- src/extension.ts
- src/shared/extensionGlobals.ts
- src/test/credentials/sso/ssoAccessTokenProvider.test.ts
* `invalidate` doesn't drop the cached registration
* Users can switch to invalid static credentials
* Use `LoginManager` to validate profiles
* Update `invalidate`
> fix(auth): more improvements

- src/credentials/auth.ts
- src/credentials/secondaryAuth.ts
* No "Edit Credentials" button when switching connections
* Persisting connections is not cohesive
* Add "Edit Credentials" button
* Add `SecondaryAuth` class (dead code)
> feat(auth): add `SecondaryAuth`

- src/extension.ts
No telemetry for when experiments are enabled/disabled
Emit events when experiments change. The settings key is used directly as the experiment ID.
> feat(telemetry): instrument experimental flags

- src/credentials/sso/ssoAccessTokenProvider.ts
Unit tests would sporadically fail due
to cache not being cleared when expected.
Certain methods called async clear() without
waiting, and the checks in the test executed before the clear() could complete.
Example test is `"drops expired tokens if failure was a client-fault"`
where `sut.getToken()` > `await this.refreshToken(data.token, data.registration)` > `this.cache.token.clear(this.tokenCacheKey)`
Add 'await' to the impacted clear() calls.
> fix(tests): sso token cache race condition

- src/shared/sam/sync.ts
`templates.json` still exists and is probably being used. The new experience doesn't support it.
Read from `templates.json` if it exists and add the overrides to the command. Also, we record a telemetry attribute so we can track legacy usage.
> fix(samcli): support legacy `templates.json` parameter overrides

- .changes/next-release/Feature-ddf9caaa-fa93-4d67-bd4c-817447ae6e68.json
- package.json
- scripts/build/generateIcons.ts
- src/awsexplorer/regionNode.ts
- src/extension.ts
Schemas feature of AWS Explorer not available in Cloud9.
Enable it.
> feat(explorer): enable EventBridge Schemas in Cloud9

- .changes/next-release/Feature-f5541d37-7638-4d1c-9347-fb565b379973.json
- package-lock.json
- src/codecatalyst/auth.ts
- src/codecatalyst/commands.ts
- src/codecatalyst/reconnect.ts
Users trying to use CodeCatalyst features might not have an AWS Builder ID connection configured yet. This especially affects users coming from https://codecatalyst.aws
Make it easier to set up a connection by asking the user to create/upgrade one.
> feat(codecatalyst): guide users to connect if not already connected

- CONTRIBUTING.md
- scripts/build/package.ts
- src/dev/activation.ts
- src/dev/beta.ts
- src/dev/config.ts
- src/shared/settings.ts
- src/shared/telemetry/vscodeTelemetry.json
- src/shared/utilities/tsUtils.ts
We have no easy way to share beta builds with users
Add codepath to download artifact from a URL. The user is prompted to install the new artifact if it is different from the currently installed extension.
**This codepath is never accessible in a release version**
~The dev setting `aws.dev.betaUrl` can be used to test this logic assuming the currently installed VSIX is a pre-release~
Only `src/dev/config.ts` is used to specify the beta URL to ensure that this behavior is dependent on compilation.
A 'config' file has been added to specify development constants. Keeping this as a separate file makes it easier to catch potential leaks and clean the git history of possibly sensitive information. If `betaUrl` is specified then the VSIX will be built with an artificially high version to stop …
> feat(dev): add logic to download beta artifacts from a URL

- src/test/shared/wizards/wizardTestUtils.ts
The wizard tester is too rigid. `assertValue` always does a strict equal which doesn't work well for non-primitive types.
See https://github.com/aws/aws-toolkit-vscode/pull/3043
Expose a `value` field so callers can make their own assertions.
Example usage:
```ts
assert.strictEqual(tester.someUriField.value?.fsPath, expectedUri.fsPath)
```
> tests: add `value` to wizard tester

- CONTRIBUTING.md
- docs/vscode-config.md
We need documentation on how to configure VSCode settings in a project that external users/our team can look at
Add documentation for `settings.json`, `tasks.json`, `launch.json` and `extensions.json`
> feat(docs): Add documentation for configuring VSCode settings in a project

- src/shared/buildspec/activation.ts
- Currently the buildspec template is pretty bare and technically invalid according to the schema
- Introduce the install phase and commands to the buildspec template to make it valid
> fix(buildspec): Add install phase into buildspec template

- src/codewhisperer/activation.ts
- src/codewhisperer/models/constants.ts
Fixes variable assignment error and moves warning message last seen timestamp so that timestamp is saved regardless of user action on popup.
> codewhisperer: fix var assign error and move timestamp save

- .changes/next-release/Feature-8cc2b8d7-860e-455e-aa73-01481d00f74c.json
- src/extension.ts
- src/shared/awsFiletypes.ts
- src/shared/extensions/yamlActivation.ts
- src/shared/sam/activation.ts
- Currently our yaml activation doesn't check for buildspec or devfiles so users may not be exposed to those features if they don't already have VSCode-YAML installed
- Prompt for YAML extension activation on buildspec and devfiles. The only differences in this implementation is that we now watch on multiple different filenames and we also use the cfn/buildspec registry to determine if the prompt should activate
> feat(filetypes): Prompt users to install YAML extension for Buildspec and Devfiles

- .changes/next-release/Bug Fix-7b9e7b89-463b-444d-99f3-d3f19d921dc2.json
- .changes/next-release/Bug Fix-8cd5b4be-7da7-4c7b-982e-1d828f2387cc.json
- package-lock.json
- src/s3/commands/uploadFile.ts
- src/s3/explorer/s3BucketNode.ts
- src/s3/explorer/s3FolderNode.ts
- src/s3/fileViewerManager.ts
- src/shared/clients/s3Client.ts
- src/test/s3/util/fileViewerManager.test.ts
- src/test/shared/clients/defaultS3Client.test.ts
* Uploading files from the file editor overwrites the existing content type
* #3055
* Non-text files without a file extension throw an error
* Shift the `ContentType` parameter up so callers have to be explicit
* Treat files with no mime type as binary files
I also refactored `fileViewerManager.ts` a bit so it could be tested with significantly less mocks
> fix(s3): handle content types more gracefully

- .changes/next-release/Bug Fix-108e77f0-4ffa-4c67-9032-62f334fc84c7.json
- src/shared/regions/endpointsProvider.ts
- src/test/shared/regions/endpointsProvider.test.ts
`endpointsProvider.ts` is not using the remote endpoints file
Rearrange the logic and add a test
* `endpointsProvider.ts` is still flawed in that it never caches the remote manifest. **This PR is not a complete solution.**
* We should consider replacing our custom endpoints solution with public parameters: https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-public-parameters-global-infrastructure.html
> fix(regions): prefer remote source over local source

- package-lock.json
bumps json5 to the latest version
> build(deps): json5 from 1.0.1 to 1.0.2 and json5 from 2.2.0 to 2.2.3

- src/shared/sam/cli/samCliInvokerUtils.ts
- src/test/shared/sam/cli/samCliInvokerUtils.test.ts
The sam cli may fail when executing operations
internally. An example is trying to debug a
lambda using python, but a specific python
version does not exist.
This commit now has the sam cli invoker collect
accepted errors (based off certain prefixes)
and throws them instead of indicating
'no message available'
You can test this by:
- Running the 'Extenstion' debugger
- Creating a python3.7 SAM lambda application
- Run and debug the lambda function
- This will induce an error telling you it could not find the python3.7 runtime (assuming you don't have it locally)
> feat(sam): collect sam cli errors

- src/dynamicResources/awsResourceManager.ts
- src/shared/buildspec/registry.ts
- src/shared/extensions/yaml.ts
- src/shared/extensions/yamlService.ts
- src/shared/fs/devfileRegistry.ts
- src/shared/fs/templateRegistry.ts
- src/shared/schemas.ts
- src/test/shared/schemas.test.ts
- We currently have a concept of ownership in the template registry where a registry can declare that they "own" a uri. This is too fragile to work in practice and comes with too many edge cases (what happens if the owner isnt defined, etc, etc). This can lead to issues where the schema isn't getting correctly define for valid aws filetypes
- Allow any template registry that defines a registry name to add a schema to a file uri. Then, when potential schemas are being evaluated use the first one that is defined. Since cfn/sam/buildspec are all distinct, we won't have any issues of them accidentally recognizing files that they shouldn't and it simplies the problem a lot
> fix(schemas): Improve template registry ownership model 

- src/cloudWatchLogs/registry/logDataRegistry.ts
- src/test/cloudWatchLogs/registry/logDataRegistry.test.ts
- src/test/cloudWatchLogs/utils.test.ts
Sometimes the results from cwl API return empty, with a `nextToken`. We don't account for this case. 
Implement `getPaginatedAwsCallIter` in order to handle this case. 
**Note**: This is an addition to #2839 since it was not completed due to a failing unit test. This unit test is now resolved along with some other minor changes.
> cwl: Fix bug where empty results are returned with valid nextToken

- src/codewhisperer/service/inlineCompletionService.ts
Reject userDecision event is misreported as Discard in below case:
When user saw a recommendation and keeps typing recommendation that does not match the prefix, the recommendation should be reported as Reject instead of Discard.
No changelog item is needed because this fix is not customer facing.
This fix is verified against below test cases:
Test case 1: Accept a recommendation with no typeahead. Expect to see Accept, Unseen/Ignore (Depending on 2nd reco is seen or not) 
Test case 2: Reject a recommendation with no typeahead. Expect to see Reject, Unseen
Test case 3: Create typeahead not matching response before response arrives, continue typing, expect to see Discard, Unseen
Test case 4: Create typeahead not matching response after response arrives, continue typing, expect to see …
> fix(codewhisperer): Fix reject userDecision event reported as Discard

- package-lock.json
- package.json
- src/codewhisperer/client/codewhisperer.ts
- src/codewhisperer/commands/invokeRecommendation.ts
- src/codewhisperer/service/inlineCompletionService.ts
- src/codewhisperer/service/keyStrokeHandler.ts
- src/codewhisperer/service/recommendationHandler.ts
- src/codewhisperer/util/telemetryHelper.ts
Adding a new telemetry : Client component latency for codewhisperer.
This telemetry's definition in https://github.com/aws/aws-toolkit-common/commit/618a9fb1585d0e7131901a9c4f3ac60ff4a3111f. 
A client component latency metric is emitted only once for each complete GenerationRecommendation pagination session if the suggestion is shown to the user.
```
{
"name": "codewhispererFirstCompletionLatency",
"type": "double",
"description": "The time it takes for the response to be received after the plugin makes a first GenerateCompletions API call."
},
{
"name": "codewhispererEndToEndLatency",
"type": "double",
"description": "The time it takes for the first completion to be shown in the IDE after the user performs the CW trigger action."
},
{
"name": "codewhispererAllCompletionsLatency",
"type": …
```
> feat(codewhisperer): Add Client component latency telemetry

- src/shared/extensions/yamlActivation.ts
This was a UX suggestion from Jo
- install YAML extension text should be more clear about what installing the extension does and why users should install it
- Update the install the YAML extension text to say what installing the extension actually does
> ux(yaml): Improve install YAML extension prompt message

- scripts/build/generateIcons.ts
Running the script on different platforms creates noise
Normalize the emitted path
> fix(icons): normalize font path regardless of platform

- .changes/next-release/Bug Fix-3e26f9c4-6479-4c79-8849-400914f3da90.json
- src/shared/clients/iamClient.ts
- src/test/shared/clients/iamClient.test.ts
Some Organization SCP policies cannot be property evaluated by SimulatePrincipalPolicy and result in false negative results.  It is best to ignore actions denied from Organization during SimulatePrincipalPolicy.
It is a [known problem ](https://github.com/aws/aws-sdk/issues/102) that some organization SCP policies cannot be simulated correctly by SimulatePrincipalPolicy.  This results in permission errors when no permission errors exist.
```
[ERROR]: aws.ecs.openTaskInTerminal: Error: Insufficient permissions to execute command. Configure a task role as described in the documentation. [MissingPermissions] (deniedActions: ssmmessages:CreateControlChannel,ssmmessages:CreateDataChannel,ssmmessages:OpenControlChannel,ssmmessages:OpenDataChannel)
```
Ignore denial from Organizations.
By …
> fix(iam): getDeniedActions returns false deny with organization SCP

- src/shared/ui/inputPrompter.ts
Problem:
`this.validateEvents` is passed as the `thisArgs` parameter.
Solution:
pass `undefined` to `thisArgs` parameter, pass `this.validateEvents` to `disposables` parameter.
> fix(inputPrompter): misplaced disposables argument

- .changes/next-release/Feature-46a93a97-f979-4c7a-9a8d-f241a30987b6.json
- src/shared/sam/activation.ts
- src/shared/sam/debugger/awsSamDebugger.ts
- src/shared/sam/debugger/typescriptSamDebug.ts
- src/shared/sam/localLambdaRunner.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
TypeScript debugger has a race condition that breaks debugging much of the time. Hard-coded tsconfig also is used which breaks anything more than a very basic typescript lambda.
Updated toolkit to generate tsconfig that attempts to match project tsconfig as close as possible, code is compiled into a ts build directory, sam deploys from there on an updated handler path (pointing to build dir). This eliminates the debugger race condition, and much more closely resembles a standard project build eliminating all of our errors. It also matches jetbrains approach [here](https://github.com/aws/aws-toolkit-jetbrains/blob/main/jetbrains-ultimate/src/software/aws/toolkits/jetbrains/services/lambda/nodejs/NodeJsLambdaBuilder.kt).
Code updated:
- src/shared/sam/activation.ts: allow typescript code to …
> feat(sam): improved TypeScript support

- src/shared/sam/debugger/typescriptSamDebug.ts
TS "code" configs do not work correctly on Windows. Minor bug from https://github.com/aws/aws-toolkit-vscode/pull/3099
Normalize the handler path
> fix(sam): normalize function handler path for TS 'code' invokes

- .changes/next-release/Bug Fix-5b67cc43-711c-4d49-9cc0-997f73289d83.json
- src/shared/logger/activation.ts
The logging `activate` function has several `fs` calls that could potentially cause issues on activation.
Don't block on non-critical functionality
> fix(logger): prevent module from blocking activation

- src/shared/clients/codecatalystClient.ts
`verifySession` is called every time a new client is created
Cache `verifySession` based off the access token
The way the CodeCatalyst client is written makes it difficult to test in a sustainable way. Something similar to https://github.com/aws/aws-toolkit-vscode/pull/2917 needs to be done to reduce the amount of custom logic in each service client.
> fix(codecatalyst): cache results of `verifySession`

- src/codewhisperer/activation.ts
- src/codewhisperer/commands/basicCommands.ts
- src/codewhisperer/models/constants.ts
to update the error popup shown to users with access code after 1/31 cutoff date based on product decisions
- update the message shown on popup
- add "Don't show again" button
- add "Learn more" button with link to documentation
before:
after:
> fix(codewhisperer): update error popup for access token migration

- .changes/next-release/Bug Fix-9f0b52be-3f38-41eb-92e8-f01a45281441.json
- src/dynamicResources/explorer/nodes/resourcesNode.ts
- src/test/dynamicResources/explorer/moreResourcesNode.test.ts
Duplicate type definitions are not handled (#3132)
Use the most recently updated definition
The CloudFormation service should clarify this behavior in their API documentation. Duplicated, undifferentiated type definitions is unexpected. This may be a bug with the service itself.
> fix(resources): handle duplicate resource type definitions

- src/cloudWatchLogs/document/logDataDocumentProvider.ts
Previously a document highlight on a cwl would
highlight the entire line, even leading whitespace.
The highlighting starts at the
first non whitespace character.
---
Previously, when we did ctrl + hover on a cwl
line in a log stream it would synchronously load
data before returning a definition highlight.
Now we will return the definition highlight immediately
while loading the data async. This should improve
UX slightly.
> cwl: Fix document highlight range + async content loading

- package.json
"git commit" fails in "PushToGithub" CI job:
.husky/pre-commit: 2: .: cannot open .husky/_/husky.sh: No such file
For now, just remove this npm "prepare" script. This is only wanted for developers, should not be used in CI.
Related: 0abd9199e53e0dbe01f99fe53e4510cf03f41056
> fix(ci): "git commit" fails in CI jobs

- .changes/next-release/Feature-3082756c-79f7-4341-88be-d2f583a93686.json
- src/cloudWatchLogs/explorer/logGroupNode.ts
Problem: There is only a single action associated with CW log groups and it is only available through the context menu.
Solution: Execute the view log stream selector when the log group node is selected.
Currently the toolkit requires the user to right-click and then choose `View Log Stream` to start the selection prompt. 
Start the prompt immediately when the node is left-clicked.
> cwl: single-click on log group shows stream select

- .changes/next-release/Bug Fix-19fd655d-6194-4ec1-954a-1a0124a8de36.json
- package-lock.json
- package.json
Customers are not able to validate their state machines definition with new intrinsic functions and new Map state attributes. This behaviour is not consistent with the launch of the new distributed Map state, and new intrinsic functions
https://github.com/aws/amazon-states-language-service/pull/90 and https://github.com/aws/amazon-states-language-service/pull/86 added validation for both distributed Map fields and new intrinsic functions. Bumping the package version to `^1.8.0` to pull in this change.
Confirmed that Map field values and new intrinsic functions were correctly validated when creating a new state machine, when bumping the version to `^1.8.0`.
> Bump amazon-states-language-service dependency to ^1.8.0

- src/codewhisperer/service/recommendationHandler.ts
We are currently sending empty user_decision events when invocation failed(connection expired, etc.)
Only send empty user decision when the invocation was successful
> fix(codewhisperer): only send user decision when invocation succeeded

- src/shared/awsClientBuilder.ts
- src/shared/sam/cli/samCliInvoker.ts
- src/shared/sam/cli/samCliInvokerUtils.ts
- src/shared/sam/cli/samCliLocalInvoke.ts
- src/shared/sam/sync.ts
- src/shared/telemetry/util.ts
- src/test/shared/sam/cli/samCliInvokerUtils.test.ts
- src/test/shared/telemetry/util.test.ts
SAM CLI doesn't know which products are executing it on the user's behalf
Add an environment variable containing additional context
> telemetry: add UA environment variable to SAM CLI invocations

- src/cloudWatchLogs/activation.ts
- src/cloudWatchLogs/commands/searchLogGroup.ts
- src/cloudWatchLogs/document/logDataDocumentProvider.ts
- src/cloudWatchLogs/document/logStreamsCodeLensProvider.ts
- src/cloudWatchLogs/document/textContent.ts
- src/test/cloudWatchLogs/document/logDataDocumentProvider.test.ts
- src/test/cloudWatchLogs/document/logStreamsCodeLensProvider.test.ts
Previously, we used an inefficient implementation of Go To Definition (Ctrl + Click) to go to
open a specific Log Stream document from a document that had many Log Streams.
It was inefficient since we could not lazily load the Go To Definition objects and
it caused performance issues due to Go To Definition pre-loading pages
as the user hovered over the lines while holding Ctrl.
Additionally it was not obvious that we had this functionality available.
- Drop the Go To Definition feature
- Replace it with Code Lenses that will appear at the beginning of
each Log Stream. When clicked they will load the specific events
of that log stream and open a new document
1. Open the AWS Explorer
2. Drop down `CloudWatch Logs`
3. Right click one of them and select `Search Log Group`
4. Once fully …
> CWL: Code lenses on 'Search Log Stream' document

- src/cloudWatchLogs/changeLogSearch.ts
- src/cloudWatchLogs/commands/addLogEvents.ts
- src/cloudWatchLogs/commands/searchLogGroup.ts
- src/cloudWatchLogs/commands/viewLogStream.ts
- src/cloudWatchLogs/registry/logDataRegistry.ts
- src/cloudWatchLogs/timeFilterSubmenu.ts
- src/eventSchemas/providers/schemasDataProvider.ts
- src/shared/extensionUtilities.ts
- src/shared/ui/common/regionSubmenu.ts
- src/shared/ui/inputPrompter.ts
- src/shared/ui/picker.ts
- src/test/cloudWatchLogs/commands/searchLogGroup.test.ts
- src/test/shared/ui/inputPrompter.test.ts
The "filter pattern" step is not validated until after the wizard closes, so customer must start the wizard again if CloudWatch logs API rejects the filter (search) pattern.
Because of current limitations of vscode and/or our Wizard framework, we can't dynamically make a service call because _async_ `onDidAccept` event handler is not await'd.
- Change "Search Pattern" step to be the last step.
- Use a workaround similar to:
https://github.com/aws/aws-toolkit-vscode/blob/183dd3ae4bf14196962c242e9236092ae509e3b0/src/credentials/wizards/createProfile.ts#L69-L104
- Subclass `InputBoxPrompter`
- Override `promptUser()`. If validation fails,
- return `WIZARD_RETRY`
- restore state in a hacky way (the `retryState` object)
By submitting this pull request, I confirm that my contribution is made …
> cwl: validate search input

- src/test/globalSetup.test.ts
- src/test/shared/vscode/message.ts
- src/test/shared/vscode/window.ts
It's not always clear why tests hang and timeout. 
Print pending UI elements before stopping the test. This is a more general solution over requiring tests to specify all responses up-front which is also viable.
Example:
> tests: print debugging info when timing out

- src/cloudWatchLogs/registry/logDataRegistry.ts
- src/dev/codecatalyst.ts
- src/shared/utilities/messages.ts
- src/shared/utilities/timeoutUtils.ts
- src/test/shared/utilities/messages.test.ts
Problem:
Search pattern is validated by making a service call 45cba189e6fe. This triggers the "Searching..." progress dialog, which is noisy.
Solution:
Don't show the "Searching..." progress dialog until after ~1 second.
> fix(cwl): avoid Progress message while validating search input

- src/codewhisperer/service/inlineCompletionService.ts
user will sometimes see recommendations disappear and show up again in 1-2 seconds
don't call getPaginatedRecommendations if current recommendations are still being displayed
> fix(codewhisperer): do not clear recommendation if it is visible

- src/cloudWatchLogs/document/logStreamsCodeLensProvider.ts
- src/cloudWatchLogs/explorer/logGroupNode.ts
vscode error when clicking a CWL Log Group:
Converting circular structure to JSON --> starting at object with
constructor 'LogGroupNode' | property 'command' -> object with
constructor 'Object' | property 'arguments' -> object with constructor
'Array' --- index 0 closes the circle
Fix the command id.
> fix(cwl): "circular JSON" error when clicking Log Group

- src/cloudWatchLogs/commands/searchLogGroup.ts
- src/cloudWatchLogs/commands/viewLogStream.ts
- src/cloudWatchLogs/document/logDataCodeLensProvider.ts
- src/cloudWatchLogs/registry/logDataRegistry.ts
- src/shared/utilities/messages.ts
- src/shared/vscode/window.ts
- src/test/cloudWatchLogs/registry/logDataRegistry.test.ts
When using the load new events codelens on a non-filtered
log stream, we would get stuck in an endless loading loop.
When loading a non-filtered logstream, explicitly using
the GetLogEvents api, we assumed that there were
no more results if the next token was undefined.
The problem with this is that the GetLogEvents
api returns the SAME token if there are no more
results. This mistake was made since the
FilterLogEvents api does return undefined if there are no more results.
Handle the scenario where the same token is returned and convert the result of the function that uses it in to undefined. We need to do this since the rest of the code expects the token to be undefined if
there are no more results.
On a Log Group in the explorer, choose 'View Log Stream' and select a random one. Then …
> fix(cwl): loading new log stream stuck in loop

- .changes/next-release/Bug Fix-b901b228-a954-413d-a9c5-b47c61ec5799.json
- .changes/next-release/Feature-6c58a802-1a1a-4819-bb6b-b95e66145a4c.json
- src/codecatalyst/explorer.ts
- src/codecatalyst/reconnect.ts
- src/credentials/auth.ts
- src/credentials/providers/sharedCredentialsProvider.ts
- src/credentials/sso/clients.ts
- src/credentials/sso/ssoAccessTokenProvider.ts
- src/test/credentials/auth.test.ts
- src/test/credentials/sso/ssoAccessTokenProvider.test.ts
* It's not always obvious that the extension is waiting for the user to login
* Some CodeCatalyst logic doesn't check for 'valid' connections prior to using them, creating noise
* The "Copy Code" modal is sometimes shown twice when refreshing expired builder ID connections
* Restrict connections to 1 re-auth flow at a time
* Add some extra checks in CC logic to reduce noise
* Show a progress notification while the user is connecting via the browser
> feat(auth): several UX improvements for browser login flows

- package.json
AWS Toolkit does not appear in VS marketplace searches for "Code Whisperer" (as opposed to "CodeWhisperer"). VS marketplace limits us to 5 keywords.
Replace other keywords with "Code" and "Whisperer".
> marketplace: add "Code" and "Whisperer" keywords

- src/codecatalyst/auth.ts
- src/codecatalyst/commands.ts
- src/integrationTest/codecatalyst/client.test.ts
We want to ensure that Code Catalyst apis work as expected. If only we had
integration tests that could do this.
This commit creates integ tests that test the CC APIs
this extension uses:
- creating a cc project
- creating a cc dev env
- connecting to the dev env through ssh
One thing to note is that the builderid/sso
configuration is required to be setup prior
to this test running (this test will fail until that
component is implemented in our CI, but is
being worked on separately).
> test: Add code catalyst integ test

- src/credentials/sso/ssoAccessTokenProvider.ts
New name is "AWS Toolkit for VSCode"
BuilderID setup webpage:
> auth(IDE-10230): Change OIDC client name to something nicer

- src/extension.ts
- src/integrationTest/schema/schema.test.ts
- src/shared/schemas.ts
- src/test/shared/schemas.test.ts
Problem:
Test fails in CI because of unpredictable telemetry and extension activation.
Solution:
- In test 1: assert telemetry from extension activation.
- In test 2: clear telemetry.
> test(integ): fix getDefaultSchemas()

- .github/workflows/node.js.yml
Hi! 👋🏻
Several of the Github Actions in the repo are using the deprecated Node.js 12 runtime. Github have announced that everyone should move away from the deprecated Node.js runtime as of [this](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) blogpost.
I've upgraded the deprecated actions to versions that uses non-deprecated runtimes.
Open to feedback if there are any other changes wanted done regarding Github Actions 😄
> chore(ci): Upgrade workflows to non-deprecated runtimes

- .github/dependabot.yml
GHA workflows themselves can be auto-updated via dependabot.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
> CI: enable dependabot for GHA workflows

- src/shared/clients/codecatalystClient.ts
- src/shared/utilities/asyncCollection.ts
- src/shared/utilities/collectionUtils.ts
- src/test/shared/utilities/asyncCollection.test.ts
- src/test/shared/utilities/collectionUtils.test.ts
It's difficult to orchestrate paginated API calls
* Add some extra utility functions combine multiple async iterables into a single iterable
* Modified CodeCatalyst to use `joinAll` when listing resources
* Minor improvements to `asyncCollection.ts`
> utils: add more functions for working with async iterables

- .changes/next-release/Bug Fix-9d690880-88ff-4125-859c-22dcc094aa84.json
- package-lock.json
- package.json
v1.9.0 of amazon-states-language-service fixes #3068.
This new release allows newlines in Step Functions Intrinsic Functions.
> build(stepfunctions): amazon-states-language-service 1.8.0->1.9.0

- src/codewhisperer/service/inlineCompletionService.ts
the total number of recommendations on the visual cue is not correct due to pagination
mitigation to allow the total index to be correct while the long-term fix rely on inline api's support of pagination
https://user-images.githubusercontent.com/60411978/224853441-ecf21063-0f84-4752-934c-03a2593b0e0c.mov
> fix(codewhisperer): update the total recommendation count in visual cue

- src/codewhisperer/service/inlineCompletionService.ts
right context handling currently don't take the typeahead into account, which result in some cases are not handled:
update the start position for right context to be the cursor position and fall back to invocation position
> fix(codewhisperer): bug with right context handling

- .changes/next-release/Bug Fix-611d45b0-5a98-4190-9db0-549d561c2200.json
- src/ecs/commands.ts
Problem:
"Enable Command Execution" and "Disable Command Execution" commands show the wrong message.
Solution:
Flip the logic.
> fix(ecs): "Enable Command Execution" shows wrong message

- src/shared/clients/codecatalystClient.ts
- src/shared/utilities/asyncCollection.ts
- src/test/caws/wizards/selectResource.test.ts
https://github.com/aws/aws-toolkit-vscode/pull/3234 tried to make things more ergonomic by converting async iterables into async collections implicitly. This does work but unfortunately it consumes the iterable and thus cannot be re-used for things like refreshing
* Remove the implicit conversion
* Add regression test
> fix(codecatalyst): fix CC refresh button on some pickers

- .changes/next-release/Bug Fix-10942e31-b4d4-4eb2-8b12-4c792a831e98.json
- .changes/next-release/Feature-e19735b8-3902-4ace-826f-5809bb6e8b7d.json
- src/codewhisperer/commands/onInlineAcceptance.ts
- src/test/codewhisperer/commands/onInlineAcceptance.test.ts
we received user feedback on not wanting CodeWhisperer to format their documents
don't automatically format user's code on acceptance
> feat(codewhisperer): do not format code on acceptance

- .changes/next-release/Bug Fix-3732d82a-1e83-45c8-a5b8-4a927d6e7418.json
- src/shared/clients/codecatalystClient.ts
Problem:
- Connecting to a CodeCatalyst DevEnv sometimes fails.
- After doing "Update" on a connected DevEnv, polling may fail with this service error:
```
[ERROR]: aws.codecatalyst.openDevEnv: [ConflictException: Cannot start Dev Environment because update process is still going on
```
Solution:
- Catch `ConflictException` and continue waiting.
- If the DevEnv transitions from STARTING > STOPPING, wait for STARTING a bit before giving up.
- Log state transitions for visibility: 
```
2023-… [DEBUG]: devenv not started, waiting (time: 18.023 s): 9981abbc-87f6-4c28- / [ STOPPED/4956ms STARTING/11974ms]
...
2023-… [DEBUG]: devenv not started, waiting (time: 41.723 s): 9981abbc-87f6-4c28- / [ STOPPED/4956ms STARTING/35674ms]
2023-… [DEBUG]: devenv not started, waiting (time: 65.485 s): …
```
> fix(codecatalyst): DevEnv connect sometimes fails

- src/codecatalyst/vue/create/backend.ts
- src/codecatalyst/vue/create/source.vue
- src/codecatalyst/wizards/selectResource.ts
When using the Create Dev Env webview we used
a drop down menu to provide all possible Projects.
The problem is that querying all Projects takes time and nothing would show on the screen for a while.
Additionally, if the user had many projects from
multiple spaces it was not easy to find
Instead of a dropdown menu use an async quick pick which will continuously load new Projects as they
are returned in the the paginated query for all Projects.
- Project loading is started immediately upon the webview loading. This will provide Projects quickly when the quick pick menu is opened
- Along with using a quick pick, the user can easily filter the Projects using the quick picks built in filtering mechanism.
- If the user specifically edits a Project, only Projects from the current space will …
> feat(IDE-9298): Dev Env Project Quick Pick selector

- .changes/next-release/Feature-542918a0-d601-4ab2-9b22-7aa04fdd223f.json
- src/credentials/auth.ts
- src/test/credentials/auth.test.ts
When a user is already signed in to their Builder ID, but they want to use a different one, they are not able to use a different ID.
This is confusing since nothing happens when they try to add another one.
When attempting to add a new Builder ID but one already exists, this will prompt the user to choose if they wish to sign out of the existing one, and will then complete the builder id verification process.
> auth: prompt existing builder id signout on new builder id

- .changes/next-release/Bug Fix-c6fcd706-c5dc-4041-9fac-9260bd9994dd.json
- .changes/next-release/Bug Fix-cd02d5c6-a80d-4e99-a1c9-16699843db88.json
- src/codecatalyst/vue/create/backend.ts
- src/codecatalyst/vue/create/source.vue
- src/shared/clients/codecatalystClient.ts
When creating a new Dev Env in the webview, users
have the option to create a new branch name from a
linked repo.
The issue though is we are not able to create a new
branch name for third party (github) repos.
Do not allow input of a new branch name when the selected
branch is from a third party repo.
Fixes IDE-10216
- This allows input from the user only when necessary
- Otherwise input is disabled
- Verifies if new branch is allowed once a user selects
an existing branch
When user selects a 3P repo, they cannot enter a new branch name:
> fix(codecatalyst): Disable new branch name for 3p repo

- src/codecatalyst/vue/create/source.vue
From a recent change we added a quick pick to select a project when creating a dev env.
But the quick pick code was not replicated if you selected "Create an empty Dev Environment",
it was only done "Use an existing CodeCatalyst repository"
Swap the old dropdown menu code with the existing
quick pick code.
Now to new quickpick style of selecting a project will work
> fix(codecatalyst): Create dev env quick pick from empty

- src/s3/activation.ts
- src/test/s3/util/fileViewerManager.test.ts
When the s3 file system provider was registered it was not set to be case sensitive. So paths like
`/aws/Test/temp.json` and `/aws/test/temp.json` were
seen as the same thing.
Set the case sensitive flag when registering the
file system provider so that it will uniquely
identify files with the same text but different
case sensitivity.
Fixes #3276 
Before setting case sensitivity, this line would return an existing text document instead of a new one (that had a different case). It was the hint that VSCode was handling it different from our expectations.
https://github.com/aws/aws-toolkit-vscode/blob/3a22329dbc6d1eb819a65ea6ef84599f24d2cb48/src/s3/fileViewerManager.ts#L171
> fix(s3): file system provider is not case-sensitive

- src/codecatalyst/vue/create/source.vue
When there was an existing branch with a very long name, the width of the input box would mess up the UI.
Fix how the widths work for the branch selectiong/naming input boxes.
Fixes IDE-10388
> fix(codecatalyst): create dev env branch selection width

- src/cloudWatchLogs/changeLogSearch.ts
- src/cloudWatchLogs/timeFilterSubmenu.ts
- src/test/cloudWatchLogs/commands/searchLogGroup.test.ts
To search a CWL log group you must enter a date
range, and an optional string to filter the
event text.
Once openend there are buttons in the editor/title that are the calendar and magnifying glass.
If you click on one of these you can re-adjust their value through a quickpick/input prompter.
The problem is that users cannot see what they previously selected, it is not that good for UX
When the user attempts to re-adjust their previous selection, autofill the previous values in the prompter so they can see what they previously chose.
Notice how `Last 12 Hours` and `Hello` are autofilled once I go to re-adjust the values.
Fixes IDE-8248
> feat(cwl): Remember previous selection for search/filter

- .changes/next-release/Bug Fix-132bdce0-d348-4c2b-bb87-5630a54a22d4.json
- src/codecatalyst/vue/create/backend.ts
- src/codecatalyst/vue/create/source.vue
- src/testE2E/codecatalyst/client.test.ts
When selecting a Space while creating a Dev Env, the user sees a quick pick of all Spaces + Projects.
When the user selects a Space, show only the Space names.
- The Project is disabled until a Space is chosen
- Upon initial loading of the webview, Space names are pre-loaded
- Upon selection of a Space, Projects are pre-loaded before the user clicks the 'edit' icon on a Project
> fix(codecatalyst): Dev Env Space quick pick shows all Spaces + Projects

- CONTRIBUTING.md
- src/shared/constants.ts
- src/shared/logger/activation.ts
- src/shared/settings.ts
- src/shared/utilities/pathUtils.ts
Problem:
vscode always changes the logfile location, so following it with "tail -F" is not easy.
Solution:
Introduce setting "aws.dev.logfile" which sets a fixed logfile path.
> dev: custom logfile path

- .changes/next-release/Bug Fix-caeb3b17-655d-42e1-b76d-2bb417794228.json
- package-lock.json
- package.json
- src/awsexplorer/localExplorer.ts
- src/credentials/statusBarItem.ts
- src/shared/settings.ts
- src/shared/utilities/functionUtils.ts
- src/shared/utilities/timeoutUtils.ts
- src/test/shared/settingsConfiguration.test.ts
- src/test/shared/utilities/functionUtils.test.ts
- src/test/shared/utilities/timeoutUtils.test.ts
- src/test/utilities/testSettingsConfiguration.ts
Calling `DevSettings.instance.get('endpoints', {})` always treats `endpoints` as being an enabled setting. This would enable 'dev mode' despite no explicit setting being present.
Remove the fragile reference comparison for trapping settings. Explicitly check for set values instead.
Other changes:
* Small refactor on the status bar item to make it more robust
* Dev settings that have been unset can now be detected
* Move `throttle` so it can be re-used; add tests (TODO: remove `lodash`)
* Had to bump `@sinonjs/faketimers` to make one test work w/ fake timers. It'd work without fakes but might be flaky.
> fix(settings): `endpoints` is incorrectly trapped by `DevSettings`

- .changes/next-release/Bug Fix-5ec947ce-d7aa-439a-b77c-110a309bcc00.json
- src/codecatalyst/activation.ts
- src/codecatalyst/devfile.ts
- src/codecatalyst/explorer.ts
- src/codecatalyst/model.ts
- src/codecatalyst/reconnect.ts
- src/codecatalyst/utils.ts
- src/codecatalyst/wizards/selectResource.ts
- src/shared/clients/devenvClient.ts
Problem:
If customer changed the "IDE runtime" (in the CodeCatalyst console), AWS Toolkit will attempt to reconnect to the Dev Environment, which is inconsistent with other IDEs (jetbrains, cloud9).
Solution:
Check the `ides` field on connect. Disconnect if the ide runtime is not "vscode".
> fix(codecatalyst): disallow non-vscode Dev Environment

- src/extension.ts
- src/shared/clients/codecatalystClient.ts
- src/shared/errors.ts
- src/test/shared/errors.test.ts
The following issue was started due to a change needed for Velox, but this will be able to apply to all AWS services.
When certain exceptions are thrown by AWS services we want them to be displayed directly to the user in a vscode window.
Currently we only display `ToolkitError`s to the user, otherwise only logging the error to the logs.
There are some AWS errors that we want to show to the user, but on top of that AWS errors can be wrapped inside a Toolkit error.
When deciding which error message to show to users:
- Show the exact error message if it is an AWS error and is in our defined list of 'prioritizied' errors.
- If we get a Toolkit error, check if it wraps a prioritized error, extract it, then display that.
- Previously when MDE threw a `ServiceQuotaExceededException` we wrapped …
> fix(codecatalyst): dev env error messages not being displayed

- buildspec/linuxE2ETests.yml
- package.json
- scripts/test/launchTestUtilities.ts
- src/codecatalyst/tools.ts
- src/integrationTest/globalSetup.test.ts
- src/integrationTest/sam.test.ts
- src/shared/extensions.ts
- src/shared/sam/activation.ts
- src/shared/systemUtilities.ts
- src/test/globalSetup.test.ts
- src/test/setupUtil.ts
- src/test/shared/vscode/statusbar.ts
- src/test/testRunner.ts
- src/testE2E/codecatalyst/client.test.ts
E2E tests must be ran manually
Run them automatically through CodeBuild
> tests: hook up E2E tests to CI

- src/shared/awsClientBuilder.ts
- src/shared/sam/cli/samCliInvokerUtils.ts
- src/shared/telemetry/util.ts
- src/test/shared/sam/cli/samCliInvokerUtils.test.ts
- src/test/shared/telemetry/util.test.ts
The name `SAM_CLI_TELEMETRY_FROM_IDE` is too specific. We're also sending more than what SAM CLI expects.
Use `AWS_TOOLING_USER_AGENT` instead and remove extraneous pairs
> telemetry: update SAM CLI UA env var to something more generic

- src/codecatalyst/tools.ts
- src/shared/extensions.ts
- src/shared/utilities/vsCodeUtils.ts
- src/test/shared/utilities/vscodeUtils.test.ts
- src/testE2E/codecatalyst/client.test.ts
When a user attempted to start a dev env, it failed since the ssh extension version was too old.
Enforce a minumum version of the ssh extension.
If the version is unsupported we will notify the user through an error message.
This solution can be used by any future extension
as well.
> fix(codecatalyst): Notify ssh extension min version required

- src/codecatalyst/commands.ts
- src/credentials/auth.ts
- src/shared/errors.ts
When using an MDE + CodeCatalyst, if the BuilderId connection became expired, on attempts to use the CodeCatalyst client users would get an error 'Connection is invalid...' with no obvious way to resolve it.
Provide the user the ability to re-authenticate their BuilderId.
This commit verifies the BuilderId connection is valid before setting up the CodeCatalyst client. If it is not valid, users will be prompted to login again. They can click the login button on a pop up window, and be redirected through the BuilderId authentication process again.
> fix(codecatalyst): No solution for 'connection is invalid or expired'

- src/credentials/auth.ts
- src/credentials/providers/sharedCredentialsProvider.ts
- src/test/credentials/auth.test.ts
* Builder ID profiles are showing in the connection picker
* Users can rarely be left in a bad auth state
* Hide builder ID profiles 
* Clean profiles left in a bad state on reload
* Free invalid credentials lock after reauth
> fix(auth): address several edge-cases

- .changes/next-release/Bug Fix-a401606f-1768-452b-967b-ba24fc834b27.json
- package.json
- resources/css/base.css
- scripts/build/generateIcons.ts
- src/codecatalyst/vue/create/source.vue
- src/codecatalyst/vue/summary.vue
With the current implementation we write to a certain
unicode range which intentionally offsets the alignment
of the unicode character.
Use the safe range starting a 0xE000-0xF8FF.
- VSCode unicode characters will be in the 0xF000 range
- Other unicode characters will be in the 0xE000 range
Due to this we shouldn't have a collision
> fix(icon): change custom unicode range

- src/codecatalyst/activation.ts
Problem:
Since eb380556b6b4, Toolkit actively exits if the CC devenv is not a "vscode" devenv. But this is incorrect when running in the context of a Cloud9 devenv.
NOTE: `executeCommand('workbench.action.remote.close')` has no effect in Cloud9, but this the code should be corrected anyway.
Solution:
Skip the condition in Cloud9.
> fix(codecatalyst): do not force-close workspace in Cloud9 devenv

- package.json
- package.nls.json
- src/credentials/activation.ts
- src/credentials/commands.ts
- src/credentials/vue/index.ts
- src/credentials/vue/root.vue
- src/credentials/vue/show.ts
- src/shared/vscode/commands2.ts
We want to create a webview for Auth setup
This PR does the following:
- Creates a vscode command which can be executed in the command palette to open the webview
- Sets up the initial code for a webview to be shown
The actual content will be added in future commits
Fixes IDE-10461
> auth: Setup initial Auth Add Connections webview

- src/codewhisperer/service/inlineCompletionService.ts
Before:
https://user-images.githubusercontent.com/89420755/232974964-86bba1d9-115e-4fe4-b0cf-bc027d691257.mov
After:
https://user-images.githubusercontent.com/89420755/232974953-bded8844-5998-460d-bcea-ea539488a758.mov
> Trigger on a not-yet-saved .ipynb file will no longer open a read-only file

- src/credentials/sso/ssoAccessTokenProvider.ts
> fix(codecatalyst): use 'AWS Cloud9' client name with SSO when in C9

- .changes/next-release/Feature-6b974904-ffc3-46c0-87a8-01ae9bf2370d.json
- src/credentials/auth.ts
- src/credentials/providers/credentials.ts
- src/credentials/providers/credentialsProviderManager.ts
- src/credentials/providers/ssoCredentialsProvider.ts
- src/credentials/sso/clients.ts
- src/shared/utilities/asyncCollection.ts
- src/shared/utilities/tsUtils.ts
- src/test/credentials/auth.test.ts
- src/test/credentials/provider/sharedCredentialsProvider.test.ts
- src/test/credentials/testUtil.ts
Users can add connections to IAM Identity Center but there's no easy way to use them for the AWS explorer.
Automatically discover linked accounts/roles and list them in the connections picker. 
Screenshot is slightly different from the current implementation. The most recent change does not have the `sso:` prefix and uses a generic label for SSO connections instead of the exact name.
> feat(auth): discover accounts/roles linked to IAM Identity Center

- src/codewhisperer/activation.ts
- src/codewhisperer/explorer/codewhispererNode.ts
- src/codewhisperer/service/inlineCompletionService.ts
- src/codewhisperer/util/authUtil.ts
- src/extension.ts
This PR also fixes some other issues:
1. Clear the inlineCompletionState on focus change so that they should still be able to invoke CW when they invoked CW and then switched to another app and switched back.
2. put activateCodeWhipserer() to be before activateAwsExplorer() since the refreshStatusBar() and showReferenceLog() commands are used within activateAwsExplorer() when the connection is changed. These
commands are not registered until activateCodeWhisperer() has been called.
3. Remove unnecessary call to refreshCodeWhisperer(), this only needs to be called when there's a connection change.
Before:
https://user-images.githubusercontent.com/89420755/233482893-7c97b057-043d-4d1c-a761-9112c09eaaa0.mov
After:
https://user-images.githubusercontent.com/89420755/233482649-62aac6cc-2ca5-4016 …
> fix(codewhisperer): auto-connect on vscode startup

- src/testE2E/codecatalyst/client.test.ts
For some reason the cc backend did not receive at
dev env id from our e2e test updateDevEnv api call.
This commit verifies we are giving a dev env id
before sending the api request.
Additional:
We used the variable 'globals' before it could
be properly initialized and due to the order of
execution this variable was accessed before it
could be properly initialized.
To fix this it was moved inside a 'before' block
which will ensure it gets executed AFTER all the
pre-test hooks are run, which includes initializing the global variable
> fix(codecatalyst): e2e test updateDevEnv failing

- .changes/next-release/Bug Fix-816f109a-df92-4584-8ce0-4b9f3095cc7a.json
- scripts/newChange.ts
- src/codewhisperer/util/authUtil.ts
We can't tell if the default connection is expired or not on C9 until after making an API call. So the `reauthenticate` logic in `authUtil.ts` does not work on C9
Remove the check to always force a refresh
> fix(codewhisperer): credentials refresh does not happen on C9

- src/cloudWatchLogs/activation.ts
- src/cloudWatchLogs/commands/searchLogGroup.ts
- src/cloudWatchLogs/commands/viewLogStream.ts
- src/test/cloudWatchLogs/commands/viewLogStream.test.ts
By default when a user clicks on a Log Group in the explorer
they will be shown a quick pick of only Log Streams.
If they want to search the whole Log Group, they have to
exit out of it, right click, then select search log group.
Add a quickpick item as the first item of the Log Stream
selection. This item if chosen will redirect them to the
Search Log Stream quick pick flow.
- When a Log Group is left clicked the user is shown the following:
- If they select the first item they are brought to the following:
> feat(cwl): jump to search log group from log stream quick pick

- src/credentials/sso/ssoAccessTokenProvider.ts
- src/shared/settings.ts
Some users run into obscure service errors that do not surface useful information in the error messages
Report the request ID in telemetry so we can investigate on the service-side
> telemetry(auth): report request IDs when refreshing a token fails

- src/integrationTest/sam.test.ts
integ tests timing out for python3.10 and go1.x for "minimum" job.
bump the required minimum expected by the related vscode extensions.
> fix(ci): update minimum vscode version required by extensions

- buildspec/linuxIntegrationTests.yml
- buildspec/setup-github-token.sh
github timeouts on various requests:
Cloning into '/codebuild/output/src577833252/src/github.com/aws/aws-toolkit-vscode/node_modules/.zzz-awssdk2'...
fatal: unable to access 'https://github.com/aws/aws-sdk-js.git/': Failed to connect to github.com port 443 after 130288 ms: Connection timed out
use a github token for all "git" operations to avoid rate-limiting
> fix(ci): avoid rate-limiting

- src/credentials/sso/cache.ts
- src/test/credentials/sso/ssoAccessTokenProvider.test.ts
- src/test/techdebt.test.ts
At a certain point in time sso tokens became invalid.
We stored those tokens in cache and eventually they will
throw errors to the user when the are attempted to be
refreshed.
When the cache is being setup delete any invalid files.
Invalid files are files that were created before
a certain date.
> fix(auth): invalid sso tokens being loaded

- src/testE2E/codecatalyst/client.test.ts
It was timing out. This increases the timeout period to hopefully have the extension installed in time.
> fix: failing ssh extension install test

- src/codewhisperer/service/recommendationHandler.ts
- src/codewhisperer/util/telemetryHelper.ts
if the next trigger happens before emiting of the prev. user trigger event, the invocation time got reset and the time to first recommendation becomes negative
set the time when we get the response and don't clear the invocation time after emiting
> fix(codewhisperer): fix time to first recommendation telemetry

- src/test/codewhisperer/commands/onAcceptance.test.ts
- src/test/codewhisperer/commands/onInlineAcceptance.test.ts
- src/test/codewhisperer/explorer/codewhispererNode.test.ts
- src/test/codewhisperer/service/recommendationHandler.test.ts
- src/test/codewhisperer/tracker/codewhispererTracker.test.ts
- src/test/codewhisperer/util/telemetryHelper.test.ts
When unit tests are run locally + CW is setup with Builder ID the `credentialStartUrl` value will be defined, this causes unit tests to fail.
To fix it, this change adds to the assertion whatever the current `startUrl` is.
- Additionally, some tests assume that CW connection is not configured automatically. This ensures the connection is not set up and prevents any failures due to the test env.
For more info see sim IDE-10578
> fix(codewhisperer): Fixes some tests that fail when run locally

- .changes/next-release/Bug Fix-d3b72a5f-4c18-47ab-afd9-ad97411e4bc6.json
- src/codewhisperer/commands/basicCommands.ts
- src/codewhisperer/service/inlineCompletionService.ts
when users are not using CWSPR, we shouldn't show the status bar
> fix(codewhisperer): hide status bar if not connected

- src/credentials/vue/ServiceItem.vue
- src/credentials/vue/ServiceItemContent.vue
- src/credentials/vue/root.vue
- We want to create the content box on the right side to eventually put content in to it
- Also if the page shrinks we cannot fit the content box on the right side anymore
- Create the initial structure of the content box on the right side, we will focus on filling in the appropriate content later
- When the page shrinks render the content box under the clicked service item box
Fixes IDE-10510
Fixes IDE-10511
> Right side auth webview

- src/shared/cloudformation/activation.ts
- src/shared/fs/templateRegistry.ts
The cfn registry setup can take a long time if there are a lot of yaml files. This can significantly slow down extension startup.
- Have the registry setup run in the background
- If the user triggers functionality that requires the template registry and it is not yet ready, a progress message will appear on the screen
Testing with: https://github.com/aws/aws-sam-cli
Before: 152 seconds in MDE, 1.6 seconds local
After: 1ms in MDE, <1ms local
If the template registry is accessed before it is done loading a message will appear to the user:
> perf: setup cfn template registry asynchronously

- .github/workflows/node.js.yml
- .vscode/launch.json
- docs/TESTPLAN.md
- package.json
- scripts/lint/testLint.ts
- src/test/gitSecrets.test.ts
- src/testLint/README.md
- src/testLint/eslint.test.ts
- src/testLint/gitSecrets.test.ts
- src/testLint/testUtils.ts
This PR
- Creates a new test directory called `testLint/` which will hold our code linting related tests
- Creates a git-secrets test in `testLint/` which runs `git-secrets` on our codebase
- Creates a eslint test in `testLint/` which runs `eslint` on our codebase
- Adds a new CI job that runs the `testLint/` tests as well as the existing code coverage tests which were running in the regular tests before
- Can run the lint tests with the new `launch.json` command or `npm run lint` from cli
> test: run git-secrets during CI

- .changes/next-release/Bug Fix-141dd557-3cb2-4651-a93e-afdaffca9637.json
- src/shared/systemUtilities.ts
Problem:
"Open CodeCatalyst Dev Environment" fails on flatpak (steamdeck).
Solution:
Prefer the special flatpak path `/app/bin/code`, instead of the $appRoot-relative path inferred from the current vscode process.
> fix(codecatalyst): "Open Dev Environment" fails on flatpak

- src/credentials/auth.ts
- src/credentials/providers/sharedCredentialsProvider.ts
- src/credentials/sharedCredentials.ts
- src/credentials/sharedCredentialsValidation.ts
- src/credentials/types.ts
- src/credentials/wizards/templates.ts
- Refactors some existing auth code
- Adds a new sharedCredentialsValidation class which centralizes validation of shared credentials data
- Previous validation functionality was moved in to this file
- Added function to be able to save credentials data (aws access key, secret key) at once to the credentials file.
> authWebview: Auth refactoring + new funcs

- src/shared/sam/cli/samCliLocator.ts
- src/shared/sam/cli/samCliSettings.ts
- src/shared/utilities/functionUtils.ts
- src/test/shared/utilities/functionUtils.test.ts
Problem:
1. sam cli location is not logged correctly (`SAM CLI location: [object Object]`)
2. sam cli location log message appears redundantly in the logs.
Solution:
1. fix log call
2. only log the location if it changed.
before:
2023-05-08 05:06:29 [INFO]: SAM CLI location: /opt/homebrew/bin/sam
2023-05-08 05:06:29 [INFO]: SAM CLI location: /opt/homebrew/bin/sam
2023-05-08 05:06:29 [INFO]: SAM CLI location: /opt/homebrew/bin/sam
2023-05-08 05:06:30 [INFO]: SAM CLI location: /opt/homebrew/bin/sam
...
2023-05-08 05:06:32 [INFO]: SAM CLI location: /opt/homebrew/bin/sam
after
2023-05-08 05:04:46 [INFO]: SAM CLI location: /opt/homebrew/bin/sam
> fix(logging): log sam cli location only if it changed

- .github/workflows/node.js.yml
Problem:
https://github.com/GabrielBB/xvfb-action is deprecated and hasn't been updated since 2021.
Solution:
Use https://github.com/coactions/setup-xvfb instead.
> ci: update xvfb action

- package.json
- scripts/build/prepare.ts
- src/shared/systemUtilities.ts
- src/shared/vscode/env.ts
Problem:
husky doesn't autoinstall since
https://github.com/aws/aws-toolkit-vscode/commit/c7637c261b90e175e9aac8dc66508dc02f4fa563
Solution:
auto install husky only if not running in CI.
> build: fix husky autoinstall

- src/shared/logger/logger.ts
- src/shared/sam/cli/samCliLocator.ts
- src/shared/sam/cli/samCliSettings.ts
- src/shared/sam/cli/samCliValidator.ts
- src/shared/systemUtilities.ts
- src/shared/utilities/asyncCollection.ts
- src/shared/utilities/functionUtils.ts
- src/shared/utilities/typeConstructors.ts
- src/stepFunctions/activation.ts
- src/test/shared/sam/cli/samCliTestUtils.ts
- src/test/shared/sam/cli/samCliValidator.test.ts
- `SamCliLocationProvider.getLocation()` is called many times and always  searches for sam on the system, which is slow (especially on Windows).
- Hard to follow the logic of SamCliValidator, too much indirection  involving `isSamCliVersionCached()` and `getSamCliExecutableId()`.
- Cache the last-found sam location in `DefaultSamCliLocationProvider`  instead of whatever `DefaultSamCliValidator` was trying to do.
- Use the cached location unless it fails `tryRun()`. This means Toolkit  still "shells out" to `sam`, which can be slow, but at least it avoids  a system search.
- Sample from CI shows that the first getLocation takes 800ms, later calls get a 5x speedup.
- Testing on Windows indicates first call can take 2-8(!) seconds, later calls are ~300ms.
```
2023-05-08 15:50:11 [VERBOSE]: …
```
> perf(sam): avoid searching for SAM CLI

- src/shared/clients/codecatalystClient.ts
- src/shared/logger/logger.ts
- src/shared/utilities/textUtilities.ts
- src/test/shared/utilities/textUtilities.test.ts
- old outdated fields listed in codecatalyst API logs
- no timing/profiling info for codecatalyst API calls
- very long fields like `nextToken` are noisy in the logs
- add timing/profiling info to logs
- truncate some fields like `nextToken`
- this is experimental, maybe the field should just be omitted if the value is not useful. OTOH, truncating it is somewhat equivalent to writing `[omitted]` but gives a hint about the "shape" of the value.
> codecatalyst: logging

- .changes/next-release/Removal-4234d2e9-3519-4f0b-ae6e-bcd5b93059a9.json
- .changes/next-release/Removal-773d85b9-9d85-40e4-9518-c784b4b13c74.json
- .changes/next-release/Removal-c111b554-676b-4080-9e59-68e95a727793.json
- src/shared/sam/activation.ts
- src/shared/sam/cli/samCliSettings.ts
Migration logic has existed for 1+ year to support old settings names.
Remove support of old settings names.
> fix!: remove legacy settings

- src/credentials/auth.ts
- src/credentials/sharedCredentials.ts
- src/credentials/sharedCredentialsValidation.ts
- src/credentials/types.ts
- src/credentials/wizards/templates.ts
This refactors the credentials validation code that previously had multiple validation functions for each credentials key.
This refactor changes this to use a switch case instead so that all validations of a certain type are contained within
the same function. This improves readability and reduces noise.
- Name changes
> refactor: Credentials Validation

- .changes/next-release/Feature-c91d7727-d6b0-4859-8023-a68fd3402189.json
- src/shared/sam/activation.ts
Problem:
`aws.samcli.enableCodeLenses` setting was added in 136a67bf64b6568eaaf5ca345b1262cb2cb0ee2d #1681 as a cosmetic feature, it didn't actually disable initialization of the codelense filewatchers(!).
Solution:
- Split the codelense setup logic for "sam template.yaml files" from "code files".
- Only initialize "code file" codelenses and filewatchers if:
1 . `aws.samcli.enableCodeLenses` setting is enabled (at startup _or_ dynamically at runtime)
2 . user invokes "Add SAM Debug Configuration"
Related: #3216
> perf: avoid filewatchers if enableCodeLenses=false

- src/shared/clients/codecatalystClient.ts
Improves performance and avoids "AccessDeniedException" noise in the logs.
> fix(codecatalyst): only get projects the user is a member of

- src/shared/sam/cli/samCliDetection.ts
- src/shared/sam/cli/samCliInfo.ts
- src/shared/sam/cli/samCliLocator.ts
- src/shared/sam/cli/samCliSettings.ts
Problem:
- Cached sam location is not evicted by the "AWS: Detect SAM CLI" command.
- Toolkit logs the sam cli location but not its version, which makes troubleshooting less obvious. #3381
Solution:
- Specify `forceSearch` when "AWS: Detect SAM CLI" calls `getOrDetectSamCli()`.
- Log the sam version.
> fix(sam): "Detect SAM CLI" uses cached sam location

- .changes/next-release/Feature-1e701503-730e-4065-b376-8be7dfa9dda7.json
- .changes/next-release/Feature-2c7d476f-6f8f-48d9-bd85-cbc53dab7216.json
- src/codecatalyst/wizards/selectResource.ts
"Open Dev Environment" menu:
- shows env id prominently which is not human-friendly
- user cannot filter by space or project name
- "Last used" string takes unnecessary space
- places "RUNNING" environments at the bottom of the list.
- Set `matchOnDetail=true` so the list can be filtered by the detail description, not just the label.
- Drop "Last used" label; the timestamp is clear enough on its own.
- When sorting the list, only compare "last used".
> codecatalyst: "Open Dev Environment": filter by space, project

- package.json
- src/codewhisperer/activation.ts
The command registration in deprecated code path is causing unit test / CI to fail. This PR is to remove one of it. A larger scale clean up will be done later.
No change log is needed. No customer facing impact.
> fix(codewhisperer): Remove command registration in deprecated code path

- package-lock.json
- package.json
- src/shared/awsClientBuilder.ts
No way to connect service-side issues with client-side failures.
Add `requestId` plus the service name to the current event and any subsequent events. 
> feat(telemetry): add request ID to events on failures

- .changes/next-release/Bug Fix-778b8105-0121-49bb-ac19-a5796d9e0b57.json
- package-lock.json
- package.json
Upgrade to the latest release of the amazon-state-language-service.
Closes #3152 “asl format doesn't allow Credentials key”
Closes #3308 “Does the ASL editor not support ProcessorConfig property”
Closes #2603 “Support for comments in YAML State Machines
> build(stepfunctions): amazon-states-language-service 1.9.0->1.10.0

- .changes/next-release/Bug Fix-5dd44ab8-9083-4dd8-ac28-585d99895aca.json
- src/stepFunctions/commands/visualizeStateMachine/abstractAslVisualizationManager.ts
- src/stepFunctions/commands/visualizeStateMachine/aslVisualizationManager.ts
- src/stepFunctions/utils.ts
- src/test/stepFunctions/utils.test.ts
Step Functions Render Graph visualizer will now work offline, as long as there is a cached local copy of the generating js and css files.
Closes #2922.
There is now a  graceful fallback when internet connectivity isn't available to a c9 or vscode host but where the required files are available in the local filesystem cache (either by previous automatic caching, or by manual user intervention).
Implementation avoids confusing the return type of 'updateCache' or 'updateCachedFile' and instead only checks for local files after a updateCache call fails.
This commit merges 3 previous work in progress commits made for PR #3098. The current change submitted in this PR incorporates all the review comments from the previous PR.
Once this PR merges to main you can close #3098.
With great thanks for …
> fix(stepfunctions): offline sfn visualizer

- .changes/next-release/Bug Fix-5496c0bc-07df-46af-b77f-e76bd53a847a.json
- src/credentials/sso/clients.ts
The retries are added to all InvalidGrantException that makes sure that all the transient issues that are causing InvalidGrantException should be resolved by this retry. Using default retry stragegy with 2 retries(as the AWSSDK standard) that is 3 max attempts. With exponential backoff
Tested with manually putting wrong parameters so the createToken call throws InvalidGrantExceptions, 3 requests are logged.
related JB change:
https://github.com/aws/aws-toolkit-jetbrains/pull/3692
```
2023-05-24 21:05:24 [DEBUG]: API request (oidc.us-east-1.amazonaws.com /token): {
clientId: ...
..........
}
2023-05-24 21:05:25 [ERROR]: API response (oidc.us-east-1.amazonaws.com /token): {
name: 'InvalidGrantException',
'$fault': 'client',
'$metadata': {
httpStatusCode: 400,
requestId: ....
},
error: …
```
> feat(auth): extra retry for failed SSO OIDC request

- src/codecatalyst/auth.ts
- src/codecatalyst/explorer.ts
- src/codewhisperer/util/authUtil.ts
- src/credentials/auth.ts
- src/credentials/vue/authForms/baseAuth.vue
- src/credentials/vue/authForms/manageBuilderId.vue
- src/credentials/vue/authForms/manageCredentials.vue
- src/credentials/vue/authForms/shared.vue
- src/credentials/vue/authForms/sharedAuthForms.css
- src/credentials/vue/authForms/types.vue
- src/credentials/vue/root.vue
- src/credentials/vue/serviceItemContent/awsExplorerContent.vue
- src/credentials/vue/serviceItemContent/baseServiceItemContent.vue
- src/credentials/vue/serviceItemContent/codeCatalystContent.vue
- src/credentials/vue/serviceItemContent/codeWhispererContent.vue
- src/credentials/vue/serviceItemContent/shared.vue
- src/credentials/vue/shared.css
- src/credentials/vue/show.ts
- Users can signup/signin to builder ID for CC or CW
- They will be guided through the existing signin flow
- CC and CW signin must be done individually. User will
need to complete signin for each.
- When signed in, a 'signout' option is shown, and if
clicked all of BuilderID will be signed out and
CC + CW will be updated in the UI
- Listening to events from the backend. Eg: when
a user interacts with builder id auth using an
alternative to the webview, the webview will
update with the latest status.
> authWebview: Builder Id sign in for CC + CW

- .github/workflows/node.js.yml
Problem:
`vscode:prepublish` takes 2 minutes in each job, but this is unnecessary. It's already tested by the `packageTestVsix.yml` CI job (`npm run package`).
Solution:
Drop `vscode:prepublish` in all CI jobs except `packageTestVsix.yml`.
> ci: skip vscode:prepublish

- .github/workflows/release.yml
- .github/workflows/release_notes.md
- scripts/build/package.ts
- Artifacts for `master` branch and `feature/x` branches are not  published to a canonical location, which makes it difficult for  scripts to consume them.
- Artifacts from `feature/x` branches are not advertised in GitHub's  "release" UI.
- Per-commit artifacts expire after a few days.
- Publish artifacts from `feature/x` branches to a fixed `pre-x` tag.
- Publish artifacts from `master` branch to a fixed `prerelease` tag.
https://github.com/justinmk3/aws-toolkit-vscode/releases
> ci: publish prerelease on push to master, feature/x

- src/auth/sso/validation.ts
- src/auth/ui/vue/authForms/manageIdentityCenter.vue
- src/auth/ui/vue/authForms/shared.vue
- src/auth/ui/vue/authForms/types.vue
- src/auth/ui/vue/serviceItemContent/baseServiceItemContent.css
- src/auth/ui/vue/serviceItemContent/codeWhispererContent.vue
- src/auth/ui/vue/show.ts
- src/auth/utils.ts
Adds in Identity Center SSO sign in for CW in the auth webview
- Validates start url field
- Can sign out and will fully delete the connections
> authWebview: Identity Center for CW

- src/testLint/eslint.test.ts
Before the actual error message wasn't being
printed on failure
> fix: lint test error message not printed

- src/shared/ui/common/regionSubmenu.ts
The actions and the log groups were blurred together in the prompt that gives user a region-change escape hatch. 
Add separators (mirroring log stream prompt) that distinguish the two options given to the user. 
Notes: 
- The data field was required, so left it as undefined. However, according to the docs, if kind is set to separator, all other fields are ignored(with the exception of label). 
> cwl: add seperators to RegionSubMenu

- src/cloudWatchLogs/document/logStreamsCodeLensProvider.ts
The wording of `Open this Log Stream` might imply we are opening a browser. Therefore, this can be confusing to users. 
Be more explicit and avoid the word `open` to alleviate confusion. 
> cwl: change codelense message to avoid confustion. 

- src/cloudWatchLogs/timeFilterSubmenu.ts
Options for CWL date search are very recent, and don't allow any defaults beyond 12 hours. 
Add more options, especially those that extend further back in time. 
Notes: 
- adding anymore requires the user to scroll through them. 
> cwl: add more "relative" date default options. 

- .changes/next-release/Feature-ce707655-611e-4a2f-997f-9d5b0472f7df.json
- src/codewhisperer/service/classifierTrigger.ts
- src/codewhisperer/service/inlineCompletionService.ts
- src/codewhisperer/service/keyStrokeHandler.ts
- src/test/codewhisperer/service/keyStrokeHandler.test.ts
- Roll out Classifier trigger 100% for languages
- Fix telemetry for classifier result inaccurate due to blocked triggers
> feat(codewhisperer): roll out classifier to more languages

- codecov.yml
Problem:
Each PR has failing CI because of a 75% code coverage requirement that hasn't moved for many months.
Solution:
Reduce the requirement to 70%. We can increase to 75% if/when code coverage is increased.
> ci: reduce codecov requirement to 70%

- CONTRIBUTING.md
- src/auth/ui/statusBarItem.ts
- src/dev/activation.ts
- src/shared/settings.ts
- src/test/shared/settingsConfiguration.test.ts
There was not a way to explicitly enable and disable dev mode with a single setting
Update the logic so that aws.dev.forceDevMode takes precedence over all other settings and will honor
whatever that value is in relation to if the user
is in dev mode.
Now, a user can have all their other dev settings
in place, but when they set 'aws.dev.forceDevMode: false' they will not be in dev mode anymore.
Fix: IDE-10948
> feat: Update the 'forceDevMode' setting

- src/shared/sam/cli/samCliInfo.ts
- src/test/shared/sam/cli/samCliValidator.test.ts
Problem:
sam cli [nightly build](https://github.com/aws/aws-sam-cli/releases/tag/sam-cli-nightly) reports an invalid semver version string (example: `1.86.1.dev202306120901`) which causes SAM features in AWS Toolkit to fail or report an error because version validation fails. 
Solution:
Add special handling for sam cli "nightly" version string format.
> feat(sam): support SAM CLI "nightly"

- .changes/next-release/Bug Fix-95b9f0dd-0811-4703-957b-deb1cea28f05.json
- src/codewhisperer/activation.ts
When user opens IDE while CodeWhisperer connection expired, there is no prompt that informs user the connection has expired. The current status bar being disconnected is not getting enough attention, causing CodeWhisperer to stay in disconnected state. 
Show re-auth prompt if connection expired at restart.
> fix(CodeWhisperer): show reauth prompt if connection expired at IDE restart

- src/test/shared/ui/prompters/regionSubmenu.test.ts
The tests currently use language specific to cwl, implying the component is only used for that purpose. However, nothing in the design of the UI component is specific to cwl and can be used outside that context.
Change the language to be more general, and avoid cwl terms like `group` or `logData`. 
> ui: regionSubmenu tests don't need to be cwl specific. 

- src/cloudWatchLogs/commands/searchLogGroup.ts
- src/ec2/prompter.ts
- src/shared/ui/common/regionSubmenu.ts
Regardless of the use case of the `RegionSubmenu` component, the separator label is fixed as `"Selections"`. Since this component is now used in EC2 and CWL, this is vague and not a very helpful label. 
Default the label to `"Selections"`, but allow for a constructor parameter to add case-specific text. 
First example: CWL can use `"Log Groups"` instead of `"Selections"`:
Second Example: EC2 can use `"Instances"` instead of `"Selections"`:
> ui: add optional parameter for separator label in RegionSubmenu

- src/auth/ui/vue/authForms/manageIdentityCenter.vue
- src/auth/ui/vue/serviceItemContent/baseServiceItemContent.css
- src/auth/ui/vue/serviceItemContent/codeWhispererContent.vue
Creates a toggle option for showing the Identity Center form for CodeWhisperer since we want to guide users to
Builder ID and reduce confusion.
> authWebview: toggle for CW Identity Center form

- src/auth/ui/vue/authForms/manageCredentials.vue
- src/auth/ui/vue/authForms/manageExplorer.vue
- src/auth/ui/vue/authForms/manageIdentityCenter.vue
- src/auth/ui/vue/authForms/shared.vue
- src/auth/ui/vue/authForms/types.ts
- src/auth/ui/vue/root.vue
- src/auth/ui/vue/serviceItemContent/awsExplorerContent.vue
- src/auth/ui/vue/show.ts
We can get IAM Credentials from an Identity Center connection for the Resource Explorer to work, but don't currently provide a way to do that.
Add a form for Identity Center in the Resource Explorer add connection webview.
Additionally, we still provide the ability to enter credentials directly, but hide it behind a toggle.
> authWebview: Identity Center sign in for Explorer

- .changes/next-release/Bug Fix-7e9427f3-d9cc-4b9b-983f-7ce5c5702368.json
- src/ecs/model.ts
- src/test/ecs/model.test.ts
- src/test/ecs/wizards/executeCommand.test.ts
See https://github.com/aws/aws-toolkit-vscode/issues/3589
Add `serviceName` to the `ListTasks` operation
Note that previously container instances spawned in a cluster but outside of a service were shown in the quick pick as well. If there is a valid use-case for this, we should consider adding some task-orientated UI.
> fix(ecs): only show tasks from the selected container

- package.json
- src/auth/activation.ts
- src/auth/ui/vue/authForms/manageBuilderId.vue
- src/auth/ui/vue/authForms/manageExplorer.vue
- src/auth/ui/vue/authForms/manageIdentityCenter.vue
- src/auth/ui/vue/root.vue
- src/auth/ui/vue/serviceItemContent/awsExplorerContent.vue
- src/auth/ui/vue/serviceItemContent/baseServiceItemContent.css
- src/auth/ui/vue/serviceItemContent/codeCatalystContent.vue
- src/auth/ui/vue/serviceItemContent/codeWhispererContent.vue
- src/auth/ui/vue/show.ts
- src/codecatalyst/utils.ts
- src/codewhisperer/util/authUtil.ts
- src/codewhisperer/util/getStartUrl.ts
- src/test/codewhisperer/util/authUtil.test.ts
This includes:
- Add/update url links
- During SSO (BuilderID and Identity Center) when something fails in the process we show an error message under the submit button indicating what happened.
- In the scenario where an Identity Center connection already exists and the user wants to use the same IC start url to connect to CodeWhisperer we previously wouldn't allow them since the start url already existed. Now, we will instead allow them to submit using that start url and it will take them through a flow which adds the new scopes to that sso profile.
> authWebview: minor changes

- src/shared/sam/cli/samCliValidationNotification.ts
- src/test/shared/sam/cli/samCliValidationNotification.test.ts
Problem:
since 4e40536c031abe09a9c5f8adb39e2018975fec85 the Toolkit can't load on cloud9:
INFO ExtHost [error]: Error: Attempted to get compute region without initializing.
at getComputeRegion (/opt/c9/dependencies/aws-toolkit-vscode/…/dist/src/main.js:377606:11)
at isCn (/opt/c9/dependencies/aws-toolkit-vscode/…/dist/src/main.js:377457:22)
at getIdeProperties (/opt/c9/dependencies/aws-toolkit-vscode/…/dist/src/main.js:377429:11)
Solution:
Lazy-load `SamCliValidationNotificationAction.label()`.
> fix(cloud9: "Attempted to get compute region without initializing"

- src/test/cloudWatchLogs/commands/copyLogResource.test.ts
As part of https://github.com/aws/aws-toolkit-vscode/pull/3558, the `copyLogStreamName` was generalized to `copyLogResource`, however, the test file names the test `copyLogStreamName`. 
To avoid confusion later and to be consistent with the rest of the toolkit, we should rename it `copyLogResource`. 
- the other changes in this PR are purely from styling fixes. 
> fix(cwl): change test text

- src/codecatalyst/auth.ts
When connection to CodeCatalyst Builder ID there is a prompt that asks if you would like to go to the browser but then immediately follows up with a prompt to copy a code then open the browser.
The initial prompt was created before the second one existed.
Remove the initial prompt since it is not needed.
> refactor: Remove additional prompt for CC Builder ID

- .changes/next-release/Feature-274d2890-0a84-4a43-9ca3-1037f4d212b7.json
- src/codewhisperer/service/classifierTrigger.ts
enable classifier trigger for jsx and tsx
> feat(codewhisperer): classifier trigger for tsx/jsx

- src/codewhisperer/util/authUtil.ts
- src/test/codewhisperer/util/authUtil.test.ts
This is for the consistency of such value for telemetry
> codewhisperer: Remove trailing / or # from startUrl

- src/auth/ui/vue/authForms/manageBuilderId.vue
- src/auth/ui/vue/authForms/manageCredentials.vue
- src/auth/ui/vue/authForms/manageIdentityCenter.vue
- src/auth/ui/vue/authForms/sharedAuthForms.css
- src/auth/ui/vue/root.vue
- src/auth/ui/vue/serviceItem.vue
- src/auth/ui/vue/serviceItemContent/awsExplorerContent.vue
- src/auth/ui/vue/serviceItemContent/baseServiceItemContent.css
- src/auth/ui/vue/serviceItemContent/codeCatalystContent.vue
- src/auth/ui/vue/serviceItemContent/codeWhispererContent.vue
- src/auth/ui/vue/shared.css
- Don't expand any of the features by default, we were previously showing the Resource Explorer form by default
- Shrink the UI to try to fit more on the screen at once
- Update CW Builder ID link to something more specific
- Improve identity center region selection
- Can click the text as well to open quick pick
- Set default to us-east-1
Fixes:
IDE-10998
IDE-10999
IDE-11000
> authWebview: Various fixes

- src/auth/activation.ts
- src/auth/ui/vue/show.ts
- src/auth/utils.ts
- src/shared/utilities/vsCodeUtils.ts
- src/test/credentials/utils.test.ts
- src/test/shared/utilities/vscodeUtils.test.ts
If the user has not had this run on their system yet, they will
not have the state variable existing yet. It will assume they
are a first time user.
- If they have no state, then fallback to checking if we are
aware of existing connections.
- Had to move the ExtensionUse class since we now have a circular
dependency due to using the Auth class
> fix(messages): "first use" missing fallback metric

- src/codewhisperer/service/recommendationHandler.ts
As per our sci team's request, update session level `CompletionType`.
- `Block` if there is a `Block` completion present in the session, otherwise `Line`
- Only check the 'first' completion, if it's `Block`, then the session is `Block` otherwise `Line`
> codewhisperer: update completion type Line/Block aggregation

- .changes/1.80.0.json
- CHANGELOG.md
Since v 1.80.0 did not have any explicit changes from 'npm run newChange', nothing was added to the changelog and this caused the 1.80.0 entry to be missing
Manually add an entry and update the changelog
> add missing changelog item

- .changes/next-release/Bug Fix-3e5e67c4-5bde-4d7d-b473-c1f772430c4f.json
- src/codewhisperer/util/supplementalContext/crossFileContextUtil.ts
Patch fix to PR https://github.com/aws/aws-toolkit-vscode/commit/219c586c72eb4127d008d68a880466ef47b79ede of which syntax error is causing crossfile context will return empty all the time
> fix(codewhisperer): fix syntax error, which cause crossfile feat returning empty

- .github/workflows/node.js.yml
Usually if one of the macos tests fails, we
will abort all other ones.
But, recently vs code insiders is failing exclusively and it aborts the other tests even though they should be fine. Due to this we cannot easily see that everything else is passing.
Solution:
Don't fail fast on mac os tests, let all of them
run and maybe we can tell if it is just a vscode
insiders problem more easily.
> ci: don't fail fast on macos tests

- .changes/next-release/Feature-fb427da2-9ded-464d-ab03-11d52a46b604.json
- src/lambda/models/samLambdaRuntime.ts
- src/lambda/utils.ts
- src/test/lambda/models/samLambdaRuntime.test.ts
- src/test/lambda/utils.test.ts
By default when a nodejs lambda was created,
the default file would be .js, but now with
node 18 the default file is .mjs.
The extension could not find node18 users files since the extension was
in .mjs but we were expecting it to be .js
Only support .mjs files for node18+ lambdas
> feat: support only .mjs extension for node18+ lambdas

- .changes/next-release/Bug Fix-e9afd2b9-cd47-4013-a2c0-8618d7b2ed15.json
- package.json
https://github.com/aws/aws-toolkit-vscode/issues/3477
Change the scope this shareCodeWhispererContentWithAWS settings to application.
> fix(codewhisperer): Change settings.shareCodeWhispererContentWithAWS to application
