aws/aws-toolkit-vscode

- src/codecatalyst/activation.ts
- src/codecatalyst/devEnv.ts
- src/shared/clients/devenvClient.ts
- src/shared/extensionUtilities.ts
- src/test/shared/clients/devenvClient.test.ts
- src/test/shared/extensionUtilities.test.ts
- src/testInteg/codecatalyst/devEnv.test.ts
If a user is using a dev env with something like vscode, and the user stops interacting with the ide
we want to notify the dev env about this inactivity so it can automatically shutdown after a certain
amount of user inactivity.
- A cancellable message will be shown a few minutes before shutdown, and will update
the remaining time each minute until the final minute before shutdown.
- On the final minute a different message will be show that indicates the dev env
will shut down in 1 minute.
- We will show messages 5 minutes before shutdown.
----
- For each message that pops up if they interact with the IDE or click one of the buttons
in the message it will refresh the shutdown timer to whatever was initially configured.
- General interactions with the IDE will cause the ide to send a …
> codecatalyst: Show warning messages when CC dev env is close to inactivity shutdown

- src/test/shared/extensionUtilities.test.ts
This fixes a flaky test due to the timeout delays
not being properly spaced. Because of this the
vscode Event Emitter would fire in the same
throttle interval. This caused the throttled function to treat
all calls to it to be in the same interval, such
that it only triggered once.
This fixes the delay of when the second set of
event firing goes off so that those are triggered
when we are in the next throttle interval, instead
of the first.
> test: unreliable ExtensionUserActivity test

- src/ec2/model.ts
- src/shared/clients/ec2Client.ts
- src/shared/clients/iamClient.ts
- src/test/ec2/model.test.ts
Currently, we retrieve the IAM Instance Profile associated with a target EC2 instance. This is not the same as the IAM Role attached to the EC2 instance. This issue is well hidden because the console (by-default) creates an instance profile for us when we attach a role to an EC2 instance. Specifically, 
> If you use the AWS Management Console to create a role for Amazon EC2, the console automatically creates an instance profile and gives it the same name as the role. When you then use the Amazon EC2 console to launch an instance with an IAM role, you can select a role to associate with the instance. In the console, the list that's displayed is actually a list of instance profile names. The console does not create an instance profile for a role that is not associated with Amazon EC2.
> …
> fix(ec2): use IAM Role instead of instance profile. 

- src/auth/ui/vue/show.ts
Problem:
getLogger() is called in module-scope, which means it may initialize to a "console logger" if the main logger is not ready yet, depending on module load order.
Solution:
Don't call getLogger() in module-scope.
> fix: ssoSetup() failure not logged

- src/test/shared/extensionUtilities.test.ts
test is still flaky in ci, increase the delay to give more flexibility
> fix: unreliable "ExtensionUserActivity" test

- src/auth/sso/cache.ts
- src/test/credentials/sso/ssoAccessTokenProvider.test.ts
- src/test/techdebt.test.ts
Problem:
- Date-triggered tech debt test started failing, which reminds us to remove old code.
- This code also was producing (harmless) failures which show up in logs (example: https://github.com/aws/aws-toolkit-vscode/issues/3403): ``` [WARN]: auth: error deleting old files in sso cache: Error: ENOENT: no such file or directory, scandir 'C:\Users\user.aws\sso\cache' [ENOENT] ```
Solution:
Remove deleteOldFiles().
> refactor: remove deleteOldFiles()

- src/codewhisperer/util/telemetryHelper.ts
The session id can be empty in the aggregated user decision events.
To reproduce it, you can invoke, and keep pressing Esc. 
When you press Esc frequently, multiple clear state function can be run in parallel, causing race conditions that set the session id to empty string.
Use the pre-existing, stored, non-empty session id in the aggregated user decision events. 
This solution only works for aggregated user decision events, it does not solve the global state problem in this code base. 
> fix(codewhisperer): use stored session id in aggregated user decision events

- src/awsexplorer/activation.ts
- src/awsexplorer/regionNode.ts
- src/shared/treeview/nodes/awsTreeNodeBase.ts
Emit `aws_expandExplorerNode` when a service node in AWS Explorer is expanded.
https://github.com/aws/aws-toolkit-common/commit/0b80eea4225c9991905855550d8adcbcbbd83a1d
> telemetry: emit aws_expandExplorerNode

- .changes/next-release/Feature-ff7562fc-d346-404a-9e2e-86d57d12d97a.json
- src/auth/auth.ts
- src/auth/connection.ts
- src/auth/sso/model.ts
- src/auth/ui/vue/show.ts
- src/test/credentials/auth.test.ts
Problem:
If the user connects with a IdC/SSO account that is not fully configured, selecting the connection silently does nothing.
Solution:
Show an error message (unless it was already shown).
Followup to #3704 24917d13b11904b12667da4d43d3c92f6f5b317c
> feat(auth): warn if SSO user has no accounts

- .changes/next-release/Bug Fix-f600d289-1c01-41c5-aff0-00619956aed1.json
- src/shared/ui/common/region.ts
- src/shared/ui/common/regionSubmenu.ts
- src/test/shared/ui/prompters/regionSubmenu.test.ts
This PR fixes the following two issues:
- "Switch region" --> "Switch Regions"
- Duplicate "recently used" tag is replaced by "default region" and "recently used" tags. 
Old Version:
New Version:
> UX: small issues with the regionSubmenu fix. 

- .changes/next-release/Bug Fix-1bdf6b9c-d49a-451d-acdc-1d4fb233e02b.json
- src/codewhisperer/service/inlineCompletionService.ts
- src/codewhisperer/service/recommendationHandler.ts
There's a weird case that when an empty suggestion is provided to the inline suggestion provider, the inline suggestion UI won't show afterward even executing commands to hide/show it again.
Given that empty suggestions don't need to be shown to the users, don't call onDidReceiveRecommendations until there's at least one non-empty suggestion for the inline provider(so inline UI will be able to pick this and show up correctly)
Before: 
1. Trigger to get two suggestions, the first one is an empty string
2. The suggestions won't show in the editor, I have to do the `tab` and `backspace` trick to see the suggestions again
https://github.com/aws/aws-toolkit-vscode/assets/89420755/ae0d6315-d5e6-48cb-a21a-4bc15f8f86c3
After:
1. Trigger at the same point to get two suggestions, frist one being an …
> CodeWhisperer: Fix inline suggestions not showing in the editor

- buildspec/linuxIntegrationTests.yml
- src/test/techdebt.test.ts
The python 3.10 sam CI tests were failing and blocking release. This downgrades from the current version causing the issue (1.95.0) to the previous version. Now CI should pass when `/runIntegrationTests` is run.
> ci: new sam cli update causing CI to fail

- src/test/techdebt.test.ts
- src/testE2E/codecatalyst/client.test.ts
These tests always fail due to a throttling issue with CodeCatalyst, see the SIM IDE-10496 for more info.
We will eventually re-enable these tests once the CC side fixes the issues causing this.
> test: Skip CodeCatalyst E2E tests

- .changes/next-release/Bug Fix-48264e8c-a8ab-487b-ad5d-d25e49068589.json
- src/auth/auth.ts
- src/auth/connection.ts
- src/auth/providers/sharedCredentialsProvider.ts
Problem:
Some IdC/SSO connections have OIDC "scopes" and don't have IAM "roles" (returning IAM credentials / "Permission sets"). Such connections are useful for scope-based applications, even though they don't have IAM credentials.
Solution:
Don't warn about missing roles/permission-sets for connections that have OIDC scopes.
> fix: misleading "Permission set" warning for OIDC SSO/IdC connection

- src/srcShared/README.md
- src/srcShared/fs.ts
- src/test/srcShared/fs.test.ts
Create Browser + Desktop compatible file system.
Future commits will make use of this, and existing uses of a different filesystem implementation (fs, fs-extra) should be
swapped to use these over time if possible.
> fileSystem: Class that works with browser or desktop file system

- .changes/next-release/Feature-c4dffad5-a36b-4f38-95d2-efbb2196c103.json
- .changes/next-release/Feature-f3f8fadc-c390-4099-8eff-894b78f4cc58.json
- package.json
- src/shared/sam/cli/samCliInvokerUtils.ts
- src/shared/sam/cli/samCliLocalInvoke.ts
- src/shared/sam/localLambdaRunner.ts
- src/test/shared/sam/cli/samCliInvokerUtils.test.ts
- src/test/shared/sam/cli/testSamCliProcessInvoker.ts
When SAM run/debug fails, customer must inspect the Output logs, which is time-consuming.
- #1643
- #3588
Capture useful messages from SAM CLI and surface them in the user message.
> sam: surface SAM CLI failures

- .changes/next-release/Bug Fix-880d1db0-1a68-4fbb-96c8-af1a988238bb.json
- .changes/next-release/Feature-c4e5cdd8-cc0e-4006-b06a-91e616ffc251.json
- src/codewhisperer/util/supplementalContext/crossFileContextUtil.ts
- src/test/codewhisperer/util/crossFileContextUtil.test.ts
revert unintended change introduced with this PR
https://github.com/aws/aws-toolkit-vscode/pull/3737/files#diff-d20df5e39cab67435d8923babae2de0a72f4e946e91f24111bf694bf28bb5a8eL73
This misconfiguration will change number of lines in a code chunk from 10 to 60 & 1000.
1000 lines of code in a code chunk will make the plugin to fetch the entire file and send back to the server every time, and we have a limitation of 10240 char length on supplemental context, thus users are possibly getting validation error from the service.
> codewhisperer: fix unintended change which is causing server side error "Exceed supplemental context content length"

- .changes/next-release/Feature-f2e37981-fba6-4a29-bdf3-4e06fa4dfa2f.json
- src/shared/fs/watchedFiles.ts
- src/shared/logger/activation.ts
- src/shared/settings.ts
- src/shared/utilities/vsCodeUtils.ts
- src/test/shared/settingsConfiguration.test.ts
- src/test/shared/utilities/vscodeUtils.test.ts
- "Scanning CloudFormation templates..." message takes a long time on big workspaces, and no way to workaround this.
- #3510
- When scanning for CFN/SAM templates, exclude all directories/files specified in _all_ of the vscode settings `files.exclude`, `search.exclude`, or `files.watcherExclude`.
> perf(sam): do not watch files excluded in user settings

- scripts/build/generateConfigurationAttributes.ts
- scripts/build/generateIcons.ts
- scripts/build/package.ts
- scripts/test/launchTestUtilities.ts
This is related to us enabling esModuleInterop in the tsconfig. When 'npm run generatePackage' was run it would add extra values to the package.json.
As a solution it was narrowed down that we can not do namespace imports (import * as assert from 'assert') and must instead do default imports (import assert from 'assert') for the package.json file.
> fix: package.json invalid after 'npm run generatePackage'

- .changes/next-release/Feature-b473d1cf-ceff-4d40-9024-29d045e4dbee.json
- package.nls.json
Added hyperlink to toolkit telemetry documentation in Settings.
https://sim.amazon.com/issues/IDE-11334
> Add telemetry hyperlink

- src/testInteg/globalSetup.test.ts
After enabling esModuleInterop if we do a namespace import
`import * as vscode from 'vscode'` we may run in to problems
when trying to patch the object.
Use a default import, `import vscode from 'vscode``
Probably something to do with how namespace vs. default imports are handled once something becomes an ESM module
> fix: failing integ test

- .changes/next-release/Breaking Change-5d46678e-8c2e-4fb3-8398-2adf4fe2ebbd.json
- package.json
- src/test/codewhisperer/util/crossFileContextUtil.test.ts
- src/test/shared/utilities/editorUtilities.test.ts
- src/testInteg/cloudformation/templateRegistry.test.ts
- src/testInteg/sam.test.ts
Since #3328 5439f9527224d8d1c0b98cd9941ee55a0cefb9ae , CI job "Integration Tests - minimum" fails (timeout) of some (not all) "invokes and attaches" tests:
5 failing
1) SAM Integration Tests
SAM runtime: python 3.10 (ZIP)
Starting with a newly created python 3.10 (ZIP) SAM Application...
target=api: invokes and attaches on debug request (F5):
Error: Test length exceeded max duration: 300 seconds
...
- Major difference is that [vscode 1.65 has nodejs 14, while vscode 1.66+ has nodejs 16](https://github.com/aws/aws-toolkit-vscode/pull/3315#issuecomment-1506896655).
- cloud9-classic has vscode extension host 1.68 + nodejs 16 ~~nodejs 12(!).~~
- cloud9-codecatalyst has vscode 1.68 + node 14.19
Tested in vscode local, vscode remote codecatalyst, cloud9-classic, cloud9-codecatalyst.
By …
> package: increase minimum vscode to 1.68

- .changes/next-release/Bug Fix-d9e4139d-a80c-4259-8492-605a5bce232a.json
- src/cloudWatchLogs/cloudWatchLogsUtils.ts
- src/cloudWatchLogs/commands/searchLogGroup.ts
- src/cloudWatchLogs/registry/logDataRegistry.ts
Problem:
When entering filter pattern for the "Search Log Group" action, the validation action does its own mini-search, before the actual search is done. The user sees multiple popups, which feels clunky.
Solution:
Ignore query parameters when calculating the message "id".
> fix(cloudwatch): "Search Log Group" shows multiple progress popups

- package-lock.json
We recently updated the vscode engine in
package.json.
'npm install' was not run so the package-lock.json was not updated.
Ran npm install and got the updated package-lock.json
> fix: package-lock.json not updated

- .changes/next-release/Bug Fix-f8528a3d-0300-44b6-ad2b-524dd5e9cd10.json
- src/cloudWatchLogs/document/logStreamsCodeLensProvider.ts
From the results page of "Search Log Group", the "View Full Log Stream" codelens only fetches 1000 events.
Use the configured limit instead of hardcoding 1000.
> fix(cloudwatch): "View Full Log Stream" only shows 1000 events

- .vscode/launch.json
- src/extensionWeb.ts
- src/shared/logger/activation.ts
- src/shared/logger/consoleLogTransport.ts
- src/shared/logger/sharedFileTransport.ts
- src/shared/logger/util.ts
- src/shared/logger/winstonToolkitLogger.ts
- src/test/shared/logger/consoleLogLogger.test.ts
- src/test/shared/logger/sharedFileTransport.test.ts
- src/test/testUtil.ts
In the browser logging does not work with our existing code.
- Change how we handle logging to a File since the built in "winston file transport" for logging to a file is not browser compatible
- Update the winston transport to allow us to log to the browser console
> browser: logging works in the browser

- src/cloudWatchLogs/activation.ts
- src/cloudWatchLogs/commands/saveCurrentLogDataContent.ts
- src/cloudWatchLogs/registry/logDataRegistry.ts
- src/test/cloudWatchLogs/commands/saveCurrentLogDataContent.test.ts
- src/test/testUtil.ts
Problem:
saveCurrentLogDataContent() re-renders the cloudwatch logs document from the "registry", even though this command only makes sense on an existing, open editor document. Also even in the case where a document isn't open, it should just be opened instead of using the low-level registry mechanics to get the file contents.
Solution:
- Use `vscode.window.activeTextEditor?.document.getText()` to get the file contents.
- Make the test more meanginful by opening an editor document instead of passing a URI.
> refactor(cloudwatch): simplify saveCurrentLogDataContent()

- .github/dependabot.yml
Dependency updates can be noisy. Unmerged dependency updates can block other updates if the max is reached.
- Use dependabot "groups" feature: https://github.blog/2023-08-24-a-faster-way-to-manage-version-updates-with-dependabot/ 
- Group updates to github actions. 
- Group updates to AWS SDK. 
- Group updates to vscode lsp packages.
Example of a grouped dependency update: https://github.com/cda-tum/setup-z3/pull/234
> CI: group dependency updates

- .changes/next-release/Feature-d124bdaa-a3b7-4d89-84c5-f7cbe495f128.json
- package-lock.json
- package.json
Upgrade amazon-states-language-service 1.10→1.11
This adds Step Functions validations for:
- Fail State: ErrorPath & CausePath.
- Retry: MaxDelaySeconds & JitterStrategy.
> build(stepfunctions): amazon-states-language-service 1.10→1.11

- scripts/build/generateServiceClient.ts
Problem:
The generateServiceClient task is noisy in CI logs:
> ts-node ./scripts/build/generateServiceClient.ts
...
Updating files:  66% (2895/4337)
Updating files:  67% (2906/4337)
Updating files:  68% (2950/4337)
Updating files:  69% (2993/4337)
Updating files:  70% (3036/4337)
...
Solution:
Use the `--quiet` option.
> build: silence git progress

- src/test/apprunner/wizards/codeRepositoryWizard.test.ts
- src/test/globalSetup.test.ts
- src/test/shared/ui/prompters/roles.test.ts
Problem:
rejected promise not handled within 1 second: Error: No return value has been set. Use `getOpenExternalStub().resolves` to set one.
stack trace: Error: No return value has been set. Use `getOpenExternalStub().resolves` to set one.
at Context.<anonymous> (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/src/test/globalSetup.test.ts:74:13)
at /Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/dist/src/test/globalSetup.test.js:35:71
Solution:
- Fail in `afterEach` (this is much more useful than a silent message in the test log).
```
1) "after each" hook: afterEach for "shows an option to go to documentation when no connections are available":
Error: Test called openExternal(https://docs.aws.amazon.com/apprunner/latest/dg/manage-create.htm …
```
> fix: tests call openExternal() without stubbing

- package-lock.json
- package.json
- src/codewhisperer/util/editorContext.ts
- src/codewhisperer/util/supplementalContext/crossFileContextUtil.ts
- src/codewhisperer/util/supplementalContext/supplementalContextUtil.ts
- src/codewhisperer/util/supplementalContext/utgUtils.ts
- src/codewhisperer/util/telemetryHelper.ts
- src/shared/telemetry/vscodeTelemetry.json
- src/test/codewhisperer/service/recommendationHandler.test.ts
- src/test/codewhisperer/util/crossFileContextUtil.test.ts
We are already able to analyze acceptance rate on either CrossFile or UTG or an aggregated number. Now we need more granular metrics for UTG `resolve source file by file name` vs. `resolve source file by file content` to help us understanding deeper the effectiveness of UTG, thus adding a new field `codewhispererSupplementalContextStrategyId` field representing the strategies being used for Crossfile and UTG.
* Crossfile
* OpenTabs + BM25
* UTG
* Resolve by file name (regex)
* Resolve by file content  
there are 4 values for now
`Empty`, `ByName`, `ByContent`, `OpenTabs_BM25`
> codewhisperer: add supplemental context strategy telemetry field

- .changes/next-release/Bug Fix-a9af385a-389b-4fe9-a6e2-2578f2e6f9ca.json
- src/codewhisperer/explorer/codewhispererNode.ts
- src/codewhisperer/util/authUtil.ts
This PR is to add more debug logs to help triage the  invalid_client error when customer is unable to sign-in successfully.
1. Add more debug logs at `isConnectionExpired`.
2. Detect connection expiration first.
> fix(codewhisperer): Add more debug logs for connection expiration

- scripts/build/package.ts
The "Package Test" CI job fails on `feature/x` branches that set `betaUrl`:
Error: Cannot package VSIX as both a release and a beta simultaneously
at main (/codebuild/output/src3161342786/src/github.com/aws/aws-toolkit-vscode-staging/scripts/build/package.ts:111:19)
(Note: `feature/x` branches are auto-tagged as `pre-x`, e.g. https://github.com/aws/aws-toolkit-vscode/releases/tag/pre-ec2 )
Make `isRelease()` more precise.
> fix(build): "package" task fails on feature-branches

- .changes/next-release/Bug Fix-68609ebe-e769-4aa3-829e-5a4af2210a14.json
- resources/codecatalyst_connect.ps1
When connecting to a dev environment using "Open Dev Environment" from a Windows user _who has not run Explorer or Edge at least once_, vscode remote-ssh may get stuck:
"Setting up SSH Host (details) Initializing VS Code Server"
"kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535"
https://github.com/aws/aws-toolkit-vscode/issues/3810
Specify the `-UseBasicParsing` option.
`Invoke-WebRequest` can fail for Windows users if IE/Edge have never been run, because of missing capabilities to parse the HTTP response. If IE/Edge were not run at least once, Windows does not initialize some libraries needed in powershell.
https://stackoverflow.com/a/38054505/152142
https://learn.microsoft.com/en-us/previous-versions/powershell/module/Microsoft.PowerSh …
> fix(codecatalyst): remote connect may fail from Windows

- src/shared/logger/activation.ts
Problem:
From a previous change we are now logging to the Developer Tools console of a browser whether in Node.js or the Browser.
Solution:
Only log to the Developer Tools console when in the Browser and skip if we are in Node.js
> logging: only log to console in browser

- src/test/techdebt.test.ts
- src/testE2E/codecatalyst/client.test.ts
The CodeCatalyst E2E tests were failing due to un-deletable Dev Environments (CodeCatalyst bug) and our code would hang, waiting for the old Dev Environments to be deleted.
Manually removed all un-deletable Dev Environments, and now the tests work again.
> codecatalyst: enable e2e test

- src/shared/sam/cli/samCliLocalInvoke.ts
Problem:
CI build logs have some very noisy messages like:
2023-09-13 17:28:03 [DEBUG]: forcing debugger to disconnect: name=test-config-1
No debugger available, can not send 'disconnect': Error: No debugger available, can not send 'disconnect'
at x.customRequest (vscode-file://vscode-app/codebuild/…/vscode-linux-x64-1.68.0/resources/app/out/vs/workbench/workbench.desktop.main.js:2161:16883)
at C.$customDebugAdapterRequest (vscode-file://vscode-app/codebuild/…/vscode-linux-x64-1.68.0/resources/app/out/vs/workbench/workbench.desktop.main.js:1722:7574)
at b._doInvokeHandler (vscode-file://vscode-app/codebuild/…/vscode-linux-x64-1.68.0/resources/app/out/vs/workbench/workbench.desktop.main.js:1731:13205)
at b._invokeHandler (vscode-file://vscode-app/codebuild/…/vscode-linux-x64-1.68.0/resource …
> logging: reduce log noise on debugger disconnect

- src/codewhisperer/activation.ts
- src/codewhisperer/commands/invokeRecommendation.ts
- src/codewhisperer/commands/onAcceptance.ts
- src/codewhisperer/commands/onInlineAcceptance.ts
- src/codewhisperer/models/constants.ts
- src/codewhisperer/models/model.ts
- src/codewhisperer/service/importAdderProvider.ts
- src/codewhisperer/service/inlineCompletionItemProvider.ts
- src/codewhisperer/service/inlineCompletionService.ts
- src/codewhisperer/service/keyStrokeHandler.ts
- src/codewhisperer/service/recommendationHandler.ts
- src/codewhisperer/service/referenceInlineProvider.ts
- src/codewhisperer/util/codeWhispererApplication.ts
- src/codewhisperer/util/codeWhispererSession.ts
- src/codewhisperer/util/telemetryHelper.ts
- src/test/codewhisperer/service/inlineCompletionService.test.ts
- src/test/codewhisperer/testUtil.ts
- src/test/codewhisperer/util/telemetryHelper.test.ts
1. Refactor some duplicated code
2. Refactor some condition checking logic to improve readability
3. Moved some of the states from `RecommendationHandler` to `CodeWhispererSession` since they are session scope(continued work), as well as removed some others that are not needed.
4. Fixed an issue where CodeWhisperer would try to get editor context (left/right context) for every request within a trigger session. These info only need to be retrieved once in the beginning of the session. Otherwise the latest leftContext will contain latest users edits which is not intended.
5. Fixed an issue where CodeWhisperer would try to use the language type of the current editor for sending telemetry; There could be cases when the current editor is no longer the original editor where invocation happens, …
> Various improvements to CodeWhisperer codebase

- .changes/next-release/Bug Fix-ed09954c-a35f-49d8-bc1f-7fa255110abf.json
- src/codewhisperer/tracker/codewhispererCodeCoverageTracker.ts
- src/codewhisperer/util/telemetryHelper.ts
- src/test/codewhisperer/tracker/codewhispererCodeCoverageTracker.test.ts
- src/test/codewhisperer/util/telemetryHelper.test.ts
1. Add the logic to compute generatedLines count, this will enable reporting the correct count of lines from CodeWhisperer. Making it a local computation.
2. Remove the 20 chars check in countTotalTokens(). This will enable the tracker timer to start whenever there's a change.
3. Remove an additional addTotalToken() call when accepting CodeWhisperer suggestions, this avoids double counting the total tokens when accepting CW suggetions.
4. Fix an issue where the referenceCount for each trigger is not reset after assigned. Removed the global and make it a local computation.
5. Ignore deletion events when computing total tokens, since it's non trivial to track the deletion of CW suggestions. This implictly makes the metric to track the code percentage of CW suggestion among all the code user …
> CodeWhisperer: Fix multiple issues around reporting CodePercentage

- src/auth/sso/model.ts
- src/auth/sso/ssoAccessTokenProvider.ts
- src/test/credentials/sso/model.test.ts
- src/test/credentials/sso/ssoAccessTokenProvider.test.ts
Problem:
Before this commit, the BuilderID/Identity Center sso flow
would require the user to copy a code and paste it in the
browser window to confirm their device.
Solution:
Now, with new changes from the identity team, if we pass
the device code in the URL a different flow will be shown
in the browser which asks them to instead confirm the
code instead of pasting it.
- This commit has users go through the new flow
- Copying code functionality is removed
- The information messages are updated to mention the requirement
to confirm the code in the browser
> sso: use new 'confirm match' device code flow

- src/codewhisperer/util/telemetryHelper.ts
update reference count in telemetry to only count accepted reference per request from product
> codewhisperer: update reference count to only count accepted reference

- .changes/next-release/Bug Fix-9fb78a30-8692-4ed2-925b-18906bef1da8.json
- src/shared/sam/debugger/typescriptSamDebug.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
Debugging a nodejs sam lambda always breaks at the nodejs internal module `internal/async_hooks` before reaching the first user-specified breakpoint. This is an old problem with `--inspect-brk`. #2758
- For "Image" packagetype, send `NODE_OPTIONS=--inspect=…` in the container environment variables instead of  `--inspect-brk`.
- For "Zip" packagetype set the `continueOnAttach` vscode nodejs debugger option, to workaround sam cli's hardcoded NODE_OPTIONS: https://github.com/aws/aws-sam-cli/blob/1adc080b82476288804c41c553c5e2ad86f28298/samcli/local/docker/lambda_debug_settings.py#L165
- Tested with node 14/16/18, python 3.10/3.11, "Image" and "Zip" packagetypes.
- Tested local and CodeCatalyst dev env.
By submitting this pull request, I confirm that my contribution is made under the terms of …
> feat(sam nodejs debug): don't break on async_hooks

- .changes/next-release/Bug Fix-ac5446a2-e6dd-4e85-b27c-cf8f75ae5aa1.json
- src/codewhisperer/service/inlineCompletionService.ts
- The function `getPaginatedRecommendation()` sets the CW status bar to loading when it starts to run.
- But it will return early if `AuthUtil.instance.isConnectionExpired()` returns true.
- The issue is when we return early we do not revert the loading status and the status bar is stuck loading.
- Set the status bar to loading after `AuthUtil.instance.isConnectionExpired()` check
> codewhisperer: loading status bar stuck on expired credentials

- .changes/next-release/Deprecation-e6ff982b-e562-4803-be2e-84e8a4c29eea.json
- README.quickstart.cloud9.md
- src/apprunner/wizards/codeRepositoryWizard.ts
- src/lambda/models/samLambdaRuntime.ts
- src/lambda/models/samTemplates.ts
- src/test/lambda/models/samLambdaRuntime.test.ts
- src/test/lambda/models/samTemplates.test.ts
- src/test/lambda/utils.test.ts
- src/test/shared/cloudformation/yaml/template_api_endpoint_configuration.yaml
- src/test/shared/cloudformation/yaml/template_api_request_model.yaml
- src/test/shared/fs/templateRegistry.test.ts
- src/test/shared/sam/debugger/awsSamDebugConfigurationValidator.test.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
- src/testFixtures/workspaceFolder/js-image-sam-app/hello-world/Dockerfile
- src/testFixtures/workspaceFolder/ts-plain-sam-app/template.yaml
No longer supported by Lambda.
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
> fix(sam): deprecate nodejs 12.x

- src/auth/ui/vue/authForms/manageIdentityCenter.vue
When there is an error under the submit button of the Identity Center form for the Add Connection page, the 'sign in' button looks like it is stuck because we expect the user to update the Identity Center form (eg: change the start url) and then allow them to click 'sign in'.
The issue is in certain cases where they have an error but want to retry (eg: cancelled during the sing in process) they are unable to do this.
If an error is detected under the 'sign in' button, which is caused by a previous failed attempt, we will still allow the user to click 'sign in' again.
> auth: change Add Connection page Identity Center submit behavior

- .changes/next-release/Deprecation-f9d02208-eb97-4c44-810c-013fabb4a7d9.json
- src/lambda/local/debugConfiguration.ts
- src/lambda/models/samLambdaRuntime.ts
- src/shared/codelens/codeLensUtils.ts
- src/shared/sam/cli/samCliValidator.ts
- src/shared/sam/debugger/awsSamDebugger.ts
- src/shared/sam/debugger/csharpSamDebug.ts
- src/shared/sam/localLambdaRunner.ts
- src/test/lambda/local/debugConfiguration.test.ts
- src/test/lambda/models/samLambdaRuntime.test.ts
- src/test/shared/fs/templateRegistry.test.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
No longer supported by Lambda.
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
- confirmed no regressions with dotnet6 on a CodeCatalyst dev env (linux)
> fix(sam): remove .NET core 3.1

- src/shared/sam/cli/samCliInvokerUtils.ts
- src/test/shared/sam/cli/samCliInvokerUtils.test.ts
- SAM CLI is an implicit dependency of AWS Toolkit, but if the customer  disables Toolkit telemetry, that choice isn't applied to SAM CLI's own telemetry.
- SAM CLI telemetry messages are very noisy in the Toolkit logs.
- Note: when the Toolkit log-level is "debug", we invoke SAM CLI      with `sam --debug`.
- When the customer has disabled AWS Toolkit telemetry, reflect that in SAM CLI invocations by setting an [env var](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-telemetry.html):
```
SAM_CLI_TELEMETRY=0
```
- Reduces CI logs by 400 lines.
- before:
```
2023-09-29 22:09:58 [VERBOSE]: stderr: 2023-09-29 22:09:58,967 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-09-29 …
```
> fix(telemetry): SAM CLI should inherit Toolkit telemetry setting

- src/codewhisperer/util/authUtil.ts
the auto-trigger setting got re-enabled when window reloads
> codewhisperer: fix auto-enable suggestion on window reload

- src/codewhisperer/commands/basicCommands.ts
- src/codewhisperer/service/recommendationHandler.ts
- src/codewhisperer/util/authUtil.ts
- src/codewhisperer/util/telemetryHelper.ts
- Auto-Enable suggestion on window reload
- Missing "CodewhispererGettingStartedTask" attribute in both "serviceInvocation" and "userTriggerDecision" events.
- Fixed auto enable suggestion on window reload by adding check for Getting started function instead of enable suggestions.
- Added "CodewhispererGettingStartedTask" attribute to "serviceInvocation" and "userTriggerDecision" events.
> codeWhisperer: fix for auto-enable suggestion on window reload and changes in Telemetry events

- src/codewhisperer/client/codewhisperer.ts
- src/codewhisperer/client/user-service-2.json
- src/test/codewhisperer/service/codewhisperer.test.ts
Updated the API and put the field in SendTelemetryEvent API requests.
Corresponding JB PR: https://github.com/aws/aws-toolkit-jetbrains/pull/3887
> CodeWhisperer: Add telemetry optout status to SendTelemetryEventRequest

- .changes/next-release/Feature-359dac4a-ed1e-4b0e-b909-6c450cf639b9.json
- src/auth/secondaryAuth.ts
Since https://github.com/aws/aws-toolkit-vscode/pull/3264 if a builder id is already in use by e.g. the CodeCatalyst feature of the Toolkit, clicking `Start` in the CodeWhisperer panel shows an unnecessary (modal!) prompt:
"CodeWhisperer requires access to your AWS Builder ID connection.
Proceed to login to grant CodeWhisperer access?"
This prompt is unnecessary because:
1. Customer has already explicitly said they want to login.
2. We don't show such a prompt when starting from zero (which is logically equivalent to "augmenting" an existing builder id connection).
3. The prompt is redundant with the browser flow, which shows the scopes and asks for confirmation.
metric                            unique clients
--------------------------------|---------------
connection_rescope_cancel …
> feat(codewhisperer): remove unnecessary "Proceed to login" prompt

- .changes/next-release/Bug Fix-628d74cf-3fbf-4bdd-bf03-93d0992660bf.json
- src/auth/sso/ssoAccessTokenProvider.ts
- src/test/credentials/sso/ssoAccessTokenProvider.test.ts
Users would run in to an `Invalid Client` error screen in the browser when reauthenticating with SSO (BuilderID or Identity Center).
In the scenario a client registration was expired and `SsoAccessTokenProvider.createToken()` was called, the expired client registration would be used to create the new token. This would result in the user being able to make it all the way to the browser web page, verifying their device code, and then they would see the `Invalid Client` error message in the browser.
This scenario was not expected to occurr since it was assumed that `getToken()` would be called before`createToken()` and `getToken()` would do the work of invalidating the expired client registration so that `createToken()` would not need to check if the client registration is expired.
Since we …
> fix(auth): client registration expiry not checked when creating token

- src/codewhisperer/activation.ts
- src/codewhisperer/service/diagnosticsProvider.ts
- src/codewhisperer/service/securityIssueHoverProvider.ts
- src/test/codewhisperer/service/securityIssueHoverProvider.test.ts
Currently hovering over a security issue will show the issue details in plain text, but there is no flexibility to add links or images, etc. due to vscode's `Diagnostic` message restricted to `string` type.
Create and register a hover provider that adds a custom hover object to each security issue which has markdown support. This will add a "TBD" message whenever a security diagnostic message is rendered. 
> CodeWhisperer: Security Issue Hover Provider

- .changes/next-release/Feature-3d9dd25d-a1c3-40a8-b520-a19b339bd4dd.json
- src/stepFunctions/utils.ts
Updating to latest version of State Machine graph static assets which supports the `ItemProcessor` field in Map states. This is necessary to visualize distributed map states and inline maps states using the new syntax.
Resolves https://github.com/aws/aws-toolkit-vscode/issues/3515
Bump graph version to latest version.
Visualized example state machine from #3515
> StepFunctions: graph visualization supports ItemProcessor field

- src/auth/secondaryAuth.ts
- src/awsexplorer/activation.ts
- src/codecatalyst/auth.ts
- src/codecatalyst/commands.ts
- src/codecatalyst/utils.ts
- src/codewhisperer/util/authUtil.ts
- src/test/codewhisperer/util/authUtil.test.ts
When adding additional auth connections like Builder ID, there are scenarios where the user is eventually shown a dialog asking them if they want to use their existing connection + new one. This is confusing to users.
Remove the prompt shown above, and always implicitly select the `Yes` option. This will cause the default behavior to now be additive. For example, if they have AWS Credentials and add a Builder ID for CodeWhisperer, then AWS Credentials will be used for the explorer while Builder ID will be used for CodeWhisperer
Previously, if a user has a CodeWhisperer Builder ID set up, then adds a CodeCatalyst Builder ID, they are prompted if they want to switch connections.
With this PR, we will skip the modal above and immediately show them the modal to open the browser so that they …
> auth: remove multiple auth prompts

- src/codewhisperer/client/codewhisperer.ts
- src/test/codewhisperer/service/codewhisperer.test.ts
1. and the api will only be called when the user has optin telemetry.
> Enable SentTelemetryEvent for Builder ID users

- src/codewhisperer/models/constants.ts
- src/codewhisperer/service/keyStrokeHandler.ts
- src/codewhisperer/util/userGroupUtil.ts
- src/test/codewhisperer/service/keyStrokeHandler.test.ts
We don't want to trigger when there is immediate right context on the same line, with "}" as an exception
This will be an A/B test
> codewhisperer: suppress token filling from auto-trigger

- src/auth/activation.ts
- src/auth/commands.ts
- src/codecatalyst/explorer.ts
- src/codewhisperer/explorer/codewhispererChildrenNodes.ts
- Will now show the auth wizard instead of the auth webview to users when in c9 classic or codecatalyst
- There will be no automatic opening of any auth setup when the user is a first time user in c9
- Renamed method to `showManageConnections()` since there are different outcomes depending on the IDE now.
> auth: show wizard in c9 instead of webview

- src/codewhisperer/models/constants.ts
- src/codewhisperer/util/runtimeLanguageContext.ts
cloud9 has different language id for bash/shellscript
add that id to supported list
> codewhisperer: fix bash not supported in C9

- src/test/codewhisperer/service/keyStrokeHandler.test.ts
KeyStrokeHandler tests has too much repetition and some tests are outdated 
remove the no longer needed tests for 2s rule for character based trigger and time based trigger, and refactor the test 
> codewhisperer: refactor keyStrokeHandler test and remove outdated tests

- src/codewhisperer/util/telemetryHelper.ts
- src/test/codewhisperer/util/telemetryHelper.test.ts
need to add # of chars accepted in userTriggerDecision event
> codewhisperer: add chars accepted in telemetry

- src/codewhisperer/util/authUtil.ts
Learn CodeWhisperer Page appears on VSCode Startup
Used DisablePrompt to disable the page to appear automatically to the user after first time signIn.
> fix(codewhisperer): "Learn" page may appear after restart

- package.json
The web extension is showing a lot of commands that we don't want to show.
Add a lot of `!isWeb` to command, debugger, and view registrations. This will render those code paths inaccessible directly via command, but will not fix any underlying compatibility issues if the code paths are exercised by alternate means.
* Using `isWeb` will still show these commands if we're running through the `Extension (browser)` debug target. We can create our own context, but since that requires the context to be written, we will see the views and commands pop in and out once the context is written. We cannot overwrite the `isWeb` context, as well.
* For now, use `npm run runInBrowser` (no debugger support though)
* Limiting on the command (instead of at the menu level) should still prevent these from …
> web: remove various commands

- src/codewhisperer/util/authUtil.ts
https://github.com/aws/aws-toolkit-vscode/assets/96078566/e3b4d24e-156c-48d3-b26a-9fc1c088ff1b
https://github.com/aws/aws-toolkit-vscode/assets/96078566/00380c89-5e35-48d9-8121-acf779c1a7bd
> codewhisperer: miss refreshing codewhisperer widget after allowlist status change

- .changes/next-release/Feature-777ada9a-6a81-42b4-b90e-7562bb5c2622.json
- src/redshift/activation.ts
Problem:
Creating a notebook first shows a "Save As" prompt, which is not the usual convention for starting a document. This adds friction to trying out redshift features.
Solution:
Create an untitled notebook without saving to the filesystem. Customer can later save (or discard) the notebook like any other document.
> feat(redshift): eliminate "Save As" prompt when creating a notebook

- package-lock.json
- src/browser/package.json
- src/srcShared/fs.ts
- webpack.browser.config.js
- Due to a recent change, we stopped using
the `fs` modules mkdir, and instead started
using the `vscode.workspace.fs` mkdir implementation
instead.
- The problem with the change is that `vscode.ExtensionContext.logUri`
is not allowed by the C9 implementation of `vscode.workspace.fs`
even though it works with the original `vscode.workspace.fs`
- This commit will have `mkdir()` revert to using `fs` in the scenario
that we are in C9. This will allow `logUri` to be mkdir'd successfully
- Also this change has been tested to work in the browser mode. Since
we only call `fs` if in C9, the non-browser-compatible `fs` module will
not be executed at any point in the browser.
> c9: fix mkdir not working 

- package.json
- package.nls.json
- src/auth/auth.ts
- src/auth/secondaryAuth.ts
- src/auth/ui/vue/show.ts
- src/codecatalyst/activation.ts
- src/codecatalyst/auth.ts
- src/codecatalyst/explorer.ts
- src/codewhisperer/activation.ts
- src/codewhisperer/util/authUtil.ts
This commit allows user to right click to root CW or CC
Node or click the new ellipsis icon, and they will get
the options to Add Connection or Signout (if appropriate)
> auth: ellipsis + right click options for `Developer Tools`

- src/codewhisperer/activation.ts
- src/codewhisperer/service/diagnosticsProvider.ts
- src/codewhisperer/service/securityIssueHoverProvider.ts
- src/test/codewhisperer/service/securityIssueHoverProvider.test.ts
Hovers positions are not being updated if the document changes.
Add an event handler which either removes the hover or offsets the line number depending on what was changed (similar to how [diagnostics are updated](https://github.com/aws/aws-toolkit-vscode/blob/0974becd8d26bc12a640b34bfbefc2e20fe8cb17/src/codewhisperer/service/diagnosticsProvider.ts#L61-L93
)) 
> codewhisperer: security hover update range and format

- src/codewhisperer/client/codewhisperer.ts
- src/codewhisperer/tracker/codewhispererCodeCoverageTracker.ts
- src/codewhisperer/tracker/codewhispererTracker.ts
- src/codewhisperer/util/telemetryHelper.ts
> fix(codewihsperer): mapping language code before calling sendTelemetry API

- .changes/next-release/Feature-177a8535-0502-4135-a0f5-a2888f98949e.json
- src/extension.ts
- src/shared/settings.ts
- src/test/utilities/testSettingsConfiguration.ts
Problem:
vscode notifies the user if `settings.json` is complete nonsense, but is silent if there are only "recoverable" JSON syntax errors. So _reading_ settings will appear to work, but _writing_ settings will throw an exception. #3910
Solution:
On startup, check that we can actually _write_ settings, and show an error message if not.
> feat(settings): check that user settings.json is valid

- .changes/next-release/Bug Fix-b3e30500-5dbe-4b08-ae36-aaba6b020c8f.json
- src/codecatalyst/devfile.ts
- src/shared/cloudformation/activation.ts
- src/shared/fs/watchedFiles.ts
- src/shared/sam/activation.ts
- src/test/shared/debug/launchConfiguration.test.ts
- src/testInteg/cloudformation/templateRegistry.test.ts
WatchedFiles takes a long time to process the watched files
There's probably a lot of problems here, but this is definitely one of them: rebuilding after each additional watch pattern meant we were processing globs n times, with each run containing `{1, 2, 3, ... , n-1, n}` patterns. Swapping this to an array and enforcing adding the patterns once ensures we only process 1 time, for n globs on initial load. We aren't adding globs dynamically at any point; if we ever feel the need to, we can implement some fancy caching/expiry business.
FWIW it seems like getting the files in the glob is fairly fast, so if processing files is the bottleneck, this might be the cure? I'm sure we can improve more going forward regardless.
By submitting this pull request, I confirm that my contribution is made …
> watchedfiles: add watch patterns once to avoid rebuilding n times

- .changes/next-release/Bug Fix-7c1f7a4d-132c-4b88-b19d-b76dab547915.json
- .changes/next-release/Bug Fix-7c49d65e-079c-4578-9c69-9dd7d4925b4e.json
- src/redshift/activation.ts
- src/redshift/explorer/redshiftWarehouseNode.ts
- src/redshift/notebook/redshiftNotebookController.ts
- src/redshift/wizards/connectionWizard.ts
- src/test/redshift/explorer/redshiftWarehouseNode.test.ts
1. When the connection parameters is removed, the re-launched connection wizard still show the earlier connection parameters.
2. When a sql query is successful but doesn't return any record, the output message is not clear. 
1. Remove the connection wizard from the redshiftWarehouseNode constructor. Create a new instance when a connection wizard is launched.
2. Modify the output message when a sql query is successful but doesn't return any record.
> fix(redshift): fix cache in connection wizard

- .changes/next-release/Bug Fix-fff4dbbd-2664-43c3-bf6f-98cf1440ace2.json
- src/redshift/activation.ts
- src/redshift/explorer/redshiftWarehouseNode.ts
Output panel always opens at VS Code launch. Issue reported at https://github.com/aws/aws-toolkit-vscode/issues/3930. 
Instead of showing Output panel at Redshift activation, change to show Output panel only when a message is added.
> fix(redshift): VS Code always opens Output panel

- src/auth/connection.ts
- src/auth/sso/validation.ts
- src/auth/utils.ts
- src/codecatalyst/auth.ts
- src/codewhisperer/util/authUtil.ts
- src/test/codewhisperer/util/authUtil.test.ts
- src/test/credentials/testUtil.ts
- src/test/credentials/utils.test.ts
- src/testE2E/codecatalyst/client.test.ts
This creates simple helper methods to be able to check if a connection of a certain type exists.
The methods answer questions similar to: `Is the toolkit extension aware of a Builder ID connection for CodeWhisperer, regardless of if the connection is active?`
- CodeCatalyst and CodeWhisperer have functions in their auth classes to check for connections specific to them
These will be used in future commits by the Add Connections page for telemetry purposes.
> auth: Helper methods to check if connection exists

- .changes/next-release/Feature-bd1ff59d-583c-4611-9e14-3e47a9014e72.json
- src/shared/ui/picker.ts
- src/shared/ui/pickerPrompter.ts
Problem:
When trying to select a CloudWatch Log Stream, the UI scrolls to the top while fetching all streams, which is very difficult to use.
Solution:
Set `keepScrollPosition = true` by default.
Closes #2379
> feat(cloudwatchlogs): preserve position while loading items

- src/codewhisperer/activation.ts
- src/codewhisperer/service/diagnosticsProvider.ts
- src/codewhisperer/service/securityIssueCodeActionProvider.ts
- src/codewhisperer/service/securityIssueHoverProvider.ts
- src/codewhisperer/service/securityIssueProvider.ts
- src/test/codewhisperer/service/securityIssueCodeActionProvider.test.ts
- src/test/codewhisperer/service/securityIssueHoverProvider.test.ts
- src/test/codewhisperer/service/securityIssueProvider.test.ts
- src/test/codewhisperer/testUtil.ts
Currently the Apply Fix action is hidden behind the hover panel and requires user to mouse over the issue. It should be more accessible without having to leave the keyboard.
- Added code action provider to provide a Quick Fix action for each issue (that has at least 1 security patch available).
- The menu can be accessed using the  ⌘ + . keyboard shortcut or by clicking the light bulb icon
- Added an abstract class `SecurityIssueProvider` which has text document change handler common for `SecurityIssueHoverProvider` and `SecurityIssueCodeActionProvider`
> codewhisperer: add quick fix code actions for issues

- src/codewhisperer/service/recommendationHandler.ts
https://github.com/aws/aws-toolkit-vscode/assets/96078566/d2fb7d33-8935-4d13-ba7b-60e668e5198d
```
2023-10-23 18:39:31 [DEBUG]: The selected customization is no longer available. Retrying with the default model.
Failed request id: 5f8265c7-23ff-4286-bc9f-1cbd3f68d7b0
2023-10-23 18:39:31 [DEBUG]: codewhisperer: Connection expired = false,
secondaryAuth connection expired = false,
connection is undefined = false
2023-10-23 18:39:31 [DEBUG]: codewhisperer: isValidCodeWhispererConnection = true
2023-10-23 18:39:31 [DEBUG]: Selected customization CodeWhisperer foundation (Default) for IAM Identity Center (d-9067af8754)
2023-10-23 18:39:31 [DEBUG]: codewhisperer: Connection is valid = true, 
connection is undefined = false,
secondaryAuth connection expired = false
2023-10-23 18:39:31 [DEBUG]: …
```
> codewhisperer: switch to default model when receiving ResouceNotFoundException

- src/codecatalyst/devfile.ts
- src/lambda/commands/createNewSamApp.ts
- src/lambda/local/debugConfiguration.ts
- src/lambda/vue/configEditor/samInvokeBackend.ts
- src/lambda/wizards/samDeployWizard.ts
- src/shared/awsFiletypes.ts
- src/shared/codelens/codeLensUtils.ts
- src/shared/extensionGlobals.ts
- src/shared/fs/watchedFiles.ts
- src/shared/sam/debugger/awsSamDebugConfigurationValidator.ts
- src/shared/sam/debugger/awsSamDebugger.ts
- src/shared/sam/debugger/commands/addSamDebugConfiguration.ts
- src/shared/sam/sync.ts
- src/shared/utilities/workspaceUtils.ts
- src/test/lambda/commands/createNewSamApp.test.ts
- src/test/lambda/config/templates.test.ts
- src/test/lambda/local/debugConfiguration.test.ts
- src/test/shared/awsFiletypes.test.ts
- src/test/shared/fs/templateRegistry.test.ts
- src/test/shared/sam/debugger/awsSamDebugConfigurationValidator.test.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
- src/testInteg/cloudformation/templateRegistry.test.ts
- src/testInteg/sam.test.ts
- src/testInteg/shared/utilities/workspaceUtils.test.ts
Problem:
getRegisteredItem implies there is some other kind of "item", which is confusing and noisy.
Solution:
Rename to getItem.
> refactor(watchedfiles): rename getRegisteredItem => getItem

- src/redshift/activation.ts
- src/redshift/explorer/redshiftDatabaseNode.ts
- src/redshift/explorer/redshiftSchemaNode.ts
- src/redshift/explorer/redshiftWarehouseNode.ts
- src/redshift/messageUtils.ts
- src/redshift/utils.ts
There are similar logging and output message in node explorer. Refactoring code to centralize logging and message output makes it easy for maintenance. 
Create message functions in messageUtils.
> refactor(redshift): logging and output message

- src/shared/clients/lambdaClient.ts
The default lambda client used across the project had a low timeout (2 minutes default for an AWS Service client).
Add a longer timeout when creating the DefaultLambdaClient
> fix: add longer timeout to default lambda client

- .changes/next-release/Bug Fix-6b798eec-0914-4eef-b384-46829bc2cde0.json
- .changes/next-release/Bug Fix-9623dcac-8c9f-4687-a2ce-8a02b4e982be.json
- src/lambda/vue/configEditor/samInvokeBackend.ts
- src/shared/debug/launchConfiguration.ts
- src/shared/fs/watchedFiles.ts
- src/shared/sam/activation.ts
- src/shared/sam/debugger/awsSamDebugConfigurationValidator.ts
- src/shared/sam/debugger/awsSamDebugger.ts
- src/test/shared/debug/launchConfiguration.test.ts
- src/test/shared/sam/debugger/awsSamDebugConfigurationValidator.test.ts
- src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
SAM debug may fail to find template.yaml even if it is explicitly given by `invokeTarget.templatePath` in the vscode launch config. #2614
- Always call `addItem()` in `validate()`, instead of depending on the  workspace-wide "scan".
- Log a message when `process()` fails to process the file contents.
> fix(sam): "Invalid (or missing) template file"

- package.json
Problem:
Cloud9 sets `isWeb` even though it has "compute".
Solution:
Add an explicit condition for Cloud9 wherever we check `isWeb`.
ref d2f03d52a221
> cloud9: skip "!isWeb" check

- docs/api.md
- src/codewhisperer/commands/basicCommands.ts
- src/codewhisperer/util/customizationUtil.ts
The `aws.codeWhisperer.connect` command was introduced to allow enterprises to establish a default customization for onboarding developers after establishing an IdC connection.
However, it only selected with a given ARN. Given the current behavior for adding updated customization for CodeWhisperer, an enterprise would need to keep the ARN up-to-date as well when calling this command.
Provide the ability to define the customization to select with a prefix for the customization name. This way the logic to select a customization as updated customizations are introduced can be simplified on the administrator side by maintaining a prefix. e.g. MyModel-v1, MyModel-v2, etc.
> feat(codewhisperer): select customization by prefix

- src/shared/awsFiletypes.ts
- src/shared/cloudformation/activation.ts
- src/shared/cloudformation/cloudformation.ts
- src/shared/fs/templateRegistry.ts
- src/test/shared/awsFiletypes.test.ts
- src/test/shared/cloudformation/cloudformation.test.ts
- src/test/shared/debug/launchConfiguration.test.ts
The AWS Documents handler (`awsFiletypes.ts`) is triggered frequently. It calls `globals.templateRegistry` which triggers an expensive "Scanning CloudFormation templates..." process. #3510
Extract the validation logic out of `CloudFormationTemplateRegistry.process()` so that `awsFiletypes.ts` can use it without requesting the full registry.
> perf(startup): avoid templateRegistry in awsFiletypes.ts

- .github/workflows/node.js.yml
- .npmrc
- buildspec/linuxE2ETests.yml
- buildspec/linuxIntegrationTests.yml
- buildspec/linuxTests.yml
- buildspec/packageTestVsix.yml
- package-lock.json
- package.json
Developers may have outdated tooling, which causes weird problems.
- Define minimum npm version and enforce it via `.npmrc`. Outdated npm will show an error like:
```
$ npm install
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: aws-toolkit-vscode@1.96.0-SNAPSHOT
npm ERR! notsup Not compatible with your version of node/npm: aws-toolkit-vscode@1.96.0-SNAPSHOT
npm ERR! notsup Required: {"npm":"^10.1.0","vscode":"^1.68.0"}
npm ERR! notsup Actual:   {"npm":"10.0.0","node":"v20.8.0"}
```
- Disable the check in CI. Because it's transitive, random dependencies  like "marked" can pointlessly require aggressively-recent versions of  NPM, which isn't feasible for us to support in our CI:
```
npm ERR! engine Not compatible …
```
> build: require minimum NPM version

- src/codewhisperer/service/securityIssueHoverProvider.ts
- src/test/codewhisperer/service/securityIssueHoverProvider.test.ts
- webpack.vue.config.js
Images are broken in hover when running the extension as VSIX file
Configure webpack to load the image files into `dist` and load it from there
> fix(codewhisperer): load hover images from dist folder

- package-lock.json
- package.json
- src/codewhisperer/commands/startSecurityScan.ts
- src/codewhisperer/models/model.ts
We want to track how many issues were generated with at least 1 suggested fix
- Update `@aws-toolkits/telemetry` version and emit the count as part of `codewhisperer_securityScan` metric
> codewhisperer: emit issues with fixes count

- src/auth/ui/vue/serviceItem.vue
We want to prioritize the CW sign in when users first open the page.
> auth: make CW appear first in 'Add Connection' page

- .eslintrc.js
- src/shared/sam/activation.ts
- src/shared/sam/debugger/goSamDebug.ts
- src/testInteg/sam.test.ts
https://eslint.org/docs/latest/rules/no-inner-declarations
Since 14aab453fea5, we can now enable this rule. The pattern that it prevents is not commonly used in our codebase, and it reduces the potential for accidents, so it's worth enabling the rule.
> lint: no-inner-declarations

- src/codewhisperer/util/telemetryHelper.ts
- src/test/codewhisperer/util/telemetryHelper.test.ts
align the logic for aggregating completionType in userTriggerDecision with JB
we should use the completionType of the first recommendation 
> codewhisperer: use first recommendation for completionType

- src/testInteg/integrationTestsUtilities.ts
- src/testInteg/sam.test.ts
Fix broken integ tests. Unknown if this will give us a lot of spam, but it looks like there are no more linting settings for Python.
> Remove deprecated Python configs

- .npmrc
Problem:
release pipeline is blocked by engine-strict.
Solution:
temporarily disable engine-strict to unblock today's release.
> build: temporarily remove engine-strict

- .changes/next-release/Bug Fix-bbaf4ca5-56ad-47cc-949c-11fc91a8bff1.json
- src/ecs/commands.ts
- src/ecs/model.ts
- src/ecs/util.ts
https://github.com/aws/aws-toolkit-vscode/issues/3969
Problem: We attempt `SimulatePrincipalPolicy` to verify the container task role has proper permissions before running exec command. Users may not have access to simulate policies, but may otherwise be able to run exec command without issue.
Solution: Only attempt `SimulatePrincipalPolicy` if exec command fails. Otherwise, there is no need to simulate policies.
Testing: Tested manually with PowerUser case described in #3969. As expected, if `exec command` fails then the failure reason is returned along with the results of the permissions check, if it failed (e.g. from missing permissions or permission denied to simulate policies).
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> fix(ecs): exec command requires SimulatePrincipalPolicy permissions #3969

- .npmrc
- buildspec/release/00clonerepo.yml
- buildspec/release/10changeversion.yml
- buildspec/release/20buildrelease.yml
- buildspec/release/30closegate.yml
- buildspec/release/40pushtogithub.yml
- buildspec/release/50githubrelease.yml
- buildspec/release/60publish.yml
Release automation logic lives in a different repo, which adds friction to developing it, and reduces discoverability.
Move all release automation logic into this repo. This repo should be the source of truth where possible.
> ci: release automation lives in this repo

- package-lock.json
- package.json
- src/codewhisperer/activation.ts
- Downgrade `@aws-toolkits/telemetry` to same version as `master` to resolve build issues
- Rename `supportedLanguages` -> `platformLanguageIds`
> codewhisperer: downgrade telemetry package

- src/codewhisperer/commands/basicCommands.ts
- src/codewhisperer/models/model.ts
- src/codewhisperer/service/securityIssueCodeActionProvider.ts
- src/codewhisperer/service/securityIssueHoverProvider.ts
- src/codewhisperer/views/securityIssue/securityIssueWebview.ts
- src/shared/telemetry/vscodeTelemetry.json
- src/test/codewhisperer/commands/basicCommands.test.ts
- src/test/codewhisperer/service/securityIssueHoverProvider.test.ts
We want to track the number of times apply fix command is executed for a security scan issue.
- Added `codewhisperer_codeScanIssueApplyFix` metric that emits when command is executed and what the resulting state is.
- Refactored `applySecurityFix` function and tests for readability
> codewhisperer: telemetry metrics apply fix

- buildspec/linuxIntegrationTests.yml
- buildspec/linuxTests.yml
- buildspec/packageTestVsix.yml
Problem:
codebuild shows non-fatal warning:
[Container] 2023/11/02 21:48:22.543013 Found possible syntax errors in buildspec:
In the section BUILD
The following keys cannot be identified:
env
In the section PRE_BUILD
The following keys cannot be identified:
env
Solution:
Remove the (invalid) "env" directive. This was already suspected to be ignored, but wasn't certain until I saw this error in the logs.
> refactor(ci): cleanup invalid syntax

- buildspec/linuxTests.yml
Problem:
lint job doesn't run in the private repo.
Solution:
- As a temporary workaround, run lint in `linuxTests.yml`. 
- TODO: create a separate codebuild task for lint.
> ci: run "lint" in codebuild

- src/ssmDocument/activation.ts
- src/ssmDocument/commands/publishDocument.ts
- src/test/ssmDocument/commands/publishDocument.test.ts
"publishDocument .. createDocument" tests fail on "Insiders" CI job. #4013
- Adjust the tests to show what was passed.
- Create the `TextDocument` in `beforeEach` instead of `before()`. Don't bother to "show" it.
- Why does this work? Some sort of misordering or race with `before()`?
1) publishDocument
createDocument
createDocument API returns successfully:
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
(0, assert_1.default)(client.createDocument.calledWith(fakeCreateRequest))
-false
+true
at Context.<anonymous> (src/test/ssmDocument/commands/publishDocument.test.ts:84:19)
+ actual - expected ... Lines skipped
[
[
{
+       Content: '',
-       Content: 'foo',
DocumentFormat: 'JSON',
...
}
]
]
By submitting this pull request, I confirm that …
> fix: failing test "publishDocument .. createDocument"

- src/codecatalyst/devfile.ts
- src/shared/cloudformation/activation.ts
- src/shared/fs/templateRegistry.ts
- src/shared/fs/watchedFiles.ts
- src/shared/sam/activation.ts
- src/test/shared/debug/launchConfiguration.test.ts
- src/testInteg/cloudformation/templateRegistry.test.ts
- src/testInteg/sam.test.ts
Cancelling the CFN registry toast would continue registering YAML files in the background, and merely just hid the popup
Cancelling through the widget should now stop after the current file finishes processing
* tested best with a breakpoint on the processing--it looks like it stops immediately but haven't tried this on a slow machine with a lot of YAML (we're getting really good at not starting the registry! it doesn't do me any favors trying to test this though...)
* some light refactoring (`registry.rebuild()` is a mandatory call--this makes it easier to pass a cancellation promise)
Note: we don't have a way to restart the load, so right now, cancelling means that you have to restart the toolkit if the registry is busted.
By submitting this pull request, I confirm that my contribution …
> fix: cannot cancel "Scanning CloudFormation templates..."

- .changes/next-release/Bug Fix-b7a9021d-e848-46a3-8f6d-fd7017cb1784.json
- src/lambda/commands/createNewSamApp.ts
- src/shared/debug/launchConfiguration.ts
- src/shared/fs/templateRegistry.ts
- src/shared/fs/watchedFiles.ts
- src/shared/sam/debugger/awsSamDebugConfigurationValidator.ts
- src/shared/utilities/vsCodeUtils.ts
followup to https://github.com/aws/aws-toolkit-vscode/pull/3987
- changelog
- fix some minor bugs
- fix(sam): "failed to process" template URI containing `${workspaceFolder}` https://github.com/aws/aws-toolkit-vscode/pull/4020/commits/183e0e4df8b1da47549a757c12d2b0873782ef39
> fix: "Scanning CloudFormation templates..."

- buildspec/lint.yml
- buildspec/linuxE2ETests.yml
- buildspec/linuxIntegrationTests.yml
- buildspec/packageTestVsix.yml
- buildspec/shared/linux-install.sh
- buildspec/shared/linux-pre_build.sh
- buildspec/shared/setup-github-token.sh
Problem:
- 6057ef46b7de was a workaround which runs lint as part of the "linuxTests" CI job.
- Too much duplicate code spread around in the CI scripts.
- ⚠️  Inlining shell code in the buildspec yaml files makes it difficult    to automate linting via https://www.shellcheck.net and prettier.
Solution:
- Define a separate CI job in `lint.yml`.
- Put common logic in `buildspec/shared/*.sh` bash scripts.
followup to 6057ef46b7de
> ci: move common logic into shared scripts

- CONTRIBUTING.md
- scripts/build/package.ts
- src/shared/extensions.ts
Problem:
Showing "Toolkit PREVIEW" message when running version `1.99.0-SNAPSHOT`
Solution:
Define `extensionAlphaVersion` as 1.9999 instead of 1.99
> fix: "Toolkit PREVIEW" message for version 1.99

- src/shared/cloudformation/activation.ts
- src/shared/fs/codelensRootRegistry.ts
- src/shared/fs/devfileRegistry.ts
- src/shared/fs/templateRegistry.ts
- src/shared/fs/watchedFiles.ts
Problem:
Progress message does not reliably appear, its behavior is erratic.
Solution:
Create one progress message and report() to it when work is performed. Return early from getInstance(), don't create `setupPromise` multiple times.
Logs sample: shows "requested" message when a new request arrives (e.g. by opening a template.yaml file):
2023-11-09 05:03:57 [INFO]: CloudFormationTemplateRegistry: building with: Watching **/*.{yaml,yml}, Untitled Files, Excluding /.*devfile\.(yaml|yml)/i, /.*[/\\]\.aws-sam([/\\].*|$)/
2023-11-09 05:04:06 [DEBUG]: CloudFormationTemplateRegistry: getInstance() requested, still initializing
2023-11-09 05:04:10 [DEBUG]: CloudFormationTemplateRegistry: getInstance() requested, still initializing
2023-11-09 05:04:32 [DEBUG]: CloudFormationTemplateRegistry: …
> fix: "Scanning..." progress message behavior

- src/codewhisperer/service/recommendationHandler.ts
- src/codewhisperer/util/codeWhispererSession.ts
- src/codewhisperer/util/telemetryHelper.ts
- src/test/codewhisperer/commands/onAcceptance.test.ts
- src/test/codewhisperer/service/recommendationHandler.test.ts
- src/test/codewhisperer/util/telemetryHelper.test.ts
Sending last recommendation request id for all the `userDecision` telemetry events in a session/trigger.
https://issues.amazon.com/issues/ConsolasIssue-12227
Send `userDecision` events with respective requestId of each recommendation in a session/trigger.
> fix(telemetry): wrong requestId in UserDecision (Prod data polluted)

- docs/develop.md
- package.json
- src/common/browserUtils.ts
Problem:
When running in "web mode" with a compute backend (as opposed to "pure web browser" mode), AWS Explorer and other features are disabled.
Solution:
Set a custom `setContext` key and use that instead.
> fix(web): missing AWS Explorer in web + compute

- src/shared/cloudformation/activation.ts
- src/shared/fs/templateRegistry.ts
- src/shared/fs/watchedFiles.ts
Problem:
The "Scanning..." message only shows busy status, it doesn't say how much work is left.
Solution:
Report incremental progress.
> feat: show "Scanning..." incremental progress

- src/auth/commands.ts
- src/auth/ui/vue/show.ts
- src/awsexplorer/activation.ts
- src/codewhisperer/activation.ts
- src/codewhisperer/commands/basicCommands.ts
- src/codewhisperer/commands/gettingStartedPageCommands.ts
- src/codewhisperer/commands/statusBarCommands.ts
- src/codewhisperer/commands/types.ts
- src/codewhisperer/explorer/codewhispererChildrenNodes.ts
- src/codewhisperer/explorer/codewhispererNode.ts
- src/codewhisperer/models/model.ts
- src/codewhisperer/service/inlineCompletionService.ts
- src/codewhisperer/vue/backend.ts
- src/test/codewhisperer/commands/basicCommands.test.ts
- src/test/codewhisperer/explorer/codewhispererChildrenNodes.test.ts
- src/test/codewhisperer/explorer/codewhispererNode.test.ts
- src/test/codewhisperer/service/inlineCompletionService.test.ts
- src/test/codewhisperer/testUtil.ts
When the CodeWhisperer status bar is clicked we will now show a QuickPick with different options for interacting with CodeWhisperer.
- The options in the quick pick are the same as the CodeWhisperer tree nodes in `Developer Tools` with the exception of a `sign out` option in the quick pick
- The CodeWhisperer status bar always exists and is always clickable
- Telemetry is emitted (`vscode_executeCommand`) that includes the name of the `command` that was executed as well as a `source` attribute (`codewhispererQuickPick` & `codewhispererTreeNode`) which indicates what caused it to be executed
- Updates to the CW status will be reflected in both the tree nodes and status bar
> codewhisperer: status bar quickpick when clicked

- src/codewhisperer/views/securityIssue/securityIssueWebview.ts
Open file from webview is opening a duplicate tab in the same active pane.
Open the file in view column one and not the active pane
> codewhisperer: open file in view column one

- src/auth/auth.ts
- src/auth/connection.ts
- src/auth/sso/cache.ts
- src/auth/ui/vue/authForms/manageIdentityCenter.vue
- src/auth/ui/vue/authForms/shared.vue
- src/auth/ui/vue/authForms/types.ts
- src/auth/ui/vue/serviceItemContent/codeCatalystContent.vue
- src/auth/ui/vue/show.ts
- src/codecatalyst/auth.ts
- src/codecatalyst/commands.ts
- src/codecatalyst/explorer.ts
- src/codecatalyst/model.ts
- src/codecatalyst/uriHandlers.ts
- src/codecatalyst/utils.ts
- src/test/codecatalyst/auth.test.ts
- src/test/fakeExtensionContext.ts
Amazon CodeCatalyst currently supports Builder ID connections. The CodeCatalyst team is working to enable IAM Identity Center connections for CodeCatalyst, including enabling IDC connections using AWS Toolkit for Visual Studio Code.
**This change adds the following:**
- Additions and changes within `CodeCatalystAuthenticationProvider` and surrounding modules to enable IDC connections.
- The changes account for switching connections.
- The changes account for extending scopes on existing connections.
- Minimal UI additions to CodeCatalyst connection form to support IDC connection flow (may be revised in subsequent revision)
- URI handler changes to support explicit IDC startUrl/region.
- `tryAutoConnect` changes to support IDC profiles.
Note that no changes were necessary for core …
> feat(codecatalyst): Add IDC connection logic

- src/codewhisperer/commands/invokeRecommendation.ts
- src/codewhisperer/service/inlineCompletionItemProvider.ts
- src/codewhisperer/service/inlineCompletionService.ts
- src/codewhisperer/service/keyStrokeHandler.ts
- src/codewhisperer/service/recommendationHandler.ts
- src/test/codewhisperer/commands/onInlineAcceptance.test.ts
1. Fixed an issue where clientCompoentLatency telemetry event would be sent every time when navigating the suggestions, where it should only be sent once when a first suggestion has been shown.
2. Fixed an issue where the requestIdList is not reset, causing a later check to not pass and stop sending the userTriggerDecisions.
3. Fixed an issue where spamming trigger will cause the invocation start time to reset to current time for each trigger action. This will cause the e2e latency to be recorded unexpectedly.
> CodeWhisperer: fix various VSC bugs

- CONTRIBUTING.md
- scripts/build/package.ts
- src/shared/extensions.ts
Problem:
package.ts generates "alpha" builds using version 1.9999. This was driven by the notion that we might want all "alpha" testers to be auto-updated if we ever bump the prod major version. But in practice there is no clear demarcation where or when that happens. And it means we need to bump the "alpha" version whenever we bump the prod major version.
Solution:
Use 99.x for "alpha" builds.
ref 991bfcb794c8699a9ffccdc26b29006a20febe28
> fix: use 99.x as alpha/beta version

- package-lock.json
- package.json
- src/codewhisperer/activation.ts
- src/codewhisperer/client/codewhisperer.ts
- src/codewhisperer/commands/basicCommands.ts
- src/codewhisperer/service/completionProvider.ts
- src/codewhisperer/service/featureConfigProvider.ts
- src/codewhisperer/service/inlineCompletionItemProvider.ts
- src/codewhisperer/service/recommendationHandler.ts
- src/codewhisperer/service/referenceLogViewProvider.ts
- src/codewhisperer/util/authUtil.ts
- src/codewhisperer/util/codeWhispererSession.ts
- src/codewhisperer/util/editorContext.ts
- src/codewhisperer/util/runtimeLanguageContext.ts
- src/codewhisperer/util/telemetryHelper.ts
- src/test/codewhisperer/commands/onAcceptance.test.ts
- src/test/codewhisperer/commands/onInlineAcceptance.test.ts
- src/test/codewhisperer/service/codewhisperer.test.ts
- src/test/codewhisperer/service/featureConfigProvider.test.ts
- src/test/codewhisperer/service/recommendationHandler.test.ts
- src/test/codewhisperer/testUtil.ts
- src/test/codewhisperer/util/telemetryHelper.test.ts
1. Add a component to fetch feature assignments every 30 mins, calling ListFeatureEvaluations API and cache values in memory.
2. Add a field in UserTriggerDecision codewhispererFeatureEvaluations to record all the feature configs in a string, which can be queried on Kibana
respective JB PR: https://github.com/aws/aws-toolkit-jetbrains/pull/3978
> CodeWhisperer: Add feature fetching component

- .changes/next-release/Feature-9f098b03-c8ed-4137-80cb-e7508d42a97f.json
- src/extension.ts
- src/shared/settings.ts
- src/test/shared/settingsConfiguration.test.ts
- src/test/utilities/testSettingsConfiguration.ts
feat(settings): "invalid settings.json" message cannot be disabled
Problem:
settings.json may be intentionally readonly, then "invalid
settings.json" is not helpful. #4043
Solution:
Only log a warning if settings.json is not writable, don't show
a message. If settings.json is invalid a message is still shown.
> feat(settings): "invalid settings.json" message cannot be disabled

- src/auth/sso/model.ts
- src/auth/ui/vue/show.ts
- src/codecatalyst/activation.ts
- src/codewhisperer/commands/basicCommands.ts
- src/codewhisperer/util/showSsoPrompt.ts
- src/test/codewhisperer/util/showSsoPrompt.test.ts
This fixes:
- CC auto connects on start to an existing valid connection
- CW Connection Prompter in C9 shows correct options when clicking `Start` node under CodeWHisperer Developer Tools
- The proceed to browser message contains the code since it was missing in C9 since C9 doesn't support the `detail` field in modal messages.
> codecatalyst: Cloud9 fixes

- src/auth/secondaryAuth.ts
- src/codewhisperer/util/authUtil.ts
In the Add Connection page we listen to auth
events in the backend. When one of these events
is fired the Add Connection page eventually checks if isEnterpriseSsoInUse. The issue is that this
uses a variable that is separately updated by
the event onDidChangeActiveConnection.
There is a race condition for when onDidChangeActiveConnection updates the variable used in isEnterpriseSsoInUse() versus when isEnterpriseSsoInUse() is actually called.
Also when SecondaryAuth.deleteConnection() is called the new state is not updated when the function is complete since we are relying on an event listener to do the final updating.
Get rid of the variable and whenever isEnterpriseSsoInUse() is called it will pull the latest state. Now we don't have to manage it.
Also in deleteConnection() do a final …
> fix: racecondition in cw auth change

- .changes/next-release/Bug Fix-2010cfac-f717-490d-b47c-5e3521cb5714.json
- src/codecatalyst/auth.ts
- src/codecatalyst/commands.ts
- src/codecatalyst/model.ts
- src/test/codecatalyst/auth.test.ts
When connecting to Dev Environment while not already authenticated locally, an error is displayed, which then requires manually working around the issue by entering startUrl through the main connect flow.
Based on the URI handler params, attempt to connect or switch connection.
> fix(codecatalyst): Try to ensure connection for Dev Environment URI handler flow

- src/test/setupUtil.ts
- src/testE2E/codecatalyst/client.test.ts
E2E tests fail when not ran locally.
- Update SSO login dialog regex to match latest.
- Update test util to accept 'test' propert of Mocha Context.
- Update data sent to lambda authorizer to match new SSO url dialog.
> fix: update e2e tests

- .changes/next-release/Feature-666cb5e9-eff1-41d9-bcf8-1d65cda2dd2c.json
- src/shared/clients/devenvClient.ts
MDE requires use of different endpoint in some VPC configurations.
Allow MDE to pass different endpoint as environment variable. (Default to current behavior.)
> feat(codecatalyst): Use MDE endpoint set by environment variable

- .changes/next-release/Feature-666cb5e9-eff1-41d9-bcf8-1d65cda2dd2c.json
- src/shared/clients/devenvClient.ts
Cherry-pick https://github.com/aws/aws-toolkit-vscode/pull/4077 to `feature/cloud9`
> fix(codecatalyst): get MDE endpoint from MDE-provided env var #4077

- .github/workflows/release.yml
- .github/workflows/release_notes.md
Problem:
The prerelease changelog might include items from the previous release,
or omit some items if the current changelog is very long.
Solution:
Use `perl` instead of `head` to get only the first section.
before:
- ...
- ...
- ...
after:
- ...
- ...
> fix(ci): improve prerelease changelog

- src/codewhisperer/commands/startTransformByQ.ts
- src/codewhisperer/models/model.ts
- src/codewhisperer/service/transformByQHandler.ts
- src/codewhisperer/service/transformationResultsViewProvider.ts
- src/test/codewhisperer/commands/transformByQ.test.ts
We run a shell command (`javap`) to determine the Java version of each of the projects open in the user's workspace. Running this command for each open project is totally unnecessary.
This fix shows the user as options to transform any of the projects open in their workspace, and then once they have selected a project, the validation checks are run (`javap` etc.) to check that it is a valid project. The solution is mostly a refactoring  -- the logic to do the validation checks was pre-existing, it is simply moved to happen after the user selects a project.
> fix(transform): do validation checks AFTER user picks project

- src/codewhisperer/commands/startSecurityScan.ts
- src/test/codewhisperer/commands/startSecurityScan.test.ts
This was added previously to fix build errors and is misreporting the number of issues with fixes.
Remove the hardcoded value assignment.
> fix(codewhisperer): remove hardcoded telemetry metric

- .changes/next-release/Bug Fix-5caa0d38-8b96-437c-9710-3b288794d9ab.json
- package.json
- src/codecatalyst/uriHandlers.ts
- src/extension.ts
- src/shared/vscode/uriHandler.ts
- src/test/codecatalyst/uriHandlers.test.ts
- src/test/shared/vscode/uriHandler.test.ts
Problem:
vscode may invoke our URI handler during startup, before Toolkit activation has finished (and thus before all Toolkit services have registered their path handlers). #4105
No handler found for: vscode://.../connect/codecatalyst URI
Solution:
- Do not call `vscode.window.registerUriHandler()` until after all Toolkit services have activated.
- Add "onUri" to package.json "activationEvents". It wasn't the root cause of the above issue, but it should be specified anyway. https://code.visualstudio.com/api/references/activation-events#onUri
- Improve visibility via logging.
> fix(codecatalyst): "No handler found" error

- .changes/next-release/Breaking Change-d11aa2b2-96e2-46f7-9a06-5fceab6299ec.json
- src/codewhisperer/service/transformByQHandler.ts
We want to make sure users cannot submit a project unless a pom.xml is present in the root directory, not anywhere in the project.
Enforce that pom.xml is in root directory specifically.
> fix(transform): check for pom.xml in root dir only

- src/codewhispererChat/editor/context/focusArea/focusAreaExtractor.ts
- src/test/codewhispererChat/editor/context/focusArea/focusAreaExtractor.test.ts
Intermittent 5xx errors are being returned from the backend due to invalid request payloads when customers have selected code on the first line of the file.
The root cause was identified as incorrect payload formatting that occurred under specific conditions. The payload generation logic has been updated to properly handle these edge cases, and additional unit tests have been written to validate the payload structure in these scenarios
> AmazonQ: Fix for incorrect code selection range values

- .changes/next-release/Bug Fix-d086954c-0bde-4ab8-9d07-7eac324faaf8.json
- src/codewhisperer/util/dependencyGraph/javaDependencyGraph.ts
- src/test/codewhisperer/util/dependencyGraph/javaDependencyGraph.test.ts
Security scans for Java code throws an error if its not compiled. This requirement should be removed since most detectors don't require compiled code to run a scan. 
- Don't throw an error if compilation output path is not set
- Don't throw an error if build files are not found
- If build files are found, still include them in the zip file
> codewhisperer: remove build requirement

- package-lock.json
- package.json
- src/ssmDocument/commands/createDocumentFromTemplate.ts
- src/stepFunctions/commands/visualizeStateMachine/aslVisualization.ts
- src/test/ssmDocument/commands/createDocumentFromTemplate.test.ts
- src/test/stepFunctions/commands/visualizeStateMachine.test.ts
Problem: 'yaml' is outdated and requires human intervention to migrate to V2. It is only used in a few places in the codebase, whereas everywhere else, a similar yaml parser js-yaml is used.
Solution: remove usage of 'yaml' and only use 'js-yaml', as it has some features that we need (ability to write out to a string and skip invalid JSON entries, which 'yaml' does not seem to offer). We do not require all the features of 'yaml' at this time. Also, remove "errors" field from the state machines parser -> webview message. It is not used by anything and was only accessible with 'yaml'.
In one case of 'yaml', we used the 'maxAliasCount' option to prevent users from submitting state machines with aliases in them. Aliases do not prevent publishing normally to step functions if used normally; I …
> refactor: remove yaml dependency, use js-yaml instead.

- .changes/next-release/Bug Fix-402cf60e-4ce2-4886-9133-b77af3b6f42b.json
- src/shared/logger/commands.ts
Problem: Interacting with other options in the Amazon Q and Explorer views ellipses menu can cause the view logs option (of the same tree) to open an empty file. Since this command and menu options are maintained in package.json only, vscode may not properly supply arguments which leads to the open logs command breaking.
Solution: Remove unused parameter, only one log file is used for toolkit logging.
> fix: help > open logs may not work after interacting with other options

- src/auth/ui/vue/show.ts
- src/codecatalyst/explorer.ts
Problem:
When a user connects to CC but skips the prompt to onboard a space, things appear to fail to the user even though things are fine. They will see a cancelled error under the Builder ID button and a "Sign in" node on the CodeCatalyst tree view.
Solution:
We ignore the error that gets raised if they cancel and successfully add the connection.
Also if they require onboarding we will show them the "You must onboard" node instead of the incorrect "You must sign in" node that we are currently showing. When they click this node it will open the CodeCatalyst page in the browser that guides them to onboard.
https://github.com/aws/aws-toolkit-vscode-staging/pull/1522
> codecatalyst: Bad auth state when adding connection + skip onboarding

- src/shared/cloudformation/activation.ts
Getting a template registry before activation returns `undefined` instead of a `NoopWatcher`. Thinking this might be the cause of https://github.com/aws/aws-toolkit-vscode/issues/4057
Return the `NoopWatcher` correctly.
> NoopWatcher returns correctly

- src/codewhisperer/models/constants.ts
Change in payload size for Go and Ruby from 1MB to 200KB for security scans
At present the payload size of Go and Ruby is 1MB.
Changed it to 200KB and If latency gets effected we can revert this back.
> CW: Change in payload size for Go and Ruby from 1MB to 200KB 

- src/amazonqFeatureDev/client/featureDev.ts
- src/amazonqFeatureDev/errors.ts
- src/amazonqFeatureDev/session/sessionState.ts
- src/shared/errors.ts
Currently featureDev errors are returning a generic failure. In the purpose of understanding the specific error with telemetry finding out if it was a 403 or a 409 was hard.
Add status code to api errors to track in telemetry.
> feat(amazonqFeatureDev, telemetry): improve generateApproach api error metrics and minor fixes.

- src/amazonq/auth/controller.ts
- src/amazonq/explorer/amazonQChildrenNodes.ts
- src/codewhisperer/commands/basicCommands.ts
- src/codewhisperer/util/authUtil.ts
- src/test/codewhisperer/util/authUtil.test.ts
Before we would always add missing scopes whenever an existing CW user was missing the new scopes for chat. This would be done during the reauthentication process automatically.
The issue is that we did not want this and only wanted to add missing Amazon Q/chat scopes when the user intentionally wanted them to be added.
- Don't always add missing scopes during `reauthenticate()`. Instead use an arg to determine if we should
- We will add missing scopes in the Chat "reauthenticate" prompt as well as the Amazon Q node.
- Everywhere else will simply reauthenticate without adding new scopes
> amazonQ: only add missing scopes intentionally

- .changes/next-release/Bug Fix-9755489d-974e-41a5-9031-f4e0a50ab9e7.json
- src/codecatalyst/commands.ts
Problem: Opening a dev env inside of the IDE will trigger logic to default to a builder ID sign in. This is because the function will not receive the proper information when opened from menu options (the connection variable is not defined when called this way), triggering the default path. Opening a dev env from the CodeCatalyst website will open it normally, because it passes the necessary information to the function that will not cause the default behavior to activate.
Solution: Check for valid connection state instead of relying on what is passed into the function. Also, remove Builder ID login as default, instead just route to the connections page. Although, this codepath should only run if something funky is going on.
By submitting this pull request, I confirm that my contribution is …
> fix(codecatalyst): no longer prompt builder ID sign in when opening dev env

- package-lock.json
- package.json
- src/amazonqFeatureDev/errors.ts
- src/amazonqFeatureDev/session/session.ts
- src/amazonqFeatureDev/session/sessionState.ts
- src/amazonqFeatureDev/util/files.ts
- src/amazonqFeatureDev/util/upload.ts
- src/test/amazonqFeatureDev/util/files.test.ts
featureDev needed to track errors in the metrics in a more detailed way.
add new metrics in order to get better error tracking.
This PR needs this dependency to be merged and in this PR the version of the library updated: https://github.com/aws/aws-toolkit-common/pull/645/files
> feat(amazonqFeatureDev): add new metrics to api operations

- .changes/next-release/Bug Fix-8dafab20-12b5-41a2-8786-889ec65cc70a.json
- src/codewhisperer/models/constants.ts
Security scans currently poll status every 5 seconds.
Increase the frequency to every 1 second.
> codewhisperer: update scan polling frequency

- src/shared/codelens/samTemplateCodeLensProvider.ts
Opening a YAML template will trigger a CFN registry load, even if SAM CodeLenses are disabled
Escape from the CodeLensProvider early (before calls to `getConfigsMappedToTemplates`)
* This shaves off file parsing, so this should represent a very slight speedup, even if the registry was already processed
* We don't want to not register the SamTemplateCodeLensProvider because then it won't be available if a user reactivates SAM CodeLenses halfway through a session
> Opening a SAM Template only triggers CFN registry if CodeLenses enabled

- src/shared/clients/codecatalystClient.ts
- src/shared/errors.ts
I think this is the best way to handle errors at the CodeCatalyst command level without forcibly handling errors for all commands the same way. This change should affect any errors coming through CodeCatalyst calls.
**CONSIDER:**
* Is this good enough for error consolidation?
* Should this be a warning or an error? That would have to be handled at the all-command level.
The following examples come from creating a valid Builder ID connection to CodeCatalyst, and modifying the cached credential files to make the access keys invalid, and then clicking "Clone Repository" in the CodeCatalyst view.
Old error message:
New error message:
> CodeCatalystClient throws ToolkitError on call

- src/auth/utils.ts
When the users sees a list of connections by clicking the AWS status bar icon, they can hover over a specific connection and delete it.
This adds a ui_click telemetry event when it is clicked.
> telemetry: ui_click when deleting connection from list

- src/codewhisperer/service/transformByQHandler.ts
@nkomonen-amazon reported an issue where CI was failing due to failure to include the result field in one of our metric emissions.
Add the result field.
> telemetry: add result field to metric

- src/extension.ts
The nodes in the CodeWhisperer view in Cloud9 sometimes don't work.
* Analyzing the browser console shows that the extension host disposes creates commands for the nodes and disposes them (these have a number tied to them as an "ID").
* Most of the time, the view picks up the most recent copy of the commands (the browser console shows the ID being executed when the node is clicked)
* Sometimes, this is tied to the ID that's disposed. In these cases, the node actions won't work, with no error feedback (outside the browser console)
Force a refresh of the CodeWhisperer view in Cloud9 only, 5 seconds after the end of the `extension.ts` `activate()` function.
* This disposes the actions and presumably recreates the nodes in the view
* It's hard to tell if this is truly a workaround/fix: since …
> Add timed refresh to Cloud9 CodeWhisperer view after load

- src/codecatalyst/uriHandlers.ts
- src/test/codecatalyst/uriHandlers.test.ts
Problem: If a user opens a vscode URI to open a dev environment and there are no IdC params, then the user is pointed to the login page instead of being routed to builder ID sign in. This means the user has to click the link again after signing in. 
Solution: Always default to builder ID if there are no IdC params in the URI, rather than prompt for sign in.
> fix(codecatalyst): default to builder ID sign in if URI contains no IdC params

- src/shared/vscode/commands2.ts
Example:
2023-12-15 12:28:11 [DEBUG]: telemetry: collapsing 4 "aws.previewStateMachine" metrics. key={}
> telemetry: improve collapse ("debounce") log message

- src/dev/activation.ts
- src/shared/ui/common/skipPrompter.ts
You can't display all mementos at once
Through dark debugger powers, we can display everything.
* ~~Need to try saving, or maybe turn this into a readonly editor.~~
* Pulling the content into an untitled new editor to prevent it from being processed by the virtual file handler.
* I'm not sure if we can show secret storage
* ...it also doesn't look like we're using the secret storage???
> feat(dev): display all globalState

- buildspec/linuxIntegrationTests.yml
- scripts/test/launchTestUtilities.ts
- src/test/techdebt.test.ts
- src/testInteg/sam.test.ts
SAM integ tests are failing.
Before, we previously created https://github.com/aws/aws-toolkit-vscode/pull/3726/files to use a specific sam cli version in our integration tests since the following version caused CI to fail. The version of sam cli we set is very old now.
Now, this PR removes explicitly setting the sam cli version to download during CI and instead grabs the latest version.
Now when running `/runIntegrationTests` the sam tests should stop failing.
The python codelens tests were failing. This was due to a bug in a newer python extension version.
Now, we lock to the last working version. More info in IDE-12283
> SAM: fix failing SAM tests

- .changes/next-release/Bug Fix-d5eeec6a-5371-4075-8442-66c70c253202.json
- .changes/next-release/Feature-20c6488b-1750-4ca6-9eb3-b509f49f194b.json
- src/amazonqGumby/telemetry/codeTransformTelemetry.ts
- src/codewhisperer/commands/startTransformByQ.ts
- src/codewhisperer/service/transformByQHandler.ts
- src/codewhisperer/service/transformationResultsViewProvider.ts
1. Code Transform artifact upload and download metrics for VSCode did not have totalByteSize.
2. Need to emit dependenciesCopied metric.
3. Several Code Transform metrics did not have `result` field.
1. Include totalByteSize where applicable.
2. Emit dependenciesCopied metric.
3. Add `result` field to metrics.
Validated dependenciesCopied emitted:
- `telemetry: emitted metric "codeTransform_dependenciesCopied" -> {"Metadata":[{"Key":"parentMetric","Value":"vscode_executeCommand"},{"Key":"codeTransformSessionId","Value":"<redacted>"},{"Key":"result","Value":"Succeeded"},{"Key":"awsAccount","Value":"not-set"},{"Key":"awsRegion","Value":"us-west-2"}],"MetricName":"codeTransform_dependenciesCopied","Value":1,"Unit":"None","Passive":false,"EpochTimestamp":1702660044892}`
Validated metrics are …
> telemetry: add code transform data byte size and result field to metrics

- .changes/next-release/Bug Fix-ec18555e-d716-40b5-b8d1-54dad851fdc2.json
- src/codewhisperer/commands/onAcceptance.ts
- src/codewhisperer/commands/onInlineAcceptance.ts
- src/codewhisperer/commands/startSecurityScan.ts
- src/codewhisperer/service/completionProvider.ts
- src/codewhisperer/service/inlineCompletionItemProvider.ts
- src/codewhisperer/service/recommendationHandler.ts
- src/codewhisperer/util/editorContext.ts
- src/codewhisperer/util/runtimeLanguageContext.ts
- src/codewhisperer/util/telemetryHelper.ts
- src/test/codewhisperer/util/runtimeLanguageContext.test.ts
CodeWhisperer needs terraform plugin extension to generate code suggestions for `tf` and `hcl` files, as `tf` and `hcl` files are recognized as `plaintext` by VSCode. 
- This issue can be resolved by categorizing the files based on file format/ file extensions instead of depending on editor document language.
- Code generation will be independent of external plugin extensions.
> fix(codewhisperer): support code generation for IaC languages without external plugin extensions

- src/codewhisperer/commands/startTransformByQ.ts
- src/codewhisperer/models/constants.ts
- src/codewhisperer/models/model.ts
- src/codewhisperer/service/transformByQHandler.ts
- src/codewhisperer/service/transformationHubViewProvider.ts
- src/codewhisperer/service/transformationResultsViewProvider.ts
- src/test/codewhisperer/commands/transformByQ.test.ts
This PR breaks down https://github.com/aws/aws-toolkit-vscode/pull/4183. This is part 1/3.
Had some unnecessary sleep statements. Missing jobId to the table shown to users. Unnecessary modals shown when displaying notifications. Possible bug when zipping dependencies if a dependency is named "target" (no evidence that this has occurred).
PR 2/3 will add the jobId to the metadata when users submit in-IDE feedback. PR 3/3 will formally remove the "he" and "proxyquire" dependencies.
Remove sleep statements. Add jobId to table. Remove modals. Add an extra check when zipping dependencies.
> fix: reorder input checks, remove modals, add jobId to table

- src/amazonqFeatureDev/session/session.ts
There is currently a problem when using `/dev` inside Q which displays the 
```
Sorry, we encountered a problem when processing your request. Amazon Q feature development request failed: Conversation id must exist before continuing
``` 
error message every time a new conversation is started.
Retrying the operation is a workaround for this, and will make the conversation work as expected.
This CR adds a missing `await` to the creation of the conversation. The missing `await` caused the error because the toolkit tried reading the `conversationId` before it was populated.
> fix: Fix missing conversationId in /dev

- src/amazonqGumby/telemetry/codeTransformTelemetry.ts
- src/codewhisperer/commands/startTransformByQ.ts
Telemetry is reporting different strings for Java versions
Typecast/check the strings reported against the aws-toolkit-common definitions
> fix(telemetry): normalize JDK strings

- package-lock.json
- package.json
- src/codewhisperer/commands/basicCommands.ts
- src/codewhisperer/models/model.ts
- src/codewhisperer/service/securityIssueHoverProvider.ts
- src/codewhisperer/service/securityScanHandler.ts
- src/shared/telemetry/vscodeTelemetry.json
- src/test/codewhisperer/service/securityIssueHoverProvider.test.ts
- Added `ruleId` to code scan telemetry metrics
- Added new metric `codewhisperer_codeScanIssueViewDetails`
> telemetry: add rule id to security scan metrics

- .changes/next-release/Bug Fix-524dba3b-28f6-4aef-b5f6-2624b73c868c.json
- src/codewhisperer/service/recommendationHandler.ts
In CW error handling code path, a throwable is directly cast to `string` type, which doesn't contain `includes` member function. 
Thus it will cause a NPE when the `finally` block is executed where there is a `include` method call https://github.com/aws/aws-toolkit-vscode/blob/24cd83683bd8366485eb60e7be49acae735ec89d/src/codewhisperer/service/recommendationHandler.ts#L328-L329
> fix(codewhisperer): fix incorrect type casting if error is not AwsError

- src/codewhisperer/util/authUtil.ts
Problem:
The `onDidChangeActiveConnection` event may fire before various components {and their commands) are activated (if ever). This manifests in the test logs as:
rejected promise not handled within 1 second:
Error: command 'aws.codeWhisperer.refresh' not found
This issue became more visible while working on https://github.com/aws/aws-toolkit-vscode/pull/1638
Solution:
Use `tryExecute()` to run the commands.
> fix(auth): command 'aws.codeWhisperer.refresh' not found

- .changes/next-release/Bug Fix-29e2ab3a-6bef-49c4-874c-05752122ea7b.json
- src/codewhisperer/commands/startSecurityScan.ts
After running a security scan, clicking "Show Scanned Files" takes you to a blank output panel unless log level is set to `verbose`.
Log the output using `info` level.
> fix(codewhisperer): "Show Scanned Files" shows empty logs

- buildspec/linuxTests.yml
When nodejs reports `rejected promise not handled`, CI does not fail. The CI test logs must be manually inspected to notice these problems. Requiring `await` #1638 will help, but still misses some cases.
Fail if "rejected promise not handled" is found in the test output. This is done in the CI script because the messages are from nodejs and I haven't found a way to scan the nodejs output from our test runner.
rejected promise not handled within 1 second: AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
rejected promise not handled within 1 second: Error: Download code bindings cancelled
rejected promise not handled within 1 second: Error: EACCES: permission denied, mkdir '/my'
rejected promise not handled within 1 second: Error: Error stopping job
rejected promise not …
> ci: fail on "rejected promise not handled"

- src/test/cloudWatchLogs/commands/saveCurrentLogDataContent.test.ts
Problem:
rejected promise not handled within 1 second: CodeExpectedError: cannot open notCloudWatch:hahahaha. Detail: Unable to resolve resource notCloudWatch:hahahaha
stack trace: CodeExpectedError: cannot open notCloudWatch:hahahaha. Detail: Unable to resolve resource notCloudWatch:hahahaha
Solution:
Assert the failure.
> fix(tests): "rejected promise not handled"

- src/codewhisperer/client/user-service-2.json
- src/codewhisperer/tracker/codewhispererTracker.ts
- src/codewhispererChat/controllers/chat/chatRequest/converter.ts
- src/codewhispererChat/controllers/chat/telemetryHelper.ts
CWSPR send telemetry API now supports 3 new event types: ChatAddMessageEvent, ChatInteractWithMessageEvent and ChatUserModificationEvent.
> Update CWSPR telemetry client as per API model changes.

- src/codewhisperer/commands/startTransformByQ.ts
- src/codewhisperer/models/constants.ts
- src/codewhisperer/service/transformationResultsViewProvider.ts
- src/feedback/vue/submitFeedback.ts
- src/shared/utilities/textUtilities.ts
- src/testInteg/amazonqGumby/transformByQ.test.ts
Users submitting feedback in VS Code had issues with Transform by Q but we had no ways to investigate.
EDIT: we are currently trying to determine if the jobId is permitted to be included in the feedback, so ignore the above
Updated problem:
- 'he' dependency used but not necessary: https://sim.amazon.com/issues/EGCP-40
- stopJob error not caught
- not all constants were in the constants file
- no integration test for verifying that the pre-signed upload URL uses HTTPS and sets a 60 second timeout (needed for AppSec)
Add the jobId to the feedback (when jobId is not empty, meaning the user must have started a transformation job).
EDIT: we are currently trying to determine if the jobId is permitted to be included in the feedback, so ignore the above
Updated solution:
- use a simple utility …
>  fix: error handling, move constants, add test, remove dep

- .changes/next-release/Bug Fix-219eee10-03c2-4122-9bf8-30f0c4ce6f88.json
- src/codewhispererChat/editor/context/focusArea/focusAreaExtractor.ts
- src/test/codewhispererChat/editor/context/focusArea/focusAreaExtractor.test.ts
There is an issue with the range trimming logic when a customer's selection is limited to a single line. The system does not handle this case correctly and trims the selection inappropriately. This results in invalid range trimming that needs to be addressed.
An invalid range parameter results in 4xx client errors.
The algorithm was modified and the changes were validated through the addition of new unit tests.
> AmazonQ: Incorrect range fix

- src/testInteg/sam.test.ts
Problem: v0.40.1 of go changes how the extension is activated and breaks the integ tests.
Solution: Remove go activation, it is not required for integ tests.
> fix(integ): remove go extension activation.

- .changes/next-release/Bug Fix-18261950-9a6c-4fdf-b618-5c45ffaa3e82.json
- src/codewhisperer/service/keyStrokeHandler.ts
In AWS Cloud9, accepting CW reco will trigger one more time of CodeWhisperer suggestion.
Ignore the document change event when accepting a code recommendation in AWS Cloud9. 
This PR will be kept in draft state until 12/18/2023.
> fix(codewhisperer): cloud9 chain suggestion bug

- .changes/next-release/Removal-ca09407d-b3ce-43df-a236-d12f7fa888f3.json
- docs/develop.md
- package.json
- src/codewhisperer/commands/basicCommands.ts
- src/codewhisperer/commands/invokeRecommendation.ts
- src/codewhisperer/util/authUtil.ts
Problem: Ellpises menus for Q/CW will display "Switch Connections", implying that the connection can be switched between other IdC/Builder ID connections on the fly. This isn't supported currently. Also, 'Add new connection' is displayed when already signed in, implying that you can add these new connections to swap to.
Solution: Remove 'Switch Connections' menu item, and only show 'Add new connection' when not signed in.
Also, rename the global context variables to to be more descriptive/not be in all caps.
> feat(auth): don't display switch connections/add new connections in Q/CW ellipses menus

- src/codewhisperer/activation.ts
- src/codewhisperer/commands/basicCommands.ts
- src/codewhisperer/commands/invokeRecommendation.ts
- src/codewhisperer/commands/startSecurityScan.ts
- src/codewhisperer/commands/startTransformByQ.ts
- src/codewhisperer/service/featureConfigProvider.ts
- src/codewhisperer/service/inlineCompletionService.ts
- src/codewhisperer/service/keyStrokeHandler.ts
- src/codewhisperer/service/recommendationHandler.ts
- src/codewhisperer/service/referenceLogViewProvider.ts
- src/codewhisperer/service/transformByQHandler.ts
- src/codewhisperer/service/transformationHubViewProvider.ts
- src/codewhisperer/service/transformationResultsViewProvider.ts
- src/codewhisperer/tracker/codewhispererTracker.ts
- src/codewhisperer/util/authUtil.ts
- src/codewhisperer/util/customizationUtil.ts
- src/codewhisperer/views/securityIssue/securityIssueWebview.ts
- src/codewhisperer/vue/backend.ts
- src/codewhispererChat/commands/registerCommands.ts
- src/test/codewhisperer/tracker/codewhispererTracker.test.ts
Continued from:
- https://github.com/aws/aws-toolkit-vscode/pull/4202
- #1638
- All promises or async calls should use `await`, or end with `.catch()`.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises
- Async calls accidentally forget `await`.
- Example: 8863ba4a799e
- Test logs show "rejected promise not handled":
```
rejected promise not handled within 1 second: HTTPError: Response code 403 (rate limit exceeded)
rejected promise not handled within 1 second: Error: command 'aws.codeWhisperer.refreshStatusBar' not found
rejected promise not handled within 1 second: HTTPError: Response code 404 (Not Found)
rejected promise not handled within 1 second: CodeExpectedError: cannot open notCloudWatch:hahahaha. Detail: Unable to resolve resource notCloudWatch:hahahaha …
```
> lint: require "await" or .catch() on async calls

- src/codewhisperer/service/securityIssueProvider.ts
- src/codewhisperer/util/dependencyGraph/cloudformationDependencyGraph.ts
https://github.com/aws/aws-toolkit-vscode/issues/4203
Add a check for `event.contentChanges` is `undefined` in `handleDocumentChange` function. If yes, `return`
> Fix: codewhisperer securityIssueProvider: "TypeError: Cannot read properties of undefined (reading 'range')"

- src/test/dynamicResources/awsResourceManager.test.ts
Since ca3dc32b2db9, `globals.schemaService` is temporarily stubbed in `awsResourceManager.test.ts`. Those tests open some filetypes that are handled by `awsFiletypes.ts`, which tries to process them by calling `SchemaService.isMapped`.
rejected promise not handled within 1 second: TypeError: SchemaService.isMapped was called uninitialized.
stack trace: TypeError: SchemaService.isMapped was called uninitialized.
at Proxy.<anonymous> (d:\a\aws-toolkit-vscode\aws-toolkit-vscode\src\test\utilities\stubber.ts:48:27)
at Object.invoke (d:\a\aws-toolkit-vscode\aws-toolkit-vscode\node_modules\sinon\lib\sinon\behavior.js:177:32)
...
at f.value (d:\a\aws-toolkit-vscode\aws-toolkit-vscode\src\shared\awsFiletypes.ts:69:59)
Stub `isMapped`. The value that it returns isn't important because the tests …
> fix(tests): "SchemaService.isMapped was called uninitialized"

- buildspec/linuxTests.yml
- buildspec/shared/common.sh
- buildspec/shared/linux-pre_build.sh
Deprecated dependencies may not be noticed for a long time.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated winston@3.7.1: Please use version 3.6.0 or >3.7.1 when available due to https://github.com/winstonjs/winston/issues/2103
Collect these warnings when running CI.
TODO: fail if new warnings are found.
> ci: report "npm WARN deprecated"

- .changes/next-release/Feature-db8301de-5d0d-4fdb-b0a3-4a55703c9de0.json
- package.json
- src/awsexplorer/activation.ts
- src/dev/activation.ts
- src/dev/codecatalyst.ts
- src/extension.ts
- src/extensionShared.ts
- src/extensionWeb.ts
- src/feedback/vue/submitFeedback.ts
Adds functionality for sharing some basic global commands between browser and desktop versions of the toolkit. Included commands:
- View Toolkit Documentation
- View Source on Github
- About Toolkit
- Report Toolkit Issue
- List Commands (*shared but inaccessible in browser at the moment)
- Send Feedback (*does not load in browser yet until vue/webview support is implemented on our end)
Not included yet:
- View Quick Start
Also removes the use of ExtContext type where used with these commands. Instead, refactor code to only pass what was used in this, which is just the actual vscode extension context.
Send Feedback... was disabled in the browser because vue is not yet supported and this feature may not be necessary for an initial
browser version of the toolkit.
tested both browser and …
> feature(browser): enable basic global commands to be shared between browser/non-browser

- .changes/next-release/Removal-626942e3-aa4b-43c5-a198-0f22bce19919.json
- package.json
- src/extension.ts
Problem: 'View Quick Start` command is redundant- it is the same as the marketplace page users see when they install the plugin.
Solution: Remove this command from appearing in non-Cloud9 instances. Users who use Cloud9 would generally not have installed the toolkit themselves, so displaying a guide for the provided plugin may be helpful.
Tested in regular and C9 instances.
> feat(commands): disable 'View Quick Start' command for non-cloud9 instances

- .changes/next-release/Bug Fix-d4bf021f-adee-4cba-9737-b371d0be85ff.json
- package.json
Problem:
"Transformation Hub" is always visible, even when Transform feature is not enabled.
Solution:
Define a "when" condition.
> fix(amazonq): "Transformation Hub" is always visible

- src/test/codewhisperer/service/telemetry.test.ts
When running this test file locally many tests fail if you deselect the window since the tests type in to it. It will run fine in CI for the most part.
Eventually have the CW team move this to the integration tests.
Reported issue: https://github.com/aws/aws-toolkit-vscode/issues/4203
> codewhisperer: skip flaky tests

- src/codewhisperer/commands/startTransformByQ.ts
- src/codewhisperer/service/transformByQHandler.ts
- src/codewhisperer/service/transformationResultsViewProvider.ts
A few CodeTransform metrics were missing for VSCode:
- totalRunTime
- mvnBuildFailed
- vcsViewerClicked
- vcsDiffViewerVisible
- logGeneralError
Add the above metrics.
```
// totalRunTime
2024-01-02 11:37:06 [DEBUG]: telemetry: emitted metric "codeTransform_totalRunTime" -> {"Metadata":[{"Key":"parentMetric","Value":"vscode_executeCommand"},{"Key":"codeTransformSessionId","Value":"9d47005a-678f-45e9-a450-a9caf37009a5"},{"Key":"codeTransformResultStatusMessage","Value":"JobCompletedSuccessfully"},{"Key":"codeTransformRunTimeLatency","Value":"246047"},{"Key":"result","Value":"Succeeded"},{"Key":"awsAccount","Value":"not-set"},{"Key":"awsRegion","Value":"us-west-2"}],"MetricName":"codeTransform_totalRunTime","Value":1,"Unit":"None","Passive":true,"EpochTimestamp":1704224226707}
// …
```
> fix: add missing code transform telemetry

- src/testInteg/codewhisperer/e2e/referenceTracker.test.ts
- src/testInteg/codewhisperer/e2e/securityScan.test.ts
- src/testInteg/codewhisperer/e2e/serviceInvocations.test.ts
Since 65e65fcaf3be, integ tests fail with weird symptom:
CodeWhisperer security scan
"before each" hook for "codescan request for file in unsupported language fails to generate dependency graph and causes scan setup to fail":
sync skip; aborting execution
CodeWhisperer service invocation
"before each" hook for "invocation in unsupported language does not generate a request":
sync skip; aborting execution
Seems like a race condition, or maybe a quirk of Mocha:
- With `beforeEach(async function…`, the Mocha test runner fails with the above message.
- With non-async `beforeEach(function…`, Mocha seems happy and reports  the test as skipped, without failing the run.
- To unblock CI in the near-term, use `void resetCodeWhispererGlobalVariables()`  instead of trying to properly await it.
- …
> fix(testInteg): "sync skip; aborting execution"

- src/test/codewhisperer/service/keyStrokeHandler.test.ts
Unhandled promise rejections in test logs:
rejected promise not handled within 1 second: AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
true !== false
at testShouldInvoke (/codebuild/output/src4225802595/src/github.com/aws/aws-toolkit-vscode/src/test/codewhisperer/service/keyStrokeHandler.test.ts:156:20)
at async /codebuild/output/src4225802595/src/github.com/aws/aws-toolkit-vscode/src/test/codewhisperer/service/keyStrokeHandler.test.ts:138:17
The test failure was NOT failing CI because the unhandled rejection was silently missed.
Fix the for-loop to `await` correctly.
Now the test fails correctly:
```
1 failing
1) keyStrokeHandler
processKeyStroke
Should skip invoking if there is immediate right context on the same line and not a single }:
AssertionError …
```
> fix(tests): "rejected promise … AssertionError"

- src/s3/commands/openFile.ts
- src/s3/fileViewerManager.ts
- src/test/s3/util/fileViewerManager.test.ts
Problem:
Lots of "Unable to read file" noise in the test logs:
FileViewerManager
✔ prompts if file size is greater than 4MB
✔ throws if the user cancels a download
opens text files
No file system provider found for resource 's3-edit-test:/us-west-2/bucket-name/big-image.jpg'
✔ opens a new editor if no document exists
✔ closes the read-only tab when opening in edit mode (70ms)
Unable to read file 's3-read-test:/us-west-2/bucket-name/test1.txt' (Error): Error: Unable to read file 's3-read-test:/us-west-2/bucket-name/test1.txt' (Error)
at h.doReadFileStream (vscode-file://…)
at async p.doRead (vscode-file://…)
at async p.readStream (vscode-file://…)
at async wr.resolveFromFile (vscode-file://…)
✔ re-uses tabs in edit mode when opening as read-only
✔ can open in edit mode, showing a warning …
> fix(tests): "Unable to read file 's3-read-test:..."

- .changes/next-release/Bug Fix-335f2fb2-ad96-4031-8777-1edba11b4d21.json
- package-lock.json
- package.json
- src/amazonq/webview/ui/apps/amazonqCommonsConnector.ts
- src/amazonq/webview/ui/apps/cwChatConnector.ts
- src/amazonq/webview/ui/apps/featureDevChatConnector.ts
- src/amazonq/webview/ui/connector.ts
- src/amazonq/webview/ui/followUps/generator.ts
- src/amazonq/webview/ui/followUps/handler.ts
- src/amazonq/webview/ui/followUps/model.ts
- src/amazonq/webview/ui/main.ts
- src/amazonq/webview/ui/messages/controller.ts
- src/amazonq/webview/ui/messages/handler.ts
- src/amazonq/webview/ui/quickActions/generator.ts
- src/amazonq/webview/ui/quickActions/handler.ts
- src/amazonq/webview/ui/tabs/generator.ts
- src/amazonqFeatureDev/controllers/chat/controller.ts
- src/amazonqFeatureDev/controllers/chat/messenger/messenger.ts
- src/amazonqFeatureDev/views/connector/connector.ts
With the new version of VSCode, they've implemented a global styling for code blocks to give background color to the texts inside them which also effects the code blocks in the Q Chat too. 
[MynahUI 3.3.2](https://github.com/aws/mynah-ui/releases/tag/v3.3.2) adds code block background color as inherited from parent. 
> fix(amazonq): code block styling inherited from vscode

- .changes/next-release/Feature-9c583c77-3b07-4c5e-b5c2-ba32b9d29963.json
- src/codewhisperer/util/customizationUtil.ts
when user's selected customization is no longer available, we want to prompt them to select a new one
add action to the notification, and make it a warning instead of info
> codewhisperer: add action to customization notification 

- .github/dependabot.yml
Dependabot updates are much less frequent. No way to troubleshoot, but correlates with the `groups` directive added in 06507c380c67 (4 months ago).
see also https://github.com/aws/aws-toolkit-common/pull/666
- Review the inscrutable documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
- Remove the `dependency-type: production` directive.
- Add the `allow: dependency-name: *` directive.
- Note: intentionally _not_ using ["allow: dependency-type:all" directive](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow); it enables updates for _transitive_ dependencies.
By submitting this pull request, I confirm that my …
> fix: missing dependabot updates

- .changes/next-release/Bug Fix-ff0dcc4b-4981-43b3-9c16-75a91b5a43a6.json
- src/shared/sam/debugger/awsSamDebugConfigurationValidator.ts
`validateTemplateConfig()` fails if the given resource is "AWS::Lambda::Function", but:
1. its error message implies that "AWS::Lambda::Function" is allowed
2. 7b5aae7cf1133539e6a1d1070f9385a0608b13af implies that "AWS::Lambda::Function" is allowed
3. `getResourcesForHandlerFromTemplateDatum()` allows "AWS::Lambda::Function": https://github.com/aws/aws-toolkit-vscode/blob/8704f2cedb065087d7a85c9a9c40fc63d296f8cf/src/shared/fs/templateRegistry.ts#L184
ref #4281
Update the condition to allow "AWS::Lambda::Function".
> fix(sam): allow "AWS::Lambda::Function" when validating

- scripts/test/launchTestUtilities.ts
- scripts/test/test.ts
- scripts/test/testE2E.ts
- scripts/test/testInteg.ts
- src/test/techdebt.test.ts
- src/testInteg/shared/extensions/git.test.ts
Just doing some tidying up after learning how our test execution works.
- Behaviour is untouched
- Methods are reordered
- 'export' is removed from methods that do not need it
- runToolkitTests() is generalized to remove duplication in scripts/test/test.ts
> refactor: CI test run scripts

- .changes/next-release/Bug Fix-3f2c34ab-615e-4501-b697-75b38a7f4c39.json
- src/codewhisperer/service/inlineCompletionItemProvider.ts
- src/test/codewhisperer/service/inlineCompletionService.test.ts
`rightContext.trim()` will result in unexpected right context merging. Should remove `trim()`
https://github.com/aws/aws-toolkit-vscode/assets/96078566/4bf8d1fd-6779-4468-96a6-4b2720c13fd7
https://github.com/aws/aws-toolkit-vscode/assets/96078566/81298b12-77a3-48a8-adf4-4ca162aa5f0d
> fix(codewhisperer): right context merge

- .changes/next-release/Feature-a4a67f74-2ea2-4e18-9864-c8904e0128e6.json
- src/codewhisperer/models/constants.ts
- src/extensionWeb.ts
- src/shared/logger/activation.ts
- src/shared/logger/outputChannel.ts
- src/shared/logger/outputChannelTransport.ts
- src/shared/sam/cli/samCliLocalInvoke.ts
- src/test/testUtil.ts
`vscode.LogOutputChannel` is now available via `createOutputChannel(..., { log: true })`, for improved highlighting and presentation of log-like output in VSCode, but AWS Toolkit still uses the old `vscode.OutputChannel` interface.
- Use `vscode.LogOutputChannel` when possible.
- Change SAM output to "info" level instead of "error" level.
> feat(sam): improve rendering of SAM output

- .changes/next-release/Bug Fix-454d780d-97bc-49af-9391-527808d8bd33.json
- src/codewhisperer/service/transformByQHandler.ts
- src/codewhisperer/service/transformationResultsViewProvider.ts
A previous PR set shell to true for a shell command we run. This can lead to issues since special characters such as $ will be interpreted by the shell.
A smaller issue: the summary.md file was not opening automatically due to the "await" keyword.
Set shell to false. Remove "await" keyword.
> fix(gumby): set shell to false

- src/shared/logger/outputChannelTransport.ts
Followup to #4285.
`vscode.LogOutputChannel` loglevel is currently readonly:
https://github.com/microsoft/vscode/issues/170450
https://github.com/PowerShell/vscode-powershell/issues/4441
So `debug()` will just drop messages unless the user has increased vscode's log-level.
Write "debug" logs using `info()` until vscode adds a way to set the loglevel.
> fix(logging): "debug" messages not shown in "AWS Toolkit Logs" channel

- src/extension.ts
- src/shared/logger/commands.ts
2024-01-16 09:26:21 [WARN]: Metric Event did not pass validation: Metric `toolkit_init` was emitted without the `result` property.
2024-01-16 09:26:39 [WARN]: Metric Event did not pass validation: Metric `toolkit_viewLogs` was emitted without the `result` property.
> fix(telemetry): metrics emitted without the `result` property

- .changes/next-release/Feature-46a5faf6-6909-48b4-bce3-d74e390b5519.json
- src/codewhisperer/commands/startTransformByQ.ts
- src/codewhisperer/models/constants.ts
- src/codewhisperer/service/transformByQHandler.ts
When `mvn` fails, we want to run `mvnw` because that may succeed, since the user could have the Maven wrapper in their workspace despite not having Maven installed.
Run `mvnw` when `mvn` fails. Some smaller things done in this PR: 1) slight renaming and 2) collect input in a simpler way (no need to use `MultiStepInputFlowController` since we only collect 1 piece of input).
> feat(gumby): run mvnw if mvn fails

- src/amazonqFeatureDev/util/upload.ts
- src/applicationcomposer/webviewManager.ts
- src/codewhisperer/service/securityScanHandler.ts
- src/codewhisperer/service/transformByQHandler.ts
- src/common/request.ts
- src/test/amazonqFeatureDev/session/sessionState.test.ts
- src/test/codewhisperer/commands/startSecurityScan.test.ts
- src/test/common/request.test.ts
- src/testE2E/amazonqGumby/transformByQ.test.ts
- src/testInteg/common/request.ts
`got` package is not available in the browser. Replace usage with common `fetch` from `request.ts`
- Also refactors request.ts fetch for testing and current usages of the common fetch.
- Other minor code refactors around some usage of the fetch code.
Manual testing ongoing.
> browser: remove usage of got in codewhisperer

- .changes/next-release/Bug Fix-80b20b86-cc12-4387-976c-681c09cbd942.json
- .github/workflows/node.js.yml
- buildspec/linuxE2ETests.yml
- buildspec/linuxIntegrationTests.yml
- buildspec/linuxTests.yml
- buildspec/windowsTests.yml
- src/shared/utilities/textUtilities.ts
- src/test/cloudWatchLogs/commands/saveCurrentLogDataContent.test.ts
- src/test/cloudWatchLogs/document/textContent.test.ts
- src/test/cloudWatchLogs/registry/logDataRegistry.test.ts
- src/test/globalSetup.test.ts
- src/test/iot/explorer/iotPolicyVersionNode.test.ts
- src/test/s3/explorer/s3FileNode.test.ts
- src/test/shared/utilities/textUtilities.test.ts
Users on Cloud9 (Node.js 16) cannot view the content of an S3 bucket since Toolkit v2.3.0 (https://github.com/aws/aws-toolkit-vscode/pull/4163).
2024-01-17 13:59:54 [ERROR]: [RangeError: Value longOffset out of range for Intl.DateTimeFormat options property timeZoneName
at new DateTimeFormat (<anonymous>)
at Sv (/…/dist/src/main.js:2653:1432)
Nodejs 16 only supports `timeZoneName: "short" | "long"`.
- Use `timeZoneName="short"` for Cloud9.
- Use `timeZoneName="shortOffset"` for VSCode; the "long" format is unnecessarily verbose.
- Add tests.
- Set a fixed timezone in CI using the $TZ env var. (No other way to force a timezone in Nodejs / javascript.)
> fix(cloud9): error when expanding S3 folder

- src/shared/logger/commands.ts
"View Toolkit Logs" command may show an error in Cloud9:
2024-01-18 00:33:13 [ERROR]: aws.viewLogsAtMessage: Error: Command 'workbench.action.files.revert' not found.
The `workbench.action.files.revert` command has existed since at least 2017, and definitely exists in vscode 1.68...
https://github.com/microsoft/vscode/commit/9e5c7d0274755b2abbe6267e5601d32f9585f21c\
Use tryExecute(), because the use of "workbench.action.files.revert" is a best-effort workaround anyway.
> fix(cloud9): "Failed to run command: aws.viewLogsAtMessage"

- package-lock.json
- package.json
$ npm audit
@koa/cors  <5.0.0
Severity: high
Overly permissive origin policy - https://github.com/advisories/GHSA-qxrj-hx23-xp82
fix available via `npm audit fix --force`
Will install @vscode/test-web@0.0.50, which is a breaking change
node_modules/@koa/cors
@vscode/test-web  0.0.24 - 0.0.49
Depends on vulnerable versions of @koa/cors
node_modules/@vscode/test-web
2 high severity vulnerabilities
> deps: update "@vscode/test-web"

- scripts/test/launchTestUtilities.ts
- src/test/cloudWatchLogs/registry/logDataRegistry.test.ts
- src/test/testRunner.ts
In #4297 we explicitly set the TZ in a part of the code that CI uses, but when running the unit tests locally it does not execute that part of the code.
Due to this the tests still fail when run locally.
Solution:
Add the TZ assignment to a part of the code that occurs a bit later, but will execute for both the CI and local tests Now unit tests will pass when run locally.
The initial reason was that some documentation said if the `Date` object was used before assigning the TZ it would lock in the users actual TZ and overriding the env var would not work anymore. But after testing this seems to work fine.
> tests: explicitly set TZ for local tests

- .changes/next-release/Bug Fix-acaea338-3c74-41b5-b09a-839806679551.json
- src/applicationcomposer/messageHandlers/deployMessageHandler.ts
- src/applicationcomposer/webviewManager.ts
- src/auth/utils.ts
- src/shared/sam/sync.ts
- src/shared/utilities/messages.ts
The built-in SAM Sync functionality provides an ambiguous error message when the user is signed in with SSO or Builder ID. The only supported form of authentication is IAM credentials. Otherwise, when the user attempts to sync, they will get this error message:
This can be confusing to the user, especially if they are using IAM Identity Center for authentication.
This adds a modal to inform the user that their current form of authentication (or lack of authentication) is not supported by SAM Sync and provides a straightforward way to switch to IAM credential authentication.
Under the new flow, if the user chooses to authenticate with IAM credentials, the user will get a quick pick menu to choose from a list of valid credentials (including all IAM credentials, but excluding SSO and Builder …
> feat(appcomposer): prompt for IAM credentials

- package-lock.json
- package.json
- src/codewhisperer/commands/startTransformByQ.ts
- src/codewhisperer/service/transformationResultsViewProvider.ts
Need to remove "parse-diff" dep from package.json & package-lock.json. Need to handle case where diff is empty. Need to make sure the "Show Transformation Summary" button remains enabled even after a user accepts/rejects changes.
`npm uninstall parse-diff` and improve error handling and ensure button remains enabled.
> fix(gumby): remove unneeded dep, improve error handling, fix button enablement bug

- scripts/test/launchTestUtilities.ts
- Teams want to re-use the toolkits test script so that they can launch tests outside of the vscode repo. This requires some teams to provide additional information (like environment variables) to the spawned VSCode instance
- Allow teams re-using the toolkits test script to set environment variables
> test: allow environment variables in toolkit test scripts

- CONTRIBUTING.md
Based on feedback from https://github.com/aws/aws-toolkit-vscode/pull/4324#issuecomment-1908549623, i'm pulling out the documentation into it's own PR since it doesn't make sense to live alongside that PR anymore
- It isn't obvious what environment variables are used internally and what they are
- Pull them into the contributing.md documentation
> docs: Add documentation for environment variables

- src/applicationcomposer/messageHandlers/generateResourceHandler.ts
- src/applicationcomposer/webviewManager.ts
- There are several places where Application Composer is making multiple logger calls in a sequence rather than combining the information into one message.
- This removes unnecessary logger calls and combines other logger calls into a single message.
> fix(appcomposer): reduce logger messages

- src/testE2E/amazonq/featureDev.test.ts
- the beforeEach registers a framework which accepts requests. If we don't dispose before building a new one we get duplicate chat messages because theres two message listeners registered
- dipose of the first framework instance before creating the second framwork instance
> tests: fix duplicate messages for featureDev tests

- CONTRIBUTING.md
- src/amazonqFeatureDev/client/featureDev.ts
- src/codewhisperer/client/codewhisperer.ts
- src/codewhisperer/models/constants.ts
- src/shared/clients/codecatalystClient.ts
- src/shared/settings.ts
- src/test/shared/settingsConfiguration.test.ts
- It's not easy to change the codewhisperer endpoint when running tests against different versions of the api
- Allow configuration via a setting for dev mode
> codewhisperer: Allow endpoint/region overrides for dev mode

- .changes/next-release/Bug Fix-2ce4c789-d0e5-425c-affb-6cac6e5069fd.json
- src/codewhisperer/client/user-service-2.json
- src/codewhisperer/commands/onAcceptance.ts
- src/codewhisperer/commands/onInlineAcceptance.ts
- src/codewhisperer/tracker/codewhispererCodeCoverageTracker.ts
- src/test/codewhisperer/tracker/codewhispererCodeCoverageTracker.test.ts
Code percentage is not accurate. 
1. Only count user keystroke input as user tokens. Do not count code changes from copy and paste, git commands, etc.
2. Report CW tokens for below 2 options
2.1  Sum of original accepted recommendations 
2.2 Sum of Unmodified(retained, after user modification) accepted recommendations 
3. Do not emit code percentage if user is not invoking CW.
Tested E2E against dev env. 
Request id: 
6d7004a5-5f5f-4fa1-ad5a-56074a5ebb51 at about 01/30 6pm PST
service returned 200.
> fix(codewhisperer): Improve Code percentage reporting

- CONTRIBUTING.md
- scripts/test/launchTestUtilities.ts
- src/test/index.ts
- src/testE2E/index.ts
- src/testInteg/index.ts
- Theres no external way to set a specific directory to use for tests
- Add the TEST_DIR that will be used when running tests
Example:
```
export TEST_DIR=src/testE2E/amazonq
npm run testE2E
```
> testing: add testing directory configuration through environment variable

- CONTRIBUTING.md
- src/shared/clients/codecatalystClient.ts
- src/shared/vscode/env.ts
- src/test/shared/vscode/env.test.ts
Problem: While we have user settings.json overrides for codecatalyst, it is not easy for settings.json to be updated in CI environments.
Solution: Add ability to override on environment variables as well. Also, add generic functions for other services to do the same.
> feat(codecatalyst): add environment variable overrides for service configs

- src/codewhisperer/tracker/codewhispererCodeCoverageTracker.ts
- src/test/codewhisperer/tracker/codewhispererCodeCoverageTracker.test.ts
This is a follow up PR of https://github.com/aws/aws-toolkit-vscode/pull/4350.
Edge cases when user has a keystroke input but the IDE modifies it were not captured in previous PR. 
We wanted to capture user keystroke input by only selecting one char input. However, VSC document events somehow merged what user input and what IDE inputs, creating 2 char input or newline + indentation inputs. this PR is to catch these edge cases. 
The document change event in VSC is causing those edge cases to surface while in JetBrains, what user inputs and what IDE changes are in separated events so they do not need this kind of extra handling 
No change log is needed. 
> fix(codewhisperer): Fix edge cases in Code percentage reporting

- CONTRIBUTING.md
- src/codewhisperer/client/codewhisperer.ts
- src/shared/clients/codecatalystClient.ts
- src/shared/vscode/env.ts
- src/test/shared/vscode/env.test.ts
- Only codecatalyst has environment variables overrides and having them for Amazon Q makes testing some things a bit easier
- Generalize the environment variables overrides and extend them to Amazon Q
> env: Generalize environment variable for service overrides

- .changes/next-release/Bug Fix-bcc441fe-f0d3-444f-bbcb-16cc634e8a5f.json
- src/shared/clients/ec2MetadataClient.ts
Problem: We did not attach the token to IMDS calls, resulting in IMDSv1 being used. The SDK does support using tokens but only for calls to the endpoint `/latest/meta-data/iam/security-credentials/`. https://github.com/aws/aws-sdk-js/blob/3333f8b49283f5bbff823ab8a8469acedb7fe3d5/lib/metadata_service.js#L123-L235
Solution: Call the "private" sdk method to get the token so code isn't duplicated, and attach that in the header of our calls just like the sdk does for the above endpoint.
AWS SDK v3 does not support token handling https://github.com/aws/aws-sdk-js-v3/issues/4004
Deployed to C9 since its an ec2 instance, no longer throws error about ec2 creds being unavailable.
> fix: use IMDSv2 for all metadata service calls.

- .changes/next-release/Bug Fix-58f92b8d-fe98-4885-b150-3c52d640b4a0.json
- src/srcShared/fs.ts
- src/test/srcShared/fs.test.ts
We recently made some changes to our file system code that used the vscode.workspace.fs instance. The issue is that some of its methods are not supported in C9
If in C9 use the original "fs" instance methods instead for delete, readdir, and mkdir.
Also added tests.
This builds on top of @hayemaxi work from #4372 but I had to add some extra fixes for other methods
> fix: Use 'fs' methods if in C9

- buildspec/shared/common.sh
- buildspec/shared/linux-pre_build.sh
- package-lock.json
- package.json
Problem:
"npm WARN deprecated" warnings do not fail CI. Since winston was
updated, the only remaining warning is for `querystring`, which is
blocked until we update aws-sdk-js.
Solution:
Fail CI for "npm WARN deprecated" warnings, but make an exception for
`querystring`.
---
Problem:
npm WARN deprecated winston@3.7.1: Please use version 3.6.0 or >3.7.1
when available due to https://github.com/winstonjs/winston/issues/2103
Solution:
Update winston.
---
> ci: fail CI on "npm WARN deprecated"

- src/extension.ts
- src/extensionShared.ts
- src/extensionWeb.ts
We currently have `extension.ts#activate()` and `extensionWeb.ts#activate()` where the web version is basically a subset of the main `activate()`. This creates code duplication.
In `extensionShared.ts` have a shared activate function which both entrypoints will call.
This function will consist of the same setup code regardless of entrypoint, this will de-duplicate the code.
Note in activation order matters, so we may have to do some hacks if we run in to any new issues as
we migrate shared code from `extension.ts` in to `extensionShared.ts`.
> browser: share activate() setup between different entrypoints

- buildspec/linuxIntegrationTests.yml
Problem:
deadsnakes sometimes fails our CI:
lazr.restfulclient.errors.ServerError: HTTP Error 504: Gateway Time-out
Solution:
Remove use of deadsnakes. We no longer test against python 3.7/3.8.
> fix(ci): "deadsnakes" causes unreliable CI

- .github/workflows/release.yml
- buildspec/packageTestVsix.yml
- docs/ARCHITECTURE.md
- package.json
- packages/toolkit/scripts/build/package.ts
Ensure that copying the .vsix to the root folder always works. Also, make sure running npm i at root also runs postinstall scripts for all workspaces.
---
`npm run generateNonCodeFiles` is redundant, it is already called in vscode:prepublish which is called by `vsce` automatically
during `npm run publish`
Also, need to make sure we are in the proper directory to package in CI.
> fix: monorepo script changes

- packages/toolkit/src/test/srcShared/fs.test.ts
Reported by #4390, this test is failing on the mkdirSpy call count assertion.
Not exactly sure why this is flaky, but maybe it is due to the previous folders not being cleaned up.
This commit deletes the created folders after each test finishes. Additionally, this commit checks the actual spy call count so that we can better debug the issue
> fix: flaky fs test

- packages/toolkit/src/codewhisperer/service/inlineCompletionService.ts
- packages/toolkit/src/codewhisperer/service/recommendationHandler.ts
- packages/toolkit/src/codewhisperer/util/telemetryHelper.ts
There is a less than 4% chance that the sessionId in STE API is reset to next session's id.  See https://github.com/aws/aws-toolkit-vscode/pull/4368 (Previous PR had incorrect solution to the problem)
Root cause:
When user accept/reject a recommendation before all the pagination API calls finish, the userTriggerDecision of this session is not sent but stored in the IDE session state. When user accept/reject a recommendation next time, the stored state of previous session is sent along with new session, causing wrong session id for some user trigger decision events.
To reproduce it, invoke a recommendation that has multiple pagination calls, managed to hit TAB or escape very fast before the 2nd pagination response arrives at the plugin.  This is tricky to reproduce but possible. 
Invoke …
> fix(codewhisperer): wrong session id reported by race condition when accept/reject during pagination

- packages/toolkit/src/codewhisperer/util/supplementalContext/utgUtils.ts
We cannot use 'glob' in browser mode since it breaks if not in nodejs
Use `vscode.workspace.findFiles` which simply searches the entire workspace (or current folder
if no workspace was selected)
Note the previous comments about it not working, which was due to us needing to use a relative path since it searches the workspace/root folder only
> refactor: remove 'glob' from CW

- packages/toolkit/src/extension.ts
- packages/toolkit/src/extensionShared.ts
- packages/toolkit/src/extensionWeb.ts
- packages/toolkit/src/shared/extensionGlobals.ts
This moves more code in to the shared activation method so that we should be able
to start enabling CodeWhisperer (it should have all the pre-requisite setup it requires now)
- Shared code was moved out of `extension.ts#activate()` and in to `extensionShared.ts#activateShared()`
- The `ExtContext` object is now created in `activateShared()` and passed to the entrypoints as a return value
> browser: move more code in to shared activation

- packages/toolkit/src/codewhisperer/commands/startTransformByQ.ts
- packages/toolkit/src/codewhisperer/models/constants.ts
- packages/toolkit/src/codewhisperer/models/model.ts
- packages/toolkit/src/codewhisperer/service/transformByQHandler.ts
- packages/toolkit/src/test/codewhisperer/commands/transformByQ.test.ts
UX request to change the way we validate input: rather than letting user select a project, then run all validation checks, we want to run all validation checks on all open projects to filter valid projects for the user, plus pre-select the Java version for them if we were able to detect it and it's a supported version (8 or 11).
Implement what is described above.
> fix(CodeTransform): pre-select Java version

- .github/workflows/release.yml
- buildspec/release/10changeversion.yml
- buildspec/release/20buildrelease.yml
- buildspec/release/40pushtogithub.yml
- buildspec/release/50githubrelease.yml
Problem: Release pipeline not behaving as expected, not updating the proper package.json version.
Solution: Update for new paths/npm workspaces.
Tested some of the commands locally, they seem to be working fine for updating the version, committing now.
> fix: release buildspec .ymls need to be updated for monorepo change

- packages/toolkit/src/extensionShared.ts
The order of the intialize methods caused issues in C9 due to the order of execution.
> refactor: reorder initialize since breaks in C9

- packages/toolkit/src/extensionShared.ts
Output channel is used inside a c9 wrapper before it is created.
Packaged and things that use progress in c9 (e.g. upload lambda, upload s3) no longer fails.
> fix: create output channel before registering with c9 progress

- packages/toolkit/src/srcShared/fs.ts
Problem: the C9 stub for the vscode api's writeFile does not support writing outside of the workspace dir, which can happen when adding new IAM credentials.
Solution: Fall back to a standard fs library for C9.
Tested on C9
> fix(c9): use 'fs' for c9 when calling `writeFile`

- .changes/next-release/Bug Fix-7858d5db-fde1-4db1-860f-5be3b0bce411.json
- packages/toolkit/package.json
The cdk refresh button was inadvertently disabled in this commit: https://github.com/aws/aws-toolkit-vscode/commit/4e72ba7102b7d59058729c592fb6d234deb1e9ed
This restores the button.
> fix(cdk): re-enable refresh button for cdk explorer

- packages/toolkit/src/amazonq/explorer/amazonQChildrenNodes.ts
- packages/toolkit/src/amazonqGumby/activation.ts
- packages/toolkit/src/amazonqGumby/commands.ts
- packages/toolkit/src/codewhisperer/commands/basicCommands.ts
This moves gumby commands to their own file.
- We are doing this since CW unintentionally imports gumby, but gumby code uses fs-extra which breaks browser mode.
- In the future we need make sure to keep CW and Gumby code separate where possible
> refactor: move some gumby out of CW files

- packages/toolkit/src/test/srcShared/fs.test.ts
Not sure if this fixes #4390, but this will now reuse the same sandbox instead of recreating it
each time. We were failing a test where a spied method was being called more than expected.
> test: try fix flaky test

- package-lock.json
- packages/toolkit/package.json
- packages/toolkit/src/codewhisperer/commands/startTransformByQ.ts
- packages/toolkit/src/codewhisperer/models/constants.ts
- packages/toolkit/src/codewhisperer/models/model.ts
- packages/toolkit/src/codewhisperer/service/transformByQHandler.ts
- packages/toolkit/src/codewhisperer/service/transformationResultsViewProvider.ts
- packages/toolkit/src/testE2E/amazonqGumby/transformByQ.test.ts
Our `Maven` shell commands sometimes fail and we suspect it is because we are not running those commands with the proper JAVA_HOME (needs to match the project JDK).
If the Maven wrapper executable exists in the project directory, use that for both `Maven` shell commands, else use regular `mvn` -- and if the Java version used by Maven differs from the project's Java version, prompt the user for JAVA_HOME and use that when running the shell commands.
> fix(CodeTransform): prompt user for JAVA_HOME

- packages/toolkit/scripts/test/launchTestUtilities.ts
- packages/toolkit/src/test/techdebt.test.ts
- packages/toolkit/src/testE2E/amazonqGumby/transformByQ.test.ts
In PR #4170 we locked the python extension to a specific version since a newer version of the extension broke CI.
The fix should be available now, so we are removing the code that locked us to a specific version and will now use whatever the latest version is.
> test: use latest version of python extension in CI

- package-lock.json
- packages/toolkit/package.json
- packages/toolkit/src/amazonq/webview/ui/apps/amazonqCommonsConnector.ts
- packages/toolkit/src/amazonq/webview/ui/apps/cwChatConnector.ts
- packages/toolkit/src/amazonq/webview/ui/apps/featureDevChatConnector.ts
- packages/toolkit/src/amazonq/webview/ui/connector.ts
- packages/toolkit/src/amazonq/webview/ui/followUps/handler.ts
- packages/toolkit/src/amazonq/webview/ui/followUps/model.ts
- packages/toolkit/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/toolkit/src/amazonqFeatureDev/controllers/chat/messenger/messenger.ts
- packages/toolkit/src/amazonqFeatureDev/views/connector/connector.ts
To support future chat features, it is necessary to update the dependent library responsible for rendering the chat UI, `mynah-ui`. 
The only breaking change that affects this codebase from upgrading from `3.x` to `4.x` is that `ChatItemFollowUp` [is renamed to](https://github.com/aws/mynah-ui/commit/631d87af733877a29df3d55f00f1d1273dc75537) `ChatItemAction`
Manually tested Q chat and `/dev` functionality, paying particular attention to behavior around the follow-up items 
`npm run testE2E` passed
> Upgrade mynah-ui to latest version

- docs/browser.md
- packages/toolkit/src/codewhisperer/commands/startSecurityScan.ts
- packages/toolkit/src/codewhisperer/util/dependencyGraph/cloudformationDependencyGraph.ts
- packages/toolkit/src/codewhisperer/util/dependencyGraph/csharpDependencyGraph.ts
- packages/toolkit/src/codewhisperer/util/dependencyGraph/dependencyGraph.ts
- packages/toolkit/src/codewhisperer/util/dependencyGraph/goDependencyGraph.ts
- packages/toolkit/src/codewhisperer/util/dependencyGraph/javaDependencyGraph.ts
- packages/toolkit/src/codewhisperer/util/dependencyGraph/javascriptDependencyGraph.ts
- packages/toolkit/src/codewhisperer/util/dependencyGraph/pythonDependencyGraph.ts
- packages/toolkit/src/codewhisperer/util/dependencyGraph/rubyDependencyGraph.ts
- packages/toolkit/src/codewhisperer/util/dependencyGraph/terraformDependencyGraph.ts
- packages/toolkit/src/codewhisperer/util/supplementalContext/crossFileContextUtil.ts
- packages/toolkit/src/codewhisperer/util/supplementalContext/utgUtils.ts
- packages/toolkit/src/srcShared/fs.ts
- packages/toolkit/src/test/codewhisperer/util/crossFileContextUtil.test.ts
- packages/toolkit/src/test/srcShared/fs.test.ts
- packages/toolkit/src/testE2E/codewhisperer/securityScan.test.ts
Adds additional changes on top of #4421 from @andrewyuq (I wasn't able to add my commit and github autoclosed his PR).
This PR removes fs-extra logic from CodeWhisperer logic so that it can run in web mode.
> browser: remove fs-extra usage in CodeWhisperer logic

- packages/toolkit/src/extensionShared.ts
- packages/toolkit/src/shared/awsClientBuilder.ts
- packages/toolkit/src/test/globalSetup.test.ts
Problem:
AWS JS SDK v2 shows a very noisy warning. This warning appears in local debugging, in the CI logs, etc.
NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `Code Helper (Plugin) --trace-warnings ...` to show where the warning was created)
Solution:
Suppress the warning (see https://github.com/aws/aws-sdk-js/issues/4354). Updating to SDK v3 is in our backlog, so we don't need the warning.
Fix #4371
> logging: suppress AWS SDK v2 warning

- package-lock.json
- packages/toolkit/package.json
- packages/toolkit/src/amazonqFeatureDev/session/sessionState.ts
- packages/toolkit/src/test/amazonqFeatureDev/session/sessionState.test.ts
This package was added in 9e8976b38ca13286e14b919a145b75515a0d565d to guard against unexpected server response, but it has a lot more features (and transitive dependencies) that we aren't using. It's also adding a maintenance cost: https://github.com/aws/aws-toolkit-vscode/pull/4435
- Use `encodeHTML` instead.
- Remove unnecessary dependencies.
> deps: remove "sanitize-html" dependency

- packages/toolkit/src/awsexplorer/activation.ts
- packages/toolkit/src/awsexplorer/activationShared.ts
- packages/toolkit/src/extensionShared.ts
We want to use the CodeWhisperer tree view during browser mode. The issue is when enabling it the current code will try and enable the other tree views such as the Resource Explorer.
Additionally, web mode breaks due to imports in `activation.ts`.
Extract the logic for the tree view that we want to work in both node and browser environments in to its own shared activate function. We then have more control over what we enable and they are guaranteed to work in the browser.
Now we can use that shared activation for both environments.
> refactor: extract codewhisperer tree view setup

- packages/toolkit/src/codewhispererChat/controllers/chat/telemetryHelper.ts
- packages/toolkit/src/shared/telemetry/vscodeTelemetry.json
The new field contains the start URL of the current SSO connection. This will allow tracing back chat events to the originating SSO session.
We missed this field for the AmazonQ experience
New field introduced
> AmazonQ: Add cwsprCredentialStartUrl field to chat telemetry events

- docs/ARCHITECTURE.md
- packages/toolkit/src/lambda/commands/uploadLambda.ts
- packages/toolkit/src/shared/clients/lambdaClient.ts
- packages/toolkit/src/shared/filesystemUtilities.ts
- packages/toolkit/src/shared/wizards/wizard.ts
- packages/toolkit/src/srcShared/fs.ts
- packages/toolkit/src/test/apprunner/wizards/codeRepositoryWizard.test.ts
- packages/toolkit/src/test/apprunner/wizards/createServiceWizard.test.ts
- packages/toolkit/src/test/apprunner/wizards/imageRepositoryWizard.test.ts
- packages/toolkit/src/test/cloudWatchLogs/commands/searchLogGroup.test.ts
- packages/toolkit/src/test/credentials/wizards/createProfile.test.ts
- packages/toolkit/src/test/credentials/wizards/sso.test.ts
- packages/toolkit/src/test/ecs/wizards/executeCommand.test.ts
- packages/toolkit/src/test/lambda/commands/uploadLambda.test.ts
- packages/toolkit/src/test/lambda/wizards/samInitWizard.test.ts
- packages/toolkit/src/test/lambda/wizards/uploadLambdaWizard.test.ts
- packages/toolkit/src/test/redshift/wizards/connectionWizard.test.ts
- packages/toolkit/src/test/shared/sam/sync.test.ts
- packages/toolkit/src/test/shared/wizards/wizardForm.test.ts
- packages/toolkit/src/test/shared/wizards/wizardTestUtils.ts
- packages/toolkit/src/test/ssmDocument/wizards/publishDocumentWizard.test.ts
- packages/toolkit/src/test/stepFunctions/wizards/createStateMachineWizard.test.ts
- packages/toolkit/src/test/stepFunctions/wizards/previewStateMachineCDKWizard.test.ts
- packages/toolkit/src/test/stepFunctions/wizards/publishStateMachineWizard.test.ts
In Cloud9, using the "Upload Lambda" action on even a small directory, takes 5+ seconds. Example trace:
2024-02-16 15:45:44 [DEBUG]: createRegionPrompter: selected { id: 'us-west-2', name: 'US West (Oregon)' }
2024-02-16 15:45:44 [DEBUG]: findApplicationJsonFile (cloud9: true)
2024-02-16 15:45:44 [DEBUG]: cloud9Findfile: /home/ec2-user/environment/
2024-02-16 15:45:46 [DEBUG]: cloud9Findfile: /home/ec2-user/environment/.c9
2024-02-16 15:45:49 [DEBUG]: cloud9Findfile: /home/ec2-user/environment/.c9/amazonwebservices.aws-toolkit-vscode
2024-02-16 15:45:50 [DEBUG]: cloud9Findfile: /home/ec2-user/environment/.c9/metadata
2024-02-16 15:45:52 [DEBUG]: cloud9Findfile: /home/ec2-user/environment/.c9/test 4
2024-02-16 15:45:52 [DEBUG]: uploadLambda: .application.json not found in: …
> perf(cloud9): "Upload Lambda" is slow since Toolkit 2.x

- .changes/next-release/Feature-acb30000-5eeb-4a1a-85ce-1df104b9cc86.json
- package-lock.json
- packages/toolkit/package.json
- packages/toolkit/src/codewhisperer/service/securityIssueHoverProvider.ts
- packages/toolkit/src/test/codewhisperer/service/securityIssueHoverProvider.test.ts
We want to capture ACR fix generation rate.
Report the ratio of hover events for issues with and without fix.
> telemetry: add fix rate metrics for hover events

- packages/toolkit/src/test/srcShared/fs.test.ts
This test is flaky and sometimes fails in CI where the spy shows that the method was invoked 2 times, when it should have been 1 time.
#4390 
Instead test against the actual args and then we should hopefully get more information regarding who is causing the second call.
> test: get better understanding of flaky test

- .changes/next-release/Bug Fix-3c1e992b-b24d-418d-a91b-a0cf4d2e7b66.json
- package-lock.json
- packages/toolkit/package.json
The previous version of FQN extraction contains some subtle bugs, which lead to crashes on syntax elements like line continuations in Python.
Updating to the latest version fixes those.
> Amazon Q: update FQN extractor

- CONTRIBUTING.md
- packages/toolkit/src/testE2E/amazonq/featureDev.test.ts
- packages/toolkit/src/testE2E/amazonq/framework/text.ts
- packages/toolkit/src/testE2E/amazonq/utils/setup.ts
_pending creation of amazonq-test-account secret_
- Amazon Q e2e tests currently use mocked responses instead of calling the backend directly
- Allow Amazon Q e2e tests to call the backend directly
> tests: Allow Amazon Q e2e tests to call the backend

- .changes/next-release/Feature-742cb7ff-2139-4c0f-9b9e-22d72c960f60.json
- packages/toolkit/src/codewhisperer/service/inlineCompletionItemProvider.ts
- packages/toolkit/src/codewhisperer/tracker/codewhispererCodeCoverageTracker.ts
- packages/toolkit/src/codewhisperer/util/telemetryHelper.ts
- packages/toolkit/src/shared/telemetry/vscodeTelemetry.json
- packages/toolkit/src/test/codewhisperer/tracker/codewhispererCodeCoverageTracker.test.ts
Previously when we count user written code we only count user keystroke input, which contributes to a higher than expected % code written metric.
However, if we include all multi character user inputs from copy & paste or other sources, the % code written metric will be very low, providing little value to customers.
We discovered that if a user copy a large file, it will generate huge total user input, which is not what we want to track. Instead, small user multi character input are indeed considered as user written code. For example, copy code snippet from Stackoverflow, copy another function signature, accepting IntelliSense suggestion, etc.
1. Add multi char user input less than 500 as total user written code. We believe 500 is a good middle ground to begin with. 
2. Add temporary …
> feat(cwspr): Improve percentage code written metrics to include some user multi character input

- .changes/next-release/Feature-29b29159-d661-4ffe-ae03-2f5473dd6dec.json
- packages/toolkit/src/codewhisperer/commands/startTransformByQ.ts
- packages/toolkit/src/codewhisperer/models/constants.ts
- packages/toolkit/src/codewhisperer/models/model.ts
- packages/toolkit/src/codewhisperer/service/transformByQHandler.ts
- packages/toolkit/src/codewhisperer/service/transformationResultsViewProvider.ts
Wanted to clean up our logging / messages, include link to docs when error occurs, and include request ID in error notifications when APIs fail.
Implement the above.
> fix(CodeTransform): show link to docs after errors

- .changes/next-release/Feature-e6bbf14f-90d8-4b30-8e63-7ff522fd855a.json
- packages/toolkit/src/auth/ui/vue/authForms/manageBuilderId.vue
- packages/toolkit/src/auth/ui/vue/authForms/manageIdentityCenter.vue
- packages/toolkit/src/auth/ui/vue/authForms/sharedAuthForms.css
- packages/toolkit/src/auth/ui/vue/featurePanel/awsExplorerContent.vue
- packages/toolkit/src/auth/ui/vue/featurePanel/codeCatalystContent.vue
- packages/toolkit/src/auth/ui/vue/root.vue
Users are sometimes confused when logging in to aws toolkit. 
1. Changed button text for both the builder ID and IAM Identity Center
2. Changed the title of the page to be more descriptive
3. Made the title of the page and the 'AWS Toolkit for VSCode' different sizes so the title stands out more.
> fix(toolkit): Improve text description in login page

- packages/toolkit/src/codewhispererChat/controllers/chat/telemetryHelper.ts
Chat events verification fails
Result field is added to chat events to prevent verification errors
> AmazonQ: Result field to chat telemetry events

- packages/core/package.json
- src.gen/@amzn/codewhisperer-streaming/package.json
Brand new workspaces will not have src.gen/ compiled, which previously only compiled when compiling the core library. Now it just builds after installing in the workspace.
> fix: build @amzn/codewhisperer-streaming on install instead of during core lib compiling

- package-lock.json
- packages/amazonq/package.json
- packages/core/src/shared/extensions.ts
Problem:
Our extensions for vscode, visual studio, etc., all share a single marketplace org (and thus "publisher" id).
Solution:
Add `-vscode` suffix to disambiguate from other extensions.
> build: update extension-id

- .changes/next-release/Bug Fix-240f643e-f2f5-4a3b-81bf-477f76429423.json
- packages/core/src/codewhisperer/service/transformByQHandler.ts
The current mechanism to copy dependencies is faulty and often results in cases where dependencies are only partially copied or the command execution fails, both of which results in users being unable to transform their code.
Using `mvn install` as the primary mechanism to copy dependencies. The order of execution is as follows:
1. Run `mvn dependency:copy-dependencies` to copy any locally persisted dependencies into an empty dependencies directory. We will continue execution even if this command fails as this is just an optimization to avoid downloading any locally available dependencies which can be copied with this command.
2. Run` mvn clean install` with the `-Dmaven.repo.local` arg pointing to the dependencies directory created in step 1. This is the primary command we are going to …
> fix(CodeTransform): Updating commands for copying dependencies

- .changes/next-release/Bug Fix-ae8ef2c1-9969-45f9-bda9-0249ee124c46.json
- packages/core/src/extension.ts
- packages/core/src/shared/sam/cli/samCliDetection.ts
- packages/core/src/shared/settings.ts
- packages/core/src/test/shared/settingsConfiguration.test.ts
- packages/core/src/test/utilities/testSettingsConfiguration.ts
Shutdown-and-restart VS Code with multiple windows opened, causes AWS Toolkit to show a "Failed to access settings" error. #4453
1. open a bunch of different vscode instances/workspaces.
2. close all vscode instances.
3. start vscode (which resumes all the previously-closed instances).
Verifying settings on startup causes too many problems, so drop it in favor of verifying just-in-time.
> fix: "Failed to access settings" when restarting multiple vscode instances

- buildspec/packageTestVsix.yml
Problem:
The build artifacts zip includes the `aws-toolkit-vscode.code-workspace` file.
Solution:
Adjust the include pattern.
> fix(ci): artifacts includes irrelevant files

- packages/core/src/testE2E/amazonq/featureDev.test.ts
- The test infra isn't fully setup so these tests will always fail
- Wait until the test infra is fully setup again before unskipping these tests
> fix: Temporarily disable amazon q tests

- buildspec/release/10changeversion.yml
In the release pipeline we are getting an error during this stage.
The phase `SetVersionForRelease` is showing this error:
`npm ERR! FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`
Add more memory
> fix: changeVersion is running out of memory

- packages/webpack.base.config.js
Problem:
The webpack'd main.js is very big. "legal" comments are not removed by default, which bloats the code size.
Solution:
Set `legalComments=eof`. This de-duplicates license headers and lists them at the end of the file. Reduces the size by ~100 KiB.
> build: minify license headers

- packages/core/src/test/setupUtil.ts
- Right now the max duration for e2e tests is always set to 300000 milliseconds. This presents a problem when certain e2e tests want a longer test timeout for retries to run, etc. This causes tests to always timeout at 300000 milliseconds regardless of whether or not a user has configured this.timeout in mocha.
- Respect the max of the default max test duration and the timeout that the user has set inside of the test
> fix: respect test timeout for max duration

- .changes/next-release/Bug Fix-b28584d3-e664-4851-9d25-0949db6ca0ac.json
- package-lock.json
- packages/core/package.json
[Amazon Q chat input does not work well with IME enabled #4125](https://github.com/aws/aws-toolkit-vscode/issues/4125)
Version [**4.3.2**](https://github.com/aws/mynah-ui/releases/tag/v4.3.2) of [mynah-ui](https://github.com/aws/mynah-ui) includes the check if the IME enabled when user hits enter while the prompt input is focused. 
> fix(amazonq): prompt input sends with enter when IME enabled

- .changes/next-release/Bug Fix-0ac3c863-5f66-450b-a0f5-f1f43a07ec76.json
- packages/core/src/codewhisperer/tracker/codewhispererCodeCoverageTracker.ts
- packages/core/src/test/codewhisperer/tracker/codewhispererCodeCoverageTracker.test.ts
By conducting one week of data collection, we find that multi character text change which has more than 50 characters only account for 2% of total document change, but they somehow contributed to more than 98% of characters in the doc. This is because user rarely copy and paste code into their editor, but when they do, the copy will result in huge number of character increase. This kind of increase is not what we want to capture in the cwspr percentage code written metric.
50 is a good threshold that includes copy of small code snippets and IDE intelliSense accepted code.
Ignore any multi character input more than 50 characters.
The userDetails JSON will be removed in the future. We want to monitor it for a few weeks longer.
By submitting this pull request, I confirm that my contribution …
> fix(cwspr): update codePercentage metrics threshold from 500 to 50

- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/amazonqFeatureDev/session/session.ts
- A couple events were missing result: 'Succeeded'
- Add it
> telemetry: Add result: 'Succeeded' to all featureDev telemetry

- .changes/next-release/Feature-2d9d80f7-b515-47ff-9cbd-514efb4cca49.json
- packages/core/src/ssmDocument/activation.ts
- packages/core/src/ssmDocument/ssm/ssmClient.ts
- packages/core/src/stepFunctions/activation.ts
- packages/core/src/stepFunctions/asl/client.ts
Toolkit starts LSP servers eagerly on startup, which slows startup (even for users that never use the SSM Documents or StepFunctions features).
- Start SSM Documents LSP client/server on first use, instead of on startup.
- Start StepFunctions LSP client/server on first use, instead of on startup.
- This also avoids 2 unnecessary Output channels (see https://github.com/aws/aws-toolkit-vscode/pull/4527).
before:
| Extension                            | Eager | Load Code | Call Activate | Finish Activate | Event                          | By                                   |
| ------------------------------------ | ----- | --------- | ------------- | --------------- | ------------------------------ | ------------------------------------ |
| amazonwebservices.aws-toolkit-vscode | false | …
> perf(ssm,stepfunctions): start LSP clients/servers lazily

- package-lock.json
- packages/core/package.json
- packages/core/src/amazonqGumby/telemetry/codeTransformTelemetry.ts
- packages/core/src/auth/secondaryAuth.ts
- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/core/src/codewhisperer/commands/startTransformByQ.ts
- packages/core/src/codewhisperer/service/transformByQHandler.ts
It is complicated to track if failures when running Q CodeTransform on customer machines are due to repeated tries of the same project or for different projects. This complicates for us to understand if errors we see are only for specific projects or for all projects for a specific clientId.
Emit a projectHash that uniquely identifies the project selected for transform by a user. This allows us to differentiate between repeated submissions of the same project or unique submissions of different projects. Thus allowing us to fix issues faster.
> Q CodeTransform: Emit projectId telemetry when starting new transformation.

- plugins/eslint-plugin-aws-toolkits/test/rules/no-only-in-tests.test.ts
Running `npm install` failed with an error:
`test/rules/no-only-in-tests.test.ts:6:23 - error TS7016: Could not find a declaration file for module '../..'.`
Update the path to point to the actual module and it now works
> fix: npm install failure

- packages/core/src/auth/sso/clients.ts
- packages/core/src/shared/utilities/collectionUtils.ts
- packages/core/src/shared/vscode/commands2.ts
- packages/core/src/ssmDocument/ssm/ssmClient.ts
- packages/core/src/stepFunctions/asl/client.ts
- packages/core/src/test/shared/utilities/collectionUtils.test.ts
Problem:
Log message "command: running with arguments …" does not print useful argument info.
Solution:
Print objects at depth of 1.
before:
2024-03-18 18:10:21 [DEBUG]: command: running "aws.cdk.renderStateMachineGraph" with arguments [[object Object], undefined]
after:
2024-03-18 13:15:20 [DEBUG]: command: running "_aws.auth.reauthenticate" with arguments: {
'0': Auth {
...
},
'1': {
...
}
}
> feat(logging): log command args

- .changes/next-release/Bug Fix-d70cbb8e-491a-439e-9cbb-b155431e3743.json
- packages/core/src/codewhisperer/service/recommendationHandler.ts
In Sage Maker Code Editor, CWSPR should create request in type GenerateRecommendation for SigV4 API invocation. Otherwise there will be a Unexpected key 'optOutPreference' found in params
Add extra if else for Sage Maker Code Editor to let the recommendation Handler use GenerateRecommendation Request payload instead of using the ListRecommendation. 
Tested in SageMaker Code Editor and it works. 
> fix(cwspr): Fix cw api call failure in sm code editor

- packages/core/src/amazonqFeatureDev/client/featureDev.ts
- packages/core/src/codewhisperer/service/transformationResultsViewProvider.ts
- packages/core/src/codewhispererChat/clients/chat/v0/chat.ts
- packages/core/src/shared/clients/codewhispererChatClient.ts
- Other folders were piggybacking off the streaming client
- Move to it src/clients so it's in a more central place
> featureDev: Move streaming client to shared client

- packages/core/.vscode/launch.json
- When launching tests in "core" there is a registration conflict when you have the current toolkit installed locally and the tests are running/loading in the extension host. This seems to be because the tests are launching under the "core" id/version of the toolkit so instead of replacing the toolkit extension itself when loading in the extension host it runs a second seperate extension instance. This means that the "core" toolkit and the actual toolkit are running inside of the extension host at the same time, causing registration conflicts
- Just disable the toolkit extension that comes from the local instance when debugging
> fix: Disable the main toolkit extension when launching tests in core

- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/codewhisperer/explorer/codewhispererChildrenNodes.ts
- packages/core/src/codewhisperer/explorer/codewhispererNode.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/models/model.ts
- packages/core/src/test/codewhisperer/commands/basicCommands.test.ts
- packages/core/src/test/codewhisperer/explorer/codewhispererNode.test.ts
Users should be able to enable/disable auto scanning feature
Add Pause/Resume button for auto scans
> codewhisperer: add auto scans trigger

- packages/core/src/auth/auth.ts
When errors occur somewhere in the getToken() process + the token was previously valid, if it fails we do not log the actual underlying error anywhere. We simply tell them to reauth.
This caused issues when debugging premature auth expiration problems since we couldn't see the actual error.
If we switch from valid to invalid connection state, then log the error as a warning. This should give us the reason as to why it is failing, though we will also see the expected case where it actually expired.
> auth: log errors when we go from valid to invalid state

- packages/core/src/codewhisperer/service/recommendationHandler.ts
As discussed offline, after introducing #4558 feature, we would like to remove progress runner/prompt while running CodeWhisperer (`Waiting for CodeWhisperer...`) for manual trigger case.
https://github.com/aws/aws-toolkit-vscode/assets/96078566/ca589453-e9f1-4a22-a246-73f85e66118a
https://github.com/aws/aws-toolkit-vscode/assets/96078566/13d6a253-f83b-4cd9-9e62-aa63b35aebcf
> feat(codewhisperer): remove prompt "waiting for CodeWhisperer..."

- docs/api.md
- packages/toolkit/src/api.ts
This is a follow up PR of https://github.com/aws/aws-toolkit-vscode/pull/4544.
It no longer exposes internal data structure `Connection` . Now it exposes a new type `AwsToolkitSsoConnection`  that does not have `getCredentials`. 
For AmazonQ extension, I have tested that it can cast the new type `AwsToolkitSsoConnection` into `Connection` and 
it can further getCredentials from this connection. This is possible only for AmazonQ because it is re-using the same auth library as toolkit. For other 3rd party extensions, they won't be able to perform `getCredentials` from `AwsToolkitSsoConnection`
> fix(cwspr): Amend exposing listConnection api

- packages/core/src/codewhisperer/service/transformByQHandler.ts
- packages/core/src/test/codewhisperer/commands/transformByQ.test.ts
Late discovery of an issue where upon opening VS Code with recently merged changes we get an error message about the "projectDetails" metric not being passive.
Also reverting the "Error" to "ToolkitError" (how it was originally) because I get a generic VS Code error about not being able to execute `aws.q.transform` when you open VS Code with no open projects.
Implement the above.
> Bugfix project details loggin

- .changes/next-release/Bug Fix-c76a701b-a106-46ef-99d9-5bb0760c469a.json
- packages/core/src/amazonqFeatureDev/session/session.ts
- packages/core/src/test/amazonqFeatureDev/controllers/chat/controller.test.ts
Bug:
Rejected files were ignored when generated code was accepted.
Fix:
Rejected files are excluded when generated code was accepted.
Testing:
I added a test to ensure the `fileClick` action correctly updates the state of the file, including rejecting files and reverting rejections. 
Additionally, I manually tested the most common scenarios, such as accepting all files, rejecting all files, and accepting a subset of them. All cases functioned as expected.
> fix: featureDev partial code acceptance

- packages/core/src/codewhisperer/service/transformByQHandler.ts
- packages/core/src/test/codewhisperer/commands/transformByQ.test.ts
When opening VS Code, all CWSPR users were getting a notification that says if they have any valid projects open for transformation. Also, the `Error`s we were throwing was causing an error notification to popup saying "Cannot execute command aws.q.transform". Changing this back to ToolkitError (with an empty string, since we already show a notification and I don't want duplicate notifications), fixes this issue too.
Implement the above.
> fix(QCT): unnecessary notifications

- .changes/next-release/Feature-04884433-f614-43a2-b7c6-58df79e31bbb.json
- .changes/next-release/Feature-36982776-d732-4c39-b76a-589745004928.json
- packages/core/src/codewhisperer/views/lineAnnotationController.ts
* LineTracker implementation #4532
* Active state indicator UI implementation #4558
* Inlinehint UI Implementation #4539
https://github.com/aws/aws-toolkit-vscode/assets/96078566/d3a5ab9c-c80c-493b-8eb4-5a05b8a90da6
https://github.com/aws/aws-toolkit-vscode/assets/96078566/0895c045-62f2-4928-a923-bfbde249ba84
> changelog(codewhisperer): inline hint + active state UI improvements

- packages/core/src/lambda/wizards/samInitWizard.ts
- packages/core/src/shared/filesystemUtilities.ts
- packages/core/src/shared/wizards/wizard.ts
- packages/core/src/shared/wizards/wizardForm.ts
- packages/core/src/test/shared/filesystemUtilities.test.ts
- packages/core/src/test/shared/wizards/wizard.test.ts
Problem:
- `bindPrompter` does not support binding to async functions. This can be very awkward, and limits how prompts can be implemented.
- `getNonexistentFilename` has a bug: it checks `existsFile` which returns false for directories.
Solution:
- Change the definition of `PrompterProvider` to allow returning a Promise.
- Fix the check in `getNonexistentFilename`.
> feat(wizard): support async prompter functions

- .github/workflows/release.yml
This is blocked until we have a `feature/standalone` branch.
prereleases don't include `amazon-q-vscode-*.vsix` artifacts.
build amazonq in the prerelease workflow.
previous: 69f30585dc03fb3161eef42a008536e18e58bed5
> ci: publish "amazonq" prereleases

- packages/core/src/login/webview/vue/amazonq/backend_amazonq.ts
- packages/core/src/login/webview/vue/backend.ts
- packages/core/src/login/webview/vue/login.vue
- packages/core/src/login/webview/vue/toolkit/backend_toolkit.ts
This is a PR moved from https://github.com/hayemaxi/aws-toolkit-vscode/pull/7.
1. User cannot easily quit the login screen
2. Code catalyst login should be under Workforce button
1 Add back arrow at login start screen ONLY for aws toolkit
2. Move code catalyst under Workforce button login screen
> feat(codewhisperer): Add back arrow at login start screen;move code catalyst login option

- packages/amazonq/.vscode/tasks.json
- packages/amazonq/package.json
- Same debugging support as toolkit (hot reloads)
- build passes now, fixing a bug with location of generateNonCodeFiles script
> fix(q): debugging and build scripts for amazonq

- packages/amazonq/package.json
It is using a script that no longer exists, so remove call to that script.
> fix(q): package npm script

- packages/core/src/amazonq/auth/controller.ts
- packages/core/src/amazonq/explorer/amazonQChildrenNodes.ts
- packages/core/src/auth/ui/vue/show.ts
- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/login/webview/vue/amazonq/backend_amazonq.ts
- Move auth hook intializations to a dedicated function in AuthUtil, so that both extensions don't attach the hooks.
- Remove extra instances of context setting for the login page.
> fix(q): login state context simplification

- packages/core/src/test/shared/ui/pickerPrompter.test.ts
- packages/core/src/test/shared/vscode/quickInput.ts
The tests below this change, starting at `'can accept custom input as ...'` were failing for some reason due to a change in VS Code Insiders.
After commenting out the test `'can handle additional items ...'` the other tests started passing.
By adding `await` to picker.setFilter() in all uses everything now passes.
This is the original ticket that connects to the Insiders change which uncovered this race condition we had in our code: https://github.com/microsoft/vscode/issues/208715
> test: fix failing insiders tests

- .changes/next-release/Bug Fix-492bca4b-aec1-414d-a719-275c854aa1d2.json
- packages/core/src/codewhisperer/tracker/lineTracker.ts
- packages/core/src/codewhisperer/views/activeStateController.ts
- packages/core/src/codewhisperer/views/lineAnnotationController.ts
`LineTracker` is subscribing `vscode.TextDocumentChangeEvent` and VSCode will also fire the above event when the plugin is adding new entry of logs. 
Therefore when user's focus is at log file, the following events will happen in order
1. VSCode `onContentChanged`
2. `LineTracker` emits events to update CWSPR UI components
3. `ActiveStateController.refresh()` & `LineAnnotationController.refresh()` 
4. `refresh()` invoke `isConnectionValid()`, which will add logs
5. back to step (1)
https://github.com/aws/aws-toolkit-vscode/assets/96078566/aa499070-1953-4126-9ab2-505bda778bcd
https://github.com/aws/aws-toolkit-vscode/assets/96078566/b34f75c9-aafb-4556-9bc4-c40c64dc476f
> fix(codewhisperer): line tracker stuck in an infinite loop while user's editor focus is on OUTPUT/LOGS and documentChangedListener will not stop

- packages/amazonq/src/extensionShared.ts
- packages/core/src/codewhisperer/index.ts
The Code Whisperer auto suggestion should be enabled by default in Amazon Q.
Enable CodeWhisperer on activation of AmazonQ
> fix(codewhisperer): Enable CodeWhisperer on activation of AmazonQ

- .changes/next-release/Bug Fix-b37b002f-d988-4b1c-ab9c-7ab16d2291f5.json
- packages/core/src/codewhisperer/views/lineAnnotationController.ts
Missing `set(inlinehintKey, this._currentState.id, globals.context.globalState)` call
Add `set(inlinehintKey, this._currentState.id, globals.context.globalState)` call
> fix(codewhisperer): fix tutorial state not persisted when user press esc to skip tutorial

- packages/core/src/auth/auth.ts
- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/core/src/shared/errors.ts
- packages/core/src/test/credentials/auth.test.ts
In Auth we were having premature SSO connection expiration issues due to network problems such as no internet connection. If the extension attempted a token refresh, or the extension was started without internet connected, the existing auth token would be invalidated.
We had some code that validated the token, but if it failed
due to network issues it would invalidate it.
Now, when we validate the token and there is a network error,
we will keep the state as-is instead of setting the connection
to invalid.
The user will instead see an error message indicating network issues or a log message depending on the action
performed.
Some renaming in the auth code to improve readability. See each commit for specifics.
By submitting this pull request, I confirm that my contribution is made under …
> fix(auth): network error may invalidate SSO token

- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/service/diagnosticsProvider.ts
- packages/core/src/codewhisperer/service/securityScanHandler.ts
- packages/core/src/codewhisperer/util/securityScanLanguageContext.ts
- packages/core/src/codewhisperer/util/zipUtil.ts
- packages/core/src/test/codewhisperer/commands/basicCommands.test.ts
- packages/core/src/test/codewhisperer/commands/startSecurityScanOld.test.ts
- packages/core/src/test/codewhisperer/util/securityScanLanguageContext.test.ts
- packages/core/src/testE2E/codewhisperer/securityScan.test.ts
Add support for auto scanning of the current active file.
- Add `ZipUtil` helper to prepare current file's contents as a zip file (tweaked from `DependencyGraph` implementation)
- Update `startSecurityScan` to run a scan on the current active file
- Add new activation subscriptions for auto scanning:
- when the extension first loads
- when contents of the text editor changes
- when the active text editor changes
- when the auto scan toggle has been enabled
- Add new `isLanguageSupported` check for security scans
Todo next: Update the existing security scan trigger to scan the whole project without dependency graph logic
> codewhisperer: zip util and triggers for file scans

- packages/core/src/applicationcomposer/messageHandlers/emitTelemetryMessageHandler.ts
- packages/core/src/applicationcomposer/types.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
We're tracking resource counts in the App Composer console, but not in the VS Code extension. This allows for tracking that telemetry event in VSC as well.
This adds the `AppcomposerResourceCount` telemetry event, which records the `resourceCounts` and `totalResourceCount` values coming from `FigAssets`.
No testable changes added, as this uses existing telemetry tracking mechanisms.
> telemetry: appcomposer_initializeProject metric

- packages/core/src/auth/auth.ts
- packages/core/src/auth/secondaryAuth.ts
- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/codewhisperer/util/authUtil.ts
Deletion events from Toolkit to Amazon Q does not refresh Amazon Q UX.
Let deletion events from Toolkit to Amazon Q refresh Amazon Q UX.
When Toolkit delete a connection, if that connection also exists in Q, then Q only removes this connection from momento DB and active connection state.  Q do not perform logout API call. Q also updates login UX and status bar.
If that connection is not in Q, do nothing. 
> fix(cwspr): properly handle deletion from toolkit to q

- packages/core/src/login/webview/vue/amazonq/backend_amazonq.ts
- packages/core/src/login/webview/vue/login.vue
See #9 in the doc. 
> Be signed out of QSign into SSO in ToolkitUse existing connection to sign into Q, which should trigger a new auth to add the Q scopesCancel the login attemptQ is now unauthenticated, but we see the chat window AND the status bar menu says we are logged in if we open it
Do not use the addScopes API which has many race conditions & edge cases because it update connection states, which triggers API to change toolkit states..
Instead use reauthenticate API. Also fix the await issue in forEach() loop. Previously, the forEach(async() => ) is not awaited.
https://github.com/aws/aws-toolkit-vscode/assets/97199248/5965acc6-6162-428a-a68d-7ce42f7f9b80
> fix(standalone): Fix cancellation not working as expected when cancel from adding scope flow

- packages/core/src/auth/ui/vue/show.ts
- packages/core/src/awsexplorer/activation.ts
- packages/core/src/dev/activation.ts
- packages/core/src/login/webview/vue/toolkit/backend_toolkit.ts
When signing in to Code Catalyst using IdC, Code Catalyst scope is missing.
Add  Code Catalyst  scope by invoking
`await this.codeCatalystAuth.connectToEnterpriseSso(startUrl, region)`
> fix(codecatalyst): use code catalyst sso login in new login view

- package-lock.json
- packages/core/src/auth/auth.ts
- packages/core/src/auth/sso/model.ts
- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/core/src/test/credentials/auth.test.ts
- packages/core/src/test/credentials/sso/model.test.ts
- packages/core/src/test/credentials/sso/ssoAccessTokenProvider.test.ts
Before, `aws_loginWithBrowser` metric only represented the opening of the browser window and not the part where users would login and confirm scopes. So if they failed somewhere in the browser, `aws_loginWithBrowser` would still result in `Succeeded`.
We did not have good insight in to the success of the part where we poll until the user completes the browser login.
Now, `aws_loginWithBrowser` will include the part where the user must login and accept scopes. Only once that is done do we emit Succeeded.
> telemetry: aws_loginWithBrowser includes user polling

- packages/core/src/codewhisperer/client/user-service-2.json
- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/codewhisperer/service/securityIssueHoverProvider.ts
- packages/core/src/codewhisperer/util/telemetryHelper.ts
CodeRemediationEvent should also be sent to CWSPR service. Currently they are sent to toolkit telemetry. 
Add CodeRemediationEvent for SecurityScan. 
No customer facing changes. 
Reference: https://github.com/aws/aws-toolkit-jetbrains/pull/4221
> fix(codewhisperer): Add CodeRemediationEvent for SecurityScan

- packages/core/src/auth/auth.ts
- packages/core/src/shared/errors.ts
We have a function `isNetworkError()` that determines if a an error is network related.
The issue is that we can see other network related errors in our telemetry metric `aws_refreshCredentials` that are not caught by `isNetworkError()`.
Add some of the network errors that we see in telemetry to the isNetworkError check.
This will improve false token invalidations during the sso token refresh process since we were previously invalidating incorrectly on certain network issues
> auth: add more network related errors to check

- package-lock.json
- packages/core/package.json
- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/service/diagnosticsProvider.ts
- packages/core/src/codewhisperer/util/zipUtil.ts
- packages/core/src/test/codewhisperer/commands/startSecurityScan.test.ts
- packages/core/src/test/codewhisperer/util/zipUtil.test.ts
Add support for full project scans
- Decouple scans from dependency graph logic
- Refactor startSecurityScan method to support Project scan type
- Add `ignore` package to exclude ignored files from artifact
- Include all Java `.class` files in the artifact
> codewhisperer: update zipUtil for full project scans

- packages/core/src/codewhisperer/views/lineAnnotationController.ts
telemetry ui_click `codewhisperer_learnmore_case*` should ONLY be sent if users complete the corresponding case/step. However
- `codewhisperer_learnmore_case_1` is sent as soon as user has seen it
- root cause: `seen.has(this.currentState)` will allow case_1's telemetry sent and not blocking it because either case_1a or case_2 is not in the set of `seen` https://github.com/aws/aws-toolkit-vscode/pull/4632/files#diff-9c8a244cafa64940c3c9f141252d08c61e9e6e79cf5e84773548bd1961f3591eL432
- `codewhisperer_learnmore_case_3` is *not* sent if the step is fulfilled by 30s timeout (case_3 has two exit criteria: one is to click the statusBar and the other is it will disappear itself after 30 seconds)
- root cause: invocation of `markTutorialDone` will immediately stop any logic being executed within …
> fix(codewhisperer): inline tutorial telemetry

- docs/api.md
- package-lock.json
- packages/core/src/auth/auth.ts
- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/test/credentials/auth.test.ts
- packages/core/src/test/credentials/sso/ssoAccessTokenProvider.test.ts
This PR does the following:
- Requires a `source` argument for partner teams using the VS Code command `aws.codeWhisperer.connect`
- We will use this to help identify which external extension is using the toolkit to connect
- In the metric `aws_loginWithBrowser` we are adding in the attribute `credentialStartUrl`
- This will help us determine which type of SSO the user is using when they go through the browser login flow for SSO
> auth: add more info when connecting to auth

- packages/amazonq/package.json
- packages/amazonq/src/extensionShared.ts
- packages/core/package.json
- packages/core/package.nls.json
- packages/core/src/amazonq/activation.ts
- packages/core/src/amazonq/explorer/amazonQChildrenNodes.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/applicationcomposer/messageHandlers/openFeedbackMessageHandler.ts
- packages/core/src/auth/credentials/utils.ts
- packages/core/src/auth/ui/vue/show.ts
- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/codewhisperer/commands/startTransformByQ.ts
- packages/core/src/codewhisperer/ui/codeWhispererNodes.ts
- packages/core/src/codewhisperer/vue/backend.ts
- packages/core/src/extension.ts
- packages/core/src/extensionShared.ts
- packages/core/src/extensionWeb.ts
- packages/core/src/feedback/index.ts
- packages/core/src/feedback/vue/submitFeedback.ts
- packages/core/src/index.ts
- packages/core/src/shared/credentials/defaultCredentialSelectionDataProvider.ts
- packages/core/src/shared/extensionUtilities.ts
- packages/core/src/test/amazonq/auth/controller.test.ts
- Hide unnecessary auth commands in amazon q (we should evaluate and remove them in the future)
- Add Q versions of generic toolkit commands for: feedback, going to github, about extension, submit issue, etc.
- This means the status bar menu github button works now.
- Ellipses for Q menu now independent of the toolkit ext.
- Toolkit explorer buttons no longer throw missing command errors.
- Cleanup package.json to remove unneeded or unused context values.
> fix(commands): update command handling and ellipses menus for q, toolkit explorer

- buildspec/release/10changeversion.yml
- buildspec/release/20buildrelease.yml
- buildspec/release/40pushtogithub.yml
- buildspec/release/50githubrelease.yml
- buildspec/release/60publish.yml
- To publish to marketplace.
- Env var `TARGET_EXTENSION` will be provided by the release pipeline.
- Only one .vsix is expected at a time.
- Only 'toolkit' will get the full release for now (e.g. a github release). We will revisit full releasing soon.
> ci: add dynamic release/publish capability

- docs/web.md
- packages/core/src/shared/extensionGlobals.ts
- packages/core/src/test/codewhisperer/commands/basicCommands.test.ts
- packages/core/src/test/shared/sam/sync.test.ts
- packages/core/src/test/shared/telemetry/telemetryService.test.ts
CI sometimes fails because the `ToolkitGlobals.context` global is undefined.
TypeError: Cannot read properties of undefined (reading 'asAbsolutePath')
at resolveIconId (…/aws-toolkit-vscode/packages/core/src/shared/icons.ts:90:33)
at …/aws-toolkit-vscode/packages/core/src/shared/utilities/functionUtils.ts:77:64
at createFeedbackNode (…/aws-toolkit-vscode/packages/core/src/codewhisperer/ui/codeWhispererNodes.ts:223:26)
at Suite.<anonymous> (…/aws-toolkit-vscode/packages/core/src/test/codewhisperer/commands/basicCommands.test.ts:302:49)
...
at runMocha (…/aws-toolkit-vscode/packages/core/src/test/testRunner.ts:93:16)
at runTests (…/aws-toolkit-vscode/packages/core/src/test/testRunner.ts:118:11)
This suggests either:
- `globalSetup.test.ts` is not invoked before the test is executed
- mocha …
> fix(tests): undefined ToolkitGlobals.context

- .gitignore
- scripts/generateNonCodeFiles.ts
- scripts/package.ts
- generateNonCodeFiles wont fail if certain files don't exist
- fix packaging command to ignore the missing repo field in amazonq because its temporary
> fix(amazonq): packaging after merge from mainline

- packages/core/src/amazonq/explorer/amazonQChildrenNodes.ts
- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/extension.ts
Toolkit Q users should be migrated to Q standalone.
Auto install AmazonQ when logging into aws toolkit for existing Q users. Prompt for Q install for new users. 
> feat(amazonq): Auto install AmazonQ when logging into aws toolkit

- packages/core/src/shared/clients/codecatalystClient.ts
aws-sdk automatically adds the bearer token to requests during the signing process. The CodeCatalystClientInternal `call()` function manually adds the bearer token to the header which is unnecessary and may cause confusion.
Remove the header assignment
> fix(CodeCatalyst): remove redundant bearer token header

- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/ui/codeWhispererNodes.ts
- packages/core/src/codewhisperer/ui/statusBarMenu.ts
- packages/core/src/test/codewhisperer/commands/basicCommands.test.ts
There are two menu options for security scans, it may be unclear what the difference is.
- Create a new sub menu section for security scans
- Update labels
- Also updated diagnostic source label
> codewhisperer: update menu item labels

- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/test/codewhisperer/commands/basicCommands.test.ts
- packages/core/src/test/codewhisperer/commands/startSecurityScan.test.ts
- packages/core/src/test/globalSetup.test.ts
- packages/core/src/testInteg/globalSetup.test.ts
- packages/core/src/testWeb/testRunner.ts
- UI cost: Security Scan feature creates vscode Output channel on startup. This is unnecessary for users that aren't currently using that feature.
- ![image](https://github.com/aws/aws-toolkit-vscode/assets/55561878/e7e2437e-3dbc-4c4c-80a4-918a27558cd3)
- create Security Scan channel on-demand, instead of in module-scope.
- ![image](https://github.com/aws/aws-toolkit-vscode/assets/55561878/405feaaa-405b-4bbc-b3b1-bb98889cbe49)
> fix: Toolkit creates too many Output channels

- packages/core/src/awsexplorer/activation.ts
- packages/core/src/extension.ts
- packages/core/src/extensionShared.ts
- packages/core/src/shared/extensionGlobals.ts
- packages/core/src/shared/extensions.ts
- packages/core/src/test/fakeExtensionContext.ts
Problem:
- Toolkit creates a "Remote Invocations" channel that is:
- never actually used by the Lambda remote invoke feature.
- created eagerly on startup, even if APIG or Lambda remote invoke are never used (clutters the user's OutputChannel list).
Solution:
Use the main Toolkit OutputChannel instead.
Followup to https://github.com/aws/aws-toolkit-vscode/pull/4527
> fix: Toolkit/Q creates too many Output channels

- buildspec/release/50githubrelease.yml
Problem: CodeBuild running sh, not bash.
Solution: Use sh compatibly syntax.
> fix(release): don't use bash syntax in buildspec

- packages/core/src/extension.ts
related: https://github.com/aws/aws-toolkit-vscode/pull/4656
fix(ci): tests hang on showInformationMessage()
Tests hang since da98c70a1aad5946515b0b941c6e1fa1535d1588
Don't await messages that require user input.
---
- da98c70 first commit where Toolkit fails to initialize (thus any commit hereafter _could_ cause a hang, but we don't know because CI fails to run the tests at all)
- [removing the "globals" proxy](https://github.com/aws/aws-toolkit-vscode/pull/4662/commits/f9be94cf8061a01a81991ba8642ab8c55b78db3f) allows the tests to run, and CI indeed hangs at commit https://github.com/aws/aws-toolkit-vscode/commit/da98c70a1aad5946515b0b941c6e1fa1535d1588 . This indicates:
- the hang isn't caused by later commits
- the hang isn't caused by …
> fix(ci): tests hang on showInformationMessage()

- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/extension.ts
Command `aws.codeWhisperer.connect` should only be declared in Amazon Q. 
1. Move the declaration & registration of command `aws.codeWhisperer.connect` inside Amazon Q activation.
2. Output log information when the declaration of command `aws.codeWhisperer.connect` fails. 
> feat(codewhisperer): only register cw.connect command in Q

- packages/core/src/testE2E/amazonq/featureDev.test.ts
The current e2e prompts cause false positive rejections and other internal quality issues which we are working on resolving.
The new prompts are more stable. It used to always fail now it passed twice in a row.
> fix(tests): amazon q featureDev e2e test prompts

- packages/core/src/login/webview/vue/amazonq/backend_amazonq.ts
- packages/core/src/login/webview/vue/backend.ts
- packages/core/src/login/webview/vue/login.vue
- packages/core/src/login/webview/vue/toolkit/backend_toolkit.ts
For users who migrate from toolkit to Q, we need to let them use Q without doing any login. The migration should be seamless.
For users who installed Q, if this user
1. Has aws toolkit installed
2. has a Amazon Q connection in toolkit 
3. Do not have any connection in Q.
Then we know this user is doing the migration from toolkit to Q, in this case, we skip the login screen for the user and immediately use the toolkit connection in Q. 
> feat(amazonq): Skip login screen for migration use case

- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/client/user-service-2.json
- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/service/diagnosticsProvider.ts
- packages/core/src/codewhisperer/service/securityScanHandler.ts
- packages/core/src/codewhisperer/util/zipUtil.ts
- packages/core/src/test/codewhisperer/commands/startSecurityScan.test.ts
- packages/core/src/test/codewhisperer/util/zipUtil.test.ts
- packages/core/src/testE2E/codewhisperer/securityScan.test.ts
Need to tell CreateCodeScan API the type of scan to perform
- Pass `scope` to CreateCodeScan API which is either `FILE` or `PROJECT`
- Update `scanType` enum to `scope` for consistency
> codewhisperer: pass scope to createCodeAnalysis api

- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/extension.ts
1. [NEW FEATURE] Installing Amazon Q from toolkit should immediately open Q extension view.
2. [BUG FIX] aws.codewhisperer.connect command conflict when user first install toolkit then install Q.
3. [BUG FIX] 2 installation notification displayed at the same time
4. [NEW FEATURE] User can click dismiss (X) button when seeing the ask user to install Q notification.   If user does not click that button, there will be no resp. It is not considered as dismiss.
> fix(amazonq): Fix various auto-installation issue

- packages/core/src/codewhisperer/client/user-service-2.json
- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/service/securityScanHandler.ts
- packages/core/src/testE2E/codewhisperer/securityScan.test.ts
Need to tell createUploadUrl API which type of scan to perform
Pass `uploadIntent` field to API which is either `AUTOMATIC_FILE_SECURITY_SCAN` or `FULL_PROJECT_SECURITY_SCAN`
> codewhisperer: pass upload intent to api

- packages/amazonq/package.json
- packages/amazonq/scripts/build/syncPackageJson.ts
- packages/core/package.json
- packages/core/package.nls.json
- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- packages/core/src/codewhisperer/util/codewhispererSettings.ts
- packages/core/src/codewhisperer/util/dependencyGraph/javaDependencyGraph.ts
- packages/core/src/shared/settings.ts
- packages/toolkit/scripts/build/handlePackageJson.ts
Rename settings from CodeWhisperer to Amazon Q.
Note: 
1. Renaming customer facing commands will be part 3 or later PR. 
2. Log level and telemetry will now be aws level configurations. They are shared between toolkit & Q. 
3. Migrating old settings to new settings is not in scope of this PR. 
> feat(amazonq): Rename settings from CodeWhisperer to Amazon Q: part 2

- .changes/next-release/Bug Fix-f5a0ad13-60ce-4ee4-9da9-0687d0961466.json
- packages/core/src/amazonq/webview/ui/quickActions/generator.ts
- Quick actions in newly opened tabs are coming all disabled. Reported on the [jetbrains PR](https://github.com/aws/aws-toolkit-jetbrains/pull/4262#issuecomment-2052275174) by @mk-fan 
- Unknown tab types follows the rules of Chat tabs for quick action disabled states since they are getting converted to chat tabs.
> fix(amazonq): Quick Action commands in new tabs are coming disabled

- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/core/src/shared/telemetry/util.ts
Amazon Q standalone needs a new client name
Use different client name for registration
> fix(amazonq): Update Client Name and User Agent

- packages/core/src/shared/vscode/commands2.ts
codewhisperer manual trigger not working in Q
Correct the command name prefix. 
> fix(amazonq): Fix codewhisperer manual trigger not working in Q

- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/test/amazonqFeatureDev/controllers/chat/controller.test.ts
File acceptance telemetry was not counting deleted files, i.e. the files that code generation marked to be deleted, even if they were rejected or not.
Count deleted files for the metric and add tests to assure this.
> fix(amazonFeatureDev): accepted files telemetry

- packages/core/src/amazonqGumby/chat/controller/controller.ts
Users can provide a JAVA_HOME with trailing or leading whitespaces, this causes issues when resolving the JAVA_HOME. 
Using `.trim()` to do preliminary cleanup of the string.
Would prefer to do UT as fast follow since I have limited bandwidth for this PR currently.
> Amazon Q CodeTransform: Trim leading and trailing whitespace from user provided JAVA_HOME.

- packages/core/src/auth/sso/server.ts
- packages/core/src/test/credentials/sso/server.test.ts
- Auth server was being bound to all interfaces
- Bind it only to 127.0.0.1
> fix: only bind auth server to 127.0.0.1

- packages/core/src/auth/sso/server.ts
- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/core/src/test/credentials/sso/server.test.ts
- We get:
rejected promise not handled within 1 second: Error: AuthSSOServer: foo: foo
rejected promise not handled within 1 second: Error: AuthSSOServer: invalid state
rejected promise not handled within 1 second: Error: AuthSSOServer: missing code
rejected promise not handled within 1 second: Error: AuthSSOServer: missing state
- Catch and test the authorization promise
> fix: handle rejected promise in server tests

- .changes/next-release/Feature-51070f02-21b0-447b-9743-e7ce616337fe.json
- packages/core/src/amazonq/explorer/amazonQTreeNode.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/test/codewhisperer/util/authUtil.test.ts
- packages/core/src/testE2E/util/codewhispererUtil.ts
We want to enable builder id authentication for amazon q. This will allow all Q features to use builder id, including gumby (code transform).
This change does not completely work yet as it is still missing the backend changes. The goal here is to just show the /dev and /transform commands in vscode when signed in with builder id and request the correct scopes.
Add the amazon q scopes to the builder id connection and show /dev and other q chat commands.
> feat(amazonq): enable builder id auth for amazon q

- .vscode/extensions.json
- CONTRIBUTING.md
- packages/amazonq/.vscode/extensions.json
- packages/core/.vscode/extensions.json
- packages/toolkit/.vscode/extensions.json
When we build locally this problem matcher helps the IDE detect that a webpack watch execution is finished so that the build scripts can progress. It is now required but there isn't a good mechanism to force developers to install it.
- The extension is required so we now mention this in the docs
- We set it as recommended extension for developers in `extension.json`.
- Remove the old duplicated `extensions.json` files for a singular one in the root
> test: update to require problem matcher extension

- packages/core/src/amazonqFeatureDev/storages/chatSession.ts
- packages/core/src/test/amazonqFeatureDev/session/chatSessionStorage.test.ts
When a customer starts a /dev chat with a message, e.g. /dev <do something>, the connector logic calls two event handlers in amazonqFeatureDev logic parallely that try to create a session, this creates a race condition where the customer could get to code generation with the wrong session, i.e. one with no conversationId.
Add a lock to the getSession function in order to mitigate concurrent calls to getSession.
This is a similar approach to the one taken in JetBrain's toolkit: [ChatSessionStorage.kt](https://github.com/aws/aws-toolkit-jetbrains/blob/ec168fc6e9306f22f07945fd516d6acdc7fe396e/plugins/amazonq/chat/jetbrains-community/src/software/aws/toolkits/jetbrains/services/amazonqFeatureDev/storage/ChatSessionStorage.kt#L18)
By submitting this pull request, I confirm that my contribution …
> fix(amazonqFeatureDev): mitigate race conditions on session creation

- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/service/securityScanHandler.ts
- packages/core/src/codewhisperer/ui/statusBarMenu.ts
Change Timeout limits for project scan and File scans. No Auto Scan status bar options for Free Users(BuilderId) and no file scans enabled for Builder Id users.
- Added Timeout Limits for Project and File Scans.
- Disabled File scan for BuilderID users.
- Removed status bar Code scan toggle option for Builder Id Users.
Compiled and run a debug extension
> feat(q-proactive-scan): remove file scans for Builder Id, add timeout limits

- packages/core/src/shared/extensionUtilities.ts
- If you are using the about from the amazon q extension it shows AWS Toolkit. e.g. "AWS Toolkit: 0.10.0"
- If you are using the q extension then show Amazon Q Toolkit
> fix: About extension message always shows AWS Toolkit

- packages/core/src/codewhisperer/client/user-service-2.json
- packages/core/src/codewhisperer/service/securityScanHandler.ts
- Adding dynamic requestHeaders for `uploadArtifactToS3`.
- Adding try/catch block for `uploadArtifactToS3 ` to catch any exception and show the error message.
> codewhisperer: telemetry(requestHeaders property) and error handling for uploadArtifactS3Url

- package-lock.json
- packages/core/package.json
- packages/core/src/amazonq/webview/ui/apps/cwChatConnector.ts
- packages/core/src/amazonq/webview/ui/connector.ts
- packages/core/src/amazonq/webview/ui/main.ts
- packages/core/src/codewhispererChat/controllers/chat/model.ts
- packages/core/src/codewhispererChat/controllers/chat/telemetryHelper.ts
- packages/core/src/codewhispererChat/view/messages/messageListener.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- Missing parameters in `onCopyCodeToClipboard` and `onCodeInsertToCursorPosition` events for telemetry.
- Added `cwsprChatCodeBlockIndex` and `cwsprChatTotalCodeBlocks` parameters to the `onCopyCodeToClipboard` and `onCodeInsertToCursorPosition` events.
- `cwsprChatCodeBlockIndex` - Provides the index of that code block, when a user interacts with a code block within a message in the conversation, 
- `cwsprChatTotalCodeBlocks` - Total number of code blocks inside a generated message.
- Passed these two parameters to `insert_code_at_cursor_position` and `code_was_copied_to_clipboard` telemetry events.
> Added telemetry parameters to the Q chat events.

- packages/core/src/codewhisperer/client/user-service-2.json
- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- packages/core/src/codewhisperer/service/securityScanHandler.ts
- packages/core/src/testE2E/codewhisperer/securityScan.test.ts
CreateUploadUrl and CreateCodeScan APIs now require CodeScanName field
Pass a random UUID to the APIs
> codewhisperer: add code scan name to api calls

- packages/core/src/amazonq/activation.ts
- packages/core/src/amazonq/explorer/amazonQChildrenNodes.ts
- packages/core/src/amazonq/onboardingPage/index.ts
- packages/core/src/auth/ui/vue/show.ts
- packages/core/src/codewhispererChat/commands/registerCommands.ts
Before, we had a function to show the chat webview or used the vscode generated show chat command.
Now we have a single command which can be used anywhere. This will allow us to get better metrics on when the chat window is opened. It has a `source` property so users must indicate where it came from.
> amazonq: command to show the chat window

- packages/core/src/amazonq/webview/ui/texts/constants.ts
- packages/core/src/amazonqFeatureDev/errors.ts
- packages/core/src/amazonqFeatureDev/userFacingText.ts
Currently for Q Feature development, users are not informed with an appropriate message in case of failures to upload user artifacts to S3.
Updated the error message to show upload failures to customers.
> QFeatureDev- handled upload failure with specific message

- packages/core/src/codewhisperer/models/constants.ts
- Existing error message is generic and provide little context for upload artifact failure.
- Change in Error message for `uploadArtifactToS3` in Gumby . 
- Provides information about the error with link in both chat and notification.
> Change in Error message for Gumby for CreateArtifactToS3 upload url

- packages/core/package.json
- toolkit auth and codecatalyst manageConnections both show "Add New Connection" in the command palette
- we can hide codecatalyst manageConnections because it's a wrapper around the toolkit auth command that sets the source
> fix: disable codecatalyst manageConnections from command palette

- packages/amazonq/scripts/build/copyFiles.ts
- Amazon q extension doesn't have the resources for the auth page
- Copy them in
> fix: copy auth page to amazon q extension

- .changes/next-release/Bug Fix-621c779b-2052-4373-9db0-6d02bec363d7.json
- packages/core/src/codewhisperer/commands/startTransformByQ.ts
- packages/core/src/codewhisperer/service/transformByQ/transformationResultsViewProvider.ts
Customers who ran multiple jobs after each other without accepting / rejecting changes could not see proposed changes for the subsequent job.
(have videos with behaviour, but too large for github upload)
Reset state when new job is submitted + streamline reset logic into one piece of code (previously scattered in two places)
1. Ran three jobs in a row and verified the proposed changes could be downloaded each time.
(have videos with behaviour, but too large for github upload)
> Q Code Transformation - Reset state between sequential job runs 

- .changes/next-release/Feature-0fb1a891-a6c4-48a4-9229-879019b7831a.json
- .changes/next-release/Feature-18b63901-6443-4fc2-80e7-8dd85077b3e1.json
- .changes/next-release/Feature-dd0b3f2a-ad7d-420f-9efb-d5c678daf392.json
- packages/core/package.json
- packages/core/src/amazonq/activation.ts
- packages/core/src/codewhispererChat/commands/registerCommands.ts
- packages/core/src/codewhispererChat/editor/codelens.ts
- packages/core/src/codewhispererChat/editor/context/focusArea/focusAreaExtractor.ts
- packages/core/src/test/codewhispererChat/editor/codelens.test.ts
We want more ways for users to use Amazon Q chat.
This adds the following features:
- For first time users will show a CodeLens(small grey text above the current line) that prompts users to try Q Chat, and if clicked will open it
- We only show this codelens 10 times (can adjust if necessary). Then never show it again. We do not want to annoy the user.
- A new keyboard shortcut `cmd` + `i` which will open Q chat
- The right click `Send to Amazon Q` menu will always show now, before it only showed when a line was highlighted.
- If the user does a right click but no highlight, the entire line will be used in the command
> amazonq: habit building features

- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/login/webview/vue/amazonq/backend_amazonq.ts
- packages/core/src/login/webview/vue/backend.ts
- packages/core/src/login/webview/vue/login.vue
- packages/core/src/login/webview/vue/reauthenticate.vue
- packages/core/src/login/webview/vue/root.vue
- packages/core/src/login/webview/vue/selectableItem.vue
- packages/core/src/login/webview/vue/toolkit/backend_toolkit.ts
- packages/core/src/login/webview/vue/types.ts
New reauth page for Amazon Q
- When we detect the login page must be shown, we will then determine if a reauth is required. If so, we show the reauth page. Otherwise, we show the login page
- In the root.vue is where we determine which "auth flow" we are in and then show the appropriate auth page (currently Login vs Reauth)
- The Reauth page is designed to have all state determined outside of the Vue file itself, and instead managed in the backend code. Our front end connects to an event emitter from the backend. When emitter fires on a change with the auth connection, the frontend will refresh itself, pulling in all the current state data from the backend. This allows us to have more control in the backend over what we show and it centralizes our state to a single place.
- Did some …
> amazonq: reauthentication page

- packages/core/src/codewhisperer/client/user-service-2.json
- packages/core/src/codewhispererChat/controllers/chat/telemetryHelper.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
In q chat telemetry, lines of inserted code is not included.
Add lines of inserted code of Q chat in the telemetry event. 
This is not customer facing and this does not introduce a new telemetry event, so I am not adding a change log. 
Relevant JB PR:
https://github.com/aws/aws-toolkit-jetbrains/pull/4337
> feat(amazonq): Add accepted lines of code of Q chat telemetry

- packages/core/package.nls.json
- packages/core/src/codewhisperer/models/constants.ts
Previously, Settings command was displayed as `Amazon Q: Amazon Q Settings`, where `Amazon Q` was duplicated.
Updated the command text to `Amazon Q: Settings` 
> fix(amazonq): settings text

- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- packages/core/src/test/codewhisperer/commands/startSecurityScan.test.ts
File scans should run in the background and not show any errors.
- Only show scan failed error notification if scope is Project.
> fix(amazonq): suppress errors for file scans

- packages/core/src/login/webview/vue/login.vue
- packages/core/src/login/webview/vue/reauthenticate.vue
- packages/core/src/login/webview/vue/root.vue
- packages/core/src/login/webview/vue/selectableItem.vue
VSCode CSS issues for new auth page:
1. Q icon should be 71px, not 100px
2. First page: Looks like the width of buttons is wrapping to fit the contents - can we set the width of the sign in buttons and continue button 260px?
3. First page: Each of the elements should have a margin of 12px, buttons should have a padding of 12px
4. SSO/IAM Creds page: Back button is center aligned now for some reason
5. SSO/IAM Creds page: Padding and size of input fields are off (width: 244px; padding: 6px 8px;)
6. SSO/IAM Creds page: Margin should be 12px between groups
7. SSO/IAM Creds page: Field labels (ex. 'Start URL') should be 11px, with a weight of 500
8. In progress page: 12px margin between elements
9. In progress page: Cancel button should be secondary grey color
10. change to 'Sign in with AWS …
> fix(amazonq): Various css updates to login page

- packages/amazonq/src/extensionShared.ts
- packages/core/src/login/webview/index.ts
Import was directly from the `core` module, but needed to first be exported by it, then consumed as a `core` module export.
> fix Amazon Q import

- .changes/next-release/Bug Fix-e2494f30-8d61-4b13-97a1-e7631f92412c.json
- packages/core/src/amazonqFeatureDev/client/featureDev.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/messenger/messenger.ts
- packages/core/src/amazonqFeatureDev/errors.ts
Currently, on reaching monthly conversation limit for QFeature development, Retry button was incorrectly shown which would degrade customer experience as clicking on Retry would render them the same error again and again.
- Handled ServiceQuotaExceeded error correctly to not show Retry button on reaching monthly conversation limit.
> fix(q): Handle monthly conversation limit error for Q Feature development

- packages/core/src/login/webview/vue/login.vue
- any characters can be present after the issuer url
- only allow 16 alphanumeric characters after ssoins-
> fix(auth): stronger validation of sso url

- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- Right now we are relying on the auth server page load time to take less than the create token request. In the case where the auth server page load takes more time then the create token request the auth server will already be closed and won't be able to serve the ui
**note:** in practice this should actually never happen. This is just extra insurance that if it _does_ happen we are protected
- delay for 5000ms
> fix(auth): delay PKCE server close

- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
`void` should usually be avoided if a potential failure in the invoked function is not otherwise handled or logged. Especially in timers, failures will not surface in any other way.
> fix(auth): log AuthSSOServer.close() failure

- packages/core/src/codewhisperer/util/zipUtil.ts
- packages/core/src/test/codewhisperer/util/zipUtil.test.ts
When running project scans, the version on disk is used which could be outdated if there are unsaved changes in the workspace.
- Check if the file is open and dirty, if it is then use `getTextContent` instead of reading from disk
> fix(amazonq): use unsaved content for project scans

- packages/core/src/auth/connection.ts
- packages/core/src/login/webview/commonAuthViewProvider.ts
- packages/core/src/login/webview/vue/amazonq/backend_amazonq.ts
- packages/core/src/login/webview/vue/backend.ts
- packages/core/src/login/webview/vue/login.vue
- packages/core/src/login/webview/vue/toolkit/backend_toolkit.ts
- packages/core/src/login/webview/vue/types.ts
- refactor to allow for better telemetry state handling
- reauthenticate page keeps more informative state + more informative cancellation
- cancellation keeps better state about current auth status
- properly check scopes for what features are enabled
- add telemetry for using an existing connection (not autoconnect)
- fixed bug that prevented logging in with builder id emitting telemetry
todo:
- toolkit needs auth_userState emitted
- auto-connect for Q from toolkit needs to be reworked, its not captured in the initial auth_userState because it occurs on UI side
> feat(telemetry): improve login page telemetry

- packages/core/src/login/webview/vue/login.vue
8px is too small for some login text.
Update text description && use larger font. 
> fix(amazonq): Fix the small font size in login screen

- packages/amazonq/package.json
- packages/amazonq/src/extensionShared.ts
- packages/core/package.json
- packages/core/src/dev/activation.ts
- packages/core/src/dev/index.ts
- Toolkit owns dev mode, amazon q just sends state data to it for display and editing.
- This will help us debug and test the remaining items, since we can now edit state for amazon Q, e.g. expire connections, show welcome message again, etc.
> feat(dev): enable dev mode for amazon q if toolkit is installed

- packages/core/src/shared/telemetry/activation.ts
- packages/core/src/shared/telemetry/util.ts
In the previous PR https://github.com/aws/aws-toolkit-vscode/pull/4698,
Below cases are handled:
1. After toolkit fully activates, activate Q extension, then Q uses toolkit client id
2. After Q fully activates, install a new toolkit as new user, then toolkit uses Q client id. 
However, it cannot handle below case:
1. When toolkit and Q activates at the same time but Q  managed to write the client id to env var before toolkit does.
When toolkit and Q activates at the same time.
1. If Q first write the client id to env var, toolkit reads it, if this toolkit already has its client id, then toolkit is the lead (master). Toolkit decides that Q should use the client id of toolkit. Therefore, toolkit write its own client id to the env var, emit a command to let Q set its telemetry client id …
> fix(amazonq): Fix telemetry id sharing

- packages/core/src/codecatalyst/auth.ts
`IsOnboarded` status of CC connection is not checked when CC reuses Q connection
Force Toolkit check `IsOnboarded` status of CC connection. 
This is a fix that has minimal blast radius. It only affects the flow when CC reuses Q connection. However, the connection state management of CC should be able to intelligently forcing the `IsOnboarded` status update using the CC API when necessary and do not perform the update when not necessary ( like UI updates). 
https://github.com/aws/aws-toolkit-vscode/assets/97199248/234c44ca-95be-473b-9959-79b9322b29cf
> fix(amazonq): Switch UI when CC reused Q connection

- packages/core/src/testE2E/amazonq/featureDev.test.ts
- packages/core/src/testE2E/amazonq/framework/setup.ts
- a css file was added into mynah ui in https://github.com/aws/aws-toolkit-vscode/pull/4800 and jsdom can't load external css files so the e2e tests fail to load
- HACK: ignore amazonq-webview.css in the module loader
> fix: ignore q css files in feature dev e2e tests

- buildspec/linuxE2ETests.yml
Problem:
e2e tests always fail because of throttling, and whatever this is:
ProtocolError: Protocol error (Page.navigate): Target closed
Solution:
Skip the tests until these issues are fixed.
> tests: skip E2E tests

- packages/core/src/shared/extensionUtilities.ts
- isToolkit check was looking for amazonq
- should be looking for toolkit
> fix: amazonq check pointing to wrong toolkit id

- packages/amazonq/package.json
- packages/amazonq/scripts/build/syncPackageJson.ts
- packages/core/package.json
- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/util/codewhispererSettings.ts
- packages/core/src/shared/settings.ts
- packages/core/src/shared/telemetry/activation.ts
- packages/core/src/shared/telemetry/util.ts
- packages/core/src/test/shared/telemetry/util.test.ts
- 'AWS > Amazon Q: ...' --> 'Amazon Q: ...'
- updated setting migrations
- also updated how TelemetryConfig is handled
todo:
**- havent tested this yet, I will shortly.**
> chore(settings): rename amazon q settings

- packages/core/src/codewhisperer/activation.ts
- packages/core/src/extensionShared.ts
- packages/core/src/shared/utilities/logAndShowUtils.ts
When login view of Q goes wrong,  for example: When attempting to login with a user id whose access was revoked, the login failure error message was not properly displayed to user. 
Root cause: 
The webview error handler was registered in `extensionShared.ts`. However, `extensionShared.ts`is not shared, it only actives in AWS Toolkit. 
register webview error handler in Amazon Q
> fix(amazonq): register webview error handler in Amazon Q

- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- packages/core/src/codewhisperer/service/securityScanHandler.ts
- packages/core/src/codewhisperer/util/zipUtil.ts
- packages/core/src/testE2E/codewhisperer/securityScan.test.ts
File scans logs are too noisy
- Use NullLogger for file scans except for errors
> fix(amazonq): reduce logs for file scans

- packages/core/src/amazonqGumby/chat/controller/controller.ts
- packages/core/src/amazonqGumby/chat/controller/messenger/messenger.ts
- packages/core/src/amazonqGumby/errors.ts
- packages/core/src/codewhisperer/commands/startTransformByQ.ts
If we exited the [Human in the Loop](https://github.com/aws/aws-toolkit-vscode/pull/4607) feature early - due to user cancellation or an error - the chat was getting stuck in a state where the user could neither get the partial transformation of their flow or start a new transformation. 
We enter the status polling loop when we terminate HIL early, so that the backend can continue to give us progress on the transformation job. 
> fix(gumby): resume transformation job to get partial success when error occurs in HIL

- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/codewhisperer/service/diagnosticsProvider.ts
- packages/core/src/codewhisperer/service/securityIssueProvider.ts
- packages/core/src/test/codewhisperer/commands/basicCommands.test.ts
Scans can now run without saving the file to disk. No need to save the file to apply fix.
- Use WorkspaceEdit to apply fix
- If auto-scans is enabled, immediately remove the issue from hover and diagnostics after fixing it
> fix(amazonq): apply fix without save

- packages/core/src/login/webview/vue/selectableItem.vue
There was previously a jiggle when moving the mouse on the items since all border sizes were not the same.
Make a single css class with the base item properties so that regardless of state they all share the same border width.
Then the stateful classes like hover or selected will only change what they need to change.
https://github.com/aws/aws-toolkit-vscode/assets/118216176/00da6304-bbb6-45e6-8ee7-7d82dcb42f88
https://github.com/aws/aws-toolkit-vscode/assets/118216176/5e8f4ba3-adb7-414f-bb8d-ce00d49519ef
> ui: remove jiggle from Login page items

- packages/core/src/codewhisperer/ui/statusBarMenu.ts
- packages/core/src/test/codewhisperer/commands/basicCommands.test.ts
Auto-scans toggle needs to be hidden for BuilderID users (got removed while resolving merge conflicts).
Don't show Auto-scans toggle in status bar menu if BuilderID is in use.
> fix(amazonq): hide auto-scans for builder id

- packages/core/src/login/webview/vue/login.vue
- packages/core/src/login/webview/vue/selectableItem.vue
Fix font size of CC login. Also make the gap between start url and CC login to 12px.
> fix(amazonq): CodeCatalyst login text too small

- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- packages/core/src/codewhisperer/util/runtimeLanguageContext.ts
- packages/core/src/codewhisperer/util/zipUtil.ts
- packages/core/src/test/codewhisperer/commands/startSecurityScan.test.ts
Project scans fail server side validation if the active file is an unsupported codewhisperer language, even if there are other supported files in the project.
Get the highest occurring language from file extension when preparing the zip file and use that as the language
> fix(amazonq): get most occurring language from project

- packages/amazonq/src/extensionShared.ts
- packages/core/src/auth/ui/vue/authForms/types.ts
- packages/core/src/auth/ui/vue/types.ts
- packages/core/src/auth/utils.ts
- packages/core/src/extension.ts
- packages/core/src/extensionShared.ts
- packages/core/src/shared/telemetry/util.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- also, to match the spec we rename metric field from 'enabledAuthConnections' to 'authEnabledConnections'
> feat(telemetry): add auth_userState to toolkit ext

- CONTRIBUTING.md
- packages/amazonq/package.json
- packages/core/package.json
- packages/core/package.nls.json
- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- packages/core/src/shared/logger/activation.ts
- packages/core/src/shared/logger/logger.ts
- packages/core/src/shared/logger/outputChannelTransport.ts
- packages/core/src/shared/settings.ts
- packages/core/src/shared/telemetry/activation.ts
- packages/core/src/test/shared/logger/activation.test.ts
- packages/core/src/test/techdebt.test.ts
- aws.logLevel setting is unnecessary, because vscode now lets users control the log level by visiting the "AWS Toolkit Logs" output channel.
- aws.logLevel setting may cause Q to show a `Cannot register 'aws.logLevel'` error.
Use the AWS Toolkit Logs" output channel log-level as the source of truth.
> feat(logging): use OutputChannel log level

- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- packages/core/src/codewhisperer/service/diagnosticsProvider.ts
Duplicate hover and code actions are appearing for project scans because only the active file's issues are getting replaced.
Update every security recommendation by file path instead of only the active file.
> fix(amazonq): duplicate hover for project scans

- buildspec/release/10changeversion.yml
- buildspec/release/50githubrelease.yml
Now that we will be releasing multiple extensions, we will need to have separate tags and release titles in github.
> feat(release): separate ext release tags/titles

- packages/core/src/login/webview/vue/login.vue
Follow up of https://github.com/aws/aws-toolkit-vscode/pull/4865, 
restore the origin text with the CodeCatalyst name as required by product. 
> fix(amazonq): Fix login code catalyst text description

- packages/core/src/login/webview/vue/login.vue
- packages/core/src/login/webview/vue/selectableItem.vue
- Updated our strings for the Amazon Q Pro License
- Removed sub string message, per docs
- Updated CSS to handle SelectableItem with no itemText
> amazonq: string change "Pro license"

- packages/core/package.nls.json
Use correct URL for Q telemetry settings
> fix(amazonq): Use correct URL for Q telemetry settings

- package-lock.json
- packages/amazonq/.changes/next-release/Bug Fix-1d12cfc3-e729-419d-a15b-deb1326459df.json
- packages/core/package.json
Incoming markdown is strings are not getting parsed properly for the list items. 
Implemented a solution through [mynah-ui version 4..7.0](https://github.com/aws/mynah-ui/releases/tag/v4.7.0) which parses the list items again with `marked.parse`.
> fix(amazonq): Markdown parsing inside list items

- .changes/next-release/Bug Fix-de3f475e-93a7-4ba6-8b26-90b655e563ca.json
- packages/core/src/applicationcomposer/messageHandlers/addFileWatchMessageHandler.ts
fix(applicationcomposer): support out of workspace file watching
Problem:
- We found a bug: File watch is not working on template files which out side workspace
Solution:
- use a [complex glob pattern](https://code.visualstudio.com/api/references/vscode-api#RelativePattern) instead of a string as the parameter of [`createFileSystemWatcher` function](https://vscode-api.js.org/modules/vscode.workspace.html#createFileSystemWatcher)
> fix(applicationcomposer): support out of workspace file watching

- buildspec/release/10changeversion.yml
- buildspec/release/50githubrelease.yml
Problem: The tag name passed to this function doesn't match the tag that we created earlier. So, it will attempt to create a new tag. Since Amazon Q is starting at 1.0.0, this will conflict with existing toolkit releases
Solution: Add extension to tag, e.g. amazonq/v1.0.0 instead of just v.1.0.0
> fix(release): correct tag for 'gh release create' command

- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/util/codewhispererSettings.ts
- packages/core/src/shared/settings.ts
- packages/core/src/shared/telemetry/util.ts
- Improve setting migration logging.
- Remove global state check for migrating codewhisperer settings. With the current state of the setting migration code, this shouldn't be needed. The old values will never overwrite what is already defined.
> settings: remove global state check for amazonq migration

- packages/amazonq/.changes/next-release/Bug Fix-f5decdc1-1202-45f7-891c-b89643214089.json
- packages/core/src/amazonqFeatureDev/constants.ts
- packages/core/src/amazonqFeatureDev/util/files.ts
There are currently 2 problems in featureDev when doing collection of repository files:
- Trying to decode binary files might crash the extension host, and 
- too large repos might make the extension run out of available memory.
This CR fixes both problems by:
- Adding a maximum allowed repo size of 200mb for collection
- Changing the behavior of the TextDecoder to replace the unsupported characters instead of throwing TypeError
Users who try to use featureDev on a codebase larger than 200mb will see a message asking for a different workspace to be selected.
> fix(featureDev): Prevent crash on large repos or unsupported encoding during file collection

- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/toolkit/.changes/next-release/Bug Fix-8d3c99b7-280e-41af-8f32-b52495610be0.json
- due to a bug in https://github.com/microsoft/vscode/pull/206381/files#diff-efa08c29460835c0ffa740d751c34078033fd6cb6c7b031500fb31f524655de2R360 installExtension will fail on remote environments when the amazon q extension is already installed locally
- install the amazon q extension using the vscode cli
- Installing directly from github releases if they're on a remote environment. Its unclear though if the user will always be able to reach github (vs marketplace which is required to install extensions anyways)
- If the user doesn't have the vscode cli (though I think it autoinstalls in remotes?) then this won't work
> fix: installation error when installing amazon q in remote AND you have the extension locally

- package-lock.json
- packages/amazonq/.changes/next-release/Bug Fix-700e4ec0-f012-405a-9073-b0a0478bd154.json
- packages/core/package.json
Copy to clipboard on code blocks in q chat doesn't work
Fixed with [mynah-ui v4.7.1](https://github.com/aws/mynah-ui/releases/tag/v4.7.1)
> fix(amazonq): Copy to clipboard doesn't work

- packages/core/src/shared/telemetry/util.ts
We attempt to migrate in both extensions, even though we should only do so in the amazon q setting. The toolkit attempt fails, but it still pollutes the state with the stored keys.
This isn't expected to have an effect because the states of the 2 exts are presumed to be separate, but maybe there is a subtle bug revolving around stating here.
> fix(settings): only migrate telemetry setting if we are in amazon q

- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- packages/core/src/test/codewhisperer/commands/startSecurityScan.test.ts
File scan metrics should be passive
Set `passive` to true if current scope is `FILE`
> telemetry: mark file scans as passive

- packages/amazonq/.changes/next-release/Bug Fix-f3dc220b-64f4-4e50-990a-9c825baf14e2.json
- packages/core/src/codewhisperer/service/securityScanHandler.ts
- packages/core/src/test/codewhisperer/service/securityScanHandler.test.ts
Security issues appear multiple times in the same line if the ListCodeScanFindings response is paginated.
Create the issues list from issues map only once per scan instead of on every page response.
> fix(amazonq): address duplicate security issue bug

- .eslintrc.js
- packages/core/src/auth/deprecated/loginManager.ts
- packages/core/src/codewhisperer/service/transformByQ/transformationResultsViewProvider.ts
- packages/core/src/eventSchemas/vue/searchSchemas.ts
- packages/core/src/shared/awsContextCommands.ts
- packages/core/src/shared/cloudformation/activation.ts
- packages/core/src/shared/extensionStartup.ts
- packages/core/src/shared/extensions/ssh.ts
- packages/core/src/shared/sam/activation.ts
- packages/core/src/shared/sam/debugger/csharpSamDebug.ts
- plugins/eslint-plugin-aws-toolkits/index.ts
- plugins/eslint-plugin-aws-toolkits/lib/rules/no-await-on-vscode-msg.ts
- plugins/eslint-plugin-aws-toolkits/lib/rules/no-only-in-tests.ts
- plugins/eslint-plugin-aws-toolkits/test/rules/no-await-on-vscode-msg.test.ts
- plugins/eslint-plugin-aws-toolkits/test/testUtil.ts
- add new lint rule with test suite.
- fix cases found by the lint rule.
This lint rule would have prevented the bug that was fixed in #4833
> lint: add no-await-on-vscode-msg custom rule

- package-lock.json
- packages/amazonq/.changes/next-release/Bug Fix-c2be4698-9cf5-4e3f-9411-8a8aff3c07fb.json
- packages/core/package.json
Code fields inside listitems for the markdowns are showing parts of the typewriter animator wrapper spans.
Updated markdown parser structure and added a skip also to the code fields inside the list items through [`mynah-ui v4.8.0`](https://github.com/aws/mynah-ui/releases/tag/v4.8.0)
> fix(amazonq): Listitems inside markdown shows shows typewriter wrapper spans as text

- packages/core/src/codecatalyst/commands.ts
- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/shared/telemetry/util.ts
- packages/core/src/shared/vscode/env.ts
- We are constantly making the same remote workspace check
- Extract it
I'm probably going to have to add it in an up and coming PR, might as well extract it ahead of time
> refactor: create helper to identify remote workspaces

- packages/core/src/login/webview/vue/backend.ts
- packages/core/src/login/webview/vue/login.vue
- packages/core/src/shared/settings.ts
New dev setting to autofill the start url:
```
"aws.dev.autofillStartUrl": "<url>"
```
Should probably be integrated into the login page for all users somehow, but that requires some UX thought. Here is a quick fix for devs.
> feat(dev): autofill login starturl setting

- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/models/model.ts
- packages/core/src/codewhisperer/service/diagnosticsProvider.ts
- packages/core/src/codewhisperer/service/securityScanHandler.ts
- packages/core/src/test/codewhisperer/commands/startSecurityScan.test.ts
- packages/core/src/testE2E/codewhisperer/securityScan.test.ts
Optimize and reduce the number of API calls for file scans
- Increase debounce delay from 2 to 5 seconds.
- Increase polling frequency from 1 to 5 seconds.
- Add a polling delay of 10 seconds (file scans) or 20 seconds (project scans).
- Cancel (stop polling) previous scan if a new scan starts.
> fix(amazonq): reduce api calls for file scans

- packages/amazonq/.changes/next-release/Bug Fix-12271e0b-126f-4112-936d-a94ad0566aee.json
- packages/core/src/codewhispererChat/editor/context/focusArea/focusAreaExtractor.ts
Ask Q to write a unit test of a function, Q does not know how to do it. It hallucinates the function.( It does not know which class I am generating against). See internal TT P128119238. 
Let the cursorState.range be undefined if user do not have a selection. The function `getSelectionInsideExtendedCodeBlock` is supposed to take the original selection as input, not the importantRange ( which is current line of cursor)
> fix(amazonq): fix codeSelection incorrect if user has no selection

- packages/amazonq/.changes/next-release/Feature-5ccb4f03-68ca-4582-93a8-6c6a40397f14.json
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/test/codewhisperer/util/crossFileContextUtil.test.ts
1) number of input chunks for BM25 retrieval needs to be changed from 60 to 200,
2) the chunk size is changed from 10 lines to 50 lines, which means totally 200x 50 lines of cross-file code will be considered in the BM25 retrieval.
3) number of chunks returned from plugin to server for prompting increased from 3 to 10.
> fix(amazonq): Update cross file context config

- .github/workflows/release.yml
- .github/workflows/release_notes.md
Problem:
- prerelease description only mentions Toolkit, not Q
- changelogs not shown in prereleases
Solution:
- update script
- Example: https://github.com/justinmk3/aws-toolkit-vscode/releases/tag/pre-smurf
> fix(ci): prerelease automation

- packages/core/src/shared/vscode/uriHandler.ts
- buildUri only grabs the extension id for the aws toolkit. This means if you only have the q extension installed you get prompted to install the aws toolkit when a uri is registered
- build the uri depending on the extension you are in
> fix: buildUri should be extension specific

- packages/core/scripts/build/generateIcons.ts
- packages/webpack.vue.config.js
Development on `Windows` for `aws-toolkit-vscode` is not working because inaccurate path
glob.sync requires posix style path. The code changes updates path.resolve to replace \\ to / from Windows to posix style.
> fix(build): invalid resource paths on Windows

- packages/toolkit/.changes/next-release/Test-5ceb1b76-ac6d-4c7d-9da7-8f90db51270f.json
We just need something so the CHANGELOG.md does not look weird and has no items for the Toolkit release.
We will want a better mechanism for this in the future.
> placeholder changelog item

- packages/amazonq/.changes/next-release/Bug Fix-58e09665-68a7-477e-b4a6-708cc77d7c54.json
- packages/amazonq/package.json
- packages/core/resources/css/amazonqTransformationHub.css
- packages/core/src/amazonq/webview/ui/tabs/generator.ts
- packages/core/src/amazonqGumby/activation.ts
- packages/core/src/amazonqGumby/chat/controller/controller.ts
- packages/core/src/amazonqGumby/telemetry/codeTransformTelemetry.ts
- packages/core/src/amazonqGumby/telemetry/codeTransformTelemetryState.ts
- packages/core/src/codewhisperer/commands/startTransformByQ.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/models/model.ts
- packages/core/src/codewhisperer/service/transformByQ/transformApiHandler.ts
- packages/core/src/codewhisperer/service/transformByQ/transformMavenHandler.ts
- packages/core/src/codewhisperer/service/transformByQ/transformationHubViewProvider.ts
- packages/core/src/codewhisperer/service/transformByQ/transformationResultsViewProvider.ts
- packages/core/src/test/codewhisperer/commands/transformByQ.test.ts
Several minor issues from GA launch: summary.md + icons not actually being saved when users accept changes, job history info not shown until the job terminates, and issues with white text / blue highlighting / grey text in transformation plan not visible with certain background colors.
Since the summary.md and icons are in their own new directories, ensure those are created before saving the files. Populate the job history tab once job ID is available and allow users to switch back and forth between plan progress and job history throughout the transformation. Use default text color which will adjust by background, make blue highlighting look better for dark backgrounds, use a lighter grey font color.
By submitting this pull request, I confirm that my contribution is made under the terms …
> fix(amazonq): ensure summary.md + icons saved, populate job history sooner, fix minor styling issues

- packages/core/src/amazonq/webview/ui/apps/featureDevChatConnector.ts
- packages/core/src/amazonq/webview/ui/main.ts
'Code changes summary' component when only 1 file is generated looks wrong. More info: [slack thread](https://amzn-aws.slack.com/archives/C02C9T4C1BQ/p1714147457229129)
The issue was fixed in 4.7.0 mynah-ui release
Adding `rootFolderTitle` to fixes the issue when displaying one file in 'Code changes summary' component 
`CODE_RESULT` is changed because it is going to be deprecated soon.
Tested:
Yes, manually
> fix(featureDev): 'Code changes summary' component when only 1 file was updated

- packages/amazonq/.changes/next-release/Bug Fix-06dc9320-3b6d-43d9-b811-c910852fdc2b.json
- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/amazonqFeatureDev/session/session.ts
- packages/core/src/amazonqFeatureDev/session/sessionState.ts
- packages/core/src/amazonqFeatureDev/types.ts
When the repo is larger that 200MB amazonqFeatureDev doesn't allow the customer to upload the repo and it prompts the customer to select a folder that could be used for the plan. This modification was not updating accordingly the config of the session state so it kept using the same root.
Update the config of the state on the fly and the session config to have the root folder correctly selected.
> fix: update session state config when modifying root folder

- scripts/package.ts
Use shell for execFileSync during extension packaging on Windows OS
A recent node update has introduced an issue with spawnSync (execFileSync) on Windows. An issue has been filed for this here https://github.com/nodejs/node/issues/52554.
This is affecting the packageExtension step for Windows OS on the latest Node versions (Node v20.12.2), giving the following error: 
```
> ts-node ./scripts/build/handlePackageJson
<ref *1> Error: spawnSync vsce ENOENT
at Object.spawnSync (node:internal/child_process:1124:20)
at spawnSync (node:child_process:876:24)
at Object.execFileSync (node:child_process:919:15)
at main (C:\Users\rbbarad\Desktop\vscode-toolkit\aws-toolkit-vscode-staging\scripts\package.ts:156:23)
at Object.<anonymous> (C:\Users\rbbarad\Desktop\vscode-toolkit\aws-toolkit-vscode-staging\ …
```
> fix(build): "npm run package" fails on Windows

- packages/amazonq/.changes/next-release/Feature-98fc029d-ac6f-43c6-b168-fb37bb077c14.json
- packages/amazonq/.changes/next-release/Feature-b7c62308-5e6e-4aeb-9dc8-ec8a5137dfb7.json
- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- packages/core/src/codewhisperer/service/diagnosticsProvider.ts
- packages/core/src/codewhisperer/service/securityScanHandler.ts
- packages/core/src/codewhisperer/util/zipUtil.ts
- packages/core/src/shared/filesystemUtilities.ts
- packages/core/src/test/codewhisperer/commands/basicCommands.test.ts
- packages/core/src/test/codewhisperer/service/securityScanHandler.test.ts
- packages/core/src/test/codewhisperer/util/zipUtil.test.ts
- packages/core/src/testE2E/codewhisperer/securityScan.test.ts
Security scans don't work for multi-root workspaces.
- Gather all open workspace folders for security scan payload instead of from the active file
- Since we no longer require the active file, remove the requirement of having a file open to run scans
> feat(amazonq): multi-root workspace support

- packages/core/src/login/webview/vue/login.vue
- packages/core/src/login/webview/vue/types.ts
Add Help link in Login Page.
- Introducing `BEM` naming convention for classes/CSS - https://getbem.com/.
- Use `?` for icon.
- Record Telemetry data when a user clicks the help link.
> feat(login): add help link

- packages/core/src/amazonq/webview/ui/quickActions/generator.ts
- packages/core/src/amazonq/webview/ui/tabs/generator.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
Updated placeholder message for feature dev in planning phase which was misleading previously due to "Briefly" in message.
Updated placeholder message for feature dev in planning phase to new UX message
> fix(featureDev): placeholder message

- packages/amazonq/.changes/next-release/Bug Fix-1a8a24b4-8845-4955-84a5-895eaed1194e.json
- packages/core/src/codewhispererChat/editor/context/file/importReader.ts
- packages/core/src/codewhispererChat/editor/context/focusArea/focusAreaExtractor.ts
Q chat will hang when the current opened file is ts/js and the syntax of the ts/js file is broken. See https://github.com/aws/aws-toolkit-vscode/pull/4876/files
- https://github.com/aws/aws-toolkit-vscode/issues/4935
- https://github.com/aws/aws-toolkit-vscode/issues/4810
Temporarily disable FQN extraction in Ts/Js files. 
> fix(amazonq): chat may hang in ts/js files

- packages/amazonq/.changes/next-release/Feature-5bbe5e13-b015-4b01-88a5-14648ba9a35d.json
- packages/core/src/auth/auth.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/codewhispererChat/editor/codelens.ts
- packages/core/src/test/codewhispererChat/editor/codelens.test.ts
> feate(amazonq): only display open chat codelens if authenticated

- packages/amazonq/.changes/next-release/Bug Fix-f01dcb01-94da-48a5-a986-e2c323622411.json
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/test/codewhisperer/util/crossFileContextUtil.test.ts
https://github.com/aws/aws-toolkit-vscode/pull/4922 may make completion fail if user opened too many tabs. The service side changes are not ready in prod yet.
> Revert "fix(amazonq): update cross file context config"

- packages/toolkit/.vscode/tasks.json
- packages/toolkit/scripts/build/handlePackageJson.ts
With the recent addition for the null extension fix in debug mode, we ran the hack during actual packaging of the AWS Toolkit extension. This hack caused the vsix to not work
Only run the hack during development. We did this by adding a flag to the handlePackageJson script to do the hack if the '--development' flag is given.
> fix: copyPackageJson script development mode

- packages/amazonq/.vscode/launch.json
- packages/amazonq/.vscode/tasks.json
- packages/amazonq/package.json
- packages/amazonq/src/extensionWeb.ts
- packages/amazonq/webpack.config.js
- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/toolkit/.vscode/tasks.json
- packages/toolkit/webpack.config.js
Amazon Q is not fully working in web, but this gets the Debug setup working so we can start developing
> web: get Amazon Q debug mode running

- packages/core/src/login/webview/vue/login.vue
- packages/core/src/login/webview/vue/selectableItem.vue
Icons are not displayed on for existing connections.
- Use `type` to render icons 
- Discuss a better way to differentiate between SSO and IAM Login in Frontend.
> fix(amazonq): update icons for Auth on Login Page

- packages/amazonq/.changes/next-release/Feature-13e24999-a2c9-4636-9ca8-d79b2ae78ca6.json
- packages/core/src/login/webview/vue/login.vue
- packages/core/src/login/webview/vue/selectableItem.vue
- packages/toolkit/.changes/next-release/Feature-2ac7c80a-b285-47a8-a512-7d10fd78d5ac.json
- Use tab/shift+tab to navigate the login.
- Press enter on start url field to shortcut continue (if the form is valid).
- Press enter on any of the IAM credential fields to continue (if the form is valid).
- Autofocus the start url field.
- Autofocus IAM profile name field.
https://github.com/aws/aws-toolkit-vscode/assets/149123719/4eb2fa77-55a1-4dba-bcac-7a03b7cf763a
TODO:
- Should we allow enter key to act as the continue button for selecting the auth options as well?
> feat(auth): navigate login page with keyboard

- packages/amazonq/.changes/next-release/Bug Fix-99765db0-02f5-421b-8188-f85f020f4763.json
- packages/core/src/amazonq/webview/ui/apps/gumbyChatConnector.ts
- packages/core/src/amazonqGumby/chat/controller/controller.ts
- packages/core/src/amazonqGumby/chat/controller/messenger/messenger.ts
Messages get lost in the code path where customers do not need to provide a JAVA_HOME.
This leads to missing chat bubbles for 
1. Building your project
2. I was able to build your project
3. I am starting to transform your code
Issue was due to typo when translating  `tabId` to `tabID`.
Search in the code shows that `tabID` is 10x more common than `tabId` so aligning Q Code Transform to this format.
After aligning the usages the missing messages are shown again and are animated where required.
1.  When JAVA_HOME set correctly from the start, then `I'm building your project ...` text does not show
2. When job completes, then nothing indicates it completed in the chat.
> Fix bug where messages to chat got lost.

- packages/core/src/auth/auth.ts
- packages/core/src/auth/secondaryAuth.ts
- packages/core/src/auth/utils.ts
- packages/core/src/codecatalyst/auth.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/login/webview/vue/amazonq/backend_amazonq.ts
- packages/core/src/login/webview/vue/toolkit/backend_toolkit.ts
- packages/core/src/test/credentials/auth.test.ts
Applies to both IdC and BuilderID, Amazon Q and Toolkit.
- Don't request AWS scopes if we are signing into Amazon Q
- Request AWS scopes for explorer sign in. Request AWS + CodeCatalyst scopes for CC sign in.
- Request scope difference if re-using a connection. Cancelling or otherwise failing to get the new scopes does NOT invalidate the connection.
- Updating a connection profile now no longer invalidates the connection. I couldn't find a use for it anymore.
- Works via login page AND quickpick menu
> feat(auth): request necessary scopes only

- packages/toolkit/scripts/build/handlePackageJson.ts
For some reason this separate fix caused debugging breakpoints to no be able to be registered.
Disabling this separate fix for now until we can determine why.
> fix: debugging breakpoints not working

- packages/amazonq/.changes/next-release/Bug Fix-7d44c921-beb1-42c5-9a6c-35efc4994d4d.json
- packages/core/src/codewhisperer/util/runtimeLanguageContext.ts
- packages/core/src/codewhisperer/util/zipUtil.ts
Projects with terraform files fail with `Improperly formed request` error. This is happening due to `tf` incorrectly mapped to `hcl`.
The reverse map lookup function `getLanguageFromFileExtension` is unreliable because there could be duplicate values. Use `getLanguageContext` instead.
> fix(amazonq): tf scans mapped to wrong language

- packages/core/src/codecatalyst/auth.ts
- packages/core/src/login/webview/vue/amazonq/backend_amazonq.ts
- packages/core/src/login/webview/vue/login.vue
- packages/core/src/login/webview/vue/toolkit/backend_toolkit.ts
- If the user enters start url and region of an already existing connection that was displayed, we will just proceed with re-using that connection.
- If the user enters start url but region differs from what exists, we will display the error.
Other misc fixes:
- fix(toolkit): return to explorer if login page is exited
- fix(codecatalyst): use default scopes (includes aws account scopes) for sign in
> fix(auth): re-use existing connections if provided manually

- packages/core/src/auth/sso/cache.ts
- packages/core/src/auth/sso/clients.ts
- packages/core/src/auth/sso/model.ts
- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/core/src/test/credentials/sso/cache.test.ts
- packages/core/src/test/credentials/sso/ssoAccessTokenProvider.test.ts
- Also adds startUrl to the registration file.
Problem: We only index client registrations files on region, scopes. IdC and builder ID are not distinguishable at the region + scopes level. This means that we can cache to the same registration file if the user tries IdC or builder Id. Now that we have moved to a new auth flow we no longer control opening the start URL, it is provided by the registration. If the registration is shared between IdC and builder ID, whatever one is accessed first will have its start URL saved to the cache.
Solution: Add start url to the hash key. This will prevent IdC and buidler ID logins matching to the same registration and routing to the same start url.
Steps to reproduce without this:
1. Try to log into builder ID or IdC
2. Don't fully sign in, cancel and …
> fix(auth): use startUrl for cache key

- packages/core/src/auth/activation.ts
- packages/core/src/auth/sso/server.ts
- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/core/src/extensionShared.ts
- packages/core/src/test/credentials/sso/server.test.ts
When users finish accepting scopes in the browser, they are brought to a custom "success" page. Additionally we use the URI Handler to then redirect them back to the IDE.
The issue is that the user is being redirected from the local server address which includes a port number. Since this port number is dynamic there will always be an "allow" prompt in the browser, instead of seamlessly taking them back to the IDE.
For now we will disable the URI Handler redirect and add it back in if the vscode:// uri becomes allowed to use as a redirect URI instead
> auth: do not use URI Handler in Auth PKCE flow

- packages/core/src/codewhisperer/activation.ts
Auto-scans are triggered even if auth connection is expired.
Use `isConnectionValid()` instead of `isConnected()`
> fix(amazonq): prevent auto-scan if connection expired

- packages/amazonq/package.json
- packages/core/package.nls.json
- Should fix nls warnings.
- Amazon Q is not supported in cloud9 at this time.
- No need for cn translations, there is nothing to change about it for Amazon Q.
> chore: remove cn and cloud9 items from q contributes

- packages/core/src/codecatalyst/auth.ts
- packages/toolkit/.changes/next-release/Bug Fix-b9005bc6-20e0-48f3-a67a-ab23ee2cf62c.json
There is some race condition that will display an onboarding node when re-using a connection from amazon Q, even if the connection is already onboarded. This occurs even if we updating the onboarded state after adding a new connection.
Update the onboarded state in the connection change callback directly. This should fire before updating the tree nodes, eliminating the race condition.
> fix(codecatalyst): don't display onboard node when using existing connection

- packages/amazonq/src/extensionShared.ts
This function does not accept a 4th arg anymore, but somehow the previous PR (#4987) did not fail CI.
> fix: remove unused arg

- packages/core/src/codewhisperer/activation.ts
Auto scans are triggered even if no workspace is found, for example creating Untitled file but not saving it, causing "No workspace found" errors
- Don't run a scan if `getWorkspaceFolder(uri)` is undefined
- Refactor condition
> fix(amazonq): avoid auto scan if no workspace found

- packages/core/src/codewhisperer/commands/basicCommands.ts
Wrong command is used or missed during merge
Replace `aws.codeWhisperer.refreshStatusBar` with `aws.amazonq.refreshStatusBar`
> fix(amazonq): update refresh status bar command

- packages/core/src/auth/auth.ts
When a Dev Env is spun up, the AWS Toolkit extension automatically creates an SSO profile in the Dev Env using the the sso session metadata in the ~/.aws/config file.
In the scenario the ~/.aws/config file contained the session for a non-builder id session (IdC),  the SSO profile created would be incorrect due to the startUrl and Region being reversed with eachother when the SSO profile was created.
This led to an invalid SSO profile, so any attempts to reauthenticate would fail.
correctly create the SSO profile by swapping the args in the method call.
> codecatalyst: fix invalid SSO profile in Dev Env

- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/messenger/messenger.ts
- packages/core/src/amazonqFeatureDev/session/session.ts
Even with the conversation id in the info logs, it could be cumbersome for a customer to get it. From UX feedback it was proposed to add the conversation on the error messages to be more specific and direct, and make the sharing of the conversation Id to customer support more convenient.
if the session has a conversation id, error messages will show the id with an accompanying text.
How the message will look:
> feat: add conversation id on error messages in amazonqFeatureDev

- packages/core/src/auth/activation.ts
- packages/core/src/auth/ui/vue/show.ts
- packages/core/src/codecatalyst/activation.ts
- packages/core/src/codecatalyst/commands.ts
- packages/core/src/codecatalyst/devEnv.ts
- packages/core/src/codecatalyst/explorer.ts
- packages/core/src/login/command.ts
- packages/core/src/shared/clients/devenvClient.ts
- packages/core/src/test/shared/clients/devenvClient.test.ts
We only tried to start the activity heartbeat on extension startup. So if
that failed due to something like an invalid connection, the heartbeat mechanism
would not start
- Try and start the heartbeat mechanism when the CC connection changes as well.
But if it is already running then we just skip it.
- Also added better logs to help debug this issue. The user should see `codecatalyst: DevEnvActivity: heartbeat sent at ...` in the logs, which indicates we called the Dev Env `/activity` api
> devEnv: Fix Dev Env timeout + logs

- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/test/codewhisperer/commands/basicCommands.test.ts
When selecting the "Fix" option inside the hover component, the hover doesn't go away or update. It's possible to click "Fix" multiple times even after the fix has already been applied, resulting in errors being reported.
Temporary solution is to keep track of which findingIds have been fixed and exiting early.
> fix(amazonq): avoid apply fix if already applied

- packages/core/src/codewhisperer/service/transformByQ/transformApiHandler.ts
This is a minor change to help customer troubleshoot issues related to file upload.
Log temporary file path and file size to be uploaded within IDE log. 
> Amazon Q Code Transform: Improve UploadZip logging

- package-lock.json
- packages/core/package.json
- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/test/amazonqFeatureDev/controllers/chat/controller.test.ts
There is no current metric tracking the usage of this UI feature form /dev which allows customer to modify root source folder. This will hopefully help us calculate any impact if this feature gets broken in the future or also have an insight of the usage.
send the modifySourceFolder when customer clicks the button to do so on the chat.
> telemetry(amazonq): modifySourceFolder event

- packages/core/src/amazonq/auth/controller.ts
- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/login/webview/vue/amazonq/backend_amazonq.ts
- packages/core/src/test/codewhisperer/util/authUtil.test.ts
Problem: Users can keep an old 3 scope connection if they continue to reauth with the notification once auth expires.
Solution: Any call to the amazon q's reauth function enforces 5 scopes, which will fix the reauth notification.
- Does NOT update the case where user reauths an amazon q connection via toolkit quickpick. That is more difficult.
> fix(auth): enforce 5 scopes when reauthing amazon q

- packages/core/src/auth/sso/server.ts
- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/core/src/login/webview/commonAuthViewProvider.ts
- packages/core/src/login/webview/vue/backend.ts
- packages/core/src/login/webview/vue/login.vue
- packages/core/src/test/credentials/sso/server.test.ts
Clicking anything other than 'open' in the VSC redirect url modal for the auth page would result in cancelling the auth attempt.
Do not expect a specific response from the url modal. Allow the auth flow to continue even if the user hits 'Cancel' or 'Copy'. To cancel the auth flow, the user should click 'Cancel' in the login ui OR leave the login ui.
> fix(auth): allow flow to continue if users copy url

- packages/core/src/codewhisperer/service/diagnosticsProvider.ts
Diagnostics are being incorrectly removed if there are multiple of the same type in the same file.
Update filter condition to remove diagnostic.
> fix(amazonq): update filter condition to remove diagnostic

- packages/core/src/codewhisperer/service/diagnosticsProvider.ts
Diagnostics from other sources are being duplicated
Only update diagnostics from Amazon Q
> fix(amazonq): duplicate diagnostics from other sources

- packages/core/src/codecatalyst/auth.ts
This reverts commit 974b1881e25171d80ebe3b8beaedd0f65be60245.
It is causing a large number of API calls to the codecatalyst service due to a circular dependency issue.
> Revert "fix(codecatalyst): don't display onboard node when using existing connection (#4988)

- package-lock.json
- packages/amazonq/.changes/next-release/Bug Fix-7c590127-172d-4803-8810-37745c4d516a.json
- packages/amazonq/.changes/next-release/Bug Fix-86b9e6a2-2d86-4be5-b362-93eb5f96568f.json
- packages/amazonq/.changes/next-release/Bug Fix-b8c7f55f-2986-48a9-91e7-cf143faf51fc.json
- packages/core/package.json
This PR includes fixes for Q Chat panel related problems: Autofocus to prompt input field, unexpected `<br/>` tags inside code blocks, prompt input field maxLength is not working and middle mouse clicks to links are not behaving as expected.
- When Q panel opens, it doesn't autofocus to prompt input field
- Inside chat body, if there is a code block inside a list item it shows `<br/>` tags
- Prompt input field in Q Chat tabs doesn't stop after it reaches to the given maxLength
- Links are not behaving as expected for middle mouse clicks inside a chat item.
- Added autofocus to prompt field when the panel opens or there is a new tab.
- Removed break generation for list items (which is the supposed way from markedjs and github's own markdown styling)
- Prompt input `maxLength` value was …
> fix(amazonq): Autofocus to prompt field when Q panel is open

- packages/amazonq/src/auth/util.ts
- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/codewhisperer/service/inlineCompletionService.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/login/webview/vue/amazonq/backend_amazonq.ts
- packages/core/src/login/webview/vue/login.vue
- packages/core/src/login/webview/vue/reauthenticate.vue
- packages/core/src/login/webview/vue/types.ts
- packages/core/src/test/codewhisperer/service/inlineCompletionService.test.ts
- packages/core/src/test/techdebt.test.ts
Continuation of https://github.com/aws/aws-toolkit-vscode/pull/5026
Changes:
- Force the flow by focusing the amazon Q panel specifically for users with a 3 scope connection.
- Additional commit to turn the status bar item red when not connected.
> Amazon Q 3 scopes to 5 scopes migration

- packages/core/src/login/webview/vue/amazonq/backend_amazonq.ts
- packages/core/src/login/webview/vue/backend.ts
- packages/core/src/login/webview/vue/login.vue
- packages/core/src/login/webview/vue/toolkit/backend_toolkit.ts
- packages/core/src/shared/regions/regionProvider.ts
- packages/core/src/shared/telemetry/telemetryService.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/shared/ui/common/regionSubmenu.ts
- packages/core/src/test/shared/regions/regionProvider.test.ts
Problem: Some telemetry (auth_addConnection) is using a 'region' field instead of the built in 'awsRegion' field. This provides misleading results in telemetry, since 'awsRegion' is guessed based on toolkit usage.
Solution: Remove 'region' field and just use 'awsRegion'. Also, updating the 'awsRegion' guess function to account for amazon Q.
- Remove checking tree nodes from the region guess function, since it was unused functionality.
- If a region can't be determined, return undefined. It is up to the caller to define the default instead now.
> fix(telemetry): use awsRegion instead of region, update guess function

- packages/core/src/amazonqGumby/activation.ts
- packages/core/src/amazonqGumby/chat/controller/controller.ts
- packages/core/src/codewhisperer/service/transformByQ/transformProjectValidationHandler.ts
The `codeTransform_ProjectDetails` metric was calculated and emitted on plugin activation no matter if user used Q Code Transform or not. This has the following issues:
1. Minor slowdown when starting vscode (some scanning of project is done)
2. Telemetry for `codeTransform_ProjectDetails` differs from IntelliJ leading to metric being useless.
3. Duplicate code
4. As part of the scanning of the project we also emit `codeTransform_isDoubleClickedToTriggerInvalidProject` which (as name suggests only should be emitted on transform started)
This removes the project validation call from the activation so it's only calculated after customer actually starts the transform process. 
> Amazon Q Code Transform: Stop verifying project on plugin activation.

- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- packages/core/src/test/codewhisperer/commands/basicCommands.test.ts
- packages/core/src/test/codewhisperer/commands/startSecurityScan.test.ts
- packages/core/src/test/codewhisperer/service/securityIssueCodeActionProvider.test.ts
- packages/core/src/test/codewhisperer/service/securityIssueHoverProvider.test.ts
- packages/core/src/test/codewhisperer/service/securityIssueProvider.test.ts
There are uncovered lines for security scans.
Add tests to increase coverage for security scans.
> test(amazonq): increase test coverage

- packages/core/src/codewhisperer/util/runtimeLanguageContext.ts
- packages/core/src/codewhisperer/util/zipUtil.ts
Project scans are slow when calling `vscode.workspace.openTextDocument` on large projects.
Inverse the file extension map for faster lookup of file extension to language, to avoid calling `vscode.workspace.openTextDocument`
> fix(amazonq): reverse map file extension to language

- packages/core/src/amazonqGumby/chat/controller/controller.ts
SessionId remains the same for different transformation jobs while it should reset for different transformation jobs.
Call the preExisting `setSessionId()` which recalculates the hash before the introduction for Q Code Transform is written to chat. (this method was never called before, or its invocations must have been mistakenly removed)
> Reset sessionId when new project transformation is triggered.

- packages/core/src/codecatalyst/commands.ts
- packages/core/src/codecatalyst/uriHandlers.ts
- packages/core/src/codecatalyst/vue/create/backend.ts
- packages/core/src/shared/logger/activation.ts
- packages/core/src/test/codecatalyst/uriHandlers.test.ts
The codecatalyst commands:
"Open Dev Environment"
"Clone Repository"
fail if their menu forms are used AFTER the treenode forms.
1. click the "Open Dev Environment" tree node in the codecatalyst panel.
2. close the wizard.
3. in the codecatalyst panel, expand the "..." root menu and choose "Open CodeCatalyst Dev Environment"
4. it fails because the TreeNode from step (1) is passed as the first arg, which breaks `openDevEnv()`.
Follow the instructions from the `VsCodeCommandArg` docstring: https://github.com/aws/aws-toolkit-vscode/blob/4decdf6341a38c58db0e9f778ba57b5514434b0b/packages/core/src/shared/vscode/commands2.ts#L23-L41
Note that the bug does NOT occur if you use the "..." menu command FIRST. It seems like the TreeNode is stored as state on the `CommandResource`; is that actually …
> fix(codecatalyst): menu command fails after using tree node

- packages/core/src/login/webview/vue/base.css
- packages/core/src/login/webview/vue/login.vue
- packages/core/src/login/webview/vue/selectableItem.vue
Update font-sizes in Login Page for AWS Toolkits and Amazon Q
- Use CSS Variables
- Initially used `rem` though now using `var(--vscode-font-size)` for base font size. This way the extension's base fon't will be as set by user for their VSCode
- fixed colors for dark and light theme
| Dark Theme | Light Theme |
| --- | --- |
| ![Screenshot 2024-05-22 at 12 42 41 PM](https://github.com/aws/aws-toolkit-vscode/assets/371007/f93ffb6c-151a-4f1c-a454-90cfbfe2efc2) | ![Screenshot 2024-05-22 at 12 42 50 PM](https://github.com/aws/aws-toolkit-vscode/assets/371007/e8f2fcf8-8ff5-475c-842c-187078b91e12) |
| ![Screenshot 2024-05-22 at 12 43 02 PM](https://github.com/aws/aws-toolkit-vscode/assets/371007/6baa01fb-b2d8-47df-9512-3b1d9cd5ae52) | ![Screenshot 2024-05-22 at 12 43 …
> refactor(ux): add css variables for font-sizes

- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/test/codewhisperer/commands/basicCommands.test.ts
Consecutive patches usually result in error because the document changed after the first patch
Increase the fuzz factor for patches up to 4 differing lines
> fix(amazonq): increase fuzz factor for diff patch

- .eslintrc.js
- packages/core/src/awsexplorer/activationShared.ts
- packages/core/src/codewhisperer/ui/statusBarMenu.ts
- plugins/eslint-plugin-aws-toolkits/index.ts
- plugins/eslint-plugin-aws-toolkits/lib/rules/no-incorrect-once-usage.ts
- plugins/eslint-plugin-aws-toolkits/test/rules/no-incorrect-once-usage.test.ts
- plugins/eslint-plugin-aws-toolkits/test/testUtil.ts
Problem: `once()` can be used incorrectly such that code can be executed multiple times, even if it seems that that the developer just wanted it to run a single time.
Solution: Custom lint rule to try to catch these cases. It is not foolproof, but it should catch most issues.
> lint: catch incorrect usages of once(), fix current usages

- package-lock.json
- packages/amazonq/.changes/next-release/Bug Fix-17e8d1cc-e35e-45d3-9dfd-f03c818c197e.json
- packages/amazonq/CHANGELOG.md
- packages/core/package.json
- packages/core/src/amazonq/webview/ui/apps/featureDevChatConnector.ts
- packages/core/src/amazonq/webview/ui/connector.ts
- packages/core/src/amazonq/webview/ui/main.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/messenger/messenger.ts
- packages/core/src/amazonqFeatureDev/session/session.ts
- packages/core/src/amazonqFeatureDev/views/connector/connector.ts
when clicking on the X to reject change nothing happens
Fix was introduced to Mynah in 4.9.1 version.
On our side we needed to update mynah chat card update by messageId.
Tested:
> fix(featureDev): File Rejection stopped working

- packages/amazonq/.changes/next-release/Feature-0c3c8bb1-444a-4fd4-81d9-19059caad5db.json
- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/models/errors.ts
- packages/core/src/codewhisperer/service/securityScanHandler.ts
- packages/core/src/codewhisperer/util/zipUtil.ts
- packages/core/src/test/codewhisperer/commands/startSecurityScan.test.ts
- packages/core/src/test/codewhisperer/service/securityScanHandler.test.ts
- packages/core/src/test/codewhisperer/util/zipUtil.test.ts
Security scans should support scanning files outside of any workspace folder.
Include files outside of workspace folder in code artifact
> feat(amazonq): scan support for non-workspace files

- packages/core/src/login/webview/vue/toolkit/backend_toolkit.ts
- packages/core/src/test/login/webview/vue/backend.test.ts
- packages/core/src/test/login/webview/vue/backend_amazonq.test.ts
- packages/core/src/test/login/webview/vue/backend_toolkit.test.ts
Just some basic tests. We could use some more tests that cover the connection re-use functionality.
> chore(auth): add login tests

- packages/amazonq/.changes/next-release/Bug Fix-90ec7784-f6a2-45b4-a91e-955e01597277.json
- packages/core/src/codewhisperer/service/diagnosticsProvider.ts
- packages/core/src/codewhisperer/service/securityIssueProvider.ts
- packages/core/src/test/codewhisperer/service/diagnosticsProvider.test.ts
- packages/core/src/test/codewhisperer/service/securityIssueProvider.test.ts
1. Line numbers of suggested fixes can be out of sync if the document changes.
2. Line offset calculation is incorrect in some cases if the change event contains multiple `contentChanges`
3. Remove diagnostic method is not reliable
1. Add line offset to suggested fix code during document changes using regex replace
2. Handle all elements in `contentChanges` array instead of just the first one
3. Assign `findingId` to diagnostic and update remove diagnostic method
> fix(amazonq): offset fix line number on document change

- packages/core/package.json
The ec2 stop and reboot instance commands can be seen without dev mode being enabled on the user. 
Correct the typo on the lines 1157 and 1162 in the package.json file. Changed "whem" to "when"
> bug fix: fixed typo in package.json that prevented the proper use of certain ec2 instance related commands.

- packages/core/src/login/webview/vue/base.css
- packages/core/src/login/webview/vue/login.vue
- packages/core/src/login/webview/vue/reauthenticate.vue
Auth UI is vertically center aligned
- Update CSS to re-position the container.
| Screen | Dark Theme | Light Theme |
| -- | -- | -- |
| Monitor (Large Screen) | ![Screenshot 2024-05-28 at 1 45 59 PM](https://github.com/aws/aws-toolkit-vscode/assets/371007/6a2a9db1-e0a7-4a72-adbc-bc109220482b)  | ![Screenshot 2024-05-28 at 1 45 38 PM](https://github.com/aws/aws-toolkit-vscode/assets/371007/3064ef05-dcf2-4b50-821c-34c039f8e62b) |
| Laptop | <img width="368" alt="Screenshot 2024-05-28 at 1 48 32 PM" src="https://github.com/aws/aws-toolkit-vscode/assets/371007/f4998b6f-2930-4803-9bec-5f908013769b">  | <img width="369" alt="Screenshot 2024-05-28 at 1 48 52 PM" src="https://github.com/aws/aws-toolkit-vscode/assets/371007/ef3239f7-5509-4987-be1d-7109328a9a2b">   | …
> fix(login): update auth-ui position

- .eslintrc.js
- package-lock.json
- package.json
- packages/core/src/accessanalyzer/vue/iamPolicyChecks.ts
- packages/core/src/lambda/commands/createNewSamApp.ts
- plugins/eslint-plugin-aws-toolkits/index.ts
- plugins/eslint-plugin-aws-toolkits/lib/rules/no-string-exec-for-child-process.ts
- plugins/eslint-plugin-aws-toolkits/test/rules/no-string-exec-for-child-process.test.ts
- Add eslint rule to prevent insecure usage of child_process functions
- 3P package, security-node/detect-child-process
- Add custom lint rule to prevent usage of "string forms" of child_process functions, e.g. `exec`, `execSync`. Use `execFile`, `execFileSync` instead.
Additional commit:
- [fix: child_process lint rule violations typo in policy checks command](https://github.com/aws/aws-toolkit-vscode/pull/5074/commits/a6c56e2191654b49be46539ce304413c79e5edc1)
- Disallow `shell: true` ?
> lint: child_process

- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/toolkit/.changes/next-release/Bug Fix-e3e035eb-3cd6-478c-a0ab-1e0b54061b12.json
- Logging into the toolkit using the authorization grant flow in code server/openshift dev spaces does not fully work. This is because the authorization grant page is being served from the backend compute and the browser is unable to access it
- Disable the authorization grant flow when you are running in a web browser
- It was done this way rather than relying on vscode.env.remoteName because remoteName can change with different remote instances. e.g. openshift dev spaces assigns a remoteName that is unique to each workspace
- VSCode itself disables remote extension hosts and web workers for this flow: https://github.com/microsoft/vscode/blob/main/extensions/github-authentication/src/flows.ts#L210
By submitting this pull request, I confirm that my contribution is made under the terms of …
> fix: use device code auth when running in a web browser

- package-lock.json
- packages/amazonq/.changes/next-release/Bug Fix-9585bc97-bea1-4abe-8928-6c753e18047e.json
- packages/core/package.json
- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
The plan disappears after clicking generate Code
This is a _critical_ bug for featureDev.
How it was fixed:
Initially, 'ANSWER_STREAM' card is created (with a loading animation). When the plan content is ready, the card type is updated  to 'ANSWER'. This prevents the updateLastChatAnswer method from catching and updating the card, allowing the complete plan content to be displayed correctly.
What is being fixed:
- Plan is shown at all times
Note:
- File rejection is still in place
> fix(featureDev): The plan disappears after clicking generate Code

- packages/core/src/accessanalyzer/vue/iamPolicyChecks.ts
Problem: recent change to use `execFileSync` instead of `execSync` resulted in a new err message if the item to exec is not found. Example: `spawnSync cfn-policy-validator ENOENT`
Solution: update catching err message for the new flow.
> fix(policychecks): readable err message if dep not found

- buildspec/release/60publish.yml
- the lowest node version that can be used for open vsx is node 18. We currently use node 16 which fails the release process with `ovsx requires at least NodeJS version 18. Check your installed version with node --version.`
- use node 20
> release: update publish vsix node version

- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/messenger/messenger.ts
- packages/core/src/amazonqFeatureDev/userFacingText.ts
The log lines for helping the customer get its conversation ID where not homogeneous between the plan and code generation phase, as well as with the ui chat message.
Now all logs will have the same format `featureName Conversation ID: conversationId`. Note that Conversation ID text is now similar to the ui chat message.
> fix(/dev): conversation id log message is now homogeneous and similar to the customer facing text

- packages/amazonq/package.json
- packages/toolkit/package.json
Problem: Subprojects (not core/) are not compiled normally, and webpack uses `esbuild-loader`. This results in no typescript compilation checks during build and packaging.
Note: by design `esbuild-loader` does not offer this, see https://github.com/privatenumber/esbuild-loader?tab=readme-ov-file#type-checking
Solution: Add a type check to buildScripts.
I did not notice any significant slow down, but if this is noticed later, we can instead use this recommended dependency https://github.com/TypeStrong/fork-ts-checker-webpack-plugin
> ci: add compile checking to subprojects

- packages/amazonq/.changes/next-release/Feature-b82b73bc-9076-4cf3-8938-281f79de96a9.json
- packages/core/src/amazonq/webview/ui/apps/featureDevChatConnector.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/messenger/messenger.ts
- packages/core/src/amazonqFeatureDev/views/connector/connector.ts
feat(featureDev): add snapToTop prop for geneterated plan
when a WB response comes out, we don’t auto scroll all the way to the bottom or at all.
So once the Plan is generated the customer will see the the top of the plan instead of the end of it
> feat(featureDev): generated plan being shown from top

- packages/amazonq/package.json
Problem: arg should go to `npm run copyFiles` in `buildScripts`, but it isn't and hasn't been. Now with the addition it of `tsc -p ./ --noEmit` it is going to that instead and it's an unrecognized arg.
Solution: remove it
Not sure if the arg ever worked. We can revisit this if the feature is desirable.
> build: remove --vueHr flag

- packages/core/src/testInteg/globalSetup.test.ts
- In globalSetup we use activateExtension which relies on globals being registered under the hood (inside of the Timeout). If globals aren't registered before we get to that code then the toolkit immediately stops running. This is evident when you use the VSCode current file test launch configs. I _think_ the reason why this doesn't happen when running all the e2e/integ tests is because the glob pattern takes longer to find all the files to load into mocha, giving more time for the extension to activate before the tests are actually ran
- Just use vscode.extensions.getExtension directly though we technically lose the 60000 timeout. ~~In the worst case I think VSCode would just close anyways because that means the extension failed to activate~~. In the worst case the editor just stays …
> fix: race condition between globals registration and extension test activation

- docs/arch_develop.md
- no docs for non vue webviews
- add some basic docs
> docs: add non vue webviews documentation

- packages/amazonq/.changes/next-release/Feature-671df6a0-7485-4d2d-a010-a3e39ac126d4.json
- packages/core/src/codewhisperer/models/constants.ts
Increase Code Transform project upload limit from 1GB to 2GB
Increase Code Transform project upload limit from 1GB to 2GB
> Amazon Q Transform: increase project size limit to 2GB

- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/amazonqFeatureDev/session/session.ts
- packages/core/src/amazonqFeatureDev/session/sessionState.ts
Some of the featureDev telemetry events were missing the `credentialStartUrl` field.
Added the missing field to all the featureDev telemetry events that didn't already have it.
> feat(featureDev): Include credentialStartUrl in all featureDev telemetry events

- packages/amazonq/.changes/next-release/Bug Fix-ebf9c5eb-9b16-4e14-acd9-85323144b08d.json
- packages/core/src/amazonq/webview/ui/main.ts
Notes: 
File rejections **works** when using a multirepo at the moment, though it doesn't work inside of some packaging extensions, because special characters can be appended, eg this packaging emoji.
Example:
The file is hovered but cannot be rejected. This is [redacted] workspace.
When I tried with a "simple" multirepo it was working as expected.
When we processCodeResultMessage we use zipFilePath
When we are calling to updateFile state, eg(reject/accept) we use relativePath.
Using zipFilePath in both places fixed the issue:
> fix(featureDev): fix file rejection for multi-workspaces

- packages/amazonq/.changes/next-release/Feature-c669b6ba-84ae-4255-aa13-c1dd7b66e7ab.json
- packages/amazonq/package.json
- packages/core/package.nls.json
- packages/core/src/codecatalyst/commands.ts
- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/codewhisperer/commands/types.ts
- packages/core/src/codewhispererChat/commands/registerCommands.ts
- packages/core/src/shared/vscode/commands2.ts
- packages/core/src/test/shared/vscode/runCommand.test.ts
Add commands in Command Palette for Amazon Q to improve feature discoverability
Commands Added
- Amazon Q: Open Chat Panel
- Amazon Q: Open Code Reference Log
- Amazon Q: Select Customizations
- Amazon Q: Toggle Auto-Scans
- Amazon Q: Toggle Auto-Suggestions
- Amazon Q: Try inline suggestion example
- Amazon Q: Sign Out
TODO:
> feat(amazonq): add commands to command palette

- packages/core/src/codewhispererChat/editor/codelens.ts
- packages/core/src/test/codewhispererChat/editor/codelens.test.ts
- Default Case: New user installs Amazon Q and Chat is open with Tips.
- When a user closes the tip, the codelens is visible. This is because the `isAmazonQChatVisible` event is not triggered until explicit action by the user
- Set default value for `isAmazonQVisible` to `true`. 
- Now codelens will be only be visible when the user manually opens the chat window.
> fix(codelens): set AmazonQ chat to open by default

- packages/core/src/amazonqGumby/chat/controller/controller.ts
- packages/core/src/codewhisperer/commands/startTransformByQ.ts
`jobStartedCompleteFromPopupDialog` telemetry was supposed to signify one of the first events happening in the transform flow:
```
A validated job was started but we have not yet compiled using Maven.
```
However currently its emitted after `mvn clean install`, this is wrong. 
Move the `jobStartedCompleteFromPopupDialog` telemetry after the `prevalidation` is finished but before the `mvn clean install`.
> telemetry(Amazon Q Code Transform): move metric earlier in transformation flow

- .husky/pre-commit
- scripts/prepare.ts
Problem:
husky prints "install command is deprecated" during "npm install".
Solution:
Migrate as described in https://github.com/typicode/husky/releases/tag/v9.0.1
> fix(build): huksy "install command is deprecated"

- packages/core/package.nls.json
> fix(amazonq): rename menu title to Amazon Q

- packages/amazonq/src/extensionShared.ts
- packages/core/src/amazonq/activation.ts
- packages/core/src/auth/auth.ts
- packages/core/src/shared/utilities/vsCodeUtils.ts
- Prompt user to sign-in into Amazon Q if they close the chat and haven't logged in. Display the notification only once. 
- Prompt the user with help link if they close the chat and were still authenticating. 
Display a notification to the user prompting for Sign In int Amazon Q.
User will see the notification if both the following conditions are met (i.e AND condition)
- User has manually closed the Amazon Q Sidepanel (this is necessary because by default we assume the sidebar is open).
- User has never attempted auth (aka clicked on the final continue button that opened the browser either for builder id or for idc connection).
> feat(amazonq): display notification for sign in

- docs/arch_develop.md
- packages/amazonq/package.json
- packages/amazonq/src/extension.ts
- packages/amazonq/src/extensionCommon.ts
- packages/amazonq/src/extensionShared.ts
- packages/amazonq/src/extensionWeb.ts
- packages/core/package.json
- packages/core/src/amazonq/onboardingPage/walkthrough.ts
- packages/core/src/codewhisperer/service/classifierTrigger.ts
- packages/core/src/codewhisperer/ui/codeWhispererNodes.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/extension.ts
- packages/core/src/extensionCommon.ts
- packages/core/src/extensionWeb.ts
- packages/core/src/extensionWebShared.ts
- packages/core/src/shared/extensionGlobals.ts
- packages/core/src/shared/utilities/functionUtils.ts
- packages/core/src/shared/utilities/timeoutUtils.ts
With inline suggestions moved to the Q extension we need to get the Q extension working in Web mode, including the debug mode to run Web locally.
This PR is mainly refactors, see individual commits for each specific change.
The refactors to the code were so that Amazon Q can now be run in Web mode. This PR will have the following limitations:
- You can only use Builder ID to sign in
- It will not work in vscode.dev due to auth/cors limitations (temporary issue)
- You must run things locally with `Extension (web) (amazonq` in the Run + Debug menu
- Local storage is not setup, so your login session will not be remembered when testing.
The Timeout class was modified to support it in both Web and Node runtimes. The inline suggestion feature indirectly relied on this so this was necessary to …
> web: setup web mode for Q inline suggestions

- README.md
- scripts/package.ts
package task fails if commit id starts with zero.
ERROR  Invalid extension version '3.9.0-0238109'
semver [disallows](https://semver.org/#spec-item-9) leading zero for prerelease. This is why `git describe` always adds a "g" prefix, for example.
Prefix the prerelease string with "g", similar to `git describe`.
> fix(build): package task fails if commit id starts with zero

- packages/core/src/extension.ts
- packages/toolkit/.changes/next-release/Bug Fix-7a3ed468-dad2-4867-933b-1cfc101e99b9.json
Problem: Q installs whenever a past connection is detected. If users don't log out of that connection, then they will forever have Q auto-installed on startup even if they don't want it.
Solution: Only install once, then store to global state that we did.
- Cleanup the install code a bit
- Use the same global state key for dismissing the install q notification.
Fixes https://github.com/aws/aws-toolkit-vscode/issues/4898
> fix: only install Q once for previous users

- packages/amazonq/README.md
- packages/toolkit/README.md
- Reorder content.
- Removed link for `Try Amazon Q Free Tier` tag. 
> docs(amazonq): update marketplace documentation

- packages/core/src/test/codewhisperer/commands/transformByQ.test.ts
unreliable test:
1 failing
1) transformByQ
WHEN update job history called THEN returns details of last run job:
AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected ... Lines skipped
{
'abc-123': {
+     duration: '2 sec',
-     duration: '0 sec',
projectName: 'test-project',
...
status: 'COMPLETED'
}
}
{
"abc-123": {
-    "duration": "2 sec"
+    "duration": "0 sec"
"projectName": "test-project"
"startTime": "05/03/24, 11:35 AM"
"status": "COMPLETED"
}
at Context.<anonymous> (d:\a\aws-toolkit-vscode\aws-toolkit-vscode\packages\core\src\test\codewhisperer\commands\transformByQ.test.ts:182:16)
Use a narrower assertion. The important property is still tested, the other properties are not relevant for this test.
fix …
> fix: unreliable test "transformByQ WHEN update job history..."

- packages/core/src/login/webview/vue/login.vue
Users have to manually select one of the auth options for Login
In order to reduce the friction and one click, we pre-select the first option by default. 
**Note**
- In case of existing logins, we still select the default option as we are in process of separating out auth.
> fix(login): pre-select auth option for the user

- packages/amazonq/.changes/next-release/Bug Fix-17572ed1-4601-4554-9144-9eb5143bf0ff.json
- packages/amazonq/src/extensionCommon.ts
IDE restart will auto enable auto trigger.
Do not auto turn on auto trigger whenever IDE restarts.
Tested with local builds. 
> fix(amazonq): remember "Pause Auto-Suggestions" after IDE restart

- README.md
- docs/arch_develop.md
- packages/amazonq/.changes/next-release/Bug Fix-17572ed1-4601-4554-9144-9eb5143bf0ff.json
- packages/amazonq/README.md
- packages/amazonq/package.json
- packages/amazonq/src/extension.ts
- packages/amazonq/src/extensionCommon.ts
- packages/amazonq/src/extensionWeb.ts
- packages/core/package.json
- packages/core/src/amazonq/onboardingPage/walkthrough.ts
- packages/core/src/codewhisperer/service/classifierTrigger.ts
- packages/core/src/codewhisperer/ui/codeWhispererNodes.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/extension.ts
- packages/core/src/extensionCommon.ts
- packages/core/src/extensionWeb.ts
- packages/core/src/extensionWebShared.ts
- packages/core/src/login/webview/vue/login.vue
- packages/core/src/shared/extensionGlobals.ts
- packages/core/src/shared/utilities/functionUtils.ts
- packages/core/src/shared/utilities/timeoutUtils.ts
- packages/core/src/test/codewhisperer/commands/transformByQ.test.ts
- packages/toolkit/.changes/next-release/Bug Fix-7a3ed468-dad2-4867-933b-1cfc101e99b9.json
- packages/toolkit/README.md
- scripts/package.ts
**Note that this is going to branch feature/separate-sessions**
Initial work for splitting auth sessions between amazon q and toolkit extensions.
- Remove UI elements for selecting existing connections.
- Remove amazon q usage of the toolkit api.
- API published by toolkit is retained so it can be used by other extensions to get auth in the future.
> refactor(auth): remove connection sharing between extensions

- packages/core/src/auth/connection.ts
- packages/core/src/auth/secondaryAuth.ts
- packages/core/src/codewhisperer/util/authUtil.ts
**Session split commit**
Problem: Amazon Q will continue to use connections it already has. These connections may contain scopes from toolkit.
Solution: Reauth with only amazon q scopes once the connection expires.
> feat(amazonq): reauth enforces amazon q scopes only

- packages/core/src/shared/logger/activation.ts
- packages/core/src/shared/settings.ts
Problem:
Extension fails to start if the "aws.dev.logfile" setting returns nonsense.
`settings.getSection().get()` is a very thin wrapper around
`vscode.workspace.getConfiguration()`, so it doesn't have the type checking and
coercion of the `Settings` class.
Solution:
Check the type.
> fix(dev mode): startup fails on invalid dev.logfile

- packages/amazonq/.changes/next-release/Bug Fix-939bbbf1-39fb-4482-8f98-10cdca69ae2a.json
- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- VSC triggers `getDirSize()` function to calculate `codeScanProjectBytes` for telemetry for both `Auto-scans` and `Project scans`.
- Disable the `codeScanProjectBytes` calculation for `Auto-scans`: Since the `codeScanProjectBytes`
parameter is optional for `Auto-scans` and is affecting the performance, it makes sense to disable the calculation for this scenario. This will help improve the overall performance of the Auto-scans.
- Enable the `codeScanProjectBytes` calculation for `Project scans`: For `Project scans`, you should continue to calculate the `codeScanProjectBytes` using the `getDirSize()` function, as this information is likely valuable for the telemetry.
> Security scans: VSC triggers to calculate codeScanProjectBytes only for Project scans

- packages/core/src/codecatalyst/activation.ts
- packages/core/src/codecatalyst/devEnv.ts
- packages/core/src/shared/clients/devenvClient.ts
- packages/core/src/shared/settings.ts
- packages/core/src/shared/utilities/messages.ts
- packages/core/src/shared/utilities/timeoutUtils.ts
- packages/core/src/test/shared/clients/devenvClient.test.ts
- packages/core/src/testInteg/codecatalyst/devEnv.test.ts
- packages/toolkit/.changes/next-release/Bug Fix-ebea70a6-ac18-4394-a543-c9422ef5ccb7.json
Toolkit requires a connection / auth session token to send heartbeat activity: https://github.com/aws/aws-toolkit-vscode/blob/4512e2052ec29bed0b11184e606b3937daa99346/packages/core/src/codecatalyst/devEnv.ts#L73-L94 This means if the user is not connected, the dev env will time out.
- Always send heartbeat activity (except when we know that `inactivityTimeoutMinutes=0`).
- If `inactivityTimeoutMinutes` is unknown, assume it is 15 minutes.
> fix(codecatalyst): always send heartbeat activity

- packages/core/src/auth/auth.ts
- packages/core/src/auth/secondaryAuth.ts
- packages/core/src/codecatalyst/activation.ts
- packages/core/src/extension.ts
**Separate sessions commit**
If the Toolkit has a connection with Amazon Q scopes, it must be in use by Amazon Q. We will forget these in Toolkit's auth. They will remain on disk. This will log out Q + Toolkit auth connections in Toolkit only.
> [split sessions] feat(auth): forget about Amazon Q connections in toolkit

- packages/amazonq/package.json
- packages/core/src/amazonq/activation.ts
- packages/core/src/amazonq/onboardingPage/walkthrough.ts
Notes
- Make inline suggestion as the first item for walkthrough
- Do not redirect user to Try inline suggestion example
- Add CTA and directly open an example
- add example for security scan in walkthrough
```
{
Metadata: {
command: '_aws.amazonq.walkthrough.inlineSuggestionsExample',
duration: '76',
result: 'Succeeded',
awsAccount: 'not-set',
awsRegion: 'us-east-1'
},
Value: 1,
Unit: 'None',
Passive: true
}
```
https://github.com/aws/aws-toolkit-vscode/assets/371007/73007977-bfae-46f9-a854-593caed1f6c9
```
{
Metadata: {
command: '_aws.amazonq.walkthrough.securityScanExample',
duration: '26',
result: 'Succeeded',
awsAccount: 'not-set',
awsRegion: 'us-east-1'
},
Value: 1,
Unit: 'None',
Passive: true
}
```
https://github.com/aws/aws-toolkit-vscode/assets/371007/11d60503-24e4-4cb2-97df-44b90 …
> fix(amazonq): update walkthrough

- packages/amazonq/.changes/next-release/Feature-a74ecc5a-9493-40e1-8211-c197b905ac87.json
- packages/core/src/amazonqGumby/chat/controller/controller.ts
- packages/core/src/amazonqGumby/chat/controller/messenger/messenger.ts
- packages/core/src/amazonqGumby/chat/controller/messenger/messengerUtils.ts
- packages/core/src/amazonqGumby/errors.ts
- packages/core/src/codewhisperer/commands/startTransformByQ.ts
- packages/core/src/codewhisperer/models/model.ts
- packages/core/src/codewhisperer/service/transformByQ/transformApiHandler.ts
- packages/core/src/test/codewhisperer/commands/transformByQ.test.ts
This change enables customers to view the server-side build logs that are generated for a code transform after a project has been submitted. The build log will be downloaded locally, and the option is given to view it in the chat.
> Amazon Q Code Transform: Failure Build Log

- packages/amazonq/.changes/next-release/Bug Fix-6f801ee1-63c1-4688-aa74-40a67d3a9193.json
- packages/core/src/amazonq/webview/ui/quickActions/handler.ts
Steps to reproduce:
- Get the Latest Q plugin for VsCode
- Open the VsCode without opening any project or workspace
- Open Q, and type /dev
- In Dev chat tab, type sometinng and hit enter/Send button
- You'll see that `Generating your anwer...` response is still there even though there is an error message below that.
It should be fixed so that, if there is an error we don't show the loading message.
- The initial streaming loading message is unnecessary when users do `/dev <User prompt>`.
> fix(featureDev): stop showing spinner when there is error

- packages/core/src/codecatalyst/devEnv.ts
- packages/core/src/shared/clients/devenvClient.ts
- packages/core/src/shared/extensionUtilities.ts
- packages/core/src/test/shared/clients/devenvClient.test.ts
- packages/core/src/test/shared/extensionUtilities.test.ts
Problem:
UserActivity may fire when the extension writes to its own logfile.
Solution:
Special-case the `onDidOpenTextDocument` event.
> fix(codecatalyst): avoid self-triggered UserActivity

- packages/core/src/login/webview/vue/selectableItem.vue
Add ellipsis for Long text
| Before | After |
| -- | -- |
|  ![Screenshot 2024-06-13 at 11 54 53 AM](https://github.com/aws/aws-toolkit-vscode/assets/371007/3e1a10e2-441a-4e85-bdd9-e2f96dbd3ae2) | ![Screenshot 2024-06-13 at 11 52 52 AM](https://github.com/aws/aws-toolkit-vscode/assets/371007/31b7687b-3446-4f1e-b6fa-9df0b193beb6) |
> fix(amazonq): add ellipsis for long text in login

- packages/core/src/auth/sso/model.ts
- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/core/src/shared/settings.ts
- packages/core/src/shared/utilities/textUtilities.ts
- packages/core/src/shared/vscode/env.ts
- We currently can't auth on web mode. Device code doesn't work because of cors and we can't start a local server without remote compute
- Temporarily redirect to a (hopefully) unused port and send the code there. This unblocks testing web mode
> auth: add temporary auth for web mode

- packages/core/src/auth/auth.ts
- packages/core/src/auth/secondaryAuth.ts
- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/login/webview/vue/toolkit/backend_toolkit.ts
- packages/toolkit/src/api.ts
**Separate sessions commit**
- Add new API to Toolkit to "declare" and "undeclare" a connection. Unlike the other API methods, this will inform the toolkit of existing connections without accepting them into its auth environment. This allows it to use params from other connections, e.g. start url region. It does not persist. 
- Retain original API because it may be beneficial in the future for other extensions/use cases
- Change Amazon Q's usage of the API to declare instead of direct session sharing.
> [split sessions] feat(auth): update api for split sessions

- packages/core/src/auth/sso/cache.ts
- packages/core/src/auth/sso/clients.ts
- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/core/src/codewhisperer/client/codewhisperer.ts
- packages/core/src/shared/awsClientBuilder.ts
- packages/core/src/shared/clients/codewhispererChatClient.ts
- packages/core/src/shared/errors.ts
- packages/core/src/shared/logger/activation.ts
- packages/core/src/shared/sam/cli/samCliInvokerUtils.ts
- packages/core/src/shared/telemetry/spans.ts
- packages/core/src/shared/telemetry/telemetryService.ts
- packages/core/src/shared/telemetry/util.ts
- packages/core/src/test/credentials/sso/ssoAccessTokenProvider.test.ts
- packages/core/src/test/shared/defaultAwsClientBuilder.test.ts
- packages/core/src/test/shared/telemetry/util.test.ts
- packages/core/src/threatComposer/threatComposerEditorProvider.ts
missing user agent, clientid, requestid for failed OIDC and Amazon Q requests.
- set `customUserAgent` in the SSO and OIDC clients
- set `customUserAgent` in the `CodeWhispererStreaming` (Amazon Q) client
- set `requestId` and `reasonDesc` on all failed metrics
```
user-agent: aws-sdk-js/3.574.0 ua/2.0 os/darwin#23.5.0 lang/js md/nodejs#20.9.0 api/sso-oidc#3.574.0 AmazonQ-For-VSCode/testPluginVersion-Visual-Studio-Code/1.90.1-ClientId/96be923b-a00d-46d4-add1-c877abfcb01c
x-amz-user-agent: aws-sdk-js/3.574.0 AmazonQ-For-VSCode/testPluginVersion-Visual-Studio-Code/1.90.1-ClientId/96be923b-a00d-46d4-add1-c877abfcb01c
```
> fix(telemetry): set UserAgent in Q, OIDC/SSO requests

- packages/core/src/shared/errors.ts
Checking `err instanceof ServiceException` fails for `SSOOIDCServiceException` even though it subclasses @aws-sdk/smithy-client.ServiceException 😑 
```
2024-06-14 13:03:07.065 [debug] telemetry: aws_loginWithBrowser {
Metadata: {
id: 'codeWhispererConnectionExpired',
source: 'vscodeComponent',
action: 'connect',
parentMetric: 'toolkit_invokeAction',
isReAuth: 'true',
credentialStartUrl: 'https://view.awsapps.com/start',
duration: '25613',
result: 'Failed',
reason: 'InvalidRedirectUriException',
reasonDesc: 'Requested client type must use loopback interface for redirect',
requestId: '1aee48f3-1062-4efe-a761-b2079ae31ac9',
awsAccount: 'not-set',
awsRegion: 'us-east-1'
},
Value: 1,
Unit: 'None'
```
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> telemetry: set requestId field on failure

- packages/core/src/auth/sso/vue/index.html
- redirectUri used to be used to redirect back to vscode but we are no longer using that
- remove it
> fix: remove redirectUri since it's no longer needed

- packages/core/src/shared/errors.ts
- packages/core/src/shared/utilities/logAndShowUtils.ts
- packages/core/src/test/shared/errors.test.ts
- Useful error messages are sometimes not surfaced to the user.
- Some services such as OIDC supply the non-standard `error_description` SDK field on some errors. If it is present, it contains more useful information than the default `message` field. But our error handling does not surface this field.
- ref https://github.com/aws/aws-toolkit-jetbrains/commit/cc9ed87fa9391dd39ac05cbf99b4437112fa3d10
- Rewrite `findBestErrorInChain()` (renamed from `findPrioritizedAwsError`) to search the full "cause chain".
- Introduce `getErrorMsg()` and use it in `findBestErrorInChain()`.
> feat(errors): surface error_description

- packages/core/src/login/webview/vue/login.vue
Problem: We do not allow the SSO form to continue if the user tries putting in an IdC start url that already exists in the same extension. However, this check isn't in place for displaying connections from the other extension. This means users can duplicate the connection start url in the extension and caused undefined behavior.
Solution: Filter out existing connections from other extensions on what connections are in the current extension.
> [split sessions] fix(auth): login page displays connections that already exist

- package-lock.json
- packages/amazonq/.changes/next-release/Bug Fix-4745c9cd-5cbc-4765-89ea-4de83778e803.json
- packages/core/package.json
When the given path for a file starts with ./ it doesn't show the file actions and not triggering the file click. Now it uses the original file path check
It was fixed in the newest mynah release
Tested: yes, now files outside of src/ can be rejected
> fix(featureDev): file rejections for files outside of src/

- packages/core/src/login/webview/vue/selectableItem.vue
Display tooltips on login page during keyboard navigation
https://github.com/aws/aws-toolkit-vscode/assets/371007/481c6623-78ed-4030-a7ee-afc3edb76039
> feat(amazonq): display tooltips during keyboard navigation

- packages/core/src/codewhisperer/models/constants.ts
Security Scans timing out due to payload size limit.
**Security scans:** Increase in payload size limit from `500MB` to `1GB`.
> Security scans: Increase in payload size limit from 500MB to 1GB.

- packages/core/src/amazonqFeatureDev/client/codewhispererruntime-2022-11-11.json
- packages/core/src/amazonqFeatureDev/client/featureDev.ts
- packages/core/src/amazonqFeatureDev/session/session.ts
For testing ABTesting configuration and infrastructure, is needed to start sending telemetry events so RTS. This will create the basic implementation to track ABTests for featureDev.
Add the new event model to the service schema, Add a sendTelemetryEvent request when a conversation is created. 
> feat: add featureDevTelemetryEvent

- packages/core/src/auth/secondaryAuth.ts
- packages/core/src/codecatalyst/activation.ts
- packages/core/src/extension.ts
**Separate sessions commit**
Problem: We forget all connections without all codecatalyst scopes only (aws account + coca scopes). However, the stored credentials in dev environments do not have the account scopes, so we are forgetting it.
Solution: Check for Q scopes explicitly.
> fix(codecatalyst): dev env logged out on load

- packages/core/src/shared/errors.ts
- packages/core/src/test/shared/errors.test.ts
We were seeing an error in `aws_refreshCredentials` metric. This error was networking related when the user has setup a proxy in vscode, but they were not connected to it. Maybe they didn't connect to VPN.
We typically catch network errors during the SSO token refresh process so that the session does not become invalidated on it. We do not catch all errors, but will add them in incrementally as we see them in telemetry. This proxy error was not caught and caused sessions to become invalidated prematurely.
Treat this VSCode Proxy Error as a network error so that we ignore it during token refresh, keeping the users session valid.
> auth: ignore vscode proxy errors on token refresh

- package-lock.json
- packages/amazonq/.changes/next-release/Bug Fix-8d9d0ab6-a0f7-4622-b0d9-0cd12cc568b3.json
- packages/core/package.json
- `<span class='typewriter-part>...</span>` shows up in contents within list items.
- Chat card component reordering and update structure is broken sometimes depending on update type.
- Streaming content component wrapped out from the chat-item-card and builded as a separate component
- Typewriter animation injection removed from the markdown parsing process
- Typewriter animation injection added to node process state with a check if the node type is TEXT, then we're adding the animation wrapper.
[MynahUI 4.13.0](https://github.com/aws/mynah-ui/releases/tag/v4.13.0)
> fix(amazonq): Code blocks with typewriter text inside list items

- packages/core/src/codewhisperer/util/authUtil.ts
command sometimes shows an error during teardown:
Failed to run command: aws.amazonq.refreshConnectionCallback: Cannot
read properties of undefined (reading 'scopes')
There may be a race somewhere, when we update the connections list. To mitigate, handle undefined AwsConnection.
> fix(amazonq): "Failed to run: refreshConnectionCallback"

- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- packages/core/src/codewhisperer/models/errors.ts
- packages/core/src/codewhisperer/models/model.ts
- packages/core/src/codewhisperer/service/securityScanHandler.ts
- packages/core/src/test/codewhisperer/commands/startSecurityScan.test.ts
- Telemetry error messages are not consistent in VSC and JB
-  Improving telemetry error messages to keep consistent in both IDE's
> telemetry(amazonq security scan): set reasonDesc

- packages/core/src/test/globalSetup.test.ts
- Unit test setup is using activateExtension before globals is registered when running `extension tests (current file)`
- Instead of activateExtension just use vscode.extensions.getExtension directly
- Similiar problem was fixed in integ/e2e in https://github.com/aws/aws-toolkit-vscode/pull/5078
This is a seperate issue from: https://github.com/aws/aws-toolkit-vscode/pull/5154 where the problem is the tests won't run. This fix just makes it so that `extension tests (current file) work`
> fix: activateExtension is used before globals is registered

- packages/amazonq/.vscode/launch.json
- We didn't have the outFiles set in some q launch configs
- Set them so we can use breakpoints
> chore: Add core outFiles to amazon q launch configs

- packages/core/src/auth/sso/clients.ts
During API calls with the OIDC client the request would time out and we would get TimeoutError.
See if adding an explicit request timeout amount will avoid this. We'll need to observe telemetry to see if this
specific type of error goes down.
> auth: TimeoutError OIDC client fix attempt

- packages/toolkit/package.json
- packages/toolkit/scripts/build/handlePackageJson.ts
- scripts/package.ts
Because of the `npm run restorePackageJson` step, the `--feature separate-sessions` arg is not passed to `package.ts`:
npm run copyPackageJson && ts-node ../../scripts/package.ts && npm run restorePackageJson --feature separate-sessions
Thus the feature branch name is not in the toolkit artifact name. For example, the feature/separate-sessions branch artifacts are:
amazon-q-vscode-1.10.0-separate-sessions-g8a563a7.vsix
aws-toolkit-vscode-3.11.0-g8a563a7.vsix
Inline the `--restore` logic into `package.ts`. This is hacky, but should be temporary after we resolved IDE-12831 so that these hacks are no longer needed.
https://github.com/justinmk3/aws-toolkit-vscode/releases/tag/pre-smurf
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> fix(ci): feature branch name missing from toolkit artifact

- packages/amazonq/package.json
- packages/core/scripts/test/testE2E.ts
- workspace folder does not open when running testE2E for amazon q through command line
- open the workspace folder
> fix: pass workspace folder to amazon q e2e tests

- packages/core/src/amazonq/auth/model.ts
- packages/core/src/amazonq/webview/ui/tabs/constants.ts
- packages/core/src/amazonq/webview/ui/tabs/generator.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/messenger/constants.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/messenger/messenger.ts
- packages/core/src/amazonqGumby/chat/controller/messenger/messenger.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
The current implementation contains hardcoded static text within the `Messenger` class, leading to repetitive and unmanageable code. This makes it difficult to maintain and update error messages and placeholders across the application.
Refactor the `Messenger` class to use enums for error messages and placeholders. This approach centralizes the management of static text, improving code maintainability and readability. The changes include:
- Introduction of `ErrorMessages` and `Placeholders` enums.
- Replacement of hardcoded static text with corresponding enum values.
> [!TIP]
> As a follow up, it would be good to consolidate some of the repetitive nature of dispatcher stuff ex: `sendAuthNeededExceptionMessage` into a single utility class
By submitting this pull request, I confirm that my …
> cleanup: moved a bunch of static text into types

- package-lock.json
- packages/core/package.json
- packages/core/src/accessanalyzer/vue/constants.ts
- packages/core/src/accessanalyzer/vue/iamPolicyChecks.ts
- packages/core/src/accessanalyzer/vue/iamPolicyChecks.vue
IAM Access Analyzer recently released an update to custom policy checks adding support for public access and critical resources: https://aws.amazon.com/about-aws/whats-new/2024/06/aws-iam-access-analyzer-policy-checks/
This PR updates the policyCheck toolkits integration to support the updated checks.
PR for adding telemetry for IamPolicyChecks: https://github.com/aws/aws-toolkit-common/pull/735
PR for updating telemetry for updated checks: https://github.com/aws/aws-toolkit-common/pull/756
PR for release of the IamPolicyChecks feature in toolkits: https://github.com/aws/aws-toolkit-vscode/pull/5028
> feat(policyCheck): new/updated custom policy checks

- packages/amazonq/test/unit/codewhisperer/service/codewhisperer.test.ts
- packages/core/src/amazonqFeatureDev/client/codewhispererruntime-2022-11-11.json
- packages/core/src/amazonqFeatureDev/client/featureDev.ts
- packages/core/src/codewhisperer/client/codewhisperer.ts
- packages/core/src/codewhisperer/util/commonUtil.ts
- packages/core/src/codewhisperer/util/editorContext.ts
- packages/core/src/shared/index.ts
- packages/core/src/shared/telemetry/util.ts
User context and opt in/out telemetry options are needed for the sendTelemetryEvent activity to parse the event. This were missing from the initial implemention.
It is being added the above fields to the request. It has been tested locally sending these events to the server and checking for their correct processing.
> feat: update sendFeatureDevTelemetry to include user context and opt in/out telemetry options

- packages/core/src/test/credentials/auth.test.ts
Test constantly fails on "minimum vscode" CI job: https://github.com/aws/aws-toolkit-vscode/issues/5115
Auth
promptForConnection
reauthenticates a connection if the user selects an expired one:
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
assert_1.default.ok(!refreshedConnItem.description?.match(/expired/i))
-false
+true
at /codebuild/output/src3389505232/src/github.com/aws/aws-toolkit-vscode/packages/core/src/test/credentials/auth.test.ts:512:24
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async /codebuild/output/src3389505232/src/github.com/aws/aws-toolkit-vscode/packages/core/src/test/shared/vscode/window.ts:496:29
Skip the test on the "minimum vscode" CI job.
By submitting this …
> tests: skip promptForConnection on "min vscode" CI

- docs/arch_develop.md
- packages/core/src/test/shared/vscode/runCommand.test.ts
- packages/core/src/test/testRunner.ts
- Windows ci is no longer working after we moved amazonq tests to the
amazonq package
- Utilize upper case drive letters for getting the root in
amazonq/toolkit. That way imports will resolve correctly.
In multi root npm workspaces on windows it looks like imports into other npm workspace packages makes the loaded module id an uppercase drive letter in the node require cache.
E.g. when we import a file from core the module ids inside of amazonq/toolkits node require cache are something like:
- C:\${pathToWorkspace}\packages\core\myfile.js
However, internal workspace package imports are lower case drive letters. That means when core imports a module inside of core we see this as:
- c:\${pathToWorkspace}\packages\core\myfile.js
This can cause things like globals to be undefined, since tests …
> ci: fix windows global activation

- packages/core/src/shared/languageServer/languageModelCache.ts
- packages/core/src/stepFunctions/activation.ts
- packages/core/src/stepFunctions/asl/aslServer.ts
- packages/core/src/stepFunctions/asl/client.ts
- packages/core/src/testInteg/stepFunctions/init.test.ts
- packages/toolkit/.changes/next-release/Bug Fix-dc4f03d3-e539-47c0-8313-317069ad6592.json
- step function language server failed to activate
- remove globals from the language server
- Still investigating but it looks like something between version 2.20 and 3.0.0 broke the step functions language server activation. AFAICT the error occurs because the language server was starting in another process and that process doesn't have access to vscode which globals seems to be importing. It's not exactly clear why this is caused in 3.0.0 and not early though
> fix: step function language server activation

- packages/core/src/codewhisperer/commands/startTransformByQ.ts
- packages/core/src/feedback/vue/submitFeedback.ts
- packages/core/src/test/feedback/commands/submitFeedbackListener.test.ts
unreliable test:
submitFeedbackListener
submits feedback for Amazon Q, disposes, and handles errors:
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
assert.ok(postStub.calledOnceWithExactly({ comment: comment, sentiment: sentiment }))
-false
+true
at Context.<anonymous> (src/test/feedback/commands/submitFeedbackListener.test.ts:33:20)
This is because of a race: CodeTransform sets a global "jobId", which may be used by the feedback form, which causes unexpected results in the feedback tests.
Remove random CodeTransform special-case from `FeedbackWebview`.
> fix: unreliable test "submitFeedbackListener"

- packages/core/src/stepFunctions/activation.ts
- packages/toolkit/.changes/next-release/Bug Fix-9d578109-b17a-40e9-a116-8c738b19e727.json
Users who open vscode after previously editing an ASL document are not seeing error checking activate
- https://github.com/aws/aws-toolkit-vscode/issues/5163
- https://github.com/aws/aws-toolkit-vscode/issues/5110
This fixes that behaviour where users will now see error checking activate when re-opening vscode and editing an ASL document from a previous session
- I elected to keep the two new functions private as they only pertain to activation. Thus there are no unit tests with this particular change.
- I verified this fix by opening up a new vscode session from which I had previously been editing an ASL document. I've attached a video for proof.
- I wasn't sure if we can mock this behaviour somehow in integration tests or E2E tests so if anyone has any ideas or recommendations, I'm …
> StepFunctions LSP server activates when users re-open vscode with an ASL document from a previous editing session

- packages/amazonq/.changes/next-release/Bug Fix-b1dd8c2c-cc3d-4986-be5b-20be5ebc3925.json
- packages/core/src/amazonq/webview/ui/tabs/constants.ts
- packages/core/src/amazonqFeatureDev/app.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/messenger/constants.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/messenger/messenger.ts
- packages/core/src/amazonqFeatureDev/errors.ts
- packages/core/src/amazonqFeatureDev/session/session.ts
- packages/core/src/amazonqFeatureDev/session/sessionState.ts
- packages/core/src/amazonqFeatureDev/types.ts
- packages/core/src/amazonqFeatureDev/userFacingText.ts
- Currently we don't have granular error handling for some specific scenarios shown by the technical writer.
- This PR updates those messages.
- In addition:
- Refactor the use of simple strings to describe the "phases" and use enum instead
- Extract the error handling in controller state to a switch/case instead if/else
> feat(amazonqFeatureDev): improve Error messages 

- packages/amazonq/.changes/next-release/Bug Fix-82f3dfb6-c3d3-48e6-806f-ff006688d852.json
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/service/transformByQ/transformApiHandler.ts
Minor adjustment to UI messages, including linking error messages to new troubleshooting document sections, removing unwanted UI messages, and minor renaming.
> Amazon Q Code Transform: Link UI messages to troubleshooting document sections

- packages/core/src/amazonqGumby/activation.ts
There was a bug that happened when VSCode is opened without having first been signed into `Amazon Q` and the user attempts a code transformation. The Transformation Hub window would open, but would not update, and Code Transform would appear to hang.
There is some initialization code that registers commands that other parts of Gumby uses to update the Transformation Hub, but this code was locked behind an auth check; if it fails, the commands are simply never registered, even if the user signs in again later.
This portion of the code is not necessary to lock behind an auth check (it doesn't save memory or make anything run faster to not have it run), so the check has been removed.
Testing:
1. User opens VSCode without already being signed in; the user signs in and then transforms a …
> fix(gumby): Do not check auth when initializing transformation hub UX

- package-lock.json
- package.json
- packages/core/src/amazonqFeatureDev/client/featureDev.ts
- packages/core/src/codewhisperer/models/model.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/shared/errors.ts
- packages/core/src/shared/telemetry/spans.ts
- packages/core/src/test/shared/errors.test.ts
- packages/core/src/test/shared/telemetry/spans.test.ts
- packages/core/src/test/shared/vscode/runCommand.test.ts
`telemetry.run()` and `runCommand` do not set some "standard" fields on failure.
Update `telemetry.run()` and `runCommand`.
> telemetry: set more MetricBase fields

- packages/core/src/codecatalyst/devEnv.ts
- packages/core/src/testInteg/codecatalyst/devEnv.test.ts
- packages/toolkit/.changes/next-release/Feature-56b5e5bc-9891-421f-a352-bcc24f257e94.json
- The "progress" message tests are flaky because of the complex logic, and sometimes fail:
```
1) InactivityMessages
shows expected messages 5 minutes before shutdown on a 60 minute inactivity timeout:
AssertionError [ERR_ASSERTION]: Expected 3 messages, but got 2
at assertMessagesShown (src/testInteg/codecatalyst/devEnv.test.ts:182:20)
at async Context.<anonymous> (src/testInteg/codecatalyst/devEnv.test.ts:85:9)
```
- Toolkit has complex logic for showing a "progress" message when the codecatalyst dev env timeout is approaching, followed by different logic for showing the "final" message. This isn't worth the complexity because if the user sees the message, clicking it is zero-cost and will happen immediately, otherwise the user isn't active and won't see any of the messages anyway.
- …
> fix(codecatalyst): simplify InactivityMessage

- packages/core/src/codewhisperer/tracker/codewhispererTracker.ts
- packages/core/src/shared/utilities/timeoutUtils.ts
- packages/core/src/test/shared/utilities/timeoutUtils.test.ts
- packages/core/src/testWeb/shared/utilities/timeoutUtils.test.ts
When in Web mode, we were using the Node.js Timeout `refresh()` method. This does not exist
in web mode.
- Update the use with our environment agnostic `Timeout` class, which works in web or node.
- Copy the timeout unit tests from our regular `test/` in to the web mode tests. Fixed a minor bug when refreshing in web mode, and now they all pass without any modifications to the tests.
> web: minor Timer/Timeout change for CW

- packages/amazonq/test/unit/codewhisperer/service/codewhisperer.test.ts
- packages/amazonq/test/unit/codewhisperer/tracker/codewhispererTracker.test.ts
- packages/amazonq/test/unit/codewhisperer/util/editorContext.test.ts
- packages/core/src/shared/telemetry/activation.ts
- packages/core/src/shared/telemetry/telemetryService.ts
- packages/core/src/test/globalSetup.test.ts
- packages/core/src/test/shared/telemetry/telemetryService.test.ts
- packages/core/src/testInteg/schema/schema.test.ts
- Emits 1 final metric on opt-out that will let us know the user opted out.
- Also, on opt out it will emit any telemetry that was previously recorded and not sent.
> feat(telemetry): emit on opt-out and opt-in 

- packages/toolkit/package.json
- packages/toolkit/scripts/build/handlePackageJson.ts
- When debugging toolkit the tasks rely on the restorePackageJson script that was removed in https://github.com/aws/aws-toolkit-vscode/pull/5222
- Re-add the restorePackageJson script
> fix: restorePackageJson failure after stopping toolkit extension

- buildspec/shared/common.sh
[3422:0705/221403.718606:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3422:0705/221403.916070:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[3449:0705/221404.002987:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
[3519:0705/221404.270770:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
- These lines are related to `xvfb` and are irrelevant. See https://github.com/cypress-io/cypress/issues/19299
- Drop the lines when printing output in Linux CI (AWS CodeBuild). …
> fix(ci): noisy lines in Linux CI output

- packages/core/src/codewhisperer/service/transformByQ/humanInTheLoopManager.ts
- packages/core/src/codewhisperer/util/zipUtil.ts
- packages/core/src/shared/errors.ts
- packages/core/src/shared/filesystemUtilities.ts
- packages/core/src/shared/systemUtilities.ts
- packages/core/src/shared/vscode/env.ts
- packages/core/src/srcShared/fs.ts
- packages/core/src/test/shared/systemUtilities.test.ts
- packages/core/src/test/srcShared/fs.test.ts
Note: This commit is part of a series.
- Our `fs.ts` module does not have the advanced error-handling present in our `SystemUtilities` module.
- `fsCommon.delete()` defaults to `recursive:true`, which means directories may be unintentionally deleted when a file was expected, and related errors are not surfaced.
- Merge the features of `SystemUtilities` into `fs.ts`.
- Migrate `SystemUtilities.delete()`.
- Change `fsCommon.delete()` to default to `recursive:false`.
- Update callers to explicitly pass `recursive:true`, where appropriate.
> fix(fs): FileSystemCommon lacks error handling

- packages/core/src/shared/schemas.ts
- packages/core/src/shared/systemUtilities.ts
- packages/core/src/shared/utilities/cacheUtils.ts
- packages/core/src/srcShared/fs.ts
- packages/core/src/test/shared/systemUtilities.test.ts
- packages/core/src/test/srcShared/fs.test.ts
Note: This commit is part of a series. Continued from https://github.com/aws/aws-toolkit-vscode/pull/5267
- Error handling is inconsistent.
- `SystemUtilities` is redundant with `fs.ts`, and is not web-compatible.
- Merge the features of `SystemUtilities` into `fs.ts`.
- Migrate tests.
> refactor(fs): FileSystem error handling, eliminate SystemUtilities

- packages/amazonq/test/e2e/amazonq/framework/jsdomInjector.ts
- We are observing "ReferenceError: Node is not defined" in the e2e test logs
- Add Node into the global object
> fix: ReferenceError: Node is not defined in e2e tests

- packages/amazonq/src/extensionCommon.ts
- packages/core/src/amazonqGumby/chat/controller/controller.ts
- packages/core/src/extensionCommon.ts
- packages/core/src/shared/errors.ts
- packages/core/src/shared/fs/fs.ts
- packages/core/src/shared/vscode/env.ts
- packages/core/src/test/shared/fs/fs.test.ts
- packages/core/src/testWeb/shared/fs.test.ts
Both AWS Toolkit and Amazon Q fail to start when the effective user account is defined externally (e.g. by AD/LDAP). #5277
[error] SystemError: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
Bisected to #5215 which calls os.userInfo in getUsername (env.ts).
When the effective user ID does not have a matching entry in /etc/passwd, userInfo throws an exception. Discussed in:
- https://github.com/microsoft/vscode-remote-release/issues/9649
- https://github.com/cyjake/ssh-config/issues/77
1. Login as a user that is synced to AD/LDAP.
2. Install AWS Toolkit and Amazon Q
3. Errors in `~/.config/Code/logs/<date and time>/window1/exthost/exthost.log`
```
2024-07-08 12:09:54.179 [error] Activating extension amazonwebservices.amazon-q-vscode failed due to an …
```
> fix(env): getUserInfo() may fail on AD/LDAP

- .github/workflows/node.js.yml
If you don't set a code coverage token it uses a global shared codecoverage token that can be rate limited
Switch to our codecoverage token
- https://github.com/aws/aws-toolkit-vscode/issues/4232
> test: codecov environment variable

- packages/core/src/login/webview/vue/login.vue
- packages/core/src/login/webview/vue/reauthenticate.vue
- packages/core/src/login/webview/vue/root.vue
remove auth screen background.
| Dark Theme | Light Theme | 
| -- | -- |
| <img width="378" alt="Screenshot 2024-07-09 at 9 27 26 PM" src="https://github.com/aws/aws-toolkit-vscode/assets/371007/ae5007e2-585c-4d29-b020-a3d718cb28c9"> | <img width="373" alt="Screenshot 2024-07-09 at 9 27 48 PM" src="https://github.com/aws/aws-toolkit-vscode/assets/371007/e979cfed-51b2-4787-bb7b-80180cfc82bd"> |
| <img width="370" alt="Screenshot 2024-07-09 at 9 27 59 PM" src="https://github.com/aws/aws-toolkit-vscode/assets/371007/fb71ecf1-af18-4bc2-819e-0cc05a20e81d"> | <img width="383" alt="Screenshot 2024-07-09 at 9 28 07 PM" src="https://github.com/aws/aws-toolkit-vscode/assets/371007/840beb4d-cea1-483c-ac95-655fa989e872"> |
By submitting this pull request, I confirm that my contribution is made under …
> fix: remove auth screen background

- plugins/eslint-plugin-aws-toolkits/lib/rules/no-incorrect-once-usage.ts
(node:99880) DeprecationWarning: "no-incorrect-once-usage" rule is
using `context.getScope()`, which is deprecated and will be removed
in ESLint v9. Please use `sourceCode.getScope()` instead. (Use `node
--trace-deprecation ...` to show where the warning was created)
update rule
> fix: eslint DeprecationWarning

- packages/core/src/awsService/accessanalyzer/vue/iamPolicyChecks.ts
The refactor that moved AWS services to the `awsService` folder (https://github.com/aws/aws-toolkit-vscode/commit/198d2c9946adfd2a0f0c4ff567a8da2a985c72e6) broke the Access Analyzer integration, since `sourcePath` was hardcoded to `src/accessanalyzer/vue/index.js`. The integration UI is blank.
Include `awsService` in `sourcePath`. The integration UI shows up after the fix.
> fix(access analyzer): broken path

- packages/amazonq/.changes/next-release/Feature-4a1c951a-2289-4808-b106-86fe4f03528e.json
- packages/core/src/amazonqFeatureDev/client/codewhispererruntime-2022-11-11.json
- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/amazonqFeatureDev/session/sessionState.ts
- packages/core/src/amazonqFeatureDev/types.ts
- packages/core/src/codewhisperer/client/user-service-2.json
- packages/core/src/test/amazonqFeatureDev/session/sessionState.test.ts
Currently, there is no information shown to customers in the chat regarding the number of iterations they could run during code generation.
They only get to know this on hitting the iteration limits and seeing the error like you have reached the limit for number of iterations.
Hence, with this change, we are showing the remaining iterations proactively by exposing the remaining iteration numbers and total iteration numbers to the end of each code generation. 
> feat: proactively show code generation iterations

- buildspec/linuxE2ETests.yml
- buildspec/linuxIntegrationTests.yml
- buildspec/linuxTests.yml
- buildspec/shared/linux-install.sh
- buildspec/windowsTests.yml
- We don't have code coverage reporting for our integ/e2e/linux tests
- Add it
https://github.com/aws/aws-toolkit-vscode/issues/4232
> feat: Add codecov to integ/e2e/linux tests

- packages/core/src/awsService/apigateway/vue/invokeRemoteRestApi.ts
A recent refactor did not update certain static paths which prevent webviews from working.
Fix the incorrect paths.
- Create a REST API Gateway on my AWS account
- In the AWS Explorer right click the REST API and select `Invoke on AWS`, this will open the webview.
> fix: refactor broke webview paths

- packages/amazonq/src/api.ts
- packages/amazonq/src/extension.ts
- packages/core/src/amazonq/extApi.ts
- packages/core/src/amazonq/index.ts
- packages/core/src/applicationcomposer/commands/openTemplateInComposer.ts
- packages/core/src/applicationcomposer/messageHandlers/generateResourceHandler.ts
- packages/core/src/applicationcomposer/messageHandlers/initMessageHandler.ts
- packages/core/src/codewhispererChat/index.ts
- packages/core/src/test/applicationcomposer/messageHandlers/generateResourceHandler.test.ts
- packages/core/src/test/applicationcomposer/messageHandlers/initMessageHandler.test.ts
- packages/core/src/test/applicationcomposer/utils.ts
- packages/toolkit/.changes/next-release/Bug Fix-2579c8e9-c8a2-45f8-bebf-228d7bd5796d.json
- app composers generate suggestions became unclickable when we switched back to seperate auth since they were relying on auth session sharing
- allow extensions to call into auth/chat for amazon q. This allows toolkit to have features that depend on q auth without exposing all of auth itself
> fix: app composer generate suggestions unclickable when logged in

- .github/CODEOWNERS
Due to a recent refactor we need to also update
the codeowners path for accessanalyzer
> ci: update accessanalyzer codeowners path

- packages/core/src/auth/sso/clients.ts
- packages/core/src/shared/errors.ts
When we attempt to refresh an SSO session, we sometimes saw
a TimeoutError in our telemetry as the reason for refresh failure.
We treat the TimeoutError as a network error.
See `isSocketTimeoutError()` docstring for more details.
> Timeout error

- packages/core/src/amazonq/lsp/lspController.ts
Upgrade the Amazon Q chat LSP to version 0.1.3. 
The version 0.1.3 has security improvements.
> fix(amazonq): Update LSP version to 0.1.3

- packages/amazonq/test/unit/amazonqFeatureDev/util/files.test.ts
- packages/core/src/amazonqFeatureDev/util/files.ts
We (feature dev team) want to understand if there are any other relevant code file extension that should be added to the allowlist.
To obtain such information, we want to emit telemetry event to see the most common file extensions being ignored while bundling.
Example log: 
```
2024-07-11 10:35:18.127 [info] Amazon Q Developer Agent for software development Conversation ID: dea452f8-e685-4285-b350-900a06a40d51
2024-07-11 10:35:19.146 [info] ignoring file extension name: graphql, count: 82
2024-07-11 10:35:19.146 [info] ignoring file extension name: eslintignore, count: 1
2024-07-11 10:35:19.146 [info] ignoring file extension name: nvmrc, count: 1
```
This is a follow up of this [pull request](https://github.com/aws/aws-toolkit-vscode/pull/5238)
By submitting this pull request, I confirm …
> telemetry(feature dev): add ignore file metric while bundling repository

- packages/amazonq/.changes/next-release/Bug Fix-acc20495-b700-47cd-b3fc-d73a34c7c720.json
- packages/core/src/amazonqGumby/chat/controller/controller.ts
- packages/core/src/codewhisperer/commands/startTransformByQ.ts
- packages/core/src/codewhisperer/service/transformByQ/transformApiHandler.ts
- packages/core/src/test/codewhisperer/commands/transformByQ.test.ts
When users download the pre-build error logs, then run another transformation without clicking the "Start a new transformation" button, if another pre-build error occurs, the **old** logs will show up. This could happen if they close the Q Chat tab and re-run a transformation, or if they close the IDE between job runs. If they do click the "Start a new transformation" button, everything works fine, but we need to handle these other situations.
Use `makeTemporaryToolkitFolder()` which creates a new folder with a random name, so that the logs are downloaded there, meaning we don't have to deal with deleting the old logs that would otherwise be in the same folder as the new logs.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> fix(amazonq): always show latest build logs

- .github/workflows/node.js.yml
- CONTRIBUTING.md
- buildspec/linuxE2ETests.yml
- buildspec/linuxIntegrationTests.yml
- buildspec/linuxTests.yml
- codecov.yml
- docs/arch_develop.md
- packages/amazonq/.c8rc.json
- packages/core/.c8rc.json
- Codecoverage for amazon q wasn't actually generating any lcov.info information since the c8rc.json lived in core and amazonq couldn't find it
- Move c8rc.json to the root of the project
- Merge the resulting lcov.info files
> fix: Code coverage report for amazon q

- packages/core/src/shared/errors.ts
- packages/core/src/test/shared/errors.test.ts
The scrubNames() function removes PII from file paths in a given string. The issue was that in certain cases where the file path extension was composed of multiple extensions, no file extension would be used.
So instead of 'x.ext1.ext2' -> 'x.ext2', we would just get 'x'.
Preserve the last file extension.
Also, this indirectly fixed some of the unit tests that were returning unexpected results.
> fix: scrubNames() drops file extension

- packages/amazonq/.changes/next-release/Bug Fix-e36701b2-54c6-4be5-9a9c-d82a91e00060.json
- packages/core/src/shared/fs/fs.ts
- packages/core/src/shared/utilities/cacheUtils.ts
- packages/core/src/test/shared/fs/fs.test.ts
- packages/toolkit/.changes/next-release/Bug Fix-19be4c1e-355d-428e-bc8a-b8aa3cc64b7a.json
During token refresh we were seeing unexpected EPERM errors in the `aws_refreshCredentials` metric, specifically in Windows.
A node filesystem rename() call can fail due to a racecondition on Windows. Looking in to the VS Code Filesystem implementation they account for this: https://github.com/microsoft/vscode/blob/09d5f4efc5089ce2fc5c8f6aeb51d728d7f4e758/src/vs/base/node/pfs.ts#L496
So we just need to use this rename instead.
Additional info here from graceful-fs which inspired the VSCode implementation: https://github.com/isaacs/node-graceful-fs/blob/234379906b7d2f4c9cfeb412d2516f42b0fb4953/polyfills.js#L87
> fix: EPERM error during SSO token refresh

- packages/core/src/threatComposer/handlers/saveFileMessageHandler.ts
- packages/toolkit/.changes/next-release/Bug Fix-b2643447-b3f1-441d-8473-c23b4ef649d8.json
On saving a threat model, the window incorrectly displays "Threat Composer JSON has bees saved"
Fix Typo to correctly read "Threat Composer JSON has been saved"
✅ By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
> Remove Typo In ThreatComposer PopUp when Saving files

- packages/core/src/auth/auth.ts
- packages/core/src/auth/sso/clients.ts
- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/core/src/shared/utilities/cacheUtils.ts
- packages/core/src/shared/utilities/map.ts
- packages/core/src/test/credentials/auth.test.ts
- packages/core/src/test/credentials/sso/ssoAccessTokenProvider.test.ts
- packages/core/src/test/credentials/testUtil.ts
- packages/core/src/test/shared/utilities/map.test.ts
In the reauth metric (`aws_loginWithBrowser` + `isReAuth: true`) we didn't know why
the user needed to reauth. It could have been due to regular expiration or some unexpected
error.
**See each commit for specific change**
Add a new field in `aws_loginWithBrowser` named `reAuthReason` which will have some sort
of identifier for why reauth was needed.
What was actually changed in this PR:
- `SsoAccessTokenProvider` has an object `ReAuthState` (name may change) which maps an SSO connection -> reason why we need to reauth
- In certain flows such as SSO token refresh, if it fails we will update the `ReAuthState` with the reason why.
- Later on the user may want to reauthenticate, and when they start the flow `SsoAccessTokenProvider` will know the reason and record it in `aws_loginWithBrowser` …
> auth: add telemetry for why the user needed to reauth

- packages/core/src/codewhisperer/models/constants.ts
- Previously debounce time was 15 sec and may be causing IDE slowness due to File scans.
- Increasing debounce time to 30 sec.
> Security Scans: Increasing debounce time to 30 sec

- packages/core/src/shared/globalState.ts
- packages/core/src/stepFunctions/activation.ts
- packages/core/src/stepFunctions/commands/visualizeStateMachine/abstractAslVisualizationManager.ts
- packages/core/src/stepFunctions/commands/visualizeStateMachine/aslVisualizationCDKManager.ts
- packages/core/src/stepFunctions/commands/visualizeStateMachine/aslVisualizationManager.ts
- packages/core/src/stepFunctions/commands/visualizeStateMachine/renderStateMachineGraphCDK.ts
- packages/core/src/stepFunctions/utils.ts
- packages/core/src/test/stepFunctions/commands/visualizeStateMachine.test.ts
- packages/core/src/test/stepFunctions/utils.test.ts
Use of vscode's `globalState` interface allows bugs such as https://github.com/aws/aws-toolkit-vscode/pull/3060#discussion_r1050240283 . 
Previous work:
- https://github.com/aws/aws-toolkit-vscode/pull/5293
- https://github.com/aws/aws-toolkit-vscode/pull/5309
Update codewhisperer code to use `globals.globalState` , which allows type-checking, error handling, and centralization of related logic.
> refactor(stepFunctions): use globalState abstraction

- packages/amazonq/test/unit/codewhisperer/util/authUtil.test.ts
- packages/core/src/auth/secondaryAuth.ts
- packages/core/src/dev/activation.ts
- packages/core/src/shared/credentials/credentialsProfileMru.ts
- packages/core/src/shared/credentials/defaultCredentialSelectionDataProvider.ts
- packages/core/src/shared/extensionGlobals.ts
- packages/core/src/shared/globalState.ts
- packages/core/src/shared/telemetry/activation.ts
- packages/core/src/shared/telemetry/telemetryService.ts
- packages/core/src/shared/telemetry/util.ts
- packages/core/src/shared/utilities/mementos.ts
- packages/core/src/test/codecatalyst/auth.test.ts
- packages/core/src/test/credentials/auth.test.ts
- packages/core/src/test/credentials/secondaryAuth.test.ts
- packages/core/src/test/credentials/testUtil.ts
- packages/core/src/test/fakeExtensionContext.ts
- packages/core/src/test/globalSetup.test.ts
- packages/core/src/test/login/webview/vue/backend_amazonq.test.ts
- packages/core/src/test/login/webview/vue/backend_toolkit.test.ts
- packages/core/src/test/shared/credentials/credentialsProfileMru.test.ts
- packages/core/src/test/shared/defaultAwsClientBuilder.test.ts
- packages/core/src/test/shared/regions/regionProvider.test.ts
- packages/core/src/test/shared/telemetry/telemetryService.test.ts
- packages/core/src/test/shared/telemetry/util.test.ts
- plugins/eslint-plugin-aws-toolkits/lib/rules/no-banned-usages.ts
- plugins/eslint-plugin-aws-toolkits/test/rules/no-banned-usages.test.ts
Use of vscode's `globalState` interface allows bugs such as https://github.com/aws/aws-toolkit-vscode/pull/3060#discussion_r1050240283 . 
Previous work:
- https://github.com/aws/aws-toolkit-vscode/pull/5293
- https://github.com/aws/aws-toolkit-vscode/pull/5309
- https://github.com/aws/aws-toolkit-vscode/pull/5323
- https://github.com/aws/aws-toolkit-vscode/pull/5344
Update all code to use `globals.globalState` , which allows type-checking, error handling, and centralization of related logic.
> refactor: use globalState abstraction

- packages/core/src/awsService/accessanalyzer/vue/iamPolicyChecks.vue
- packages/toolkit/.changes/next-release/Bug Fix-ba5dce72-56eb-42a5-92f7-f3b894c43e76.json
`cfn-policy-validator` dependency was updated with a bugfix (https://github.com/awslabs/aws-cloudformation-iam-policy-validator/releases/tag/v0.0.34)
Update the dependency version to 0.0.34 from 0.0.33 in the accessanalyzer integration.
> fix(accessanalyzer): Update cfn-policy-validator version

- packages/amazonq/.changes/next-release/Bug Fix-4b44becd-f933-48b3-9e77-62da8504969a.json
- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/amazonqFeatureDev/errors.ts
- packages/core/src/amazonqFeatureDev/session/sessionState.ts
When cancellation is requested, the error message includes a typo ("within"). By the way, since ```class.name``` or ```someClassInstance.constructor.name``` can be impacted by transpilers when bundled, some explicit name might be required and adding here.
This PR fixes:
- Typo
- Add a safe static field check for error name which doesn't depend on transpiler / prototype / es polyfill
> refactor(amazonqFeatureDev): refactor error message and include backfill for error name

- packages/core/src/codewhisperer/service/classifierTrigger.ts
for new languages that we support which don't have a coefficient, we want to use average instead of 0 as default
> amazonq: update default language coefficient for classifier

- packages/core/src/shared/errors.ts
- packages/core/src/test/shared/errors.test.ts
When we use the function getTelemetryReasonDesc() we would lose information about the underlying error in the case the error was a ToolkitError with an underlying chained error. Only the message of the ToolkitError was used.
So in telemetry we would be missing some information about the real cause of the error.
getTelemetryReasonDesc() will return a  message which consists of all messages in the chain. It recursively calls in to the next chained error of a ToolkitError and appends it to the final output.
This will give us some context about the higher level call as well as the root of the issue.
The final message could look something like:
"Message A::Message B::Message C"
> telemetry: include chained error message in reasonDesc

- packages/amazonq/.changes/next-release/Bug Fix-a2ce509a-e62b-45a6-95d1-2e5e1fe4587d.json
- packages/amazonq/src/extension.ts
Problem: VSC workbench can throw an error sometimes if we try to focus the panel too quickly. `Error: View already awaiting revival`
Solution: Use our command to focus the panel and give time for the ext to load by sending this to the back of the queue after 1 second.
> fix(amazonq): sign-in page may not render in rare scenarios

- packages/core/src/applicationcomposer/messageHandlers/generateResourceHandler.ts
- packages/core/src/applicationcomposer/types.ts
- packages/core/src/test/applicationcomposer/messageHandlers/generateResourceHandler.test.ts
appcompser got a lot invalid JSON responses and out of domain errors from codewhisperer api call
starling using `userIntent` to get higher quality responses from codewhisperer
> fix(appcomposer): use userIntent to get higher quality responses from codewhisperer

- .github/workflows/node.js.yml
- packages/core/scripts/test/launchTestUtilities.ts
- In github ci vscode is downloaded for every test package (core/q)
- Use AWS_TOOLKIT_TEST_CACHE_DIR and AWS_TOOLKIT_TEST_USER_DIR to cache the test and user directories
- By default use `../../.vscode-test` directory
Related issue: https://github.com/aws/aws-toolkit-vscode/issues/5311
> fix: VSCode is downloaded for every test package

- packages/amazonq/.changes/next-release/Bug Fix-32f3fd29-6924-4e09-a94d-f8e249542c1b.json
- packages/core/src/amazonq/webview/ui/tabs/constants.ts
- dev/transform intro text shows as markdown
- it should show as regular text
Before:
After:
Before:
After:
> fix: Amazon Q Dev and Transform introduction text formatted incorrectly

- packages/core/src/shared/fs/fs.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/shared/utilities/cacheUtils.ts
- packages/core/src/test/shared/fs/fs.test.ts
- packages/core/src/test/shared/vscode/runCommand.test.ts
When writing content to our SSO cache file we noticed the json content was malformed.
As a solution we did an "atomic" write where we wrote the contents to a temp
file then renamed to the actual file. This prevented the content from being malformed due to
by separate write.
The combination of writing a temp file, then renaming it started failing recently:
- Failures were indicated by our metric `aws_refreshCredentials` 
- its properties are `reason: 'FileNotFound'` + `reasonDesc: 'Failed to save "x:/Users/x/.aws/sso/cache/x"'`
- The problem was introduce in #5335 version of Amazon Q 1.16.0/AWS Toolkit 3.15.0
- We were using Node.js `rename()` and then switched to the VS Code Filesystem `rename()`
- [This is the specific code change that started causing the …
> bug: premature SSO expiration due to failed file `rename()`

- packages/amazonq/test/unit/codewhisperer/util/authUtil.test.ts
- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/util/authUtil.ts
Previously the AWS Toolkit and Amazon Q extensions shared Auth connections. To do this they communicated their Auth connections to each other, with each extension storing this in their auth connection cache.
Later we decided to stop sharing the Auth connections between the extensions, instead having each extension create its own connection.
The problem is that when we created this separate auth connection change, we had stale connections remaining in Amazon Q. This caused issues like users being unable to sign in to a new connection since the cached connections showed it already existed.
On every startup clear the stale connections.
We have existing code that does this, but it only ran in a CodeCatalyst dev environment. But it looks like we always want to run this check as it seems there …
> bug: Amazon Q sign in blocked by stale connection

- packages/core/src/shared/telemetry/activation.ts
- packages/core/src/shared/telemetry/util.ts
- packages/core/src/test/shared/telemetry/util.test.ts
Problem: There is a function called `setupTelemetryId` which syncs the client Id between the two extensions when both are installed. However, there is a race condition that causes toolkit to generate the client ID before calling this setup function. The result is that amazon q is signalled to update its client id with a fresh one from toolkit. This results in telemetry showing we have a new user even though that is not the case. 
Solution: Bypass this race condition by putting the logic in the client id generation function. We will also change how we compute the client ID so that extensions more intuitively  converge to the same client id. See code for computation docs.
Cases:
1. New user installs an extension -> client id is generated once and stored in global state
2. Existing extension …
> fix(telemetry): toolkit replacing amazon q clientId

- packages/amazonq/.changes/next-release/Bug Fix-3caf33d6-2e1f-4013-92e3-365c77ac9378.json
- packages/core/src/codewhisperer/util/zipUtil.ts
When zipping the project workspace, binary files are getting decoded/added to the zip artifacts as a utf-8 string which results in .class files being invalid and causing scans to fail.
Process binary files by adding them to the zip using the local file path instead of a buffer.
> fix: add class files from local file

- codecov.yml
We have no idea what % of codecoverage partner teams have
Add flags to see
> Add codecoverage for partner teams

- packages/amazonq/.changes/next-release/Bug Fix-ceb237af-1d58-4560-9939-c07074eb3eee.json
- packages/core/src/shared/errors.ts
- packages/core/src/shared/fs/fs.ts
- packages/core/src/test/shared/errors.test.ts
- packages/core/src/test/shared/fs/fs.test.ts
- packages/toolkit/.changes/next-release/Bug Fix-04a6bfcb-9d56-4388-aadd-50e6c7db9670.json
In our `aws_refreshCredentials` telemetry we saw a spike in `FileNotFound`
errors when writing the refreshed token to our filesystem.
This is caused by something in the `vscode.workspace.fs.rename()`
implementation that is not obvious and does not seem like an obvious error
on our end. Most of the time things work, so most users are not running
in to this problem.
Originally, to fix some errors happening during writing to the filesystem
we created an "atomic" write, but there are edge cases where this did
not work. So there are different implementations of writing a file that we used
to rememdy this.
Try the next write file method as a fallback when one fails.
See the comment in the code for the explanation of the implementation.
We also report telemetry on the specific failed cases to …
> fix: FileNotFound error during SSO token refresh

- packages/core/src/dynamoDb/utils/dynamodb.ts
- packages/core/src/dynamoDb/vue/tableView.css
- packages/core/src/dynamoDb/vue/tableView.ts
- packages/core/src/dynamoDb/vue/tableView.vue
- packages/core/src/shared/clients/dynamoDbClient.ts
Users should be able to query the records based on Partition Key and Sort Key (if present in the table). 
So, a new panel for querying the table data has been added in the DynamoDB WebView. 
> DynamoDB Query changes

- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/test/techdebt.test.ts
[fix(tests): snooze split session tech debt](https://github.com/aws/aws-toolkit-vscode/commit/a71d1e9b2601e082ae2f5841c3e53b92a3a8b29f) 
- Split sessions is just over a month old, let's snooze it a little longer.
[fix(tests): remove Q 3 -> 5 scope migration tech debt](https://github.com/aws/aws-toolkit-vscode/commit/62238939beafdbf72925f7d09b5ae2f2a270960e) 
- Cleans up remainder of https://github.com/aws/aws-toolkit-vscode/commit/9525cdfab8a40cb88f361c522d6bc7dadf794f81
> fix tech debt tests

- package-lock.json
- packages/amazonq/.changes/next-release/Bug Fix-1215af20-b5fb-451a-b118-deb6a462fb32.json
- packages/amazonq/.changes/next-release/Bug Fix-4885c18d-bf4f-4b58-b318-407d1c2bcbec.json
- packages/amazonq/.changes/next-release/Bug Fix-58eb1af1-78e7-44ba-b62f-7ebb6751f774.json
- packages/core/package.json
Q Chat UI:
- Prompt Text box does not accurately display cursor position
- The scrollbars were disabled/invisible
- The max tabs notification couldn't be dismissed
Updating @aws/mynah-ui to 4.15.4
https://github.com/aws/mynah-ui/releases/tag/v4.15.4
- Fixing issue with an incorrect input cursor position in the prompt text box
- Showing/hiding the scrollbars is now controlled by the OS settings
- Fixing issue with the max tabs notification not being dismissible
> Fix Q chat's cursor positioning, scroll bars, max tabs notification

- packages/core/src/codewhisperer/service/transformByQ/transformApiHandler.ts
Some users have broken symlinks within their projects, which cause the zipping process to fail.
Skip these so that the zipping still succeeds.
> fix(amazonq): skip symlinks when zipping

- packages/amazonq/src/extensionNode.ts
- packages/core/package.json
- packages/core/src/shared/index.ts
- packages/core/src/shared/indexNode.ts
4294f8d1522511308651d3f82992c1489f7c2e4c only emits for toolkit. This adds to amazon q as well.
This will mean telemetry events are duplicated if both extensions are installed. With some additional complexity and over-engineering, we can avoid this. But de-duplication should not be a big deal across products.
> feat(amazonq): emit ide_editCodeFile

- packages/amazonq/.changes/next-release/Bug Fix-b1798202-f20e-42b4-a730-04ee77572ee7.json
- packages/core/src/codewhispererChat/editor/context/file/importReader.ts
- packages/core/src/codewhispererChat/editor/context/focusArea/focusAreaExtractor.ts
the `Python.findNames` and `findNamesWithInExtent` promises never resolves and causing chat to hang
related: https://github.com/aws/aws-toolkit-vscode/pull/4954
temporarily remove the findNames & findNamesWithInExtent calls for all languages as a mitigation until the rootcause is fixed
> fix(amazonq): AmazonQ Chat window became unresponsive after prompt

- package-lock.json
- packages/core/package.json
Before the latest v4.15.4 release, the markdown table's UI was:
But with v14.5.4 the new style was inadvertently introduced:
Updating @aws/mynah-ui to v4.15.5. 
https://github.com/aws/mynah-ui/releases/tag/v4.15.5
Table styles are reverted back
> fix(amazonq): reverted table styles in mynah-ui

- packages/core/src/auth/sso/clients.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/shared/errors.ts
Problem: Rare and unreproducible case where SDK client calls to create an SSO token return an html page instead of JSON data. It is probably some error page indicating an interference with the request.
Solution: Try to extract the reason and status code from the page if possible, and report it in telemetry.
> fix(telemetry): try to handle SyntaxError for createToken requests

- packages/core/src/login/webview/vue/login.vue
- packages/core/src/shared/clients/ec2MetadataClient.ts
Contains 2 commits (don't squash merge)
[chore: change ec2 token fetch error to warn instead](https://github.com/aws/aws-toolkit-vscode/commit/f247601818a5949aab279c44242d60d1dc115b8c) 
It isn't really an error unless you are using the ext in EC2. It's just cluttering the logs.
`warn` may even be a stretch.
[fix(auth): allow trailing slash for start urls](https://github.com/aws/aws-toolkit-vscode/commit/717062f91cb98ae5346b49c12744b5caebd6b525) 
Might fix cases for some users reporting that the auth screen is not accepting their start url. ~~May or may not~~ Does fix https://github.com/aws/aws-toolkit-vscode/issues/5412
> Misc small changes (allow trailing slash in start url, updating log level)

- packages/core/src/amazonqGumby/app.ts
We were incorrectly importing the wrong `sessionStorage` api, causing a runtime error to be reported under `Features -> Runtime Status`.
This change imports the correct already-existing sessionStorage.
Tested:
1. Launched VSCode while not authenticated through Q, authenticated and ran `/transform` workflow on a project expected to succeed in transforming
2. Repeated above test case, but was authenticated at launch
3. Closed `/transform` tab, re-opened, confirmed tab saved session state
4. While a `/transform` tab was already open, tried to open a new `/transform` tab from the Q Chat tab and was redirected to the already existing tab
> Fix: incorrect chatSession import

- packages/amazonq/.changes/next-release/Bug Fix-4ca70db9-154a-4c5d-a311-07e08e7bd56c.json
- packages/core/package.nls.json
- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
When selected folder/workspace size its too large, we prompt to select a smaller one. However, after selected, user describe that doesn't retry again forcing to rewrite the prompt again. 
This PR adds a retry button option after it changes the workspace folder and update the placeholder, allowing user choose rewrite the prompt or retry the previous one.
https://github.com/user-attachments/assets/3281cbf3-afed-4293-887a-5346df0b4afe
> fix(amazonqFeatureDev): add retry step after user change workspace folder

- packages/core/src/shared/errors.ts
- packages/core/src/test/shared/errors.test.ts
During SSO token refresh (`aws_refreshCredentials`) we were seeing certain transitive Network specific errors causing the refresh to fail and the connection to show as expired.
Add the specific errors to the `isNetworkError()` function.
What this ends up doing:
- when these errors appear during token refresh the SSO connection remains valid, but the `getToken()` call will throw
> auth: Add more network errors

- packages/amazonq/.changes/next-release/Bug Fix-7299b780-d965-4bed-9302-0ed726c8e2ee.json
- packages/core/src/shared/utilities/workspaceUtils.ts
https://github.com/aws/aws-toolkit-vscode/issues/5431
Ignore .venv and venv at local indexing. We will build more robust ignore mechanism in the LSP soon. This is a stopgap for now.
> fix(amazonq): ignore venv when local indexing

- packages/amazonq/test/unit/codewhisperer/util/authUtil.test.ts
- packages/core/src/auth/secondaryAuth.ts
- packages/core/src/codecatalyst/auth.ts
- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
Includes a new telemetry event, 'auth_modifyConnection' which will begin to encompass changes to connections.
> feat(telemetry): add telemetry for restoring and forgetting connections

- packages/amazonq/.changes/next-release/Bug Fix-b3b09219-b76c-4892-90b4-45fada4a5e60.json
- packages/core/src/codewhisperer/service/recommendationHandler.ts
https://github.com/user-attachments/assets/40cf2d0f-2c25-469d-a7e4-3895766a3fbf
The flash exists because after each pagination call we refresh the max number of suggestions in the tooltip.(1/1 to 1/5, then 1/6) Since we refresh the max count, we also refresh the suggestion itself. VSC do not have API to let us just refresh the max count.(we fresh it by re-creating the inline completion object)
https://github.com/user-attachments/assets/f88d7cb0-a717-4b06-a208-957ee19993bb
Remove the refresh of index. This solution has been approved by product.
> fix(amazonq): avoid refresh suggestion for paginated response

- packages/amazonq/.changes/next-release/Bug Fix-b5a20120-ce65-48ef-a256-62d0c48f4c95.json
- packages/core/src/login/webview/vue/login.vue
Q logo is aligned left for some reason
Change styling to align center, see screenshot
> fix: center login logo

- docs/telemetry.md
- packages/core/src/shared/telemetry/spans.ts
- packages/core/src/shared/telemetry/telemetry.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/shared/vscode/commands2.ts
- packages/core/src/test/shared/telemetry/spans.test.ts
- packages/core/src/test/testUtil.ts
See the doc added in this PR for explanation on Problem + Solution
The gist is that you can now add "options" to a `run()`, allowing configurations.
In our case:
- we can signal for run() to not emit, but it will still emit by default.
- Add a `FunctionEntry` which will add to the function execution stack that is derived from the span stack
> feat: telemetry stack trace - runWithCallEntry()

- packages/core/src/shared/errors.ts
- packages/core/src/test/shared/errors.test.ts
Due to a recent change the isSyntaxError() function was not returning when expected. We were still seeing it appear in `auth_refreshCredentials` even though it should have been filtered out.
Fix the function so it reports correctly identifies syntax error when it happens.
> fix: isSyntaxError() function

- packages/amazonq/.changes/next-release/Feature-273f3647-0ce0-48ad-874a-a9614447a18d.json
- packages/amazonq/package.json
- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/shared/settings-amazonq.gen.ts
need to add a notification to IdC users to contact their admin to configure extended session
show the notification once to IdC users when their connection expired
> feat(amazonq): add session configuration notification

- packages/amazonq/test/unit/codewhisperer/util/authUtil.test.ts
- packages/core/src/auth/auth.ts
- packages/core/src/auth/secondaryAuth.ts
- packages/core/src/auth/sso/clients.ts
- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/core/src/auth/utils.ts
- packages/core/src/codecatalyst/auth.ts
- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/dev/activation.ts
- packages/core/src/extensionNode.ts
- packages/core/src/login/webview/vue/amazonq/backend_amazonq.ts
- packages/core/src/login/webview/vue/backend.ts
- packages/core/src/shared/telemetry/spans.ts
- packages/core/src/shared/telemetry/util.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/shared/vscode/commands2.ts
- packages/core/src/test/credentials/auth.test.ts
- packages/core/src/test/credentials/sso/ssoAccessTokenProvider.test.ts
- packages/core/src/test/credentials/testUtil.ts
- packages/core/src/test/shared/telemetry/spans.test.ts
- packages/core/src/test/testUtil.ts
When an auth connection changes, eg goes from valid to invalid, there were cases for some users where it happened unexpectedly. It was difficult to answer why the users connection became invalid
Wrap many auth related functions with their "function entry" context. This will then allow the final telemetry event in `Auth.updateConnectionState()` to report the entire call stack in its `source` field for the metric `auth_modifyConnection`. What this results in is a string like: `AmazonQ#signoutButton:AuthUtil#signout:Auth#signout,deleteConnection,updateConnectionState` which tells us the path taken to get to updating the connection state.
Example metric when I click signout in the Amazon Q quick pick:
```
[debug] telemetry: auth_modifyConnection {
Metadata: {
action: 'updateConnectionState', …
```
> telemetry: add function stack to auth connection change

- packages/core/src/shared/performance/performance.ts
- packages/core/src/shared/telemetry/spans.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/shared/utilities/workspaceUtils.ts
- packages/core/src/test/codewhisperer/commands/startSecurityScan.test.ts
- packages/core/src/test/shared/performance/performance.test.ts
- packages/core/src/test/shared/telemetry/spans.test.ts
- packages/core/src/test/utilities/performance.ts
- We are sometimes running into problems where functions are using a ton of memory/cpu but we have no way to figure that out ahead of time without manually debugging
- Create a starter set of tools that allows us to measure the impact of different parts of code. These tools should be used as needed and surround heavy computational parts of the code i.e. collecting all files in the workspace, reading them in and putting them in a zip
See:
- [Security Scans] Adding performance test for auto scans: https://github.com/aws/aws-toolkit-vscode/pull/5420
- [Amazon Q Security Scans] Refactoring code to improve the performance: https://github.com/aws/aws-toolkit-vscode/pull/5346#
> performance: Create a starter set of tools for measuring the CPU/memory impact of code

- packages/core/src/test/techdebt.test.ts
we have a keepAlive workaround that is fixed in vscode 1.93 https://github.com/microsoft/vscode/issues/173861
add a techdebt reminder.
> tests: check "keepAlive" techdebt

- packages/core/src/test/shared/telemetry/spans.test.ts
- "returns the correct call stack when the context switches" uses sleep under the hood which requires manual ticks when fake clocks are installed. When we added the fake clock it caused this test to fail
- only install the fake clock for "records performance"
> tests: fix telemetry span test timeout

- packages/core/src/shared/telemetry/telemetryClient.ts
- packages/core/src/shared/telemetry/util.ts
- packages/core/src/shared/vscode/env.ts
- packages/core/src/test/shared/vscode/env.test.ts
Anything that was a ssh-remote environment was labeled as `ec2` in our
telemetry. But there are more nuanced cases for Amazon internal ssh connections.
Add more specific checks for a Cloud Desktop and an internal ec2
> telemetry: add env type `cloudDesktop-amzn` & `ec2-amzn`

- .github/workflows/lintcommit.js
- .github/workflows/node.js.yml
- CONTRIBUTING.md
Pull requests and commits often lack a clear, concise explanation or even just a useful, clear, concise title. 
This increases the cost of reviewing the PRs. And results in low-quality commit log, which adds friction to understanding why a change was made (and reduces learning/communication for observers).
- add a CI check (github action) which enforces a custom flavor of https://www.conventionalcommits.org/ for *PR titles*.
- currently doesn't check commit messages because those are usually squash-merged.
- update docs.
> ci: conventional commits

- package-lock.json
- packages/amazonq/.changes/next-release/Bug Fix-738aa5e7-6e07-4b9e-8c03-2ca25d60f7db.json
- packages/core/package.json
New version of MynahUI requires release in vscode.
Release new version of MynahUI with the following bug fix: [Nested list parsing doesn't work in Mynah UI](https://github.com/aws/mynah-ui/issues/97).
MynahUI v4.15.7 release notes: https://github.com/aws/mynah-ui/releases/tag/v4.15.7
The release fixes:
- markdown formatting in nested lists in response prompt
- code indentation in response prompt
> fix(amazonq): Release mynah-ui v 4.15.7 with a bug fix

- packages/amazonq/.changes/next-release/Bug Fix-43d1cc50-8f12-4467-9331-f9b1fe89381d.json
- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/service/recommendationHandler.ts
This is an alternative to the fix in https://github.com/aws/aws-toolkit-vscode/pull/5474/files.
Test case 1: Trigger suggestion, accept it, ctrl +z, saw same suggestion, press Esc, suggestion disappears. The error  command not found is not thrown. In this case, user can also reject it by keep typing to ignore it. 
Test case 2: Install Vim. Trigger suggestion, accept it, ctrl +z, saw same suggestion, press Esc,  suggestion disappears.  The error  command not found is not thrown. In this case, user can also reject it by keep typing to ignore it. .
Test case 3: Install Vim. Trigger suggestion, press left or right, the navigation is still not working(because Vim overrides the left right keys with highest priority), however, there is no crash anymore and user can still accept or reject the …
> fix(amazonq): "rejectCodeSuggestion not found" after ctrl-z

- .github/PULL_REQUEST_TEMPLATE.md
- .prettierignore
For better or worse, PRs tend to be squash-merged, so devs tend to neglect commit messages, and the PR description (as opposed to commit messages) contains the relevant info.
Therefore to encourage a useful git commit history, we have configured the github repo to use the PR description as the "Default commit message".
But the `PULL_REQUEST_TEMPLATE.md` contains a lot of boilerplate that would then get pasted into the merged commit message unless the merging party takes time to delete it.
Minimize `PULL_REQUEST_TEMPLATE.md` boilerplate to avoid lots of noise in the git commit messages.
---
> docs: minimize PULL_REQUEST_TEMPLATE.md

- packages/core/src/shared/filetypes.ts
- packages/core/src/shared/fs/watchedFiles.ts
- packages/core/src/test/shared/filetypes.test.ts
- packages/core/src/test/testUtil.ts
- packages/core/src/testFixtures/workspaceFolder/test.ssm.json
- packages/core/src/testInteg/shared/utilities/workspaceUtils.test.ts
- Pseudo-documents like `foo.git`, `output://…`, and `~/.vscode/argv.json` are included in `ide_editCodeFile` metrics even though they were not actually opened by the user.
- `onDidOpenTextDocument` doesn't correctly represent user activity: it fires for *all* documents opened with `onDidOpenTextDocument()`, which includes all documents/buffers opened for programmatic purposes by application or library code.
- Listen to `onDidChangeActiveTextEditor` instead of `onDidOpenTextDocument`. This represents when a user actually opens a file in the IDE.
- Ignore various "noise" documents.
---
> telemetry: ide_editCodeFile is noisy

- packages/core/src/shared/performance/performance.ts
- packages/core/src/shared/telemetry/spans.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/test/shared/performance/performance.test.ts
- packages/core/src/test/shared/telemetry/spans.test.ts
- packages/core/src/test/utilities/performance.ts
- We currently do a one-shot performance test measurement, which can be be impacted by the underlying cpu
- Run 5 performance tests by default, this should give us a more accurate reading
```
{userCpuUsage: 27.763992642839753, systemCpuUsage: 5.8700764000563925, duration: 0.0488549862, heapTotal: 0.15}
{userCpuUsage: 32.432557472712574, systemCpuUsage: 7.287778251185924, duration: 0.0350972354, heapTotal: 0.15}
{userCpuUsage: 36.17269595509756, systemCpuUsage: 8.190125881726889, duration: 0.0313357906, heapTotal: 0.15}
{userCpuUsage: 23.575720185158513, systemCpuUsage: 5.680905138190308, duration: 0.0468292694, heapTotal: 0.05}
{userCpuUsage: 29.722270663855547, systemCpuUsage: 6.725376761131834, duration: 0.044072017399999996, heapTotal: 0.05}
{userCpuUsage: 30.981420694546227, …
```
> fix(tests): improve reliability of performance tests

- .github/workflows/node.js.yml
- buildspec/linuxE2ETests.yml
- buildspec/linuxIntegrationTests.yml
- buildspec/linuxTests.yml
- codecov.yml
The codecoverage reports are so inconsistent, see if we can tweak their settings
- remove anything related to target, what's reported on the actions is very inconsistent
- patch, changes, and comment were getting flagged by the codecoverage schema. Just set them to false instead 
> ci: tweak codecoverage settings

- .github/workflows/node.js.yml
github CI is not triggered on PRs in the private "staging" repo.
update workflow trigger.
example: https://github.com/aws/aws-toolkit-vscode-staging/pull/1678
---
> ci: run github CI in private repo

- package-lock.json
- packages/amazonq/.changes/next-release/Bug Fix-7386c56a-07b9-4c6e-98f2-4321ec9cea28.json
- packages/amazonq/.changes/next-release/Bug Fix-7ab2c6fa-1678-4834-8edd-80eb2c12953e.json
- packages/core/package.json
New version of MynahUI requires release in vscode.
Release new version of MynahUI with the following bug fixes:
- Fix copy pasting inline code texts https://github.com/aws/mynah-ui/issues/98
- Fix disabled commands not filtered in quick actions
MynahUI v4.15.8 release notes: https://github.com/aws/mynah-ui/releases/tag/v4.15.8
---
> fix(amazonq): Release mynah-ui v 4.15.8 with bug fixes

- .github/workflows/node.js.yml
The notification step of lint-commits fials on master since a pull request is not defined
If the linting isn't in a PR then don't run the notification step
---
> ci(toolkit): Only run issue notification on pull requests

- .github/workflows/lintcommit.js
- .github/workflows/notify.js
- .github/workflows/utils.js
- If a user is using the types feat/fix in the PR title they should also include a changelog item
- Notify them if a changelog item isn't present
---
> ci(toolkit): add github comment for missing changelog item

- packages/amazonq/.changes/next-release/Bug Fix-59842853-a46a-4ffd-b866-e62bec96ad45.json
- packages/core/src/amazonqGumby/chat/controller/controller.ts
Some users provide a symlink when QCT prompts them for a JDK path, and this previously was not being accepted.
Remove part of a conditional check (`isDirectory`, since that is always false for symlinks). This allows users to use symlinks, which will work fine during the local build. Even if someone provides a path that is *not* a directory now, the local build will fail and build error logs will open up for them to debug, as usual.
---
> fix(amazonq): allow symlinks for JDK path

- .github/workflows/lintcommit.js
- .github/workflows/notification.yml
- .github/workflows/notify.js
- .github/workflows/utils.js
Problem:
Since 8e34c5e650f3, `node lintcommit.js test` fails various tests and CI fails for those cases too:
/home/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/.github/workflows/lintcommit.js:80
} else if (!scope && typeScope.includes('(')) {
Solution:
Revert the changes from 8e34c5e650f3. It's good to avoid code duplication, but in this case `parsePRTitle()` is not the right abstraction:
- it doesn't signal failures in a way that is handled by callers
- its return type is awkward (`undefined | string | object`)
- notify.js doesn't actually need `parsePRTitle`, it only needs to check `startsWith()`.
> ci: lintcommit.js regressions

- packages/amazonq/.changes/next-release/Bug Fix-910f825b-6832-42ac-80b4-ffcac58d15c5.json
- packages/amazonq/src/extension.ts
- packages/core/src/auth/auth.ts
- packages/core/src/auth/secondaryAuth.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/shared/errors.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/test/credentials/auth.test.ts
- packages/core/src/test/shared/errors.test.ts
- packages/toolkit/.changes/next-release/Bug Fix-a9d6d04d-f861-49ce-8d08-ff50b3e0bb2b.json
During extension startup, the auth system tries to restore the connection. This may result in a `refreshToken` call. If a network error happens during this, the connection restore fails and no connection is set to active. Then, Amazon Q will clean up any "leftover" connections, including this one, and the user will be completely logged out. The connection is technically valid despite having an expired token, and another call may clear up the network error and allow us to get better token.
The auth system will restore this connection even if it runs into a network error. Then, Amazon Q will display as if its logged in normally. If the network error was one-off, then there is no indication that there was an issue to the user. If there are still network issues, using chat or …
> fix(auth): handle network errors during restore/getChatAuthState

- packages/core/src/amazonq/webview/messages/messageDispatcher.ts
- packages/core/src/amazonq/webview/ui/connector.ts
- packages/core/src/amazonq/webview/ui/main.ts
- packages/core/src/amazonq/webview/webView.ts
- packages/core/src/shared/performance/marks.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- We have no detailed information on how long the amazonq webview took for first meaningful paint
- We have no way to keep track whether or not webviews fail to load or any error events are that emitted
- The onready event gets fired when "UI is initialized and rendered". See https://github.com/aws/mynah-ui/blob/main/docs/PROPERTIES.md#onready
- Listen to error events on the window and forward them to the vscode side
- How long are webviews taking to load?
- How long until they're interactive?
- What errors are occurring in the webview?
TODO:
- tests (if I even can?)
- move webview events to commons repo
---
> telemetry(amazonq): Add webview load metric for amazonq

- packages/core/src/shared/telemetry/spans.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/shared/utilities/workspaceUtils.ts
- packages/core/src/testInteg/globalSetup.test.ts
- packages/core/src/testInteg/shared/utilities/workspaceUtils.test.ts
- Right now we can't really corelate cpuusage to anything because we don't know how big users projects are (file size or total files)
- Add additional metrics for file size and total file count
---
> perf(toolkit): add additional metrics for measuring performance

- packages/amazonq/.changes/next-release/Bug Fix-54ae3b04-fe8b-40e8-866a-7f9f73f3c7cb.json
- packages/core/src/auth/sso/clients.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/shared/errors.ts
- packages/core/src/test/shared/errors.test.ts
- packages/toolkit/.changes/next-release/Bug Fix-48f605af-ae0d-477f-b1bb-1691b64ad96c.json
There were some previous changes that caused the existing implementation of a `SyntaxError` to not be considered a Network Error. And during token refresh we were seeing SyntaxErrors still appearing
Create a single class which wraps a `SyntaxError`, called `AwsClientResponseError`. Under the hood of a SyntaxError is the real error that originates from a failed AWS SDK Client response, this is how we determine if it should be an `AwsClientResponseError`. This new class can only be created if given the correct SyntaxError instance to `AwsClientResponseError.instanceIf()`.
Then we can simply check if an error matches by using `instanceif AwsClientResponseError`
Any existing code that was related to this scenario has all been centralized in to the AwsClientResponseError class.
---
License: I …
> fix(auth): SyntaxError not being considered Network Error

- packages/core/src/auth/auth.ts
- packages/core/src/auth/connection.ts
- packages/core/src/auth/secondaryAuth.ts
- packages/core/src/codecatalyst/activation.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/test/credentials/auth.test.ts
- packages/core/src/test/techdebt.test.ts
We are still getting hits in telemetry for users seeing the split session notification. Adding more fine-grained telemetry to determined if this users are still migrating. This telemetry will also help us track other auth issues.
---
> telemetry(auth): snooze techdebt and add telemetry for evaluation

- packages/core/src/shared/crypto.ts
- packages/core/src/shared/telemetry/activation.ts
- packages/core/src/shared/telemetry/service-2.json
- packages/core/src/shared/telemetry/telemetryClient.ts
- packages/core/src/shared/telemetry/telemetryService.ts
- packages/core/src/shared/telemetry/util.ts
- packages/core/src/test/shared/crypto.test.ts
- packages/core/src/test/shared/telemetry/util.test.ts
I have filtered all the metrics in Kibana by `clientId: "XXXXXX"`, but if they had multiple IDE windows opened at the same time sending metrics I cannot know which window they are coming from since they share the same clientID.
This adds a new field to the telemetry service  called `sessionId` which uniquely identifies a part of the UI in an IDE window. It is adjacent to `clientId`.
Now in my metrics I will be able to differentiate metrics by their sessionID since they both share the same clientId by design.
Changes in the Telemetry service need to be merged before this change can since they update the endpoint to accept this new field.
The updates of this commit only mirror the upstream, so this process is manual.
---
License: I confirm that my contribution is made under the terms of the …
> telemetry: Add `sessionId` to metrics

- packages/amazonq/test/unit/codewhisperer/util/securityScanLanguageContext.test.ts
- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/util/securityScanLanguageContext.ts
Sometimes security issues have a Diagnostic but not SecurityIssueHover issue. This happens when the document's languageId is not enabled when registering the hover/code actions provider.
Update the enabled languageIds for security scans feature.
---
> fix(amazonq): update security scan languages

- packages/amazonq/.changes/next-release/Bug Fix-cf2cb680-6b37-4d51-a34a-5b5f03bd04c4.json
- packages/core/src/amazonqGumby/chat/controller/messenger/messengerUtils.ts
- packages/core/src/codewhisperer/models/constants.ts
We are not showing Linux users the right terminal command they need to find the JDK path we ask for.
Show them the proper instructions.
---
> fix(amazonq): show instructions for finding JDK path on Linux

- packages/amazonq/.changes/next-release/Bug Fix-cf81a6d7-2bc9-4888-9142-ce036245dd0e.json
- packages/amazonq/src/app/chat/activation.ts
Problem: `Start using Amazon Q` can display if there is some error restoring the connection object in the main Auth class. May be a network error or some other error. This is fine because Q uses secondary auth, so it only needs to be restored in that class. However, the notification logic access is in the Auth class which may not be restored.
Solution: Use AuthUtil to check if there is a connection instead of Auth.
---
> fix(amazonq): sign-in notification displaying if user is signed in

- packages/amazonq/.changes/next-release/Feature-0da66e82-7f81-46c7-be39-5634cf0a64f3.json
- packages/core/package.nls.json
- packages/core/src/amazonqFeatureDev/session/sessionState.ts
Currently we display a long-running message "Generating code ... " while in code generation still IN_PROGRESS state. There is an often customer feedback based on this experience that its "stuck" or not "progressing".
Although the RTS and LLM are processing the request, user expects some feedback on whats is doing or if its actually stuck processing.
This PR provides exposure for the codeGenerationStatusDetail which will be leveraged to return the strings in the following format:
LLM actions example returned:
"I have reviewed 7 files and applied changes to 3 files in total so far.
Most recently, I reviewed 2 files and applied changes to 1 file. "
Error scenario while IN_PROGRESS:
"The previous attempt failed. I am retrying now. For reference, the previous 
attempt took approximately 1 …
> feat(dev): include in progress state agent details in code generation

- packages/amazonq/.changes/next-release/Bug Fix-b8b46fa8-b467-4b35-9741-ce6962c8f674.json
- packages/core/src/shared/errors.ts
- packages/core/src/test/shared/errors.test.ts
- packages/toolkit/.changes/next-release/Bug Fix-9ae19be3-32f5-475c-8206-cb82f4ffe30e.json
There is a small edge case where there are SOMETIMES missing fields in a SyntaxError, in this case the $response or its reason field do not exist. Due to this those cases are causing a connection to become invalid when refresh credentials fails.
Handle the case where those fields are missing and gracefully handle them by still marking it as an AwsClientResponseError. Since we cannot extract the underlying error message, we set a custom errors message for those cases.
Now this will not cause a failed refresh credential to invalidate.
---
> fix(auth): handle SyntaxError edge case in refresh credentials

- packages/amazonq/.changes/next-release/Feature-d4728cdd-22be-4255-b5e9-4d897a646782.json
- packages/core/src/amazonq/lsp/lspController.ts
The indexing of @workspace feature is slow.
By upgrading ONNX version from 1.18 to 1.19 in the 0.1.5 LSP, we observed reduction in indexing time by about 50% when using CPU for index. There is no improvement when using GPU or AMD CPU on Windows. There is no customer facing change or customer experience change. 
---
> feat(amazonq): Reduce @workspace indexing time by 50% 

- packages/amazonq/package.json
- packages/core/package.json
- packages/core/src/auth/auth.ts
- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/core/src/shared/errors.ts
- packages/core/src/shared/settings-amazonq.gen.ts
- packages/core/src/shared/settings-toolkit.gen.ts
- packages/core/src/shared/settings.ts
- packages/core/src/shared/utilities/cacheUtils.ts
- packages/core/src/test/shared/errors.test.ts
- packages/toolkit/package.json
When we get SSO cache errors, such as a failed write, we do not want to
invalidate the connection. Instead we want to gracefully handle this similar
to network errors, since the connection can still be recovered on a subsequent
token refresh.
A place that this happens is during SSO token refresh. Where if there is a filesystem
error when writing the new token to disk, the connection will become invalid.
Catch sso cache errors and wrap them in a high level `DiskCacheError` so
that we can easily determine an sso cache error during token refresh. Then we can
know not to invalidate the connection when there is a cache error since `isRecoverableError()` will
catch the error.
Additionally a message is shown to the user explaining how the sso token refresh failed and guides
them to the logs in …
> fix(auth): File System error during SSO token refresh expires session

- CONTRIBUTING.md
- packages/core/src/extensionNode.ts
- packages/core/src/lambda/commands/createNewSamApp.ts
- packages/core/src/lambda/commands/deploySamApplication.ts
- packages/core/src/lambda/local/debugConfiguration.ts
- packages/core/src/shared/logger/activation.ts
- packages/core/src/shared/logger/index.ts
- packages/core/src/shared/logger/logger.ts
- packages/core/src/shared/logger/winstonToolkitLogger.ts
- packages/core/src/shared/sam/cli/samCliInvoker.ts
- packages/core/src/shared/sam/cli/samCliLocalInvoke.ts
- packages/core/src/shared/sam/debugger/csharpSamDebug.ts
- packages/core/src/shared/sam/debugger/goSamDebug.ts
- packages/core/src/shared/sam/debugger/typescriptSamDebug.ts
- packages/core/src/shared/sam/localLambdaRunner.ts
- packages/core/src/shared/utilities/cliUtils.ts
- packages/core/src/test/globalSetup.test.ts
Currently we use `getLogger()` for all log messages.
`getLogger()` takes a type input, indicating one of three logger types: 'channel', 'debugConsole', and 'main'.
- The `channel` type is out dated and no longer carries meaning. Might even confuse other developers if they come across this.
- The `debugConsole` type logging calls are only used in SamCLI, we shouldn’t complicate a very popular interface with something so specific and rarely used. 
- It's discovered in implementation that the current `debugConsole` is not printing to IDE's debug console, this is fixed in one of the commits. 
This change is also a pre-rec of the following project:
https://quip-amazon.com/B4hTAcZSsGXF/VSC-Better-Logging-With-Headers
1. The `channel` type should be removed, converting existing calls into `main` …
> refactor(logging): removed types input in getLogger()

- packages/core/src/shared/errors.ts
- packages/core/src/test/shared/errors.test.ts
These showed up in telemetry during `aws_refreshCredentials`
---
> fix(auth): add more errors to `isNetworkError()`

- packages/core/src/codewhisperer/service/diagnosticsProvider.ts
- packages/core/src/codewhisperer/views/securityIssue/vue/root.vue
Dead links to detector library for some findings.
Use detector library url from the server response instead of building it from the client.
---
> feat(amazonq): use detector library url from server

- package-lock.json
- packages/amazonq/.changes/next-release/Bug Fix-cedd6c55-8a91-432e-87a0-1832248b9e7e.json
- packages/core/package.json
In the latest VSCode IDE, Amazon Q Chat inline code block items are not aligned with the texts.
Implemented a solution through a [mynah-ui update](https://github.com/aws/mynah-ui/releases/tag/v4.15.9) which specifically adjusts the inline code block items to align in the middle.
---
> fix(amazonq): Inline code blocks are not aligned with text

- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/core/src/shared/errors.ts
- packages/core/src/test/codewhisperer/commands/startSecurityScan.test.ts
- packages/core/src/test/shared/errors.test.ts
- packages/core/src/test/shared/telemetry/spans.test.ts
In telemetry we sometimes add the error message to the `reasonDesc` field.
Additionally when using `getTelemetryReasonDesc()` it will recurse through the causal
chain of the error and return a value composed of all the error messages.
Eg: `Reason A | Reason B | Reason C`
The issue is that the nested errors may have useful context (in addition to the message) in their
id (code or name). And currently this is lost.
Prepend the code/name to the error messages when using `getTelemetryReasonDesc()`
Eg: `CodeA: Reason A | CodeB: Reason B | NameC: Reason C`
---
> refactor(telemetry): prepend the error code/name to the `reasonDesc` field

- packages/amazonq/test/unit/codewhisperer/util/editorContext.test.ts
- packages/core/src/codewhisperer/util/editorContext.ts
Inline completion quality can be improved by passing the relative path instead of file name. 
In the inline API request payload, we send relative path instead of file name.
No user facing change log item is added. The service controls what is sent for generation, this change will not have immediate customer impact.
---
> feat(amazonq): switch to relative path for inline Completion API field

- packages/amazonq/.changes/next-release/Feature-8fc46bec-9ca5-4544-85dc-a71e0dee1b82.json
- packages/core/src/amazonq/lsp/lspClient.ts
- packages/core/src/amazonq/lsp/lspController.ts
In current build, when workspace index expires, the IDE rebuild index for all files, which is slow. 
Whenever the current index is out of date, the IDE rebuild index for only the files that are changed since last index. 
Meanwhile, this change will also make the index refresh mush faster. New index will be created and refreshed if the existing index is more than 12 hours old.
---
> feat(amazonq): workspace indexing only applies to new files that are changed

- packages/core/src/codewhispererChat/controllers/chat/telemetryHelper.ts
There is a discrepancy between STE telemetry and toolkit telemetry in terms of field `cwsprChatHasProjectContext` in 
`AmazonqAddMessage`.
Use same boolean field for `cwsprChatHasProjectContext`
---
> fix(amazonq): fix chat project context telemetry discrepancy

- packages/core/src/auth/auth.ts
- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/core/src/shared/errors.ts
- packages/core/src/shared/utilities/cacheUtils.ts
- packages/core/src/test/shared/errors.test.ts
The original implementation of DiskCacheError can be simplified and still achieve it's original purpose.
During token refresh we eventually write to the disk cache. Sometimes this process fails due to filesystem errors.
We dont need to care about the actual file system error, but only that the error came during a DiskCache operation (i.e when it attempts to save the token to disk)
So instead, at the root of where the disk cache errors ocurr, we will wrap caught errors in a DiskCacheError.
This adds context to the error and allows anything upstream to specifically check for that context, instead of needing to parse the error to see if it was filesystem related.
Additionally not all file system errors were guaranteed to come from the disk cache, so this change allows us to target the right …
> refactor(auth): redo `DiskCacheError` with proper context

- package-lock.json
The vulnerabilities include:
```
body-parser  <1.20.3 - body-parser vulnerable to denial of service when url encoding is enabled
express  <=4.19.2 || 5.0.0-alpha.1 - 5.0.0-beta.3
path-to-regexp  <=0.1.9 || 0.2.0 - 1.8.0 || 4.0.0 - 6.2.2 - path-to-regexp outputs backtracking regular expressions
node_modules/@koa/router/node_modules/path-to-regexp
node_modules/express/node_modules/path-to-regexp
node_modules/path-to-regexp
send  <0.19.0
send vulnerable to template injection that can lead to XSS
node_modules/send
serve-static  <=1.16.0
Depends on vulnerable versions of send
node_modules/serve-static
```
Just run `npm audit fix`. It doesn't look like there's any top level dependency changes. It looks like its all related to [express](https://github.com/expressjs/express), which is used for …
> deps(dependencies): Address high-severity vulnerabilities by updating dependencies 

- packages/core/package.json
- When you build the project amazonQSessionConfigurationMessage and ssoCacheError get removed from the amazon q package.json
- Add them into core, which makes sure they get copied to the package.json of amazonq
---
> fix(core): Add missing amazonq.supressPrompts

- .github/dependabot.yml
This attempts to fix our dependabot issue but I am not sure what the best way to test this is other than committing it and seeing what happens.
Problem (as I understand it, may be incorrect): Dependabot wants to update deps in src.gen/, but this is managed separately and can cause things to break. There is no exclude dirs option in dependabot. So, we limit the dependabot to packages/core only which doesn't paint the full picture of all of our dependencies AND since this is a monorepo where the package-lock.json lives in the root, it cannot be updated. This effectively bricks dependabot and makes the PRs nothing more than a reminder.
Solution: Use this 'workaround' to exclude a directory so that dependabot can update the deps of all of our subprojects and the root directory without …
> ci: make dependabot work on all projects except src.gen/

- packages/core/src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
- This test started failing around sept 10th with no clear code change
- https://github.com/aws/aws-toolkit-vscode/issues/5587
- Until we can figure out the problem lets just disable it on mac ci
---
> ci(core): skip "target=code: typescript" test on mac ci

- packages/core/src/awsService/redshift/explorer/redshiftNode.ts
- packages/toolkit/.changes/next-release/Bug Fix-7abe66a9-111f-4507-8129-48b460819095.json
Customer not able to list the provisioned clusters in region where serverless API's not present.
Solution
Made a minor code change to fix the issue. Tested the change too.
---
> feat(redshift): bug fix for regions which do not support serverless API

- packages/amazonq/.changes/next-release/Bug Fix-bab65b05-77c0-4a6d-ae51-4af37160d957.json
- packages/amazonq/.changes/next-release/Bug Fix-cf363600-c0a7-4a4e-b5da-79e968d01f93.json
- packages/core/src/auth/auth.ts
- packages/core/src/auth/connection.ts
- packages/core/src/auth/secondaryAuth.ts
- packages/core/src/auth/sso/cache.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/login/webview/vue/amazonq/backend_amazonq.ts
- packages/core/src/login/webview/vue/backend.ts
- packages/core/src/login/webview/vue/toolkit/backend_toolkit.ts
- packages/toolkit/.changes/next-release/Bug Fix-511c0b65-6f7b-4c1a-a0c5-616c3ec802f4.json
Problem: Users can open multiple VSC sessions. If they sign out or the connection is lost in another window, then interacting with chat or in-line suggestions in the original window will only produce cryptic "Profile does not exist" errors, with no clear way to get back to a working state.
Solution: Log out once this state is detected (uses chat, invokes manual or auto inline suggestion).
3 commits:
[fix(amazonq): user stays signed in if they log out in other windows](https://github.com/aws/aws-toolkit-vscode/pull/5547/commits/270a321071d6523ca04b4f59a0fdf5378cf57570)
Problem: Users can open multiple VSC sessions. If they sign out or the connection is lost in another window, then interacting with chat or in-line suggestions in the original window will only produce cryptic "Profile does …
> fix(auth): login state updates across windows

- package-lock.json
- packages/amazonq/.changes/next-release/Bug Fix-88f06153-eaf2-4d50-9934-e5d1044aa2e9.json
- packages/amazonq/.changes/next-release/Bug Fix-b116896a-a7d1-445b-bd6a-5d2e82fe336a.json
- packages/core/package.json
New version of MynahUI requires release in vscode.
Release new version of MynahUI with the following bug fixes:
- Fix shifted chat contents
- Fix tooltip remaining on screen after closing and opening chat panel: https://github.com/aws/aws-toolkit-vscode/issues/5535
MynahUI v4.15.10 release notes: https://github.com/aws/mynah-ui/releases/tag/v4.15.10
Also fixed a regression in the following MynahUI v4.15.11
Release notes: https://github.com/aws/mynah-ui/releases/tag/v4.15.11
---
> fix(amazonq): fix chat contents

- packages/core/src/shared/performance/performance.ts
- packages/core/src/test/codewhisperer/commands/startSecurityScan.test.ts
- packages/core/src/testInteg/shared/utilities/workspaceUtils.test.ts
We are currently running performance tests without waiting for the cpu to recover. This could be part of the reason why our tests could be flaky.
These were suggestions made by George on Friday
Wait until the the cpu usage is at a reasonable (determined using previous test runs) starting cpu usage before continuing on with the tests
---
> ci(core): Seperate setup, execution, and verification of performance tests

- packages/amazonq/.changes/next-release/Bug Fix-239f62a8-0e2a-42f8-a028-ef1639bac4c5.json
- packages/core/src/codewhisperer/models/model.ts
- Issue with loading icon in the status bar menu.
- Replaced previous icon with relevant loading icon.
- Did not update any logic in the PR, its just a UI icon change so adding/updating tests is not considered.
---
> fix(amazonq): Replacing the loading icon in the status bar menu.

- packages/amazonq/.changes/next-release/Feature-3a97670a-e801-44a6-812e-37e2f68516fc.json
- packages/core/src/amazonq/lsp/lspController.ts
1. When filename is in the query, chat can not resolve to that file context.
Upgrade LSP to 0.1.9 to fix above 2 use cases.
---
> feat(amazonq): Support @workspace queries for specific files like `@workspace what does test.ts do? `. 

- packages/core/package.json
- packages/toolkit/.changes/next-release/Bug Fix-35f330d2-90f9-468c-8723-40ec8f4f1cfc.json
Gives option to copy instance id on non-instance node. 
Leads to error: 
Only give this option on ec2InstanceNodes
---
> fix(ec2): don't allow user to copy instance id from parent ec2 node. 

- packages/amazonq/test/unit/codewhisperer/util/authUtil.test.ts
- packages/core/src/auth/auth.ts
- packages/core/src/auth/secondaryAuth.ts
- packages/core/src/shared/utilities/mementos.ts
- packages/core/src/test/credentials/secondaryAuth.test.ts
As part of our design we intentionally separate the Auth state between a local environment, versus a remote (ssh'd) one. We do this so that if the user has 2 IDE instances, one local and the other remote, if one changes its auth state the other one will not be affected.
The reason for separating auth that I can remember is due to how we store the actual tokens on disk. Because the remote does not have access to the disk of the local, we need to ensure the remote operates its auth independently of the local auth.
By design globalState is shared by both local and remote instances. So for local we need to ensure we do not use the base globalState, otherwise the same Auth state as the remote will be used.
The problem, SecondaryAuth is not doing this for all cases. It is using the globalState …
> fix(amazonq): Use the correct state for Q in remote environment

- packages/core/src/shared/errors.ts
- packages/core/src/shared/logger/activation.ts
- packages/core/src/shared/logger/logger.ts
- packages/core/src/shared/logger/sharedFileTransport.ts
- packages/core/src/shared/logger/toolkitLogger.ts
- packages/core/src/shared/logger/winstonToolkitLogger.ts
- packages/core/src/test/shared/logger/activation.test.ts
- packages/core/src/test/shared/logger/toolkitLogger.test.ts
- packages/core/src/test/testLogger.ts
- packages/core/src/testInteg/globalSetup.test.ts
Log message can appear in output channels(such as Amazon Q Logs as shown), IDE Debug console, or write to pre-defined log file destinations. They come from all parts of our services and can amount to large and lengthy chunks quickly.
We don’t have a reliable way to identify log messages from various services and modules of our product. Some messages might have headers while others don’t, and the existing headers are hard-coded on a message by message basis, with no checks for consistency. 
1. It’s difficult to locate and trace unidentified log messages when the size of logs grow quickly.
2. Without regulation, the hard-coded custom headers can lead to legacy issues down-the-road and inconsistencies within the codebase.
1. Make message topic identifiers an input variable of the getLogger() …
> feat(logging): topic header for logs

- packages/core/src/shared/telemetry/spans.ts
- packages/core/src/shared/telemetry/telemetry.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/test/shared/telemetry/spans.test.ts
- We can't see an e2e view of our events
- Implement telemetry tracing using the opentelemetry idea of trace ids.
- A trace id helps create a collection of spans.
- Only one trace id can be active in an execution flow at a time.
- Additionally, it swaps parentMetric for parentId so that we can directly correlate one telemetry event to another
- A trace is associated with a top level telemetry event. The top level can be either event_trace or any other of our metrics. 
---
> telemetry(core): implement tracing

- packages/core/src/shared/sshConfig.ts
- packages/toolkit/.changes/next-release/Bug Fix-7e333959-58a0-48ff-9368-888735328bf2.json
Occasionally this error pops up: 
Add one line to ssh config that force agent to use the provided key. 
- `IdentitiesOnly yes`: only use identity file provided. 
More info here: https://www.ssh.com/academy/ssh/config
---
> fix(ec2): ssh config forces use of supplied keys

- packages/core/src/awsService/ec2/sshKeyPair.ts
- packages/core/src/test/awsService/ec2/sshKeyPair.test.ts
- packages/toolkit/.changes/next-release/Feature-3bebe8f2-b933-4104-8dd6-013d738bd6b5.json
currently use RSA.
switch to ed25519
---
> feat(ec2): switch to using ed25519 to generate key pair

- packages/core/package.json
- packages/core/package.nls.json
- packages/core/src/extensionNode.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/stepFunctions/workflowStudio/activation.ts
- packages/core/src/stepFunctions/workflowStudio/types.ts
- packages/core/src/stepFunctions/workflowStudio/workflowStudioEditor.ts
- packages/core/src/stepFunctions/workflowStudio/workflowStudioEditorProvider.ts
ASL files, represented as *.asl.json and *.asl.yaml, are rendered using the default JSON editor
Use existing SFN visual custom editor in VSCode to render ASL files in a visual builder, similar to how it would be displayed in SFN console in create/edit modes.
Current pull request is a tracer bullet implementation without support for local file editing - this functionality will be added in the following changes 
---
> feat(stepfunctions): Custom editor to view and edit ASL files - tracer bullet

- docs/telemetry.md
- packages/core/src/shared/telemetry/spans.ts
- packages/core/src/test/shared/telemetry/spans.test.ts
- We have no way to connect disjoint events that may or may not be in a telemetry span
- Add withTraceId, which allows you to start a new trace with a specific id
- Update the telemetry docs
This a pre-req to https://github.com/aws/aws-toolkit-vscode/pull/5566 and another codewhisperer telemetry PR
---
> telemetry(core): Add withTraceId function for improved tracing

- packages/amazonq/.changes/next-release/Bug Fix-385bc912-dc06-4b16-91ae-47fa1c586367.json
- packages/amazonq/test/unit/codewhisperer/service/securityScanHandler.test.ts
- packages/core/src/codewhisperer/service/securityScanHandler.ts
Hardcoded credentials detections are being removed from auto scan results due to line string comparison with the server response which contains redacted code.
For redacted code, check only the line length instead of a full comparison.
---
> fix(amazonq): issues with redacted code are hidden

- packages/core/src/awsService/ec2/sshKeyPair.ts
- packages/core/src/test/awsService/ec2/sshKeyPair.test.ts
- packages/toolkit/.changes/next-release/Feature-5ca56f55-9d01-40bd-86e8-bcb8a776c4d8.json
(title)
Try to use `ed25519` first, if it fails use `rsa`. Alternatively, we could use the same code to check if version number of ssh, and then see if its above version 6.5 (https://www.openssh.com/releasenotes.html#6.5). However, doing an actual attempt at generating the keys felt more robust, as it could potentially fail for other reasons. Make use of the code here: 
https://github.com/aws/aws-toolkit-vscode/blob/791ae55021c0ee73dd84abaa57da46237d0fb0d5/packages/core/src/shared/utilities/pathFind.ts#L117-L134
---
> feat(ec2): default to ed25519 key type, but fall back on rsa

- packages/core/src/amazonq/messages/chatMessageDuration.ts
- packages/core/src/amazonq/util/eventRecorder.ts
- packages/core/src/amazonq/webview/messages/messageDispatcher.ts
- packages/core/src/amazonq/webview/ui/apps/cwChatConnector.ts
- packages/core/src/amazonq/webview/ui/connector.ts
- packages/core/src/amazonq/webview/ui/main.ts
- packages/core/src/amazonq/webview/ui/messages/handler.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/controllers/chat/model.ts
- packages/core/src/codewhispererChat/view/connector/connector.ts
- packages/core/src/codewhispererChat/view/messages/messageListener.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/shared/utilities/map.ts
- We can't measure e2e how long a chat request takes
- Plumb the trace id through to the webview -> vscode -> webview. This allows us to know exactly what is happening to a message and how long everything took to get there
- chat e2e latency can be linked with the other telemetry events via the traceId
<details closed>
<summary>Previous PR description</summary>
This is just a draft of what we could potentially do to measure e2e latency in amazon q chat message requests. Feel free to leave comments on the PR
- It's hard to connect a tab id to a conversation id. Tab ID's exist pretty much to send/receive messages but they don't really live along side conversation id's. Conversation id's are exclusively related to the session. The only place they meetup is in their chat session storages
- Do …
> telemetry(amazonq): measure e2e latency for amazon q requests

- packages/amazonq/test/unit/codewhisperer/service/telemetry.test.ts
- packages/amazonq/test/unit/codewhisperer/tracker/lineTracker.test.ts
- packages/amazonq/test/unit/codewhisperer/util/closingBracketUtil.test.ts
- packages/amazonq/test/unit/codewhisperer/util/codeParsingUtil.test.ts
- packages/amazonq/test/unit/codewhisperer/util/crossFileContextUtil.test.ts
- packages/amazonq/test/unit/codewhisperer/util/editorContext.test.ts
- packages/core/src/test/amazonq/common/contentController.test.ts
- packages/core/src/test/shared/utilities/editorUtilities.test.ts
- packages/core/src/test/testUtil.ts
- packages/core/src/testInteg/stepFunctions/init.test.ts
- packages/core/src/testInteg/stepFunctions/visualizeStateMachine.test.ts
Problem:
Redundant code, suboptimal names and docstrings.
Solution:
- Introduce `toTextDocument` for tests such as `codeParsingUtil.test.ts` which don't need a TextEditor.
- Rename `openATextEditorWithText` => `toTextEditor`.
---
> refactor(test): toTextDocument, toTextEditor

- packages/amazonq/.changes/next-release/Feature-cd5797a0-6460-4fc6-b3f7-47f55f9bf163.json
- packages/core/src/amazonqGumby/chat/controller/controller.ts
Revert https://github.com/aws/aws-toolkit-vscode/pull/5607 by not showing users the skip tests form
Above
---
> revert(amazonq): skip showing users unit test form

- packages/core/src/shared/logger/logger.ts
- packages/core/src/test/globalSetup.test.ts
- packages/core/src/test/shared/logger/toolkitLogger.test.ts
Problem:
Regression b2ebc10342f63 in the logger: `debug('%s %s', foo, bar')` sends `foo, bar` as a single `[foo, bar]` list to the first `%s`. Example:
2024-09-26 12:18:29.631 [debug] getClientId: determined clientId as: [
'96be923b-a00d-46d4-add1-c877abfcb01c',
undefined,
'96be923b-a00d-46d4-add1-c877abfcb01c'
], process.env clientId was: { logID: 1 }, stored clientId was: %s
Solution:
Spread the args when passing to sendToLog().
> fix(logging): logger functions do not handle varargs

- packages/amazonq/package.json
- packages/core/src/codewhispererChat/controllers/chat/userIntent/userIntentRecognizer.ts
Command and context menu item for unit test generation was disabled for internal users before last release. We are ready to enable now.
This PR enables the context menu item and commands for unit test generation.
---
> feat(amazonq): Re-enable generate unit tests command and context menu item

- packages/core/src/awsService/ec2/explorer/ec2ParentNode.ts
- packages/core/src/test/techdebt.test.ts
The issue is here: https://github.com/aws/aws-toolkit-vscode/blob/9eea1f3700930df79620ef26ff6a43450e593580/packages/core/src/awsService/ec2/explorer/ec2ParentNode.ts#L55-L64
This fires off multiple asynchronous calls on each child, with the function returning before any are resolved. Thus, the child node could be deleted from the set after this function returned (potentially when another piece of code is using it). This leads to `undefined` errors within that function. 
Refactor the code to make use of a `for...of` with `await` pattern. 
---
> test(ec2): fix flaky tests regarding child node updates. 

- packages/core/src/login/webview/vue/base.css
- packages/core/src/login/webview/vue/login.vue
- packages/core/src/login/webview/vue/reauthenticate.vue
- packages/core/src/login/webview/vue/selectableItem.vue
make auth container responsive
https://github.com/user-attachments/assets/d38db517-4734-435f-8100-b6a65d502c75
https://github.com/user-attachments/assets/17b579e1-003f-42aa-967e-7565e66624f0
https://github.com/user-attachments/assets/2cd8754d-6707-4cd4-a250-7b28a0cd7de5
> fix(auth): make view container responsive

- packages/core/src/shared/performance/performance.ts
- packages/core/src/shared/telemetry/spans.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/shared/utilities/workspaceUtils.ts
- packages/core/src/test/shared/telemetry/spans.test.ts
- packages/core/src/testInteg/shared/utilities/workspaceUtils.test.ts
- withPerformance was an experiment to see if we could correlate cpu/memory with number of files
- Cpu usage/memory usage in the extension host is way too volitile so we might as well clean up this code
---
> refactor(core): Remove trackPerformance from telemetry

- packages/core/src/test/awsService/accessanalyzer/iamPolicyChecks.test.ts
There is a test from recent PR that is incorrect given current structure. Ex. https://github.com/aws/aws-toolkit-vscode/actions/runs/11149044046/job/30987024464
Using `globals.context.asAbsolutePath` will prepend `toolkit` to the path, whereas we want to look in `core` for this file. 
- Manually construct the path to be checked. 
---
> fix(test): fix failing IAMPolicy check test

- packages/core/src/amazonqFeatureDev/client/featureDev.ts
- `/dev` conversation would got terminated by retry-able errors, since we disabled the default retry.
- Re-enable the default to prevent `/dev` from terminated by transient/retry-able errors.
---
> config(dev): re-enable Q dev API retry for read APIs

- packages/core/src/codewhisperer/tracker/codewhispererCodeCoverageTracker.ts
Product thinks that code percentage event should not consider user modification
use raw accepted token count (without considering modification) for the percentage field in toolkit telemetry
there is no change to STE
---
> telemetry(amazonq): change code percentage event to not consider modification for toolkit telemetry

- packages/amazonq/src/extension.ts
- packages/core/src/extension.ts
- packages/core/src/shared/handleUninstall.ts
Do not trigger uninstall when extension auto-updates
> fix(amazonq): do not trigger uninstall when extension auto-updates

- packages/core/src/awsService/apprunner/wizards/apprunnerCreateServiceWizard.ts
- packages/core/src/awsService/apprunner/wizards/codeRepositoryWizard.ts
- packages/core/src/awsService/apprunner/wizards/imageRepositoryWizard.ts
- packages/core/src/extension.ts
- packages/core/src/lambda/commands/createNewSamApp.ts
- packages/core/src/lambda/wizards/samDeployWizard.ts
- packages/core/src/lambda/wizards/samInitWizard.ts
- packages/core/src/shared/constants.ts
- packages/core/src/shared/debug/launchConfiguration.ts
- packages/core/src/shared/extensionUtilities.ts
- packages/core/src/shared/sam/sync.ts
- packages/core/src/shared/ui/buttons.ts
We have some strings that need to resolve a url depending on c9 vs toolkit.
The isCloud9() function is causing issues in the constants file. Due to some sort of module import order, isCloud9() did not resolve appropriately when expected. I think we used the constants file before all the dependencies of the isCloud9() function were available
The constants file should be a minimal module with as little external dependencies as possible.
Move the resolution of c9 vs toolkit docs to an external function. Update uses everywhere.
---
> refactor(urls): Remove isCloud9 from constants file

- package-lock.json
- package.json
- packages/amazonq/test/unit/amazonqFeatureDev/util/files.test.ts
- packages/core/src/amazonqFeatureDev/util/files.ts
- packages/core/src/amazonqFeatureDev/util/telemetryHelper.ts
- packages/core/src/auth/secondaryAuth.ts
- packages/core/src/shared/telemetry/index.ts
- packages/core/src/shared/telemetry/spans.ts
- packages/core/src/shared/telemetry/telemetry.ts
- packages/core/src/shared/vscode/commands2.ts
- packages/core/src/test/shared/telemetry/spans.test.ts
- packages/core/src/threatComposer/threatComposerEditor.ts
- packages/core/src/threatComposer/threatComposerEditorProvider.ts
- Theres quite a few missues of telemetry.foo.record inside of the codebase and it can be confusing for external contributors
- Clean up the telemetry interface by only allowing record/increment on spans
---
> refactor(telemetry): Remove telemetry.foo.record

- packages/core/src/stepFunctions/utils.ts
In the recent refactor (https://github.com/aws/aws-toolkit-vscode/pull/5689), there is a mismatch in args between our fs and fs-extra. Not caught until integ tests were run. 
have default write file method ignores encoding since it uses utf8 anyway. 
---
> fix(test): fix failing integ tests. 

- packages/core/src/test/amazonqFeatureDev/prepareRepoData.test.ts
Last PR: https://github.com/aws/aws-toolkit-vscode/pull/5670 was not rebased onto https://github.com/aws/aws-toolkit-vscode/commit/a386cc389787e385db82924b4fa8ce94b04dfe4a, so did not include relevant telemetry changes. Therefore tests passed until the merge happened. 
change type signature to reflect telemetry changes. 
---
> fix(test): rebase test w/ new telemetry

- packages/amazonq/.changes/next-release/Bug Fix-3f76aff8-1622-4647-aafe-3210cf0c3b74.json
- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/login/webview/vue/amazonq/backend_amazonq.ts
- packages/core/src/test/shared/credentials/userCredentialsUtils.test.ts
Problem:
If Toolkit fails to start, then Q will also fail to start:
2024-10-01 09:56:13.188 [error] aws.amazonq.refreshConnectionCallback: [
[TypeError: Cannot read properties of undefined (reading 'getApi')
at c:\…\dist\src\extensionNode.js:6093:284
Solution:
Check for undefined `exports`.
> fix(startup): Q may fail if Toolkit fails

- packages/core/src/awsService/cloudWatchLogs/activation.ts
- packages/core/src/awsService/cloudWatchLogs/commands/tailLogGroup.ts
- packages/core/src/awsService/cloudWatchLogs/liveTailLogStreamSubmenu.ts
- packages/core/src/shared/constants.ts
- packages/core/src/test/awsService/cloudWatchLogs/commands/tailLogGroup.test.ts
- packages/core/src/test/awsService/cloudWatchLogs/liveTailLogStreamSubmenu.test.ts
- packages/toolkit/package.json
CWL is planning on supporting a LiveTail experience in AWSToolkit for VSCode
Registers `aws.cwl.tailLogGroup` as a recognized command in AWS Toolkit. 
In this PR, running this command will simply take the user through a Wizard to collect the configuration for the tailing session, and logs it.
In follow up PRs, I will take this Wizard input and use it to call CWL APIs and output streamed LogEvents to a TextDocument. 
This command will be able to be executed in the command pallet, or by pressing a "play button" icon when viewing LogGroups in the CloudWatch Logs explorer menu. 
---
> feat(cwl): Initialize TailLogGroup command with Wizard

- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/shared/utilities/workspaceUtils.ts
- packages/core/src/testInteg/shared/utilities/workspaceUtils.test.ts
- Follow up on the previous remove trackPerformance PR, we no longer need collectFiles telemetry since the data isn't reliable in the extension host
- integ tests are failing because of this
- Remove the instrumentation
> refactor(amazonq): Remove collectFiles instrumentation

- packages/core/src/amazonq/messages/chatMessageDuration.ts
- packages/core/src/amazonq/util/eventRecorder.ts
- packages/core/src/amazonq/webview/messages/messageDispatcher.ts
- packages/core/src/amazonq/webview/ui/apps/cwChatConnector.ts
- packages/core/src/amazonq/webview/ui/commands.ts
- packages/core/src/amazonq/webview/ui/connector.ts
- packages/core/src/amazonq/webview/ui/followUps/handler.ts
- packages/core/src/amazonq/webview/ui/main.ts
- packages/core/src/amazonq/webview/ui/messages/handler.ts
- packages/core/src/amazonq/webview/ui/quickActions/handler.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/controllers/chat/model.ts
- packages/core/src/codewhispererChat/controllers/chat/telemetryHelper.ts
- packages/core/src/codewhispererChat/view/connector/connector.ts
- packages/core/src/codewhispererChat/view/messages/messageListener.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- It's not clear what's meant by cwsprChatTimeToFirstChunk, cwsprChatTimeBetweenChunks, cwsprChatFullResponseLatency
- We don't have any client latency metrics
- Clarify the descriptions of cwsprChatTimeToFirstChunk, cwsprChatTimeBetweenChunks, cwsprChatFullResponseLatency
- Implement cwsprTimeToFirstDisplay, cwsprChatTimeBetweenDisplay, cwsprChatFullDisplayLatency metrics
- Instead of instrumenting everything via a traceId instead use the tabId as the unique identifier and store a traceId when we get it inside of the uiEventRecorder. That way we can associate events from a tab to the trace without needing to pass the trace around the entire application.
- Lock stopChatMessageTelemetry on the tabId just in case something calls that twice for the same event
- All flows from start of chat …
> telemetry(amazonq): Add client latency metrics for amazon q chat

- packages/core/src/awsService/ec2/sshKeyPair.ts
- packages/core/src/test/awsService/ec2/sshKeyPair.test.ts
Follow up: https://github.com/aws/aws-toolkit-vscode/pull/5578#discussion_r1769231182
`isDeleted` status is determined by looking at the actual file system, rather than maintaining additional state
---
> refactor(ec2): avoid unnecessary state in sshKeyPair

- packages/core/src/amazonqFeatureDev/client/featureDev.ts
- The API connection was timing out after 120 seconds, leading to a poor customer experience (CX). Users were waiting for 2 minutes before receiving a timeout error, which is an unacceptably long wait time.
- Adjust the API connection timeout to 10 seconds, which is approximately 3 times the high band of the API's P99 latency.
- This change should improve the user experience by failing fast in case of connection issues.
---
> config(dev): adjust API connection timeout

- packages/toolkit/.changes/next-release/Bug Fix-d8111f1d-c5f8-48ee-9b25-6d64a98bc3c2.json
- packages/toolkit/README.md
After renaming Application Composer to Infrastructure Composer, we need to update the animate graph in Toolkit/README
update the animate graph in Toolkit/README
---
> fix(infracomposer): update animate graph for infraComposer in toolkit README

- packages/amazonq/.changes/next-release/Feature-294f0da4-1fb4-43c9-90f2-e066d7351c3c.json
- packages/core/src/amazonq/lsp/lspController.ts
If the customer machine is already under heavy CPU load, the @ workspace indexing can cause slowness.
When the user's OS is under heavy load, we pause the @ workspace  indexing and resumes when it is low. This is to avoid slowing down customer's device. 
---
> feat(amazonq): Automatically pause and resume @workspace indexing when OS CPU load is high

- packages/amazonq/.changes/next-release/Bug Fix-55ef93ff-1589-41bc-a482-ed09002f1fd9.json
- packages/core/package.nls.json
- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/amazonqFeatureDev/errors.ts
- packages/core/src/amazonqFeatureDev/util/upload.ts
- Upload url would expire in a given time. The original error message is not clear for users what to do next.
- Handle URL expiry explicitly.
- Add a clear error message.
---
> fix(dev):  add error messages for upload URL expiry

- packages/amazonq/.changes/next-release/Bug Fix-dd58d9cb-4fb4-4cb3-a9a2-dc5c5462e529.json
- packages/amazonq/test/unit/amazonqFeatureDev/session/session.test.ts
- packages/core/src/amazonq/webview/ui/apps/featureDevChatConnector.ts
- packages/core/src/amazonq/webview/ui/connector.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/messenger/messenger.ts
- packages/core/src/amazonqFeatureDev/session/session.ts
- packages/core/src/amazonqFeatureDev/session/sessionState.ts
- packages/core/src/amazonqFeatureDev/types.ts
- packages/core/src/amazonqFeatureDev/views/actions/uiMessageListener.ts
- packages/core/src/amazonqFeatureDev/views/connector/connector.ts
- packages/core/src/test/amazonqFeatureDev/controllers/chat/controller.test.ts
- packages/core/src/test/amazonqFeatureDev/session/sessionState.test.ts
We currently only support accessing the last code generated (by the Tree view). If you try open the diff view in past history, will thrown an error. This happens because when we click on past history Tree we actually send a "newer" uploadId and didn't keep track of all the past ones.
Cache those uploadIds based on codeGenerationId which can be easily accessible while clicking in past views.
---
> fix(dev): Allow user access history diff generated along iterations

- packages/amazonq/.changes/next-release/Bug Fix-0d324321-bddd-4f93-80c4-80978930f157.json
- packages/core/src/amazonqFeatureDev/session/sessionState.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
When customer use workspaces to generate files, RTS and LLM cannot decide which folder to deliver the generated file. We're for now tracking how many times we reach for accountability and prioritization.
Add telemetry to count and save the conversationIds that reach this specific workspace usage.
PS: This is should only be included in VS Code since the Workspaces capability its only used here.
---
> telemetry(dev): add tracking for empty path file scenario

- packages/amazonq/.changes/next-release/Bug Fix-5576420e-6db2-4045-a99f-afced496da0f.json
- packages/amazonq/.changes/next-release/Feature-5576420e-6db2-4045-a99f-afced496da0f.json
- packages/core/src/amazonq/lsp/lspController.ts
Current LSP start is coupled with vector index creation, this should be decoupled. We will be having new releases in the LSP to build some other indexes for everyone very soon ( not computation expensive as vector index), therefore we need to start LSP by default. The vector indexing, as a computational expensive index, will be only enabled if opt-in.
Decouple LSP from vector index creation; start LSP by default
---
> feat(amazonq): Decouple LSP from vector index creation; start LSP by default

- packages/core/src/amazonq/commons/controllers/contentController.ts
- packages/core/src/amazonq/util/functionUtils.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/shared/utilities/textDocumentUtilities.ts
- packages/core/src/shared/utilities/textUtilities.ts
move getIndentedCode to textDocumentUtilities and use cwsprChatInteractionType from aws-toolkit-common
---
> refactor(amazonq): move getIndentedCode to textDocumentUtilities and use cwsprChatInteractionType

- package-lock.json
- packages/amazonq/test/unit/codewhisperer/tracker/codewhispererCodeCoverageTracker.test.ts
- packages/core/src/codewhisperer/client/user-service-2.json
- packages/core/src/codewhisperer/service/inlineCompletionService.ts
- packages/core/src/codewhisperer/service/recommendationHandler.ts
- packages/core/src/codewhisperer/tracker/codewhispererCodeCoverageTracker.ts
- packages/core/src/codewhisperer/tracker/codewhispererTracker.ts
- packages/core/src/codewhisperer/util/codeWhispererSession.ts
- packages/core/src/codewhisperer/util/commonUtil.ts
- packages/core/src/codewhisperer/util/telemetryHelper.ts
1. bring back UserModification SendTelemetryEvent and track acceptedCharacterCount and unmodifiedAcceptedCharacterCount.
2. combine some latency tracking to the session object
JB PR reference: https://github.com/aws/aws-toolkit-jetbrains/pull/4955 
---
> telemetry(amazonq): Add new fields in UserTriggerDecision and UserModification events

- packages/amazonq/src/extensionNode.ts
- packages/core/src/extensionNode.ts
- packages/core/src/shared/crashMonitoring.ts
- packages/core/src/shared/filesystemUtilities.ts
- packages/core/src/shared/utilities/functionUtils.ts
- packages/core/src/shared/utilities/osUtils.ts
- packages/core/src/test/shared/crashMonitoring.test.ts
- packages/core/src/test/shared/filesystemUtilities.test.ts
- packages/core/src/test/shared/fs/fs.test.ts
- packages/core/src/test/shared/utilities/functionUtils.test.ts
- packages/core/src/test/shared/utilities/osUtils.test.ts
- packages/core/src/test/testUtil.ts
Crash monitoring is reporting incorrect crash metrics.
This seems to be due to various filesystem errors such as eperm (even though we were doing an operation on a file we created), enospc (the user ran out of space on their machine, and other errors.
Because of this we ran in to situations where our state did not reflect reality, and due to this certain extension
instances were seen as crashed.
- Determine if a filesystem is reliable on a machine (try a bunch of different filesystem flows and ensure nothing throws), if it is THEN we start the crash monitoring process. Otherwise we do not run it since we cannot rely it will be accurate.
- We added a `function_call` metric to allow us to determine the ratio of successes to failures
- Add retries to critical filesystem operations such as …
> fix(telemetry): Crash monitoring fixes

- package-lock.json
- packages/core/src/shared/extensionStartup.ts
- packages/core/src/shared/utilities/messages.ts
- packages/core/src/test/shared/extensionUtilities.test.ts
no metrics for notifications.
add `toolkit_showNotification` to `showMessage` and use it in `maybeShowMinVscodeWarning`.
---
> telemetry(messages): maybeShowMinVscodeWarning

- CONTRIBUTING.md
- packages/core/src/shared/logger/activation.ts
- packages/core/src/shared/logger/logger.ts
- packages/core/src/test/shared/logger/activation.test.ts
Problem:
When debugging the extension, vscode tends to ignore the log-level that was set from the `AWS Toolkit Logs` UI.
Solution:
If the dev-mode `aws.dev.logfile` path is configured, log to it at "debug" log-level regardless of the (initial) `vscode.LogOutputChannel.logLevel`.
---
> feat(dev-mode): always log to `aws.dev.logfile` at "debug" log-level

- packages/core/src/test/globalSetup.test.ts
In https://github.com/aws/aws-toolkit-vscode/blob/16aa3684f479566bfcf6a9e33f88e70039831e9a/packages/core/src/test/globalSetup.test.ts#L48, we use our fs wrapper, but global context hasn't been initialized yet. When we check `isWeb` in our fs module, we get the following: 
```
Exception has occurred: Error: ToolkitGlobals accessed before initialize()
at Object.get (/Volumes/workplace/aws-toolkit-vscode/packages/core/src/shared/extensionGlobals.ts:109:23)
at FileSystem.get isWeb [as isWeb] (/Volumes/workplace/aws-toolkit-vscode/packages/core/src/shared/fs/fs.ts:689:24)
at FileSystem.mkdir (/Volumes/workplace/aws-toolkit-vscode/packages/core/src/shared/fs/fs.ts:94:63)
at Runner.<anonymous> (/Volumes/workplace/aws-toolkit-vscode/packages/core/src/test/globalSetup.test.ts:48:18)
at async …
```
> fix(tests): avoid using our fs before globals initialized
