aws/aws-toolkit-vscode

- docs/telemetry-perf.md
It's hard to know what certain performance metrics are tracking
Add documentation
---
> docs(amazonq): Add visual representation for performance telemetry metrics

- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/messenger/messenger.ts
- packages/core/src/amazonqFeatureDev/errors.ts
- packages/core/src/test/amazonqFeatureDev/controllers/chat/controller.test.ts
- Static `errorName` is unnecessary in feature dev error classes. It also causes error code mismatches some of errorName which result in wrong state. 
- Remove `errorName` from error classes
- use class name match to ensure error handled correctly.
- Add unit tests to cover all the error cases.
---
> refactor(dev): remove errorName from Error classes

- packages/amazonq/test/unit/codewhisperer/util/authUtil.test.ts
- packages/core/src/test/testUtil.ts
This test was flaky due to the event emitter and the test expecting 2 of the same event to come in, but sometimes the second one was not capture.
This looks to be due to the second `captureEventOnce` call needing to do some initial setup before it could capture an event. And I think there was a race condition between it being setup in time and the event being emitted before it could start listening.
Make a new function which does the event capture once and then listens N amount of times. This is reliable.
fix https://github.com/aws/aws-toolkit-vscode/issues/5681
---
> fix(test): unreliable test "AuthUtil CodeWhisperer uses fallback connection"

- packages/core/src/awsService/cloudWatchLogs/commands/tailLogGroup.ts
- packages/core/src/awsService/cloudWatchLogs/registry/liveTailSession.ts
- packages/core/src/awsService/cloudWatchLogs/wizard/liveTailLogStreamSubmenu.ts
- packages/core/src/awsService/cloudWatchLogs/wizard/tailLogGroupWizard.ts
- packages/core/src/test/awsService/cloudWatchLogs/wizard/liveTailLogStreamSubmenu.test.ts
- packages/core/src/test/awsService/cloudWatchLogs/wizard/tailLogGroupWizard.test.ts
Wizard code intermixed with command logic
Refactor out the Wizard so the TailLogGroup command class can focus only on command logic.
* Additionally adds the AWSToolkit for VSCode UserAgent to the CWL LiveTail client. 
---
> refactor(cwl): lift TailLogGroupWizard into its own class

- packages/core/src/awsService/cloudWatchLogs/registry/liveTailSessionRegistry.ts
- packages/core/src/test/awsService/cloudWatchLogs/registry/liveTailRegistry.test.ts
The nestedMap implementation of the registry was forcing a defined Default item. This doesn't fit the usecase I am aiming to provide by this registry. There is no default object to be returned. If an item doesn't exist in the registry, we should handle an undefined object, and not a placeholder. In other words, there is no concept of a placeholder/default value for a LiveTailSession.
Additionally, `set` on the NestedMap would perform a deep merge. I am wanting to replace the object. 
Originally I defined the default object to an exception, but the NestedMap `set` operation calls `get`. And if there isn't already a value in the map, it would throw the exception defined as the default object. This means we could never add any item to the map. 
Swap the underlying implementation of the …
> refactor(cwl): Change implementation of LiveTailRegistry to standard map

- packages/core/src/test/shared/credentials/userCredentialsUtils.test.ts
- packages/toolkit/.changes/next-release/Bug Fix-a0acdaa1-7356-4f58-bc9b-fb7b708fe831.json
https://github.com/aws/aws-toolkit-vscode/blob/0164d4145e58ae036ddf3815455ea12a159d491d/packages/core/src/test/shared/credentials/userCredentialsUtils.test.ts#L38-L39
This test is deleting my actual aws config file
Update the environment variable to point to a fake location before test
Then recover them after test
---
> fix(credentials): fix credential test so it won't remove real aws config

- docs/TESTPLAN.md
Follow up from: https://github.com/aws/aws-toolkit-vscode/pull/5735#issuecomment-2412032047
See file changes. 
---
> docs(tests): update TESTPLAN.md with performance test section.

- packages/core/src/notifications/rules.ts
- packages/core/src/notifications/types.ts
- packages/core/src/shared/telemetry/util.ts
- packages/core/src/test/notifications/rules.test.ts
Initial code for a rule engine to determine whether or not to show an in-IDE notification. A notification is a JSON payload with a set amount of criteria. The rule engine accepts context from the currently running extension then determines if the notification payload's criteria will fit the provided context.
The types match the commonly designed schema, but may change in future commits.
Future work:
- More docs
- Updates to types and/or criteria
- Code that will use this
---
> feat(notifications): initial rule engine + tests

- packages/core/src/shared/crashMonitoring.ts
- packages/core/src/test/shared/crashMonitoring.test.ts
See each commit message for revelant fix
---
> test(crash): Crash minor fixes

- packages/core/package.nls.json
- packages/core/src/feedback/vue/submitFeedback.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/stepFunctions/workflowStudio/handleMessage.ts
- packages/core/src/stepFunctions/workflowStudio/types.ts
- packages/core/src/stepFunctions/workflowStudio/workflowStudioEditor.ts
- packages/core/src/stepFunctions/workflowStudio/workflowStudioEditorProvider.ts
Workflow Studio custom editor does not communicate bi-directly with local asl file
Adding bi-directional sync between local file and Workflow Studio custom editor
- On local file save, the change is sent and applied to WFS
- On every WFS action the change is synced with local file (without saving)
- On save action from WFS (Save button or Crtl+S) the local file is saved
Additionally, adding send feedback functionality + handling webview loading indicator
[Demo gif](https://maxis-file-service-prod-iad.iad.proxy.amazon.com/issues/bccf68da-2515-47fd-b549-65d7f7de39fe/attachments/4c11f37d32d60190aba363c20716f554045326d9381107c403f741c0496cd7b4_cb34c843-ee3b-42a3-b725-a7e87856741a)
---
> feat(stepfunctions): Implement bi-directional sync between local file and WFS

- packages/core/src/shared/utilities/timeoutUtils.ts
- packages/core/src/test/shared/utilities/timeoutUtils.test.ts
Creates our own version of an Interval, similar to how we have our own Timeout
---
> feat(time): Add Interval class

- packages/core/src/awsService/cloudWatchLogs/activation.ts
- packages/core/src/awsService/cloudWatchLogs/commands/tailLogGroup.ts
- packages/core/src/awsService/cloudWatchLogs/document/liveTailDocumentProvider.ts
- packages/core/src/awsService/cloudWatchLogs/registry/liveTailSession.ts
- packages/core/src/test/awsService/cloudWatchLogs/commands/tailLogGroup.test.ts
TailLogGroup currently is just logging the Users WizardResponse. It does not start a LiveTail stream or print results to the VSCode editor
* Creates a `LiveTailSession` with the input params from the TailLogGroupWizard
* Registers the LiveTailSession in the `LiveTailSessionRegistry`
* Iterates the Response Stream and prints new LogEvents to a TextDocument
* If there are no open tabs for a given session's TextDocument, the stream will be closed by triggering its AbortController and disposing its client. 
We will use a new URI Scheme for LiveTail text documents so we can identify a LiveTail session vs a Cloudwatch SearchLogGroup/ViewLogStream document. In the future, we will register LiveTail specific CodeLenses that depend upon this URI scheme. Defining a new URI scheme for a Text Document …
> feat(cwl): initialize tailLogGroup command. starts stream and prints logEvents to textDocument

- packages/core/src/shared/telemetry/telemetryService.ts
When the user shutdown their extension gracefully our mechanism that would cache any pending metrics for the next startup would not save to disk.
This was due to the VS Code FS implementation being used, but it will not work since the function it is called in is called by `deactivate()` which does not have access to vscode apis on shutdown.
Solution is to swap it with the node fs implementation
---
> fix(telemetry): session_end not caching events

- packages/core/src/shared/ui/pickerPrompter.ts
- packages/core/src/test/shared/ui/pickerPrompter.test.ts
- packages/core/src/test/shared/vscode/quickInput.ts
Currently prompter doesn't support multipick
Add a new function `createMultiPick` that supports multipick and can be used in Wizard.
The returned result will be a list encoded by `JSON.stringify` , use `JSON.parse` to recover the list
```typescript
// define DataQuickPickItem, note you can use `picked: true` to pre-select items in the multipick
const syncFlagItems: DataQuickPickItem<string>[] = [
{
label: 'Build in source',
data: '--build-in-source',
description: 'Opts in to build project in the source folder. Only for node apps',
},
{
label: 'Code',
data: '--code',
description: 'Sync only code resources (Lambda Functions, API Gateway, Step Functions)',
picked: true,
}
]
export interface SyncParams {
readonly syncFlags: string
}
// define the wizard
export class SyncWizard extends …
```
> feat(ui): support multipick prompter

- packages/toolkit/package.json
Every time I did a development build the package.json would change.
Background: New fonts are added for Amazon Q by adding the SVG to `packages/core/resources/icons`. Then the `generateIcons.ts` script will read this and add the icon to our custom font that we generate. Another part of this script also updates the package.json with this new icon.
The problem is that the package.json change was only reflected in the Amazon Q package.json and not the Toolkit package.json. This needs to be reflected in the Toolkit package.json as well since we only generate a single font for both extensions, instead of a customized font for each.
Run the generate icon script for Toolkit and commit the package.json changes.
---
License: I confirm that my contribution is made under the terms of the Apache 2.0 …
> test(build): Sync fonts to Toolkit

- packages/core/src/test/shared/utilities/pathFind.test.ts
Test is very sensitive to implementation changes. 
Specifically, if the environment PATH isn't completely overwritten, it fails. 
avoid assumption that we completely overwrote PATH, and assume we only add to it. 
---
> fix(ssh): remove extra call to findSshPath in test. 

- packages/core/package.json
- packages/core/package.nls.json
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/stepFunctions/activation.ts
- packages/core/src/stepFunctions/workflowStudio/activation.ts
- packages/core/src/stepFunctions/workflowStudio/handleMessage.ts
- packages/core/src/stepFunctions/workflowStudio/types.ts
- packages/core/src/stepFunctions/workflowStudio/workflowStudioEditor.ts
Workflow Studio (WFS) is opening for all asl files by default and there is no straightforward way to close it in favour of default editor if the user requires that. Additionally, there is no easy way open WFS from the current default editor
Adding options to close and reopen WFS custom editor:
- WFS still launches as a default editor for asl files
- On clicking the custom close button in WFS, the webview panel gets closed and the custom editor is opened instead
- With the custom editor opened, there is an option to launch WFS by clicking codelens command on top of the file. This command will close current(default) editor and reopen the file in WFS. If WFS is already opened for the file, it will redirect to that tab
- There is an additional option to launch WFS on right-click context menu …
> feat(stepfunctions): Allow closing Workflow Studio and reopening it

- packages/amazonq/.changes/next-release/Feature-4540d7be-edc2-42ce-b7e7-6f04b2bd9106.json
- packages/core/src/amazonqFeatureDev/session/sessionState.ts
Agent polling rate is too low, causing users to receive slow summary updates of changes agent has made to their code
- Decrease requestDelay to 5000ms from 10000ms to ensure we poll for agent updates more frequently
- Increased pollCount to 360 from 180 as we are now polling twice as frequently
---
> feat(amazonq): Increase polling rate for Q agent code summary

- packages/core/src/awsService/cloudWatchLogs/commands/tailLogGroup.ts
- packages/core/src/test/awsService/cloudWatchLogs/commands/tailLogGroup.test.ts
* LiveTail sessions can run for a long time, on LogGroups that have a high volume of LogEvents. We want to not infinitely add logs to a TextDocument, leading to memory issues within VSCode.
Users can configure a `limit` preference (default: 10000 , max 10000 , min: 1000). 
When the number of lines in a Live Tail session (number of LogEvents) reaches the limit, the 'N' oldest logEvents will be removed, to fit in the 'N' newest events coming in from the response stream. 
---
> feat(cwl): Add line trimming to LiveTail when limit is reached

- packages/amazonq/.changes/next-release/Bug Fix-771c645f-eeea-4da5-b2d2-4315dfad9506.json
- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/core/src/shared/vscode/env.ts
- packages/toolkit/.changes/next-release/Bug Fix-9c15d2c5-6b28-42ae-b068-f71821acf62a.json
- When running auth through tunneled vscode the auth server starts up even though its not accessible
- Instead of detecting for ssh-remote we should detect where the extension host is running.
- If we are running in browser with compute backend -> use device code
- If we are running locally -> use authorization grant
- If we are connected to a remote instance through vscode -> use device code
- If we are running through tunneled vscode -> use device code
This keeps it inline with detecting the extension host from https://github.com/microsoft/vscode/blob/7c9e4bb23992c63f20cd86bbe7a52a3aa4bed89d/extensions/github-authentication/src/githubServer.ts#L121, which it uses to determine whether or not device code flow should be used
---
License: I confirm that my contribution is made under the …
> fix(auth): Fix device code detection when running auth through tunneled vscode

- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/telemetryHelper.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- The full server response metrics don't include the ~2 seconds to create the conversation id, it just handles everything between after the conversation id was created
- Create new metrics that include the conversation id creation data
---
> telemetry(amazonq): Create server request metrics that include conversation id creation

- packages/core/src/dev/activation.ts
- packages/core/src/shared/telemetry/activation.ts
- packages/core/src/shared/telemetry/util.ts
- packages/core/src/test/shared/telemetry/util.test.ts
There seems to be a bug with vscode.env.sessionId since we observed in telemetry multiple clientIds who had the same sessionId.
Generate our own sessionId and share it between extensions through globalThis
---
> telemetry(bug): sessionId not unique

- packages/core/src/codewhispererChat/editor/context/file/languages.ts
This is the longest case of code duplication in the repo from `jscpd` (46 lines!). 
Remove the duplication case, remove redundant if statement. 
The switch statements could also be refactored into something with significantly less code in the future. Want to keep this PR focused on reducing code duplication. 
---
> refactor(cw): avoid duplicating language list. 

- .github/workflows/jscpd.json
- .github/workflows/node.js.yml
New contributors often copy-paste logic and test cases, which creates a maintenance cost for little gain.
Examples
- https://github.com/aws/aws-toolkit-vscode/pull/3837#discussion_r1367182525
- https://github.com/aws/aws-toolkit-vscode/pull/3805#discussion_r1317867006
We call these repeated segments of code "clones". 
implement a static threshold. 
Run `jscpd` in CI and compare the % duplicated to a fixed threshold of 1.34%, which is the current duplication rate in the repo. 
The main issue with this solution is that it fails to provide easy debugging options when new duplicates are found. Currently exploring adding this functionality in a follow-up. 
- this is a summary of the problem/solution. For full information, see full doc (VSCode: Detecting and Reducing Duplicate Code) describing …
> ci(lint): run jscpd in CI, compare to static threshold. 

- packages/core/src/test/lambda/config/samParameterCompletionItemProvider.test.ts
This is the second longest case of code duplication in the repo from jscpd (38 lines!).
Provide helper methods to build test objects. 
---
> refactor(sam): remove duplication in sam test file

- packages/core/src/awsService/cloudWatchLogs/commands/tailLogGroup.ts
New log events in a LiveTail session are added to the end of a TextDocument. Session updates can contain multiple LogEvents, leading to the text document growing quickly past the user's view. requiring them to constantly be scrolling the document themselves. 
To maintain parity with CWL console experience (and the classic `tail -f` experience), we want to auto scroll the customer's LiveTail session's visible editors to the bottom. 
This will only happen IF the end of file is already in view. Meaning, if a User scrolls UP (causing the end of file to not be in view), auto scrolling will not enable. However, if they scroll back down to EOF themselves, it will re-enable.
Simply, if the end of file is in view, when new logEvents are added to the document, the editor will be autoscrolled back …
> feat(cwl): Support autoscrolling live tail session's visible editors

- packages/core/src/codewhisperer/util/supplementalContext/utgUtils.ts
Using extractClasses with path as file content incorrectly, so always returns empty list.
Fix the call.
fix #5864
---
> fix(amazonq): utg findSourceFileByContent passes pass wrong context

- packages/amazonq/.changes/next-release/Bug Fix-279c3a22-246e-41ca-9a42-3e446cdb9565.json
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/util/supplementalContext/crossFileContextUtil.ts
We found there were lots of cases where open tabs context sent from the plugins with total length > 10240 chars long, which will result in `validationException` error while users trigger inline completion service. 
Limit maximum length of supplemental context added in the result set and meanwhile Q team is conducting investigation to root cause it.
---
> fix(amazonq): limit maximum size of supplementalContext being sent

- packages/amazonq/package.json
- packages/amazonq/src/inlineChat/command/registerInlineCommands.ts
- packages/amazonq/src/inlineChat/controller/inlineChatController.ts
- packages/core/package.nls.json
This PR adds the "Inline chat" menu option to the right click context menu and command palette. It also rejects empty inputs to inline chat to make it clearer to users they must input text into the dialog. 
> feat(amazonq): Add inline chat to context menu and reject empty inputs

- packages/amazonq/.changes/next-release/Bug Fix-0be85264-f542-4383-a02e-0ae0e66dba90.json
- packages/amazonq/src/inlineChat/controller/inlineChatController.ts
This PR removes the notification when a query is empty, this was not intended to be added and the menu should simply close when the input is empty.
> fix(amazonq): Remove warning on empty inputs to inline chat

- packages/amazonq/.changes/next-release/Bug Fix-9cebf072-0ebd-476d-a1bf-babd27ef9cc5.json
- packages/core/src/amazonq/webview/ui/apps/featureDevChatConnector.ts
- packages/core/src/amazonq/webview/ui/apps/gumbyChatConnector.ts
- packages/core/src/amazonq/webview/ui/main.ts
The function onAsyncEventProgress its reused for both Gumby and Dev feature, which enabled for both (not the expected scenario).
Added a condition to prevent and only enable for Dev. 
---
> fix(dev): Add conditional for stop code gen on async event

- packages/core/src/test/techdebt.test.ts
> test(techdebt): push date back to after re:Invent

- packages/webpack.base.config.js
https://github.com/aws/aws-toolkit-vscode/issues/4463
The two required flags are set as follows:
- `__VUE_OPTIONS_API__`: `true` since we use the options API extensively. This is opposed to the newer composition API, which I don't believe we use. An example of us using the options API can be found here: https://github.com/aws/aws-toolkit-vscode/blob/f806ae04f5d56b872282e42d5f765b2b1a9e28dd/packages/core/src/login/webview/vue/login.vue#L321 and more info can be found here https://vuejs.org/guide/typescript/options-api
- `__VUE_PROD_DEVTOOLS__`: `false` since this is the default, and it otherwise increases the build size per https://vuejs.org/api/compile-time-flags.html#VUE_PROD_DEVTOOLS. 
- Also relevant, composition API: https://vuejs.org/guide/extras/composition-api-faq.html
- More …
> build(vue): fix warnings from vue about unset flags. 

- packages/core/package.nls.json
- packages/toolkit/.changes/next-release/Bug Fix-c45df2a7-e8f0-488a-815c-0883ab3919b9.json
Somehow missed merging some strings needed for guided walkthrough to package.nls.json 
Added them back
---
> fix(lambda): added walkthrough strings

- .github/workflows/notification.yml
- .github/workflows/notify.js
Problem:
- Contributors get confused about when to add a changelog.
- Bot adds two comments which could be combined into one comment.
Solution:
- Clarify the changelog note.
- Combine messages into one comment.
Example: https://github.com/justinmk3/aws-toolkit-vscode/pull/21#issuecomment-2448660727
---
> ci: condense messages, clarify "changelog" message

- packages/amazonq/.changes/next-release/Feature-4eed9d3c-8ada-44de-9621-fb34fbbc9e15.json
- packages/core/src/amazonq/webview/ui/main.ts
- packages/core/src/codewhispererChat/controllers/chat/telemetryHelper.ts
Allow users to View and Apply diff when they explictily send code to Amazon Q using - Fix, Refactor, Optimize and Send To Prompt.
Notes:
- Releasing it all customers
- The View and Apply diff is only retained for first response after Fix, Refactor, Optimize and Send To Prompt, and NOT for followup chats.
- `featureConfig`  is the setup for A/B experiments and`Ignored` by `tslint` because, 
- currently View Diff and Apply Diff are the only feature that uses these.
- If the changes are reverted the next time any team wants to use it, they will have to rewire the A/B experiments setup again.
https://github.com/user-attachments/assets/2f4c0e06-4185-435f-9969-8b8f92d32fd1
---
> feat(amazonq): Allow users to View and Apply diff

- packages/core/src/amazonq/lsp/lspController.ts
This is a PR to upgrade LSP to 0.1.24, this LSP contains new APIs for unit test generation.
---
> feat(amazonq): upgrade Q LSP to 0.1.24 for UTG

- packages/core/src/shared/sam/sync.ts
- packages/core/src/test/shared/sam/sync.test.ts
- packages/toolkit/.changes/next-release/Bug Fix-2ad71338-1d0f-4bbf-a9e9-ac0f12be7a4d.json
When customer choose use flag information from `samconfig.toml` for sync and deploy operations, we assume that all the needed parameters will be available in the `samconfig.toml`.  Only `--config-file <samconfig file path>` is passed to SAM CLI. 
We skip many prompters in such scenario reduce clicking. Yet, we also need to skip prompter for `ecrRepoUri` and `syncFlag` in sync wizard. 
Add condition to skip these prompter when flag information from `samconfig.toml` is used. 
---
> fix(lambda): skip ecrRepoUri and syncFlags prompters when using flag from samconfig file 

- packages/core/src/shared/sam/deploy.ts
- packages/core/src/test/shared/sam/deploy.test.ts
- packages/core/src/testInteg/sam.test.ts
- packages/toolkit/.changes/next-release/Bug Fix-1ade44c5-bd1f-4b8f-a7f3-f2740ebb8097.json
- packages/toolkit/CHANGELOG.md
Explicitly specifying template path in sam deploy command to point to the build artifact folder makes SAM CLI create/update `samconfig.toml` in the build artifact folder rather than updating the `samconfig.toml` file in project root folder. 
Remove the `--template-path` from deploy flag. SAM will determine the template in the project folder and write to correct samconfig file
---
> fix(lambda): remove template path from sam deploy command

- packages/amazonq/.changes/next-release/Bug Fix-63cca37f-cf3c-42ff-bc9d-b3f71c0e3202.json
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- The examples text shows "How can Amazon Q help me?" but when you click on it it shows "What can Amazon Q help me with?" in chat. This is confusing to users
- Align both the example help text and the prompt message in chat as "How can Amazon Q help me?"
- Align them with "What can Amazon Q help me with?" instead
---
> fix(amazonq): Align example help text with the prompt message that it sends in chat

- docs/telemetry-perf.md
We have no documentation showing what latencies we are measuring for amazon q chat
Add documentation
Direct link: https://github.com/jpinkney-aws/aws-toolkit-vscode/blob/4c7ae0ae0c8d0e4525b68da487bd43c4c1b7884b/docs/telemetry-perf.md
---
> docs(amazonq): Add latency metric diagrams for amazon q chat

- packages/core/src/codewhisperer/models/model.ts
- packages/core/src/codewhisperer/service/transformByQ/transformApiHandler.ts
Recently noticed an issue where language upgrade transformations fail when our `manifest.json` includes this new key which was added for SQL conversions (unreleased feature).
Use a default of `undefined` for `requestedConversions`, so that it does not appear in the `manifest.json`, and only add it to the `manifest.json` when the user is doing a SQL conversion, as this key is only used for SQL conversions.
---
> fix(amazonq): default requestedConversions to undefined in manifest

- package-lock.json
- package.json
> deps: resolve http-proxy-middleware vulnerability by updating webpack-dev-server

- packages/amazonq/src/extensionNode.ts
- packages/core/src/dev/activation.ts
- packages/core/src/dev/beta.ts
- packages/core/src/dev/config.ts
- packages/core/src/dev/index.ts
- packages/core/src/extensionNode.ts
> config(beta): support per-extension beta URLs

- packages/toolkit/.changes/next-release/Bug Fix-f6bb74e5-14cd-4e63-bc24-5e8e82dbaf46.json
- packages/toolkit/package.json
When resources are provisioned and controlled through a SAM template, customers should never modify resources directly as this such action would create drift in the CFN template.
Removed action to delete a Lambda or S3 bucket in the AppBuilder section
---
> fix(lambda): removed delete action for lambda and s3 in AppBuilder

- packages/amazonq/.changes/next-release/Bug Fix-8459b9ba-8260-411b-ad00-0ed1394263d0.json
- packages/core/src/amazonq/lsp/lspController.ts
When multiple IDE instances are opened at the same time, the `@workspace ` indexing can increase CPU usage to a point that system fan needs to engage. IDE can be slow if it is older devices like intel i5 or i7 Mac OS.
When multiple IDE instances are opened at the same time, the `@workspace`  indexing can increase CPU usage to a point that system fan needs to engage. IDE can be slow if it is older devices like intel i5 or i7 Mac OS. This PR is to improve indexing auto start-stop strategy, detect CPU usage more frequently and pause indexing more aggressively whenever system total CPU usage goes up. In the mean time, further reduce CPU usage for old Intel i5, i7 devices, make sure one IDE instance at most utilize one physical core and all instance combined cannot exceed 1 for any extended …
> fix(amazonq): Improve indexing auto start-stop strategy

- packages/core/src/amazonq/webview/ui/apps/baseConnector.ts
- packages/core/src/amazonq/webview/ui/apps/cwChatConnector.ts
- packages/core/src/amazonq/webview/ui/apps/featureDevChatConnector.ts
- packages/core/src/amazonq/webview/ui/apps/gumbyChatConnector.ts
- packages/core/src/amazonq/webview/ui/connector.ts
Create an abstract class that can be used by all connectors.
---
> refactor(amazonq): add BaseConnector Abstract class for common logic

- CONTRIBUTING.md
- packages/core/src/shared/logger/logger.ts
- packages/core/src/shared/logger/toolkitLogger.ts
- packages/core/src/test/shared/logger/toolkitLogger.test.ts
- deduplicate tests
- define `setTopic` on `BaseLogger`, not `ToolkitLogger`
- it's not specific to ToolkitLogger, so it should live in the base interface.
- define `LogTopic` in `logger.ts`, not `ToolkitLogger`
- it's not specific to ToolkitLogger, so it should live in the base interface.
---
> refactor(logging): cleanup

- packages/core/src/notifications/panelNode.ts
- packages/core/src/shared/utilities/textDocumentUtilities.ts
- packages/core/src/test/notifications/resources/emergency/1.x.json
- packages/core/src/test/notifications/resources/startup/1.x.json
Created a `ReadonlyDocument` class in `textDocumentUtilities` to show a virtual read-only txt file. Converted existing txt notifications.
Use telemetry url wrapper instead of `openExternal` 
Also updated some local notification JSON for future testing
> feat(notification): Use virtual txt file and telemetry url wrapper

- packages/core/src/amazonq/messages/chatMessageDuration.ts
- packages/core/src/codewhispererChat/controllers/chat/telemetryHelper.ts
the trace id that gets emitted for amazonq_addMessage is different then the one that gets emitted for amazonq_chatRoundTrip
Use the same trace id
---
> telemetry(amazonq): include trace id in amazonq_addMessage

- packages/core/src/shared/crashMonitoring.ts
- packages/core/src/test/shared/fs/node/fs.test.ts
In our telemetry data we saw the following scenario:
- We saw a session (`7ebb2966-7e94-4177-80d9-c5a485511c13`) sending heartbeats as normal, with the latest one being at: `Nov 4, 2024 @ 03:35:45` (1730691345628). A heartbeat is simply a file with a timestamp value that is constantly updated.
- ~2 minutes later we see that this session was reported as crashed at `Nov 4, 2024 @ 03:37:32`, but the timestamp on the heartbeat file it read was `Nov 4, 2024 @ 03:05:45` (1730689545627)
- This does not make sense since the latest heartbeat was at `3:35`, but what was seen was `3:05`. 2 more heartbeats are known to have happened after `3:05` based on telemetry, but it looks like they somehow were not seen when the crash check happened
We already do handling for this edge case by...
- After the …
> fix(crash): fsync heartbeat file writes

- packages/core/src/amazonq/messages/chatMessageDuration.ts
It's hard to diagnose why we sometimes get some extreme values for a chat round trip. One idea is that some remote instances might be hosted in a different region and that's causing the increased values in some rare instances
Add the stringified version to the reasonDesc field temporarily so that we can get more information. This would look like:
```
'{"chatMessageSent":1730994444010,"editorReceivedMessage":1730994444011,"featureReceivedMessage":1730994444013,"messageDisplayed":1730994459698}',
```
The numbers picked were pretty arbitrary `(x > 30000 || x < -30000)` but it should give us a sampling of 50+ examples in the next week. After that we can revert this code since we should have all the data we need to see if this is the issue
> telemetry(amazonq): Add more information for outlier chat round trips

- packages/amazonq/.changes/next-release/Breaking Change-7a7320b8-e8a2-4d61-8f2d-7da04f1716da.json
- packages/amazonq/package.json
- packages/amazonq/src/inlineChat/controller/inlineChatController.ts
This PR updates the keybindings for Amazon Q's focus chat keybind to win+alt+i on Windows, cmd+alt+i on macOS, and meta+alt+i on Linux. This was requested by product to keep it consistent with the other keybinds:
Additionally there is a small change to add a log line for when an in stream error occurs to help in debugging with customers.
> fix(amazonq): Update keybinding for focus chat

- packages/core/src/awsService/cloudWatchLogs/commands/tailLogGroup.ts
- packages/core/src/awsService/cloudWatchLogs/registry/liveTailSession.ts
- packages/core/src/test/awsService/cloudWatchLogs/commands/tailLogGroup.test.ts
Problem
As LiveTail session is running, we want to display to the user metadata about their session.
**While updating my local feature branch after fixing the merge conflicts in https://github.com/aws/aws-toolkit-vscode/pull/5889, my original PR for this change was closed.**
**Please see original PR [here](https://github.com/aws/aws-toolkit-vscode/pull/5894) for addional comments and context**
Solution
While a livetail session is the active editor, in the bottom status bar, we will display the duration the session has been running for, how many events per/s, and if the log data is being sampled or not.
> feat(cwl): LiveTail statusbar

- packages/core/src/awsService/ec2/sshKeyPair.ts
- packages/core/src/shared/utilities/pathFind.ts
Starting in https://github.com/aws/aws-toolkit-vscode/pull/5936 some tests started expiring, since fixed in https://github.com/aws/aws-toolkit-vscode/pull/5954. However, than expire, the `SshKeyPair` tests hang because they are stuck in a child process. This leads to these tests failing to timeout, even when exceeding the test timeout threshold. 
Add explicit timeout on the child process we use to spawn ssh keys. 
---
> test(ssh): Add explicit timeout on child process to avoid hanging. 

- packages/amazonq/.changes/next-release/Bug Fix-15ddd682-232b-4bcd-a6e5-969f5c1c40c9.json
- packages/core/src/amazonq/lsp/lspController.ts
List of fixes:
- `def func (a) :` -> `def func(a):`
- `class (A) :` -> `class(A):`
- for python, change `// Function definitions to # Function definitions` ,` // Class definitions`  to `# Class definitions`
- for js/ts: `function findMax (arr: number[]) : number | undefined{.`  ->  `function findMax(arr: number[]): number | undefined {.`
- for all language: `// File path: a.ts`  -> `//File path a.ts`  
- for js/ts: `String privateString ;`  -> `String privateString;` 
> fix(amazonq): wrongly formatted supplemental context for inline suggestion

- packages/core/src/codewhisperer/client/user-service-2.json
> config(amazonq): update Q API model

- packages/amazonq/.changes/next-release/Bug Fix-9f5467f7-da28-455c-9471-a5799055ddb7.json
- packages/amazonq/test/unit/codewhisperer/util/crossFileContextUtil.test.ts
- packages/amazonq/test/unit/codewhisperer/util/supplemetalContextUtil.test.ts
- packages/core/src/codewhisperer/util/editorContext.ts
- packages/core/src/codewhisperer/util/supplementalContext/crossFileContextUtil.ts
- packages/core/src/codewhisperer/util/supplementalContext/supplementalContextUtil.ts
- LSP might return chunk with empty string, which will cause validation exception if such supplemental chunk is sent to the service
- pretty logging
updated log string example
```
2024-11-04 11:36:38.767 [debug] CodeWhispererSupplementalContext:
isUtg: false,
isProcessTimeout: false,
contentsLength: 5208,
latency: 50.849000096321106
strategy: OpenTabs_BM25
Chunk 0:
Path: /Volumes/workplace/ide/aws-toolkit-vscode-staging/packages/core/src/codewhisperer/service/keyStrokeHandler.ts
Length: 1777
Score: 75.30026364918442
Chunk 1:
Path: /Volumes/workplace/ide/aws-toolkit-vscode-staging/packages/core/src/codewhisperer/service/referenceInlineProvider.ts
Length: 1437
Score: 63.365755359719486
Chunk 2:
Path: /Volumes/workplace/ide/aws-toolkit-vscode-staging/packages/core/src/codewhisperer/service/in …
```
> fix(amazonq): validationException if empty supplemental context chunk is sent to the service

- packages/core/src/awsService/cloudWatchLogs/activation.ts
- packages/core/src/awsService/cloudWatchLogs/commands/tailLogGroup.ts
- packages/core/src/awsService/cloudWatchLogs/document/liveTailCodeLensProvider.ts
- packages/core/src/awsService/cloudWatchLogs/registry/liveTailSession.ts
- packages/core/src/awsService/cloudWatchLogs/registry/liveTailSessionRegistry.ts
- packages/core/src/test/awsService/cloudWatchLogs/commands/tailLogGroup.test.ts
Users may want to clear their screen during a tailing session. The liveTail document is read only.
Users may want to stop their session without closing the document. 
Provide a codeLens to clear the screen (make document empty)
Provide a codeLens to stop the session without closing the document. 
Moves Interval Timer for updating the StatusBar to the LiveTailSession object so `stopLiveTailSession()` can interrupt it, and be guaranteed to be cleaned up.
The TextDocument's URI and Session URI seem to not be equal. Looking up in the LiveTailSessionRegistry with a document URI causes a session to not be found. Converting with `toString` allows these URIs to match and the registry to work as intended. 
Improves Exception handling on-stream. Previously, stopping the session in an expected …
> feat(cwl): Add clear screen and stop session code lens

- packages/core/src/notifications/activation.ts
- packages/core/src/notifications/controller.ts
- packages/core/src/notifications/panelNode.ts
- packages/core/src/notifications/types.ts
- packages/core/src/test/notifications/controller.test.ts
I explored sending telemetry if the user hides or unhides the notification view panel. However, there is no VSC hook to detect this and other ways (e.g. checking visible property) are not reliable. So, we cannot track this.
- toolkit_showNotification
- for displaying notifications on receive or when clicked on
- toolkit_invokeAction
- invoking an action from a notification, e.g. clicking on a button in the notification or opening a text document
- ui_click for clicking on the notifications node or dismiss button
---
> telemetry: add notifications telemetry

- packages/core/src/codewhisperer/client/user-service-2.json
not clear why is this but these lines will make client generated not able to call the service correctly and seems it always timeout.
https://github.com/aws/aws-toolkit-vscode/pull/5965/files#diff-1993309d74a00d453d972baa185cc65e227911391f8de06add4ee0998684e638R5-R12
---
> config(amazonq): patch #5965

- packages/core/src/codewhisperer/models/constants.ts
based on data, we found out that 50ms cap is not sufficient for larger repo and it tends to return empty supplementalContext due to timeout.
Increase to 100ms for now and there will be action items for Q team to collect p50, p75, p90 latency according to different repo size to conduct a detailed investigation.
---
> config(amazonq): update supplementalContext timeout from 50 to 100ms

- packages/core/src/applicationcomposer/activation.ts
- packages/core/src/applicationcomposer/composerWebview.ts
- packages/core/src/applicationcomposer/webviewManager.ts
- packages/core/src/test/applicationcomposer/utils.ts
In the constructor for `ApplicationComposerManager`, there is an async call (non-awaited). This call is modifying state within the object and therefore causes a race condition with any other function relying on this state. See https://github.com/aws/aws-toolkit-vscode/blob/81132884f4fb3319bda4be7d3d873265191f43ce/packages/core/src/applicationcomposer/webviewManager.ts#L30-L33
~This is potentially related to a flaky test.~ The test is still failing, but this refactor is still a win. 
- Implement an async `create` method with a private constructor. Move this pattern upward to enable async calls. 
---
> refactor(webview): avoid race conditions in constructors. 

- packages/core/src/dev/activation.ts
When opening the AWS Developer Menu for toolkit, no items were showing.
This is due to a wrong value being used for menu options. The second use was expecting it to be an object with keys, when it was actually a function. This happened due to a recent change that didn't catch this
---
> fix(dev): dev menu wasnt loading items

- packages/core/src/awsService/cloudWatchLogs/registry/liveTailSession.ts
Exceptions can occur pre-stream (the synchronous portion of a StartLiveTail call that establishes the streaming connection). Currently, we are calling StartLiveTail in a try-catch, catching errrors, and throwing them as a ToolkitException. These are not chaining the root exception. This means when an error occurs, its root cause is being swallowed - causing user's to not know *why* their LiveTall command is failing.
Given that we are just rethrowing `err`. There's probably no point to this catch. Removing it, and letting the root exception throw. 
Forced pre-stream exception to throw with an IAM permission violation and this change applied. More clear as to what the actual problem is:
Pop-up: `Failed to run command: aws.cwl.tailLogGroup: User: …
> fix(cwl): Remove wrapping pre-stream exceptions and just letting them throw

- packages/core/src/test/testUtil.ts
- See https://github.com/aws/aws-toolkit-vscode/issues/5325
- the following `waitUntil` is timing out: https://github.com/aws/aws-toolkit-vscode/blob/43299f368308b6720ba22bbd910c6714bc47bdcb/packages/core/src/test/testUtil.ts#L495-L518
- All occurrences of error (AFAIK) fail to list any editors open. This implies `waitUntil` is timing out even though all editors (that aren't ignored by pattern) are closed. 
A potential explanation is that the `executeCommand` is taking a long time to close the editors ignored by the patterns, and causing a timeout in `waitUntil`. In this case, we don't want to error. 
- refactor to also check if activeEditors is cleared. If there aren't any, we shouldn't be throwing an error. 
- Also, decrease timeout to avoid wasting time here during tests (if we can't …
> test(vscode): fix failure to close editors on `beforeEach` hook.

- packages/core/src/shared/sam/cli/samCliLocalInvoke.ts
- packages/core/src/shared/sam/cli/samCliLocator.ts
- packages/core/src/shared/sam/cli/samCliSettings.ts
- packages/core/src/test/shared/sam/cli/samCliLocalInvoke.test.ts
- The test failure is due to timeout on Windows when first searching for the SAM cli path in `src/shared/sam/cli/samCliLocator.ts`. This is a known slow process. 
- The verification of SAM is also slow (100-200ms), even if result is cached and we do this each time we read from cache. 
- Verify the cache once, rather than on each read. 
- Find sam cli in the before hook to allow all sam tests to run under same conditions. Otherwise, the first test is then responsible for actually finding the path causing it to take way longer than the rest of the tests. 
- Allow 3x retries on before hook on windows to avoid flakiness. 
- An alternative solution could involve manually inserting into the cache, or mocking a piece of the component, but wanted to keep the test coverage as is. 
- This approach …
> test(slowsam): samcli test speed up

- packages/amazonq/.changes/next-release/Bug Fix-46c5fb9b-1b36-4826-8520-ec03409bce79.json
- packages/amazonq/src/inlineChat/controller/inlineChatController.ts
- packages/core/src/codewhisperer/views/lineAnnotationController.ts
The LineAnnotationController could get stuck showing the tutorial for new users due to changes in the inline chat logic, this PR resolve that bug and prevents the `aws.codewhisperer.tutorial.workInProgress` from being set to `true` when using inline chat.
Additional a more descriptive error log for the `computeDiffAndRenderOnEditor` function call and check for not null in `updateTaskAndLenses`
> fix(amazonq): tutorial always showing on start

- .github/workflows/jscpd.json
Copy paste detection is very sensitive as the minLines is currently set to 3. 
increase it to 10. 
---
> build(lint): increase `minLines` in jscpd. 

- package-lock.json
- packages/amazonq/.changes/next-release/Feature-d18cffcd-fd30-4936-9586-587b0ba88ec9.json
- packages/amazonq/test/e2e/amazonq/featureDev.test.ts
- packages/amazonq/test/e2e/amazonq/framework/messenger.ts
- packages/amazonq/test/unit/amazonqFeatureDev/session/session.test.ts
- packages/core/package.json
- packages/core/package.nls.json
- packages/core/src/amazonq/commons/diff.ts
- packages/core/src/amazonq/index.ts
- packages/core/src/amazonq/webview/ui/apps/featureDevChatConnector.ts
- packages/core/src/amazonq/webview/ui/commands.ts
- packages/core/src/amazonq/webview/ui/connector.ts
- packages/core/src/amazonq/webview/ui/diffTree/actions.ts
- packages/core/src/amazonq/webview/ui/diffTree/types.ts
- packages/core/src/amazonq/webview/ui/main.ts
- packages/core/src/amazonq/webview/ui/texts/constants.ts
- packages/core/src/amazonqFeatureDev/app.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/messenger/messenger.ts
- packages/core/src/amazonqFeatureDev/session/session.ts
- packages/core/src/amazonqFeatureDev/session/sessionState.ts
- packages/core/src/amazonqFeatureDev/types.ts
- packages/core/src/amazonqFeatureDev/views/actions/uiMessageListener.ts
- packages/core/src/amazonqFeatureDev/views/connector/connector.ts
- packages/core/src/test/amazonq/common/diff.test.ts
- packages/core/src/test/amazonqFeatureDev/controllers/chat/controller.test.ts
- packages/core/src/test/amazonqFeatureDev/utils.ts
For the current /dev experience for code review, user needs to review the entire file list of generated code, reject the changes they do not want, and then accept the remaining changes in bulk at the end.
This PR introduces improvements in user experience around the code review experience in which user can now review the file changes and accept them one at a time. User can start editing the file right away after accepting the changes without having to go through the entire generated file list.
- introduces a new action button for accepting file change for each change suggested on the file list
- accepted changes are now highlighted in green
- when accepting changes in bulk, the file list is updated to reflect the status if a change is rejected or accepted
- minor text changes / …
> feat(dev): File-level accepts of generated code

- packages/core/src/codewhisperer/util/editorContext.ts
- packages/core/src/codewhisperer/util/supplementalContext/crossFileContextUtil.ts
The overall supplemental context has a timeout of 50ms, each sub promise has a timeout of 50ms. Problem is these 2 timeout are very tight, leaving no buffer time for node js runtime to do context switch. The poll interval of each sub promise is 10ms, which does not precisely timeout at 50ms. 
Add a 10ms buffer time for supplemental context.
Reduce poll duration
---
> config(amazonq): adjust timeout for supplemental context

- packages/amazonq/.changes/next-release/Bug Fix-30c6bfc4-9411-4bc4-bfd1-41305859109d.json
- packages/amazonq/test/unit/codewhisperer/util/runtimeLanguageContext.test.ts
- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/util/runtimeLanguageContext.ts
- packages/core/src/codewhisperer/views/lineAnnotationController.ts
within inline suggestion code path, `isLanguageSupported()` relies on `vscode.editor.document.langaugeId` to determine whether the given language is supported Q inline suggestion functionality. However, it's possible that some languages are not recognized by VSCode IDE itself without 3rd party extensions, for example: VSCode doesn't recognize `.sv`, `svh`, `vh` files which is bound to SystemVerilog language if users do not have the 3rd party extension installed and enabled, in this case, `vscode.editor.document.languageId` will simply return `plaintext`. 
This is the root cause why autotrigger doesn't work for systemverilog files, because at the beginning, we don't even register keyStrokeHandler for files with `.sv`, `svh`, `vh` files.
if language check return false, we should also check …
> fix(amazonq): users not able to auto trigger Q inline suggestion on systemVerilog files

- packages/core/src/awsService/cloudWatchLogs/commands/tailLogGroup.ts
- packages/core/src/awsService/cloudWatchLogs/registry/liveTailSession.ts
- packages/core/src/test/awsService/cloudWatchLogs/commands/tailLogGroup.test.ts
- packages/core/src/test/awsService/cloudWatchLogs/registry/liveTailRegistry.test.ts
When creating the CloudWatchClient for a LiveTail session, we are not specifying which credentials to use. This is causing the client to always use the `Default` credential profile, even if a different AWS Credential profile is selected within AWSToolkit.
Resolve the active AWS credential from `globals.awsContext`, and supply that to the LiveTailSession constructor. These credentials are then use to construct the CWL client. 
---
> fix(cwl): Pass in active credentials when creating CWL client for LiveTail

- packages/toolkit/package.json
Known scenario where a new icon is added in Q but not synced to Toolkit. Due to not being synced, whenever Toolkit is built during development the package.json is updated.
Do the sync and merge the change
---
> test(packagejson): sync fonts to Toolkits

- packages/core/src/test/awsService/accessanalyzer/iamPolicyChecks.test.ts
Flaky tests: https://github.com/aws/aws-toolkit-vscode/issues/5996
The check for executeCommand is not important to these tests, and can be removed. 
fix #5996
> test(policychecks): remove flaky check with executeCommand

- packages/core/src/awsService/cloudWatchLogs/registry/liveTailSession.ts
- packages/core/src/test/awsService/cloudWatchLogs/registry/liveTailSession.test.ts
LogEventFilter is an optional configuration parameter when building a LiveTailSession. Currently, the Constructor is not actually setting this property so it is always undefined. This means that if a user sets a Filter pattern, it will not be applied. 
Set the property in LiveTailSession Constructor.
Add missing unit tests to validate that LiveTailSession config values are set properly. Testing via `buildStartLiveTailCommand` because this is what actually gets sent to the CWL backend to start a LiveTailSession.
---
> fix(cwl): Set LogEventFilter when constructing LiveTailSession

- packages/core/src/shared/sam/debugger/awsSamDebugger.ts
- packages/core/src/shared/sam/localLambdaRunner.ts
- packages/core/src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
- packages/toolkit/.changes/next-release/Bug Fix-e5a76bd7-06a7-4a59-aead-8ea3e3924ee9.json
fix #5957 
Appbuilder added `--region` parameter to `sam local invoke`, however this region is always reading region prop from default toolkit connection. Ignoring region set in sam debug config.
region and credential set in sam debug config should override region and credential in current active toolkit connection.
---
> fix(appbuilder): SAM local debugging: region and credential in launch config should override toolkit default

- packages/amazonq/test/unit/amazonqFeatureDev/session/session.test.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/amazonqFeatureDev/session/session.ts
retry message without problem statement
Move latestMessage setter call outside of session in controller as it interrupts with retryMessage functionality
---
> fix(feature dev): retry message without problem statement

- packages/core/src/awsService/appBuilder/explorer/nodes/appNode.ts
- packages/core/src/awsService/appBuilder/explorer/nodes/rootNode.ts
- packages/core/src/test/shared/applicationBuilder/explorer/nodes/appNode.test.ts
- packages/core/src/test/shared/applicationBuilder/explorer/nodes/rootNode.test.ts
- packages/toolkit/.changes/next-release/Bug Fix-3f75e95c-f940-42e3-b0e2-b6a3b9143a58.json
I was working on a CDK project, and after synthesizing my CDK template, I noticed that the app-builder is showing a misleading notification to customers: No IaC templates found in the workspace. This seems incorrect, as I do have IaC templates in the workspace, including both raw and synthesized CDK templates.
While I understand the intention behind the message, it needs to be more precise to avoid confusion. I suggest we roll it back to something more accurate, like No SAM templates found in the workspace, to clearly indicate the specific missing template type. I'm considering this a P0 issue and will raise a PR to address it.
Solution is to change all instance where IAC is mentioned to the customer to SAM, we would roll back to IaC once we start support CDK.
Remove redundant Logic.
--- …
> fix(appbuilder): Issue related to App-builder placeholder wrong message

- package-lock.json
- package.json
- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/core/src/test/credentials/sso/ssoAccessTokenProvider.test.ts
Depends on https://github.com/aws/aws-toolkit-common/pull/914
On the condition of:
- SSO session is BuilderID or Internal Amazon IdC
- Subsequent login for same SSO session happened earlier than 90 days (the expected session expiration)
We need to know on the client side to be able to report this information so that CloudWatch alarms can consume this. 
By adding the existing sessionDuration field, which is `currentTime - whenThePreviousSessionWasCreated`, to `aws_loginWithBrowser` we will have all the information we need to alarm on.
---
> telemetry(auth): report sessionDuration on reauth `aws_loginWithBrowser`

- packages/amazonq/test/unit/codewhisperer/util/crossFileContextUtil.test.ts
#5994 is causing CI test failure
misuse of `sinon.alwaysReturned()`
should use `sinon.returns()`
---
> test(amazonq): patch #5994 causing CI test failing

- packages/core/src/shared/logger/logger.ts
- packages/core/src/test/testLogger.ts
Problem:
Log messages have literal format strings such as "%s", even though values were passed to the log function:
2024-11-14 11:00:33.778 [info] CloudFormationTemplateRegistry: processed … %s
2024-11-14 11:00:34.634 [debug] schema service: handle … -> %s
Solution:
Regression introduced by `TopicLogger`. Fix the call.
---
> fix(logger): logs show "%s" instead of replaced value

- packages/amazonq/.changes/next-release/Feature-76e907b5-f09d-4b24-bc60-156471d3cb22.json
- packages/core/src/amazonq/webview/ui/tabs/constants.ts
- packages/core/src/amazonqGumby/chat/controller/messenger/messenger.ts
- packages/core/src/amazonqGumby/chat/controller/messenger/messengerUtils.ts
- packages/core/src/codewhisperer/commands/startTransformByQ.ts
- packages/core/src/codewhisperer/models/constants.ts
Currently /transform feature can only accept java 8/11 projects.
Updating user form to allow jdk 17 as source version.
> feat(amazonq): adding support to accept java 17 projects

- packages/core/src/dev/beta.ts
- packages/core/src/shared/fs/watchedFiles.ts
- packages/core/src/shared/logger/logger.ts
Assigning a `const logger = getLogger()` in module scope, may default to `ConsoleLogger`, because modules may be loaded before logging is initialized.
Move the decision into `TopicLogger`, so that the time of the `getLogger()` assignment is irrelevant (just-in-time).
---
> fix(logger): support module-scope getLogger()

- packages/amazonq/test/unit/codewhisperer/util/crossFileContextUtil.test.ts
- packages/amazonq/test/unit/codewhisperer/util/supplemetalContextUtil.test.ts
call `assertTabCount()` to wait until text editors are opened correctly
---
> test(amazonq): fix flaky crossfileContextUtil.test

- packages/core/src/dev/beta.ts
- packages/core/src/shared/logger/activation.ts
- packages/core/src/shared/logger/toolkitLogger.ts
- packages/core/src/shared/vscode/env.ts
- packages/core/src/test/shared/vscode/env.test.ts
Beta and bug-bash users often need logs.
Log debug/verbose messages at "info" log-level. They will appear as "info" logs in the Output channel, even though they were logged at "debug" or "verbose" level.
https://github.com/aws/aws-toolkit-vscode-staging/pull/1961 confirms CI behavior in a beta branch.
---
> feat(beta): force debug/verbose logging for Beta users

- packages/amazonq/.changes/next-release/Bug Fix-17fd1915-ab2a-4fe8-aa1e-6fc15524b46a.json
- packages/core/src/amazonq/webview/ui/tabs/constants.ts
- packages/core/src/amazonq/webview/ui/tabs/generator.ts
The `@workspace` [context command](https://github.com/aws/mynah-ui/blob/main/docs/DATAMODEL.md#contextcommands-default-) is being shown in all tab types, even though it is only relevant to Amazon Q chat ('cwc' tabType).
Move the context command to the tab specific config file. This change also allows other tab types to specify their own context commands if applicable.
---
> fix(amazonq): `@workspace` command shown in all tab types

- packages/core/src/notifications/activation.ts
- packages/core/src/notifications/controller.ts
- packages/core/src/notifications/panelNode.ts
- packages/core/src/notifications/rules.ts
- packages/core/src/notifications/types.ts
- packages/core/src/shared/telemetry/telemetryService.ts
- packages/core/src/shared/vscode/setContext.ts
- packages/core/src/test/notifications/controller.test.ts
- packages/core/src/test/notifications/rendering.test.ts
- packages/core/src/test/notifications/rules.test.ts
**Don't squash** 
Commit messages are complete.
Summary:
- Remove unneeded criteria rule
- Add verbose logging for rule checks
- Add types that were missing to parts of the notification schema. Some were just strings but had predefined values
- Add a timeout to the update and reload action so that telemetry can run.
- UX updates including removing the panel wording, add red icons, add activity bar badge.
---
> feat(notification): misc logging, types, fixes

- docs/telemetry.md
- packages/core/src/shared/telemetry/util.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/test/shared/telemetry/spans.test.ts
See each commit for the specific change. But this has multiple improvements to the `@withTelemetryContext` decorator.
The main change to note:
- Adding the `@withTelemetryContext` decorator to a method can wrap thrown errors with context about that function. This helps us to build some sort of stack trace in the `reasonDesc` of our telemetry when errors are thrown.
- [This is the documentation updated to get a better idea of what this is](https://github.com/aws/aws-toolkit-vscode/blob/b3f2ad9c65b47cd61ca72652171e932ef2480d8c/docs/telemetry.md#adding-a-stack-trace-to-your-metric) 
- The decorator allows for minimal diffs to the code. It is replacing [this previous code](https://github.com/aws/aws-toolkit-vscode/blob/2a72e6df814e3cbabce1cfe2476f1ca98ea8de2b/packages/core/src/shared/crashMoni …
> refactor(telemetry): add functionality to @withTelemetryContext

- packages/core/src/test/testRunner.ts
- packages/toolkit/test/unit/index.ts
There are many unreliable tests that seem to fail very rarely or even only once. If they are truly failing so rarely, retrying them should keep CI green. This also allows us to avoid investigating flaky tests that aren't having a meaningful negative impact on the dev experience.
- retry failed tests up to 3 times. 
---
> build(test): add automatic retry to all mocha tests. 

- packages/amazonq/.changes/next-release/Feature-e3c11418-cbdc-4281-ab70-b1a7c574aaa1.json
- packages/core/src/amazonq/webview/ui/tabs/constants.ts
- packages/core/src/amazonqGumby/chat/controller/controller.ts
- packages/core/src/amazonqGumby/chat/controller/messenger/messenger.ts
- packages/core/src/amazonqGumby/models/constants.ts
- packages/core/src/codewhisperer/commands/startTransformByQ.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/models/model.ts
- packages/core/src/codewhisperer/service/transformByQ/transformApiHandler.ts
- packages/core/src/codewhisperer/service/transformByQ/transformationResultsViewProvider.ts
- packages/core/src/dev/config.ts
- packages/core/src/shared/utilities/workspaceUtils.ts
- packages/core/src/test/codewhisperer/commands/transformByQ.test.ts
- packages/core/src/testInteg/shared/utilities/workspaceUtils.test.ts
Enable the SQL conversion feature for `/transform`.
Enable feature, intended for 11/21 release.
---
> feat(amazonq): enable SQL conversions feature

- packages/core/src/test/testRunner.ts
- packages/toolkit/test/unit/index.ts
Some tests appear to be hanging indefinitely with the new retry system. Example: https://github.com/aws/aws-toolkit-vscode/actions/runs/11899590502/job/33158551534?pr=6037
Rollback changes until proper solution is found. 
---
> build(test): undo automatic retries.

- packages/core/src/codewhisperer/client/user-service-2.json
> config(amazonq): update amazonq service api model

- packages/core/src/codewhisperer/views/securityIssue/securityIssueWebview.ts
- packages/core/src/codewhisperer/views/securityIssue/vue/root.vue
Opening the security scan issues webview led to an infinite loop on the `update` call, consuming significant amounts of customer CPU.
Updated the webview to not auto-update, and made it so that each "view" command opened a new window, even if already present.
This isn't fully ideal, but it at least immediately fixes the CPU consumption issue.  Any setup to watch/poll for updates from the server would be either expensive or latent.  This will be the most clean, but may lead to a different UX than expected.
---
> fix(amazonq): fixed bug with high CPU use event loop for security scan findings

- packages/amazonq/.changes/next-release/Bug Fix-fd4826b9-25e6-428e-ba73-c774e79dd2ca.json
- packages/core/src/amazonq/commons/diff.ts
- packages/core/src/amazonq/index.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/test/amazonq/common/diff.test.ts
- when you accept an individual code change, it will bring up the file window
- when you update the accepted file, both left and right of the window reflects the changes you made immediately
- it should only show the changes made on the left, while the right stays the same as the original suggested code change
- updated the way vscode.diff is called when opening up the file such that it is the actual file on the left, and the suggested code change stays on the right
---
> fix(amazonq): file opening behavior on accepted changes

- package-lock.json
- package.json
- packages/core/src/awsService/cloudWatchLogs/activation.ts
- packages/core/src/awsService/cloudWatchLogs/commands/tailLogGroup.ts
- packages/core/src/awsService/cloudWatchLogs/document/liveTailCodeLensProvider.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/test/awsService/cloudWatchLogs/commands/tailLogGroup.test.ts
Cloudwatch wants to monitor usage metrics of the LiveTail integration
When starting a session emit telemetry for: 
* Session already started (this case happens when session is already running, and customer sends a new command that matches the already running session)
* Has LogEventFilter
* LogStream filter type
* Source of the command (command palette, explorer)
When closing a session: 
* Session duration
* source of cancellation (ex: CodeLens, ClosingEditors)
---
> feat(cwl): Emit telemetry when starting and stopping liveTail sessions

- packages/toolkit/package.json
running `npm run compile` always gives you a toolkit package.json change because the icons are out of sync
commit the updated toolkit icons
---
> deps(toolkit): Update toolkit icons

- packages/amazonq/.changes/next-release/Bug Fix-54e46358-d60f-492b-af5c-b23f4aa2b1b8.json
- packages/core/src/amazonq/lsp/lspController.ts
If customers open a workspace without a workspace folder they get:
```
2024-11-19 10:49:16.189 [error] Error: No workspace folders found
at k (/Users/myuser/.vscode/extensions/amazonwebservices.amazon-q-vscode-99.0.0-g3afd54d/dist/src/extensionNode.js:5464:5562)
at L.buildIndex (/Users/myuser/.vscode/extensions/amazonwebservices.amazon-q-vscode-99.0.0-g3afd54d/dist/src/extensionNode.js:5464:9890)
at Immediate.<anonymous> (/Users/myuser/.vscode/extensions/amazonwebservices.amazon-q-vscode-99.0.0-g3afd54d/dist/src/extensionNode.js:5464:11854)
```
because workspace indexing is throwing an error
Log that no workspace folders were found so indexing is skipped
---
> fix(amazonq): skip indexing when no workspace folders are found

- packages/amazonq/src/extensionNode.ts
- packages/core/src/extensionNode.ts
- packages/core/src/notifications/activation.ts
- packages/core/src/notifications/controller.ts
- packages/core/src/test/notifications/controller.test.ts
If notifications fail to fetch, it will retry multiple times with 30 second waits. Activation is awaiting on this though, so it may take forever to finish.
don't await on notification activation
Also, update logging statements.
---
> fix(notifications): extension activation hangs if fetch fails

- packages/core/src/awsService/cloudWatchLogs/activation.ts
- packages/core/src/awsService/cloudWatchLogs/commands/tailLogGroup.ts
- packages/core/src/awsService/cloudWatchLogs/document/liveTailCodeLensProvider.ts
- packages/core/src/awsService/cloudWatchLogs/registry/liveTailSession.ts
- packages/core/src/test/awsService/cloudWatchLogs/commands/tailLogGroup.test.ts
Currently after closing a session in a way that leaves the TextDocument open (`Stop tailing` CodeLens), the codeLenses remain visible. This means a user could click `Stop tailing` again, and receive an error for not being able to find the running LiveTail session for the given document. 
Additionally, there is no feedback when a session is closed. Clicking `Stop tailing` doesn't signal to the user that the session was actually stopped. 
* Provide a `refresh` method in the LiveTail CodeLens provider. This fires an event to force recomputing the CodeLenses on a document. 
* Modify LiveTail Lens provider to return no Lenses if the session is not running (in the registry)
* Display an information window when a Session is stopped
* Changes wording/placement on some log statements for …
> fix(cwl): Hide LiveTail CodeLenses and display info message when closing session

- packages/amazonq/.changes/next-release/Feature-77884869-72ad-4ee0-986e-62cc1ca8e746.json
- packages/core/src/notifications/activation.ts
- packages/core/src/notifications/panelNode.ts
- packages/toolkit/.changes/next-release/Feature-e62b5743-d746-4689-91dd-96d037d346fe.json
- Removes feature flag
- Slightly adjusts toolkit_invokeAction telemetry to not use button string, instead we use action enums.
---
> feat(notifications): enable notifications for all users

- packages/core/resources/css/amazonqTransformationHub.css
- packages/core/src/codewhisperer/models/constants.ts
After meeting with customer team, we wanted to be more specific about the last patch we were presenting the user
The new strings in the constants replaced have been confirmed and provide better understandability.  
---
> fix(amazon q): updating string for final patch of selective transformation

- packages/amazonq/.changes/next-release/Feature-13564075-487c-424c-a48e-43ee446d1dad.json
- packages/core/src/shared/filetypes.ts
`.gradle` files are not currently supported by /dev
Add `.gradle` to list of supported file extensions
I manually tested some prompts in /dev with requests to modify the build.gradle and it worked
---
> feat(amazonq): support `.gradle` files in /dev

- packages/core/src/awsService/appBuilder/explorer/openTemplate.ts
- packages/core/src/shared/sam/build.ts
- packages/core/src/shared/sam/deploy.ts
- packages/core/src/shared/sam/sync.ts
- packages/core/src/shared/ui/sam/bucketPrompter.ts
- packages/core/src/shared/ui/sam/templatePrompter.ts
- packages/core/src/test/shared/ui/sam/bucketPrompter.test.ts
- packages/core/src/test/shared/ui/sam/templatePrompter.test.ts
- packages/toolkit/.changes/next-release/Bug Fix-c45b6435-6724-4cbf-bfac-eac4184985b5.json
We have been using components from sync.ts, where all prompters created for other command still use samSyncUrl.
Use correct url link for respective command in all prompter button. 
---
> fix(lambda): correct prompter url button for sam deploy sync build commands

- packages/core/src/awsService/cloudWatchLogs/commands/tailLogGroup.ts
- packages/core/src/awsService/cloudWatchLogs/wizard/liveTailLogStreamSubmenu.ts
- packages/core/src/awsService/cloudWatchLogs/wizard/tailLogGroupWizard.ts
- packages/core/src/test/awsService/cloudWatchLogs/wizard/liveTailLogStreamSubmenu.test.ts
Addresses feedback after working with Toolkit UXD. There are inconsistencies with formatting/capitalization of certain nouns in the LiveTail menu. Some of the verbiage is unclear/too lengthy.
In the case there is an already running session and the user tries to start a new session with the same parameters, it is unclear that we are opening an already existing session and not starting a new one. 
* Consistent spacing and capitalization of "Log Group" and "Log Stream"
* Introduce new Info window when opening and existing session stream
* Re-words LogStream filter type sub menu.
---
> fix(cwl): Change wording in menus, add info message when opening running session

- packages/amazonq/test/unit/codewhisperer/util/crossFileContextUtil.test.ts
#6079
Ignore the flaky test cases for now until we root caused why it failed occasionally in some CI machines
---
> test(amazonq): skip flaky crossfileContextUtil.test

- packages/amazonq/.changes/next-release/Feature-7ffbdb5d-40c5-4c3e-bc20-63d731bc51d2.json
- packages/core/src/codewhisperer/util/customizationUtil.ts
- packages/core/src/shared/featureConfig.ts
- packages/core/src/test/fake/mockFeatureConfigData.ts
- packages/core/src/test/shared/featureConfig.test.ts
When a customization is overridden via AB, the name of the customization is not shown to users
Uses the variation field from the customizationArnOverride feature as the name for the customization. This allows the UX to show a customization name when the customizationArn is overriden
---
> feat(amazonq): Using AB variation value as customization name when overridden

- packages/core/src/amazonqFeatureDev/client/featureDev.ts
> fix(amazonq): add throttling exception handling and in code comments for featureDev quota

- packages/core/src/shared/crashMonitoring.ts
- packages/core/src/shared/logger/logger.ts
Use the topic logger, removing the old prefixes since the topic is automatically prepended
---
> refactor(logs): Use CrashMonitoring topic in logger

- packages/amazonq/.changes/next-release/Feature-75f96117-d8c5-4bd4-88d9-0d3919060f99.json
- packages/core/src/amazonqGumby/chat/controller/controller.ts
- packages/core/src/amazonqGumby/chat/controller/messenger/messenger.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/models/model.ts
- packages/core/src/dev/config.ts
Selective transformation changes were released under an IDE feature flag due to backend changes that needed to be fixed.
In this PR, we are removing the feature flag on the IDE side so the users will now be able to see the form to select if they want to view their changes in one or multiple diffs. If they select multiple diffs in this form, then selective transformation will be invoked. 
---
> feat(amazon q): removing feature flag for selective transformation and confirmed string changes

- packages/core/src/awsService/cloudWatchLogs/commands/tailLogGroup.ts
- packages/core/src/test/awsService/cloudWatchLogs/commands/tailLogGroup.test.ts
TailLogGroup command is not being fully cleaned up properly. The event listeners for: 
* showing the StatusBar item
*  closing a session when exiting its editors  
are not being disposed of. As users stop sessions, these listeners remain active whilst doing no meaningful work. This is effectively a memory leak.
Additionally during testing, I noticed that we are adding a session to the LiveTailRegistry before the session is actually started. This could cause an issue where a session stream isn't successfully created, but the session is still registered. 
* Create an array of disposables and dispose of them as we exit the TailLogGroup command
* Only register a session after startLiveTail returns
Because now we dispose of the "tab close" listener when tailLogGroup exits, changes are needed …
> fix(cwl): Dispose event listeners when command exits

- packages/amazonq/.changes/next-release/Feature-06d3549d-411e-43e3-a731-d1e435a86577.json
- packages/core/src/shared/filetypes.ts
`Dockerfile` files are not currently supported by /dev
Add a list of file prefixes that are considered code files for /dev.  This approach supports not only `Dockerfile` but also popular variants of this such as `Dockerfile.build`, `Dockerfile-prod`, etc.
I manually tested some prompts in /dev with requests.  I set breakpoints to see that the file was being zipped up in workspace upload.
---
> feat(amazonq): support Dockerfile files in /dev

- buildspec/release/35opengate.yml
We close source gate during the start of a release to prevent unwanted commits coming in, but we have to remember to manually open it again. 
We want to automatically re-open the source gate after a release is triggered. 
This PR creates the buildSpec file to be used by codeBuild project in our release pipeline to open the source transition.
Related infra CR: https://code.amazon.com/reviews/CR-162245234/revisions/1#/diff
---
> ci(automation): added openGate build spec

- packages/core/src/codewhispererChat/controllers/chat/controller.ts
enable implicit workspace ab test for broader groups of users but not only internal users
remove isInternalUser predicate
---
> config(amazonq): enable implicit project context ab test for broader users

- packages/amazonq/src/extensionNode.ts
- packages/core/src/dev/activation.ts
- packages/core/src/extensionNode.ts
- packages/core/src/notifications/activation.ts
- packages/core/src/notifications/controller.ts
- packages/core/src/notifications/index.ts
- packages/core/src/notifications/rules.ts
- packages/core/src/notifications/types.ts
- packages/core/src/shared/globalState.ts
- packages/core/src/shared/settings.ts
- packages/core/src/test/notifications/controller.test.ts
- packages/core/src/testInteg/notifications/notifications.test.ts
- Add a generic dev menu item to reset the state of a feature. Simply extend with a function handler to add an item to the menu. The initial item resets in-ide notification state.
- Add a way to test notifications locally without modifying code. Using a dev menu item you can add a notification to global state and receive it in your IDE for visualization.
- Refactor notifications controller to not require a RuleEngine when polling is requested.
---
> test: add notification and reset state dev options

- packages/amazonq/.changes/next-release/Bug Fix-80f16b7a-440d-4e06-89ad-1454c58ff28f.json
- packages/core/src/shared/filetypes.ts
The codefileExtensions does not contain an extension type for `.pli` which is the common extension for PL/1, or for `.bms` which is Basic Mapping Support and common for screen definition files in IBM mainframe. Because of this, the files and code in them are not accessible in the workspace context for Amazon Q using the `/dev` quick action.
When using the Q quick action '\dev' for `.pli` or `.bms` files, Q responds with the following message
> This appears to be an empty program or workspace with no source files present. There is nothing to explain at this time since no code or files are available for analysis.
- Add the PL/1 language extension `.pli` as a known code file extension type
- Add the Basic Mapping Support extension `.bms` as a known code file extension type
No tests were …
> fix(amazon q): add pl/1 and bms extensions as a recognized code file type

- packages/core/src/test/awsService/appBuilder/walkthrough.test.ts
- packages/core/src/test/codewhisperer/commands/basicCommands.test.ts
fix #6078 
Turn off CodeWhisper scanning after test suite completes.
---
> test(codewhisperer): Turn off CodeWhisperer Auto Scan after test case

- packages/amazonq/README.md
/docs should be /doc
fix it
---
> fix(amazonq): /docs -> /doc in readme

- buildspec/shared/common.sh
According to the comment in this file, there is an ignore pattern that is only needed on the vscode minimum version of 1.68, but we have bumped to 1.83.0. 
Remove pattern for this case. 
---
> build(pattern): remove ignore pattern related to 1.68 vscode version. 

- packages/amazonq/.changes/next-release/Feature-fd23658e-ecc3-4d17-8944-240cbe24a7cc.json
- packages/amazonq/src/extension.ts
- packages/core/src/amazonq/lsp/lspClient.ts
- packages/core/src/extension.ts
- packages/core/src/shared/logger/activation.ts
We didn't have much use for the old "Amazon Q" channel in addition to "Amazon Q Logs". All the logs we used were in "Amazon Q Logs".
- Now, just have the useful "Amazon Q Logs" channel.
- Move the Amazon Q Language Server logs in to Amazon Q Logs to unify all logs
---
> refactor(logs): drop "Amazon Q Logs" channel and just have "Amazon Q"

- packages/core/src/amazonqTest/chat/controller/controller.ts
- packages/core/src/amazonqTest/chat/controller/messenger/messenger.ts
- UTG toolkit telemetry can not differentiate the users from builderID users vs internal IAM IDC users vs external enterprise users.
- Adding `credentialUrl = AuthUtil.instance.startUrl` field to differentiate the builderID users vs internal IAM IDC users vs external enterprise users.
---
> telemetry(amazonq): differentiate Internal vs External users

- .github/CODEOWNERS
As part of the renaming of "DEXP" to "Flare", the team name on GitHub has changed, and so the `.github/CODEOWNERS` file in this repository should be updated accordingly.
Updated the `.github/CODEOWNERS` file accordingly.
---
> config(repository): renamed @aws/dexp to @aws/flare in codeowners

- package-lock.json
- packages/core/package.json
- packages/toolkit/.changes/next-release/Feature-76bb396d-6268-4d24-9373-4c7c0e91cbc4.json
Upgrading amazon-states-language-service from 1.11.0 to 1.13.0
> feat(toolkit): Upgrade amazon-states-language-service to 1.13.0

- packages/amazonq/.changes/next-release/Bug Fix-357cef5f-a2e7-43c4-b4ca-0e89bc8fccd7.json
- packages/core/src/amazonqDoc/session/sessionState.ts
If a user creates or updates a README using /doc and hits "Cancel" during the "Scanning source files" step, the prompt input progress bar persists.
Do not display the prompt progress bar if a user has cancelled the current task.
---
> fix(amazonq): progress bar persists after cancelling README creation

- packages/core/src/awsService/cloudWatchLogs/registry/liveTailSession.ts
- packages/core/src/test/awsService/cloudWatchLogs/registry/liveTailSession.test.ts
The `LiveTailSession` object's start/stop methods aren't directly under test. TailLogGroup tests are mocking their behavior. TailLogGroup command tests are more focused on managing the session registry, opening/writing to the document, and the close tab behaviors. 
Write a test that's scoped to creating a `session` and calling start and stop on it. Assert that timers are handled/disposed of properly, and that the session response stream is returned. 
Addresses [this comment](https://github.com/aws/aws-toolkit-vscode/pull/6095#discussion_r1857571286).
---
> test(cwl): Add unit test for starting and stopping LiveTailSession object. 

- codecov.yml
codecov always fails for gumby/appcomposer:
codecov/project/amazonqGumby — 75.29% (-3.93%)
codecov/project/applicationcomposer — 82.69% (-0.…)
Based on https://docs.codecov.com/docs/commit-status , the "default" item is just a name, it doesn't set defaults that are "inherited".
- rename the "default" project item to avoid confusion
- duplicate the configuration for all project items.
---
> ci: codecov always fails

- packages/core/package.json
https://github.com/advisories/GHSA-3xgq-45jj-v275
Use version 7.0.5
---
> deps(cross-spawn): update cross-spawn to 7.0.5

- .github/workflows/node.js.yml
- codecov.yml
- codecov is always skipped in github actions:
- <img width="430" alt="image" src="https://github.com/user-attachments/assets/669b25b7-1720-47e1-b8f9-a6eb9881dce5">
- We have a bot that attempts to remind contributors about adding tests, but it gets ignored.
- Fix the condition: https://github.com/aws/aws-toolkit-vscode/pull/6150/commits/cec8218a0bc7bfc8d0dfcc92a2764de18030e720
- Reintroduce the codecov "patch" check.
---
> ci: codecov "patch" check

- packages/core/src/shared/vscode/commands2.ts
The EC2 ARN sneaks its away into the logs via the `Ec2InstanceNode` tooltip property from `packages/core/src/awsService/ec2/explorer/ec2InstanceNode.ts`. When we run any command on this instance, we get the following logs with the middle section omitted for brevity. 
``` 
2024-12-04 17:25:10.859 [debug] command: running "aws.ec2.openTerminal" with arguments: [
{
collapsibleState: 0,
label: 'testInstance ({INSTANCE_ID}) RUNNING',
...
contextValue: 'awsEc2RunningNode',
iconPath: { id: 'pass', color: undefined },
tooltip: 'testInstance\n' +
'{INSTANCE_ID}\n' +
'running\n' +
'arn:aws:ec2:us-east-1:{ACCOUNT_ID}:instance/{INSTANCE_ID}',
id: '{INSTANCE_ID}'
},
undefined
]
```
The actual AWS account ID in use is included in the logs. 
What makes this difficult is that this node is passed directly …
> refactor(logs): avoid logging EC2 ARN on commands. 

- package-lock.json
- packages/amazonq/src/chat/activation.ts
- packages/amazonq/src/chat/handler.ts
- packages/amazonq/src/inline/completion.ts
- packages/amazonq/src/lsp/activation.ts
- packages/amazonq/src/lsp/auth.ts
- packages/amazonq/src/lsp/client.ts
- packages/core/package.json
- packages/core/src/amazonq/lsp/lspClient.ts
- vscode doesn't have the codewhisperer lsp for completion requests
- use the codewhisperer lsp when `"aws.experiments": {
"amazonqLSP": true
},`
---
> feat(amazonq): Use codewhisperer language server for completions

- packages/amazonq/.changes/next-release/Bug Fix-570a8c06-4da6-4585-b589-be1fba2ce20f.json
- packages/core/package.nls.json
- packages/core/src/amazonqDoc/controllers/chat/controller.ts
When a user clicks the "Change folder" button when creating or updating a README, the "Generating answer..." loading text appears, even though there is no answer being generated, since we are waiting for the user to choose a folder. 
This is an especially confusing UX if the user is connected to an SSH host:
When the user clicks the "Change folder" button, send a "Choose a folder to continue" message in the chat.
---
> fix(amazonq): prompt user to choose a folder in the chat for /doc

- packages/core/src/amazonq/webview/ui/quickActions/generator.ts
- packages/core/src/amazonqGumby/chat/controller/controller.ts
We were only recording the metrics when the user accepts changes so we can track which patches were applied based on their description. We wanted to also keep track of the form in which the user is prompted to pick whether they want their changes in one or multiple diffs.
Adding a telemetry call when we handle the form selection for selective transformation one or multiple diffs.
---
> telemetry(amazon q): adding telemetry after one or multiple diffs form selection

- docs/arch_features.md
Missing documentation about current behavior of ec2 remote window connect. 
Add some detail to the docs. 
---
> docs(ec2): add details about `authorized_keys`override

- packages/core/src/amazonqTest/chat/controller/controller.ts
- UTG sends plaintext instead of python for amazonq_utgGenerateTests event.
- In code, `session.fileLanguage = await this.getLanguageForFilePath(filePath)` reassigned python to plaintext after test generation.
- Removal of `session.fileLanguage = await this.getLanguageForFilePath(filePath)` should fix the issue.
---
> telemetry(amazonq): UTG sends plaintext instead of python for amazonq_utgGenerateTests event

- packages/amazonq/.changes/next-release/Bug Fix-5f545950-eae0-4ee9-bb41-3c0ac9b7dcb1.json
- packages/core/src/shared/filetypes.ts
[POST RE:INVENT]
Nested `Dockerfile` files were not supported with https://github.com/aws/aws-toolkit-vscode/pull/6107
Look at path basename when comparing file to list of well known files.
I manually tested adding nested `Dockerfile`s to various folders and ensured that pattern matched.
---
> fix(amazonq): /dev to support upload of nested dockerfiles

- packages/amazonq/.changes/next-release/Bug Fix-56306583-37cf-4364-ba41-ac69d0ffdf44.json
- packages/core/src/codewhisperer/util/zipUtil.ts
Issues reported in chat sometimes does not match issues tree.
This is happening because the zip artifact uses workspace name (custom name could be different from fsPath) while git diff output uses fsPath. This causes the findings to come back as two filePaths that end up overwriting each other.
Update zip to use project name from fsPath instead of `workspaceFolder.name`
---
> fix(amazonq): use fsPath for project name

- packages/amazonq/.changes/next-release/Bug Fix-0c35b577-da17-4132-a0b7-e0d630e73cb9.json
- packages/core/src/codewhisperer/util/zipUtil.ts
- Code diff for file review format has changed in payload to improve LLM based code review accuracy and is dependent on git.
- We are currently send entire file in diff format and run git commands to extract it. This change will remove git dependency for LLM based code review issues.
---
> fix(amazonq): Improved LLM code review for file review

- package-lock.json
Express needs to be updated to a newer version to avoid security vulnerabilities
Update it
---
> deps(core): Update dependencies

- package-lock.json
- package.json
- packages/core/src/awsService/cloudWatchLogs/commands/tailLogGroup.ts
Updating telemetry to accommodate changes in https://github.com/aws/aws-toolkit-common/pull/932
Update package version for telemetry. 
Add validation on the LogStreamFilter submenu's response for filter type. This is needed to allow the type returned from the LogStreamFilterSubmenu to be convertible to the type in the metric definition for filterPattern. In any case, this is a good validation to have since the 'menu' placeholder value isn't valid for starting a LiveTail session anyways.  
---
License: I confirm that my contribution is made …
> fix(cwl): Update metric definitions for TailLogGroup

- packages/core/src/amazonqTest/chat/controller/controller.ts
- packages/core/src/amazonqTest/chat/controller/messenger/messenger.ts
- packages/core/src/amazonqTest/chat/session/session.ts
- packages/core/src/codewhisperer/service/testGenHandler.ts
- Missing data if job fails at `StartTestGeneration` API.
- Adding requestId for `amazonq_utgGenerateTests` event, which helps ti debug the reason for job failures from the backend.
---
> telemetry(amazonq): Adding requestId for amazonq_utgGenerateTests event

- packages/core/src/testInteg/perf/prepareRepoData.test.ts
- packages/core/src/testInteg/perf/registerNewFiles.test.ts
- packages/core/src/testInteg/perf/zipcode.test.ts
Some of the performance tests have been flaky on CI, and is more noticeable lately with reduction in overall flakiness. 
bump the thresholds up. 
---
> test(perf): increase thresholds of perf tests. 

- packages/core/src/testInteg/stepFunctions/init.test.ts
Integration test for SFN was broken after updating amazon-states-language-service package to 1.13.0 ([relevant PR](https://github.com/aws/aws-toolkit-vscode/pull/6139))
Updating integration test to account for the new `QueryLanguage` variable introduced in the new version of the package
---
> fix(stepfunctions): integration test after ASL service update

- packages/core/src/amazonqDoc/controllers/docGenerationTask.ts
When users don't choose a different folder during document generation, the current telemetry will log folder level as undefined
Change the default workspace value to "Entire Workspace" to match the default behavior of the UX flow.
> telemetry(amazonq): folder level telemetry data undefined issue

- packages/amazonq/.changes/next-release/Bug Fix-c685f18f-0c30-49a0-b4d8-e4eab0cf3bc6.json
- packages/core/src/amazonq/lsp/lspController.ts
The system status (battery, CPU usage) was polled very frequently. https://github.com/aws/aws-toolkit-vscode/issues/6134
Only poll system status (battery, CPU usage) when vector indexing is in progress, this is to make the vector index pause when system load is high to protect system resources. 
---
> fix(amazonq): reduce system status poll freq

- packages/amazonq/.changes/next-release/Bug Fix-53ead65f-187e-47d9-9432-a48200b604d6.json
- packages/core/src/codewhisperer/util/gitUtil.ts
- packages/core/src/codewhisperer/util/zipUtil.ts
Git commands are too noisy; running /review always opens Amazon Q output channel with git command output
- Output to the Amazon Q Logs channel instead
- Make it verbose level so it won't show by default
---
> fix(logs): suppress git output

- codecov.yml
The "tests" codecov target always reports 0%, probably because the test code is ignored.
The "tests" target is not useful without more configuration, so drop it for now.
---
> ci: drop codecov "tests" coverage

- packages/core/src/test/codewhisperer/commands/transformByQ.test.ts
`jscpd` detected a duplicate code block in a `/transform`-related test file.
Use a shared variable so as not to duplicate.
---
> refactor(amazonq): fix duplicate code block in test file

- packages/amazonq/package.json
Code issues tree view takes up too much space away from chat view
Set `visibility` to `collapsed` (will only take effect for new installations)
---
> config(amazonq): code issues collapsed by default

- packages/amazonq/.changes/next-release/Bug Fix-64bec56a-f152-4345-b036-0c5ddb0ce5a2.json
- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/codewhisperer/service/securityIssueProvider.ts
Applying a fix does not update the position of other issues in the same file.
Revert disabling event handler on apply fix command
---
> fix(amazonq): revert disable event handler

- packages/amazonq/.changes/next-release/Bug Fix-d5c39800-ce37-4f6c-be23-9cc4035d0cef.json
- packages/amazonq/test/unit/codewhisperer/util/zipUtil.test.ts
- packages/core/src/codewhisperer/util/zipUtil.ts
- packages/core/src/testFixtures/workspaceFolder/workspaceFolder/App.java
Projects with a nested folder of the same name does not scan properly.
For example if the project name is `foo`, and there exists a folder `foo/foo/` then the zip artifact only contains the inner `foo/` folder.
Always include the project name in the zip artifact instead of conditionally adding it.
---
> fix(amazonq): always use projectName in zipEntryPath

- packages/amazonq/.changes/next-release/Bug Fix-a243e8d5-b494-46a1-9ec0-c8c6af3cbf35.json
- packages/core/src/auth/sso/cache.ts
- packages/core/src/shared/regions/regionProvider.ts
- packages/core/src/shared/utilities/cacheUtils.ts
- packages/core/src/test/credentials/sso/cache.test.ts
- packages/core/src/test/credentials/sso/ssoAccessTokenProvider.test.ts
- packages/toolkit/.changes/next-release/Bug Fix-868c7cda-80c1-4947-a498-3792f88622ad.json
When we loaded sso cache from disk, we would only invalidate (leading to a reauth prompt) if the cache file was missing.
But if the cache file was present, though its content was malformed, we would incorrectly treat it as recoverable by throwing instead of returning undefined. Users would get stuck in a state where all future api calls would fail, and they'd never get a prompt to reauth to fix their SSO session.
If we detect a SyntaxError treat it as non-recoverable, meaning it will trigger a reauth.
Also added some code to validate the content of the SSO cache we loaded from disk to ensure it is what we expected.
Fixes #6140
--- …
> fix(auth): malformed SSO cache didn't prompt reauth

- package-lock.json
- package.json
- packages/core/src/amazonqTest/chat/controller/controller.ts
- packages/core/src/amazonqTest/chat/controller/messenger/messenger.ts
- packages/core/src/codewhisperer/util/telemetryHelper.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- Repetitive code when emitting amazonq_utgGenerateTests telemetry events
- Metric has already been migrated to aws-toolkit-common
- Created sendTestGenerationToolkitEvent helper to extract common fields
- Removed metric override in this repo
- Tested and can confirm that metrics are same as previous method
---
> telemetry(amazonq): added helper for amazonq_utgGenerateTests metric and removed metric override 

- packages/core/src/amazonqTest/chat/controller/controller.ts
- If user clicks on Cancel button, IDE do `this.sessionCleanUp()` before emitting the metrics
- Removed this function `this.sessionCleanUp()`
---
> telemetry(amazonq): Removing session cleanUp before emitting the telemetry event

- packages/amazonq/test/e2e/amazonq/doc.test.ts
- packages/amazonq/test/e2e/amazonq/featureDev.test.ts
- packages/amazonq/test/e2e/amazonq/framework/messenger.ts
- packages/core/package.json
Add an E2E test for Creating a README using /doc
Moved reusable functions out of featureDev.test.ts to shared test framework
---
> test(amazonq): E2E test for /doc

- packages/amazonq/.changes/next-release/Bug Fix-8331f6fe-6955-4a49-91ac-e4ca3fbe4165.json
- packages/amazonq/test/unit/codewhisperer/service/diagnosticsProvider.test.ts
- packages/core/src/codewhisperer/service/diagnosticsProvider.ts
Diagnostics in problems panel show findingId as code which doesn't add any value
Use ruleId instead
---
> fix(amazonq): diagnostics code is incorrect

- packages/amazonq/.changes/next-release/Feature-65d6b661-7ab8-409d-8af8-918db3e69a2d.json
- packages/core/src/codewhisperer/views/securityIssue/securityIssueWebview.ts
- packages/core/src/codewhisperer/views/securityIssue/vue/root.vue
Code fix section is not automatically visible after clicking on generate fix inside code issue detail view.
- Changed the behavior of updating the webview so that it doesn't close/reopen a new panel every time
- Added event listeners to trigger UI updates
- Added scroll into view functionality
---
> feat(amazonq): automatically scroll to fix section

- package-lock.json
- packages/amazonq/.changes/next-release/Bug Fix-82132c4a-d74a-43d6-a93f-c65bac24d9fa.json
- packages/amazonq/.changes/next-release/Bug Fix-c79529d6-7df0-4c7a-bb41-60ff4f6600e2.json
- packages/amazonq/.changes/next-release/Feature-df165695-1b62-4e7e-b5e8-8ae42504b2fc.json
- packages/core/package.json
> deps(amazonq): update mynah ui

- packages/core/src/auth/sso/cache.ts
- packages/core/src/test/credentials/sso/cache.test.ts
- packages/core/src/test/credentials/sso/ssoAccessTokenProvider.test.ts
- packages/toolkit/.changes/next-release/Bug Fix-7cb802f6-498a-4442-ae88-399eaec1d9a5.json
Error users were seeing was:
```
Error: SSO cache data unexpectedly missing props: ["refreshToken"]
```
This was due to a change from a previous PR that assumed the refreshToken was always present in SSO cache.
It looks like the refreshToken does not exist for all cases, so some research needs to be done.
But for now this reverts the validation that the refreshToken exists. Though it keeps the validation that the accessToken exists since that is always guaranteed.
**A temporary workaround should be to sign out/in and things should start working. If not please downgrade 3.38.0 until we release this fix next week.**
Fixes #6230 
--- …
> fix(auth): SSO failed to get token due to missing 'refreshToken'

- docs/arch_develop.md
- packages/core/src/shared/ui/wizardPrompter.ts
- packages/core/src/shared/wizards/compositeWizard.ts
- packages/core/src/test/shared/wizards/compositWizard.test.ts
Follow up action item in [#6166](https://github.com/aws/aws-toolkit-vscode/pull/6166#issuecomment-2540112922)
- Refactor class : `NestedWizard`  --> `CompositeWizard`
- Update test file name
- Add information on `arch_development.md` about `CompositeWizard` and how to test using `PrompterTester` class. 
---
> refactor(toolkit): rename NestedWizard class and update arch doc

- packages/amazonq/.changes/next-release/Bug Fix-49ee4921-044b-48b0-b51c-4e7054e84e6a.json
- packages/core/src/amazonq/webview/generators/webViewContent.ts
- packages/core/src/amazonq/webview/messages/messageDispatcher.ts
- packages/core/src/amazonq/webview/ui/commands.ts
- packages/core/src/amazonq/webview/ui/main.ts
- packages/core/src/amazonq/webview/webView.ts
- the current implementation only opens the first tab as a welcome tab for the next 3 times you open vscode
- the new implementation shows the welcome tab 3 total times, either when you open a new chat tab or a new vscode window or both
---
> fix(amazonq): improve welcome page opening detection

- buildspec/linuxE2ETests.yml
- For the last 8 months or so we've skipped e2e test results, now they're becoming a lot more crucial and used by other teams
- remove the skipping
---
> test(core): unskip e2e test failures

- packages/amazonq/test/unit/codewhisperer/util/crossFileContextUtil.test.ts
- packages/core/src/codewhisperer/util/supplementalContext/crossFileContextUtil.ts
- packages/toolkit/package.json
Remove client side A/B experiment (control, treatment1, treatment2), move it to service side and always assume treatment1
---
> config(inline-completion): change supplemental context configuration to always use repomap

- packages/core/src/codewhisperer/util/supplementalContext/crossFileContextUtil.ts
Current `supplementalContextStrategy ` only reflect what group the user is in, however by doing this it won't help much on our data analysis. What we need is the context strategy being used so that we know how much % of users have repomap or opentabs and how % of users have empty supplemental context etc.
---
> telemetry(inline-suggestion): fine tune supplemental context strategy telemetry

- package-lock.json
- package.json
- packages/core/src/codewhisperer/commands/startTransformByQ.ts
- packages/core/src/codewhisperer/service/transformByQ/transformationResultsViewProvider.ts
`jobId` missing in some metrics.
Add it.
---
> fix(amazonq): add jobId to all metrics

- packages/amazonq/.changes/next-release/Bug Fix-1fd5992c-cc2e-49ac-8afc-360d7f0a3966.json
- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/codewhisperer/service/securityIssueProvider.ts
- packages/core/src/test/codewhisperer/commands/basicCommands.test.ts
Apply fix removes other issues in the same file. This is happening because apply fix command will always replace the entire file contents which triggers a document change event that intersects with all issues in the file.
Look through the diff hunks and apply them in a range.
---
> fix(amazonq): apply fix removes other issues

- packages/core/src/test/techdebt.test.ts
Techdebt test is failing CI. This is unlikely to be addressed atm. 
- Delay until 2025. 
---
> test(techdebt): delay timer to new year. 

- packages/amazonq/.changes/next-release/Bug Fix-9575c7da-3e49-4051-ba29-6b292d3e399a.json
- packages/amazonq/test/unit/codewhisperer/util/crossFileContextUtil.test.ts
- packages/amazonq/test/unit/codewhisperer/util/supplemetalContextUtil.test.ts
- packages/core/src/codewhisperer/util/supplementalContext/crossFileContextUtil.ts
related issue:  https://github.com/aws/aws-toolkit-vscode/issues/6079, https://github.com/aws/aws-toolkit-vscode/issues/6252
caller
```
function main () {
// init vscode cancellation token
const cancellationToken
setTimeout(100, () => {
cancellationToken.cancel()
})
highlevelWrapperFetchSupplementalContext(editor, cancellationToken)
}
```
```
export function highlevelWrapperFetchSupplementalContext(editor, cancellationToken) {
const supplementalContext = waitUntil(100, () => {
// here always timeout and throw TimeoutException
const opentabs =  await fetchOpenTabsContext(...)
const projectContext = await fetchProjectContext()
const result = []
if (projectContext not empty) {
// push project context
}
if (opentabs not empty) {}
// push openttabs
})  
return result
}
async function …
```
> fix(inline-suggestion): replace vscode.cancellation with waitUntil for timeout

- packages/amazonq/test/e2e/amazonq/framework/jsdomInjector.ts
- JSDOM logs non-critical CSS parsing errors during E2E tests. These warnings occur when mynah-ui loads SCSS files in [main.ts](https://github.com/aws/mynah-ui/blob/8058f86ed370f5268ba6e0993b2436dca0e09b30/src/main.ts#L37). These errors appear the test logs but they do not affect test functionality or results.
- Suppress the errors
---
> test(core): supress Failure to parse stylesheet message from e2e test logs

- packages/amazonq/test/unit/codewhisperer/util/crossFileContextUtil.test.ts
#6252
As test previously was using real system clock, it's likely to timeout due to heavy computation in an undeterministic way
Use fake clock
---
> test(iinline-suggestion): fix crossFileContextUtil.test failure caused by using real clock and test timeouts

- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/core/src/awsService/apprunner/commands/pauseService.ts
- packages/core/src/awsService/apprunner/wizards/deploymentButton.ts
- packages/core/src/awsService/ecs/commands.ts
- packages/core/src/awsService/s3/fileViewerManager.ts
- packages/core/src/codecatalyst/activation.ts
- packages/core/src/codewhisperer/commands/gettingStartedPageCommands.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/codewhisperer/vue/backend.ts
- packages/core/src/shared/awsContextCommands.ts
- packages/core/src/shared/extensionStartup.ts
- packages/core/src/shared/sam/activation.ts
- packages/core/src/shared/sam/sync.ts
- packages/core/src/shared/settings.ts
- packages/core/src/shared/utilities/messages.ts
- packages/core/src/test/shared/settings.test.ts
There is no real reason this needs to be async. It is also now inconsistent with `isExperimentEnabled`. 
Make non-async and add logged error if the promise rejects. 
---
> refactor(settings): make isPromptEnabled non-async

- packages/core/src/test/awsService/cloudWatchLogs/commands/tailLogGroup.test.ts
Currently, the TailLogGroup tests are passing, but emitting noisy errors in the CI logs:
```
<...>
No LiveTail session found for URI: test-region:test-log-group:all: Error: No LiveTail session found for URI: test-region:test-log-group:all
at D:\a\aws-toolkit-vscode\aws-toolkit-vscode\packages\core\src\awsService\cloudWatchLogs\commands\tailLogGroup.ts:94:19
at AsyncLocalStorage.run (node:async_hooks:346:14)
<...>
```
The cause for this, is that the event listener for closing the tailing session when Editor tabs close in TailLogGroup is not being disposed of. Disposal happens [here](https://github.com/aws/aws-toolkit-vscode/blob/master/packages/core/src/awsService/cloudWatchLogs/commands/tailLogGroup.ts#L80). However, currently the "mock response stream" in the test blocks indefinitely on …
> test(cwl): Fix TailLogGroup test not disposing its event listeners

- packages/amazonq/test/unit/codewhisperer/util/supplemetalContextUtil.test.ts
> test(inline-suggestion): fix supplementalContextUtil.test failure #6266

- packages/core/src/codewhisperer/client/codewhisperer.ts
Customers that experience transient network issues are unable to view their transformation results when the `GetTransformation` API fails after the default of 3 retries.
Increase retries to 8.
---
> fix(amazonq): increase GetTransformation maxRetries

- packages/amazonq/.changes/next-release/Bug Fix-f7bb3f35-1b43-4604-b3bd-c2e7f1b65083.json
- packages/core/src/amazonqGumby/chat/controller/messenger/messenger.ts
- packages/core/src/amazonqGumby/chat/controller/messenger/messengerUtils.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/service/transformByQ/transformApiHandler.ts
- packages/core/src/codewhisperer/service/transformByQ/transformProjectValidationHandler.ts
- packages/core/src/test/codewhisperer/commands/transformByQ.test.ts
S3 upload sometimes fails due to transient issues.
Add up to 3 retries.
---
> fix(amazonq): retry S3 upload

- packages/amazonq/.changes/next-release/Bug Fix-c0428af9-a9e5-4f7f-a4f3-9cfe4ea851c9.json
- packages/core/resources/css/securityIssue.css
Code block extends beyond margins followed by the rest of the document.
Remove css styles
Before:
After:
---
> fix(amazonq): code block extends beyond margins

- packages/amazonq/.changes/next-release/Feature-06bf59c2-da3f-4ab5-ab86-634b3c25bd5e.json
- packages/core/src/amazonqFeatureDev/client/featureDev.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/amazonqFeatureDev/session/session.ts
- packages/core/src/amazonqFeatureDev/types.ts
- packages/core/src/test/amazonqFeatureDev/controllers/chat/controller.test.ts
This is a part of the task to implement client side alarms in order to track success rate for the client.
- Emit metric data telemetry on success/failure.
---
> telemetry(amazonq): sending metric data in `onCodeGeneration`

- packages/amazonq/test/e2e/amazonq/assert.ts
- packages/amazonq/test/e2e/amazonq/explore.test.ts
- packages/amazonq/test/e2e/amazonq/framework/framework.ts
- packages/amazonq/test/e2e/amazonq/framework/messenger.ts
- packages/amazonq/test/e2e/amazonq/welcome.test.ts
- packages/core/src/amazonq/index.ts
We have no tests for the welcome page and explore agents page
Add them
note: https://github.com/aws/aws-toolkit-vscode/pull/6171 and https://github.com/aws/mynah-ui/pull/204 need to be merged beforehand
---
> test(amazonq): welcome page and explore agents page tests

- packages/core/src/amazonqGumby/chat/controller/controller.ts
- packages/core/src/codewhisperer/commands/startTransformByQ.ts
Be able to tell when a language upgrade vs sql conversion happens.
Add metric.
---
> telemetry(amazonq): add metric for transformation type

- packages/core/src/codewhisperer/client/codewhisperer.ts
We previously increased the maxRetries for GetTransformationJob from 3 to 8 since it's polled every 5 seconds; we should do the same for GetTransformationPlan since it too is polled every 5 seconds.
Increase maxRetries from 3 to 8.
---
> fix(amazonq): increase maxRetries for GetPlan

- packages/amazonq/.changes/next-release/Feature-1e7f3af5-7c94-4c60-8909-a61c0b06e02e.json
- packages/amazonq/test/e2e/amazonq/transformByQ.test.ts
- packages/core/src/amazonqGumby/chat/controller/controller.ts
- packages/core/src/amazonqGumby/chat/controller/messenger/messenger.ts
- packages/core/src/amazonqGumby/chat/controller/messenger/messengerUtils.ts
- packages/core/src/codewhisperer/commands/startTransformByQ.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/service/transformByQ/transformationResultsViewProvider.ts
A "View summary" button was missing in the chat, which made it difficult for users to re-open their transformation summary once they closed it.
Add the button.
---
> feat(amazonq): add view summary button in chat

- packages/core/src/amazonqGumby/chat/controller/controller.ts
- packages/core/src/codewhisperer/service/transformByQ/transformationResultsViewProvider.ts
> telemetry(amazonq): use run block instead of emit

- packages/amazonq/test/unit/codewhisperer/util/zipUtil.test.ts
- packages/core/src/codewhisperer/util/zipUtil.ts
Flaky test `generateZipTestGen` sometimes fails with
```
1) zipUtil
generateZipTestGen
Should generate zip for test generation successfully:
Error: done() called multiple times in test <zipUtil generateZipTestGen Should generate zip for test generation successfully> of file /Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/amazonq/dist/test/unit/codewhisperer/util/zipUtil.test.js; in addition, done() received error: EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, scandir '/test/zip/utgRequiredArtifactsDir'
at Function.e (/private/tmp/.vscode-test/vscode-darwin-arm64-1.83.0/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:26740)
at Object.readDirectory …
```
> test(amazonq): generateZipTestGen is unreliable

- packages/amazonq/.changes/next-release/Removal-aa696d15-306f-4af5-aa4b-ab48c44f0a5e.json
- packages/core/src/amazonq/explorer/amazonQTreeNode.ts
- packages/core/src/auth/auth.ts
- packages/core/src/codecatalyst/activation.ts
- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/codewhisperer/util/codewhispererSettings.ts
- packages/core/src/extensionNode.ts
- packages/core/src/shared/globalState.ts
- packages/core/src/shared/telemetry/activation.ts
- packages/core/src/shared/telemetry/util.ts
- packages/core/src/test/techdebt.test.ts
- packages/toolkit/.changes/next-release/Removal-1c5617ae-50c9-4de1-a191-a2d57dce5bd7.json
- packages/toolkit/.changes/next-release/Removal-6703e62b-3835-402b-b187-b327c58f425b.json
[revert: amazon q standalone special handling](https://github.com/aws/aws-toolkit-vscode/commit/7ae5405b3797ba1b5342dfd7a6de2df4ad453c92) 
Removes code that should no longer be necessary anymore.
- Remove autoinstall Amazon Q if you were a CodeWhisperer user on 2.x versions of toolkit
- The prompt to install Amazon Q will still appear, if you don't have it. It has been slightly reworded.
- If Amazon Q is installed, then you uninstall, it you will not see the prompt again in toolkit (previously you could).
- Remove settings migrations from codewhisperer settings
- Remove amazon Q telemetry enabled setting being initialized by the value from toolkit.
We are still getting hits in telemetry for people getting auto install (172 in last 2 months). However, they are mostly on old versions.
Let's …
> revert: old codepaths from session separation/standalone

- package-lock.json
- packages/amazonq/.changes/next-release/Bug Fix-8434a098-361d-4e8d-9de4-c616da38ccbf.json
- packages/amazonq/.changes/next-release/Bug Fix-acf80397-e84d-430e-b7e2-fec67736338b.json
- packages/amazonq/.changes/next-release/Feature-6e3400cd-def4-4a63-b344-fd7ffa7fa509.json
- packages/core/package.json
Bumped MynahUI to version 4.21.4 from 4.21.2. This includes two bug fixes and one feature, as described by the changelog commits and by the [MynahUI release notes](https://github.com/aws/mynah-ui/releases).
---
> deps(amazonq): bump mynahui to 4.21.4

- packages/amazonq/.changes/next-release/Bug Fix-4f85fc73-11cd-4033-bc93-b49ff3c3e45e.json
- packages/core/src/amazonqFeatureDev/util/files.ts
- packages/core/src/shared/errors.ts
When zipping context for /dev, customer build processes (file watchers, etc.) may delete build artifacts we’ve already enumerated but have not added to the archive. As a best practice, customers should `.gitignore` these types of files, but in the event they don't, this has the potential to block /dev from running.
Skip affected files, which are not found when adding to zip context for Feature Dev.
---
> fix(amazonq): Skip including deleted files for FeatureDev context.

- packages/amazonq/.changes/next-release/Bug Fix-b071ef14-0566-4efa-9a16-43362b87639f.json
- packages/core/src/amazonqTest/chat/controller/controller.ts
/test test generation jobs failed for files open in workspace which do not belong to workspace because of path discrepancies.
Redirecting the test generation for external files with a warning and generating tests for users in chat using conversation APIs instead of test generation workflow.
https://github.com/user-attachments/assets/6cc92ca4-f5ed-40a9-b720-ae2517de51ae
Telemtery will added in followup PR once toolkit common merge happens.
---
> fix(amazonq): fix for /test for files outside of workspace.

- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/core/src/test/credentials/provider/sharedCredentialsProvider.test.ts
- packages/core/src/test/credentials/sso/ssoAccessTokenProvider.test.ts
The Identity team noticed a large spike in token refreshes for specific users. One user would trigger refresh over 50 times within a few seconds.
Ticket: `P180886632`
The telemetry showed that `getChatAuthState()` was being called many times in a short period. This eventually triggered the token refresh logic many times, if the token was expired.
The solution is to add a debounce to `getToken()` which calls the refresh logic.
- `debounce()` only accepts functions without any args, the refresh logic requires args
- `getToken()` will also load from disk is the token is not expired, so debouncing here saves disk I/O as well.
The current debounce interval is 100 milliseconds, which based on telemetry should be enough to capture the barrage of calls. With some manual testing it does not feel …
> fix(auth): debounce getToken() function

- packages/core/src/amazonqDoc/controllers/chat/controller.ts
/doc has adopted another telemetry service, and we need to clean up these unused telemetry methods
Remove unused telemetry methods
---
> telemetry(amazonq): Remove unused Telemetry metric for /doc 

- packages/core/src/codewhisperer/models/constants.ts
Have 2 unused strings
Remove them
---
> refactor(amazonq): remove unused strings

- packages/amazonq/src/lsp/client.ts
In a recent PR we disabled using child_process in favour of our internal one. This started flagging lsp/client.ts, since it wasn't skipped.
Skip eslint for child_process in this case, since the language server options expect the actual child process. The same is done for the workspace context language server: https://github.com/aws/aws-toolkit-vscode/blob/master/packages/core/src/amazonq/lsp/lspClient.ts#L13
---
> ci(amazonq): fix linting issue on language server child process

- packages/core/src/codewhisperer/commands/startTestGeneration.ts
- packages/core/src/codewhisperer/service/testGenHandler.ts
- NumOfUnitTestCasesGenerated shows non 0 value when LinesOfCodeGenerated and CharsOfCodeGenerated are 0
- Occurs only when ExportResultArchive API did not have any generated code or when the job fails
- Reset NumOfUnitTestCasesGenerated to 0 when one of these cases occur 
---
> telemetry(amazonq): numberOfTestsGenerated correctly emits as 0

- packages/amazonq/.changes/next-release/Bug Fix-d8c02c38-bdc4-492a-bf8c-6c35e35087be.json
- packages/core/src/codewhisperer/index.ts
- packages/core/src/codewhisperer/util/customizationUtil.ts
- packages/core/src/test/amazonq/customizationUtil.test.ts
If a user was part of an AB group with a customization override, they could only ever use the customization from the override regardless of personal choice. 
Changes the logic for when a customization will be overridden if the user is part of an AB group that has a customization override. With this change, if the user has manually selected a customization, it will not be overridden by the AB customization.
---
> fix(amazonq): Prevent customization override if user has manually selected a customization

- packages/core/src/test/setupUtil.ts
The CC tests are failing in the auth lambda step, saying that the `user_code` value is not a string
See code for solution
NOTE: This part is now fixed, but the auth lambda itself has its own separate issue that needs to first be fixed
---
> fix(e2e): failing Auth Lambda

- packages/core/src/shared/wizards/wizard.ts
- packages/core/src/test/shared/wizards/wizardTestUtils.ts
The wizard remained in a "not ready" state if a custom `init()` was provided, requiring manual toggles in the test code.
- Wrap the user’s init() with a small decorator that sets _ready = true.
- Remove the manual toggles in wizardTestUtils.ts, letting the wizard handle readiness on its own.
---
> fix(wizard): wizard remains in "not ready" state if a custom init() was provided

- packages/core/src/codewhisperer/commands/startTransformByQ.ts
We search for 4 strings to indicate/infer Oracle SQL is present, including `oracle.jdbc.OracleDriver`, but legacy software can instead contain `oracle.jdbc.driver.OracleDriver`.
Broaden/loosen the validation/search.
---
> fix(amazonq): broaden search strings

- packages/core/src/codewhisperer/models/constants.ts
Link to docs could be helpful in this intro message.
Add it.
---
> fix(amazonq): add link to docs

- packages/core/src/codewhisperer/service/testGenHandler.ts
already has session variable before try block 
remove session variable in the try block
---
> telemetry(amazonq): remove redundant session varaible

- packages/amazonq/.changes/next-release/Bug Fix-72b26a2d-3647-4d07-b0ef-92238e3f0050.json
- packages/amazonq/test/unit/codewhisperer/util/crossFileContextUtil.test.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/util/supplementalContext/crossFileContextUtil.ts
- packages/core/src/test/codewhisperer/testUtil.ts
In some rare cases, the total supplementalContext length exceeds 20k character. With recent service side changes, we need to make sure the total supplementalContext length do not exceed 20k in any situation.
Make sure the total supplementalContext length do not exceed 20k in any situation. Drop when necessary.
This is not customer facing so no change log is attached.
---
> fix(amazonq): max 20k char for inline supplementalContext

- packages/amazonq/.changes/next-release/Feature-37eb706c-57a1-4751-888d-220b2f68ee4d.json
- packages/amazonq/test/e2e/amazonq/welcome.test.ts
- packages/core/src/amazonq/webview/ui/main.ts
- packages/core/src/amazonq/webview/ui/tabs/generator.ts
When working on new features available to AB groups, the new action are not easily discoverable to users
Add the ability to send a new command that will appear when a user types @ in the chat window
---
> feat(amazonq): Adds capability to send new context commands to AB groups

- packages/amazonq/test/unit/codewhisperer/service/recommendationHandler.test.ts
- packages/core/src/codewhisperer/models/model.ts
- packages/core/src/codewhisperer/util/supplementalContext/crossFileContextUtil.ts
- packages/core/src/codewhisperer/util/supplementalContext/supplementalContextUtil.ts
- packages/core/src/codewhisperer/util/supplementalContext/utgUtils.ts
house cleaning and unify naming pattern of this field
corresponding JB commit https://github.com/aws/aws-toolkit-jetbrains/pull/5256/commits/39bc048f2f437213bd25f7b4d32d53cbca9c9988
---
> refactor(inline suggestion): camel case supplemental context strategy ids

- packages/core/src/dev/activation.ts
- packages/core/src/shared/utilities/mementos.ts
It's opening the toolkit global state value instead.
---
> fix(dev): Q developer menu opening wrong auth state

- .eslintrc.js
- packages/core/src/test/testRunner.ts
- Tests were failing or behaving inconsistently on different operating systems due to improper file path normalization.
- End-of-line (EOL) conflicts were causing unnecessary formatting diffs in collaborative workflows.
- Updated the testFile variable in the test runner to normalize paths by replacing backslashes (\) with forward slashes, ensuring cross-platform compatibility.
- Added the Prettier rule 'prettier/prettier': ['error', { endOfLine: 'auto' }] to align EOL behavior with the host environment, avoiding platform-specific conflicts.
--- …
> build(os-compatibility): normalize file paths and enforce eol consistency

- packages/amazonq/test/e2e/amazonq/doc.test.ts
Add E2E test case for /doc: Making a specific change to the README
---
> test(amazonq): add edit README E2E test case for /doc

- packages/amazonq/.changes/next-release/Bug Fix-71c6bbc1-67ae-4318-a7f0-c594e097ebc4.json
- packages/core/src/auth/sso/constants.ts
- packages/core/src/login/webview/vue/backend.ts
- packages/core/src/login/webview/vue/login.vue
- packages/core/src/shared/utilities/uriUtils.ts
- packages/core/src/test/shared/utilities/uriUtils.test.ts
- packages/toolkit/.changes/next-release/Bug Fix-29e6ef4c-536b-47bb-ae27-26b802ccdb65.json
A user reported that a non-standard start url is technically
valid. This is because it can redirect to the underlying valid
start url that matches the pattern: https://xxxxxxxx.awsapps.com/start
Allow any URL, but warn users if they are using a non-standard one.
We will show a yellow warning message in this case.
The red error message is still shown when the input does not match a
URL in general.
---
> fix(sso): login with custom startUrl not allowed

- packages/amazonq/.changes/next-release/Bug Fix-b6d52b75-69e6-47bb-939b-5ddede03f977.json
- packages/core/src/amazonqTest/chat/controller/controller.ts
- Should show a completed message after user completes accept/reject process (just like JB)
- This message does not currently show in VSC
- Show completed message after user completes accept/reject process 
https://github.com/user-attachments/assets/e6e65268-b851-4298-afa6-a784e75dd0a3
---
> fix(amazonq): add message after accept/reject action

- package-lock.json
- package.json
- packages/amazonq/.changes/next-release/Bug Fix-cb743d9a-67da-41a2-bda3-9bc8bfa19b75.json
- packages/core/src/amazonqTest/chat/controller/controller.ts
- packages/core/src/amazonqTest/chat/controller/messenger/messenger.ts
- packages/core/src/codewhisperer/util/telemetryHelper.ts
- The test generation for unsupported language files and external files is unreliable and flaky.
- Telemetry updated to include new metadata for existing metadata.
- Fix to add file name as fallback in case of empty prompt or no code selection.
- Telemetry updated and values passed to it in controller and messenger. Essentially same PR : https://github.com/aws/aws-toolkit-vscode/pull/6323 was closed last week due to build issues.
---
Before:
https://github.com/user-attachments/assets/90ed6629-4753-41e6-9d11-b6d4dd0d6e7c
After fix:
https://github.com/user-attachments/assets/d0993345-cd2c-47ac-a8b5-1e9badf8fbac …
> fix(amazonq): unsupported languages test generation query

- packages/amazonq/.changes/next-release/Feature-7f17c8e5-2242-4a8a-93bc-f7a6c08899dc.json
- packages/core/src/codewhispererChat/editor/context/focusArea/focusAreaExtractor.ts
> feat(amazonq): change active file context limit to 40k

- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/test/amazonqFeatureDev/controllers/chat/controller.test.ts
Previously the logic of showing different messages at different remaining iteration counts are tested manually.
Adding tests to automate the process.
---
> test(amazonq): update tests for messages at different remaining iteration counts

- packages/core/src/amazonqTest/chat/controller/controller.ts
- packages/core/src/amazonqTest/chat/controller/messenger/messenger.ts
- packages/core/src/amazonqTest/error.ts
- packages/core/src/codewhisperer/commands/startTestGeneration.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/service/codeFixHandler.ts
- packages/core/src/codewhisperer/service/securityScanHandler.ts
- packages/core/src/codewhisperer/service/testGenHandler.ts
- packages/core/src/codewhisperer/util/zipUtil.ts
Incorrect handling of errors for 4xx and 5xx on IDE. Proper error messages for users and telemetry needs to differentiate between service errors.
- Adding 4XX vs 5XX `httpStatusCode` field to `amazonq_utgGenerateTests` event.
- Improving error handling in unit test generation.
---
> telemetry(amazonq): Improving error handling and telemetry in unit test generation

- packages/core/src/awsService/appBuilder/explorer/detectSamProjects.ts
- packages/core/src/awsService/appBuilder/explorer/nodes/appNode.ts
- packages/core/src/awsService/appBuilder/explorer/nodes/deployedNode.ts
- packages/core/src/awsService/appBuilder/explorer/samProject.ts
- packages/core/src/awsService/appBuilder/utils.ts
- packages/core/src/awsService/appBuilder/walkthrough.ts
- packages/core/src/test/awsService/appBuilder/explorer/detectSamProjects.test.ts
- packages/core/src/test/awsService/appBuilder/explorer/samProject.test.ts
- packages/core/src/test/awsService/appBuilder/utils.test.ts
- packages/core/src/test/awsService/appBuilder/walkthrough.test.ts
- packages/core/src/test/shared/applicationBuilder/explorer/nodes/appNode.test.ts
- packages/core/src/test/shared/applicationBuilder/explorer/nodes/deployedNode.test.ts
- packages/toolkit/.changes/next-release/Bug Fix-b033b55b-52a5-488a-a4a7-c3228232bca6.json
Several errors that were being shown to customers did not have enough information for them to take action on the problem.
Audited all errors and logs shown to customers and updated them to make them more legible and actionable.
---
> fix(lambda): Update error messaging in AppBuilder

- packages/core/src/lambda/commands/downloadLambda.ts
- packages/core/src/shared/resourcefetcher/httpResourceFetcher.ts
- packages/core/src/shared/resourcefetcher/node/httpResourceFetcher.ts
- packages/core/src/shared/utilities/cliUtils.ts
- packages/core/src/test/awsService/appBuilder/walkthrough.test.ts
- Resource fetcher currently only works on node. This causes some implements to use got directly, some use fetch directly, some use httpResourceFetcher depending on their use case
- Make HttpResourceFetcher platform independent so it can run on node + web
- Move the streaming based HttpResourceFetcher to a node specific folder
---
> refactor(core): Make HttpResourceFetcher platform agnostic

- packages/core/src/codewhisperer/client/codewhisperer.ts
Revert endpoint change in previous commit: https://github.com/aws/aws-toolkit-vscode/commit/062d24a8dad43527bf3fd52f80b60fecce876de5
---
> revert(amazonq): defaultServiceConfig endpoint change

- packages/amazonq/.changes/next-release/Bug Fix-34e877a1-d2ca-4c93-9dee-5dd2019769fe.json
- packages/core/src/amazonq/webview/ui/apps/testChatConnector.ts
User can only view file diff by clicking the viewdiff button. This fix allows user view the file diff by clicking the file in file tree and update UI accordingly. 
https://github.com/user-attachments/assets/bd521c11-b881-4c52-80d9-5db225067ef6
Update the onFileDiff function on testChatConnector. Send the file diff open request there and implement the onChatAnswerReceived function to handle the followup functionality. 
---
> fix(amazonq): User can view file diff by file click

- packages/core/src/shared/request.ts
Only 200-299 are treated as "response.ok" responses by fetch. However, 304's (content not modified) are valid response codes as well
If the status code is 304 then don't throw
---
> ci(core): Request should not throw on 304 status

- packages/core/package.nls.json
A phrase is repeated in the error message for prompt refusal when updating a README in /doc
Fix error message for prompt refusal
Note: changelog is not updated since error message updating already included [in changelog for this release](https://github.com/aws/aws-toolkit-vscode/commit/bcdfcdd5d87e90c2d7bdd6a3f7a9b0112eb7bc00#diff-6edd3b49931bb5d80cf0b6d048305bb4902587900e26fea567efe8a1bca38decR3)
---
> fix(amazonq): /doc prompt refusal error message text update

- package-lock.json
- packages/amazonq/test/unit/codewhisperer/service/securityScanHandler.test.ts
- packages/core/package.json
- packages/core/src/test/codewhisperer/commands/transformByQ.test.ts
- packages/core/src/test/codewhisperer/testUtil.ts
Update `aws-sdk` to v2.1692.0
The `Response` class in AWS SDK changed the signature of the `nextPage` method, so some tests that were mocking this method had to be updated accordingly (changing the response from `undefined` to `null`).
The definition changed from 
```
nextPage(callback?: (err: E, data: D) => void): Request<D, E>|void;
```
(callback optional, can return `void`)
To 
```
nextPage(): Request<D, E> | null;
nextPage(callback: (err: E, data: D) => void): void;
```
(can return `null` if no callback. only when a callback is passed returns `void`)
The version of the AWSK SDK v2 was outdated 1.5 years, so some newer functionality was not available.
Update the version of `aws-sdk` package to the latest version.
---
- Treat all work as PUBLIC. Private `feature/x` branches will not be …
> deps: Update "aws-sdk" to v2.1692.0

- packages/core/src/awsService/apprunner/explorer/apprunnerNode.ts
- packages/core/src/awsService/ec2/explorer/ec2ParentNode.ts
- packages/core/src/shared/utilities/pollingSet.ts
- packages/core/src/shared/utilities/processUtils.ts
- packages/core/src/test/awsService/ec2/activation.test.ts
- packages/core/src/test/awsService/ec2/explorer/ec2InstanceNode.test.ts
- packages/core/src/test/shared/utilities/pollingSet.test.ts
Right now `PollingSet` exposes both the `add` and the `start` methods. The `start` adds the item and starts the timer, while the `add` only adds the item. 
This allows a consumer to create a non-empty `PollingSet` where the timer never started. 
- override the add method so that a consumer is forced to start the timer when adding items. 
---
> refactor(pollingset): make bad state impossible

- packages/amazonq/.changes/next-release/Bug Fix-a49b3835-40c5-4878-ac0c-c4c613f1bf97.json
- packages/amazonq/package.json
- packages/toolkit/.changes/next-release/Bug Fix-f7aec5a8-a21c-4539-9ed4-820dd9887598.json
- packages/toolkit/package.json
Gets rid of these
You can still dismiss by clicking the X button next to non-emergency notifications.
---
> fix(notifications): dismiss command visible in command palette

- packages/core/src/extension.ts
- packages/core/src/shared/regions/regionProvider.ts
While starting the release process we found an problem where the endpoints couldn't be fetched because the resourceFetcher was expecting a string but the httpResourceFetcher was returning a Resource
If its a string then return the contents from the resource fetcher directly, otherwise consider it as a response and get the text from the request
---
> fix(core): Could not fetch endpoints

- packages/core/src/notifications/controller.ts
- packages/core/src/shared/crashMonitoring.ts
- packages/core/src/shared/resourcefetcher/httpResourceFetcher.ts
- packages/core/src/shared/utilities/functionUtils.ts
- packages/core/src/shared/utilities/timeoutUtils.ts
- packages/core/src/test/notifications/controller.test.ts
- packages/core/src/test/shared/utilities/functionUtils.test.ts
- packages/core/src/test/shared/utilities/timeoutUtils.test.ts
We had 2 different implementation of similar code, between withRetries and waitUntil.
We couldn't easily merge them though since behavior was slightly different when it came to expected return types, and since one threw and the other did not.
- waitUntil returns undefined if it never properly resolves
- withRetries throws if it never properly resolves
As a solution we keep both methods but they share the same underlying code.
- waitUntil now has a backoff field to increase the delta between intervals
- withRetries also has this
- withRetries will retry even on a thrown exeception
- on timeout it will throw the last exception it encountered
--- …
> refactor(util): merge withRetries and waitUntil

- packages/core/src/shared/lsp/lspResolver.ts
- packages/core/src/shared/lsp/manifestResolver.ts
- packages/core/src/shared/resourcefetcher/httpResourceFetcher.ts
- packages/webpack.web.config.js
Now that we've refactored the httpResourceFetcher a little bit we can use that for fetching both the manifest and the language server
---
> refactor(core): Manifest/LSP fetching should use httpResourceFetcher

- .changes/next-release/Bug Fix-77137e24-593d-4859-a15f-e029edf843a7.json
- packages/core/src/shared/clients/s3Client.ts
S3 tree view doesn't show contents with specific IAM role policies. Prefix parameter was null.
Set Prefix parameter to an empty string as default. Allows bucket contents display if root prefix is allowed.
#4643 S3 Tree View Not Displaying Bucket Contents with Specific IAM Role Policies
> fix(S3 View): Display bucket contents with specific IAM role policies

- packages/core/src/shared/clients/s3Client.ts
Currently seeing the following error on master 
```
passes eslint:
AssertionError [ERR_ASSERTION]: ,
/home/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/src/shared/clients/s3Client.ts
Error:   468:[31](https://github.com/aws/aws-toolkit-vscode/actions/runs/12991583651/job/36229470175#step:6:32)  error  Delete `·`  prettier/prettier`
```
- delete the extra space. 
---
> fix(lint): remove extra space so that lint passes. 

- .github/workflows/node.js.yml
The "jscpd" CI check tends to be ignored by contributors, possibly because its purpose is not clear.
Rename it.
---
> ci: rename "jscpd" job to "lint-duplicate-code"

- buildspec/release/70checkmarketplace.yml
Our release MCM currently has a step for each extension (Toolkit and Q) that requires the human operator to wait and check for the marketplace publish and then try to install from the marketplace. This uses human time and can easily be automated.
Added a final stage in release pipeline: https://code.amazon.com/reviews/CR-173945904/revisions/1#/commits
that runs this YML build script that automatically installs and uninstalls the extension from marketplace on a two minute interval. 
When the version matches the new release version, the code-build succeeds:
When it doesn't, it keeps retrying until the timeout limit is reached (1 hour):
--- …
> feat(release): check for marketplace update

- packages/amazonq/test/unit/amazonqFeatureDev/util/files.test.ts
- packages/core/src/amazonqFeatureDev/util/files.ts
- packages/core/src/shared/filetypes.ts
- packages/core/src/shared/utilities/workspaceUtils.ts
- packages/core/src/test/shared/filetypes.test.ts
* Fixes for execution engine
* Don't drop binary files matching with extra gitignore rules
* Don't drop `.gitignore` file from repository.
> fix(amazonq): Allow including binary files when execution is enabled

- package-lock.json
- package.json
- packages/amazonq/test/unit/codewhisperer/service/securityScanHandler.test.ts
- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/codewhisperer/models/model.ts
- packages/core/src/codewhisperer/service/securityScanHandler.ts
Need to understand:
- How many users are using fix feature from /review (not auto-review)
- How many fixes were generated/applied for each scanJob
- How many code fix requests were unable to generate a fix
- Add flag `autoDetected` to be able to filter out auto-review findings
- Add flag `includesFix` to be able to see fix requests that generated no fixes
- Add `codewhispererCodeScanJobId` to associate a fix action with a specific scan that produced the finding
---
- License: I confirm that my contribution is made under the terms of the Apache …
> telemetry(amazonq): add fields for code fix events

- packages/core/src/test/shared/awsClientBuilderV3.test.ts
The client should not be making requests with stale credentials so we want test coverage to ensure this
- Create a mock credentials shim and insert it into the global context.
- The client builder will then use that shim, and we can manually expire it.
- Ensure client does not cache potentially stale credentials.
---
> test(sdkv3): add tests for expiring credentials

- packages/amazonq/package.json
- packages/amazonq/test/unit/amazonqFeatureDev/util/files.test.ts
- packages/core/package.nls.json
- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/amazonqFeatureDev/util/files.ts
- packages/core/src/codewhisperer/util/codewhispererSettings.ts
- packages/core/src/shared/clients/s3Client.ts
- packages/core/src/shared/settings-amazonq.gen.ts
"Dev Command Workspace Configurations" is overly broad and too ambiguous with regards to what this setting enables. 
Worked with tech writer to establish a different string to present to customers.
---
> docs(amazonq): Update /dev auto build setting strings

- package-lock.json
- packages/amazonq/.changes/next-release/Bug Fix-8212e8e4-f65f-4594-a04f-76d47c61b41e.json
- packages/core/package.json
- Links incoming from Q responses can redirect to a vulnerable site depending on the used context from the files.
- Linkify strategy is updated to only accept links with `[TEXT](URL)` format. (through MynahUI version [4.21.6](https://github.com/aws/mynah-ui/releases/tag/v4.21.6))
MynahUI PR:
https://github.com/aws/mynah-ui/pull/226
---
> fix(amazonq): For security reasons, disabled auto linkify for pure text links

- packages/amazonq/.changes/next-release/Bug Fix-1d7e776d-333a-4f39-a8e6-29ea2ecb19c9.json
- packages/core/src/codewhisperer/util/customizationUtil.ts
- packages/core/src/test/amazonq/customizationUtil.test.ts
Users that are part of an AB group that have a customization override can't go back to the default customization. This was the original intention but has been relaxed after feedback.
Update setSelectedCustomization to no longer check if the user is trying to switch back to the default customization.
---
> fix(amazonq): Allow AB users with an overriden customization to go back to the default customization

- packages/core/package.nls.json
- packages/core/src/awsService/appBuilder/explorer/nodes/deployedNode.ts
- packages/core/src/awsService/cloudWatchLogs/activation.ts
- packages/core/src/awsService/cloudWatchLogs/commands/tailLogGroup.ts
- packages/core/src/awsService/cloudWatchLogs/wizard/tailLogGroupWizard.ts
- packages/core/src/lambda/activation.ts
- packages/core/src/test/awsService/cloudWatchLogs/commands/tailLogGroup.test.ts
- packages/core/src/test/awsService/cloudWatchLogs/wizard/tailLogGroupWizard.test.ts
- packages/toolkit/.changes/next-release/Feature-48c399ea-d42f-4ea1-8f32-d8bc1486a107.json
- packages/toolkit/package.json
Allow to "Tail Logs" from Lambda functions, which will get the configured Log Group for a particular function and start a Live Tail session in that Log Group.
Some code was removed, because with the recently updated version of the SDK v2, we can take the configured log group directly from the function's configuration and we don't need that extra call using SDK V3 that was being made inside `deployedNode.ts`
To start a CloudWatch Live Tail session, a user needs to know their Log Group name and find it in the AWS explorer. For Lambda users, that might not be easy to find or well known all the time
We help the Live Tail experience for Lambda customers by allowing them to start a Live Tail session directly from their function in the AWS explorer and in the Application Builder section for …
> feat(lambda): Connect CW Live Tail to Lambda functions

- packages/amazonq/.changes/next-release/Bug Fix-e2bb3c83-52e8-4ae9-aedb-844e8780971b.json
- packages/core/src/amazonq/onboardingPage/walkthrough.ts
- packages/core/src/codewhisperer/vue/genSuggestionTab.vue
The first Amazon Q inline suggestion example is missing a closing bracket, and the returned response often excludes it.
Simplifying the example by just including the closing bracket.
- Failing tests and lints appear to be unrelated to the changes in this PR.
- "RemoteFetcher" test failed, unrelated.
- "lint-duplicate-code" is referencing unrelated code.
- Just updating example code, so 0% code coverage is expected.
---
> fix(example): Add closing bracket to Amazon Q inline example

- package-lock.json
- packages/amazonq/.changes/next-release/Bug Fix-22f55c14-bd62-49d7-aa68-3ab3cc8f0929.json
- packages/core/package.json
- The citation links are broken after the [linkify structure change](https://github.com/aws/aws-toolkit-vscode/pull/6449).
- Updated link check pattern to accept `[[TEXT]](LINK)` format too which is used for citations. **[MynahUI v4.22.1](https://github.com/aws/mynah-ui/releases/tag/v4.22.1)**
[MynahUI PR](https://github.com/aws/mynah-ui/pull/228)
---
> fix(amazonq): Broken citation links

- packages/amazonq/.changes/next-release/Bug Fix-dc78e630-6320-4297-9ae9-7a19891f5357.json
- packages/core/src/amazonqTest/chat/controller/controller.ts
- Placeholder texts are different between VSC and JB for /test
- update placeholder text so it is consistent between the two after UTG Completion, UTG Reject, UTG Cancel
---
> fix(amazonq): /test align placeholder text across IDEs

- packages/amazonq/test/e2e/amazonq/featureDev.test.ts
2 Amazon Q feature dev e2e tests are failing in CI (but work fine locally).
Temporarily disabled these tests to unblock green CI while we investigate.
---
> test: disable feature dev unstable e2e tests

- packages/amazonq/.changes/next-release/Bug Fix-5c9f7fbc-1333-4c28-a049-7b17a17a7cea.json
- packages/core/src/amazonq/lsp/lspController.ts
The LSP cannot start in AL2023 arm64.
Update the binary of linux arm64 to make it compatible with both AL2023 and Ubuntu arm64
---
> fix(amazonq): Fix LSP start failure in al2023 arm64

- package-lock.json
- packages/core/package.json
- packages/toolkit/.changes/next-release/Feature-f899524a-1862-4e6f-a10a-bda639f1e792.json
Step Functions: Upgrade amazon-states-language-service to 1.15. This new version enhance autocomplete for variable and JSONata expression in JSON ASL files.
[Variables and JSONata](https://aws.amazon.com/blogs/compute/simplifying-developer-experience-with-variables-and-jsonata-in-aws-step-functions/) was a Step Funtions feature released in 2024 Nov
---
> feat(toolkit): Enhance autocomplete for variable and JSONata expression in JSON ASL files.

- packages/toolkit/.changes/next-release/Feature-7dc599c8-77a6-423f-960e-eb32687d7714.json
- packages/toolkit/.changes/next-release/Feature-8fa49dc1-d427-4bff-adb1-7e0f11c3d866.json
Changelog is missing for the Step Functions Workflow Studio integration
Added Changelog for Workflow Studio integration, and a separate one for TestState in the integration.
---
> docs(stepfunctions): add changelog for Workflow Studio and TestState

- packages/core/src/codewhisperer/service/securityScanHandler.ts
- packages/core/src/codewhisperer/service/testGenHandler.ts
Regression in API Back off and retry. Not necessary for VSC.
This reverts commit 3a03e95599e5254341ee4e8acae6c39bdeee70a8.
---
> perf(amazonq): Revert backoff and retry for /test APIs (#6461)

- packages/amazonq/.changes/next-release/Bug Fix-c3484e6b-4093-4d35-8964-b5d07fb76469.json
- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- packages/core/src/codewhisperer/index.ts
- packages/core/src/codewhisperer/service/securityIssueTreeViewProvider.ts
- packages/core/src/test/codewhisperer/startSecurityScan.test.ts
Issues detected by auto-review feature are not populating the code issues treeview list unless you run a manual `/review` first.
This issue is happening because `vscode.window.createTreeView` is hidden inside `SecurityIssuesTree` class which only gets invoked when you call `SecurityIssuesTree.instance.focus()`. Since we don't want to focus the tree view for auto-reviews, the treeview itself is never created.
Move the treeview creation to activation so that it always gets created when the extension is activated
--- …
> fix(amazonq): auto-review doesn't populate treeview

- packages/amazonq/test/e2e/amazonq/testGen.test.ts
- valid language tests are flaky, specifically the "before each" hook is failing in the CI for valid language
- skip valid language tests for now
These changes will be helpful for when we come back to this issue:
- use closeAllEditors function in existing testUtils file
- retries for setting up and opening text file
---
> test(amazonq): skip valid language tests

- packages/amazonq/.vscode/launch.json
If you have amazon q locally and start a debugging session, pressing stop can sometimes crash the entirety of vscode
remove [debugWebviews](https://github.com/microsoft/vscode-js-debug/blob/main/OPTIONS.md#rendererdebugoptions)/[rendererDebugOptions](https://github.com/microsoft/vscode-js-debug/blob/main/OPTIONS.md#rendererdebugoptions) from amazon q's launch config since they cause the local amazon q webview to attach to the debug instance which coincidentally ends up crashing vscode when extension debugging is stopped
---
- License: I confirm …
> fix(amazonq): debugging amazon q can crash vscode

- packages/core/package.nls.json
A line in [packages/core/package.nls.json](https://github.com/aws/aws-toolkit-vscode/compare/master...witness-me:fix-lint?expand=1#diff-4d90099a916e267c6fa8cfeeec9c569c4889dc50cb53178e1c748d0d37ff501e) contains extra space, which is inconsistent with current code style
Remove extra space
---
> fix(lint): Remove extra space

- packages/core/src/awsService/appBuilder/explorer/samProject.ts
- packages/core/src/lambda/vue/configEditor/samInvokeBackend.ts
- packages/core/src/lambda/vue/configEditor/samInvokeComponent.vue
- packages/core/src/lambda/vue/configEditor/samInvokeFrontend.ts
- packages/core/src/test/lambda/vue/samInvokeBackend.test.ts
- packages/toolkit/.changes/next-release/Feature-b2217598-82cb-4268-b731-e137fa6a92e8.json
Update support for enVar in the webview
---
> fix(appbuilder): Update support for enVar in the webview

- packages/core/src/codewhisperer/service/transformByQ/transformApiHandler.ts
When API calls fail, it can be difficult to debug without the requestId.
Log entire error to ensure we have all relevant details, not just the error message.
---
> fix(amazonq): log full error

- packages/core/src/auth/auth.ts
- packages/core/src/shared/utilities/functionUtils.ts
- packages/core/src/test/shared/utilities/functionUtils.test.ts
`debounce` is reimplemented in multiple places. There is `debounce`: https://github.com/aws/aws-toolkit-vscode/blob/100eb0737789d9d5ba4b04e055730b467bd97e14/packages/core/src/shared/utilities/functionUtils.ts#L89-L108
`cancellableDebounce`: https://github.com/aws/aws-toolkit-vscode/blob/100eb0737789d9d5ba4b04e055730b467bd97e14/packages/core/src/shared/utilities/functionUtils.ts#L114-L147
and a very similar function `keyedDebounce`: https://github.com/aws/aws-toolkit-vscode/blob/100eb0737789d9d5ba4b04e055730b467bd97e14/packages/core/src/auth/auth.ts#L107-L122
These functions should share common implementation logic, and live in the same place for easier discoverability. 
- reimplement `debounce` in terms of `cancellableDebounce` since its a special case. 
- move these functions to shared, …
> refactor(debounce): avoid reimplementations of the same logic. 

- packages/amazonq/src/lsp/lspInstaller.ts
Amazon q currently uses the 2.3.2 version of the language server which doesn't appear to be working
Update to the 3.x.x series for now
Independently i'm going to follow up with teams to understand how this happened. Had we released this feature to prod amazon q inline would have been completely broken
---
> deps(amazonq): Update amazon q language server to 3.x.x

- packages/amazonq/src/extensionNode.ts
- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/test/credentials/sso/ssoAccessTokenProvider.test.ts
getChatAuthState() is called in many places by the Q features simultaneously,
this eventually triggers multiple calls to getToken() and if needed refreshToken().
This resulted in refreshToken being spammed and the Identity team seeing spikes in token refreshes
from clients.
Throttle getChatAuthState().
Throttling w/ leading: true, allows us to instantly return
a fresh result OR a cached result in the case we are throttled. Debounce on the
other hand would cause callers to hang since they have to wait for debounce to timeout.
Also, we put a debounce on getToken() before in #6282 but this did not work since a new
SsoAccessToken instance is created each time the offending code flow triggered (we could
look to cache the instance instead which would enable the getToken() debounce to be useful. …
> fix(auth): token refresh rapidly called unexpectedly

- packages/amazonq/.changes/next-release/Feature-f0b1a42d-ee00-4b68-9160-cbae9bd27873.json
- packages/amazonq/test/e2e/amazonq/transformByQ.test.ts
- packages/core/src/amazonqGumby/chat/controller/controller.ts
- packages/core/src/amazonqGumby/chat/controller/messenger/messenger.ts
- packages/core/src/amazonqGumby/chat/controller/messenger/messengerUtils.ts
- packages/core/src/codewhisperer/client/user-service-2.json
- packages/core/src/codewhisperer/commands/startTransformByQ.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/models/model.ts
- packages/core/src/codewhisperer/service/transformByQ/transformApiHandler.ts
Support transformations to Java 21.
Add support.
---
> feat(amazonq): java21 support

- packages/core/src/amazonqGumby/errors.ts
- packages/core/src/codewhisperer/service/transformByQ/transformApiHandler.ts
1) we already have logic to show the user the request ID of the last failed API call 
2) we also already have logic to show them the failure reason
3) when a job is stopped, we don't expect anything to be present in the `reason` field
Remove param
---
> fix(amazonq): remove requestId param

- packages/amazonq/.changes/next-release/Bug Fix-704d175a-a99f-4ce7-bf08-b94d6f7218c0.json
- packages/core/src/amazonq/apps/initContext.ts
- packages/core/src/amazonq/messages/messagePublisher.ts
- packages/core/src/amazonq/webview/messages/messageDispatcher.ts
- packages/core/src/shared/logger/logger.ts
When a user starts up VSC, hasn't opened Q chat yet, then highlights text and does a right click option like "send to prompt" THEN the whole prompt fails to make it to chat.
This is because there is a race condition between the message being sent to the webview, and the webview completed loading and ready to recieve messages.
In the appToMessage publisher, verify that the chat is ready to recieve messages based on if the webview sent the chat ui ready message. Otherwise wait until we get it, and then send the message.
https://github.com/user-attachments/assets/baf86737-4a5a-4f80-86fb-9abca2c56827
https://github.com/user-attachments/assets/c3361403-5dae-49df-a878-94722eb4fc62
---
- Your code …
> fix(amazonq): right click options dont send context if chat not loaded

- packages/amazonq/.changes/next-release/Feature-d9128dff-2867-4bf4-9046-2a52a36803d7.json
- packages/core/src/codewhisperer/commands/startTransformByQ.ts
Transformation results/artifacts expire after 24h, and sometimes users forget to manually click the "Download Proposed Changes" button within that time period.
Auto-download the results from S3 when ready.
---
> feat(amazonq): auto-download results

- packages/core/src/shared/regions/regionProvider.ts
- packages/core/src/testInteg/regionProvider.test.ts
In the release yesterday we found an issue where fetching remote region data was failing
Add a new test since its critical to the flow
---
> test(toolkit): Add region provider remote test

- packages/core/src/shared/lsp/utils/platform.ts
The leading `''` when not in debug mode made the process start but not accept any events
Only prepend the `inspect` args when required
---
> fix(amazonq): language server fails to start in non-debug mode

- packages/amazonq/src/lsp/lspInstaller.ts
- packages/amazonq/test/e2e/lsp/lspInstaller.test.ts
- packages/core/src/shared/lsp/lspResolver.ts
We can't consume prerelease versions from the gamma manifest
Support pre release lsp versions + test
- I'll have another PR soon that pulls out the configuration so we can switch manifest urls for testing pretty easily
- E2E tests won't work until https://github.com/aws/aws-toolkit-vscode/pull/6538 is merged
---
> feat(amazonq): Support pre-release LSP versions

- packages/amazonq/src/lsp/client.ts
In the last few months we reduced the amount of output channels. This includes having the workspace context language server log to the "Amazon Q logs" output channel. However, the codewhisperer language server always creates the "Amazon Q Language Server" output channel
When the trace server is enabled ('amazonq.trace.server' in the vscode settings), output to a seperate channel because its extremely noisy, otherwise send the logs to the "Amazon Q Logs" output channel
---
- License: I confirm that my contribution is made under the terms of the …
> fix(amazonq): Split trace server logs into separate output channel

- packages/amazonq/test/e2e/amazonq/featureDev.test.ts
- packages/amazonq/test/e2e/amazonq/framework/framework.ts
Amazon Q feature dev e2e test was disabled due to flakiness. Issue: #6513 
- Modified test prompt to prevent no change required scenarios that were causing deadend.
- Add `getSelectedTab` function in `qTestingFramework` to access newly created tab by quick action.
---
> test(e2e): stabilize Amazon Q feature development tests

- packages/amazonq/.changes/next-release/Bug Fix-cd65fb78-14de-4214-baac-2e998c4fb143.json
- packages/core/src/amazonqTest/chat/controller/controller.ts
- packages/core/src/codewhisperer/commands/startTestGeneration.ts
- packages/core/src/codewhisperer/service/testGenHandler.ts
-  If user tries to run `/test` on the test file, Q considers test file as source file and starts the test generation on the test file.
- If user tries to run `/test` on the test file, Q infers the context from the original source file and generate tests accordingly.
- No change in functionality, minor change in UX filename.
---
> fix(amazonq): Q infers source file from active test file for UTG.

- packages/core/src/auth/providers/credentialsProviderManager.ts
- packages/core/src/test/techdebt.test.ts
Alternative solution to https://github.com/aws/aws-toolkit-vscode/pull/6541
- debounce very aggressively (once per day).
- remove debugging `function_call`. 
debounce ignores args, so regardless of the telemetry metadata, it will only be emitted once per day. That is, regardless of the value of `credentialsSourceId`, it is emitted once per day. 
---
> telemetry(auth): debounce `aws_loadCredentials` more aggressively and remove debugging. 

- packages/amazonq/.vscode/tasks.json
- packages/core/package.json
- packages/core/scripts/build/checkServerPort.ts
In our development build we spawn a webpack server that serves the Vue files used by our webviews. It is served on port 8080, but sometimes an existing process is already using it, and this causes the webpack server to use the next available port. But because we assume it will use 8080 it silently breaks, and when developing the Q webview would not load as expected.
Explicitly require 8080 in the webpack server cli command, also create a custom script to catch the error early and explain how to resolve it.
Now in the build tasks if 8080 is in use the dev can see the failed task with the solution explicitly stated.
--- …
> fix(build): webviews sometimes did not load during development

- packages/core/src/codewhisperer/service/transformByQ/transformMavenHandler.ts
After entering JDK path, chat is sometimes frozen until the local build completes.
Pause after user enters JDK path, to give chat time to update before starting the local build.
---
> fix(amazonq): let chat update after entering jdk path

- packages/core/src/lambda/vue/remoteInvoke/remoteInvoke.vue
- packages/core/src/lambda/vue/remoteInvoke/remoteInvokeFrontend.ts
Today Remote Invoke call ListRemoteTestEvent every instances the webview is spun up. This pr introduces condition for which this api calls can be made thereby reducing the spike in number failures we see in our dashboard.
Note: we currently don't have test for frontend logic, however extensive testing was conducted.
---
> refactor(appbuilder): reduce number of ListRemoteTestEvent calls by remote invoke

- packages/amazonq/src/extension.ts
- The amazonqLSP flag is only checked at start. This sidesteps the amount of work that would be required to enable/disable codewhisperer at runtime. However, its not obvious they need to restart their editor
- Notify users that they should reload when they change the experiments setting
---
> feat(amazonq): Notify users to reload when amazonqLSP experiment flag has changed

- packages/amazonq/src/lsp/client.ts
- packages/core/src/auth/sso/ssoAccessTokenProvider.ts
- packages/core/src/shared/extensionUtilities.ts
Initialization name is just dummy text for now. We should consider updating it to the c9/toolkit one
---
> fix(amazonq): Update initializationOptions extension name

- packages/core/src/testInteg/globalSetup.test.ts
Features that depend on global state can cause test failures locally because the tests will use your current global state settings instead of a fake state for integ/e2e tests
integ/e2e tests should use a fake global state instead that automatically gets reset after each test
---
> test(core): Use a fake global state for integ/e2e tests

- packages/amazonq/test/e2e/amazonq/framework/framework.ts
- packages/amazonq/test/e2e/amazonq/framework/messenger.ts
- after https://github.com/aws/aws-toolkit-vscode/commit/19d0346db98d45480f9909629b50daf31cba1186 the listener adds messages in a buffer until the ui is ready. It looks like some messages get caught in the buffer during tests since the mynah ui activation is slightly different there
- The waitUntil was waiting until an event evaluated to true and then afterwords checks to see if that same event is still true. This was causing an issue where if the event originally evaluated to true and then instantly evaluated to false, your tests would fail
- manually set the ui ready after we've created the mynah ui instance in tests
--- …
> test(amazonq): Set UI ready before executing amazonq e2e tests

- packages/core/src/lambda/vue/configEditor/samInvokeBackend.ts
- packages/toolkit/.changes/next-release/Feature-d85ac3b3-0e30-41fd-9dc1-1d214275189a.json
Users have to re-select a debug config every time when open the Invoke and Debug webview
Automatically load the first matching debug configuration when the local invoke view is opened
Note: No UI tests. https://github.com/aws/aws-toolkit-vscode/blob/master/docs/TESTPLAN.md#testing-gaps
---
> feat(lambda): Autoload debug config when the local invoke view is opened

- packages/core/src/auth/credentials/utils.ts
- packages/core/src/test/credentials/provider/sharedCredentialsProvider.test.ts
https://github.com/aws/aws-toolkit-vscode/issues/6594
The `getMfaCodeFromUser` currently uses a deprecated version of `createInputBox` and the following `promptUser` function: 
https://github.com/aws/aws-toolkit-vscode/blob/0fa1b5b47ab642458df934192832a4ffcb6c9d1e/packages/core/src/shared/ui/input.ts#L72-L135
Based on the stack trace, there is a race condition here that can lead to a type error, but unsure how?
Stack trace: 
```
TypeError: inputBox.hide is not a function
at promptUser (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/src/shared/ui/input.ts:133:18)
at async getMfaTokenFromUser (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/src/auth/credentials/utils.ts:124:19)
at async …
```
> test(auth): avoid deprecated InputBox usage that caused flakiness. 

- packages/amazonq/.changes/next-release/Bug Fix-037e19bd-95f5-4cdf-8408-6eb273ff7ebd.json
- packages/amazonq/test/unit/amazonqFeatureDev/util/files.test.ts
- packages/core/src/amazonq/util/files.ts
Stuck on "Uploading code..." for /dev and /doc in a multi-root workspace with the same file paths in it multiple times.
Add a check to prevent same file from being added to archive twice
Fixes issue https://github.com/aws/aws-toolkit-vscode/issues/6566
---
> fix(amazonq): Prevent adding same file twice for /doc and /dev

- buildspec/release/80notify.yml
- buildspec/release/notify.txt
Will enable for prod once I confirm it outputs the proper messages.
---
> ci: add post-release notification buildspec

- packages/amazonq/.changes/next-release/Bug Fix-eac82ab9-bdab-47c4-834d-600cb1a0b6a2.json
- packages/core/src/codewhisperer/service/transformByQ/transformationResultsViewProvider.ts
View Summary button wasn't working after users accept changes, since we save the `summary.md` to where their project is locally.
Update summary file path.
---
> fix(amazonq): fix view summary button

- packages/core/src/shared/sam/build.ts
- packages/core/src/test/shared/sam/build.test.ts
- packages/toolkit/.changes/next-release/Bug Fix-f7a3ecad-06a7-48cd-896b-2285ea95bd84.json
When users use appbuilder to build their lambda functions, they choose between using their samconfig file or manually selecting the build parameters/flags. The problem is that when the user selects build flags and intentionally doesn't select the ```--use-container``` flag, the command will still be run with --use-container if the samconfig file has ```use_container``` is set to true.
Whenever the user manually selects the build flags and doesn't select ```--use-container```, we add the negative version of ```--use-container```, which is ```--no-use-container```. This serves as an override if the samconfig file has ```--use-container``` set to true.
---
- Your code changes must meet the …
> fix(appbuilder): pass in the negative version of --use-container when using build quickpick

- buildspec/release/80notify.yml
- Enable for prod runs
- Fix script slightly because the way codebuild runs bash and the way my local runs bash seems to not be the same.
- Tested on dev release pipeline
---
> ci: fix and enable post-release notification

- packages/core/src/codewhisperer/models/constants.ts
Increase in codefix timeouts
Increase default timeout and lower the polling frequency
---
> config(amazonq): update polling config for codefix

- packages/amazonq/.changes/next-release/Bug Fix-c8a60497-e42c-4141-bcfe-2c44188bc98b.json
- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/service/diagnosticsProvider.ts
- packages/core/src/codewhisperer/service/securityIssueProvider.ts
- packages/core/src/shared/utilities/commentUtils.ts
- packages/core/src/test/shared/utilities/commentUtils.test.ts
Auto-reviews often produce less code issues than manual reviews, but the current behavior is to remove all the issues in the file when processing the new ones. This means that issues discovered by manual reviews but not auto-reviews will silently disappear if auto-reviews is enabled.
- Auto-reviews should not clear the previous issues, but instead merge in the new results to the existing group.
- Fixed a related issue with the `ignoreIssue` command being flaky
---
- License: I confirm that my contribution is made under the terms of the Apache …
> fix(amazonq): auto-review removes existing issues

- packages/core/src/auth/activation.ts
> refactor(cleanup): remove dead code

- packages/amazonq/src/extension.ts
- packages/core/src/auth/utils.ts
- packages/core/src/login/webview/commonAuthViewProvider.ts
- packages/core/src/login/webview/vue/backend.ts
- packages/core/src/login/webview/vue/login.vue
- packages/core/src/login/webview/vue/reauthenticate.vue
- packages/core/src/shared/telemetry/telemetryService.ts
- packages/core/src/shared/telemetry/util.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/test/credentials/utils.test.ts
- packages/core/src/test/shared/telemetry/util.test.ts
We noticed that there was an auth dropoff between `session_start` with a brand new clientId, versus when the `auth_userState` metric indicated `isFirstUse` meaning the user is net new. We went from 12.7k for `session_start` to 9.8k for `auth_userState`, these should have been basically the same.
Add in certain metrics to help debug where the discrepancy is coming from:
- When we determine the user is a first time user, we will also check if the clientId is newly generated. If this is not the case we know there is a discrepancy here
- The relevant metric will be `function_call` with a `functionName: isFirstUse`, `result: Failed`, and a `reason: ClientIdAlreadyExisted`
- When we determine the user is a first time user, if we detected that they had previous auth connections, this will …
> telemetry(auth): Update metrics to better debug Auth dropoff

- packages/amazonq/.changes/next-release/Bug Fix-ee447a9f-6a92-47c5-8e94-069c1aee46ab.json
- packages/core/src/codewhisperer/util/zipUtil.ts
- packages/core/src/shared/utilities/workspaceUtils.ts
- This will fix `Target file doesn't exist or is a directory.` issue in unit test generation.
- If user opens project in workspace mode and try `/test` then in shared workspaceUtils: https://github.com/aws/aws-toolkit-vscode/blob/35502be238b1bf7c3ff73e44df8d077a6d32aa85/packages/core/src/shared/utilities/workspaceUtils.ts#L220-L236 returns the files starting from src but UTG does need values from child level.
Given above function with workspaceFolders as 
```
[
{
uri: {
scheme: "file",
authority: "",
path: "/Users/Q/Downloads/TestingUTG/Sample/src",
query: "",
fragment: "",
_formatted: "file:///Users/Q/Downloads/TestingUTG/Sample/src",
_fsPath: "/Users/Q/Downloads/TestingUTG/Sample/src",
},
name: "src",
index: 0,
},
{
uri: {
scheme: "file",
authority: "",
path: …
```
> fix(amazonq): Updating logic for getWorkspaceRelativePath in shared src for /test

- packages/core/src/codewhisperer/service/transformByQ/transformApiHandler.ts
When a plan table is empty, the table header shows.
Don't show the table header when the table is empty.
---
> fix(amazonq): skip empty plan tables

- package-lock.json
- packages/core/package.json
- packages/webpack.base.config.js
- we have a couple moderate vulnerabilities due to an old version of esbuild-loader
- update esbuild-loader + other npm packages that have vulnerabilities
- In the [3.0.0 esbuild-loader version](https://github.com/privatenumber/esbuild-loader/releases/tag/v3.0.0) ESBuildMinifyPlugin was re-named to EsbuildPlugin, it still does the minification by default though
---
> deps(build): update esbuild-loader to 4.3.0

- packages/amazonq/.changes/next-release/Bug Fix-e587b325-81f7-4ad0-8945-7c162dceffcd.json
- packages/core/src/amazonqTest/chat/views/connector/connector.ts
- Capability card text should be updated
- Update capability card with correct text
---
> fix(amazonq): update capability card text for /test

- packages/core/src/awsService/ec2/sshKeyPair.ts
- packages/core/src/shared/utilities/pathFind.ts
- packages/core/src/shared/utilities/textUtilities.ts
- packages/core/src/test/shared/utilities/pathFind.test.ts
This is aimed at fixing the following ec2 bug.
Attempting to generate the ssh keys via tryRun can log a failure, when there is no failure. Looking at https://github.com/aws/aws-toolkit-vscode/blob/35502be238b1bf7c3ff73e44df8d077a6d32aa85/packages/core/src/awsService/ec2/sshKeyPair.ts#L78-L86 
We use `tryRun` to detect if the output contains "unknown key type". This allows us to detect when a certain key type such as RSA or ed25519 is not supported on the local machine. Detecting if the key generated successfully is a harder problem, as the output did not contain a consistent message. 
However, it results in `tryRun` logging a failure to find "unknown key type" in the output, which means failed to find the expected text in the output, but still generated the key. This is then logged as a …
> refactor(util): allow tryRun to take a regex. 

- packages/amazonq/test/e2e/inline/inline.test.ts
- we have no way to get any information on why an inline test was flaky. It might be because telemetry events are being out of order?
- Since fib doesn't have spaces in the contents it's autocompleting on the very first line which may be causing the backend to return no results
- add more debugging information to understand why there was a failure
- add spaces to the test fib function
- consider a suggestion shown if the recommendation handler says its visible or if its state has been declared as 'Shown'
--- …
> test(amazon): add more debugging information to inline tests

- packages/core/src/awsService/ec2/model.ts
- packages/core/src/test/awsService/ec2/model.test.ts
As part of the EC2 Connect process, we check if the SSM agent is pingable on the target instance. This is done here: https://github.com/aws/aws-toolkit-vscode/blob/b9af56c3097242fb796995479f864d95098bf713/packages/core/src/awsService/ec2/model.ts#L153-L162
This check can fail, and is currently does fail a decent amount of the time in telemetry.
- wrap the check in a `waitUntil`, retrying every half second up to 10 times. 
---
> fix(ec2): increase robustness of checking ssm agent ping status. 

- packages/core/src/awsService/ec2/model.ts
- packages/core/src/shared/extensions/ssh.ts
- packages/core/src/test/shared/extensions/ssh.test.ts
Within telemetry, there are a large group of fatal errors within EC2 Connect being grouped together under the same general error code. Additionally, there is very little information in the error message to determine the source of this error. Specifically, it appears the the test SSM connection done before attempting to pass the connection to VS Code, implemented [here](https://github.com/aws/aws-toolkit-vscode/blob/b9af56c3097242fb796995479f864d95098bf713/packages/core/src/shared/extensions/ssh.ts#L133-L155), can fail, and gives us a general error code with little information about its root cause.
- Add a specific error code for this connection type. (reused an old unused one)
- Pipe the error from the child process into the error message so that we get it in telemetry. 
- Add a docstring …
> refactor(ec2): improve error information in telemetry. 

- packages/core/src/codewhispererChat/controllers/chat/controller.ts
Remove as experiment has been disable from the service side, no need to collect workspace context if service doesn't actually utilize it.
---
> config(amazonq-chat): disable and remove implicit workspace context experiment

- package-lock.json
- packages/core/package.json
- packages/webpack.base.config.js
This reverts commit 8d2d335caa2fd2f501324e50aef7d5490051d6b5.
Upgrading esbuild-loader broke loading mynah-ui
Revert for now
---
> Revert "deps(build): update esbuild-loader to 4.3.0 (#6622)"

- packages/amazonq/.changes/next-release/Bug Fix-8e53fbd9-35d8-40f0-95be-5c7ac2478353.json
- packages/amazonq/test/e2e/amazonq/transformByQ.test.ts
- packages/core/src/amazonqGumby/chat/controller/messenger/messenger.ts
- packages/core/src/codewhisperer/service/transformByQ/transformMavenHandler.ts
When users choose to skip tests, we were skipping them on our server by passing in their choice to our backend, but we weren't also skipping them locally.
Tell Maven to use `-DskipTests`
---
> fix(amazonq): skip tests locally

- packages/core/src/shared/clients/clientWrapper.ts
- packages/core/src/shared/clients/ssm.ts
The AWS SDK now supports built-in pagination: [https://aws.amazon.com/blogs/developer/pagination-using-async-iterators-in-modular-aws-sdk-for-javascript/ ](https://aws.amazon.com/blogs/developer/pagination-using-async-iterators-in-modular-aws-sdk-for-javascript/)
Currently, have our own logic build on top of calls to do this logic for us. However, the SDK paginators are likely more reliable, and avoids reimplementing logic. They are also part of the SDK making them easier to integrate with (specifically for types).
Doing this early in the migration process has the potential to reduce a lot of unnecessary code.
- Migrate existing use cases of sdkv3 to use these paginators.
- Create general support for them in the Wrapper class.
---
- Treat all work as PUBLIC. Private `feature/x` branches …
> refactor(sdkv3): switch to using built-in sdkv3 pagination. 

- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/controllers/chat/model.ts
- packages/core/src/codewhispererChat/view/connector/connector.ts
The mergedRelevantTextDocument should have a better name. It is actually the documents that are referenced.
---
> refactor(cw): Rename the mergedTextDocument field. 

- packages/core/src/shared/awsClientBuilderV3.ts
- packages/core/src/test/techdebt.test.ts
- packages/core/src/testE2E/shared/awsClientBuilderV3.test.ts
Inspecting the logs, and http requests themselves, it appears that the sdkv3 clients are somehow adding a `connection: close` header to the http requests. This is not done by the SDK (according to SDK team), and inspecting the headers throughout the SDK packages at the recommended points suggests this is being overwritten somewhere else. 
Creating a new vscode extension with this code snippet also fails, but a new project without vscode succeeds. This suggests its VS Code. 
I believe this is caused by https://github.com/microsoft/vscode/issues/173861, which was resolved, but is now reopened. The comments and techdebt tests suggested this is no longer an issue, but it now is again due to fix being reverted. 
- Remove outdated notes/test that suggest this is fixed in newer versions of VS …
> feat(sdkv3): enable persistent connections by forcing keep alive header. 

- packages/core/src/stepFunctions/workflowStudio/handleMessage.ts
- packages/core/src/stepFunctions/workflowStudio/types.ts
- packages/core/src/stepFunctions/workflowStudio/workflowStudioEditorProvider.ts
- packages/toolkit/package.json
1. In case we introduce new feature dependant on the Toolkit change in the future, users may face issues if they don't update their toolkit right away (as their toolkit version won't have the new functionality in place)
2. There was a regression from my [previous PR](https://github.com/aws/aws-toolkit-vscode/pull/6024/commits/9c40f4c982c7d6a02c064b6dea62120f3760aa71), in `package.json` - most possibly due to incorrect merge conflict resolution (since the original file has been moved to another folder). The regression is that undo command override is not working, causing uncorrect undo command behaviour when triggered from webview
3. There is some redundant code which is not useful and causes incorrect behaviour, showing in the webview view screen
1. To ensure compatibility, we are adding …
> fix(stepfunctions): Bug fixes - handling unsupported messages, fix undo sync bug, code cleanup

- package-lock.json
- packages/core/package.json
- packages/toolkit/.changes/next-release/Feature-43784260-ff60-4419-8fe3-a886a2b37fc6.json
Upgrade `amazon-states-language-service` to 1.16.1.
The new version expands data source and output options for Distributed Map in ASL. 
Feature release post: https://aws.amazon.com/about-aws/whats-new/2025/02/aws-step-functions-data-source-output-option-distributed-map/
---
> feat(toolkit): Expand data source and output options for Distributed Map in ASL language schema

- packages/amazonq/.changes/next-release/Bug Fix-21c570d4-388e-460f-88e1-7034ed7e17d4.json
- packages/core/src/amazonqTest/chat/controller/controller.ts
- When users attempt to generate unit test cases using the /test command for packages other than the primary one in the workspace, they encounter a diff view suggesting the absence of an existing file. However, this is incorrect as there is already an existing test file in the package.
- Fixed this issue by getting the project path from the target file.
---
> fix(amazonq): Test generation shows incorrect view diff view

- packages/core/src/codewhispererChat/controllers/chat/controller.ts
This is a band-aid to temporarily set the size of `relevantTextDocuments` and `additionalContentEntry[]` combined to be lower than 40k characters, due to limitations on the service side. This PR will fix the issue when the API returns validation exception.
1. Truncation is performed at chunk level. 
2. Prioritize `additionalContentEntry[]` over `relevantTextDocuments`
3. Added TODO for a total character count indicator.
---
> fix(amazonq): Set context limit to 40k characters

- packages/core/src/codewhisperer/util/customizationUtil.ts
- packages/core/src/shared/featureConfig.ts
- packages/core/src/shared/globalState.ts
1. change poll interval from 30mins to 180 mins
2. Only call listAvailableCustomizations for new customization override for update
3. Use a new field customizationArnOverrideV2 for a clean override plan
---
> fix(amazonq): adjust feature config customization arn override logic

- packages/amazonq/.vscode/launch.json
In https://github.com/aws/aws-toolkit-vscode/pull/6581 I had updated the name of the environment variables that get used but forgot to update the launch config, meaning you can't set breakpoints
Update the launch config to the new path
---
> fix(amazonq): use __AMAZONQLSP_PATH in launch config

- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/util/zipUtil.ts
- packages/core/src/shared/utilities/workspaceUtils.ts
/test has been seeing quite a lot of failures due to file paylaod limit exceeded errors in past weeks in both IDEs but in last week there has been huge rise in these errors for /test on VSCode.
We have noticed a change that ignores to use default patterns in file filtering was introduced in PR #6561 . We have also collected data from internal customers by adding payload manifest in JetBrains for these errors and compiled a list of extensions which are causing this issue. We have decided to add these patterns to ignore list on VSCode as well.
- For Test Generation useCase, we have added back default pattern ignore list
- we have created testGenIgnorePattern list and added these patterns to Filtering methods for Test Generation UseCase.
- Fixed the workspace folders sorting for Test …
> fix(amazonq): /test file collection usecase adds more patterns to filtering.

- docs/lsp-debugging.md
- Multiple people have gotten confused on how to get the language server activated for inline
- Add that to the language server debugging documentation
---
> docs(amazonq): Add instructions on how to start Amazon Q inline debugging

- packages/amazonq/.changes/next-release/Bug Fix-b183d3cf-e277-4465-a28d-53a0bdf7f424.json
- packages/amazonq/test/unit/codewhisperer/service/securityScanHandler.test.ts
- packages/core/src/codewhisperer/service/securityScanHandler.ts
- packages/core/src/test/codewhisperer/securityScanHandler.test.ts
When running a new `/review` scan, Q fails to respect previously added ignore line, causing ignored issues to reappear in subsequent reviews.
Fixed incorrect filter logic on ignoring single line issue
Old unit tests for `listScanResults` will not work after this change. So in addition, I improved all of `securityScanHandler`'s unit tests to not use any file stubs to better simulate real environment. 
---
> fix(amazonq):  ignored lines should not show up in /review scan issues

- packages/core/src/amazonq/lsp/lspController.ts
In certain rare cases, when the changed file has no dot in filename, this file was misread as folders in the older LSP. Now this bug is fixed in 0.1.42 lsp.
update lsp artifact to 0.1.42
---
> fix(amazonq): update lsp artifact to 0.1.42

- package-lock.json
- packages/core/package.json
- packages/core/src/amazonq/webview/ui/main.ts
File list in header flickers as message is rendering (see screen recording)
https://github.com/user-attachments/assets/485c665f-cde1-4ed6-a316-8cea2ac63a49
Update to latest mynah beta. Pass `undefined` to `header` in subsequent messages (as instructed by Mynah UI team)
Note: no fix in changelog needed since feature hasnt yet been released
---
> fix(amazonq): file list flicker

- packages/core/src/shared/fs/fs.ts
- packages/core/src/shared/lsp/lspResolver.ts
- packages/core/src/shared/vscode/env.ts
- Language servers are only being downloaded on macs
- Download on windows/linux as well
---
> feat(amazonq): Add lsp downloading support for windows/linux

- package-lock.json
- packages/core/package.json
- packages/core/src/shared/awsClientBuilderV3.ts
- packages/core/src/test/shared/awsClientBuilderV3.test.ts
From https://github.com/aws/aws-toolkit-vscode/pull/6664, we have persistent connections.
However, each SDK client creates its own http handler. If we have N distinct service clients we maintain, then we could have up to N http handlers, with N distinct connection pools. This does not affect persistent connections since each service maintains its own endpoints, however, there is a small overhead in initiating each connection pool. Additionally, there is no guarantee for consistent behavior across handlers with regards to configuration options (Ex. requestTimeout). 
- inject the same HTTP handler into each SDK client, unless explicitly given a different one. 
- use fetch-http-handler on web and `node-http-handler` on node. 
- We don't want to use `fetch-http-handler` in node because it …
> refactor(http): inject same http handler into each sdk client.

- packages/amazonq/.changes/next-release/Feature-90704e88-3ab3-4030-8bc6-fdde95aa3923.json
- packages/amazonq/test/unit/codewhisperer/service/securityScanHandler.test.ts
- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- packages/core/src/codewhisperer/index.ts
- packages/core/src/codewhisperer/service/securityScanHandler.ts
- packages/core/src/testE2E/codewhisperer/securityScan.test.ts
All code scans are run with a scanName as a UUID which makes it impossible to track the bug lifecycle of projects. We are not leveraging the bug tracking feature which allows grouping together different scan runs of the same project by passing in the same scanName between runs.
Calculate the scanName using ClientID, the current workspace configuration (project root(s) or active file), and code analysis scope.
---
> feat(amazonq): generate scanName from workspace config

- package-lock.json
- packages/amazonq/.changes/next-release/Feature-cf1e3d13-1b3d-4b23-bf6b-d6d46c75565c.json
- packages/core/package.json
Upgrade mynah-ui library to latest version
https://github.com/aws/mynah-ui/releases/tag/v4.23.0
---
> feat(amazonq): upgrade mynah-ui to 4.23.0

- packages/core/src/shared/errors.ts
- packages/core/src/shared/lsp/lspResolver.ts
- packages/core/src/shared/resourcefetcher/httpResourceFetcher.ts
- packages/core/src/shared/utilities/timeoutUtils.ts
- packages/core/src/test/shared/utilities/timeoutUtils.test.ts
the cancellation button on notification doesn't actually stop the LSP download
Route the notification timeout into `httpResourceFetcher` call, so that the user cancellation event stops the download as well.
Demo: non-cancelled and cancelled downloads:
https://github.com/user-attachments/assets/4f3d4ed0-635a-4f88-aef7-ee62e87bfc83
---
> feat(amazonq): user cancellable lsp download

- packages/core/src/amazonq/lsp/lspController.ts
- packages/core/src/codewhispererChat/clients/chat/v0/chat.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
In multiroot workspace setup, the contextList UI displays files that are deduped for the same files and doesn't resolve relative paths correctly.
1. In a multi-root workspace, the index is built on the root of the 1st project after sorting workspaceFolders, thus the chunk response also contains relativePath to the 1st project root after sorting. In order to get the same relativePath from explicit @file, we also need to use the root of the 1st project after sorting workspaceFolders.
2. Use a relativePath to projectRoot map to store the project root for each relativePath so that on clicking the file(which only returns relativePath in the event) we correctly construct the absolute path of the file to open in the editor.
---
- Treat all work as PUBLIC. Private `feature/x` branches will not be …
> fix(amazonq): context fixes for multiroot workspace setup

- package-lock.json
- package.json
- packages/amazonq/.changes/next-release/Feature-f0e30c17-67f5-4538-a109-e7acf203a76c.json
- packages/core/src/amazonq/webview/ui/texts/constants.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/controllers/chat/model.ts
- packages/core/src/codewhispererChat/controllers/chat/telemetryHelper.ts
- Send metrics on additional context to the `amazonq_interactWithMessage` event. This enables measuring success metrics as they relate to the new context features. 
- Improve error handling when collecting context items & metrics.
- Add new features to /help message
- Improve efficiency by switching from vscode.workspace.findFiles to fs.readDirectory
---
> telemetry(amazonq): add metrics to `amazonq_interactWithMessage`

- packages/amazonq/.changes/next-release/Bug Fix-c2494a35-1254-4920-abec-2fb44a15ac1d.json
- packages/amazonq/src/app/amazonqScan/app.ts
- packages/amazonq/src/app/amazonqScan/chat/controller/controller.ts
- packages/amazonq/src/app/amazonqScan/chat/views/actions/uiMessageListener.ts
- packages/core/src/amazonq/webview/ui/apps/amazonqCommonsConnector.ts
- packages/core/src/amazonqScan/controller.ts
Subsequent reviews (`/review`) were not possible after running a review. 
- subsequent reviews are now allowed
- Fix were made to not impact the previous bug fix where review causes two "run code review" chat messages
- Fix were made not to impact previous bug fix to auto-trigger `/review` from Quick Actions Menu
- Reverts https://github.com/aws/aws-toolkit-vscode/pull/6550
---
> fix(amazonq): allow subsequent reviews in review tab

- packages/amazonq/.changes/next-release/Test-de93b6df-6192-4718-8b64-080cfc770827.json
- packages/amazonq/test/e2e/amazonq/review.test.ts
- packages/core/src/testFixtures/workspaceFolder/QCAFolder/InsecureCode.java
- packages/core/src/testFixtures/workspaceFolder/QCAFolder/ProblematicCode.java
/review command functionality lacks end-to-end test coverage.
Add basic E2E tests for file review, project review, and ignore lines features.
---
> test(amazonq): Add E2E tests for Q Chat's /review command

- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/telemetryHelper.ts
In Windows, the rules under .amazonq/rules were not send in the chat prompt because of path resolution failure.
Use path.join instead of vscode.Uri.joinPath
---
> fix(amazonq): path resolution incorrectness in windows for .amazonq/rules

- package-lock.json
- packages/core/src/codewhisperer/service/securityScanHandler.ts
- packages/core/src/shared/telemetry/spans.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
Some users are reporting S3 upload failures but we don't have the requestIds to investigate further.
Emit `amazonq_createUpload` metric with requestIds
---
> telemetry(amazonq): createUpload metric for scans

- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/test/codewhisperer/startSecurityScan.test.ts
Events about findings are always tied to hover, apply fix, etc. Not able to understand the number of findings which never get acted on.
Emit metrics about findings at the time of scan results.
---
> telemetry(amazonq): emit metrics per finding

- packages/core/package.nls.json
- packages/core/resources/walkthrough/appBuilder/AppPicker.md
- packages/core/src/awsService/appBuilder/activation.ts
- packages/core/src/awsService/appBuilder/serverlessLand/main.ts
- packages/core/src/awsService/appBuilder/serverlessLand/metadata.json
- packages/core/src/awsService/appBuilder/serverlessLand/metadataManager.ts
- packages/core/src/awsService/appBuilder/serverlessLand/wizard.ts
- packages/core/src/shared/ui/pickerPrompter.ts
- packages/core/src/test/awsService/appBuilder/serverlessLand/main.test.ts
- packages/core/src/test/awsService/appBuilder/serverlessLand/metadataManager.test.ts
- packages/core/src/test/awsService/appBuilder/serverlessLand/wizard.test.ts
- packages/core/src/testInteg/appBuilder/serverlessLand/main.test.ts
- packages/core/src/testInteg/appBuilder/sidebar/appBuilderNode.test.ts
- packages/toolkit/.changes/next-release/Feature-769497f4-873f-4fa4-892d-833ff2a45a8d.json
- packages/toolkit/package.json
- packages/toolkit/scripts/build/copyFiles.ts
New feature from the Lambda team:
The AWS Toolkit for VS Code now integrates Serverless Land's application pattern library, allowing developers to browse, search, and implement pre-built serverless patterns directly in the IDE. This simplifies and accelerates the process of building serverless applications using VS Code.
---
> feat(lambda): Add Serverless Land feature

- packages/core/src/shared/sam/cli/samCliLocalInvoke.ts
- packages/core/src/shared/sam/localLambdaRunner.ts
- packages/core/src/test/shared/sam/cli/samCliLocalInvoke.test.ts
- packages/toolkit/.changes/next-release/Feature-c5435979-4c37-4dce-8ebb-dd14b77d3b87.json
Customers are not able to local invoke with the runtime selected in the webview UI. Currently the runtime used is the one specified on the template. The feature was already added to SAMCLI https://github.com/aws/aws-sam-cli/pull/7885.
Allows customers to change runtimes when locally invoking in the local invoke webview, without having to change it in their template and rebuilding. Under the hood, the newly added ```--runtime``` option will be appended to the ```samcli``` command.
---
- License: I confirm that my contribution is made under the …
> feat(lambda): Update SAM CLI to accept a runtime parameter in local invokes

- packages/amazonq/.changes/next-release/Feature-90704e88-3ab3-4030-8bc6-fdde95aa3923.json
- packages/amazonq/test/unit/codewhisperer/service/securityScanHandler.test.ts
- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- packages/core/src/codewhisperer/index.ts
- packages/core/src/codewhisperer/service/securityScanHandler.ts
- packages/core/src/testE2E/codewhisperer/securityScan.test.ts
This reverts commit 62d3ec19969c5eef6ee22f7ed155a0c32452ebcf.
Scan name change is causing unexpected behavior from the service.
Temporarily revert this change
---
> revert(amazonq): generate scanName from workspace config #6679

- packages/core/src/testInteg/appBuilder/serverlessLand/main.test.ts
There is a side effect from `sandbox.spy(AppBuilderRootNode.instance)` between two integration tests for AppBuilder causing test failure due to **_`TypeError: Attempted to wrap onDidChangeChildren which is already wrapped`_**`
```
1) "before each" hook for "creates an AppBuilderRootNode with correct label":
TypeError: Attempted to wrap onDidChangeChildren which is already wrapped
at checkWrappedMethod (/Volumes/workplace/Lambda Tooling/aws-toolkit-vscode/node_modules/sinon/lib/sinon/util/core/wrap-method.js:64:21)
at wrapMethod (/Volumes/workplace/Lambda Tooling/aws-toolkit-vscode/node_modules/sinon/lib/sinon/util/core/wrap-method.js:135:13)
at spy (/Volumes/workplace/Lambda Tooling/aws-toolkit-vscode/node_modules/sinon/lib/sinon/spy.js:180:16)
at /Volumes/workplace/Lambda …
```
> test(lambda): fix integration test failure in appBuilder

- package-lock.json
- package.json
- packages/core/src/amazonqTest/chat/controller/controller.ts
- packages/core/src/amazonqTest/chat/controller/messenger/messenger.ts
- packages/core/src/amazonqTest/chat/session/session.ts
- packages/core/src/codewhisperer/util/telemetryHelper.ts
- The current unit test generation telemetry event lacks a field to distinguish between user actions: acceptance, rejection, failure, or cancellation.
- Enhancing the amazonq_utgGenerateTests telemetry event by incorporating a status field to capture user actions in toolkit metrics.
- Bumping telemetry version to `1.0.307`
---
> telemetry(amazonq): Add status field to unit test generation telemetry for tracking user actions

- packages/amazonq/.changes/next-release/Bug Fix-b89574ec-9f50-4b4c-b548-30bfce5d0999.json
- packages/core/src/codewhisperer/util/zipUtil.ts
Reproduce steps:
1. Open a window with multiple workspace folders, for example `workspaceFolders: [folder1, folder2]`
2. Open any file and run a code review on the active file, for example `folder1/sample.py`
3. The zip entry will be created with the workspaceFolder duplicated, for example `folder1/folder1/sample.py`
Explicitly set `includeWorkspaceFolder` to false when getting the relative path of the file.
---
> fix(amazonq): incorrect zip entry path for file scans

- packages/amazonq/.changes/next-release/Bug Fix-917c4c75-6019-4d7d-a246-0248cf2be55d.json
- packages/core/src/amazonq/webview/ui/apps/cwChatConnector.ts
- packages/core/src/amazonq/webview/ui/connector.ts
- packages/core/src/amazonq/webview/ui/main.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
When a user selects "Create a new prompt", a mouse is required to 1) select the prompt name input field and 2) click the Enter button. This flow should be able to be completed with just the keyboard
Autofocus prompt input field, and allow submit on Enter key press.
---
> fix(amazonq): Keyboard navigation does not work on create prompt overlay

- packages/core/src/amazonq/webview/ui/apps/testChatConnector.ts
- packages/core/src/amazonqTest/chat/controller/controller.ts
- packages/core/src/amazonqTest/chat/controller/messenger/messenger.ts
- packages/core/src/amazonqTest/chat/controller/messenger/messengerUtils.ts
- packages/core/src/amazonqTest/chat/views/connector/connector.ts
- The unit test generation team lacks sufficient feedback to enhance the quality of their produced tests.
- Implementing the feedback system for internal users to evaluate and enhance unit test generation quality.
https://github.com/user-attachments/assets/25018157-8146-4182-a458-7ac68203e975
---
> feat(amazonq): Implementing the feedback system for internal users to improve unit test generation quality.

- packages/amazonq/.changes/next-release/Bug Fix-a7de0f94-cd21-4adc-8fcf-3082aa862528.json
- packages/amazonq/.changes/next-release/Feature-6192cfc5-c6cb-4302-bfcf-ec90cac95b72.json
- packages/core/src/codewhisperer/service/securityIssueHoverProvider.ts
- packages/core/src/codewhisperer/views/securityIssue/vue/root.vue
We currently see only code fix for fix preview. We want to see the diff containing both code fix and original code.
Remove logic to generate only the code fix. 
Remove logic for line number as it will be different for the diff.
/review: show code diff instead of only code fix for fix preview
---
> feat(amazonq): show code diff instead of only code fix for fix preview

- packages/core/src/amazonq/webview/ui/apps/testChatConnector.ts
- packages/core/src/amazonq/webview/ui/connector.ts
- packages/core/src/amazonqTest/chat/controller/controller.ts
- This PR is continuation of https://github.com/aws/aws-toolkit-vscode/pull/6748.
- Modifying UX to align with JetBrains IDE.
- Modified UX to align with JetBrains IDE.
- This change will effect only Internal  users.
https://github.com/user-attachments/assets/543de196-ddf3-494f-a117-b8d7296376e1
---
> fix(amazonq): ux modifications in utg feedback mechanism

- package-lock.json
- packages/core/package.json
- packages/core/src/awsService/apigateway/commands/copyUrl.ts
- packages/core/src/awsService/apigateway/explorer/apiGatewayNodes.ts
- packages/core/src/awsService/apigateway/vue/invokeRemoteRestApi.ts
- packages/core/src/shared/clients/apiGateway.ts
- packages/core/src/test/awsService/apigateway/explorer/apiGatewayNodes.test.ts
client still uses v2.
- Very straightforward migration, mostly exchanging types. 
- Create a simple APIGateway that redirects to a GET request to this repo's homepage. 
- Use the invoke method from the IDE.
- Copy ARN, name, and URL. 
---
> deps(apigateway): migrate client to use v3.

- packages/core/src/shared/telemetry/util.ts
1. `computeEnv` reports "wsl" for all remote envs.
2. `computeEnv` does not report "web" envs.
1. Only report "wsl" for WSL envs.
2. Report "remote" for other remote envs.
3. Report "web" for unknown web envs.
---
> telemetry: computeEnv reports "wsl" for all remote envs

- packages/core/src/awsService/appBuilder/serverlessLand/main.ts
Earlier we recorded the pattern name based on the asset name, which resulted in multiple records for the same template. This occurred because the asset name included the runtime name as well.
Modified the metric recording process to capture the pattern name, which remains consistent across runtimes. This approach ensures there is a single entry for each pattern, regardless of the runtime utilized. The runtime information is recorded separately.
---
> fix(lambda): making metric change for serverless land

- packages/amazonq/.changes/next-release/Bug Fix-4f680a31-ba5e-4baa-9984-666e0c1c2b72.json
- packages/amazonq/test/unit/codewhisperer/service/securityScanHandler.test.ts
- packages/core/src/codewhisperer/models/constants.ts
- we are getting quite a noteworthy amount of scan timeout errors on the front end. 
- increase front-end timeout
---
> fix(amazonq): increase scan timeout threshold

- packages/amazonq/test/unit/codewhisperer/commands/onAcceptance.test.ts
- packages/amazonq/test/unit/codewhisperer/commands/onInlineAcceptance.test.ts
- packages/amazonq/test/unit/codewhisperer/service/recommendationHandler.test.ts
- packages/amazonq/test/unit/codewhisperer/util/telemetryHelper.test.ts
- packages/core/src/codewhisperer/util/telemetryHelper.ts
- packages/core/src/shared/telemetry/exemptMetrics.ts
the `codewhisperer_userDecision ` metric isn't used by the codewhisperer/Q team. And it is very noisy (5x more emits than second most frequent metric, 20x more emits than the third).
Stop emitting this metric from vsCode
The user decision [events](https://github.com/aws/aws-toolkit-vscode/blob/ebb932698ff32c8d65504c702065a18cc2d325b0/packages/core/src/codewhisperer/util/telemetryHelper.ts#L261C19-L261C24) are still kept since they are used to calculate `userTriggerDecision`. De-noising it would be the next TODO
--- …
> telemetry(amazonq): deprecate `codewhisperer_userDecision` metric

- packages/core/src/dev/activation.ts
- packages/core/src/shared/lsp/manifestResolver.ts
- packages/core/src/shared/settings-amazonq.gen.ts
- packages/core/src/shared/settings.ts
If the language server manifest is deprecated we just show it in the logs. However, users may not be explicitly aware that they will need to upgrade the extension to get a different manifest.
Also according to the design specsheet, user should have the option to mute the message for good once seen.
- Added a message window with `don't show` and `ok` buttons for deprecated LSP manifest.
- Use AmazonQ suppressed prompts for `don't show` tracking
- Added a re-enable feature so that we can re-enable that setting if manifest gets updated. 
Also added language server name in logs, helpful to track different instances
--- …
> feat(amazonq): manifest deprecation message with optional don't show

- packages/amazonq/.changes/next-release/Bug Fix-f80cc751-cb9d-45b6-a03a-3aec945a4565.json
- packages/core/src/codewhisperer/util/zipUtil.ts
Diff path is incorrect when running a scan from windows. The code scan service expects diff paths in UNIX format.
Replace all `\` with `/`
---
> fix(amazonq): incorrect path for diff on windows

- packages/amazonq/test/e2e/amazonq/testGen.test.ts
- source code change for /test which adds a test plan summary after generating tests, but did not update e2e test to account for this
- update test
---
> test(amazonq): update view diff test

- packages/amazonq/src/lsp/client.ts
- When the bearer token updates in the background we never re-notify the language server
- update it every 5 minutes as a hack to unblock the pentest
---
> fix(amazonq): update the bearer token in the language server every 5 minutes

- packages/amazonq/.changes/next-release/Bug Fix-385a5132-b128-4acb-920a-53990ebdb7c4.json
- packages/amazonq/package.json
- packages/core/src/amazonq/webview/webView.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/commands/registerCommands.ts
- packages/toolkit/package.json
Fixes https://github.com/aws/aws-toolkit-vscode/issues/6787.
Only happens when toolkit is installed otherwise there is no ellipses menu.
Before
After
---
> fix(review): code issues ellipses menu displaying toolkit options

- packages/amazonq/.changes/next-release/Bug Fix-62081c53-09b4-46b0-80b0-6eb853ffabd6.json
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/telemetryHelper.ts
The system prompt for saved prompts and workspace rules is too vague, users reporting they are sometimes ignored entirely.
Add system prompt for saved prompt and workspace rules to improve quality of responses
---
> fix(amazonq): Improve responses for saved prompts and workspace rules

- package-lock.json
- packages/amazonq/scripts/build/copyFiles.ts
- packages/core/package.json
- packages/toolkit/scripts/build/copyFiles.ts
FQN not used since 6484c98c3ecd4a2b665e7ee8fa3d96e8ba9ce935. And it adds ~1 MB to the vsix size.
- Drop FQN dependency.
- Remove "temporary" hack added a long time ago for mynah: b2dc00ab7431
---
> build(deps): remove `@aws/fully-qualified-names` dependency

- packages/amazonq/.changes/next-release/Feature-7a3c930e-cc8e-4323-9ecd-c1bf767fd2ed.json
- Missing changelog
- Add it before releasing
---
> feat(amazonq): Add changelog item for enabling inline code suggestions via Amazon Q Language Server

- packages/amazonq/package.json
The Q product name should find amazon-q-vscode.
---
> docs: add "Q Developer" marketplace tag

- packages/core/src/codewhisperer/client/user-service-2.json
- packages/core/src/codewhispererChat/controllers/chat/chatRequest/converter.ts
- src.gen/@amzn/codewhisperer-streaming/README.md
- src.gen/@amzn/codewhisperer-streaming/src/commands/ExportResultArchiveCommand.ts
- src.gen/@amzn/codewhisperer-streaming/src/commands/GenerateAssistantResponseCommand.ts
- src.gen/@amzn/codewhisperer-streaming/src/commands/GenerateTaskAssistPlanCommand.ts
- src.gen/@amzn/codewhisperer-streaming/src/commands/SendMessageCommand.ts
- src.gen/@amzn/codewhisperer-streaming/src/models/models_0.ts
- src.gen/@amzn/codewhisperer-streaming/src/protocols/Aws_restJson1.ts
Q Agentic Chat needs new updated model with additional fields as part of its core functions. 
- Added IDE origin to the GenerateAssistantResponse API call
- Added model changes for APIs for Q Agentic Chat.
---
> feat(chat): Updated model for Q Agnetic Chat APIs.

- packages/core/src/shared/lsp/lspResolver.ts
When running multiple VSCode windows on mac arm64, Amazon Q's language server works correctly in the first window but crashes in additional windows with the error: `EXC_CRASH (SIGKILL (Code Signature Invalid))`
The crash occurs because:
- The first VSCode window starts the language server and extracts everything (including the node binary from flare)
- When additional VSCode windows are opened, they attempt to re-extract the zip from flare, overriding the current contents
- On mac arm64, overwriting the node binary while it's in use by the first VSCode window can apparently cause code signing validation to fail for the next callers of it
- This didn't effect windows when I was playing around with it yesterday
- Weirdly enough, if you start the language server outside of VSCode, unzip …
> fix(amazonq): Open multiple VSCode instances crashes Amazon Q Language Server

- packages/amazonq/.changes/next-release/Feature-25bf4b40-331e-4b28-8a89-0a19075b6b79.json
- packages/core/src/codewhisperer/client/user-service-2.json
- packages/core/src/codewhisperer/commands/startCodeFixGeneration.ts
- packages/core/src/codewhisperer/service/codeFixHandler.ts
When Q generates code fixes, it some times can get code from external links. For these fixes, it is required to return the reference along with the code fixes.
This change gives customer the choice to either accept or block the code fix with references.
---
> feat(amazonq): passing referenceTrackerConfiguration to StartCodeFixJob

- packages/amazonq/src/extension.ts
- packages/amazonq/src/extensionNode.ts
- packages/amazonq/src/lsp/chat/activation.ts
- packages/amazonq/src/lsp/chat/commands.ts
- packages/amazonq/src/lsp/chat/messages.ts
- packages/amazonq/src/lsp/chat/webviewProvider.ts
- packages/amazonq/src/lsp/client.ts
- packages/amazonq/src/lsp/lspInstaller.ts
- packages/core/src/shared/lsp/baseLspInstaller.ts
- packages/core/src/shared/lsp/types.ts
- packages/core/src/shared/settings-toolkit.gen.ts
- packages/toolkit/package.json
- We removed chat a while ago from the `feature/amazonqLSP` branch because we were just starting with inline suggestions
- Now that we're moving to use chat we can re-add it
- Implement explain, refactor, fix, optimize, sendToPrompt, openTab
- Add a feature flag for enabling/disabling chat
- **note**: amazonqLSP and amazonqChatLSP must be enabled in order for chat support to work 
- extended the baseinstaller so that individual lsps installers can provider their own resource paths
- this is the equivalent of https://github.com/aws/language-servers/blob/55253ea258b2d34bcc47b93e9998b1e9898e8f2a/client/vscode/src/chatActivation.ts but integrated with our codebase
- since commands require the webview we pass in the view provider to all commands so we can lazy evaluate the webview when …
> feat(amazonq): re-add basic chat through a language server

- packages/core/src/amazonq/webview/messages/messageDispatcher.ts
- packages/core/src/amazonq/webview/ui/main.ts
- packages/core/src/login/webview/commonAuthViewProvider.ts
- packages/core/src/login/webview/vue/amazonq/backend_amazonq.ts
- packages/core/src/login/webview/vue/backend.ts
- packages/core/src/login/webview/vue/login.vue
- packages/core/src/login/webview/vue/reauthenticate.vue
- packages/core/src/login/webview/vue/root.vue
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/webviews/main.ts
With our telemetry, we do not know when the frontend webview UI has actually loaded.
The current process looks like the following:
- We create a webview and set the HTML to load, but after that we do not have a formal way to detect if the webview actually loaded the HTML/JS successfully. We only know that the process started (`toolkit_willOpenModule`)
Emit certain metrics during the webview loading process to get a better idea of if the webview UI successfully completed its initial load.
- `toolkit_willOpenModule`, indicates intent to render a webview. It does not mean the user is seeing anything.
- `toolkit_didLoadModule`, indicates the final result of loading the webview
- We know a `result: Succeeded` when the frontend send a successful message to the backend. It knows this by ensuring …
> telemetry(webview): Emit toolkit_X module telemetry on auth webview

- packages/amazonq/src/app/inline/completion.ts
The inline completion document selectors between vscode's currently implementation and the new implementation aren't aligned
Rather than providing our own implementation that was originally stolen from [here](https://github.com/aws/language-servers/blob/main/client/vscode/src/inlineCompletionActivation.ts#L22) and expanding it, we should just use the exact document selectors that vscode already uses from [here](https://github.com/aws/aws-toolkit-vscode/blob/master/packages/core/src/codewhisperer/models/constants.ts#L104)
---
- License: I …
> fix(amazonq): align inline completion document selectors

- packages/amazonq/.changes/next-release/Feature-fa845e78-1e76-407a-be8a-e64c63b98795.json
- packages/amazonq/package.json
- packages/core/package.nls.json
There is no hard command to focus the chat view from command palette. There exists Amazon Q: Focus on Chat View, but if the user moves the chat it can change names, e.g. Terminal: Focus on Chat View, which is confusing.
CoPilot also has this issue, which is why they have the Chat: Open Chat command.
Note: This command will work whether the user is logged in or not, for ease of use. If they are not logged in then it will open the login window.
---
> feat(amazonq): add open chat command

- package-lock.json
- packages/amazonq/src/app/inline/completion.ts
- packages/amazonq/src/app/inline/recommendationService.ts
- packages/amazonq/src/app/inline/sessionManager.ts
- packages/amazonq/src/lsp/activation.ts
- packages/amazonq/src/lsp/client.ts
- packages/amazonq/test/unit/amazonq/apps/inline/completion.test.ts
- packages/amazonq/test/unit/amazonq/apps/inline/recommendationService.test.ts
- packages/core/package.json
Basic paginated inline suggestions implementation using language server (related: https://github.com/aws/language-servers/pull/831)
---
> feat(amazonq): basic paginated suggestions using language server

- packages/core/src/codewhispererChat/tools/fsRead.ts
- packages/core/src/codewhispererChat/tools/toolShared.ts
- packages/core/src/shared/logger/logger.ts
- packages/core/src/shared/utilities/workspaceUtils.ts
- packages/core/src/test/codewhispererChat/tools/fsRead.test.ts
Amazon Q Agentic Chat needs the ability to read files and directories from the user's workspace to provide context-aware assistance. Currently, there's no tool available for Amazon Q to access the file system in a controlled and secure manner.
- Implemented a new fsRead tool that allows Amazon Q to:
- Read entire files or specific line ranges
- List directory contents with configurable depth
- Handle error cases gracefully with informative messages
- Enforce size limits (30KB) to prevent excessive memory usage
```
FsRead Unit Tests
extensionHostProcess.js:178
✔ reads entire file
extensionHostProcess.js:178
✔ reads partial lines of a file
extensionHostProcess.js:178
✔ lists directory contents up to depth = 1
extensionHostProcess.js:178
✔ throws error if path does not exist …
```
> feat(chat): Add fsRead tool for Amazon Q Agentic Chat

- packages/core/src/codewhispererChat/tools/fsWrite.ts
- packages/core/src/shared/logger/logger.ts
- packages/core/src/test/codewhispererChat/tools/fsWrite.test.ts
Agentic chat experience needs a local write tool.
Add `fsWrite` tool with `create` command implementation.
---
> feat(chat): add fsWrite tool create command

- packages/amazonq/src/app/inline/completion.ts
- packages/amazonq/test/unit/amazonq/apps/inline/completion.test.ts
need to log reference for inline with language server
---
> feat(amazonq): handle reference for inline with language server

- packages/core/src/login/webview/commonAuthViewProvider.ts
- packages/core/src/login/webview/vue/backend.ts
We have an explicit force refresh of the auth webview when it is shown/hidden. There is not an obvious reason why we do this.
This causes problems since we expect that show/hiding of the webview does not trigger any functional changes since we have configured the webview to continue running even while hidden. This means that our handlers for auth changes are still running even when auth is hidden.
For my specific issue, by force reloading the webview on every show/hide it triggered the webview loading code each time, causing webview telemetry events to be triggered more than expected.
Remove the force reload line. With this change we can move the edge case handling code which throttled the telemetry emitted when it was triggered on every hide/show.
I've done manual testing and have not …
> refactor(auth): dont manual refresh auth webview on hide

- packages/core/src/codewhispererChat/tools/fsWrite.ts
- packages/core/src/test/codewhispererChat/tools/fsWrite.test.ts
Agentic chat requires support for different write commands
Add missing commands for `fsWrite` tool
---
> feat(chat): add fsWrite tool commands

- packages/core/src/awsService/appBuilder/serverlessLand/metadata.json
- packages/toolkit/.changes/next-release/Feature-279a0842-feff-4089-8529-61376bf8cf97.json
Adding new pattern for ServerlessLand feature. 
Added pattern for SNS integration with Lambda in python, nodejs, java and dotnet runtime, supporting SAM IaC.
---
> feat(lambda): adding SNS pattern for ServerlessLand

- packages/core/src/amazonq/webview/ui/apps/cwChatConnector.ts
- packages/core/src/amazonq/webview/ui/connector.ts
- packages/core/src/amazonq/webview/ui/main.ts
- packages/core/src/codewhispererChat/app.ts
- packages/core/src/codewhispererChat/clients/chat/v0/chat.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/controllers/chat/model.ts
- packages/core/src/codewhispererChat/view/connector/connector.ts
- packages/core/src/codewhispererChat/view/messages/messageListener.ts
- Agentic chat does not view the generated code diff and no option for accept or reject the code diff
- Splitting this bulk PR: https://github.com/aws/aws-toolkit-vscode/pull/6843
- Adding UX improvements and agent loop mechanism to Q chat.
https://github.com/user-attachments/assets/81ab88b3-ffb9-4db7-a38f-e0562848cb6f
---
- Metrics
- Refactoring code
- More UX improvements
- Pending part 2 of https://github.com/aws/aws-toolkit-vscode/pull/6843
---
> feat(amazonq): Adding openDiff and acceptDiff UX to the agentic chat.

- packages/core/src/codewhispererChat/tools/executeBash.ts
- packages/core/src/codewhispererChat/tools/fsRead.ts
- packages/core/src/shared/logger/logger.ts
- packages/core/src/test/codewhispererChat/tools/executeBash.test.ts
Amazon Q Agentic Chat needs the ability to execute bash commands
```
ExecuteBash Tool
extensionHostProcess.js:178
✔ pass validation for a safe command (read-only)
extensionHostProcess.js:178
✔ fail validation if the command is empty
extensionHostProcess.js:178
✔ set requiresAcceptance=true if the command has dangerous patterns
extensionHostProcess.js:178
✔ set requiresAcceptance=false if it is a read-only command
extensionHostProcess.js:178
✔ whichCommand cannot find the first arg
extensionHostProcess.js:178
✔ whichCommand sees first arg on PATH
extensionHostProcess.js:178
✔ stub invoke() call
extensionHostProcess.js:178
7 passing (45ms)
```
---
- Your code changes must meet the guidelines …
> feat(chat): Add executeBash tool for Amazon Q Agentic Chat

- packages/core/src/codewhispererChat/clients/chat/v0/chat.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/storages/chatHistory.ts
Earlier PR only add setup for Q Agentic chat loop. But Agentic loop does not work yet.
This PR fixes the Q Agentic chat loop and is set for fsRead Tool.
---
> feat(chat): fix for q agentic chat loop

- packages/core/src/amazonq/webview/ui/apps/cwChatConnector.ts
- packages/core/src/codewhispererChat/app.ts
- packages/core/src/codewhispererChat/clients/chat/v0/chat.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/controllers/chat/model.ts
- packages/core/src/codewhispererChat/view/messages/messageListener.ts
- Existing Q chat has `contextList` and `fileListTree` both component using same event to show the file and the diff view functionality respectively. IDE can not know what exact functionality to perform if user clicks on a filePath.
**ContextList:**
**FileListTree:**
- Adding a conditional check to open the diff view only if the IDE is doing a `fs_write` tool operation.
- Rest show open the file for contextList.
---
> fix(amazonq): FollowUp PR to reuse file-click function to show the diff view

- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/tools/fsWrite.ts
- packages/core/src/codewhispererChat/tools/tool_index.json
- packages/core/src/test/codewhispererChat/tools/fsWrite.test.ts
FsWrite should be enabled in agentic loop
- Updated tool index with fsWrite
- Updated the agentic loop to invoke fsWrite tool
- Added input validation
---
> feat(chat): add fsWrite tool to agentic loop

- packages/core/src/codewhispererChat/controllers/chat/chatRequest/converter.ts
- src.gen/@amzn/codewhisperer-streaming/src/commands/GenerateAssistantResponseCommand.ts
- src.gen/@amzn/codewhisperer-streaming/src/commands/GenerateTaskAssistPlanCommand.ts
- src.gen/@amzn/codewhisperer-streaming/src/commands/SendMessageCommand.ts
- src.gen/@amzn/codewhisperer-streaming/src/models/models_0.ts
- src.gen/@amzn/codewhisperer-streaming/src/protocols/Aws_restJson1.ts
IDE context should know about the workspace
Update codewhisperer-streaming client and pass in workspaceFolders
---
> feat(chat): pass workspace folders to IDE context

- packages/core/src/codewhisperer/util/zipUtil.ts
`codeDiff` folder was missing from zip output. 
- optional parameter was not passed when it wasn't really optional. 
- The source of this issue is addressed in https://github.com/aws/aws-toolkit-vscode/pull/6838 by avoiding these scopes entirely. 
The following test case now passes when there are uncommitted changes to the repo. 
```
// packages/core/src/test/codewhisperer/zipUtil.test.ts
it('should generate a codeDiff folder when there are uncommitted changes', async function () {
const zipMetadata = await zipUtil.generateZip(vscode.Uri.file(appCodePath), CodeAnalysisScope.PROJECT)
const zipFileData = await fs.readFileBytes(zipMetadata.zipFilePath)
const zip = await JSZip.loadAsync(zipFileData)
const files = Object.keys(zip.files)
assert.ok(files.find((f) => f === …
```
> fix(ziputil): ensure codeDiff is generated when there are uncommitted changes

- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/tools/executeBash.ts
- packages/core/src/codewhispererChat/tools/toolShared.ts
- packages/core/src/codewhispererChat/tools/tool_index.json
- packages/core/src/test/codewhispererChat/tools/fsRead.test.ts
Execute bash tool is added but is not hooked to the Q Agentic chat yet.
Adding execute bash tool setup in Q Agentic chat loop.
---
> feat(chat): Adding execute bash tool setup in Q Agentic chat loop

- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/tools/chatStream.ts
- packages/core/src/codewhispererChat/tools/executeBash.ts
- packages/core/src/shared/logger/logger.ts
We need to be able to stream the command tool execution logs to the chat in real-time
- Added a new ChatStream class that extends Node's Writable stream to capture and stream bash command output to the chat UI in real-time
- Implemented a sendPartialBashToolLog method in the Messenger class to display command output as it's generated
- Modified the chat controller to use the new streaming functionality instead of waiting for commands to complete
-  Added appropriate logging and error handling for the streaming functionality
-  Fixed a duplicate write operation in the handleChunk method of executeBash.ts
https://github.com/user-attachments/assets/a27900d1-5c0e-4690-a7d3-33f7712f255a
---
- …
> feat(chat): Stream executeBash output to chat

- packages/amazonq/test/e2e/amazonq/framework/jsdomInjector.ts
`ReferenceError: IntersectionObserver is not defined` in E2E tests due to JSDOM 
Add mock for IntersectionObserver
---
> test(amazonq): add mock for IntersectionObserver

- packages/amazonq/.changes/next-release/Feature-b5f9e589-3415-4e4e-b7b2-f292b5436ad0.json
- packages/amazonq/test/e2e/amazonq/transformByQ.test.ts
- packages/core/src/amazonqGumby/chat/controller/messenger/messenger.ts
Hide a feedback form since we haven't gotten the Legal-approved text yet.
---
> fix(amazonq): hide feedback form

- packages/amazonq/.vscode/tasks.json
- packages/core/.vscode/tasks.json
- packages/toolkit/.vscode/tasks.json
```
*  Executing task in folder amazonq: yarn run watch 
zsh:1: command not found: yarn
*  The terminal process "/opt/homebrew/bin/zsh '-l', '-c', 'yarn run watch'" failed to launch (exit code: 127). 
*  Terminal will be reused by tasks, press any key to close it. 
```
Seems to be a vscode issue. 
- https://github.com/microsoft/vscode/issues/181006
- https://github.com/microsoft/vscode/issues/159465
Given that we already have `npm.packageManager` set to `npm` in this repo, I'm not sure why it keeps trying to use `yarn`.
Run the watch task as a shell script
---
- Your code changes must meet the guidelines in [CONTRIBUTING.md](https://github.com/aws/aws-toolkit-vscode/blob/master/CONTRIBUTING. …
> build: ensure npm is used for watch task

- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/tools/chatStream.ts
- packages/core/src/codewhispererChat/tools/executeBash.ts
ChatStream should be able to send messages for more use cases than just bash output.
Reuse the chat stream class for all tool messages
---
> feat(chat): use ChatStream to show tool description

- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/tools/chatStream.ts
- packages/core/src/codewhispererChat/tools/fsRead.ts
- packages/core/src/codewhispererChat/tools/fsWrite.ts
Tool acceptance confirmation is not implemented.
Some tools are missing descriptions.
Add confirmation button to tool message if required
---
> feat(chat): add confirmation buttons and tool descriptions

- packages/core/src/codewhisperer/client/user-service-2.json
The API model is out of date.
Update API model.
This is done by copying aws-sdk-external-2022-11-11/c2j/codewhispererruntime-2022-11-11.normal.json
and then format it using prettier plugin in VS Code. By doing so, the format of the JSON matches the one in the repo.
---
> deps(amazonq): update api model json

- packages/core/src/shared/clients/codewhispererChatClient.ts
This client is used in many Q features and does not currently allow retries. This means a single SDK request failure will cause the operation to fail. 
It appears based on the code that this is not intentional, and was accidentally left unfinished. 
- allow up to 1 retry.
---
> fix(cw): allow retries in the cw streaming sdk client. 

- packages/core/src/codewhispererChat/tools/fsRead.ts
- packages/core/src/codewhispererChat/tools/listDirectory.ts
- packages/core/src/codewhispererChat/tools/toolUtils.ts
- packages/core/src/codewhispererChat/tools/tool_index.json
- packages/core/src/shared/logger/logger.ts
- packages/core/src/shared/utilities/workspaceUtils.ts
- packages/core/src/test/codewhispererChat/tools/fsRead.test.ts
- packages/core/src/test/codewhispererChat/tools/listDirectory.test.ts
- packages/core/src/test/codewhispererChat/tools/toolShared.test.ts
LLM does not always use fsRead to list directory
Create a dedicated ListDirectory tool, updated FsRead to not support listing directory
---
> feat(chat): Add ListDirectory tool

- packages/core/src/codewhispererChat/tools/fsRead.ts
FsRead doesn't show readRange so there can be duplicate messages when a file is read in chunks.
Stream the readRange info to the chat. 
Assumes the changes in https://github.com/aws/aws-toolkit-vscode/pull/6888 will be merged so that fsRead will not support reading directories anymore.
---
> fix(chat): fsRead doesn't show readRange

- packages/core/src/codewhispererChat/controllers/chat/controller.ts
Clicking on file links opens the file in other apps.
Use VSCode API to open if it's a file
---
> fix(chat): file links open in other apps

- packages/amazonq/package.json
- packages/amazonq/src/lsp/config.ts
- packages/amazonq/test/e2e/lsp/lspInstallerUtil.ts
- packages/amazonq/test/unit/amazonq/lsp/config.test.ts
- packages/core/src/amazonq/lsp/config.ts
- packages/core/src/shared/lsp/baseLspInstaller.ts
- packages/core/src/shared/lsp/manifestResolver.ts
- packages/core/src/shared/settings-amazonq.gen.ts
- packages/core/src/test/shared/lsp/manifestResolver.test.ts
- manifest suppression messages were missing from package.json and directly written to settings gen, causing them to be overridden on every `npm install`
- add manifest suppression to package.json
- make this field available in the config 
---
> fix(amazonq): add missing lsp manifest messages from amazonq/package.json

- docs/lsp.md
- packages/amazonq/src/extension.ts
- packages/amazonq/src/lsp/activation.ts
- packages/amazonq/src/lsp/client.ts
- packages/core/src/shared/settings-toolkit.gen.ts
- packages/toolkit/package.json
- We previously thought inline completion was going to be launched first so we didn't end up putting it behind a feature flag
- Add inline completion behind a feature flag
---
> refactor(amazonq): expose lsp inline completion as an experiment

- packages/amazonq/.changes/next-release/Bug Fix-ccbc5e50-0a90-4340-b6d5-e57537949898.json
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
`@Prompts` not being sent to context due to change in [last week's release](https://github.com/aws/aws-toolkit-vscode/pull/6831/files#r2021948984)
Add 'file' label to user prompts 
---
> fix(amazonq): @-prompts not added to context

- packages/core/src/codewhispererChat/clients/chat/v0/chat.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
Additional context is not passed into to subsequent requests of the agentic loop
Store the context on each starting message, then pass it into the request payload for each tool message
---
> fix(chat): preserve context in agentic loop

- packages/amazonq/src/lsp/chat/messages.ts
- packages/amazonq/test/unit/amazonq/lsp/chat/messages.test.ts
- packages/core/src/amazonq/index.ts
There was no implementation for the `authFollowUpClicked` message received from LSP for Amazon Q. Because of that, the `authenticate` button that appears in case of expired SSO connection had no effect.
I added the implementation as follows:
* If the received `authFollowUpType` is `'re-auth'` or `'missing_scopes'`, initiate a re-authentication
* If the received `authFollowUpType` is `'full-auth'` or `'use-supported-auth'`, delete the connection so a new full authentication flow kicks off
I added a unit test file for this message type, which is extendable for every command handled in `registerLanguageServerEventListener`
--- …
> feat(amazonq lsp): add authFollowUpClicked implementation

- packages/amazonq/test/e2e/amazonq/transformByQ.test.ts
- packages/core/src/amazonqGumby/chat/controller/controller.ts
- packages/core/src/amazonqGumby/chat/controller/messenger/messenger.ts
- packages/core/src/amazonqGumby/chat/controller/messenger/messengerUtils.ts
We don't yet have legal approval to show users a feedback form. It is currently disabled / commented out, but better to remove the unused code until we get approval, since it may take a while and may not even happen.
Remove unused code and fix test.
---
> fix(amazonq): fix /transform test and remove feedback form

- package-lock.json
- packages/core/package.json
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/tools/chatStream.ts
- packages/core/src/codewhispererChat/tools/executeBash.ts
- packages/core/src/codewhispererChat/tools/toolUtils.ts
- packages/core/src/test/codewhispererChat/tools/executeBash.test.ts
- packages/core/src/test/codewhispererChat/tools/toolShared.test.ts
AppSec has required that we give the user an indication if they are about to run a potentially dangerous command
- Parse bash command to determine whether or not commands are dangerous or not.
- Display message warning to user
---
> feat(chat): Add warning UI for high risk bash command

- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/storages/chatHistory.ts
- packages/core/src/codewhispererChat/storages/chatHistoryStorage.ts
- History storage not set up for each tabs.
- If user ignores tool use and moves on, then request fails.
- Fixed chat history for multiple tab support
- User cancellation message is added to request in this case.
---
> fix(chat): fix for chat history for multuple tabs and user tool ignore

- packages/core/src/codewhispererChat/tools/executeBash.ts
- packages/core/src/test/codewhispererChat/tools/executeBash.test.ts
Regular read-only commands are being categorized as high risk.
- Split commands by additional operators
- Do not automatically default to return false on readOnly command
- Tested manually via plugin build
- Updated unit tests
---
> feat(chat): Split commands by additonal operators

- packages/core/src/codewhispererChat/tools/executeBash.ts
When the excutable command fails, the output is not formatted.
Format the stderr the same as stdout.
---
> (fix)chat: fix the bash output is not formatted

- package-lock.json
- packages/core/package.json
[sessionManager](https://github.com/aws/aws-toolkit-vscode/blob/master/packages/amazonq/src/app/inline/sessionManager.ts#L6) has an implicit dependency on `@aws/language-server-runtimes-types` that isn't present in the package.json
Add an explicit dependency, that way when the underling package currently controlling runtime-types's version changes it doesn't cause a build error as current observed in https://github.com/aws/aws-toolkit-vscode/pull/6825
--- …
> fix(deps): Add explicit @aws/language-server-runtimes-types dependency

- packages/amazonq/.changes/next-release/Feature-86f056f5-4ac4-47be-8167-09c19a529a1e.json
- packages/core/src/amazonq/session/sessionState.ts
- packages/core/src/test/amazonq/session/sessionState.test.ts
Users currently cannot access logs generated by the Agent when it executes user commands during code generation.
The output generated by the Agent during user command execution will be captured and written to the user's `logs`. This ensures that:
- Command execution logs are persisted locally
- Users can access the logs directly from their repository for troubleshooting.
---
> feat(amazonq): get logs generated by the Agent

- packages/core/src/shared/db/chatDb/util.ts
Export and delete icons are swapped
Before
After
---
> fix(amazonq): export and delete icons are swapped in chat history

- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/tools/listDirectory.ts
- UserIntent is populated when certain keyword is detected, which causes the request to not hit agentic code path
- list directory description is verbose
- Remove the userIntent from the agentic chat window input 
- Minor fix: adjust the list directory description
---
> fix(chat): Remove userIntent from agentic chat window input

- packages/core/src/test/shared/sam/build.test.ts
fix https://github.com/aws/aws-toolkit-vscode/issues/6913
Move the spy instantiation closer to reduce side effects. Add delay before start running command so additional for clean up to reduce chance of flakiness. Change assertion from true/false to count comparison to give more info for debugging in case the flakiness persists into the future. 
---
> fix(lambda): flaky test due to terminal instance

- packages/amazonq/test/e2e/amazonq/review.test.ts
/review test is flaky, but I was not able to reproduce.
skip this test for this week to unblock
---
> test(amazonq): skip exact finding test

- packages/core/src/test/awsService/appBuilder/walkthrough.test.ts
- packages/core/src/test/shared/sam/build.test.ts
fix https://github.com/aws/aws-toolkit-vscode/issues/6921
Refactor the tests for cleaner creating and deletion template.yaml file. 
- Scope and group tests cases based on required starting template. 
- Update assertion and error message. 
---
> fix(lambda): flakiness due to existing template.yaml

- packages/core/src/codewhispererChat/tools/listDirectory.ts
- packages/core/src/codewhispererChat/tools/tool_index.json
- packages/core/src/shared/utilities/workspaceUtils.ts
- packages/core/src/test/codewhispererChat/tools/listDirectory.test.ts
- ListDirectory tool will get called too many times if the directory has many subdirectories
- Add maxDepth parameter to ListDirectory tool to allow recursively listing directories
- Minor fix on the tool_spec
---
> fix(chat): Add maxDepth parameter to ListDirectory tool

- packages/core/src/amazonq/webview/ui/apps/cwChatConnector.ts
- packages/core/src/amazonq/webview/ui/main.ts
- packages/core/src/codewhispererChat/clients/chat/v0/chat.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/tools/chatStream.ts
- packages/core/src/codewhispererChat/view/connector/connector.ts
LLM will sometimes try to execute the `fsRead` tool (and `listDirectory` tool) many times in succession, when this happens we don't want to show every read message.
Update the existing chat message that already shows a read message if it exists.
- Added a new type of UiMessage `ToolMessage` specifically for handling tool chat messages
- `ToolMessage` will call MynahUI's `updateChatAnswerWithMessageId` API
- For every "group" of consecutive read messages we store the first occurrence of the read tool's toolUseId in session storage and use that as the messageId to update
- Updated `ChatStream` class to take in this messageId to update for the current message
https://github.com/user-attachments/assets/8df75d4d-c15f-4e21-9867-4ad3ca8f3233
---
- Treat all work as PUBLIC. Private `feature/x` …
> feat(chat): group consecutive read tool messages

- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/tools/toolShared.ts
Chat request fails if tool output exceeds the character length limit of 800,000.
Handle this and send a error result instead of a success result back to the LLM.
---
> fix(chat): request fails if character limit exceeded

- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/storages/chatHistory.ts
- packages/core/src/codewhispererChat/storages/chatSession.ts
Responses need to stop for new user prompt and fix user history
- featureflag to check the response state to stop the responses.
- Fixing history incase of exception or stopped responses.
---
> feat(chat): Adding state Management to stop the response for new user input prompt

- packages/core/src/codewhispererChat/controllers/chat/controller.ts
Chat history is not storing user input context 
fix for userInputMessage to include all context
---
> fix(chat): fix for userInputMessage to include all context

- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/tools/chatStream.ts
- packages/core/src/codewhispererChat/tools/fsWrite.ts
- packages/core/src/shared/utilities/diffUtils.ts
- packages/core/src/shared/utilities/textDocumentUtilities.ts
Use https://www.npmjs.com/package/diff for diffs
- Update diffs for FsWrite
- Remove hardcoded changed lines
- Remove hardcoded diff language
- Use file name instead of file path in card header
---
> fix(chat): use diff lib to get diffs

- packages/core/src/codewhispererChat/controllers/chat/chatRequest/converter.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/model.ts
- packages/core/src/codewhispererChat/storages/chatHistory.ts
History logic cleanup
- History does not need to be in triggerPayload
- ChatHistory does not need tools
- We don't need to create and maintain a separate newUserMessage object
---
> refactor(chat): simplify history logic

- packages/core/src/amazonq/webview/ui/apps/cwChatConnector.ts
- packages/core/src/codewhispererChat/clients/chat/v0/chat.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/tools/chatStream.ts
- packages/core/src/codewhispererChat/tools/toolUtils.ts
- packages/core/src/codewhispererChat/view/connector/connector.ts
Agentic chat should have a stop button
Implement `asyncEventProgressMessage` for CWChat
---
> feat(chat): show stop button for agentic loop

- packages/core/src/shared/utilities/processUtils.ts
- packages/core/src/test/shared/extensions/ssh.test.ts
Problem:
SSH Agent
can start the agent on windows:
Error: Test length exceeded max duration: 30 seconds
[No Pending UI Elements Found]
at Timeout._onTimeout (D:\a\aws-toolkit-vscode\aws-toolkit-vscode\packages\core\src\test\setupUtil.ts:46:32)
Solution:
- retry 2 times.
- set short timeout.
fix https://github.com/aws/aws-toolkit-vscode/issues/6891
---
> test(ec2): unreliable test "SSH Agent can start the agent on windows"

- packages/core/src/amazonq/webview/ui/tabs/generator.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- Pair programming features should be restricted to Q Chat but right now its available in other tabs like `/test`
- Multiple spinner loading events were causing delayed display of code difference views
- Improved performance by adding a specific check for 'cwc' tab type
- Optimized loading by eliminating redundant spinner events sent to the Mynah UI.
---
> fix(amazonq): Fixing bugs for agentic chat

- packages/core/src/codewhispererChat/clients/chat/v0/chat.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/shared/utilities/messageUtil.ts
- Sometimes we receive error in sendAIResponse where `await ToolUtils.queueDescription(tool, chatStream)` throws error and we don't handle it currently
- Minor refactoring to remove `tool-unavailble` custom action and `processUnavailableToolUseMessage` to re-use `processToolUseMessage` instead
- Store the error along with toolUse in chatSession so that we can handle it correctly in `processToolUseMessage`
---
> fix(chat): Fix ChatStream error caused by tool error

- packages/amazonq/.changes/next-release/Feature-80edcce3-4e32-4e74-a35a-af2242782181.json
- packages/amazonq/package.json
- packages/amazonq/src/extension.ts
- packages/core/src/amazonq/webview/generators/webViewContent.ts
- packages/core/src/amazonq/webview/ui/main.ts
- packages/core/src/amazonq/webview/ui/tabs/constants.ts
- packages/core/src/auth/auth.ts
- packages/core/src/codewhisperer/ui/statusBarMenu.ts
- packages/core/src/shared/extensionUtilities.ts
SageMaker AI and Unified Studio currently in prod uses version `1.32` and with manual upgrade to the newer version `>1.54`, observing agentic prompt added along with new commands `/test, /review, /doc` which are not supported by SageMaker apps
1. SageMaker doesnt support currently `/dev, /transform` commands and in addition to that disabling the above listed agentic Q commands that are not supported in SageMaker apps(both SMAI and SMUS). 
2. Also disabling the agentic options from quick pick items
3. Skip agentic welcome prompt
Testing
`npm run compile && npm run package` and tested with the artefacts manually in SMUS and SMAI
--- …
> feat(amazonq): Disable Q agentic commands not supported in SageMaker apps and skip agentic welcome prompt

- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/tools/fsRead.ts
- packages/core/src/codewhispererChat/tools/toolShared.ts
- packages/core/src/codewhispererChat/tools/toolUtils.ts
- packages/core/src/test/codewhispererChat/tools/fsRead.test.ts
- packages/core/src/test/codewhispererChat/tools/toolShared.test.ts
- fix(chat): Remove enforceMaxSize from fsRead
- It had the wrong limit size of 30720
- Remove it since we have toolResult size validation after executing the tool already
---
> fix(chat): Remove enforceMaxSize from fsRead

- packages/core/package.nls.json
- packages/core/src/amazonq/webview/ui/apps/cwChatConnector.ts
- packages/core/src/codewhispererChat/clients/chat/v0/chat.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/tools/fsWrite.ts
- packages/core/src/codewhispererChat/tools/toolUtils.ts
- packages/core/src/shared/utilities/diffUtils.ts
- packages/core/src/test/codewhispererChat/tools/toolShared.test.ts
Support workflows with multiple file writes without confirmation
- Set `requiresAcceptance` to `false` for all FsWrite executions
- Store backups of each FsWrite so we can revert the changes if needed
---
> feat(chat): support multi file write with reject and open diff

- package-lock.json
- packages/amazonq/.changes/next-release/Bug Fix-2daaf655-9a45-4104-94f9-06b9d8c703e2.json
- packages/amazonq/.changes/next-release/Bug Fix-338b0a7b-81fd-460a-82f4-8e65e4a0614c.json
- packages/core/package.json
- packages/core/src/amazonq/webview/ui/main.ts
* Amazon Q extension sometimes crashed with a grey screen
* Chat history icon was not easy for users to identify
* Update to [Mynah UI 4.30.0](https://github.com/aws/mynah-ui/releases)
Before (old icon)
After (new icon)
---
> deps(amazonq): Update to Mynah UI 4.30.0

- packages/amazonq/.changes/next-release/Feature-4b7ab0af-2fe3-4e21-be78-5fcb1896257c.json
- packages/core/src/amazonq/webview/ui/main.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/shared/db/chatDb/util.ts
Users don't have a way to export an Amazon Q chat
Add an export icon to chat tab bar and, allow users to export conversations from chat history. Users can choose Markdown or HTML format
---
> feat(amazonq): enable export chat feature

- packages/amazonq/.changes/next-release/Feature-846afd38-d618-4bd1-a3aa-7c74597502f1.json
- packages/core/src/amazonq/lsp/config.ts
- packages/core/src/amazonq/lsp/lspClient.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
Users can't add `@Code` context from PHP, Ruby, Scala, Shell, and Swift files
Add support for adding `@Code` context for PHP, Ruby, Scala, Shell, and Swift
---
> feat(amazonq): Add @Code context for PHP, Ruby, Scala, Shell, and Swift

- packages/core/src/codewhispererChat/clients/chat/v0/chat.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/shared/db/chatDb/chatDb.ts
- packages/core/src/shared/logger/logger.ts
Users lose all chats when they close VSCode, and there's no way to browse through chat history. Users also cant export their conversations to an easily shareable format.
Automatically persist conversations to JSON files in ~/.aws/amazonq/history, one for each workspace where Amazon Q chats occur. Add chat history and chat export buttons to top of Amazon Q toolbar. Clicking on the chat history button allows users to browse and search through chat history. Users click on an old conversation to open it back up (currently open conversations are in bold). Clicking on chat export button allows users to save chat transcript as a markdown or html.
Note: persistence + history is only for Q Chat Tabs (not /dev, /doc, /transform, etc.)
Agentic chat does not currently use this persisted history in …
> feat(amazonq): Add conversation persistence to agentic chat

- packages/amazonq/test/e2e/amazonq/testGen.test.ts
- packages/core/src/amazonqTest/chat/controller/controller.ts
In /test feature, test generation in languages other than Java and Python display message that they were not supported. Tests are generated for all languages, so this message needs to be removed.
Removed message to the user that /test only supports Python and Java
---
> feat(amazonq): Remove unsupported message for non-java python languages in /test

- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- after user click the reject button of running shell command, we call LLM to get response of shell command rejection
---
> feat(chat): Call LLM to get response of shell command rejection

- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/tools/chatStream.ts
Context is shown repeatedly in the UI if it is provided.
- Separate initial stream and context messages into separate functions
- Only show context on the first message of the loop
---
> fix(chat): only show context on first message

- packages/core/src/amazonq/webview/ui/apps/cwChatConnector.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
Remove static response string for shell command reject
- Use shell icon in shell command header
- Remove static response string for shell command reject
---
> fix(chat): Use shell icon in shell command header

- packages/core/src/codewhispererChat/tools/executeBash.ts
Before we are unclear about the commands' category and sometimes we show warning for some wide-used commands. Also we want to show the different warning message for destructive commands and mutable commands.
---
> fix(chat): change warning category and show the currect warning message

- package-lock.json
- package.json
- packages/core/src/amazonq/webview/ui/tabs/generator.ts
The pair-program was off by default and there was no tooltip. 
---
> fix(feat): add tooltip and set default mode to on

- packages/amazonq/.changes/next-release/Bug Fix-c6521d8e-639d-4672-b5fb-354c91c526be.json
- packages/amazonq/src/lsp/chat/commands.ts
- packages/core/src/amazonqFeatureDev/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/commands/registerCommands.ts
This command is called frequently and the command or related vscode "view" may not exist yet early in the extension startup/lifecycle.
---
> fix(amazonq): "failed to run command"

- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- When throttling happens today, we receive ISE from the server 
- Send back appropriate customer facing throttling error message
---
> fix(chat): Send back throttling error message

- packages/core/src/amazonq/webview/ui/apps/cwChatConnector.ts
- packages/core/src/amazonq/webview/ui/connector.ts
- packages/core/src/amazonq/webview/ui/main.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/view/connector/connector.ts
Chat input prompt should be disabled during the agentic loop
- Disable chat prompt
- Removed stop button for now
---
> fix(chat): disable prompt during loop

- packages/amazonq/src/lsp/chat/messages.ts
- packages/amazonq/test/unit/amazonq/lsp/chat/messages.test.ts
There was no implementation for the `copyToClipboard` message received from LSP for Amazon Q. The functionality did work because of the [MynahUI implementation](https://github.com/aws/mynah-ui/blob/b56a4b1df828eaa22515ef0f5af211eec24a5f89/src/helper/chat-item.ts#L36C1-L37C1), but for UI consistency to consider edge cases with webview clipboard, we decided to handle it explicitly.
Call the `copyToClipboard` function and add unit tests
---
> feat(amazon lsp): add copyToClipboard implementation

- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- JSON.parse error will break the agentic loop
- handle JSON.parse error gracefully
---
> fix(chat): handle JSON.parse error gracefully

- packages/core/src/amazonq/webview/ui/apps/cwChatConnector.ts
- packages/core/src/amazonq/webview/ui/connector.ts
- packages/core/src/amazonq/webview/ui/main.ts
- packages/core/src/codewhispererChat/clients/chat/v0/chat.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/tools/chatStream.ts
- packages/core/src/codewhispererChat/tools/fsRead.ts
- packages/core/src/codewhispererChat/tools/listDirectory.ts
- packages/core/src/codewhispererChat/view/connector/connector.ts
- We show read tool message for each file read which is occupying the entire chat with these messages which is not super important.
- Group all the read tool messaged under ContextList.
---
> fix(amazonq): Grouping read tool messages under contextList

- packages/amazonq/.changes/next-release/Bug Fix-09516662-6f63-4ec7-8d7e-763b3937b40b.json
- packages/core/src/codewhisperer/commands/startCodeFixGeneration.ts
> fix(amazonq): fix generate fix bug

- packages/amazonq/.changes/next-release/Bug Fix-45379b8c-1faa-4b04-951a-26e234c6dc03.json
- packages/amazonq/src/app/chat/activation.ts
- packages/amazonq/src/extensionNode.ts
- packages/amazonq/src/inlineChat/activation.ts
When toggling the experiment via, the `aws.experiments.amazonqChatLSP` flag in settings, inline chat fails to activate. Specifically, it appears the command fails to register.
```
command 'aws.amazonq.inline.invokeChat' not found
```
This happened because inline chat was activated as part of regular chat. When we use LSP chat, this then never gets activated. 
- Activate inline chat independently of regular chat. 
- Verified the fix by running extension with and without `aws.experiments.amazonqChatLSP` flag and using inlineChat in both cases. One of these cases is shown in the demo below. 
This will have to change once we consume LSP inline chat, as we don't want to activate both our inline chat and Flare's. 
https://github.com/user-attachments/assets/7e6f140d-2b3b-4ce4-9df1-01a1d713c02f …
> fix(amazonq): inline chat now activates independently of LSP chat

- packages/core/src/codewhispererChat/controllers/chat/chatRequest/converter.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/storages/chatHistory.ts
- packages/core/src/codewhispererChat/tools/chatStream.ts
```
An error occurred while processing your request.This error is reported to the team automatically. We will attempt to fix it as soon as possible.Details: Input is too long.
```
- A bug where status code is not being populated in error message
- A bug where output log window can be considered as active file which can cause waste of tokens
- A bug where toolUse JSON.parse is not being handled correctly
- Prune history if it's too large
- Fix status code bug in error message
- Fix active file bug
- Fix JSON.parse handling
---
- License: I …
> fix(chat): Prune history if it's too large, ignore log window as active file

- package-lock.json
- packages/amazonq/.changes/next-release/Bug Fix-9d840c3e-80a2-45a0-961f-8441b2339860.json
- packages/amazonq/.changes/next-release/Bug Fix-e8dc0bd0-b232-429c-b16a-f3bf993b19b4.json
- packages/amazonq/.changes/next-release/Bug Fix-ee90e4d2-aa78-403f-8b58-1464c6419778.json
- packages/core/package.json
from mynah-ui changelog:
- Fixed bug where tab bar buttons would disappear when closing a non-active tab 
- Fixed bug where markdown in detailed list descriptions could mess up layout through newlines
- Fixed issues with code blocks
- Code block max-height is no longer breaking inline codes
- Fixed issue where switching tabs while streaming makes expand buttons disappear on code blocks
- Fixed issue where while streaming, expand code block button blinks
- Code block action icons and show more resource link icons are now properly visible
Update to latest mynah-ui: [changelog](https://github.com/aws/mynah-ui/releases/tag/v4.30.1)
--- …
> deps(amazonq): mynah-ui 4.30.1

- packages/core/resources/css/amazonq-webview.css
- Markdown headers are too large 
- `no-padding` from mynah-ui is not working
Before:
- Override the font size for h1-h4
- Override the padding for any card under `no-padding`
After:
---
> style(chat): smaller headers, fix no-padding

- package-lock.json
- package.json
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/controllers/chat/model.ts
- packages/core/src/codewhispererChat/controllers/chat/telemetryHelper.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- currently no metrics for agentic chat
Emit telemetry events when:
- message shown to user (message sent from user already exists)
- diff was generated
- user rejected diff
- command was generated
- user accepted command
- user pressed stop button
- upstreamed metric to aws-toolkit-common: https://github.com/aws/aws-toolkit-common/pull/1010
- additional telemetry events for: user interrupts Q while generating, thumbs up/down
- see when user pressed stop (ex: chat, command execution, etc)
---
- License: I confirm that my contribution is made …
> telemetry(chat): agentic chat metrics

- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- Session context is missing for the follow ups in the agentic loop
- Bug in parsing toolUseInput which causes JSON.parse error
- Add session context for the agentic loop
- Fixed the bug in parsing toolUseInput
---
> fix(chat): Add session context for the agentic loop

- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
-  Set valid tooluse Input when parsing fails
- Server side cannot handle the raw string
---
> fix(chat): Set valid tooluse Input when parsing fails

- packages/core/resources/css/amazonq-webview.css
Padding override is not needed anymore
Revert padding change since it looks like it was already fixed in mynah-ui
---
> style(chat): undo padding change

- packages/core/src/codewhispererChat/tools/toolShared.ts
- packages/core/src/codewhispererChat/tools/tool_index.json
- packages/core/src/test/codewhispererChat/tools/toolShared.test.ts
- Large repo can cause result of listDirectory to contain more than 500K characters
- Reduce maxToolResponseSize from 800K to 200K
- Updated fsRead to read every 4000 lines if the file is too big
- Updated fsWrite to include explanation optional parameter
---
> fix(chat): Reduce maxToolResponseSize from 800K to 200K

- packages/core/src/shared/utilities/collectionUtils.ts
- packages/core/src/shared/utilities/processUtils.ts
- packages/core/src/test/shared/utilities/processUtils.test.ts
"memory threshold" message logged multiple times for a the same PID:
2025-04-11 ... Process 23662 exceeded memory threshold: 506986496
2025-04-11 ... Process 23662 exceeded memory threshold: 507019264
2025-04-11 ... Process 23662 exceeded memory threshold: 507052032
2025-04-11 ... Process 23662 exceeded memory threshold: 507084800
This is noisy in the logs.
Only log "memory threshold" once per PID.
---
> fix(childprocess): noisy "memory threshold" logs

- packages/amazonq/.changes/next-release/Bug Fix-42b2c2f0-e40e-4f97-842b-cb7ead1a010b.json
- packages/core/src/codewhisperer/commands/startCodeFixGeneration.ts
- packages/core/src/codewhisperer/service/securityIssueProvider.ts
1. `document.lineAt` would error due to line out of bounds.
2. File uploaded for codeFix is not the same as the one in editor
1. Remove `document.lineAt` logic 
2. Ensure dirty file is saved before zipping.
---
> fix(amazonq): make code fix's line number or file to be accurate

- packages/amazonq/.changes/next-release/Bug Fix-a8339a5e-5367-46a8-82f4-84369b384adb.json
- packages/core/src/amazonqDoc/session/session.ts
- packages/core/src/amazonqFeatureDev/client/featureDev.ts
- packages/core/src/codewhisperer/client/codewhisperer.ts
- packages/core/src/codewhisperer/commands/startTestGeneration.ts
- packages/core/src/codewhisperer/commands/startTransformByQ.ts
- packages/core/src/codewhisperer/service/testGenHandler.ts
- packages/core/src/codewhisperer/service/transformByQ/transformApiHandler.ts
- packages/core/src/codewhisperer/service/transformByQ/transformationResultsViewProvider.ts
- packages/core/src/shared/utilities/download.ts
- packages/core/src/testInteg/perf/downloadExportResultArchive.test.ts
The CreateUploadUrl and StartTestGenerationJob requests succeeded with the profile ARN  attached. However, the ExportResultArchive requests were made without this profile ARN, leading to inconsistent profile resolution between operations.
---
> fix(amazonq): downloadExportResultAcrchive api not passed with profileArn and cause 400 error

- packages/core/src/amazonq/webview/ui/main.ts
- main.ts is hard to parse and there's circular dependency between everything 
- refactor it so that all circular references can be resolved by calling a property on the WebviewUIHandler class
- the code is the **exact same** other then I reference properties on the WebviewUIHandler class directly, instead of calling the top level variables
- this makes [hybrid chat](https://github.com/aws/aws-toolkit-vscode/pull/7032) a lot easier, since it's directly calling the WebviewUIHandler
- these changes were done ontop of https://github.com/aws/aws-toolkit-vscode/commit/b127c9298a4e8172dd70ef646a6d2a5bf07b305c, so the latest main.ts changes are already refactored as well
---
- Your code changes …
> refactor(amazonq): Refactor main.ts into a re-usable component

- package-lock.json
- package.json
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/telemetryHelper.ts
- differentiate `Chat` vs `AgenticChat` for cwsprChatConversationType
- stop button functionality changed so event is being incorrectly emitted
- emit `AgenticChat` for cwsprChatConversationType
- correctly emit event when user clicks stop button
- https://github.com/aws/aws-toolkit-common/pull/1012 
---
> telemetry(chat): differentiate chat vs agenticChat

- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/tools/chatStream.ts
- packages/core/src/codewhispererChat/tools/executeBash.ts
- packages/core/src/codewhispererChat/tools/fsWrite.ts
- packages/core/src/codewhispererChat/tools/tool_index.json
- Multiple invocations of ExecuteBash and FsWrite can be confusing to the user
- Add explanation for tool invocation for fsWrite and executeBash
[
](url)
---
> feat(chat): Add explanation for tool invocation for fsWrite and executeBash

- packages/core/resources/css/amazonq-webview.css
- packages/core/src/amazonq/webview/ui/tabs/generator.ts
We want to show the programmer card on top of the page. And change the welcome message
---
> fix(chat): Add programmer card on top of the page. 

- packages/core/src/amazonq/webview/ui/texts/constants.ts
Currently the spinner text on waiting for LLM responses displays `Generating your Answer` which is not reflective of new features.
- Updated it to `Thinking`
---
> fix(chat): Updating spinner text to thinking

- packages/core/package.nls.json
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/tools/chatStream.ts
- packages/core/src/codewhispererChat/tools/fsRead.ts
- packages/core/src/codewhispererChat/tools/listDirectory.ts
- packages/core/src/codewhispererChat/tools/toolUtils.ts
- packages/core/src/test/codewhispererChat/tools/toolShared.test.ts
- Reading Tool and List Directory tool requires users acceptance if IDE wants to perform operation outside of workspace.
- This problem is fixed as part of this PR
---
> fix(chat): Adding conditional check for Read and List tool execution

- packages/core/src/codewhispererChat/constants.ts
- packages/core/src/codewhispererChat/tools/tool_index.json
- packages/core/src/shared/utilities/workspaceUtils.ts
- packages/core/src/test/codewhispererChat/tools/listDirectory.test.ts
- packages/core/src/testInteg/shared/utilities/workspaceUtils.test.ts
- ListDirectory tool will include all directories and files in the result which is not necessary and does not help LLM understand the structure better 
- Ignore directories and files that are not relevant to the code analysis in listDirectory
---
> fix(chat): Ignore directories and files that are not relevant to the code analysis in listDirectory

- packages/core/src/amazonq/webview/ui/apps/cwChatConnector.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
The Ux design does not meet the requirement
Make the undo a clickable button and change the string when user reject the generated code
---
> fix(chat): Add Undo clickable button and string change

- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/controllers/chat/telemetryHelper.ts
- do not have `requestID` and `errorMessage` in amazonq_messageResponseError
- emit amazonq_messageResponseError event with `requestID` and `errorMessage`
---
> telemetry(chat): request id and error message in error metric

- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- Message should be provided as part of header body but right now its passed as body directly.
- In existing IDE experience, If user asks a second question in the same chat tab, IDE overrides the first workflow read files with second workflow read files because `session.setMessageIdToUpdate` is unchanged(not defined to undefined after completion of first request.)
- Fixed in this as passing as part of header body.
- Cleaning the `session.setMessageIdToUpdate` value so for second request IDE won't update the first request read fileTree.
---
- …
> fix(chat): Fixing bug in read files and in accepting permissions

- packages/core/src/amazonq/webview/ui/apps/cwChatConnector.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/controllers/chat/telemetryHelper.ts
Right now, when user reject executing command, chat would send the reject message to LLM and LLM would response. The loop would still continue
---
> fix(chat): When user reject executing command, it should not send messages to LLM

- packages/core/src/amazonq/commons/types.ts
- packages/core/src/amazonq/webview/ui/followUps/handler.ts
- packages/core/src/amazonq/webview/ui/main.ts
- packages/core/src/amazonq/webview/ui/messages/controller.ts
- packages/core/src/amazonq/webview/ui/messages/handler.ts
- packages/core/src/amazonq/webview/ui/quickActions/handler.ts
- Flare's hybrid chat injects MynahUI reference after chat connector creation
- Implement delayed resolution so that onces MynahUI is injected everything dynamically resolves
---
> refactor(amazonq): Pass mynah references to ui handlers

- package-lock.json
- packages/core/package.json
- packages/core/src/amazonq/webview/ui/apps/cwChatConnector.ts
- packages/core/src/amazonq/webview/ui/followUps/handler.ts
- packages/core/src/amazonq/webview/ui/main.ts
- packages/core/src/amazonq/webview/ui/messages/controller.ts
- packages/core/src/amazonq/webview/ui/messages/handler.ts
- packages/core/src/amazonq/webview/ui/quickActions/handler.ts
- packages/core/src/shared/db/chatDb/chatDb.ts
Stop button disappears for subsequent conversations.
- Removed cancelButtonWhenLoading set to false across all places. No need for this, now stop button behaviour is consistent with all chat agentic and otherwise and in agents.
---
> fix(chat): fix for stop button for disappearing for subsequent conversations

- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/tools/fsWrite.ts
- packages/core/src/test/codewhispererChat/tools/fsWrite.test.ts
- Sometimes the fsWrite input is invalid causing the diff view to show 0 changes
- Add more fsWrite validation and validate before diff view
---
> fix(chat): Add more fsWrite validation and validate before diff view

- packages/amazonq/.changes/next-release/Bug Fix-a6e9ce99-842b-4d64-b9b0-967383d7acb9.json
- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/region/regionProfileManager.ts
- Before
customization is bound to a specific idc instance
- After
customization is bound to a specific Q profile and an idc instance can have multi profiles
therefore each Q profile will have access to different sets of customization
We need to validate if the selected customization is accessible from the user's selected profile, otherwise will get
```
*An error occurred while processing your request.*
This error is reported to the team automatically. We will attempt to fix it as soon as possible.
Details: The provided profile ARN and customization ARN is mismatched. (Service: CodeWhispererRuntime, Status Code: 403, 
```
--- …
> fix(amazonq): validate customization on profile change

- package-lock.json
- packages/amazonq/src/lsp/chat/messages.ts
- packages/amazonq/test/unit/amazonq/lsp/chat/messages.test.ts
- packages/core/package.json
- In order to enable chat history in Flare the: listConversationsRequestType, conversationClickRequestType, tabBarActionRequestType events need to be implemented
- Handle listConversationsRequestType, conversationClickRequestType, tabBarActionRequestType events
---
> feat(amazonq): Chat history provided through flare

- packages/amazonq/src/lsp/chat/webviewProvider.ts
- packages/amazonq/test/unit/amazonq/lsp/lspClient.test.ts
- packages/core/src/amazonq/index.ts
- packages/core/src/amazonq/lsp/lspClient.ts
- packages/core/src/amazonq/webview/generators/webViewContent.ts
- packages/core/src/shared/logger/logger.ts
- packages/core/src/shared/lsp/baseLspInstaller.ts
- packages/core/src/shared/lsp/lspResolver.ts
- packages/core/src/shared/lsp/types.ts
When lsp fetch/install/start fails it does not mention the download path, which could help with troubleshooting. #6972
[info] using amazonqWorkspaceLsp service configuration: default
[info] lsp: Failed to download latest "AmazonQ-Workspace" manifest. Falling back to local manifest.
[info] lsp: Finished setting up LSP server
[info] [Error] Starting client failed
[info] Error: write EPIPE
- Validate that `node` can actually run, before passing it to `LspClient`.
- Add more logging.
Also captured by telemetry:
```
2025-04-16 08:24:51.738 [debug] telemetry: languageServer_setup {
Metadata: {
missingFields: 'id',
metricId: '8da91a4b-ee00-4115-9b9e-796b5357402c',
traceId: '8569c16e-d319-486e-a6f3-d4ee91698468',
languageServerSetupStage: 'all',
duration: '1417',
result: 'Failed',
reason: …
```
> fix(lsp): verify that nodejs runs before starting LSP client

- packages/core/src/amazonq/webview/ui/main.ts
- packages/core/src/amazonq/webview/ui/quickActions/handler.ts
currently tabs get added to the tabs storage when the onTabAdd handler gets called.
In hybrid chat, the onTabAdd handler will never get called, because it first needs to be in the tabsStorage, which doesn't happen because the onTabAdd handler hasn't been called
in hybrid chat mode just add new tabs directly to the tabs storage
---
> fix(amazonq): quick action handler should add to tab storage

- package-lock.json
- package.json
- packages/core/src/codewhispererChat/controllers/chat/telemetryHelper.ts
- want to differentiate between a message without tool use (ex: what time is it) and a message with tool use (ex: write a docstring for my function)
- for both successful messages and messages that resulted in error, see if this message was apart of an agentic loop. 
- An agentic loop is when the LLM asks to run a tool and the LLM receives the results back of running the tool.
---
> telemetry(chat): see if message is apart of agentic loop

- packages/core/src/amazonq/webview/ui/apps/cwChatConnector.ts
- packages/core/src/codewhispererChat/clients/chat/v0/chat.ts
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/tools/chatStream.ts
- If user clicks on filePath(example: `util.py`) in read files, in existing user experience nothing happens. Ideally we need to open the file in the editor.
- Fixed this issue by maintaining a map between `messageID to filePath`, so IDE can display the files according to the use click on specific messageId.
**Demo:**
https://github.com/user-attachments/assets/b78d8de1-970f-4e0f-ac09-a0e93d5bd73c
- Refactored some parts of legacy code.
- Refactor the code diff part of code which is not related to this PR.
--- …
> fix(chat): Fixing issue with opening the file for read files.

- packages/amazonq/src/lsp/activation.ts
- packages/core/src/amazonq/lsp/lspClient.ts
- packages/core/src/amazonq/lsp/lspController.ts
- packages/core/src/shared/lsp/baseLspInstaller.ts
- packages/core/src/shared/lsp/lspResolver.ts
- packages/core/src/shared/lsp/manifestResolver.ts
- packages/core/src/shared/resourcefetcher/httpResourceFetcher.ts
- packages/core/src/shared/utilities/processUtils.ts
continues https://github.com/aws/aws-toolkit-vscode/pull/7043
Manifest resolver always reports:
Failed to download latest "…" manifest. Falling back to local manifest.
- In `fetchRemoteManifest()`, if the ETag indicates no new manifest is needed, return the local manifest instead of throwing an error
- Fix other ambiguous/misleading log messages.
---
> fix(lsp): manifest resolver always reports "Failed to download"

- packages/amazonq/src/lsp/client.ts
- packages/core/src/amazonq/lsp/lspClient.ts
- packages/core/src/shared/lsp/utils/platform.ts
Problem:
The logic added in a26437735b08 wasn't added in the other "lsp startup" module.
Solution:
Add it to the new module also.
> fix(lsp): verify that nodejs runs (again)

- packages/core/src/shared/lsp/baseLspInstaller.ts
- packages/core/src/shared/lsp/utils/cleanup.ts
- packages/core/src/test/shared/lsp/utils/cleanup.test.ts
When switching between different manifests, a newly downloaded version might chronologically be older than all previously downloaded versions, even though it's marked as the latest version in its own manifest. This is why we are getting the EPIPE error when trying out the alpha manifest. The cleanup deletes the language server right after it was downloaded
In such cases, we skip the cleanup process to preserve this version. Otherwise we will get an EPIPE error. At this point the version that was downloaded shouldn't be delisted, so we don't want to make sure its not removed
---
- Your code changes must meet the guidelines in [CONTRIBUTING.md](https://github.com/aws/aws-toolkit-vscode/blob/ma …
> fix(amazonq): improve lsp cleanup logic

- packages/core/src/codewhisperer/util/customizationUtil.ts
- packages/core/src/shared/globalState.ts
With the old VSCode auth, customization was stored in global state (indexed by connection ID). With the new auth from the Flare identity server, this no longer applies since there is only a single connection
* Consume the new AuthUtil in the customizationUtil
* Change `CODEWHISPERER_SELECTED_CUSTOMIZATION` in the global state to be a single value instead of a map
Investigate if it's possible to hook up the customization to the Q profile from the new Region Manager, so customizations are persisted between different logins
---
- License: I …
> feat(core): Store codewhisperer customization in global state as single value and consume new authUtil

- package-lock.json
- package.json
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/controllers/chat/telemetryHelper.ts
- Want to see the distribution of tools that LLM either used directly (no acceptance needed) or suggested (user acceptance required)
- Emit metric `toolUseSuggested` after LLM invokes any tool
---
> telemetry(chat): metric for distribution of tools 

- packages/core/src/codewhispererChat/tools/fsRead.ts
- packages/core/src/codewhispererChat/tools/tool_index.json
- packages/core/src/test/codewhispererChat/tools/fsRead.test.ts
- LLM sometimes gets confused when reading a large file that are truncated
- Improve fsRead truncation handling
---
> fix(chat): Improve fsRead truncation handling

- packages/amazonq/src/lsp/chat/activation.ts
- packages/amazonq/src/lsp/chat/webviewProvider.ts
- packages/amazonq/src/lsp/client.ts
- developer profiles are only synced to our local agents (/dev, /doc, etc). Now that the main chat panel is served by flare we need to update the profile information when it becomes available so that flare is using the correct profile for the request
- send profile information to flare on the initial request + subsequent changes to the active profile
- refresh the webview if the profile changes 
---
> feat(amazonq): sync developer profiles to flare chat panel

- packages/amazonq/src/lsp/chat/messages.ts
- packages/amazonq/test/unit/amazonq/lsp/chat/messages.test.ts
for agentic chat with language server, we need client to handle open files and update context command
---
> feat(amazonq): handle context command and open file for chat with lsp

- packages/core/src/codewhispererChat/controllers/chat/telemetryHelper.ts
- `error: TypeError: Cannot read properties of undefined (reading 'emit') `
- telemetry can throw an error and break tool execution
- use `run` instead of emit
- add try catch
---
> telemetry(chat): try catch for telemetry to not break tool execution

- packages/core/src/amazonq/webview/ui/tabs/generator.ts
- we want different tooltip when pair programmer is on vs off
---
> fix(chat): tooltip for pair programmer

- packages/core/src/codewhisperer/util/editorContext.ts
linting fails because of https://github.com/aws/aws-toolkit-vscode/commit/b4de24fbfb008be534f76d385dfa58eb79eb9242. Lei was too busy to fix so I'm just doing a followup PR
---
> fix(lint): fix editorContext lint

- packages/amazonq/src/lsp/chat/activation.ts
- packages/amazonq/src/lsp/chat/webviewProvider.ts
when the flare chat panel refreshes on log in/log out, the message listener never gets disposed of, causing the next webview instantiation to have two message listeners that are forwarding messages to the ui
dispose of the message listener when the webview gets disposed
---
> fix(amazonq): duplicate messages in flare chat

- package-lock.json
- packages/core/package.json
New updates for mynah UI from beta-6
- update for Mynah UI to beta 6
---
> feat(chat): update for Mynah UI to beta 6

- packages/core/src/amazonq/webview/ui/main.ts
- packages/core/src/codewhispererChat/controllers/chat/messenger/messenger.ts
- packages/core/src/codewhispererChat/tools/fsRead.ts
- IDE requests permission twice when accessing files outside workspace
- Users can see insert at cursor and copy buttons for bash commands.
- UX stying: No borders for 
- Read and List directory files/folder outside of the workspace
- Code diff view UX
- Execute bash command UX
- `Insert at cursor` option is available if pair programming mode is enabled.
- Fixed issue issue of showing reading files twice.
- Fixed issue of showing insert at cursor and copy buttons for bash commands.
- Added borders for mentioned UX.
- User can see only `Copy` option (remove `Insert at cursor` option) if pair programming mode is enabled.
- If user turn off pair programming mode, IDE shows both `Insert at cursor` and `Copy` options.
---
- Treat all work as PUBLIC. Private `feature/x` branches will not be …
> fix(chat): UX fixes for agentic chat

- packages/core/src/codewhispererChat/controllers/chat/tabBarController.ts
- packages/core/src/shared/db/chatDb/util.ts
When tabs are restored, directive messages stored in the explanation field of toolUses are not being displayed.
Restore toolUse explanations when restoring tabs
Tested manually
Uploading Screen Recording 2025-04-18 at 4.15.40 PM.mov…
---
> fix(amazonq): Restore toolUse explanations when restoring tabs

- packages/amazonq/src/lsp/client.ts
local workspace context has been added to flare and its needed for falcon changes 
we don't have `aws.q` settings in vscode so we have to use the language server middleware to send back the settings
Once local workspace context is fully working and in the manifest I'll uncomment
---
> fix(amazonq): enable local workspace server through flare

- package-lock.json
- packages/amazonq/package.json
- packages/amazonq/src/lsp/chat/messages.ts
- packages/amazonq/src/lsp/chat/webviewProvider.ts
- packages/core/package.json
- packages/core/src/shared/settings-amazonq.gen.ts
agentic chat should have a pair programming card that appears at the top of chat
implement it with the following behaviors:
1. If the pair programming card was dismissed in a previous session, never show it again
2. Continue showing the pair programming card in new basic chat tabs until you click the "X" to dismiss it. Once the "X" is pressed it will never be shown for future tabs in the current chat-client session or future sessions
3. If you have multiple basic chat tabs open and click X on one of them it only closes the programmer mode card for that single tab
depends on: https://github.com/aws/language-servers/pull/1023
--- …
> feat(amazonq): add pair programming card

- packages/amazonq/src/extensionNode.ts
We introduced a new auth state `pendingProfileSelection`, however the current code path will determine the connectivity to be `disconnected` and thus we observe a drastic drop of `connected` users and increase of `disconnected`.
---
> telemetry(amazonq): correct auth_userState telemetry 

- packages/amazonq/src/lsp/client.ts
q developer profiles are being fetched by VSCode + flare on the same token causing requests to be throttled
temporary disable profile fetching. The real solution will need to be implemented in flare, which should disable profile fetching by default for VSCode?
---
> fix(amazonq): temporarily disable q developer profiles

- packages/amazonq/src/lsp/chat/messages.ts
links clicked in help and responsible ai policy don't open
implement info link and link click handlers
---
> feat: handle link clicks in /help

- package-lock.json
- packages/amazonq/src/lsp/chat/messages.ts
- packages/core/package.json
agentic chat has stop response disabled
make it so that when its clicked the token is disposed off and the UI unlocks
---
> feat(amazonq): handle stop response

- packages/amazonq/src/lsp/chat/messages.ts
- packages/core/src/amazonq/commons/controllers/contentController.ts
Sometimes we need to show the diff in reverse order (left/right flipped).
Add a flag to show the diff in reverse order. Right now we will always do this in the lsp diff handler to avoid the need to create a temporary file.
---
> feat(amazonq): option to show diff in reverse order

- packages/amazonq/src/lsp/chat/messages.ts
telemetry events forwarded to flare aren't emitted 
emit them
---
> feat(amazonq): emit flare telemetry events

- packages/amazonq/src/lsp/chat/messages.ts
- packages/core/src/amazonq/commons/controllers/contentController.ts
Clicking on diff for newly created files did not open diff
Allow opening diffs for empty string
---
> fix(amazonq): diff not appearing for new files

- packages/amazonq/.changes/next-release/Feature-2a696d00-e8c8-44a4-ab2c-2204b4d8e31d.json
- packages/amazonq/test/unit/codewhisperer/region/regionProfileManager.test.ts
- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/client/codewhisperer.ts
- packages/core/src/codewhisperer/index.ts
- packages/core/src/codewhisperer/region/regionProfileManager.ts
- packages/core/src/codewhisperer/util/customizationUtil.ts
- packages/core/src/shared/featureConfig.ts
- packages/core/src/test/amazonq/customizationUtil.test.ts
Due to throttling issue we already encounter now in PROD, we decided to revert it back and fix the throttling issue first then bring this back afterward.
This reverts commit 70ba83fc066cfe8a1f9f50e5eb73a5e1b51d42f4. #7060 
---
> fix(amazonq): revert 7060 show customization across profiles

- packages/amazonq/src/lsp/chat/messages.ts
ChatUpdate notifications are not getting forwarded to UI
Forward chat update notification
---
> fix(amazonq): forward chat update notification

- packages/amazonq/.changes/next-release/Bug Fix-4323842a-bd34-4c49-9a03-12620cce0203.json
- packages/core/src/codewhisperer/region/regionProfileManager.ts
- packages/core/src/codewhisperer/service/inlineCompletionService.ts
- packages/core/src/codewhisperer/ui/codeWhispererNodes.ts
- packages/core/src/codewhisperer/ui/statusBarMenu.ts
Inline suggestion users who upgraded to the new extension version with region profile selection need to select a profile, but are not prompted in a significant way to do so.
If they didn't select a profile, inline suggestions would just stop working for them. There is no obvious hint to the user that to get inline suggestions working again they must select a profile.
If a profile is not selected, show the status bar as not connected. Once the status bar is clicked they will see the top item telling them they must select a profile to get features working. This opens a quick pick of the profiles they can select from.
https://github.com/user-attachments/assets/7115ed56-8faf-486f-beaa-6f09cbca56e7
---
- Treat all work as PUBLIC. Private `feature/x` branches will not be squash-merged at …
> fix(amazonq): indicate profile needs to be selected from status bar menu

- packages/amazonq/src/lsp/chat/webviewProvider.ts
Reloading the webview directly causes export/history to be missing
Add a specialized handler that simulates reloading the webview when a profile changes, rather than actually refresh everything. This is required because the chat-client relies on initializedResult values from the language server that are only sent once
---
> fix(amazonq): simulate refresh of chat

- packages/amazonq/src/lsp/client.ts
Reverts aws/aws-toolkit-vscode#7118
We were getting throttled because of https://github.com/aws/aws-toolkit-vscode/pull/7060. That's been reverted so we should be safe to re-enable this
> Revert "fix(amazonq): temporarily disable q developer profiles"

- packages/amazonq/src/lsp/chat/activation.ts
cw chat is still registered and sending events to the frontend, in some cases those UI handlers are the same as they are on the chat-client. This causes disruptive behavior to happen like "normal" chat tabs being restored when they shouldn't
disable restoreTabMessage, contextCommandData
get rid of cw app start up
---
> fix(amazonq): deny restoreTabMessage/contextCommandData messages from cwc chat

- packages/amazonq/src/lsp/chat/messages.ts
It's not obvious that the LSP language client passes on telemetry events to Toolkits Telemetry
Add clarifying comment to the code implementation
---
> fix(amazonq): Add clarifying comment to telemetry pass through mechanism

- packages/core/src/shared/lsp/lspResolver.ts
When downloading the LSP artifacts from the manifest, there are some large ones (100+ MB).
For a slow connection this can take 1+ minutes, but our timeout for the "downloading" message
is set to disappear much earlier. So it is still downloading in the background, but the message
has disappeared and the user thinks that the download is done.
Increase the timeout to 30 minutes, which will ensure the downloading message sticks around
while the download is still happening.
In another commit this fixes a separate HTTP client bug where it would time out a request if it took longer than 3 seconds.
This caused downloads to be aborted (separate from the download message disappearing). Now it times out after 30 minutes.
---
- Treat all work as PUBLIC. Private `feature/x` branches will not be …
> fix(lsp): LSP download timeout message disappears too early

- package-lock.json
- package.json
- bump aws-toolkit-common version from 1.0.312 to 1.0.316
---
> telemetry(amazonq): bump aws-toolkit-common version to 1.0.316

- packages/amazonq/src/lsp/auth.ts
- packages/amazonq/src/lsp/client.ts
race conditions can occur with getConnectionMetadata
instead send the start url through the token update. When it's done this way you don't need to [set getConnectionMetadata](https://github.com/aws/language-server-runtimes/blob/5ba754af403a6f35cd771f27efb987c1580ae6b5/runtimes/runtimes/auth/auth.ts#L158)
---
> fix(amazonq): send sso startUrl on token update

- package-lock.json
- packages/core/package.json
- packages/core/src/amazonq/webview/ui/main.ts
- UI styles coming from flare and the local instance are conflictin.
- Latest production version of mynah-ui has the ability to avoid loading styles. Bumped up mynah-ui version and set `loadStyles` to `false`.
---
> feat(amazonq): update mynah version with no style loading option

- packages/amazonq/src/lsp/auth.ts
- packages/amazonq/src/lsp/client.ts
When the server restarted due to a crash, the auth token was not sent again. This caused users to run in to the state where if it crashed and restarted, when they sent a subsequent chat message they'd get stuck with the server asking the user to Authenticate.
Note that server restart is triggered automatically by the LanguageClient, I think.
Detect when the server is restarted and manually resend the bearer token again.
Note, this solution needs to be revisited since there may be other initialization logic that needs to run on server restart, aside from just the bearer token.
1. Ensure you do not have a workspace open, you can open a new vscode window at the top left `File` > `New Window`
2. Make a random folder in your home directory
3. Make a couple typescript files in that folder
4. …
> fix(chat): Resend auth token on server restart

- packages/amazonq/src/lsp/chat/messages.ts
If the server sends a partial result without a body, we currently ignore it. 
- explicitly check for undefined. 
---
> fix(amazonq): accept empty body partial result. 

- packages/amazonq/src/lsp/chat/error.ts
- packages/amazonq/src/lsp/chat/messages.ts
- packages/amazonq/test/unit/amazonq/lsp/chat/error.test.ts
Response errors returned by the LSP are returned to chat after prepending a custom error message. We can remove this custom error message and rely on flare for a single implementation of this error message. 
- perform a sanity check on the response before casting it to the proper type. 
- log the last result from the language server to help debug. 
- include the requestId clearly in the logs. 
---
> fix(amazonq): handle response errors from lsp

- packages/amazonq/.changes/next-release/Bug Fix-489e72aa-bb0d-4964-bd84-002f25db6b5f.json
- packages/amazonq/package.json
- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/commands/types.ts
- packages/core/src/codewhisperer/region/utils.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/shared/settings-amazonq.gen.ts
If a user has not selected Q Developer Profile after signing in, their features will not work.
Some existing users, before the introduction of Q Developer Profiles, who were already signed in had their features stop working because they didn't select a profile.
On startup if we detect the user did not select a profile, then send a warning message that their features will not work until they select one. The message will have a button to allow them to select a profile through quickpick, or entirly ignore the message and not show it again.
---
- …
> fix(amazonq): Warn user Developer Profile not selected

- packages/amazonq/test/e2e/inline/inline.test.ts
- packages/core/src/auth/sso/clients.ts
- packages/core/src/shared/utilities/collectionUtils.ts
- packages/core/src/shared/utilities/textUtilities.ts
- packages/core/src/shared/vscode/commands2.ts
- packages/core/src/test/shared/utilities/collectionUtils.test.ts
If we want to log a large json object with giant strings (think whole files), it can make the logs difficult to read. This is especially relevant when the underlying string values are not very important.  
- allow the string values to be truncated with `maxStringLength` option. 
I am planning to port this utility to Flare to improve the logging experience there, and want this functionality to exist there however I thought this could be useful here too. 
--- …
> feat(core): add value length cap to partialClone

- packages/amazonq/src/lsp/chat/webviewProvider.ts
401 and CSP errors when launching hybrid chat on windows
fix paths
---
> fix(amazonq): 401 errors on windows

- packages/amazonq/.changes/next-release/Bug Fix-8290a06f-ee3f-4235-b8af-faedb1bdfbe4.json
- packages/core/src/codewhisperer/region/regionProfileManager.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/login/webview/vue/amazonq/backend_amazonq.ts
- packages/core/src/shared/globalState.ts
- packages/core/src/shared/logger/logger.ts
- packages/core/src/shared/utilities/resourceCache.ts
revision of #7134, this pr aims to address the comment from the previous PR https://github.com/aws/aws-toolkit-vscode/pull/7134#discussion_r2056518840 to extract the logic to a shared module so the diff against 7134 is expected to be large.
after deployment 4/21, service has a strict 1 tps throttling policy and there was no caching for the API call previously.
It will impact users as long as they have multiple ide instances opened as all of them will make list profile call while users attempt to sign in.
1. cache the api result for 60 seconds for reuse 
2. use lock to prevent multiple instances trying to call at the same time. Only 1 will make the service call and the rest will wait until it's done and read from the cache.
---
- Treat all work as PUBLIC. Private `feature/x` branches will …
> fix(amazonq): fix enterprise users not able to sign in correctly if they have 2+ vscode instances open

- packages/amazonq/src/lsp/chat/commands.ts
- packages/core/src/codewhispererChat/app.ts
- packages/core/src/codewhispererChat/commands/registerCommands.ts
explain, refactor, fix, optimize right click menus aren't working
re-enable them through flare's genericCommand message
- handle generateUnitTests
- handle explainIssue
both of these need flare API changes to send generic prompts from the frontend to the backend
---
> fix(amazonq): handle explain, refactor, fix, optimize, sendToPrompt

- packages/core/src/codewhisperer/util/authUtil.ts
https://github.com/aws/aws-toolkit-vscode/pull/7151/commits/97a44821ee9bb65cdc737011e81dc6e87ab23136
this commit breaks the cache by resetting the flag/lock on connection changed. When users sign in and have multiple VSCode instances, all windows will get a `onConnectionChanged` hence overwrite the lock/flag and load the resource from live.
Only clear the cache when users sign out, and it's sufficient for "change connection" use case as well. (users have to sign out before connecting with different connection)
--- …
> fix(resourceCache): patch #7151

- packages/core/src/shared/utilities/resourceCache.ts
> fix(resourcecache): improve logging

- packages/amazonq/src/lsp/client.ts
context items should be always on and not controlled by workspace setting
there need to be a separate setting to control @workspace indexing, out of scope for this PR
---
> fix(amazonq): enable local context for falcon

- package-lock.json
- packages/amazonq/src/lsp/chat/messages.ts
- packages/core/package.json
- packages/core/src/amazonq/commons/controllers/contentController.ts
- packages/core/src/amazonq/commons/controllers/diffContentProvider.ts
- packages/core/src/amazonq/index.ts
- packages/core/src/shared/utilities/textDocumentUtilities.ts
- packages/core/src/shared/utilities/textUtilities.ts
- packages/core/src/test/amazonq/commons/controllers/contentController.test.ts
- packages/core/src/test/shared/utilities/textDocumentUtilities.test.ts
The current viewDiff implementation is restricted to only allowing comparing the current file contents. This means it's not possible to view a diff for a change that was applied at a previous point in time.
- Create a new `DiffContentProvider` that can support showing multiple URIs in the same scheme. The current `ContentProvider` has a limitation that it can only show a single URI. 
- Refactor the code to use a defined type `ViewDiffMessage` instead of `any`
- Change the logic so that diffs are stored in memory instead of a temp file on disk
---
- Your code changes must meet the guidelines in [CONTRIBUTING.md](https://github.com/aws/aws-toolkit-vscode/blob/master/CONTRIBUTING.md#guidelines) …
> feat(amazonq): support multiple uri in a single diff scheme

- packages/amazonq/src/lsp/lspInstaller.ts
- packages/core/src/shared/lsp/baseLspInstaller.ts
- packages/core/src/shared/lsp/lspResolver.ts
When installing the LSP for Q we get a message that says `"Installing 'Amazon Q' language server"`, but they want it to be slightly different (`"Updating Amazon Q plugin"`). The issue is the base class for the lsp installer class has a generic message that is not easy to customize.
Allow an override downloading message to be defined in each specific LspInstaller implementation. This message is then routed in to the LspResolver (the thing that downloads the Lsp), and the message is displayed here. This override message will show when the download is happening. Everyone is happy.
---
- Your code changes must meet the guidelines in [CONTRIBUTING.md](https://github.com/aws/aws-toolkit-vscode/blo …
> refactor(amazonq): Change Q LSP downloading message text

- packages/amazonq/src/lsp/chat/activation.ts
- packages/amazonq/src/lsp/client.ts
- packages/amazonq/src/lsp/config.ts
- packages/core/src/shared/extensionGlobals.ts
- packages/core/src/shared/logger/logger.ts
Same problem as https://github.com/aws/aws-toolkit-vscode/pull/7172
- listen to logLevel change events, and forward them to LSP. 
- pass initial logLevel to the LSP as well. 
- This requires mapping the local levels to the Flare Levels. This is done with the following:
```
export const lspLogLevelMapping: Map<vscode.LogLevel, LspLogLevel> = new Map([
[vscode.LogLevel.Error, 'error'],
[vscode.LogLevel.Warning, 'warn'],
[vscode.LogLevel.Info, 'info'],
[vscode.LogLevel.Debug, 'log'],
[vscode.LogLevel.Trace, 'debug'],
[vscode.LogLevel.Off, 'error'], // TODO: once the language server supports a no-log setting, we can map to that.
])
```
- Because of this mapping, it means that to enabled 'debug' logs in Flare, we set to 'trace' in VSC which can be confusing for contributors. 
---
- Treat all …
> feat(amazonq): sync lsp logging with local configuration.

- packages/amazonq/src/lsp/client.ts
the extension name doesn't match what flare expects: https://github.com/aws/language-servers/blob/main/server/aws-lsp-codewhisperer/src/shared/telemetryUtils.ts#L50
update it
---
> fix(amazonq): fix extension name in lsp initialization

- packages/core/src/codewhisperer/util/codewhispererSettings.ts
set default to empty string instead of undefined for workspaceIndexCacheDirPath
---
> fix(amazonq): type error for workspaceIndexCacheDirPath

- packages/core/src/amazonq/webview/ui/quickActions/handler.ts
using the generate tests right click command won't work because a new tab never gets created, causing a "no more tabs available" warning
If we're using the right click -> generate tests command AND there isn't a /test tab open then create a new tab
---
> fix(amazonq): open review tab for generate tests

- packages/amazonq/src/lsp/chat/commands.ts
- packages/core/src/codewhispererChat/commands/registerCommands.ts
- Explain issue from security scan hasn't been hooked up when moving to flare
- use sendToPrompt from flare to automatically submit an "explain message". This message contains a prompt that gets shown to the user and an escaped prompt that gets sent to the backend
- text/formatting for uiMessage and contextMessage were taken from codewhisperer chat
---
> fix(amazonq): explain issue fails

- packages/amazonq/src/app/chat/activation.ts
- we don't need workspace indexing on extension side anymore,
the `isVectorIndexEnabled` setting controls if we build vector index used for @workspace feature, since now chat is moving to language server, the extension side workspace lsp should be only responsible for building BM25 index for inline, and not responsible for vector indexing for chat.
- stop vector indexing on extension
- next step is to tie workspace index setting to language server workspace indexing, will be in next PR
---
- License: I confirm that my contribution is made under …
> fix(amazonq): stop workspace indexing in extension

- packages/amazonq/src/lsp/client.ts
With https://github.com/aws/language-servers/pull/1201 we can now use userSetting to control vector indexing
---
> fix(amazonq): tie enableLocalIndex back to user setting

- packages/amazonq/src/lsp/chat/messages.ts
- packages/core/src/amazonq/commons/model.ts
- packages/core/src/amazonq/index.ts
- packages/core/src/amazonqDoc/session/session.ts
- packages/core/src/amazonqFeatureDev/constants.ts
- packages/core/src/amazonqFeatureDev/session/session.ts
Chat results are never getting added to the reference tracker
If code references are available, add them to the reference tracker
---
> feat(amazonq): add reference log for chat messages

- packages/core/src/lambda/vue/configEditor/samInvokeBackend.ts
- packages/core/src/lambda/vue/configEditor/samInvokeComponent.vue
- packages/core/src/lambda/vue/configEditor/samInvokeFrontend.ts
- packages/toolkit/.changes/next-release/Feature-b9357975-bda4-4ec8-a8ea-d955708b7596.json
Add checkbox in local invoke webview so customers can choose to locally invoke with or without debugger
No tests added since the functionality is already tested here: https://github.com/aws/aws-toolkit-vscode/blob/a7732b96982adbbac691f2869db3136c159d80ed/packages/core/src/test/shared/sam/debugger/samDebugConfigProvider.test.ts#L111
---
> feat(lambda): Add checkbox in local invoke webview for debugger

- packages/amazonq/src/lsp/chat/webviewProvider.ts
In [this PR](https://github.com/aws/language-servers/pull/1172/files#diff-3ef0f209f2cb39ae2f8b1c622f885a33cbf797f1882dfb4b22fb4cb17bcf901aR381) they're going to add a config setting for indicating we're in agentic mode
always enable it so we see the agentic UI
---
> fix(amazonq): enable agentic mode

- packages/amazonq/src/lsp/chat/messages.ts
We're currently adding the reference log on partial responses and on complete responses, causing duplicate messages
on flare side we're combining all code references into the final response, so we just need to emit once
---
> fix(amazonq): duplicate code reference in reference log

- packages/amazonq/.changes/next-release/Feature-73d53c1b-6a88-448a-a4a3-144e99bd95e6.json
- packages/amazonq/test/e2e/amazonq/transformByQ.test.ts
- packages/amazonq/test/unit/amazonqGumby/transformApiHandler.test.ts
- packages/core/src/amazonqGumby/chat/controller/controller.ts
- packages/core/src/amazonqGumby/chat/controller/messenger/messenger.ts
- packages/core/src/amazonqGumby/chat/controller/messenger/messengerUtils.ts
- packages/core/src/amazonqGumby/chat/session/session.ts
- packages/core/src/codewhisperer/commands/startTransformByQ.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/models/model.ts
- packages/core/src/codewhisperer/service/transformByQ/transformApiHandler.ts
- packages/core/src/codewhisperer/service/transformByQ/transformFileHandler.ts
- packages/core/src/codewhisperer/service/transformByQ/transformMavenHandler.ts
- packages/core/src/codewhisperer/service/transformByQ/transformationHubViewProvider.ts
- packages/core/src/codewhisperer/service/transformByQ/transformationResultsViewProvider.ts
- packages/core/src/dev/config.ts
- packages/core/src/test/codewhisperer/commands/transformByQ.test.ts
We should perform builds client-side (rather than server-side) to handle customers’ unique / challenging local environments, which often cause our server-side build to fail.
Periodically download intermediate `diff.patch` files, apply them to a copy of the project, perform the local build, then upload the build logs and resume the transformation.
---
> feat(amazonq): client-side build support

- packages/amazonq/src/lsp/client.ts
- packages/core/src/amazonq/lsp/lspClient.ts
- packages/core/src/shared/lsp/utils/platform.ts
- packages/core/src/shared/utilities/processUtils.ts
- packages/core/src/test/shared/utilities/processUtils.test.ts
Some processes use significantly more cpu/memory than others, so we shouldn't hold them to the same static threshold. 
As an example, the language servers are consistently using more memory than the 100 MB threshold. 
Based on some experimentation with different sized workspaces, I've noticed that the process running agentic chat uses roughly 80MB-150MB of memory, and the workspace indexing uses 550 - 700 MB memory.  
- Allow each child process to set a warning threshold, with a default of 100MB of memory. 
- Set the Q LSP threshold to 200 MB, and workspace indexing to 800 MB. 
- This should help to allow these logs to point to real concerns, rather than be noise. 
---
- Your code changes …
> feat(amazonq): allow child processes to define custom thresholds

- packages/amazonq/src/extensionNode.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/login/webview/commonAuthViewProvider.ts
- packages/core/src/login/webview/vue/amazonq/backend_amazonq.ts
The new auth util on Flare LSP is not yet supporting telemetry events
* Migrate `getTelemetryMetadata` and `getAuthFormIds` to the new AuthUtil
* Restore commented-out references
**Note: CI is exepected to fail, unti tests not yet addressed and rebase with mainline is needed**
---
> feat(amazonq): Add telemetry for auth through LSP

- packages/amazonq/.changes/next-release/Feature-3fb0a20d-75e8-4141-a1a6-d8cfd9b7f3f0.json
- packages/core/src/login/webview/vue/amazonq/backend_amazonq.ts
- packages/core/src/login/webview/vue/backend.ts
- packages/core/src/login/webview/vue/login.vue
- packages/core/src/login/webview/vue/toolkit/backend_toolkit.ts
- packages/core/src/shared/globalState.ts
Customers hope we could auto-fill the url and region with the last used one. Actually there is a customer saying it would cause friction for their adoption
Memorize the url/region as a global state within VSCode and use them when they're present
---
> feat(auth): memorize and autofill users' last sso login info

- packages/amazonq/src/extension.ts
- packages/amazonq/src/extensionNode.ts
- packages/amazonq/src/lsp/activation.ts
- packages/amazonq/src/lsp/chat/messages.ts
- packages/amazonq/src/lsp/chat/webviewProvider.ts
- packages/amazonq/src/lsp/client.ts
- packages/core/src/codewhisperer/util/authUtil.ts
Agentic chat introduced code changes that break auth on LSP
Fixes for the auth flow:
* Move instantiation of `AuthUtil` into `startLanguageServer` sinc ethe function uses several AuthUtil calls, which fail if it is not instantiated yet
* Remove the dependency of LSP on glibc patch, since auth doesn't work if LSP is not started
* Add URL opening capability to the new `ShowDocumentRequest` handler, and remove the old handler from `client.ts`.
* Fix bug where session isn't restored upon start of extension when SSO is expired.
---
- License: I …
> fix(amazonq): Bug fixes for LSP auth on agentic mode

- packages/amazonq/src/app/inline/completion.ts
the isSuggestionsEnable setting isn't respected
if someone disabled suggestions via a setting or from the status bar then don't return anything for automatic triggers
---
> fix(amazonq): respect suggestions enabled setting for auto trigger

- packages/amazonq/src/lsp/config.ts
There is currently no way to test gamma changes without manually overriding the endpoint. 
- create a feature branch that points to gamma so that we can easily test in pre-prod. 
---
> feat(amazonq): initialize feature branch with gamma endpoint. 

- .github/CODEOWNERS
Flare is marked as codeowners of the following:
```
packages/core/src/codewhispererChat/ @aws/flare
packages/core/src/amazonq/ @aws/flare
```
AFAIK, the flare team hasn't done significant work in these folders, and does not have bandwidth to review changes here. 
- `packages/core/src/codewhispererChat/ ` will be mostly deleted when we complete the migration to Flare (ex. [here](https://github.com/aws/aws-toolkit-vscode/pull/7237)).
- `packages/core/src/amazonq/ ` contains most changes to the amazon q extension, which seems out of scope for the Flare team. 
Having flare as codeowners requires the toolkits team to bypass their approval on any PRs touching files in these directories. This can lead to delayed merges and confusion. 
- remove flare as a code owner. 
---
- Treat all work as …
> build(core): remove flare as codeowners

- packages/core/src/shared/settings.ts
Misleading log message when a setting returns `null`, even if the caller specified `defaultValue`:
[error] Settings (amazonQ): failed to read "workspaceIndexCacheDirPath":
Unexpected type cast: got object, expected primitive String
`cast()` considers `null` to be "object" type, which is misleading. If the caller passed a `defaultValue`, they have intentionally opted-in to ignoring this situation, and *don't* want this kind of log message.
If a setting returns `null|undefined`, skip `cast()` and return `defaultValue` immediately. Don't log an error message.
---
- Your code changes must meet the guidelines in [CONTRIBUTING.md](https://github.com/aws/aws-toolkit-vscode/blob/master/CONTRIBUTING. …
> fix(logging): misleading "settings failed" message

- packages/core/src/codewhisperer/util/customizationUtil.ts
Customization will only have "1" parent profile, so theoretically we don't need another call of listAvailableCustomization to check if the new profile has access to given profile or not. Instead, we could simply switch to default.
---
> refactor(amazonq): reduce extra call of listAvailableCustomization

- packages/amazonq/src/extensionNode.ts
- packages/amazonq/src/inlineChat/activation.ts
- packages/amazonq/src/inlineChat/controller/inlineChatController.ts
- packages/amazonq/src/inlineChat/provider/inlineChatProvider.ts
- packages/amazonq/src/lsp/chat/messages.ts
- packages/amazonq/src/lsp/client.ts
- packages/amazonq/src/lsp/encryption.ts
- packages/amazonq/src/lsp/utils.ts
- packages/core/src/shared/settings-toolkit.gen.ts
- packages/toolkit/package.json
This is the initial set of work required to get inline chat running through flare. 
- **add a feature flag for inline chat**: this allows testing of the two implementations side-by-side by flipping the feature flag. 
- **move general utils out of chat**: stuff like encryption and editorState can all be reused. 
- **render full diff response from inline chat**: this does not include progress updates from the language server. 
https://github.com/user-attachments/assets/0dff58b7-40f7-487d-9f9e-d58610201041
- ensure telemetry is still being emitted. 
- add tests for new flow. (there aren't any for the existing one)
- handle partial events from the language server. 
- selecting part of a line will cause the text to insert mid-line 
- running inline-chat without a selection causes the entire …
> feat(amazonq): add experiment for basic e2e flow of inline chat through Flare.

- packages/amazonq/src/inlineChat/provider/inlineChatProvider.ts
- packages/amazonq/src/lsp/chat/messages.ts
- packages/amazonq/src/lsp/encryption.ts
- packages/amazonq/test/unit/amazonq/lsp/encryption.test.ts
Follow up to https://github.com/aws/aws-toolkit-vscode/pull/7235#discussion_r2077892394. 
- extract all decrypting and encrypting logic to a single location. 
- add a simple test for this logic (encrypt and decrypt are inverses). 
- refactor existing implementations. 
Used agentic chat with some tools, as well as inline chat and didn't notice a difference. If encryption were broken, I would expect this to fail immediately. 
---
> refactor(amazonq): pull out all decryption logic to one place

- packages/core/src/amazonq/webview/ui/quickActions/generator.ts
- IDE shows `Generate unit tests (python & java) for selected code` in quick actions but Q supports all the languages.
- Made change accordingly.
---
> fix(amazonq): Minor string change in quickActionCommands for /test

- packages/amazonq/test/e2e/lsp/lspInstallerUtil.ts
- packages/core/src/shared/lsp/baseLspInstaller.ts
- packages/core/src/shared/lsp/lspResolver.ts
- packages/core/src/shared/lsp/manifestResolver.ts
If a users firewall is blocking downloading the zips or reaching the manifest its not clear to the user what to do
If the user:
1. doesn't have the latest version cached
2. download of the manifest failed
3. they don't have any previous language servers downloaded
it might be a firewall issue. Rather than just `Unable to find a compatible version of the Language Server` we show a more descriptive message to the user
---
> fix(amazonq): add a more descriptive issue for firewall problems

- packages/amazonq/src/lsp/chat/messages.ts
vscode keeps track of `codewhispererImportRecommendationEnabled` inside of the `codewhisperer_serviceInvocation` event but flare doesn't
add it before emitting telemetry, since this is purely a client side feature
---
> telemetry(amazonq): align flare/vscode codewhisperer_serviceInvocation metric

- packages/core/src/shared/lsp/utils/platform.ts
These errors show up in telemetry with reason `Error`. All of the `reasonDesc` are different since they include unique PID values. This makes it hard to count/quantify how often this is happening. 
- attach a unique error code to these errors. For when node can't be run we have `FailedToRunNode`, and when the language server can't be started we have `FailedToStartLanguageServer`. 
---
> telemetry(amazonq): add an error code for when node validation fails. 

- packages/amazonq/.changes/next-release/Bug Fix-75375702-36b5-4e89-af57-4afe983a7238.json
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/util/editorContext.ts
We introduced `editorState` in data instrumentation launch. The service has a requirement of 40k character limit for the `text` field. 
Implement a check on text length. If the text length exceeds 40k characters, section 20k max characters from the left and right side of current cursor position, so the final text is always less than 40k.
validated prod endpoint inline working for files > 40k characters.
Example request id: `57bbbe65-fbe7-47fc-81c4-c65262f47ce8`
---
- License: I confirm that my contribution is made under the terms of the Apache …
> fix(nep): truncate editor state

- packages/amazonq/src/app/inline/completion.ts
- packages/amazonq/src/app/inline/inlineGeneratingMessage.ts
- packages/amazonq/src/app/inline/recommendationService.ts
- packages/amazonq/test/unit/amazonq/apps/inline/completion.test.ts
- packages/amazonq/test/unit/amazonq/apps/inline/recommendationService.test.ts
This new name more accurately represents what this class is for. It is just a util to create the "Amazon Q generating" inline message.
- Class is renamed
- File is renamed and move out of the "stateTracker" folder
---
> refactor(amazonq): rename inline "generating" message class

- packages/amazonq/test/unit/amazonq/backend_amazonq.test.ts
- packages/amazonq/test/unit/codewhisperer/commands/invokeRecommendation.test.ts
- packages/amazonq/test/unit/codewhisperer/region/regionProfileManager.test.ts
- packages/amazonq/test/unit/codewhisperer/service/inlineCompletionService.test.ts
- packages/amazonq/test/unit/codewhisperer/service/keyStrokeHandler.test.ts
- packages/amazonq/test/unit/codewhisperer/util/authUtil.test.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/test/amazonq/customizationUtil.test.ts
- packages/core/src/test/codewhisperer/startSecurityScan.test.ts
- packages/core/src/test/codewhispererChat/editor/codelens.test.ts
- packages/core/src/test/shared/featureConfig.test.ts
- packages/core/src/test/testAuthUtil.ts
There are no unit tests for the new AuthUtil on Flare LSP
* Add unit test for core AuthUtil functionality
* Create a test util for all tests where AuthUtil is needed
* Ensure all tests that interact with the AuthUtil consume the new test util
* Add destroy method to the AuthUtil class to simplify cleanup for unit tests
---
> test(amazonq): add unit tests for authUtil

- packages/core/src/codewhisperer/util/customizationUtil.ts
This reverts commit 98b0d5d1e9b1ea594e6ce0a76045072528b5fc7a.
It regress #7181 and make 7181 not working: profile will be changed, but customization will be swapped to default always.
---
> fix(amazonq): Revert refactor(amazonq): reduce extra call of listAvailableCustomization (#7242)

- packages/amazonq/.changes/next-release/Bug Fix-b873a959-2742-4440-badc-c90c6ac754c3.json
- packages/core/src/amazonq/webview/ui/quickActions/handler.ts
Inconsistent behavior when opening agent tabs (/review, /doc, etc). When the tab is reused it keeps the prompt input options visible, but when a new tab is created it doesn't.
https://github.com/user-attachments/assets/2ff7264f-f7a3-46f6-9a34-e29835768833
Set `promptInputOptions` to empty when an existing tab is reused.
---
> fix(amazonq): agent tabs open with prompt options

- packages/amazonq/src/app/inline/completion.ts
- packages/amazonq/src/app/inline/sessionManager.ts
- packages/amazonq/src/app/inline/stateTracker/inlineLineAnnotationTracker.ts
- packages/amazonq/src/app/inline/stateTracker/lineAnnotationTracker.ts
- packages/amazonq/src/app/inline/tutorials/inlineChatTutorialAnnotation.ts
- packages/amazonq/src/app/inline/tutorials/inlineTutorialAnnotation.ts
- packages/amazonq/src/inlineChat/activation.ts
- packages/amazonq/src/inlineChat/controller/inlineChatController.ts
- packages/amazonq/src/lsp/client.ts
- packages/amazonq/test/unit/amazonq/apps/inline/completion.test.ts
the tutorial trackers aren't implemented when using the language server
- re-add the inlineLineAnnotationController (inlineChatTutorialAnnotation) for adding hints with inline chat
- re-add the lineAnnotationController (inlineTutorialAnnotation) for adding the inline suggestions tutorial
in a future PR I'll fully deprecate the old trackers
---
> feat(amazonq): add tutorial trackers for lsp

- packages/amazonq/src/lsp/client.ts
clientId from `clientParams.initializationOptions?.aws?.clientInfo?.clientId` is random on every restart
use the client id from telemetry utils
---
> fix(amazonq): flare clientId changes on every instance

- packages/amazonq/src/app/inline/completion.ts
- packages/amazonq/src/app/inline/recommendationService.ts
- packages/amazonq/src/app/inline/telemetryHelper.ts
the only metric it looks like we're missing for inline on the vscode side is `codewhisperer_clientComponentLatency`
codewhisperer_clientComponentLatency uses a very similar implementation as before the only differences are:
1. codewhispererCredentialFetchingLatency is no longer relevant because the token is always injected into the language server and it doesn't need to build the client on demand like before.
- This causes the preprocessing latency to decrease, because that used to contain the time it takes to fetch the credentials
2. postProcessing latency is way lower because once we get the result vscode instantly displays it -- we no longer have control of that
example metric now:
```
2025-05-06 11:53:59.858 [debug] telemetry: codewhisperer_clientComponentLatency {
Metadata: { …
```
> telemetry(amazonq): implement codewhisperer_clientComponentLatency

- packages/amazonq/src/app/inline/completion.ts
- packages/amazonq/test/unit/amazonq/apps/inline/completion.test.ts
For some reason inline suggestions won't auto complete in function args e.g.
```
def getName(
```
or
```
def getName(firstName, 
```
if you don't provide a range
provide a range similar to what the old implementation was doing
---
> fix(amazonq): completions not showing in function args

- packages/amazonq/src/lsp/client.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
When the server crashes and then restarts again, we will emit a metric to indicate it crashed.
When querying look for: `metadata.metricName: languageServer_crash` & `metadata.id: AmazonQ`
---
> telemetry(amazonq): Emit metric on server crash

- packages/amazonq/src/app/inline/completion.ts
- packages/amazonq/test/e2e/inline/inline.test.ts
- packages/core/src/codewhisperer/models/model.ts
- packages/core/src/shared/telemetry/exemptMetrics.ts
inline tests don't work with the language server
- I removed the `${name} invoke on unsupported filetype` test because you can't trigger inline completions at all for unsupported filetypes (vscode doesn't allow it -- you need to specify file extentions)
- hack: I have no way to spy on actual inline completions so I added a global variable that lets the tests know when recommendations are being generated :/. This allows us to wait for before accepting/rejecting requests
- hack: codewhisperer_perceivedLatency, codewhisperer_serviceInvocation don't have the result field set in flare so it causes a lot of noisy logs. TODO add the result field there
---
- Your code changes must meet the …
> test(amazonq): update inline tests for flare

- packages/core/src/amazonqFeatureDev/session/sessionState.ts
FileCreationFailed exceptions are displayed as UnknownException in telemetry. This exception is new and we want to separate this out from other unknown exceptions.
Return API service error with `FileCreationFailedException`
---
> telemetry(amazonq): expose FileCreationFailed exceptions

- packages/amazonq/src/lsp/client.ts
- the extension version is a fix string.
- update extension version
Before change: the userAgent field received in RTS.
```
aws-sdk-nodejs/2.1692.0 darwin/v23.10.0 AWS-Language-Servers AWS-CodeWhisperer/0.1.0 AmazonQ-For-VSCode/0.0.1 Visual-Studio-Code---Insiders/1.100.0-insider ClientId/c342ab45-6aba-4118-b48c-44dcedb10a78 promise
```
After change: Verified via local testing of sending request to RTS.
```
aws-sdk-nodejs/2.1692.0 darwin/v23.10.0 AWS-Language-Servers AWS-CodeWhisperer/0.1.0 AmazonQ-For-VSCode/testPluginVersion Visual-Studio-Code---Insiders/1.100.0-insider ClientId/c342ab45-6aba-4118-b48c-44dcedb10a78 promise
```
--- …
> fix(lsp): update extension version

- packages/amazonq/src/lsp/chat/messages.ts
- packages/core/src/amazonq/webview/ui/quickActions/generator.ts
- No logs is being emitted for  telemetry events.
- Adding logs if telemetry events are emitted.
---
> fix(amazonq): adding logs for the agentic chat telemetry events

- packages/amazonq/src/app/inline/recommendationService.ts
- packages/amazonq/test/unit/amazonq/apps/inline/recommendationService.test.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/shared/utilities/functionUtils.ts
- packages/core/src/test/shared/utilities/functionUtils.test.ts
When typing a decent amount of text in quick succession, the language server will get throttled in its requests to the backend. This is because we send a request for recommendations on every key stroke, causing the language server to make a request on each key stroke. This is rightfully getting throttled by the backend.
- The ideal behavior is that we only make a request to the language server, and thus to the backend, when typing stops. Therefore, this is an ideal use case for `debounce`. However, we need to extend debounce slightly outlined below. 
- Apply `debounce` to the recommendations such that we wait 20 ms after typing stops before fetching the results. 
- By applying this at the recommendation level, none of the inline latency metrics are affected. 
-Let f be some debounced …
> fix(amazonq): debounce inline suggestion requests.

- package-lock.json
- package.json
New telemetry metrics were [added](https://github.com/aws/aws-toolkit-common/pull/1023) to aws-toolkit-common
Consume latest version of aws-toolkit-common package
---
> deps: bump @aws-toolkits/telemetry to 1.0.318

- packages/amazonq/src/app/inline/completion.ts
- packages/amazonq/src/app/inline/recommendationService.ts
- packages/amazonq/test/unit/amazonq/apps/inline/completion.test.ts
- packages/amazonq/test/unit/amazonq/apps/inline/recommendationService.test.ts
- packages/core/src/codewhisperer/models/constants.ts
Adding logging statements to the top level is extremely noisy, since that part still triggers on each key stroke. This could also improve latency since any computation at the top-level will be redone on each keystroke. 
- move the debounce up a layer. 
- remove outdated tests, since the debounce util already has tests for all this logic. 
- added new tests for new behavior. 
- I tested this side-by-side with previous version and didn't notice a difference. 
--- …
> refactor(amazonq): move debounce to top level. 

- packages/amazonq/.changes/next-release/Bug Fix-9b0e6490-39a8-445f-9d67-9d762de7421c.json
- packages/amazonq/test/unit/codewhisperer/util/editorContext.test.ts
- packages/amazonq/test/unit/codewhisperer/util/runtimeLanguageContext.test.ts
- packages/core/src/codewhisperer/util/editorContext.ts
- packages/core/src/codewhisperer/util/runtimeLanguageContext.ts
VS Code treats each cell in a notebook as a separate editor.  As a result, when building the left- and right-contexts for the completion from the current editor, we were limited to just the current cell, which might be very small and/or reference variables and functions defined in other cells.  That meant that completions never used the context of other cells when making suggestions, and were often _very_ generic. https://github.com/aws/aws-toolkit-vscode/issues/7031
The `extractContextForCodeWhisperer` function now checks if it is being called in a cell in a Jupyter notebook.  If so, it collects the surrounding cells to use as context, respecting the maximum context length.  During this process, Markdown cells have each line prefixed with a language-specific comment character.
---
- …
> fix(amazonq): Previous and subsequent cells are used as context for completion in a Jupyter notebook

- packages/amazonq/src/lsp/client.ts
Add importAdder and userWrittenCode configuration to inline with LSP
---
> feat(amazonq): import userWrittenCode configuration for inline with lsp

- packages/amazonq/src/lsp/chat/activation.ts
At the startup of the extension, the customization that a user already decided previously was not being pushed to flare.
The only time we would push the customization to flare was if the customization was changed.
Otherwise everything else works as expected.
On startup, push the customization to flare (if it already exists)
---
> fix(amazonq): push customizations on startup

- package-lock.json
- package.json
- Added new metrics in aws-toolkit-common package: https://github.com/aws/aws-toolkit-common/pull/1024
- Consume latest version of aws-toolkit-common package
---
> deps: bump @aws-toolkits/telemetry to 1.0.319

- packages/amazonq/src/lsp/chat/activation.ts
- packages/amazonq/src/lsp/client.ts
- packages/amazonq/src/lsp/config.ts
- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/index.ts
After some testing there is the edge case of cached Customizations/Profiles not being sent on startup.
This PR fixes that so that they are sent to the LSP on extension startup, when expected.
See each individual commit as they are isolated changes.
---
> fix(amazonq): Customization/Profiles not being sent to LSP on startup

- packages/amazonq/src/app/inline/completion.ts
- packages/amazonq/src/app/inline/recommendationService.ts
- packages/amazonq/test/unit/amazonq/apps/inline/completion.test.ts
There are two edge cases discovered during testing that warrant some tests. 
1. the language server will respond without a range, causing the result to not be rendered. 
2. the language server COULD respond with a `StringValue` instead of string (currently doesn't, but valid in the type contract). 
- add tests for these cases, and do minor refactoring to make this easier. 
---
> test(amazonq): add tests for edge cases

- packages/amazonq/test/unit/codewhisperer/service/referenceLogViewProvider.test.ts
- packages/core/src/codewhisperer/service/referenceLogViewProvider.ts
References are not added to the reference log at the bottom. The root cause is that the reference tracker log is expecting CW shaped references, but we are passing "Flare" shaped ones. 
- Update the reference log to standardize the shape of incoming references. 
- added unit test.
- Verified e2e:
https://github.com/user-attachments/assets/620f6f3d-1205-405e-96a2-322d5e8220c4
- 
---
> fix(amazonq): standardize reference type for reference log

- packages/amazonq/.changes/next-release/Bug Fix-2471c584-3904-4d90-bb7c-61efff219e43.json
- packages/amazonq/.changes/next-release/Bug Fix-91d391d4-3777-4053-9e71-15b36dfa1f67.json
- packages/amazonq/src/lsp/auth.ts
- packages/amazonq/src/lsp/chat/activation.ts
- packages/amazonq/src/lsp/client.ts
- packages/amazonq/src/lsp/config.ts
- packages/core/src/auth/index.ts
See individual commits for isolated changes
We were seeing the following errors from the Q Language Server on startup:
- `Amazon Q Profile is not selected for IDC connection type`
- `Amazon Q service is not signed in`
We needed to do 2 solutions, each is a separate commit (see their message). There were also some minor refactors.
In short:
- The Auth bearer token MUST be sent to the Q LSP before Profile is sent. We were not doing this and it was causing an error
- When sending the Auth to the Q LSP, the startUrl MUST be included in the request or else it would fail. We thought we were sending it but based on the logs prefixed with `UpdateBearerToken` it showed`sso` did not contain the startUrl
---
- Treat all work as PUBLIC. Private `feature/x` branches will not be squash-merged at …
> fix(amazonq): Profile needing to be selected on server restart

- packages/amazonq/src/app/inline/completion.ts
- packages/amazonq/test/unit/amazonq/apps/inline/completion.test.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/shared/utilities/index.ts
When manually invoking inline suggestions, it is possible for the backend to still not reply with results. Since the user took an action to invoke this, we should let them know when it fails. 
- add a message with same timeout as original implementation. 
- added unit test. 
- E2E flow demo (notice it doesn't trigger on automatic failures, but does on manual invoke failures):
https://github.com/user-attachments/assets/7cf34178-e91e-4d38-8875-1259c5552a53
--- …
> feat(amazonq): show a message when no suggestions are found on manual invoke

- packages/amazonq/package.json
- packages/amazonq/src/commands.ts
- packages/amazonq/src/util/clearCache.ts
- packages/core/package.nls.json
We need a way to clear `globalState` since it looks like some users are getting in to a bad corrputed state where things stop working.
Uninstalling the extension does not clear state, it is intentionally designed that way by vscode, as we don't want to wipe states on extension updates.
This creates a new command "Amazon Q: Clear extension cache" which clears the cache and reloads the window.
There is safety modal which pops up right before clearing after the command is selected.
---
- License: I confirm that my contribution is made under the …
> feat(amazonq): Command to clear extension cache

- packages/amazonq/src/app/inline/completion.ts
- packages/amazonq/src/app/inline/sessionManager.ts
- packages/amazonq/test/unit/amazonq/apps/inline/completion.test.ts
- packages/amazonq/test/unit/amazonq/apps/inline/recommendationService.test.ts
The current implementation overwrites the `editor.action.inlineSuggest.showPrevious` and `editor.action.inlineSuggest.showNext` commands to swap out the inlineProvider. These custom overwrites cause a few issues:
- forces us to maintain a ton of state [leads to bugs, some of which were observed in bug bash].
- causes the suggestions to "refresh" when going through them since we are re-instantiating the provider on "scrolls". 
- doesn't natively support "accept word"/"accept line". 
- Remove the overwrite, remove reliance of `session` state. 
- Simplify implementation to use native VSC commands. 
- Scrolling through suggestions now works and doesn't "refresh". 
- Accept Word/Accept Line now work properly. 
- Significantly faster to scroll through suggestions. 
- Inline Reference Codelense …
> fix(amazonq): inline suggestion scrolling now uses built-in VSC commands. 

- packages/amazonq/.changes/next-release/Bug Fix-636765f1-2278-4a2d-b512-7c63ecc2ce67.json
- packages/core/src/amazonqGumby/chat/controller/controller.ts
/transform was unnecessarily prompting users for their target JDK paths in some cases.
Remove the prompt.
---
> fix(amazonq): remove target JDK path prompt

- packages/amazonq/src/util/clearCache.ts
- packages/amazonq/test/unit/amazonq/apps/inline/recommendationService.test.ts
- packages/core/src/auth/auth2.ts
- packages/core/src/auth/sso/cache.ts
- packages/core/src/codewhisperer/util/authUtil.ts
The current cache file watcher is triggered on every `*.json` file change in the cache folder. When migrating old auth SSO connections to Flare, there is a race condition. If the old connection is migrated (meaning that the old token file deletes) after the file watcher is instantiated, the file watcher `delete` event will trigger and logout the user
The Flare auth cache file watcher will only listen to events for the Flare token .json file. This way, when we delete the old token .json file, there is no logout event triggered
---
- License: I …
> fix(amazonq): fix cache watcher on token file to avoid logout after SSO connection migration

- packages/amazonq/src/extension.ts
- packages/core/src/codewhisperer/activation.ts
Commands `updateReferenceLog` and `refreshStatusBar` are not yet registered when invoked in `AuthUtil`
Register the commands before `activateAmazonqLsp`, instead of in `activateCodeWhisperer`
---
> fix(amazonq): register commands before invocation

- packages/amazonq/test/unit/codewhisperer/util/editorContext.test.ts
- packages/core/src/codewhisperer/client/service-2.json
- packages/core/src/codewhisperer/client/user-service-2.json
- packages/core/src/codewhisperer/util/editorContext.ts
In order to coordinate the new https://github.com/aws/language-servers/pull/1348 change, GenerateCompletions requests would start expecting the `fileUri` field to be set.
Add `fileUri` to FileContext
---
> feat(codewhisperer): add fileUri to FileContext

- packages/amazonq/.changes/next-release/Feature-09ac6888-de83-418b-afa7-d1cc58f687b2.json
- packages/amazonq/src/lsp/lspInstaller.ts
- packages/core/src/shared/lsp/utils/platform.ts
- AgenticChat will add a grepSearch tool which depends on ripgrep binary
- Add ripgrep path and make it executable
---
> feat(chat): Add ripgrep path and make it executable

- packages/core/src/codewhisperer/util/runtimeLanguageContext.ts
Team decides to remove `.acds` and only allow `.abap` as the file extension of `abap` language
---
> config(amazonq): remove .acds file extension from abap language

- packages/core/src/codewhisperer/region/regionProfileManager.ts
When ListRegionProfile call throttles for a subset of regions, we currently do not throw, but instead return the available profiles in the regions where the call succeeded. However, if that list is empty (no profiles in that region), we return an empty list. This breaks the UI, and causes a state that is not recoverable
Throw an error in the scenario where availableProfiles is empty. This triggers a retry state in the UI, making the state recoverable.
--- …
> fix(amazonq): throw if no region profiles are available

- packages/amazonq/src/util/clearCache.ts
Sometimes users MAY modify the LSP cache dir for reasons like development.
We have a feature to clear cache, but right now it does not clear the LSP cache.
Now we will additionally clear the LSP cache when the user runs the command `Amazon Q: Clear extension cache`
---
> refactor(clearcache): Delete the LSP cache dir

- packages/core/src/auth/sso/clients.ts
In ticket V1761315147 it was being reported that createToken could take 9 seconds. This would mean that the SSO client API request would time out
Bump the timeout to 12 seconds as specified in V1761315147
---
> fix(sso): increase SSO timeout

- packages/amazonq/test/unit/codewhisperer/region/regionProfileManager.test.ts
- packages/core/src/codewhisperer/region/regionProfileManager.ts
The cached/persisted Q Developer Profile selection is stored as a map of `{connectionID: RegionProfile}`, where `connectionID` is a `randomUUID`. When migrating to Flare auth, we move away from the concept of a connectionID, and we do not have access to the latest ID of a user. The result is that we cannot restore the user's last selected region profile, and always need users who update versions to make a profile selection. 
To handle this more gracefully, we will:
* Use regionProfile if matching auth profile name (existing logic)
* If no match, check if there is only a single RegionProfile stored in lastUsed. If so, use that one
* If no match, and multiple RegionProfiles are stored in lastUsed cache, make user select
Unit tests added
---
- Treat all work as PUBLIC. Private `feature/x` …
> fix(amazonq): Handle developer profile migration more gracefully

- packages/amazonq/test/unit/codewhisperer/util/authUtil.test.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/shared/logger/logger.ts
Auth migration to LSP is not handled gracefully when a user downgrades and upgrades to auth on LSP multiple times, causing users to be logged out if they upgrade a second time
In the auth migration script, call the LSP identity server to check if a token is available. If the token is available, don't migrate the auth connection. If no token is available, migrate.
Added unit tests for the case.
---
> fix(amazonq): handle existing Flare connection when migrating SSO connections

- packages/amazonq/test/unit/codewhisperer/region/regionProfileManager.test.ts
- packages/amazonq/test/unit/codewhisperer/util/authUtil.test.ts
- packages/core/src/auth/sso/clients.ts
- packages/core/src/codewhisperer/region/regionProfileManager.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/shared/logger/logger.ts
Merge feature/flare-mega branch so the latest version is available for testing Flare preprod
---
> fix(amazonq): Merge feature/flare-mega

- packages/amazonq/.changes/next-release/Removal-951c2b6a-c6ce-45df-95d0-381ca51b935f.json
- packages/amazonq/src/app/chat/activation.ts
The workspace LSP has been merged into the Amazon Q LSP (Flare). There is no need to keep the non-flare workspace LSP, it will consume both CPU and memory once it starts to index. This will make non agentic chat experience not having `@file` or `@workspace ` but at this point we want customers to use agentic chat. As such CPU and memory usage problem is of higher priority.
remove: disable workspace lsp
---
> fix(workspace): remove non-flare workspace lsp

- packages/core/src/codewhisperer/util/telemetryHelper.ts
Users are seeing `telemetry: invalid Metric: "codewhisperer_clientComponentLatency" emitted without the `result` property, which is always required. Consider using `.run()` instead of `.emit()`, which will set these properties automatically. See https://github.com/aws/aws-toolkit-vscode/blob/master/docs/telemetry.md#guidelines`
Add result attribute when emitting the metric
---
> fix(telemetry): add result parameter when emitting telemetry

- packages/core/src/amazonq/webview/ui/quickActions/handler.ts
When users have a /transform tab open, then open a new tab and type /transform, we open the existing /transform tab but don't show a notification like IntelliJ does.
Add notification in top right.
---
> fix(amazonq): show notification when user switches tabs

- buildspec/release/50githubrelease.yml
Problem:
The `browser_download_url` in https://api.github.com/repos/aws/aws-toolkit-vscode/releases/latest points to a random artifact depending on whether toolkit or amazonq was the last release to publish.
Solution:
Modify the deploy logic to only set "latest" for "amazonq", never "toolkit".
---
> ci: only publish amazonq as "latest" release

- packages/amazonq/src/lsp/chat/messages.ts
`chatOptionsUpdate` notifications are not forwarded to UI.
This is needed to persist previously selected model in new tabs.
Forward `chatOptionsUpdate` notifications to UI
Related PR: https://github.com/aws/language-server-runtimes/pull/530
---
> feat(lsp): forward chatOptionsUpdate to ui

- package-lock.json
- package.json
- packages/amazonq/package.json
- packages/amazonq/src/app/inline/EditRendering/displayImage.ts
- packages/amazonq/src/app/inline/EditRendering/svgGenerator.ts
- packages/amazonq/src/app/inline/completion.ts
- packages/amazonq/test/unit/amazonq/apps/inline/recommendationService.test.ts
- packages/core/package.json
- packages/core/src/shared/settings-toolkit.gen.ts
- packages/core/src/shared/vscode/setContext.ts
- packages/toolkit/package.json
1. Added a feature flag `amazonqLSPNEP` for NEP.
Configure the settings.json like:
```
"aws.experiments": {
"amazonqLSP": true,
"amazonqLSPInline": true, // optional: enables inline completion from flare
"amazonqLSPChat": true, // optional: enables chat from flare
"amazonqLSPNEP": true, // optional: enables next edit prediction
},
```
2. Fixed some UI/UX bugs:
- Color theme matches IDE light/dark theme
- Cursor move to the end of edit once accepted
- Added conditions to the accept/reject commands so tab/esc works outside of NEP context. 
---
- …
> NEP: feature flag & bug fix

- packages/amazonq/src/lsp/chat/messages.ts
- packages/core/src/shared/utilities/vsCodeUtils.ts
LSP server can't open URLs, because the LSP client does not correctly handle `ShowDocumentParams.external` requests.
LSP spec: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#showDocumentParams
When `ShowDocumentParams.external` is true, open the URL in a web browser instead of as a editor document.
Also: avoid PII in openUrl metric.
---
> fix(lsp): handle ShowDocumentParams.external

- packages/amazonq/.changes/next-release/Feature-d6714581-799f-49dc-bb63-f08d461e9bde.json
- packages/amazonq/src/lsp/activation.ts
- packages/amazonq/src/lsp/chat/webviewProvider.ts
- packages/amazonq/src/lsp/config.ts
- packages/amazonq/src/lsp/lspInstaller.ts
- scripts/lspArtifact.ts
- scripts/package.ts
The LSP start failure because 
1. node binary is blocked because of firewall
2. chat UI js file is blocked because of firewall or anti virus
3. lsp js file is broken post download because of security mechanism
1. Bundle the JS LSP with the amazonq package.
2. Re-start LSP wth the bundled JS files if and only if downloaded LSP does not work!
3. Use the VS Code vended node to start the bundled LSP.
This was tested by 
1. Generated the vsix, which is now 20MB.
2. Disconnect from internet, remove local LSP caches
3. Install the new vsix
4. Webview of chat should load.
also tested by manually corrupting the aws-lsp-codewhisperer.js
Limitations:
1. The indexing library function will not work because it is missing.
2. rg is not in the bundle
Ref: …
> feat(amazonq): Bundle LSP with the extension as fallback.  

- packages/amazonq/package.json
- packages/amazonq/src/extension.ts
- packages/core/package.nls.json
- packages/core/src/shared/index.ts
- packages/core/src/shared/logger/logger.ts
- packages/core/src/shared/settings-amazonq.gen.ts
- packages/core/src/shared/utilities/proxyUtil.ts
Amazon Q For VS Code has lost proxy support following the release of Agentic Chat (1.63.0) due to a fundamental architectural change. Previously, API calls were executed in VS Code's Extension Host process, which automatically handled proxy settings. Now, these calls are made through a separate Flare Language Server process that doesn't inherit VS Code's proxy configurations.
Key Issues:
- VS Code's built-in proxy handling doesn't propagate to the Flare process
- Environment variables required for proxy support aren't being passed to the Flare Language Server
- Enabled Flare's experimental proxy support by setting `EXPERIMENTAL_HTTP_PROXY_SUPPORT=true`. See: https://github.com/aws/language-server-runtimes/blob/main/runtimes/docs/proxy.md
- Implemented `ProxyUtil` class to configure proxy …
> fix(amazonq): Add proxy configuration support with SSL Cert Validation

- packages/amazonq/.changes/next-release/Feature-57661731-6180-4157-a04b-d3a8b50aa1a8.json
- packages/amazonq/src/lsp/client.ts
- we are missing the `mcp: true` flag
- add `mcp: true` flag to enable mcp server support
---
> feat(amazonq): add MCP server support

- packages/amazonq/.changes/next-release/Feature-57661731-6180-4157-a04b-d3a8b50aa1a8.json
- packages/amazonq/src/lsp/client.ts
MCP Servers feature is broken in alpha manifest and is causing regression to chat.
- reverting the feature flag to enable MCP
---
> revert: revert to "feat(amazonq): add MCP server support (#7451)"

- packages/amazonq/src/app/inline/EditRendering/displayImage.ts
- packages/amazonq/src/app/inline/EditRendering/imageRenderer.ts
- packages/amazonq/src/app/inline/EditRendering/svgGenerator.ts
> feat: pass isInlineEdit as true to LogInlineCompletionSessionResultsParams for NEP

- packages/amazonq/.changes/next-release/Bug Fix-9b0e6490-39a8-445f-9d67-9d762de7421c.json
- packages/amazonq/.changes/next-release/Bug Fix-bb976b5f-7697-42d8-89a9-8e96310a23f4.json
- packages/core/src/codewhispererChat/controllers/chat/controller.ts
> deps(amazonq): remove unused code in Flare inline migration

- scripts/lspArtifact.ts
String comparison says "1.11.0" < "1.9.0". We should compare numbers.
---
> fix(amazonq): bundle flare version comparison using numbers 

- packages/core/src/shared/utilities/proxyUtil.ts
- Start seeing "unable to get local issuer certificate" since 1.72, affecting server-side workspace context in Flare
- Removing  openSSL and the Experiment flag set to true works fine.
- This should fix the current regression.
---
> fix(amazonq): Fixing issue with unable to get local issuer certificate

- package-lock.json
- package.json
- Added new metrics in aws-toolkit-common package: https://github.com/aws/aws-toolkit-common/pull/1054
- Consume latest version of aws-toolkit-common package
---
> deps: bump @aws-toolkits/telemetry to 1.0.324

- packages/core/src/codewhisperer/commands/startTransformByQ.ts
- packages/core/src/codewhisperer/models/constants.ts
Some text about how we do transformations is confusing to users.
Update text.
---
> fix(amazonq): update text for STV2 feature

- packages/amazonq/src/app/inline/completion.ts
- packages/amazonq/src/app/inline/recommendationService.ts
- packages/amazonq/src/app/inline/sessionManager.ts
In the inline flare branch, the typeahead experience is bad because even when user typed matching characters after seeing a suggestion, we are still re-fetching the new suggestions, which causes the cached suggestion to disappear and new suggestion re-appear.
Use the previous suggestion from last invocation if what user typed matches the suggestion prefix.
https://github.com/user-attachments/assets/8c039a80-edd9-4687-9f2c-fb646707b79c
This also aligns the experience in prod plugins without Flare inline.
--- …
> fix(amazonq): improve typeahead experience

- .github/workflows/node.js.yml
- `windows-2019` image is being deprecated on 6/30/2025
- See here: https://github.com/actions/runner-images/issues/12045
- update to use `windows-latest` image for github CI
---
> ci: use windows-latest image for github CI

- docs/lsp.md
The documentation was incomplete for setting up the LSP locally for testing. 
Added the required information.
---
> docs(amazonq): Improved the local LSP setup documentation with more information

- packages/core/src/shared/lsp/utils/platform.ts
- large repo has OOM exception when init
```
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
1: 0xb9bbf0 node::Abort() [Amazon Q Helper (Workspace Context)]
2: 0xaa27ee  [Amazon Q Helper (Workspace Context)]
3: 0xd734a0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [Amazon Q Helper (Workspace Context)]
4: 0xd73847 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [Amazon Q Helper (Workspace Context)]
5: 0xf50c55  [Amazon Q Helper (Workspace Context)]
6: 0xf6312d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [Amazon Q Helper (Workspace Context)]
7: 0xf3d81e v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath( …
```
> fix(amazonq): increase node memory size to 8G

- packages/amazonq/src/lsp/chat/messages.ts
- Missing `chatOptions` like mcp icon, history icon, export icon in tab bar and  quickActions like `/clear` and `/help` in the input menu.
- The `CHAT_OPTIONS` command is sometimes not properly received by the handleInboundMessage function in the chat client.
- The root issue was a race condition in the communication between the VSCode extension and the webview component. When the `onDidResolveWebview` event fired, the code was immediately trying to send a message to the webview, but in some cases, the webview wasn't fully ready to receive messages yet, causing the message to be lost.
- If user opens a large repository(example: [JetBrains](https://github.com/aws/aws-toolkit-jetbrains)) in any IDE(VSC or JB or VS or Ecllipse), IDE takes some time to do indexing.
- This delay of indexing is …
> fix(amazonq): chatOptions are missing in q chat

- packages/amazonq/.changes/next-release/Bug Fix-541466ab-cebc-4f12-bbc6-6cdedad9eafe.json
- packages/amazonq/src/lsp/chat/messages.ts
- Right now, Q does not open the history tabs automatically after VSC Reload or restart
- This PR fixes the above issue
---
> fix(amazonq): Q opens the history tabs automatically after plugin launch

- packages/core/src/shared/lsp/utils/platform.ts
- packages/webpack.base.config.js
With the introduction of agentic chat, Amazon Q Developer now runs its language server (Flare) in a separate Node.js process outside of VS Code's control. This creates network connectivity issues in corporate environments:
The Node.js process doesn't inherit VS Code's proxy settings, causing connection failures behind corporate proxies
Corporate SSL certificates aren't trusted by the Node.js process, resulting in certificate validation errors
Proxy authentication (including Integrated Windows Authentication) doesn't work automatically
These issues prevent Amazon Q Developer from functioning in enterprise environments with strict network policies.
This PR enables the Flare Language Server to inherit VS Code's Electron proxy settings and certificate trust store:
Added a …
> fix(amazonq): allow node to inherit proxy settings from VSC

- packages/core/package.nls.json
- packages/core/src/stepFunctions/activation.ts
- packages/core/src/stepFunctions/constants/webviewResources.ts
- packages/core/src/stepFunctions/executionDetails/executionDetailProvider.ts
- packages/core/src/stepFunctions/workflowStudio/types.ts
- packages/core/src/stepFunctions/workflowStudio/workflowStudioEditorProvider.ts
- packages/toolkit/.changes/next-release/Feature-ce02287b-d043-4d71-8589-685903fb5ee7.json
- packages/toolkit/package.json
Execution Details cannot be launched / View by Execution ARN isn't supported
- Added aws.stepfunctions.viewExecutionDetailsByExecutionARN command to package.json and package.nls.json
- Implemented `ExecutionDetailProvider` to open execution details in a dedicated webview panel
- Added ExecutionDetailProvider.openExecutionDetails call to activation.ts for viewExecutionDetailsByExecutionARN command
---
> feat(stepfunctions): add View by Execution ARN command and provider

- packages/core/src/codewhisperer/region/regionProfileManager.ts
…
- to reduce # of service calls within short time duration and result in throttling error thrown
- 
---
> fix(amazonq): add jitter for validation call of profiles 

- packages/amazonq/.changes/next-release/Bug Fix-a06c2136-a87a-41af-9304-454bc77aaecc.json
- packages/amazonq/src/extension.ts
- packages/core/src/shared/lsp/utils/platform.ts
- packages/core/src/shared/utilities/proxyUtil.ts
Previous fix was separate from the existing proxyUtil.ts handling.
Logic has been moved form platform.ts to proxyUtil.ts to have all process.env handling in one place. 
also added fetching for NO_PROXY settings from vsc
---
> fix(amazonq): migrate process.env proxy setting handling to proxyUtil.ts

- packages/core/src/shared/utilities/proxyUtil.ts
Recently added the `process.env.NODE_OPTIONS = '--use-system-ca'`. This caused issues when downloading the LSP:
```
2025-06-26 14:48:04.633 [error] amazonqLsp.lspClient: failed to run basic "node -e" test (exitcode=9): PID 48382: [/Users/tsmithsz/Library/Caches/aws/toolkits/language-servers/AmazonQ/1.16.0/servers/node -e console.log("ok " + process.version)]
2025-06-26 14:48:04.634 [warning] telemetry: invalid Metric:  "languageServer_setup" emitted with missing fields: id
2025-06-26 14:48:04.634 [debug] telemetry: languageServer_setup {
Metadata: {
missingFields: 'id',
metricId: '4fb062f4-ac6d-4da5-8c36-a32425d58260',
traceId: '95908c07-fa81-49a9-9356-45f2f3739888',
parentId: '840adbe9-3e9b-47e5-86a2-970f10e53828',
languageServerSetupStage: 'launch',
duration: '900',
result: 'Failed', …
```
> fix(amazonq): Remove incompatible Node 18 flag

- packages/core/src/testLint/gitSecrets.test.ts
> fix(amazonq): revert unneeded changes

- packages/amazonq/src/app/inline/EditRendering/diffUtils.ts
- packages/amazonq/src/app/inline/EditRendering/displayImage.ts
- packages/amazonq/src/app/inline/EditRendering/imageRenderer.ts
- packages/amazonq/src/app/inline/EditRendering/svgGenerator.ts
- packages/amazonq/src/app/inline/completion.ts
- packages/amazonq/test/unit/app/inline/EditRendering/diffUtils.test.ts
- packages/amazonq/test/unit/app/inline/EditRendering/imageRenderer.test.ts
Trigger inline suggestion via acceptance for EDITS
Also clean up addedCharacterCount and deletedCharacterCount implementation
---
> feat(amazonq): trigger inline suggestion via acceptance for EDITS

- packages/amazonq/.changes/next-release/Bug Fix-8d48cfa7-278f-4b38-8121-0738bb0841b1.json
- packages/amazonq/src/app/inline/completion.ts
Before we migrate inline completion to LSP, we do not auto trigger when user delete code.
In the `provideInlineCompletion` callback that VS Code invokes, we check if this document has a very recent deletion event, if there is, do not make auto trigger. This is a best effort estimate of recent deletion because the `provideInlineCompletion` callback does not indicate the source input that triggered itself, we have to listen to document deletion events that almost happens at the same time.
---
- License: I confirm that my contribution is made …
> fix(amazonq): do not trigger inline completion when user delete code

- packages/amazonq/.changes/next-release/Bug Fix-da82b914-41c2-4003-8691-73f9ec62cc68.json
- packages/amazonq/src/app/inline/completion.ts
- packages/amazonq/src/app/inline/recommendationService.ts
- packages/amazonq/test/unit/amazonq/apps/inline/recommendationService.test.ts
As inline completion was moved to Flare LSP, one previous design of inline completion: Show re-auth prompt when access denied, was not migrated. 
Prompt re-authenticate if auto trigger failed with expired token.
This is not new code, I just borrowed old code path. Link is added in the comments. 
---
> fix(amazonq): Prompt re-authenticate if auto trigger failed with expired token

- packages/core/src/codewhisperer/region/regionProfileManager.ts
VS Code extension startup was delayed by ~5 seconds due to profile validation logic that used jittered API calls to avoid rate limiting. This cross-validation checked if restored profiles were still valid but caused poor user experience during plugin loading.
Related PR:
- https://github.com/aws/aws-toolkit-vscode/pull/7534
Removed the profile cross-validation code in restoreRegionProfile() to eliminate startup delays. This trades off immediate detection of admin-deleted profiles (rare edge case) for faster plugin loading that benefits all users daily.
Generate plugin build and tested. Saw latency improvements of ~2-3s in plugin load time
--- …
> fix(amazonq): remove profile validation

- packages/amazonq/src/lsp/client.ts
- Model selection feature flag is not enabled.
- Sent `modelSelection: true` as part of awsClientCapabilities.
---
> fix(amazonq): Adding modelSelection feature flag

- packages/amazonq/src/app/inline/EditRendering/displayImage.ts
- packages/amazonq/test/unit/app/inline/EditRendering/displayImage.test.ts
> fix(amazonq): nep path asynchronous ops are not awaited

- packages/amazonq/src/app/inline/EditRendering/displayImage.ts
adding isInlineEdit to LogInlineCompletionSessionResultsParams for EDITS telemetry: 
https://github.com/aws/language-servers/blob/main/server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts#L910
---
> feat(amazonq): adding isInlineEdit to LogInlineCompletionSessionResultsParams for EDITS telemetry

- package-lock.json
- packages/amazonq/.changes/next-release/Feature-a93aa3b3-83cd-45bb-81d9-4ad25e783300.json
- packages/amazonq/src/lsp/chat/messages.ts
- packages/amazonq/src/lsp/client.ts
- packages/core/package.json
WebView emit event to open system file dialog to use the VSC api to open file dialog, and the event need to be handled by extension
1. Register the request between WebView and language server by adding `case OPEN_FILE_DIALOG`
2. Add handling for event when language server request to open system file dialog, which is defined in `languageClient.onRequest(ShowOpenDialogRequestType.method, async (params: ShowOpenDialogParams)`
---
> feat(amazonq): support select images as context

- packages/core/src/feedback/vue/submitFeedback.ts
- packages/core/src/feedback/vue/submitFeedback.vue
- packages/core/src/test/feedback/commands/submitFeedbackListener.test.ts
Feedback forms were coming empty and with no useful data. Mostly a UI change.
Added char limits and starting templates so that we can get meaningful messages out of this.
---
> fix(amazonq): improve feedback experience and min char limit

- packages/amazonq/src/app/inline/EditRendering/displayImage.ts
> config(amazonq): nep only auto trigger on acceptance if there is nextToken

- packages/core/src/lambda/commands/editLambda.ts
- packages/core/src/lambda/commands/uploadLambda.ts
- packages/core/src/lambda/utils.ts
- packages/core/src/test/lambda/commands/editLambda.test.ts
- packages/core/src/test/lambda/utils.test.ts
- packages/toolkit/.changes/next-release/Bug Fix-70bf4138-7b79-4fc1-8e6a-0637f0058da6.json
fixes #7618
Introduced in #7601 is a bug where choosing to upload a Lambda function from a directory would not allow the user to actually select the directory. In the directory selection window, the button to select is disabled. This was an inadvertent change when adding new functionality.
Revert the breaking change. In addition to switching `canSelectFolders` to `true` and `canSelectFiles` to `false`, I have reverted the other changes in the upload flow that were added in the original PR. This is because these changes added another flow to the upload modal that doesn't fit with all the other added functionality, and just increases the complexity of the code without much benefit. Because this was the only place that used the `lambdaEdits` array from the `utils`, I removed that as well. …
> fix(lambda): Revert update to function upload directory selection wizard

- packages/amazonq/src/app/inline/EditRendering/displayImage.ts
- packages/amazonq/src/app/inline/completion.ts
- packages/amazonq/src/app/inline/recommendationService.ts
- packages/amazonq/src/app/inline/sessionManager.ts
> fix(amazonq): should pass nextToken to Flare for Edits on acceptance without calling provideInlineCompletionItems

- aws-toolkit-vscode.code-workspace
- packages/amazonq/.changes/next-release/Bug Fix-91380b87-5955-4c15-b762-31e7f1c71575.json
- packages/amazonq/package.json
- packages/amazonq/src/app/inline/recommendationService.ts
- packages/amazonq/src/app/inline/sessionManager.ts
- packages/amazonq/src/lsp/client.ts
Previous the pagination API call was blocking and it does not render until all pagination API calls are done.
Without a force refresh of the inline ghost text, paginated response will not be rendered.
1. Keep doing paginated API call in the background.
2. Refresh the ghost text of inline completion when user press Left or Right key to add paginated responses by calling VS Code native commands.
Note that we can do such refresh below whenever the pagination session finish but that will result in inline completion flickering, hence it is better to do it on demand when Left or Right is pressed.
```
await vscode.commands.executeCommand('editor.action.inlineSuggest.hide')
await vscode.commands.executeCommand('editor.action.inlineSuggest.trigger')
```
---
- Treat all work as PUBLIC. Private …
> fix(amazonq):  Render first response before receiving all paginated inline completion results

- packages/core/src/auth/activation.ts
After Remote - SSH to a sagemaker space via VS Code, the amazon Q plugin cannot be loaded for the following error.
```
2025-07-10 17:23:52.976 [info] ExtensionService#_doActivateExtension amazonwebservices.aws-toolkit-vscode, startup: false, activationEvent: 'onStartupFinished'
2025-07-10 17:23:57.478 [error] Activating extension amazonwebservices.amazon-q-vscode failed due to an error:
2025-07-10 17:23:57.478 [error] Error: command 'sagemaker.parseCookies' not found
at mYe.n (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1855:1328)
at mYe.executeCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1855:1260)
```
After …
> fix(sagemaker): fix sagemaker.parseCookies cmd not found

- P261194666.md
- packages/amazonq/src/lsp/auth.ts
- packages/amazonq/src/lsp/chat/messages.ts
- packages/amazonq/src/lsp/client.ts
- packages/core/package.json
- packages/core/scripts/lint/testLint.ts
- packages/core/src/auth/auth.ts
- packages/core/src/shared/lsp/utils/platform.ts
- packages/core/src/testLint/eslint.test.ts
Amazon Q for VSCode fails to authenticate in SageMaker environments after v1.62.0. The extension moved from directly calling the Q service using AWS SDK clients to using the aws-lsp-codewhisperer service (LSP). While the legacy
implementation had specific handling for SageMaker IAM credentials, the new LSP-based implementation only supports SSO token authentication.
The breaking change occurred in commit 938bb376647414776a55d7dd7d6761c863764c5c which enabled three experiment flags by default, moving the extension from the core implementation to the LSP implementation that lacks IAM credential
support.
This PR adds IAM authentication support to the Amazon Q LSP client for SageMaker environments by:
1. Setting the USE_IAM_AUTH environment variable when running in SageMaker to signal the …
> fix(amazonq): Q chat stopped using IAM creds in the Amazon Q v1.63.0 release

- packages/amazonq/package.json
- packages/amazonq/src/lsp/chat/commands.ts
- packages/amazonq/src/lsp/chat/webviewProvider.ts
- packages/amazonq/src/lsp/client.ts
- packages/core/src/shared/vscode/setContext.ts
> fix: reverts for keyboard shortcuts feature

- packages/core/src/test/lambda/utils.test.ts
Duplicate code linter was finding errors in the `utils` tests for Lambda
Remove duplicate code (now relying on already existing `mockLambda`)
---
> test(lambda): Remove duplicate code in Lambda tests

- packages/amazonq/src/app/inline/recommendationService.ts
- packages/amazonq/src/app/inline/sessionManager.ts
> fix(amazonq): should check if partialResultToken is empty for EDITS trigger on acceptance

- packages/amazonq/.changes/next-release/Feature-a0140eaf-abe8-43ae-9ea1-f0b1afcbc962.json
- packages/amazonq/src/lsp/client.ts
- Removing feature flag for Code Review tool
- Removed change logs for the above too
---
> fix(amazonq): remove feature flag for CodeReview tool, update change logs

- packages/amazonq/src/lsp/client.ts
- packages/amazonq/src/lsp/rotatingLogChannel.ts
- packages/amazonq/src/test/rotatingLogChannel.test.ts
Amazon Q extension lacks persistent logging to disk, making it difficult to debug issues after they occur. Customers have no easy way to get them to us. This commit is one in a series to enable 1 click log retrieval on the IDE.
Old log on std out starting point:
You can search now for 'Logging with' in the terminal and you will find the path of the log. The log is getting stored at per workspace level.
Implement RotatingLogChannel for disk-based logging
- Add file-based logging with automatic rotation (5MB per file)
- Maintain maximum of 4 log files to prevent disk space issues
- Clean up log files on VS Code shutdown
- Add comprehensive unit tests for logging functionality
File Log Sample:
---
- Treat all work as PUBLIC. Private `feature/x` branches will not be squash-merged at release …
> feat(amazonq): write logs to disk with  rotation & cleanup

- packages/amazonq/src/app/inline/EditRendering/imageRenderer.ts
applyDiff may fail and the consequence is the `newCode` to update become empty string, thus deleting all users' code.
https://github.com/user-attachments/assets/6524bae2-1374-452d-bb4e-3ec6f865c258
https://github.com/user-attachments/assets/75d5ed7a-6940-4432-a8d9-73c485afb2c3
---
> fix(amazonq): skip edit suggestion if applyDiff fail

- packages/core/src/auth/activation.ts
- packages/core/src/test/auth/activation.test.ts
This pr: https://github.com/aws/aws-toolkit-vscode/pull/7670 didn't been covered by the unit test
Add unit test for the activation initialize method.
---
> fix(test): add unit test for auth activation initialize method

- packages/amazonq/src/extension.ts
- packages/core/src/codewhisperer/commands/basicCommands.ts
- packages/core/src/codewhisperer/region/regionProfileManager.ts
- packages/core/src/shared/featureConfig.ts
- packages/core/src/shared/utilities/resourceCache.ts
Performance analysis of the Amazon Q extension revealed significant startup latency issues, with the extension taking over 9 seconds to fully initialize. A detailed timing analysis identified several critical bottlenecks in the startup sequence, particularly around resource caching, LSP initialization, and feature configuration. These bottlenecks negatively impact user experience during IDE startup and extension activation.
- **File:** [extension.ts](https://github.com/aws/aws-toolkit-vscode/pull/7673/files#diff-864d212c3cfe80d9fd863446a284ac78f32841f4a2473fc045eb44da2125ef34)
- Call `activateAmazonqLsp` for everyone unless that person is using AL2 and they do not have glibc patch
- Remove `activateInlineCompletion` since it is for the old inline completion
- **File:** …
> fix(amazonq): Reduce plugin start-up latency

- packages/amazonq/src/extension.ts
- packages/amazonq/src/lsp/rotatingLogChannel.ts
LSP logs were being forwarded to the disk log. 
Added extension logs also to set that would get printed on the disk.
---
> feat(amazonq): added logs of toolkit to the same disk file too

- packages/amazonq/src/lsp/rotatingLogChannel.ts
- packages/amazonq/src/test/rotatingLogChannel.test.ts
When replacing the overall logger, log level gets overwritten. 
Customized the logger level.
---
> fix(amazonq): match rotating logger level

- package-lock.json
- packages/amazonq/.changes/1.84.0.json
- packages/amazonq/.changes/next-release/Bug Fix-45aef014-07f3-4511-a9f6-d7233077784c.json
- packages/amazonq/.changes/next-release/Bug Fix-91380b87-5955-4c15-b762-31e7f1c71575.json
- packages/amazonq/.changes/next-release/Feature-9e413673-5ef6-4920-97b1-e73635f3a0f5.json
- packages/amazonq/CHANGELOG.md
- packages/amazonq/package.json
- scripts/package.ts
[chore: removing unwanted files](https://github.com/aws/aws-toolkit-vscode/commit/bd2d5fe8b8d5f126631fbcb187a6f8c5b19373bb)
---
> fix(amazonq): removing unwanted files

- packages/core/src/lambda/remoteDebugging/ldkController.ts
This change has no customer facing impact.
duration -> sessionDuration (correct)
Previously this metrics is wrongly recorded to duration and got overwritten by the metrics wrapper
Change to use sessionDuration correctly
---
> telemetry(lambda): nit to use sessionDuration correctly for debug duration

- packages/core/src/auth/utils.ts
- packages/core/src/test/credentials/auth.test.ts
- packages/toolkit/.changes/next-release/Feature-852d6637-ac3c-4b7f-b846-649d23da87e3.json
For customers using SSO with IAM Identity Center, the select connection quickpick looks like this:
In this screenshot, I have 2 profiles configured to be using IdC, as well as 2 profiles using access keys at the bottom. In addition, there are the `PowerUserAccess` IAM credentials that are associated with my SSO profiles, although it's not clear which one. It is also not clear to me that in order to be properly set up to use Toolkit features, I must select the IAM credential sourced from the IdC. This is backed up by data from the recently launched Console to IDE project (mostly launched in #7601) that shows that when entering the quickpick through the introduced URI handler, many customers fail with an error of `CredentialsProviderError: Profile <profile identifier> was not found.` This …
> feat(auth): Display second quickpick for SSO linked IAM profiles

- packages/amazonq/src/lsp/chat/messages.ts
Log folder was getting highlighted instead of the file. 
Pointed to the file itself instead of the folder.
---
> fix(amazonq): point to the log file inside the folder

- packages/amazonq/package.json
- packages/core/package.nls.json
- packages/core/src/codewhisperer/activation.ts
- packages/core/src/codewhisperer/commands/basicCommands.ts
Needed to add a new drop down show logs button at the top. Having just a web view button would lead to this functionality not work incase the LS doesnt work.
Added the same show logs functionality in the top drop down.
---
> feat(amazonq): added show logs to the top menu bar dropdown

- packages/amazonq/package.json
Added another code setting for show logs.
Added another code setting for show logs.
---
> fix(amazonq): disable SageMakerUnifiedStudio for show logs

- packages/amazonq/src/app/inline/completion.ts
- packages/amazonq/src/app/inline/recommendationService.ts
When a paginated response is in flight, but the user already accepted or rejected a completion, the subsequent paginated requests should be cancelled.
This PR also fixes the `codewhispererTotalShownTime` being negative issue by using performance.now() across all timestamp computation. 
This is not a user facing change.
---
> fix(amazonq): early stop pagination requests when user decision is made

- packages/amazonq/.changes/next-release/Bug Fix-7261a487-e80a-440f-b311-2688e256a886.json
- packages/amazonq/package.json
- packages/amazonq/src/app/inline/completion.ts
- packages/amazonq/src/app/inline/recommendationService.ts
- packages/amazonq/src/app/inline/sessionManager.ts
- packages/amazonq/src/lsp/client.ts
- packages/amazonq/test/unit/amazonq/apps/inline/completion.test.ts
1. when intelliSense suggestion is surfaced, inline completion are not shown even if provideInlineCompletionItems have returned valid items.
2. provideInlineCompletionItems is unnecessarily debounced at 200ms which creates a user perceivable delay for inline completion UX. We already blocked concurrent API call. 
3. The items returned by provideInlineCompletionItems, even though they match the typeahead of the user's current editor (they can be presented), sometimes VS Code decides to not show them to avoid interrupting user's typing flow. This not show suggestion decision is not emitted as API callback or events, causing us to report the suggestion as Rejected but it should be Discard.
1. Force the item to render by calling `editor.action.inlineSuggest.trigger` command.
3. Remove the …
> fix(amazonq): Faster and more responsive auto trigger UX. 

- packages/core/src/auth/providers/sharedCredentialsProvider.ts
- packages/core/src/test/auth/providers/sharedCredentialsProvider.test.ts
AWS Toolkit version 3.47.0 introduced a regression where profiles using `source_profile` for role chaining fail to authenticate when the source profile uses SSO credentials. Users get an "InvalidClientTokenId: The security token included in the request is invalid" error.
The issue was introduced in commit 6f6a8c2 (Feb 13, 2025) which refactored the authentication code to remove deprecated AWS SDK dependencies. The new implementation in `makeSharedIniFileCredentialsProvider` method incorrectly assumed that the source profile would have static credentials (aws_access_key_id and aws_secret_access_key) directly in the profile data.
When the source profile uses SSO, these static credentials don't exist in the profile data - they need to be obtained by calling the SSO service first.
The fix …
> fix(auth): Fix for SSO Profile Role Chaining Regression

- packages/amazonq/src/lsp/chat/messages.ts
In VSC, we check that the metric name must be in [aws-toolkit-common](https://github.com/aws/aws-toolkit-common) before emitting the metric.
Therefore when we want to add a new metric, the current process is:
1. Add new metric in aws-toolkit-common
2. Wait for version to increment (~1 hour)
3. Bump up toolkit-common version in VSC repo
4. Wait for next VSC release (up to 1 week)
Only after steps 1-4, will we be actually emitting the new metric.
JB, VS, and Eclipse do not have this dependency, and assume Flare is the source of truth for metrics
In VSC, Flare is now the source of truth for metrics instead of depending on aws-toolkit-common
--- …
> telemetry(amazonq): flare is now source of truth for metrics

- packages/core/src/shared/lsp/utils/setupStage.ts
- packages/core/src/shared/telemetry/service-2.json
- packages/core/src/shared/telemetry/telemetryClient.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
Need to differentiate internal vs external customers.
add startUrl to more metrics.
---
> fix(amazonq): add startUrl to more metrics

- packages/amazonq/src/app/inline/EditRendering/svgGenerator.ts
- packages/core/src/shared/utilities/diffUtils.ts
The unifiedDiff from suggestionResponse is outdated due to the change of context, resulting to the wrong line getting highlighted while rendering.
Calculate the addedLines and removedLines using the current code content and new code suggestion.
---
> fix(amazonq): use current file content to calculate highlighted ranges

- buildspec/linuxTests.yml
if token is not available or the target branch is not master, then coverage upload command will report failure
additionally, coverage upload failure should not fail the build
suppress failure
---
> ci: don't fail build if coverage should not be reported/failure

- packages/amazonq/src/app/inline/recommendationService.ts
- packages/amazonq/src/util/timeoutUtil.ts
During the inline completion migration to Flare, the timeout handling of inline completion API was lost. It was there in earlier versions. The IDE -> Flare call is a local network call that should have a timeout. 
Add the inline completion call with timeout back. See https://github.com/aws/aws-toolkit-vscode/blob/amazonq/v1.74.0/packages/core/src/codewhisperer/util/commonUtil.ts#L21
---
> fix(amazonq): bring back timeout to local LSP call inline completion

- packages/amazonq/src/lsp/chat/messages.ts
- packages/amazonq/src/lsp/client.ts
- packages/core/src/codewhisperer/commands/startSecurityScan.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/service/diagnosticsProvider.ts
- packages/core/src/codewhisperer/service/securityIssueProvider.ts
- packages/core/src/test/codewhisperer/mergeIssuesDisplayFindings.test.ts
Need to enable and support findings coming in from the displayFindings tool
Also - Agentic scans are supposed to use the CodeAnalysisScope of AGENTIC, which needed to be added
Set feature flag for displayFindings to be true
Listen for displayFindings messageId from FLARE similarly to how is being done for CodeReview tool.
Treat displayFindings findings and CodeReview findings separately, so they do not overwrite one another.
---
> feat(amazonq): enable displayFindings tool

- packages/amazonq/src/extensionNode.ts
- packages/amazonq/src/inlineChat/provider/inlineChatProvider.ts
- packages/amazonq/test/unit/codewhisperer/util/authUtil.test.ts
- packages/core/src/auth/auth2.ts
- packages/core/src/codewhisperer/ui/codeWhispererNodes.ts
- packages/core/src/codewhisperer/util/authUtil.ts
- packages/core/src/login/webview/vue/backend.ts
- packages/core/src/login/webview/vue/login.vue
- packages/core/src/shared/featureConfig.ts
- packages/core/src/shared/globalState.ts
- packages/core/src/shared/settings.ts
- packages/core/src/test/amazonq/utils.ts
- packages/core/src/test/testAuthUtil.ts
UI and error message no longer compatible after adding IAM credentials authflow
IAM Access Key needs manual input every time a client log in
This is part of https://github.com/aws/aws-toolkit-vscode/pull/7507 and is built on top of https://github.com/aws/aws-toolkit-vscode/pull/7659.
---
> fix(auth): fix UI and error message bug, disable inline chat for IAM, autofill access key id

- package.json
- packages/amazonq/test/e2e_new/amazonq/tests/inline.test.ts
- packages/amazonq/test/e2e_new/amazonq/utils/generalUtils.ts
The inline test cannot be run consecutively with other tests in our suite since it switches its focus to the editorView and textEditorView. Each time the inline test is run, a new driver was launched with caused a new VSCode instance to instantiate. 
The `package.json` should only target the `.test.js` files. Right now it targets all .js files in the directory.
The `writeToTextEditor` function is faulty since it is wrongly indexed due to its element not being accessed before counting and referencing its indices within code.
Implemented an `after` function which correctly switches back to our webviewView (AmazonQ). Added the true inline test into the suite and fixed driver problem.
Changed the path referenced in the `package.json` to `.test.js` files. 
Fixed the `writeToTextEditor` …
> fix(amazonq): Inline test after function addition, writeToTextEditor fix, and package.json pathing fix

- packages/core/src/stepFunctions/commands/downloadStateMachineDefinition.ts
- packages/core/src/stepFunctions/executionDetails/executionDetailProvider.ts
- packages/core/src/stepFunctions/executionDetails/handleMessage.ts
- packages/core/src/stepFunctions/messageHandlers/types.ts
- packages/core/src/stepFunctions/utils.ts
- packages/core/src/stepFunctions/vue/executeStateMachine/executeStateMachine.ts
- packages/core/src/test/stepFunctions/utils.test.ts
Currently the New Execution and Edit State Machine Buttons in Execution Details don't work
New Execution button now opens a new input webview
Edit State Machine launches Workflow Studio 
Added message handling for new execution and edit state machine
Refactoring in utils
---
> feat(stepfunctions): Handling newExecution and editStateMachine 

- packages/core/src/test/amazonqGumby/transformationJobHistory.test.ts
> test(amazonq): minor test fix

- packages/amazonq/src/app/inline/EditRendering/displayImage.ts
- packages/amazonq/src/app/inline/completion.ts
> send firstCompletionDisplayLatency in multiple reject cases

- packages/core/src/amazonqGumby/chat/controller/controller.ts
- packages/core/src/codewhisperer/commands/startTransformByQ.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/service/transformByQ/transformFileHandler.ts
- packages/core/src/codewhisperer/service/transformByQ/transformationHistoryHandler.ts
- packages/core/src/codewhisperer/service/transformByQ/transformationHubViewProvider.ts
- packages/core/src/codewhisperer/service/transformByQ/transformationResultsViewProvider.ts
- packages/core/src/test/amazonqGumby/transformationJobHistory.test.ts
Job history-related code is scattered throughout various files, making it difficult to review and understand.
Centralize existing history functions in a new file and add helper functions to declutter transformation flow. Update and simplify unit tests accordingly.
---
> refactor(amazonq): reorganize transformation history code

- packages/amazonq/src/app/inline/EditRendering/displayImage.ts
discard when it's not yet shown.
reject when user's typing and makes the diff invalid.
---
> fix(amazonq): discard/reject edit suggestion if it isn't valid

- .github/workflows/release.yml
- .github/workflows/setup-release-candidate.yml
The AWS Toolkit VSCode project lacked a streamlined release candidate workflow. Creating release candidates would require manual branch creation and version management.
Added automated release candidate support:
- Created `.github/workflows/setup-release-candidate.yml `- Workflow to create RC branches with automatic version bumping
- Supports `Major/Minor/Patch/Custom` version increments
- Reads and increments both `toolkit` and `amazonq` package versions independently
- Creates date-based RC branches (`rc-YYYYMMDD`)
- Commits version changes and pushes the RC branch
- Updated `.github/workflows/release.yml` - Added support for `release/* ` branches
- Automatically creates `rc-*` prefixed releases for release candidate branches
- Proper release naming for RC artifacts
This enables a clean …
> ci: create GitHub releases for release candidate branches

- .github/workflows/setup-release-candidate.yml
The release candidate workflow was failing with "protected branch update failed" error because the default `GITHUB_TOKEN ` did not exist.
Updated the workflow to use `RELEASE_CANDIDATE_BRANCH_CREATION_PAT` instead of `GITHUB_TOKEN` in the checkout step.
---
> chore: use PAT token in RC workflow

- .github/workflows/release.yml
- .github/workflows/setup-release-candidate.yml
The prerelease workflow is configured to run on branches matching release/*. The RC creation workflow previously created branches like `rc-YYYYMMDD` instead of `release/rc-YYMMDD`, which did not match the trigger pattern, meaning the prerelease workflow was never invoked automatically.
As it stands now any team member with write access can perform workflow_dispatch injection.
Update the RC creation workflow to create branches in the format `release/rc-YYYYMMDD` instead of `rc-YYYYMMDD`, ensuring they match the prerelease workflow’s `release/*` branch trigger and are picked up for prerelease builds.
Sanitize the input fields via Github environment variables
---
- Your code changes must meet …
> config: update rc branch naming and sanitize input 

- packages/core/src/shared/utilities/proxyUtil.ts
There is an issue we suspect is related to the recent support we added for proxy auto-discovery on this GitHub issue: https://github.com/aws/aws-toolkit-vscode/issues/7878
Disabling the experimental proxy support
---
> fix(amazonq): disable experimental proxy

- packages/core/src/shared/utilities/proxyUtil.ts
There is an issue we suspect is related to the recent support we added for proxy auto-discovery on this GitHub issue:
https://github.com/aws/aws-toolkit-vscode/issues/7878
Disabling the experimental proxy support
---
---
- Your code changes must meet the guidelines in [CONTRIBUTING.md](https://github.com/aws/aws-toolkit-vscode/blob/master/CONTRIBUTING.md#g …
> fix(amazonq): disable experimental proxy (#7904)

- packages/amazonq/src/app/inline/completion.ts
Bug: When inline suggestion is active but user types a character that does not match the typeahead, this typing event triggered a inline completion API call that eventually did not manage to display suggestion on screen, which eventually reported as rejected completions.
Previously, before Flare migration, we had this design:
https://github.com/aws/aws-toolkit-vscode/blob/amazonq/v1.74.0/packages/amazonq/src/app/inline/activation.ts#L108
Auto trigger will be disabled if at that moment the suggestion is visible. 
Under the previous design, the first character that does not match the typeahead will not make a new auto trigger, it simply rejects the current inline completion. 
This PR is to bring back the old design.
It is not customer facing, hence no change log.
---
- Treat all work as …
> fix(amazonq): do not auto trigger if the ongoing typeahead does not match

- packages/amazonq/test/e2e_new/amazonq/helpers/pinContextHelper.ts
- packages/amazonq/test/e2e_new/amazonq/tests/pinContext.test.ts
We were faced with the problem that when all our tests and helpers were merged together, and then run as a full suite, we saw errors with the pinContext.test.ts file. Namely, it was targeting a background overlay that had identical css components to the pinContext overlay. This is problematic since our entire suite relies on these css components, and even test-ids were not differentiated. Additionally, our pinContextHelpers used sleep functions in the range of 100-3000 ms which is naturally arbitrary values.   
We implement the XPath css selectors that are used within Selenium to identify the pinContext Buttons by text, not css classes or ids. This drastically decreases the length and complexity of our helpers while also eliminating the need for sleep functions other than a sleep(0) …
> fix(amazonq): XPath Selector for pinContextHelpers and fixing PinContext ability to run in full test suite

- packages/amazonq/package.json
- packages/core/package.nls.json
- packages/core/src/shared/settings-amazonq.gen.ts
- packages/core/src/shared/utilities/proxyUtil.ts
The proxy and certificate auto-discovery code occasionally causes issues and there is a need to allow control of this by users.
Add a checkbox in settings that allow customers to control whether they want Amazon Q's proxy and certificate auto-discovery turned on.
Experimental proxy util used once setting enabled:
Standard proxy util  used once setting disabled:
---
> fix(amazonq): add flag in settings for controlling experimental proxy support

- docs/lsp.md
- `npm link` is not working for some people when connecting local language-server-runtimes
- `npm pack` has been working better for people, hence updating documentation to include the `npm pack` approach
---
> docs(amazonq): update docs for connecting local language-server-runtimes

- packages/amazonq/package.json
Keyboard shortcuts for fixCode and generateUnitTests functions are not working on Windows VSC, although they function correctly on Mac
The current shortcuts conflict with Windows reserved keyboard combinations.
Current Shortcuts (Windows):
- fixCode: Windows + Alt + Y
- generateUnitTests: Windows + Alt + T
New Shortcuts (Windows only):
- fixCode: Windows + Alt + H
- generateUnitTests: Windows + Alt + N
This approach results in different letter keys for the same functions across platforms:
- generateUnitTests: 'T' on Mac, 'N' on Windows
- fixCode: 'Y' on Mac, 'H' on Windows
---
- Your code changes must meet the guidelines in [CONTRIBUTING.md](https://github.com/aws/aws-toolkit-vscode/blob/mas …
> fix(amazonq): windows keyboard shortcut for fixCode and generateUnitTests

- package-lock.json
- packages/amazonq/.changes/1.92.0.json
- packages/amazonq/.changes/next-release/Feature-5e9de7e7-cf7b-4ed3-824f-062b82b3f4b9.json
- packages/amazonq/.changes/next-release/Feature-bac44cae-5e68-4192-bbdc-2aaf4cdc0e7c.json
- packages/amazonq/.changes/next-release/Feature-dad6607e-513c-4355-9655-e80fd2da9ec2.json
- packages/amazonq/CHANGELOG.md
- packages/amazonq/package.json
> fix(amazonq): bump version to 1.93.0-SNAPSHOT

- packages/amazonq/src/lsp/client.ts
- Adding a feature flag for VSC terminal integration to avoid regressions in other IDE's and in past VSC Amazon Q plugin versions.
- Reference language server pr: https://github.com/aws/language-servers/pull/2186
---
> feat(amazonq): Adding feature flag for VSC terminal integration.

- packages/core/src/codewhisperer/commands/invokeRecommendation.ts
- packages/core/src/codewhisperer/commands/onAcceptance.ts
- packages/core/src/codewhisperer/commands/onInlineAcceptance.ts
- packages/core/src/codewhisperer/models/constants.ts
- packages/core/src/codewhisperer/service/classifierTrigger.ts
- packages/core/src/codewhisperer/service/inlineCompletionItemProvider.ts
- packages/core/src/codewhisperer/service/inlineCompletionService.ts
- packages/core/src/codewhisperer/service/keyStrokeHandler.ts
- packages/core/src/codewhisperer/service/recommendationHandler.ts
- packages/core/src/codewhisperer/service/recommendationService.ts
- packages/core/src/codewhisperer/tracker/codewhispererCodeCoverageTracker.ts
- packages/core/src/codewhisperer/util/commonUtil.ts
- packages/core/src/codewhisperer/util/editorContext.ts
- packages/core/src/codewhisperer/util/globalStateUtil.ts
- packages/core/src/codewhisperer/util/supplementalContext/codeParsingUtil.ts
- packages/core/src/codewhisperer/util/supplementalContext/crossFileContextUtil.ts
- packages/core/src/codewhisperer/util/supplementalContext/rankBm25.ts
- packages/core/src/codewhisperer/util/supplementalContext/supplementalContextUtil.ts
- packages/core/src/codewhisperer/util/supplementalContext/utgUtils.ts
- packages/core/src/codewhisperer/util/telemetryHelper.ts
Cherry pick files from https://github.com/aws/aws-toolkit-vscode/pull/7480/files
---
> fix(amazonq): add back inline completion code files - part 1

- packages/core/src/codewhisperer/util/telemetryHelper.ts
> fix(amazonq): add telemetryHelper back

- packages/amazonq/src/lsp/client.ts
- packages/core/src/codewhisperer/service/inlineCompletionService.ts
- packages/core/src/codewhisperer/util/supplementalContext/crossFileContextUtil.ts
> fix(amazonq): removing duplicate refreshStatusBar declare method

- packages/amazonq/test/unit/codewhisperer/util/telemetryHelper.test.ts
add back test file for telemetryHelper.ts
Test file for https://github.com/aws/aws-toolkit-vscode/pull/7975
Ref: https://github.com/aws/aws-toolkit-vscode/pull/7906
---
> test(amazonq): add back test file for telemetryHelper.ts

- packages/core/src/codewhisperer/service/transformByQ/transformApiHandler.ts
- packages/core/src/codewhisperer/service/transformByQ/transformationResultsViewProvider.ts
Better to first open the diff.patch for user to see, then parse it and apply it, so that if it is malformed, it is first visible to user.
Open diff.patch first.
---
> fix(amazonq): show diff.patch first, then parse it

- packages/core/src/sagemakerunifiedstudio/activation.ts
- packages/core/src/test/sagemakerunifiedstudio/activation.test.ts
- packages/core/src/test/sagemakerunifiedstudio/auth/smusAuthenticationProvider.test.ts
**Description**
We were seeing intermittent issues where sometimes the context was being returned as undefined.
Setting it at the start of the activation to ensure the the context is available always.
**Motivation**
Bug fix
**Testing Done**
Tested manually locally.
---
> fix(smus): Fix potential race condition bug on getting context

- package-lock.json
- packages/toolkit/.changes/3.74.0.json
- packages/toolkit/.changes/next-release/Feature-11b05698-7406-4ccd-afd2-a22d3adbfa67.json
- packages/toolkit/.changes/next-release/Feature-385a8d57-8874-4f90-a7e8-50f058f43c62.json
- packages/toolkit/.changes/next-release/Feature-b799e933-2707-4cd8-9217-6cdd46ee2b4a.json
- packages/toolkit/CHANGELOG.md
- packages/toolkit/package.json
This merges the released changes for rc-20250910 into main. MCM-134160906
---
> build(amazonq): merge release candidate version rc-20250910

- packages/amazonq/.changes/next-release/Bug Fix-da0e805d-faab-4274-b37a-943c7263e42b.json
- packages/amazonq/src/lsp/auth.ts
- packages/core/src/auth/auth.ts
- packages/core/src/auth/connection.ts
- packages/core/src/auth/credentials/store.ts
- packages/core/src/auth/index.ts
- packages/core/src/shared/utilities/functionUtils.ts
- packages/core/src/test/shared/utilities/functionUtils.test.ts
- IAM credentials is not updating in Sagemaker instances due to incorrect comparison logic which prevents credential refresh and hence users cant interact with Q chat after the initial expiration time
- 
- Add custom comparator logic and method to properly compare credentials by their actual values (accessKeyId,
secretAccessKey, sessionToken) instead of string comparison
- Added 60-second expiration buffer to credential validation. similar to SSO token logic [here](https://github.com/aws/aws-toolkit-vscode/blob/c3685274fc4e09e72c98db4c43b7959634bc63b0/packages/core/src/auth/sso/model.ts#L158) for grace-time
- Tested by building a debug artefact on a SMUS CodeEditor instance and verified q chat is triggering refresh credentials
- ```npm run package && npm run test``` succeeded
- …
> fix(amazonq): fix iam credential update logic to use custom comparator and added buffer time in cred validation

- packages/core/src/codewhisperer/commands/invokeRecommendation.ts
- packages/core/src/codewhisperer/service/inlineCompletionService.ts
- packages/core/src/codewhisperer/service/keyStrokeHandler.ts
This reverts commit 00ffeb376ea1db1187999ee6e35ea9bcd0432b86.
---
> revert(amazonq): Revert flush usertriggerDecision event on keystroke or manual trigger 8085

- packages/core/src/sagemakerunifiedstudio/auth/providers/smusAuthenticationProvider.ts
- packages/core/src/sagemakerunifiedstudio/explorer/nodes/redshiftStrategy.ts
- packages/core/src/sagemakerunifiedstudio/shared/smusUtils.ts
- packages/core/src/sagemakerunifiedstudio/shared/telemetry.ts
- packages/core/src/shared/telemetry/vscodeTelemetry.json
- packages/core/src/test/sagemakerunifiedstudio/auth/smusAuthenticationProvider.test.ts
- packages/core/src/test/sagemakerunifiedstudio/shared/smusUtils.test.ts
The project account id and region was missing from data connection and space action telemetry.
The project account id and region are added to data connection and space action telemetry.
Telemetry for a cross-account example:
```
2025-09-23 15:42:29.674 [debug] telemetry: smus_login {
Metadata: {
metricId: 'fdbf85ac-a093-4ab9-ac47-add57a5901cc',
traceId: '7ee3db34-3f9b-41b7-aa16-824290fa0719',
parentId: '5c66c1e2-09ba-4308-8e28-a47bfc4acdda',
smusDomainId: 'dzd_64o7tjjv1cm9gp',
awsRegion: 'us-east-2',
smusDomainAccountId: '730335272067',
duration: '24121',
result: 'Succeeded',
awsAccount: 'not-set'
},
Value: 1,
Unit: 'None',
Passive: false
}
2025-09-23 15:42:32.466 [debug] telemetry: smus_accessProject {
Metadata: {
metricId: 'cc75867d-cb7c-4392-b7d7-cda1f7ba627c',
traceId: …
```
> telemetry: add project account id and region

- packages/core/src/awsService/iot/commands/attachPolicy.ts
- packages/core/src/awsService/iot/commands/createCert.ts
- packages/core/src/awsService/iot/explorer/iotPolicyNode.ts
- packages/core/src/awsService/iot/explorer/iotPolicyVersionNode.ts
- packages/core/src/test/awsService/iot/commands/createCert.test.ts
- packages/core/src/test/awsService/iot/commands/deletePolicy.test.ts
- packages/core/src/test/awsService/iot/explorer/iotCertFolderNode.test.ts
- packages/core/src/test/awsService/iot/explorer/iotCertificateNode.test.ts
- packages/core/src/test/awsService/iot/explorer/iotPolicyFolderNode.test.ts
- packages/core/src/test/awsService/iot/explorer/iotPolicyNode.test.ts
- packages/core/src/test/awsService/iot/explorer/iotPolicyVersionNode.test.ts
- packages/core/src/test/awsService/iot/explorer/iotThingFolderNode.test.ts
- packages/core/src/test/awsService/iot/explorer/iotThingNode.test.ts
AWS SDK V2 is EOL.
Migrate IoT imports to V3
---
> refactor(iot): migrate to aws-sdk v3 part 2

- package-lock.json
- packages/core/package.json
- packages/core/src/awsService/redshift/wizards/connectionWizard.ts
- packages/core/src/shared/clients/secretsManagerClient.ts
AWS SDK V2 is at EOL.
Migrate SecretsManager client to V3
---
> refactor(secretsmanager): migrate to aws sdk v3
